nnstreamer/nnstreamer

- tests/tizen_capi/unittest_tizen_sensor.cc
Fix coverity issues caused by uncaught exceptions from GTest.
Coverity CID 1123680, 1123739 : Error handling Issues (UNCAUGHT_EXCEPT)
tests/tizen_capi/unittest_tizen_sensor.cc
> [Coverity] Fix uncaught exceptions CID: 1123680, 1123739

- ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
Fix Coverity issues caused by unitialized pointer field in tensor_filter_cpp.cc
> [Coverity] Fix unitialized pointer field CID: 1123873

- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
- ext/nnstreamer/tensor_filter/tensor_filter_python.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- gst/nnstreamer/tensor_filter/tensor_filter_custom.c
- tests/nnstreamer_filter_extensions_common/meson.build
- tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
Added check for setInputDim/reloadModel in unittests
Framework functions are reset at close in python subplugin
Framework functions are updated based on available in model file in custom subplugin
Resolves  #1959
> [subplugin/ext] Added support for setInputDim/reloadModel in unittests

- api/capi/include/nnstreamer-capi-private.h
- api/capi/src/nnstreamer-capi-single.c
- api/capi/src/nnstreamer-capi-util.c
We need to rewrite this change to make it more general.
This fixes:
1. if there are multiple files for a model, we need to check the
whole list at once, not indivisually.
2. add VIVANTE detection and verification methods.
> Tizen/CAPI: Workaround to support VIVANTE

- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
TensorFlow Lite models whose I/O is of type `kTfLiteInt8` are rejected,
requiring an I/O wrapper (`Quantize` operators). As signed 8-bit
integers are preferred in TensorFlow's quantization specifications [1],
this patch alleviates the need for an I/O wrapper to run strictly
`kTfLiteInt8`-type models.
Resolves: #2105 
[1] https://www.tensorflow.org/lite/performance/quantization_spec
> [Wait for #2119] Support models with signed 8-bit integer I/O

- api/capi/src/nnstreamer-capi-single.c
Return not-supported if the property is not available.
> [Api/Single] change return value

- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
From GStreamer 1.16, package name and plugin name should be
matched; otherwise, gstreamer will blacklist the plugin.
This fixes blacklisting issue with GStreamer 1.16 and
Tizen-sensor-framework plugin.
> Hotfix: prepare GStreamer 1.16

- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
check supporting datatypes with meson_option and return the valid  datatype
> [TFLite] check supporting datatype

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
- ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc
- ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
- ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
- ext/nnstreamer/tensor_filter/tensor_filter_openvino.hh
- ext/nnstreamer/tensor_filter/tensor_filter_python.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
- gst/nnstreamer/tensor_filter/tensor_filter_custom.c
- meson.build
- tests/meson.build
- tests/tizen_capi/unittest_tizen_capi.cc
- Updated the list of HWs supported with openvino. Providing "true:npu" should also work along with "true:npu.movidius". Providing specific movidius accelerator works. However, just providing a generic npu should also default to movidius.
- Added list of supported accelerators as backend for caffe2
- Added list of supported backend accelerators for python extension of tensor filter
- Added supported list of hardware for tensorflow's tensor filter's extension. Added corresponding unit-tests using single API
- Added supported accelerators for custom filters and its unit-tests with single API
- Added unit-tests for nnfw supported accelerators with single API
- Added supported accelerators for ncsdk2 extension and corresponding unit-tests with single API
- Added supported accelerators for …
> Support accelerator backends for tensor filter extensions

- packaging/run_unittests_binaries.sh
- tests/meson.build
- tests/nnstreamer_filter_reload/meson.build
- tests/nnstreamer_filter_reload/runTest.sh
- tests/nnstreamer_repo_dynamicity/meson.build
- tests/nnstreamer_repo_dynamicity/runTest.sh
Many unittest binaries are built and located in build/tests
All these binaries located in build/tests (not in recursive folders) are
run all at once with nnstreamer.spec by running all the files in build/tests (line 388)
However, some of these binaries are not supposed to run directly (they requires extra params),
and are properly run and tested with their shell scripts run with ssat (repo and reload unittests)
This PR moves the repo and reload unittest generated binaries into appropriate subfolders
to avoid running these binaries directly and avoid unnecessary warnings
> [unittest/build] Fix location of unittests binaries

- gst/nnstreamer/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- tests/nnstreamer_sink/unittest_sink.cc
Support probing for tensor filter subplugins framework of version 1
Various ToDos' have been added which will be supported soon.
Related Issue: #2116
> [filter] Support probing for tensor filter subplugins version 1 @open sesame 03/02 03:40

- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
Move unnecessary computations out of the critical path to maximize invoke performance for tensorflow-lite.
See also: #2134 
> [tflite] optimize invoke critical path

- api/capi/src/nnstreamer-capi-single.c
There are two for loops trying to compare the unsigned integer, num_tensors, with a signed integet iterator in the single C-API wrapper code. This patch fixes them.
> [CAPI/Single] Do not compare unsigned integer with signed one

- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
- ext/nnstreamer/tensor_source/tensor_src_tizensensor.h
fix invalid element name in src-tizensensor source.
> [Doc] invalid element name

- tests/cpp_methods/meson.build
- tests/meson.build
- tests/nnstreamer_filter_extensions_common/meson.build
Some of the unit-tests depend on gtest
However, their dependency is not checked leading to build failure with incorrect messages
Added dependency check of gtest before building those unittests
> [meson] Add dependency of gtest

- packaging/nnstreamer.spec
adding an element: `tizenwlsink`
it opens video preview when a pipeline with video is constructed.
> [Tizen] add a supporting element for tizen

- gst/nnstreamer/nnstreamer_subplugin.c
The header file, features.h, does not exist in the libc of clang. Therefore, features.h is excluded when building with clang to avoid a compilation error reltate to this header file.
This PR fixes a sub-item in #2096 
See also https://github.com/nnsuite/nnstreamer/issues/2141#with-enable-orc-enable-env-var-and-enable-symbolic-link
2. Run test: [ ]Passed [ ]Failed [ ]Skipped
> [Clang/Subplugin/Infra] Exclude features.h when building with clang

- ext/nnstreamer/tensor_filter/meson.build
- meson.build
This PR mainly concerns checking which data types the installed TensorFlow Lite supports at build time. In detail, the following commits are included:
- [Meson/TFLite] Check version in ext/nns/filter/meson.build 
- Move a specific code for the tensor filter extension for tflite from meson.build in the source root to the tensor filter extension directory
- [Meson/Filter/TFLite] Use has_type to check types tflite supports 
- Instead of checking which data types the installed TensorFlow Lite
supports via hardcoded version information, this patch uses has_type,
which is a function of the compiler object in meson, to check that.
See also: #2139, #2120
cc: @helloahn
Signed-off-by: Wook …
> [Meson/Filter/TFLite] Use has_type to check types tflite supports 

- ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
This patch adds a workround for the warning issued by clang when wrapping a function which takes format-literal-string arguments.
Resolves: https://github.com/nnsuite/nnstreamer/issues/2141#with-enable-cppfilter
> [Filter/C++] Add workround for a warning related to format-nonliteral @open sesame 03/16 12:00

- tests/nnstreamer_filter_extensions_common/meson.build
- tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
- tests/nnstreamer_filter_reload/tensor_filter_reload_test.c
This patch fixes build failures when the 'enable-test' option is set 'true' on macOS. The following errors are fixed:
- Corrected typo (G_OPTION_FLAG_NONE -> G_OPTION_ARG_NONE)
- Fixed an error caused by the behaviour difference of 'sed' between Linux
and macOS
- Eliminated a warning related to 'missing-braces' complained by clang++
Resolves: https://github.com/nnsuite/nnstreamer/issues/2141#with-enable-test
> [Tests] Fix build failures incurred by typo and sed on macOS

- tests/meson.build
The model reload test cases of tensor filter only works for the tensorflow lite filter and its models. Therefore, this patch adds a condition to check that the option for Tensorflow-Lite is enabled
before building those tests.
> [Tests/Meson] Build tensor filter reload tests when tf-lite is enabled

- tests/nnstreamer_filter_tensorflow/runTest.sh
This patch modifies the runTest script for TensorFlow sub-plugin tensor filter to use SO_EXT (pre-defined in SSAT) instead of the hardcoded extension, .so.
See also: #2170
> [Tests/Filter/TensorFlow] Use SO_EXT instead of hardcoded extension, .so

- api/android/api/src/main/jni/nnstreamer-native-customfilter.c
release resources if failed to construct native handle.
> [Android/Custom] possible mem leak

- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- tests/nnstreamer_filter_tensorflow_lite/runTest.sh
This reverts PR #2135 
The location of input/output buffers are not static when the tflite model has multi-tensor output. Thus #2135 causes regressions described in #2145 (it does not happen when the model has a one output tensor)
And, add a fail case and a simple run case for multi-tensor output tflite model.
Resolves: #2145 
> [tflite] Revert #2135 and add ssat tests for multi-tensor output tflite model

- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
WID:16576294 Uninitialized data is read from local variable 'status' at tensor_filter_tensorflow_lite.cc:474.
> [AHUB/430058] Fix unitialized local variable

- api/capi/src/nnstreamer-capi-util.c
Even with GST_STR_NULL, if the dereferenced pointer is null,
we will be doing NULLPTR[0], which may incur segmentation faults.
> [AHUB/434790] Fix dereferencing null pointer

- gst/nnstreamer/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.h
- tests/tizen_capi/unittest_tizen_capi.cc
Support get and set properties for GstTensorFilterFramework V1.
Updated GstTensorFilterFramework to include the number of accelerators supported along with its list.
Added TODO where updating of the framework is to be added if the set is called after the framework is opened or input/output is already configured.
Note: All the added TODO with the property update will be handled in a separate PR as per #2114
See also: #2116
> [filter] Support get and set properties @open sesame 03/07 05:10

- packaging/nnstreamer.spec
- tools/development/count_test_cases.py
Count negative cases of SSAT.
Print the sum of negative cases of Gtest and SSAT at the end.
This requires updates of SSAT (1.1.0)
Fixes #2150
With this commit, we get the following summary in the build log:
```
[  185s] GTest (total 349 cases)
[  185s]   Passed: 349 / Failed: 0 / Ignored: 0 | Positive: 251 / Negative: 98
[  185s] SSAT (total 520 cases)
[  185s]   Passed: 520 / Failed: 0 / Ignored: 0 | Positive: 508 / Negative: 12
[  185s] Grand Total: 869 cases (negatives : 110)
[  185s]   Passed: 869 / Failed: 0 / Ignored: 0
```
> [TestCase] Count negative cases of SSAT results @open sesame 3/18 09:59

- ext/nnstreamer/tensor_filter/tensor_filter_cpp.hh
- gst/nnstreamer/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/meson.build
- gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
- gst/nnstreamer/tensor_filter/tensor_filter_support_cc.hh
- meson_options.txt
With this, developers can write a C++ class to create
a tensor_filter subplugin without writing the duplicated
C codes.
Changes in V2:
- Redesigned the whole classes
- Applied the recent changes of #2072
Changes in V3:
- Re-redesigned the whole class.
- Build tested without subplugins
TODOS in later PRs:
- Refactor a few subplugins as pure C++ classes and test/update this class.
- Add packaging info
- Add more inline doxygen comments.
With this PR completed in the future, we can remove all the duplicated C code in C++ subplugins.
> New Filter Subplugin Interface Draft: C++ support

- tests/nnstreamer_plugins/unittest_plugins.cc
With LINE 1982, we had:
WID:16576305 An integer overflow may occur due to arithmetic operation (multiplication) between values '2' and '4294967295', where the first value comes from the expression 'i + 1' and the second value comes from the expression '-1'
Fix similar issues as well.
> [AHUB/430098] Fix typing errors

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
This fixes:
WID:16646516 After having been compared to NULL value at tensor_filter_common.c:773, pointer 'priv->fw' is dereferenced at tensor_filter_common.c:791.
> [AHUB/523198] Fix null pointer dereferencing

- tests/nnstreamer_source/unittest_src_iio.cc
Coverity complains about malloc-gfree pair. Then, pacify it by
using g_malloc-gfree pair.
Fixes: CID 1123909 (#1 of 1): Incorrect deallocator used (ALLOC_FREE_MISMATCH)
12. free: Calling g_free frees scan_el_data using g_free but it should have been freed using free.
> [Coverity/1123909] Fix ALLOC-FREE-MISMATCH

- nnstreamer_example/custom_example_LSTM/dummy_LSTM.c
- nnstreamer_example/custom_example_RNN/dummy_RNN.c
- nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c
- nnstreamer_example/custom_example_opencv/nnstreamer_customfilter_opencv_average.cc
- nnstreamer_example/custom_example_opencv/nnstreamer_customfilter_opencv_scaler.cc
- nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c
- nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough_variable.c
- nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c
- nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c
- tests/nnstreamer_sink/nnscustom_drop_buffer.c
- tests/nnstreamer_sink/nnscustom_framecounter.c
- tools/development/nnstreamerCodeGenCustomFilter.py
Change "LICENSE: LGPL-2.1" to "SPDX-License-Identifier: LGPL-2.1-only"
> [LFAI-4] Switch to SPDX short-form identifiers

- tests/tizen_capi/unittest_tizen_sensor.cc
The FHUB QB system is way too slow and cannot handle
events in 100ms, which makes the unit test fail.
> Fix: Tizen 6.0 FHUB QB is too slow. @open sesame 3/23 11:43

- tests/tizen_capi/unittest_tizen_capi.cc
Fix:
CID 1133962 (#1 of 1): Explicit null dereferenced (FORWARD_NULL)
166. var_deref_op: Dereferencing null pointer content.
> [Coverity/1133962] Prevent NULL dereference

- tests/tizen_capi/unittest_tizen_capi.cc
the success/fail cases are added for the api `ml_single_invoke_dynamic()`
> [C-API] add testcases for a function: `ml_single_invoke_dynamic()`

- api/android/api/src/main/jni/Android.mk
INT8/INT16 may incur build errors with older TF-Lite.
For users with older TF-Lite, leave some comments.
> [Android/Build] Add comments on TF-Lite versions and types.

- ext/nnstreamer/tensor_filter/meson.build
- meson.build
Although python2_incs and python3_incs are defined for the purpose of providing proper -I flags to the compiler, they are not used anywhere. Therefore, even though meson finds numpy in the system, building the python extensions is failed due to lack of the proper -I flags. Moreover, the existing mechanism to find numpy could not cover the cases when numpy is installed with pip using the user sheme or is installed in the virtual environment. This patch concerns this issue.
> [Filter/Python/Meson] Revise python dependencies

- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
Do not let subplugin authors handle alloc/dealloc name
for frequent getFrameworkInfo calls.
Allow them to point to a const string instead.
> [Filter/API] Constify subplugin name. @open sesame 3/26 18:35

- ext/nnstreamer/tensor_filter/tensor_filter_python.cc
In C++11, the use of the register keyword as a storage-class-specifier is deprecated [1] and this keyword is excluded from storage-class-specifiers in C++17 [2]. In order to avoid build warnings
from the old python2.7 code, this patch adds a workaround for it.
[1] http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4193.html#809
[2] http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4340
> [Filter/Python/CXX] Do not use 'register' as a storage-class-specifier @open sesame 03/26 13:46

- tests/tizen_capi/unittest_tizen_capi.cc
Using the instance of the model handle after failing to ml_single_open causes undefined behaviour. To prevent such cases, this patch changes the line for checking the result of ml_single_open() from EXPECT_EQ to ASSERT_TRUE that aborts the current test function.
> [Tests/CAPI] Abort the current test when ml_single_open is failed @open sesame 03/27 15:12

- packaging/nnstreamer.spec
This patch disables the test cases for the mvnc2 tensor filter which fails on Tizen 6.0 DA FHUB.
> [Dist/Tizen] Add workaround for mvnc filter test failure on Tizen

- tests/tizen_capi/unittest_tizen_capi.cc
This patch fixes trivial build warnings related to -Wsign-compare.
> [Tests/CAPI] Elminate comparison between signed and unsigned @open sesame 03/27 15:12

- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
This PR fixes the unpretty error message as follows:
```bash
[  186s] [ RUN      ] nnstreamer_nnfw_mlapi.invoke_pipeline_01_n
[  186s] Model file (/home/abuild/rpmbuild/BUILD/nnstreamer-1.5.1/tests/test_models/models/NULL.tflite) or its metadata is not valid (not regular).Model file (/home/abuild/rpmbuild/BUILD/nnstreamer-1.5.1/tests/test_models/models/NULL.tflite) or its metadata is not valid (not regular).Model file (/home/abuild/rpmbuild/BUILD/nnstreamer-1.5.1/tests/test_models/models/NULL.tflite) or its metadata is not valid (not regular).Model file (/home/abuild/rpmbuild/BUILD/nnstreamer-1.5.1/tests/test_models/models/NULL.tflite) or its metadata is not valid (not regular).Model file (/home/abuild/rpmbuild/BUILD/nnstreamer-1.5.1/tests/test_models/models/NULL.tflite) or its metadata …
```
> [Ext/Filter/NNFW] Add missing '\n' to the error messages

- ext/nnstreamer/tensor_filter/meson.build
#2225 requires this PR.
In order to provide the proper location of the test helper library which mocks edgetpu.so, this patch adds build_rpath to the shared_object statement in the meson build script for the edgeTPU filter extensions when 'enable-test' is true.
> [Ext/Filter/Meson/EdgeTPU] Add build_rpath when test is enabled

- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Related issue : #2226 [GBS] Failed test cases with --define "unit_test 1"
Add nnfw check availability method.
It fixs 'ml_check_nnfw_availability' with NNFW always returns true for any H/W resources
> [Filter/nnfw] Add check nnfw availability

- tests/tizen_capi/unittest_tizen_capi.cc
Changed `/* @brief ... "custom backend" -> "NNFW | NCSDK2 | ARMNN" */`
> [CAPI/unittest] Fix @brief of unittest for clarification

- README.md
- README.md: Add three images of ubuntu native apps and links to nnstreamer-example repos
check: https://github.com/anyj0527/nnstreamer/tree/Add-webp#usage-examples
I use html for merging rows in table which is not supported by github markdown.. 
> [Doc] Add webp files showing some example apps.

- packaging/nnstreamer.spec
This patch corrects LD_LIBRARY_PATH where the test helper shared libraries are placed for NCSDK2 and Edge-TPU test cases in the Tizen RPM spec file.
> [Dist/Tizen] Correct LD_LIBRARY_PATH for NCSDK2/Edge-TPU test cases

- tests/nnstreamer_decoder_image_segment/runTest.sh
- tests/tizen_capi/unittest_tizen_capi.cc
Related issue : #2226
```
$ gbs build -A armv7l  --define "unit_test 1" --clean --include-all
...
[  317s] [  FAILED  ] 2 tests, listed below:
[  317s] [  FAILED  ] nnstreamer_capi_sink.dummy_01
...
```
Fixed intermittent failure of test case due to slow speed of arm.
Sometimes the number of buffers stored in files are different.
Wait until EOS so that a fixed number of buffers can be saved.
@wooksong Please test with this change.
> [Tests/CAPI] Fix test case to stable in arm arch

- api/capi/include/platform/tizen_error.h
In order to handle the case of the platforms that do not have ESTRPIPE in their errno.h, ESTRPIPE is defined with EPIPE [1] if it is not available.
[1] https://gitlab.freedesktop.org/dude/gst-plugins-base/-/commit/a4b94e6c69525e404354cbd3d0b67ae7e001f385
> [CAPI] Use EPIPE if ESTRPIPE is not available

- Documentation/component-description.md
- api/capi/include/nnstreamer-capi-private.h
- api/capi/meson.build
- api/capi/src/nnstreamer-capi-tizen.c
- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
- gst/nnstreamer/nnstreamer.c
- gst/nnstreamer/tensor_repo/tensor_reposink.c
- gst/nnstreamer/tensor_repo/tensor_reposrc.c
- gst/nnstreamer/tensor_sink/tensor_sink.c
- gst/nnstreamer/tensor_source/meson.build
- meson.build
- meson_options.txt
- packaging/nnstreamer.spec
- tests/meson.build
A Tizen 4.0 device has decided to use nnstreamer for its updates
and the PM decided not to upgrade Tizen version of the product :(
WTH, let's support Tizen 4.0 as well.
In the due course, we will be supporting GStreamer 1.6 as well. (NNStreamer requires GStreamer >= 1.8 conventionally.)
Included commits are:
commit ee30eb76d4e84692216ace524c21e30a10e92078 (HEAD -> Tizen4, github-fork/Tizen4)
Date:   Tue Mar 31 12:23:14 2020 +0900
[Tizen 4.0] Disable mvnc packages in older Tizen
If mvnc build is turned off, do not package them.
commit ee66bf6319434b43172aba339e5e2afc085dd134
Date:   Tue Mar 31 11:41:23 2020 +0900
[Tizen 4.0-5.5] Disable …
> Support Tizen 4.0 Backports & GST < 1.8

- tests/cpp_methods/unittest_cpp_methods.cc
- tests/unittest_util.c
- tests/unittest_util.h
The direction of the operator determining the timeout was wrong and it was modified.
The timeout was too long in the test, so I reduced it.
> [tests] Fix pipeline state check methods

- ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
- ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc
- ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
- ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
- ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
- ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
- ext/nnstreamer/tensor_filter/tensor_filter_python.cc
- ext/nnstreamer/tensor_filter/tensor_filter_python_api.c
- ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- gst/nnstreamer/nnstreamer_conf.c
- gst/nnstreamer/nnstreamer_log.h
- gst/nnstreamer/nnstreamer_subplugin.c
- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- gst/nnstreamer/tensor_filter/tensor_filter_custom.c
- gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c
- gst/nnstreamer/tensor_transform/tensor_transform.c
With ml_log* nnstreamer internal APIs,
we can enable dlog in Tizen and Android logging in Android
while keep using GLIB's logging in other systems.
Fixes #1905
> [Log] Use ml_log* instead of g_* for logging

- tests/nnstreamer_sink/unittest_sink.cc
- tests/tizen_capi/unittest_tizen_capi.cc
In order to support the shared library on multiple platforms, the file extension corresponding to each platform is defined in nnstreamer_conf.h. To avoid code duplication, this patch replaces the
local defines in test code with NNSTREAMER_SO_FILE_EXTENSION.
> [Tests] Use NNSTREAMER_SO_FILE_EXTENSION instead of the local one

- tests/tizen_capi/unittest_tizen_capi.cc
This patch adds a #ifdef guard for the test cases which require TensorFlow Lite.
> [Tests/CAPI] Add a #ifdef guard for test cases that require tflite

- nnstreamer_example/custom_example_opencv/nnstreamer_customfilter_opencv_scaler.cc
This imports the gerrit commit from Tae-Young Chung:
https://review.tizen.org/gerrit/#/c/platform/upstream/nnstreamer/+/230088/
And then added a backward compatibility patch.
commit 90840083d5e5c87a05aeacb6299f4afcaf459b13 (HEAD -> opencvup, github-fork/opencvup)
Date:   Wed Apr 8 10:58:02 2020 +0900
[Example/custom/opencv] Backward compatibility for old opencv
The previous commit is for OPENCV3. Keep the old code for OPENCV2 or before.
Changed in v2:
- Per the comment from Tae-Young Chung,
"opencv3 also supports this change (opencv3 support c++)
how old opencv version should be supported? for example, opencv2.x?"
The backward compatibility patch is adjusted to support 2 or before. …
> [Example/custom/opencv] Use enumeration in imgproc.hpp

- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
If a sensor is not available or unknown,
do not assert, but emit error messages and return errors.
Fixes #2219
> [Tizen/Sensor] Do not assert for sensor not available

- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
Although SENSOR_ERROR_NONE is 0, explicitly specify
the name to increase readability.
> [Tizen/Sensor] Explicitly specify return values.

- api/capi/src/nnstreamer-capi-util.c
If user gets tensor data and tries to update it, memcpy is unnecessary.
> [C-API] same mem ptr

- gst/nnstreamer/nnstreamer_subplugin.c
GLIBC dlclose bug
https://bugzilla.redhat.com/show_bug.cgi?id=1264556#c42
is haunting us again with Tizen 5.5 backports.
> [Tizen 5.5 / GLIBC 2.24] Workaround for GLIBC bug

- api/android/README.md
- api/android/build-android-lib.sh
Change default option to build library with NNFW and SNAP.
NNFW and SNAP requires additional script.
Also update guide to build Android library.
> [Android/Build] default option to build subplugins

- gst/nnstreamer/meson.build
- gst/nnstreamer/registerer/nnstreamer.c
- jni/nnstreamer.mk
SAM analysis says that nnstreamer.c is causing cyclic dependency
between modules.
Although I think this is false positive, let's move nnstreamer.c
to a subdirectory so that SAM won't recognize nnstreamer.c is
"parent module" of other nnstreamer elements.
Because this is the only modules that SAM recognizes as MCD issue,
this may enhance SAM score greatly.
> Lower MCD, Increase SAM Score

- tests/tizen_capi/unittest_tizen_capi.cc
This patch experimentally replaces #define and #ifdef used for checking enable-tensorflow-lite is true with constexpr, which is type-safe replacement for #define.
> [Tests/CAPI] Use constexpr instead of define and ifdef for tflite @open sesame 04/13 15:19:47

- README.md
Builds and tests for armv7l, aarch64 and android(build only) are conducted every morning at 7: 30 a.m.
The results are shown on the first page of the nnstreamer.
Click the badge to download the log and images for the last seven days.
Build scripts can be found here : http://nnsuite.mooo.com/nnstreamer/ci/taos/daily-build/
> [Daily build] Add daily build badge

- api/android/api/src/main/jni/nnstreamer-native-api.c
- api/android/build-android-lib.sh
For C-API developers, add gst-init in native code.
Calling initialize() in java is unnecessary.
> [Android] initialize native code

- ext/nnstreamer/tensor_filter/meson.build
- tools/development/gen_mediapipe_libs.sh
add OpenCV dependency and check the architecture of the system.
Since some of the calculators of mediapipe have dependency at OpenCV, the libraries related to OpenCV are required.
Furthermore, the path of OpenCV libs is created according to the system and architecture of the environment.
> [Mediapipe] update meson script

- gst/nnstreamer/meson.build
- gst/nnstreamer/registerer/nnstreamer.c
- gst/nnstreamer/tensor_if/gsttensorif.c
- gst/nnstreamer/tensor_if/gsttensorif.h
- gst/nnstreamer/tensor_if/meson.build
- jni/nnstreamer.mk
Add empty functions and build infra for Tensor-If.
Tensor-If is a subclass of GstBaseTransform.
The src-pad and sink-pad are supposed to have the same
capabilities.
It appears that in-place op has no benefit, but
not sure if we need to prohibit it.
> [Tensor-If] Make it buildable

- ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
- ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
- ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
- ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
- ext/nnstreamer/tensor_decoder/tensordec-pose.c
- gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_decoder/tensordec.c
- gst/nnstreamer/tensor_filter/tensor_filter.c
- gst/nnstreamer/tensor_merge/gsttensormerge.c
- gst/nnstreamer/tensor_mux/gsttensormux.c
- gst/nnstreamer/tensor_repo/tensor_reposrc.c
- gst/nnstreamer/tensor_source/tensor_src_iio.c
- gst/nnstreamer/tensor_split/gsttensorsplit.c
- gst/nnstreamer/tensor_transform/tensor_transform.c
Some systems may use NDEBUG and skip all assert calls.
Do not call essential ops in there.
Fixes #2282
Reported-by: @ndufresne
> [Bug] Do not call essential ops in assert(). @open sesame 4/18 12:34

- CONTRIBUTING.md
- Documentation/contributing.md
- MAINTAINERS.md
As attorneys of stakeholders are drafting the community charter,
based on the current draft, I am updating related documents.
This is at the early stage of drafting. We have a lot more to update.
Refer to  https://wiki.lfai.foundation/display/NNSTREAM/NNStreamer+CONTRIBUTING+draft+of+2020.04
> [UPDATING THE RULE!] Comply with LF/AI Community Charter

- gst/nnstreamer/nnstreamer_log.h
Separate "fatal" level from "error".
When we convert "assert" fail to general error handling,
log-fatal might be appropriate.
Fixes #2288
> [Log] Add fatal-log

- tests/nnstreamer_sink/unittest_sink.cc
Test fails occasionally due to slow speed of arm.
The test was modified to wait until the pipeline processing the buffers
*Until the Daily build PASSES!
> [Tests] Fix sink unittest fail

- api/capi/src/tensor_filter_single.c
- gst/nnstreamer/include/nnstreamer_cppplugin_api_filter.hh
- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.h
- gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
By testing with C++ class tf-subplugin, "edget-tpu",
bugs were found from the recently introduced TF-V1 subplugin API.
- V1 APIs uses void * private_data instead of void ** private_data.
There are codes that do not reflect this.
In order to make C++ class subplugins work smoothly,
they need to know "this" pointer when they were invoked
by common C++ wrapper infrastructure, which is a set of
static functions of the base class.
Thus, add a new argument for them to find out "this" pointer.
CC: @kparichay
ps. This breaks C++ subplugin classes, which are, fortunately, not built by default yet. C++ subplugin classes will be working after PR #2194 (it has fixes)
> [Filter/v1] Bugfix of TF-V1 subplugin API / C++ support @open sesame 4/21 10:46

- api/android/api/src/main/jni/Android-nnstreamer.mk
- gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
- jni/Android-nnstreamer.mk
- jni/Android.mk
add cxx-flag in android build, enable exception handling.
> [Android/Build] flag to handle exception

- tests/unittest_util.c
- tests/unittest_util.h
1. apply "const" for data_received. It won't update it
2. make it robust against TEST_DEFAULT_SLEEP_TIME values
> [TEST/util] Clean up wait_pipeline_process_buffers

- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
increase timeout (30 sec) before invoking the model.
> [Test/NNFW] ignore timeout in singleshot

- tests/tizen_capi/meson.build
- tests/tizen_capi/unittest_tizen_sensor.cc
Fix tizen sensor unit test.
- Add macro to wait until start the pipeline.
- Wait until expected buffers are processed
> [TEST] Fix tizen sensor unit test

- packaging/nnstreamer.spec
Instead of manually setting cflags for coverage tracking, let's use b_coverage which is a meson's base option to do it.
> [Dist/Tizen] Use the base option, b_coverage, to track coverage

- tests/tizen_capi/meson.build
- tests/tizen_capi/unittest_tizen_capi.cc
Today's daily build was a success, but the test fails occasionally due to slow speed of arm.
Timeout increased to 10 seconds.
If timeout occurs again, I will investigate another cause.
> [Test] Fix tizen capi unittest

- ext/nnstreamer/android_source/gstamcsrc_looper.cc
- ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
- ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
- ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
- ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
- ext/nnstreamer/tensor_decoder/tensordec-pose.c
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- gst/nnstreamer/nnstreamer_conf.c
- gst/nnstreamer/nnstreamer_subplugin.c
- gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
- gst/nnstreamer/tensor_common.c
- gst/nnstreamer/tensor_common_pipeline.c
- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_decoder/tensordec.c
- gst/nnstreamer/tensor_filter/tensor_filter.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- gst/nnstreamer/tensor_filter/tensor_filter_custom.c
- gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c
- gst/nnstreamer/tensor_merge/gsttensormerge.c
- gst/nnstreamer/tensor_mux/gsttensormux.c
- gst/nnstreamer/tensor_repo/tensor_repo.c
- gst/nnstreamer/tensor_repo/tensor_reposrc.c
- gst/nnstreamer/tensor_split/gsttensorsplit.c
- gst/nnstreamer/tensor_transform/tensor_transform.c
If an error might occur by external reasons,
(invalid input/app behaviors and inappropriate environments)
it should not simply assert away, but should provide
appropriate error messages and handling.
This is WIP stage.
> Error return instead of assert for external errors.

- gst/nnstreamer/tensor_sink/tensor_sink.c
Set default sync option 'false'.
It may be delayed with tensor_filter element, to invoke neural network model.
> [Sink] default sync false

- tests/tizen_capi/unittest_tizen_capi.cc
Sync option is added on appsink pad to prevent potential test fail caused by buffer drop.
> [Test] Fix potential test fail

- ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
- ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_filter/tensor_filter.c
1. fix invalid index when unmapping the mem block
2. unref buffer when failed to get mem
> [CodeClean] fix invalid index

- api/capi/src/nnstreamer-capi-pipeline.c
add warning message if sink element does not have sync=false option.
> [C-Api/Pipeline] warning message for sync option

- tests/common/unittest_common.cc
- tests/nnstreamer_filter_mvncsdk2/unittest_filter_mvncsdk2.cc
- tests/nnstreamer_plugins/unittest_plugins.cc
- tests/nnstreamer_sink/unittest_sink.cc
- tests/tizen_capi/unittest_tizen_capi.cc
using `EXPECT_STREQ` rather than `EXPECT_TRUE( g_str_equal...`
> [Unittest] apply EXPECT_STREQ for string comparisons

- tests/nnstreamer_decoder_pose/runTest.sh
The test with `videotestsrc num_buffers=4` sometimes does not enough to execute some functions. This commit adds a test with more buffers.
> [Test/tensordec-pose] Add test case with more buffers

- tests/nnstreamer_decoder_pose/runTest.sh
- tensordec-pose treats incoming array as float, thus add `tensor_transform mode=arithmetic` to test pipeline
- expecting proper line converage results
> [Test/tensordec-pose] Fix a test case with arithmetic transform

- api/capi/include/nnstreamer.h
- api/capi/src/nnstreamer-capi-util.c
- tests/tizen_capi/unittest_tizen_capi.cc
if tensors-info has name, return new ref when getting the tensor name.
> [C-Api] new ref to get tensor name @open sesame 05/06 15:26

- ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Fix memory leak of nnfw runtime and tensor decoder image labeling unit test.
Related SVACE defects : 440263, 440264, 440265, 440266, 440261
> [TEST] Fix svace defect : nnfw_runtime, tensordec-imagelabel

- gst/nnstreamer/nnstreamer_conf.h
* Add omitted parameter comment for nnsconf_get_subplugin_info()
* Fix a typo
> [Conf] Add omitted comment and fix a typo @open sesame 05/07 11:09

- packaging/nnstreamer.spec
- packaging/run_unittests_binaries.sh
This PR fixes the broken test cases for the Tizen sensor tensor source extension.
In detail, 'unittest_tizen_sensor' requires a nnstreamer extension plugin, 'tensor_src_tizensensor', in addition to the other nnstreamer plugins. In order to resolve this dependency at build time, the rpm spec for Tizen is modified to provide extra GST_PLUGIN_PATH to 'unittest_tizen_sensor'.
See also: https://github.com/nnstreamer/nnstreamer/pull/2274
> [Tests/Source] Fix broken test cases for the Tizen Sensor extension

- tests/nnstreamer_source/unittest_src_iio.cc
fix mem leaks of few test cases
Valgrind result:
```text
==25353== LEAK SUMMARY:
==25353==    definitely lost: 0 bytes in 0 blocks
==25353==    indirectly lost: 0 bytes in 0 blocks
==25353==      possibly lost: 9,924 bytes in 80 blocks
==25353==    still reachable: 827,585 bytes in 9,637 blocks
==25353==                       of which reachable via heuristic:
==25353==                         length64           : 384 bytes in 9 blocks
==25353==                         newarray           : 1,600 bytes in 20 blocks
==25353==         suppressed: 0 bytes in 0 blocks
==25353== Reachable blocks (those to which a pointer was found) are not shown.
==25353== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```
**Self …
> [Unittest/IIO] fix mem leak of unittest_src_iio

- packaging/run_unittests_binaries.sh
PR #2338 has incurred a regression in the test suite that
make gbs pass even if there is a failed unit test case in gtest.
This fixes the regression of #2338
> [Tests/Regression] GTEST error is ignored

- api/capi/include/ml-api-common.h
- api/capi/include/nnstreamer.h
- api/capi/meson.build
- packaging/nnstreamer.spec
nntrainer wants to share the error codes for its API set.
Separate "common" header and release it via a sub-pacakge.
CC: @jijoongmoon: You can use this for
https://github.com/nnstreamer/nntrainer/issues/75
> [CAPI] Separate error codes: ml-api-common.h

- ext/nnstreamer/android_source/gstamcsrc.c
`gst_amc_src_finalize()` exists in the code but the finalize of GObject
class is not set. Because of this reason, gst_amc_src_finalize() function
is not called at all. This patch fixes this bug.
1. Build test: [*]Passed [ ]Failed []Skipped 
> [Android/AMC] Set the omitted finalize function

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
- meson.build
- meson_options.txt
- Developer should define SNPE_ROOT (dir path to Qualcomm Neural Processing SDK) which contains SNPE headers and libraries.
- Currently, this supports only CPU runtime on linux-x86_64
sample pipeline :
```
$ gst-launch-1.0 videotestsrc num-buffers=5 ! videoconvert ! videoscale !  video/x-raw,width=299,height=299,format=RGB,framerate=30/1 ! \
tensor_converter ! tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 ! tensor_filter framework=snpe model=./inception_v3.dlc ! fakesink
```
sample app :
https://github.com/anyj0527/nnstreamer-example/tree/example/snpe/image-classification/native/example_image_classification_snpe
Fixes #1872
> [filter/SNPE] Add tensor_filter sub-plugin for SNPE

- api/android/build-android-lib.sh
When running `build-android-lib.sh`, it does not stop even though error occur.
For example, `svn` is required for `build-android-lib.sh` 
but the script does not stop even though error occurs as below.
```bash
$ bash ./api/android/build-android-lib.sh 
NNStreamer library name: nnstreamer
...
~/Android/workspace/nnstreamer ~/Android/workspace/nnstreamer
./api/android/build-android-lib.sh: line 227: svn: command not found
./api/android/build-android-lib.sh: line 228: svn: command not found
./api/android/build-android-lib.sh: line 229: svn: command not found
~/Android/workspace/nnstreamer/build_android_lib ~/Android/workspace/nnstreamer ~/Android/workspace/nnstreamer
sed: can't read gradle.properties: No such file or directory
sed: can't read gradle.properties: No such file or directory
sed: …
```
> [Android] Stop when first error occurs

- api/capi/include/tensor_filter_single.h
- api/capi/src/nnstreamer-capi-single.c
- api/capi/src/tensor_filter_single.c
single API should process all the frameworks transparently once the single handle has been opened.
The framework check has been performed when the handle was created and opened.
If the operation is not supported, that should be handled in the nnfw rather than in single API.
Resolves: #2326 
> [single] single API to process nnfw transparently once opened

- gst/nnstreamer/tensor_demux/gsttensordemux.c
- gst/nnstreamer/tensor_split/gsttensorsplit.c
After demux/split the incoming buffer, unref the buffer to decrease ref count.
> [Demux/Split] unref incoming buffer

- tests/nnstreamer_filter_tensorflow_lite/runTest.sh
unittest of tflite compared output with grep "exp"
however some expressions could be prefix of different exp
this could lead to false positives
added line end marker
> [tflite] bug fix for tflite unittest

- api/capi/src/nnstreamer-capi-single.c
Added documentation for the thread behavior in various functions in single API
Also removed ERROR state as it was redundant after #2360
Resolves #2185
> [single] Added documentation for the thread behavior @open sesame 5/12 09:23

- api/capi/include/nnstreamer-capi-private.h
- api/capi/src/nnstreamer-capi-single.c
- api/capi/src/nnstreamer-capi-util.c
single API supported hw accelerator for the NNFW
this hw was used to check if it is supported by the framework
however this hw was never passed to the framework to use
this patch sovles this issue
resolves #2374
> [single] Add implementation to support for hw accelerator

- meson.build
- Change `additional_deps` -> `extra_deps` for tflite-nnapi-delegation
> [meson]Correct deprecated arg in features

- api/android/build-android-lib.sh
`ml-api-common.h` is recently added and it is included in nnstreamer.h.
However, it is not archived in nnstreamer-native.zip. Because of this
reason, buildbreak occurs when building Android jni application as below.
```bash
In file included from /home/again4you/Android/workspace/nnstreamer-example/android/example_app/capi-sample/src/main/jni/nnstreamer-native-sample.c:19:
/home/again4you/Android/workspace/nnstreamer-example/android/example_app/capi-sample/src/main/jni/nnstreamer/include/nnstreamer.h:29:10: fatal error: 'ml-api-common.h' file not found
#include "ml-api-common.h"
^~~~~~~~~~~~~~~~~
1 error generated.
```
This patch fixes that bug by adding it into zip file.
1. Build test: [*]Passed [ ]Failed …
> [Android] Add omitted header when archiving

- api/capi/include/nnstreamer.h
- api/capi/src/nnstreamer-capi-util.c
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- tests/nnstreamer_filter_tensorflow_lite/runTest.sh
- tests/tizen_capi/unittest_tizen_capi.cc
Added CPU_SIMD as a backend option
CPU_NEON will be alias for CPU_SIMD in enum but different string representation
Only updated tflite supported accelerators list. Others will be updated after #2372.
Refer https://github.com/nnstreamer/nnstreamer/pull/2372#discussion_r424857942 for more details.
cc. @myungjoo 
> [hw/accl] Add CPU_SIMD as a backend option

- ext/nnstreamer/tensor_filter/tensor_filter_mediapipe.cc
call free the resource after using it.
> [Filter/Mediapipe] fix a bug at destructor @open sesame 5/18 18:53

- meson.build
- tests/meson.build
- tests/nnstreamer_filter_edgetpu/meson.build
- tests/nnstreamer_filter_extensions_common/meson.build
- tests/nnstreamer_filter_mvncsdk2/meson.build
- tests/tizen_capi/meson.build
- tests/tizen_nnfw_runtime/meson.build
In order to make test() in the meson.build script work, this patch defines an environment object for the unit test cases and provides it to those test() functions as an argument.
```bash
$ rm -rf build && meson build && ninja -C build
...
$ ninja -C build test
ninja: Entering directory `build'
[1/2] Running all tests.
1/16 unittest_common                         OK       0.03 s 
2/16 unittest_sink                           OK      21.58 s 
3/16 unittest_plugins                        OK       1.98 s 
4/16 unittest_src_iio                        OK      21.76 s 
5/16 unittest_filter_mvncsdk2                OK      15.36 s 
6/16 …
```
> [Meson] Provide an environment object to test()  @open sesame 5/18 18:42

- api/capi/src/nnstreamer-capi-util.c
- ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
- tests/nnstreamer_filter_pytorch/runTest.sh
- tests/nnstreamer_filter_tensorflow_lite/runTest.sh
Patch to handle auto/default semantics for tensor_filter
Each tensor_filter can now pass its default/auto accelerator
If not passed, the value defaults to first entry from supported list of accelerators
Workaround used to provide this functionality in c - this helps running exisiting code error free with this change, and does not need each filter to essentially declare auto/default accelerators
Passed user input is parsed and if auto/default is used, corresponding accelerators are set and used.
This resolves #2320 for tensor_filter
> [filter] Handle auto/default semantics for tensor_filter

- gst/nnstreamer/nnstreamer_conf.c
Since key_file is declared using g_autoptr macro, it does not need to clean up variables.
reference link : https://blogs.gnome.org/desrt/2015/01/30/g_autoptr/
It is related to issue #2393. 
The unit tests are failed intermittently.
The nnsconf_loadconf is called while registering the external converter.
Remove g_autoptr instead of g_key_file_free
#
> [CONF] Fix nnstreamer conf load function

- tests/cpp_methods/meson.build
update unittest arg, use test-env in cpp-method test.
> [Test] use test-env

- packaging/nnstreamer.spec
Because of the typo for meson option, below warning occurs when
building.
* WARNING: Unknown options: "armnn_support"
This patch fixes this warning.
> [Spec] Fix the wrong meson option for armnn @open sesame 5/24 14:42

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/vivante/README.md
- ext/nnstreamer/tensor_filter/vivante/build_run.sh
- ext/nnstreamer/tensor_filter/vivante/meson.build
- ext/nnstreamer/tensor_filter/vivante/tensor_filter_subplugin.c
- meson_options.txt
- packaging/nnstreamer.spec
This commit is to append the Vivante sub-plugin based on the tensor filter
of NNStreamer to support the Vivante NPU driver.
**Changelog**
* Version 10:
* Added license clause
* Improved statements of the nnsreamer.spec file
* Version 1-9:
* Fixed memory leak (e.g., g_free)
* FIxed security (e.g., nnstreamer.nanifest) for Tizen packaging
* doc: Added how to build and run the Vivante filter on Ubuntu 18.04 (ARM64)
* Updated the invoke function to support various models
(e.g., Inception, Yolo, Mobile SSD)
* Added Tizen package script for Tizen platform
* Fixed incorrect var type (e.g., unsigned int for num_tensors)
* Added annotations for code maintenance
* Added run.sh for Ubuntu18.04 aarch64 + VIM3 board
* Added convert function for vivante tensor data type
* Added vsi_nn_GetTensor of …
> [Vivante Filter,V10] Added a sub-plugin filter for VIM3/Vivante NPU

- tests/nnstreamer_plugins/unittest_plugins.cc
This patch fixes the potential bug (i.e. pipeline parsing error) of unit testcase when using Protobuf v3.8.
> [Unittest] Fix a potential bug of unit testcase

- gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
Remove duplicated works to set source pad cap when sink event is received
> [Aggregator] Remove duplicated works to set caps

- api/android/api/build.gradle
- api/android/api/src/main/jni/Android-snpe-prebuilt.mk
- api/android/api/src/main/jni/Android-snpe.mk
- api/android/api/src/main/jni/Android.mk
- api/android/api/src/main/jni/nnstreamer-native-api.c
- api/android/build-android-lib.sh
- ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
- Add required snpe-sdk libs
- Set `jniLibs.srcDirs` to the android project explictly contains snpe-sdk libs for dsp/npu
- Make function `nns_set_env` to set env "ADSP_LIBRARY_PATH" (https://developer.qualcomm.com/docs/snpe/dsp_runtime.html)
- Log SNPE version
- Prevent build SNAP and SNPE together in android build script and
Android.mk
1 more commit:
- Add Debug message
- Add custom prop for snpe runtime and cpu_fallback options
ex) "custom=Runtime:GPU,CPUFallback:true"
> [Android] Prepare dsp/npu runtime for snpe filter

- api/capi/src/nnstreamer-capi-util.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.h
Add missing support for gstTensorFilterFramework in checking framework availability
for a given backend accelerator/hardware
> [single] Add missing gstTensorFilterFramework v1 support

- tests/meson.build
This patch fixes minor build errors caused when `libpng_dep` does not exist.
`tests/nnstreamer_filter_extensions_common/meson.build` is using this
variable regardless of `libpng_dep`'s existence.
> [Build/Tests] Fix 'tests/meson.build' to always find 'copy' program @open sesame 6/2 12:41

- gst/nnstreamer/nnstreamer_conf.c
- gst/nnstreamer/nnstreamer_conf.h
- gst/nnstreamer/tensor_decoder/tensordec.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
Basename is unnecessary, set sub-plugins name while loading configuration.
> [Conf] parse sub-plugins name

- gst/nnstreamer/include/nnstreamer_cppplugin_api_filter.hh
This patch adds a missing header, `string.h`, to `nnstreamer_cppplugin_api_filter.hh`, which uses `memcpy()`.
The below describes the related build errors.
```
dchae@dchae-ubuntu:~/PR/nnstreamer$ ninja -C build
ninja: Entering directory `build'
[7/10] Compiling C++ object 'ext/nnstreamer/tensor_filter/584bea7@@nnstreamer_filter_snpe@sta/tensor_filter_snpe.cc.o'.
FAILED: ext/nnstreamer/tensor_filter/584bea7@@nnstreamer_filter_snpe@sta/tensor_filter_snpe.cc.o 
ccache c++ -Iext/nnstreamer/tensor_filter/584bea7@@nnstreamer_filter_snpe@sta -Iext/nnstreamer/tensor_filter -I../ext/nnstreamer/tensor_filter -I/home/dchae/OpenLab/snpe-1.38.0.2034/include/zdl -Igst/nnstreamer -I../gst/nnstreamer -Igst/nnstreamer/./include/ -I../gst/nnstreamer/./include/ -I/usr/include/glib-2.0 …
```
> [Build/Fix] Add a missing header to 'nnstreamer_cppplugin_api_filter.hh'

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
gfree should be called when you completed accesing it.
> [Filter] bugfix: dangling pointer access.

- gst/nnstreamer/nnstreamer_log.h
define new nns_logf (common fatal-log definition with nns_log prefix)
> [Log] add definition log-fatal

- api/capi/include/nnstreamer-capi-private.h
- api/capi/src/nnstreamer-capi-pipeline.c
Add new function to get the gst-element from pipeline handle.
For native developers, it is necessary to get pipeline element to use gstreamer functions.
> [C-Api] function to get pipeline element

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCustomFilter.java
- api/android/api/src/main/java/org/nnsuite/nnstreamer/CustomFilter.java
- api/android/api/src/main/jni/nnstreamer-native-customfilter.c
In custom-filter interface, returning null in invoke-callback will drop the input buffer.
> [Android/Custom] drop input buffer

- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.h
This patch adds performance properties (latency/throughput) for tensor filter.
Those properties will be used for the overlay information, to show the performance
of tensor filter (e.g., SNPE).
It resolves #2417 
> [Filter/Prop] Add performance properties (lat/fps) for tensor filter

- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
setting the allocation type is not effective anymore.
previously(at Tensorflow v1.9), the flag `kTfLiteDynamic` for the allocation option of each tensor of Tensorflow-Lite was required. if it was not, there was no way to set input raw data and to get output raw data without `memcpy`.
However, recently, we met a case about a TFLite model not working with the option `kTfLiteDynamic`, and I tried various ways to solve it.
In conclusion, at TF 1.13.1 and 1.15.2 we provide, the option is not effective anymore. In other words, the raw data pointer that we used to still works properly without any problem like memleak or defects.
For this reason, we can solve the problem(the model not working) by removing the setting phrase without any modification of the current policy(not using the `memcpy`). …
> [Filter/TFLite] remove ineffective codes

- ext/nnstreamer/tensor_filter/vivante/README.md
This commit is to append how to enable the Vivante tensor filter
based on Vivante NPU Toolkit library on Ubuntu/ARM and Tizen/ARM devices.
---
> doc: how to enable vivante tensor filter

- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
recently updated, nnfw set-backend should be called after loading the model.
> [NNFW] set backend after loading model

- packaging/nnstreamer.spec
DA requested to remove mvncsdk/edgeTPU from the dependency.
Disable them for their builds.
> Tizen/spec: disable mvncsdk/edgeTPU for DA build

- jni/nnstreamer.mk
fix typo in mk file (jni nnstreamer defines)
> [Android] typo in mk file

- api/android/api/src/main/jni/nnstreamer-native-api.c
- api/android/api/src/main/jni/nnstreamer-native-customfilter.c
- api/android/api/src/main/jni/nnstreamer-native-pipeline.c
- api/android/api/src/main/jni/nnstreamer-native-singleshot.c
- api/android/api/src/main/jni/nnstreamer-native.h
Each invoke callback gets/returns tensor data object including metadata.
To improve performance, Cache tensor metadata object and avoid duplicated conversion.
> [Android] private data to set metadata

- ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
This patch supports neon accl for SNPE deeplab/depth segmentation decoder
I think we can optimize more as it's a naive impl. 
In fact, setting alpha values (conditionally) makes some inefficiency to use neon instructions.
> [Decoder/Neon] Support neon accl for SNPE deeplab/depth decoder @open sesame 6/5 13:19

- gst/nnstreamer/include/tensor_filter_custom_easy.h
Fix easy-custom-filter API's doxygen entry.
It gets output dimenesion info as an input, not output.
> Filter/Custom/Easy: fix doxygen entry

- gst/nnstreamer/tensor_mux/gsttensormux.c
- tests/nnstreamer_repo_lstm/runTest.sh
- tests/nnstreamer_repo_rnn/runTest.sh
After passing mux / demux, the framerate is extremely bigger than
before. (Issue #2440) This is mainly because sync_mode of tensor_mux
filter is SYNC_NOSYNC. To fix this bug, this patch set sync_mode to
SYNC_SLOWEST as default.
* Related Issue: #2440 
**Result**
After applying this patch, Default sync-mode is `slowest`.
```bash
$ gst-inspect-1.0 --gst-plugin-path="build" tensor_mux
...
sync-mode           : Time synchronization mode?
flags: readable, writable
String. Default: "slowest"
...
```
> [Mux] Set sync-mode to slowest as default @open sesame 6/9 23:16

- debian/control
- debian/nnstreamer-edgetpu.install
- debian/rules
- ext/nnstreamer/tensor_filter/meson.build
This PR addresses providing a debian/ubuntu sub-package that contains the tensor_filter extension for Edge TPU. To this end, 
- The mechanism that resolves for Edge TPU is modified.
- The option to enable-edgtpu is set to true by default in the **rules** file.
- The **control** file is modified and nnstreamer-edgetpu.install is added as well.
libedgetpu1-std and libedgetpu1-max simultaneously provides libedgetpu1 on which libedgetpu-dev depends. This incurs a conflict between these two packages at the build time so that pdebuild fails. To avoid this issue, libedgetpu1-std is added to the **Build-Depends** section of the **control** file.
See also: #1966
Signed-off-by: Wook Song …
> [Dist/Debian] Provide a sub-package for the Edge TPU extension 

- debian/control
- packaging/nnstreamer.spec
As flatbuf headers are separated from tflite-dev pkg, flatbuf-dev pkg is added.
~~*Updated tensorflow-lite-dev package not uploaded yet.~~
1. Build test: [ ]Passed [ ]Failed [ *]Skipped
2. Run test: [ *]Passed [ ]Failed []Skipped
> [Debian/control] Add flatbuf-dev build dependent package @open sesame 6/11 12:49 

- gst/nnstreamer/include/tensor_filter_custom_easy.h
- gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c
- tests/nnstreamer_sink/unittest_sink.cc
This patch newly add `NNS_custom_easy_unregister()` function to remove registered function so that pipeline itself can be reused without changing custom model name.
> [Filter/Custom/Easy] Add unregister function @open sesame 6/11 15:10 

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
This PR resolves https://github.com/nnstreamer/nnstreamer/issues/1966#issuecomment-641708718 by handling the error case when a model compiled by edgetpu-compiler is given. In general, a higher version of tensorflow-lite (> 1.13) could support more various types of the tflite models.
```bash
$ ./do.sh 
Null custom op data.
Node number 0 (edgetpu-custom-op) failed to prepare.
Failed to allocate tensors.
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Invoke called on model that is not ready.
Failed to invoke tensorflow-lite + edge-tpu.
** (gst-launch-1.0:1320): CRITICAL **: 19:47:07.893: Tensor-filter invoke failed (error …
```
> [Filter/EdgeTPU] Handle the error case when a compiled model is given

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
This patch fixes the memory bug in auto tensor filter detection.
`gst_tensor_filter_get_available_framework` assumes that `fw_name` and
`prop->fwname` are pointing different memory regions.
However, `_gtfc_setprop_Model` has passed the argument `fw_name` as
`prop->fwname`, which may cause the invalid memory access.
In this case, `fw_name` is being accessed after `prop->fwname` is freed.
> [Bugfix/Auto] Fix the bug accessing the freed memory region in auto fw_name

- api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsData.java
- api/android/api/src/main/jni/nnstreamer-native-api.c
- api/android/api/src/main/jni/nnstreamer-native.h
In tensors-data class, update private constructor with tensor-info.
This can remove method call to set metadata in native.
> [Android] constructor with info

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
- api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
- api/android/api/src/main/jni/nnstreamer-native-customfilter.c
- api/android/api/src/main/jni/nnstreamer-native-pipeline.c
- api/android/api/src/main/jni/nnstreamer-native-singleshot.c
To improve performance, it is necessary to remove metadata conversion in invoke method.
Do not handle dynamic mode in invoke method and update description to change the tensor info.
Also, if output info is changed using set-info method, update cached instance in private data.
> [Android] do not convert meta in invoke method

- gst/nnstreamer/nnstreamer_conf.c
- gst/nnstreamer/tensor_common.c
This patch removes uncessary argument checking before calling g_strdup()
If an argument of g_strdup() is NULL, its return value is also NULL.
So, checking its argument before calling is duplicated and useless.
> [Fix] Remove unncessary arg checking before calling g_strdup()

- meson.build
- tests/nnstreamer_filter_extensions_common/meson.build
- tests/nnstreamer_filter_mvncsdk2/meson.build
- tests/tizen_capi/meson.build
Update sub-plugin path in test-env, set converter plugin path.
> [Meson] converter sub-plugin path in test-env

- api/capi/include/nnstreamer.h
- api/capi/src/nnstreamer-capi-util.c
- tests/tizen_capi/unittest_tizen_capi.cc
Remove unnecessary error code (stream-pipe).
If failed to allocate mem for tensors-data handle, API returns out-of-mem error.
> [C-Api] error code when failed to allocate tensor data

- .TAOS-CI/config/config-environment.sh
- .TAOS-CI/config/config-plugins-prebuild.sh
1. Enable clang TAOS-CI module
2. Add "C++ ONLY" mode for it.
Note that I need to update TAOS-CI to make it accept such options: https://github.com/nnstreamer/TAOS-CI/pull/628
Fixes #2044
ps. This needs a new PR in TAOS-CI. Wait for it.
> TAOS-CI / Enable clang-format for C++ codes @open sesame 6/10 15:57

- api/capi/src/nnstreamer-capi-util.c
- tests/tizen_capi/unittest_tizen_capi.cc
When creating the data handle, return error if given tensors-info is invalid.
> [C-Api] handle invalid info when creating data handle

- packaging/nnstreamer.spec
Exclude generated files by flatbuf from coverage report
Before : 
After : 
> [Coverage] Exclude generated files by flatbuf

- gst/nnstreamer/tensor_repo/tensor_reposink.c
repo-sink may not receive a buffer when pipeline constructed.
set sync and async option to ignore this case.
> [RepoSink] ignore sync and preroll

- gst/nnstreamer/nnstreamer_conf.c
This patch adds missing `g_free()` to `nnstreamer_conf.c`
`nnsconf_get_custom_value_string()` allocates `hashkey` in the first    
line. However, if a value is found in the first hash lookup or a value  
does not exist in anywhere, `hashkey` is not inserted to the hash table,
which results in memory leak.                                           
> [Conf/MemLeak] Add missing g_free() to nnstreamer_conf.c @open sesame 6/19 15:30

- tests/nnstreamer_decoder_image_segment/runTest.sh
- Add test cases for newly added option `snpe-deeplab` and `snpe-depth`
- It also check profiling option of tensor_filter
> [Test] Add test for imageseg-decoder and tensor_filter profiling

- packaging/nnstreamer.spec
- tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc
- tests/nnstreamer_filter_edgetpu/unittest_edgetpu.cc
- tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
- tests/nnstreamer_filter_mvncsdk2/unittest_filter_mvncsdk2.cc
- tests/nnstreamer_filter_openvino/unittest_openvino.cc
- tests/nnstreamer_plugins/unittest_plugins.cc
- tests/tizen_capi/unittest_tizen_capi.cc
- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
In most cases, the environment variable, NNSTREAMER_BUILD_ROOT_PATH, is used for indicating the root directory of the path to which the 'test_models' directory belongs, which means the source root path. To avoid confusion, this patch renames it with NNSTREAMER_SOURCE_ROOT_PATH.
> [Tests] Rename NNSTREAMER_BUILD_ROOT_PATH with NNSTREAMER_SOURCE_ROOT_PATH

- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
When testing the operation of the multi-framework, if tflite is disabled, the test fails.
If tflite is disabled, skip the test.
> [TEST] Fix nnfw unit test

- ext/nnstreamer/android_source/gstamcsrc.c
- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
- gst/nnstreamer/include/tensor_typedef.h
- gst/nnstreamer/tensor_repo/tensor_reposink.c
- gst/nnstreamer/tensor_repo/tensor_reposrc.c
- gst/nnstreamer/tensor_sink/tensor_sink.c
- gst/nnstreamer/tensor_source/tensor_src_iio.c
code clean, remove unnecessary predefinition to set pad template.
> [CodeClean] remove unnecessary defines @open sesame 6/24 11:42

- meson.build
- tests/nnstreamer_filter_edgetpu/meson.build
- tests/nnstreamer_filter_extensions_common/meson.build
- tests/nnstreamer_filter_mvncsdk2/meson.build
- tests/tizen_capi/meson.build
This patch enables test(), which has been commented out, in the meson  build script for the EdgeTPU filter.
**After this PR**
```bash
$ ninja -C build test
[37/38] Running all tests.
1/17 unittest_common                         OK       0.01 s 
2/17 unittest_sink                           OK      21.71 s 
3/17 unittest_plugins                        OK       1.89 s 
4/17 unittest_src_iio                        OK      11.63 s 
5/17 unittest_edgetpu                        OK       1.99 s 
6/17 unittest_filter_mvncsdk2                OK      15.50 s 
7/17 unittest_cppfilter                      OK       1.04 s 
8/17 unittest_tizen_custom                   OK       0.02 s 
9/17 unittest_tizen_custom-set               OK       0.01 s 
10/17 …
```
> [Tests/Filter/EdgeTPU] Enable test() in the meson build script

- gst/nnstreamer/tensor_filter/tensor_filter.c
the allocated memory(when `allocate_in_invoke` is FALSE) should be free when `invoke()` returns not 0(OK)
> [Filter] fix a memory leak

- gst/nnstreamer/tensor_common.h
- gst/nnstreamer/tensor_common_pipeline.c
- gst/nnstreamer/tensor_mux/gsttensormux.c
This new sync mode allows PUSHING with only one new buffer of sinkpads of `tensor_mux`.
Previously, if `tensor_mux` want to push its buffers to srcpad, all of sink pads had to be filled with new buffers.
However, this new mode, REFRESH, push buffers when `tensor_mux` receive a new buffer.
For the other sink pads, except the one received the new buffer, will use again the previous one.
It decides EOS when any of the sink pads receive it.
related with: https://github.com/nnstreamer/nnstreamer-example/pull/141
> [Mux] add the new sync_mode:REFRESH

- api/capi/src/nnstreamer-capi-pipeline.c
- ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
1. add g_free to release the memory when appending mem block in buffer.
2. free interator in switch api.
> [C-Api] fix mem leak @open sesame 6/26 12:54

- api/capi/include/ml-api-common.h
This patch newly adds the ml_error_e Enumeration into the
CAPI_ML_FRAMEWORK doxygen group.
**Related doc issue**
* https://code.sec.samsung.net/confluence/pages/editpage.action?pageId=162754890
> [CAPI] Add ml_error_e into CAPI_ML_FRAMEWORK group

- api/capi/include/nnstreamer-capi-private.h
- api/capi/include/nnstreamer.h
- api/capi/src/nnstreamer-capi-pipeline.c
- tests/tizen_capi/unittest_tizen_capi.cc
This PR newly adds element-wise control functions to get and set
property values of the target element in NNStreamer pipeline.
It contains below patchs:
* Rename ml_pipeline_get_element() to ml_pipeline_get_gst_element()
* Add element-wise control functions
* Add testcases for element-wise control functions
**Related Issues**
* #2466 
* Add the code example for doxygen
* Add 16 test cases (8 positives, 8 negatives)
* Cleanup unused code & comments
* Support all element including AppSrc, AppSink, TensorSink, Selector and Valve.
* Add more testcases for sink and valve element.
* Update wrong comment
* first element -> first …
> [CAPI] Add element-wise control functions @open sesame 6/19 11:30

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
- gst/nnstreamer/tensor_transform/tensor_transform.c
- tests/nnstreamer_sink/unittest_sink.cc
When pushing the data directly from appsrc to tensor-transform (with typecast option), caps-negotiation failed and cannot run the pipeline.
To fix this, set type to unknown when direction is src pad.
> [Transform] nego failure with appsrc @open sesame 7/3 10:12

- debian/nnstreamer-dev.install
- gst/nnstreamer/include/meson.build
- gst/nnstreamer/include/nnstreamer_plugin_api.h
- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/include/nnstreamer_version.h.in
- gst/nnstreamer/tensor_common.c
- jni/nnstreamer.mk
- meson.build
- packaging/nnstreamer.spec
- tests/codegen/runTest.sh
- tests/common/unittest_common.cc
Let external nnstreamer plugins to probe nnstreamer version
at both run-time and build-time.
Fixes #2294
> [Common] Allow to fetch nnstreamer version @open sesame 7/1/ 23:04

- ext/nnstreamer/android_source/gstamcsrc.c
1. fix macro to get private data in element (will be deprecated)
2. fix indent
> [Android/AMCSrc] prevent build warning  @open sesame 7/3 10:28

- api/android/README.md
- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
- Add classification result test with inception model
- Add runtime checks
> [Test/android/snpe] Add android tests with snpe @open sesame 7/3 18:02 

- api/android/README.md
- api/android/api/src/main/jni/Android-nnfw-prebuilt.mk
- api/android/api/src/main/jni/Android-nnfw.mk
- api/android/api/src/main/jni/Android-nnstreamer-prebuilt.mk
- api/android/api/src/main/jni/Android-tensorflow-lite.mk
- api/android/build-android-lib.sh
Change default option to enable NNFW in android-api build, and clean up build script.
When building android library, download nnfw libs from ONE repo and start to build library.
> [Android] enable nnfw @open sesame 7/3 17:09

- api/capi/include/nnstreamer.h
Since 6.0, ML_ERROR_STREAMS_PIPE error code is removed in
ml_tensors_data_create() function and ML_ERROR_OUT_OF_MEMORY is returned
for this internal error. This patch adds a remarks section in
ml_tensors_data_create() for Tizen application developers.
**Related ACR**
* https://code.sec.samsung.net/jira/browse/ACR-1572
> [C-API] Add remarks section in ml_tensors_data_create()

- packaging/nnstreamer.spec
To avoid the license conflict issue by an automatic tool, this patch
newly adds the capi-nnstreamer-devel-static package, which only contains
`ibcapi-nnstreamer.a` file. capi-nnstreamer-devel package only has
headers and package config as below.
```bash
$ rpm -qlp capi-nnstreamer-devel-static-1.5.3-0.armv7l.rpm
/usr/lib/libcapi-nnstreamer.a
$ rpm -qlp capi-nnstreamer-devel-1.5.3-0.armv7l.rpm
/usr/include/nnstreamer/nnstreamer-single.h
/usr/include/nnstreamer/nnstreamer.h
/usr/lib/pkgconfig/capi-nnstreamer.pc
$ rpm -qlp nnstreamer-devel-static-1.5.3-0.armv7l.rpm
/usr/lib/libnnstreamer-tizen-sensor.a
/usr/lib/libnnstreamer.a
/usr/lib/libnnstreamer_decoder_bounding_boxes.a
/usr/lib/libnnstreamer_decoder_direct_video.a
/usr/lib/libnnstreamer_decoder_image_labeling.a …
```
> [SPEC] Newly add devel-static package

- tests/nnstreamer_sink/unittest_sink.cc
This patch fixes compiler warnings with -Werror=sign-compare related to the TestData and TestOption structures in unittest_sink.
> [Tests/Sink] Fix compiler warnings with -Werror=sign-compare

- ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
This patch fixes compile errors related to restriction of designated initialization in C++.
Resolves: #2528
> [Filter/OpenVino] Fix compile error due to OoO designated initialization

- api/capi/include/nnstreamer.h
This patch adds the remarks section for
ml_tensors_info_get_tensor_name() since the behavior of this function is
changed since 6.0.
* Update the `remark section` as @jaeyun-jung  recommanded.
* First draft.
> [C-API] Add remarks section for ml_tensors_info_get_tensor_name()

- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
- tests/tizen_capi/dummy_sensor.c
- tests/tizen_capi/dummy_sensor.h
API to read sensor data was deprecated since 5.5.
Replace this API (sensor data list).
Also set block size of output buffer when starting the src element.
> [Tizen/Sensor] remove deprecated api

- tests/tizen_capi/unittest_tizen_capi.cc
SVACE reported issues in Tizen CAPI unit test cases:
- 443268 (uninitialized local variable)
- 443269 (uninitialized local variable)
- 443278 (memory leak): although this is always not allocated successully, I've added "free" that fails with its error code assertion.
> [Fix/SVACE] memory leak and un-init local variables

- packaging/nnstreamer.spec
Adding elements: gdppay, gdpdepay
These elements payload and depayload GStreamer buffers and events using the GStreamer Data Protocol.
Related issue from LFAI technical discuss: https://lists.lfai.foundation/g/nnstreamer-technical-discuss/message/11
2. Run test: [ ]Passed [ ]Failed [ *]Skipped
> [SPEC] Add supproting elements for tizen

- gst/nnstreamer/tensor_demux/gsttensordemux.c
If `tensorpick` property of demux element is set twice by calling
`g_object_set()` function, the previous value should be removed and
new one should be written. However, the value is appended and it can
make a problem. This patch fixes this bug.
> [Demux] Bugfix for set_property function

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
1. Change nnfw api to set input info.
The function apply_tensorinfo will be deprecated soon.
2. Remove unnecessary definition about max rank of nnfw.
> [Filter/NNFW] change nnfw api

- api/capi/include/nnstreamer-capi-private.h
- api/capi/src/nnstreamer-capi-pipeline.c
- tests/tizen_capi/unittest_tizen_capi.cc
If the handle of sink-type element (i.e. tensor_sink and app_sink) is fetched by calling both `ml_pipeline_element_get_handle()` and `ml_pipeline_sink_register()` functions, segmantation fault occurs because of abnormal accessing for callback function. This PR adds this case and fixes this bug
It contains the following patches.
* Bugfix for abnormal accessing of the callback function
* Add test case for abnormal accessing of callback function
* Use `g_list_free_full()` and `GDestroyNotify` instead of iteration of GList.
* First draft
> [C-API] Bugfix for abnormal accessing of the callback function

- api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
- api/capi/include/nnstreamer-single.h
- api/capi/src/nnstreamer-capi-single.c
If user does not set the timeout, single-invoke function will wait for the output till the invoke is done.
This requires another ACR.
> [Api/Single] default no timeout when invoking model

- debian/control
- debian/nnstreamer-openvino.install
- debian/rules
- ext/nnstreamer/tensor_filter/meson.build
This PR depends on https://review.tizen.org/gerrit/#/c/platform/upstream/dldt/+/238180/ and https://review.tizen.org/gerrit/#/c/platform/adaptation/npu/intel-movidius-firmware/+/227997/.
This patch adds a sub-package that provides the tensor filter for OpenVino to Debian/Ubuntu.
> [Dist/Debian] Add a sub-package that provides the openvino filter @open sesame 7/21 11:30

- debian/control
- debian/nnstreamer-flatbuf.install
- debian/nnstreamer-protobuf.install
nnstreamer-flatbuf and
nnstreamer-protobuf will be available for Ubuntu/Debian.
This resolves the final subitem of #1919
> Debian: add flatbuf/protobuf packaging

- tests/tizen_capi/unittest_tizen_capi.cc
ret_sync_mode is unsigned.
If it is compiled with more strict compilers,
it emits errors. Fix it by adding U.
> Test/CAPI: Type mismatch warning

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc
- ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
- meson.build
Update pytorch extension for pytorch v1.6.0-rc1
Also pytorch and caffe2 headers do not follow redundant declarations
So, remove redundant declaration warning flag when compiling with them
Update caffe2 extension to remove warning based on api update for version 1.6.0-rc1
Related issue : #2411
> [pytorch/caffe2] Update extensions for v1.6.0-rc1

- tests/nnstreamer_source/unittest_src_iio.cc
~Src iio test fails occasionally when getting state of the pipeline.~
~Add a timeout and watch the results through the aging test.~
Unusual cases failed again..
I removed the previous patch and modified it to ignore this test in Ubuntu.
It seems difficult to fix immediately,  and it needs to be revised later.
> [Test] Ignore src iio unusual cases test  @open sesame 7/23 11:29

- api/capi/src/nnstreamer-capi-single.c
Enable setting timeout to 0
timeout 0 now has significance and re-setting timeout to 0 should be allowed
Related issue: #2568
> [single] Enable setting timeout to 0

- tests/tizen_capi/unittest_tizen_capi.cc
Bug fix for c-api unittest when tensorflow-lite is not present
Bug of destroy info without create in invoke_01
> [unittest] Bug fix for c-api unittest

- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
Ease the future timestamp check:
- At the check time, the timestamp of event could be the "next" sample
- Add tolerance amount of sampling rate
- Change Error to Warning
> [tizensensor] Add tolerance for sensor data check @open sesame 07/28 15:30

- ext/nnstreamer/tensor_filter/meson.build
1. For nnfw deprecated function, find symbol in header. (cannot find function in library)
2. Remove unnecessary dependency to check pytorch version.
> [Meson] dependency for filter subplugin

- ext/nnstreamer/extra/nnstreamer_protobuf.h
- ext/nnstreamer/tensor_decoder/tensordec-protobuf.cc
- ext/nnstreamer/tensor_filter/tensor_filter_python.cc
Having header inclusion with incorrect orders
may incur errors with older gcc of older Ubuntu distro.
You shouldn't omit headers only because they may be included
indirectly by other headers.
> Fix Ubuntu CI Build Error @open sesame 7/28 13:31

- api/capi/include/nnstreamer.h
- api/capi/src/nnstreamer-capi-pipeline.c
- tests/tizen_capi/unittest_tizen_capi.cc
To comply with Tizen API Design Guideline, this PR uses single key-value pair
for `ml_pipeline_element_set_property()` and `ml_pipeline_element_get_property()` functions.
It contains the following patches.
* [C-API] Modify element-wise control functions
* [Test/CAPI] Update testcases of element-wise control functions
**Related ACR**
* https://code.sec.samsung.net/jira/browse/ACR-1571
* Make a separate getter and setter for each type to comply with Tizen API Design Guideline.
* Use fixed width integer types (i.e. `int32_t`, `int64_t`) instead of primitive type (i.e. `int`, `long`).
* Need more scenario test cases.
* First draft
> [C-API] Modify element-wise control functions @open sesame 7/28 15:15

- api/android/api/src/main/jni/nnstreamer-native-api.c
- ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
Add condition to check params when initializing nnstreamer.
Also, single-shot does not need gstreamer initialization. Add feature for this.
> [Android] params to init nnstreamer

- api/capi/include/nnstreamer-capi-private.h
- api/capi/src/nnstreamer-capi-pipeline.c
for the specific situation, tensor_mux(refresh), the EOS buffer has to be inserted to make the pipeline state as NULL
> [C-API] add the EOS push at the destroy moment

- api/android/README.md
- api/android/build-android-lib.sh
For native developers, remove gstreamer java file in native libraries.
> [Android] remove java in native libs

- api/capi/src/nnstreamer-capi-single.c
- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
- ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
- ext/nnstreamer/tensor_filter/tensor_filter_openvino.hh
- ext/nnstreamer/tensor_filter/tensor_filter_python.cc
- ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
- gst/nnstreamer/include/tensor_typedef.h
- gst/nnstreamer/tensor_decoder/tensordec.c
- gst/nnstreamer/tensor_filter/tensor_filter.c
- tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc
- tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
- tests/nnstreamer_filter_openvino/unittest_openvino.cc
- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
One of the efforts to minimize API latency is to avoid creating data wrappers in
API and internally in nnstreamer and avoid its copying. Rather just interpret
the API data structure as internal definition.
This requires internal and external structures to be coherent.
This commit makes GstTensorMemory coherent with ml_tensor_data_s by removing
`tensor_type type` from GstTensorMemory.
type can be remove from GstTensorMemory as GstTensorMemory is used internally
and its usage is always supported with GstTensorInfo which contains the type information.
Correspondingly update the existing elements and extensions which use GstTensorMemory
to use the GstTensorInfo type information.
Also add bugfix for bug exposed with this patch - 
setInputDimension in python extension updates only the number of …
> [tensor] Update GstTensorMemory coherent with ml_tensors_data_s

- api/capi/include/nnstreamer.h
- api/capi/src/nnstreamer-capi-pipeline.c
- tests/tizen_capi/unittest_tizen_capi.cc
This patch makes int32/uint32 element-wise getter/setter functions
support Enumeration type. It is much natural and easy to use for
developers. I also add related test cases.
* Remove remark section related with long and enum type.
* Update the negative test case of element-wise control function.
* First draft
> [C-API] int32/uint32 get/set functions support enum type.

- api/android/build-android-lib.sh
use nnfw 1.6.1 for android build and release.
> [Android/NNFW] change nnfw version

- api/capi/include/nnstreamer-capi-private.h
- api/capi/src/nnstreamer-capi-tizen-feature-check.c
- tests/tizen_capi/unittest_tizen_capi.cc
- tests/tizen_capi/unittest_tizen_sensor.cc
- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
For readability, use typedef enum.
Resolves: https://github.com/nnstreamer/nnstreamer/issues/2574
> [C-API] Use typedef enum for feature_state

- api/capi/include/tensor_filter_single.h
- api/capi/src/tensor_filter_single.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
Tensor filter single performs various check on invoke
However, these checks are done on properties which remain static after open and first invoke
So, these checks are now performed on the first invoke only
Further, some checks were being performed multiple times, which have now been removed.
> [filter/single] Optimize invoke path for tensor filter single

- api/android/build-android-lib.sh
This reverts commit 5eefd5119550bbd19c351ecfb04bef1d589b72bd.
PM has decided to keep using 1.6.0 for this release.
> Revert "[Android/NNFW] change nnfw version" / Emergency

- api/capi/include/nnstreamer.h
In order to give events to appsrc via ml_pipeline_src_input_data,
I'd like to suggest to use "policy" argument to keep "data"
uncomplicated.
We can simply add non-policy enum values to have general
event support; if you need some value for an event, you can
keep using "data".
#2557 can coexist with this as a safety fall-back. (in case the user didn't call EOS before closing the pipeline.)
We just need to check if it is ok to call EOS twice for an appsrc.
Note that the implementation is not there and someone (@helloahn ?) needs to implement the function body: @helloahn 
We may need ACR as well: @again4you 
> C-API/ml_pipeline_src_input_data new enum for events suggstion.

- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
In `unittest_tizen_nnfw_runtime_raw.cc`,
change constants to unsigned value for gtest EXPECT_EQ
> [Test] Fix signed-unsigned comparison

- api/capi/include/nnstreamer-capi-private.h
- api/capi/src/nnstreamer-capi-pipeline.c
Currently, the waiting time for the 'state change' at the destroy moment is fixed with 50ms even when the state change is not required.
This PR suggests changing it with 'check-and-wait' loop with a new flag to reduce the fixed waiting time.
With this change, I checked that `ml_pipeline_destroy()` became almost 40ms faster than before at RPI4.
> [C-API] removing the hard coded waiting time

- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- tests/tizen_capi/meson.build
- tests/tizen_capi/unittest_tizen_capi_latency.cc
Added unittest to measure the invoke latency by single API.
This latency is measured for tensorflow-lite and nnfw-runtime filters.
The latency is measured by running the invoke with single API and running the invoke over the same data with the same model using filter API directly.
The difference in average execution time is reported as the latency introduced by the single API invoke per call.
The invoke is called 1000 times after a warmup where the output is also verified.
> [Single] Add unittest to measure invoke latency by single API

- api/capi/include/nnstreamer-capi-private.h
- api/capi/src/nnstreamer-capi-single.c
- api/capi/src/nnstreamer-capi-util.c
Reduced wrapper memcopy for invoke by typecasting ml_tensors_data_s->tensors to GstTensorMemory *
This reduces invoke latency
> [single] Reduce wrapper memcopy for invoke

- api/capi/src/nnstreamer-capi-pipeline.c
Clear pipeline bus before unref the pipeline.
> [C-Api] fix exception case

- tools/nnstreamer-toolkit.py
1. Change "Library" to "Lesser" for LGPL v2.1
Both words are correct, but "Lesser" is more common in v2.1
2. Fix some typo
> [tools] Fix typo

- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
Tflite invoke stores evaluates and stores indexes of input and output tensors which is not needed
Remove it from critical path
Minimize invoke critical path for tflite extension:
1. Cache input and output tensor ptrs out of the invoke to the location where extension
stores input and output tensors info
2. Verification of output size also moved out of invoke as the output tensor memory is
allocated internally by nnstreamer and its size is verified by each of the single API
and by tensor_filter.c for pipeline
> [tflite] Optimization for the invoke critical path @open sesame 07/28 15:00

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
In case, empty string is provided for the property,
tensor filter set_property() sets the number of tensors to 0 in
its private info.
Now with this patch, updating the num_tensors to non-zero is allowed.
However, setting to 0 is not.
Resolves #2594
> [filter] Buf fix of setting num_tensors to 0

- api/capi/include/nnstreamer.h
Fix typo from:
nnstreamer.h
Signed-off-by: DaWoon Kim <kim1023123@gmail.com>
> [C-api] Fix typo

- ext/nnstreamer/android_source/gstamcsrc_looper.cc
- ext/nnstreamer/android_source/gstamcsrc_looper.h
Fix exception case, start amcsrc-looper after calling the constructor.
> [Android/AMC] start thread after the construction

- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
- Cause GstBaseSrc manages the timestamp, remove related part
> [tizensensor] Remove code related with timestamp

- api/android/api/src/main/AndroidManifest.xml
- For Android Gradle Plugin 3.6.0 or higher, the property is set to "false" by default,
- It makes snpe sub-plugin unable to use dsp/npu runtime, so set it to "true"
> [android] Set `extractNativeLibs` true to use snpe dsp/npu runtimes

- api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsData.java
- api/android/api/src/main/jni/nnstreamer-native-api.c
- api/android/api/src/main/jni/nnstreamer-native-customfilter.c
- api/android/api/src/main/jni/nnstreamer-native-pipeline.c
- api/android/api/src/main/jni/nnstreamer-native-singleshot.c
- api/android/api/src/main/jni/nnstreamer-native.h
In native code, we can get the mem ptr of byte-buffer.
Remove memcopy to convert tensors object and data struct in native.
> [Android] mem ptr to byte-buffer

- tests/common/unittest_common.cc
- tests/nnstreamer_filter_openvino/unittest_openvino.cc
- tests/nnstreamer_plugins/unittest_plugins.cc
1. The TCM(test case manager) cannot check properly the test which is defined as a macro.
Add assert test for unittest_plugins.cc
2. Remove the version control test. It's not a proper negative test.
3. tensor_filter_custom_easy.in_code_func_01 is False-negative.
The test case contains assert_* and expect_*, it is detected as no assertion TC.
Related issue: #2633 
Results:
> [TESTS] Fix no assertion test

- packaging/nnstreamer.spec
This PR requires https://review.tizen.org/gerrit/#/c/platform/adaptation/npu/intel-movidius-firmware/+/240962/ and https://review.tizen.org/gerrit/#/c/platform/upstream/dldt/+/240964/.
This patch adds a sub-package that enables the tensor filter plugin for OpenVino support.
> [Dist/Tizen] Add a sub-package that enables tensor filter for OpenVino

- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Some models use INT64 type
Change-Id: I1009cc7ac845c1dbb20fbed36fc68b08f98e81dc
Signed-off-by: Semun Lee <semun.lee@samsung.com>
- Added INT64 case to nnfw_tensor_type_to_gst()
Resolves: #2643 
2. Run test: [ *]Passed [ ]Failed []Skipped
1. See if ml_single_open() succeed with nnfw and models with INT64 output.
```
> [nnfw] Support INT64 for nnfw

- packaging/nnstreamer.spec
A [comment](https://github.com/nnstreamer/nnstreamer/pull/2537#pullrequestreview-467332430) from @helloahn was not applied in #2537.
This patch applies that comment by correcting typo in the rpm spec file.
> [Dist/Tizen] Correct typo

- api/android/api/src/main/jni/nnstreamer-native-api.c
- api/android/api/src/main/jni/nnstreamer-native-singleshot.c
- api/android/api/src/main/jni/nnstreamer-native.h
The result of single-shot invoke is invalid.
Remove tensor data free after converting native handle to data object in single-shot.
> [Android] fix data conversion error

- api/android/build-android-lib.sh
We will use ONE v1.8.0 from next build & release of Android APIs.
cc. @lemmaa @chunseoklee
> [Android/NNFW] update version

- tests/tizen_capi/unittest_tizen_capi.cc
Negative TCs has multiple tests, separate them as single test cases.
After this PR:
- Total TCs: 458
- Positive TCs: 250
- Negative TCs: 208
> [TESTS/CAPI] Seperate negative TC as single test case

- packaging/nnstreamer.spec
This patch excludes the device-dependent filters such as OpenVino and
EdgeTPU when checking testcase coverage.
> [SPEC] Exclude device-dependent filters when checking testcase coverage

- tests/tizen_capi/unittest_tizen_capi_latency.cc
- Fix build fail issue when build with capi
Previous build result:
```bash
../tests/tizen_capi/unittest_tizen_capi_latency.cc:170:7:   required from here
/usr/src/gtest/include/gtest/gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
if (lhs == rhs) {
~~~~^~~~~~
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```
> [test/fix] Fix signed-unsigned compare

- api/capi/src/nnstreamer-capi-single.c
- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Bug fix for setting accelerator in the C-API.
When accelerator is set after the framework, tensor_filter does not know the framework
to check its version and store that information appropriately.
So, when framework version does not match, set property returns without setting the property.
This patch changes the order of setting this information for single API.
Related Issue: #2645 #2650
> [single] Bug fix for setting accelerator @open sesame 8/15 18:50

- ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
The output tensor description of face detection model for OpenVino is the same as that of person detection model for the same framework. This patch updates the bounding-boxes mode of tensor decoder to support face detection model by reusing the code for the person detection model support.
1. Build 
```console
$ pwd
./nnstreamer
$ sudo apt install openvino-dev
$ meson build -Denable-openvino=true
$ ninja -C build
```
2. Prepare the running environment
```console
$ export GST_PLUGIN_PATH=$(pwd)/build/gst/nnstreamer
$ export NNSTREAMER_CONF=$(pwd)/build/nnstreamer-test.ini
$ export NNSTREAMER_FILTERS=$(pwd)/build/ext/nnstreamer/tensor_filter
$ export NNSTREAMER_DECODERS=$(pwd)/build/ext/nnstreamer/tensor_decoder
```
3. Launch the pipeline …
> [Ext/Decoder] Support face detection models for OpenVino

- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- This resolves #2665
- For some tf-lite models, the `Invoke()` function newly reserve the internal tensor vector `tensors_`
- To fix this issue, cache again after the first invoke
The tf-lite model from #2665 has `tensors_size` of 113. After the first invoke the tf-lite reserves it to capacity of 129 (from 128).
Because `tensors_size` 113 + `capacityheadroom` 16 > `tensors_.capacity()` 128
```
before invoke: 0x56151998ac40
capacityheadroom: 16, tensors_size: 113, tensors_.capacity: **128**
after invoke: 0x7fa994030550
capacityheadroom: 16, tensors_size: 113, tensors_.capacity: **129**
```
REF (tf-lite):
- [TfLiteStatus …
> [filter/tflite] Cache tensor ptr after the first invoke

- api/capi/include/nnstreamer.h
This patch adds the Tensor dimension information, which is omitted in
the sample code.
> [CAPI] Update sample code for Custom Filter

- tests/tizen_capi/unittest_tizen_capi.cc
Fix duplicated test in unittest_tizen_capi.cc.
`info_get_tname_02_n` equals `info_get_tname_03_n`.
> [TEST] Fix duplicated test

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
- ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
- Throw invalid_argument exception when it fails to configure options
- Add two negative TCs for invalid custom properties
- Add a TC to test utilizing DSP runtime
> [Android/Test] Add Test cases for SNPE Singleshot api

- debian/control
- debian/nnstreamer-util.install
- debian/rules
- gst/nnstreamer/nnstreamer_conf.c
- gst/nnstreamer/nnstreamer_conf.h
- packaging/nnstreamer.spec
- tools/development/confchk/confchk.c
- tools/development/confchk/meson.build
Second commit (packaging):
Dist/Tizen,Ubuntu: Add nnstreamer-util package
Package nnstreamer-check at /usr/bin with "nnstreamer-util" package.
Note that this does NOT require nnstreamer installation.
If there is no nnstreamer detected, it will simply say that nnstreamer is not found.
The utility, "nnstreamer-check", is supposed to search for nnstreamer installation with GStreamer infrastructure.
First commit (code):
[Utility] NNStreamer-Check
The new utility, "nnstreamer-check", shows
NNStreamer configuration dump to stdout.
This helps nnstreamer developers who suffer from
installation paths and configuration paths.
Fixes #2638
Example:
```bash
$ nnstreamer-check
NNStreamer version: 1.5.3
loaded : TRUE
path   : …
```
> NNStreamer-Check Utility

- gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
fix typo, cpp std version macro.
> [Filter/Cpp] typo in cpp check

- gst/nnstreamer/tensor_transform/tensor_transform.h
This patch fixes a minor typo in 'stand' transform description.
> [Stand/Typo] Fix a minor typo in 'stand' transform description

- api/capi/doc/nnstreamer_doc.h
- api/capi/include/nnstreamer-single.h
- api/capi/include/nnstreamer.h
This patch adds a '%' before http to avoid html link. It is related to
Tizen public header issue.
> [Docs] Add a '%' before http @open sesame 8/27 18:30

- tests/common/unittest_common.cc
check return value when setting conf path after test is done.
> [CodeClean] fix coverity issue

- api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsData.java
- api/android/api/src/main/jni/nnstreamer-native-api.c
- api/android/api/src/main/jni/nnstreamer-native-singleshot.c
- api/android/api/src/main/jni/nnstreamer-native.h
Direct buffer allocated from native will not release the buffer.
Create instance in java and set byte array, then call method to add tensor data.
> [Android] deallocate direct buffer

- gst/nnstreamer/tensor_split/gsttensorsplit.c
This patch fixes the offset calculation bug in tensor split.
Unless tensors have 1-byte data size, each tensor split's src gets invalid data.
> [Bug/TensorSplit] Fix the offset calculation bug

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
- tests/nnstreamer_filter_tensorflow_lite/runTest.sh
This patch adds independence on the order of setting the properties
Properties of tensor filter which depends on the framework can now be set before setting the framework as well
When setting the framework, these properties are set again from the cache
Resolves #2650
> [filter] Independency on order of the properties

- gst/nnstreamer/tensor_transform/tensor_transform.c
- gst/nnstreamer/tensor_transform/tensor_transform.h
- tests/transform_clamp/generateTest.py
- tests/transform_clamp/runTest.sh
This patch supports 'clamp' as tensor_transform's option.
It requires min/max values to apply clamp for input tensor data.
The usage is like below:
```
... ! tensor_transform mode=clamp option=-123.902313:150.837601 ! ...
```
It resolves https://github.com/nnstreamer/nnstreamer/issues/2675
> [Clamp] Support 'clamp' as tensor_transform's option

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
- api/android/api/src/main/jni/Android.mk
- api/capi/src/nnstreamer-capi-util.c
- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- meson.build
- tests/tizen_capi/unittest_tizen_capi.cc
Support model path as model property for NNFW.
NNFW requires model path to open model.
Current tensor-filter and API does not allow directory string.
Check the model property and if it is directory, set framework to NNFW.
cc @lemmaa @chunseoklee 
> [Filter/NNFW] directory as model parameter

- api/android/api/build.gradle
- api/android/api/src/main/jni/Android-snpe-prebuilt.mk
- api/android/api/src/main/jni/Android-snpe.mk
- api/android/build-android-lib.sh
- We do not need to link all snpe prebuilt libs: only libSNPE requires to build aar
- Move excluded libs to jniLibs
> [Android/SNPE] Modify SNPE prebuilt libs

- api/android/api/build.gradle
- api/android/api/src/main/jni/Android-nnfw-prebuilt.mk
- api/android/build-android-lib.sh
It is unnecessary to link all nnfw prebuilt libs. Only nnfw-dev requires to build aar.
This may fix unexpected error in nnfw runtime env.
cc @chunseoklee 
> [Android/NNFW] nnfw prebuilt libs

- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
For now, there is no api to use bcq backend from android java
application. Thus, as a workaround, set 'cpu;bcq' as a deafult backend.
Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>
---
```bash
various tools like `log`, `shortlog` and `rebase` …
```
> onert(nnfw) uses 'cpu;bcq' as default backend

- debian/nnstreamer.install
Since nnstreamer-protobuf and nnstreamer-flatbuf packages are separated from nnstreamer package, fix the SO installation list of nnstreamer.
> [Dist/debian] Fix nnstreamer install files

- api/capi/include/nnstreamer-capi-private.h
- api/capi/include/nnstreamer-single.h
- api/capi/include/tensor_filter_single.h
- api/capi/src/nnstreamer-capi-single.c
- api/capi/src/nnstreamer-capi-util.c
- api/capi/src/tensor_filter_single.c
- gst/nnstreamer/tensor_filter/tensor_filter.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.h
- meson_options.txt
- tests/tizen_capi/unittest_tizen_capi.cc
Commit 1 : 
When tensor filter with `allocate_in_invoke` allocates the memory,
its memory should be destroyed with the filters destroy notify
However, this was ignored until now for the single API (#2593)
This patch fixes this
Single handle now creates a list of each such data buffer
as well as the single handle is stored in the data buffer.
If the data buffer is deallocated, then destroyNotify is called from the
single handle stored in it.
However, if the single handle is closed before the data buffer is freed,
then all the memory is freed from the list of the data buffers
stored in the single handle.
V2:
Added note to the description of `ml_single_invoke` about data not being available 
single handle is closed when memory is allocated by the framework.
Commit 2 :
Appropriate negative …
> [single] Resolve tensor filter memory leak

- gst/nnstreamer/hw_accel.c
- gst/nnstreamer/hw_accel.h
- gst/nnstreamer/meson.build
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- jni/nnstreamer.mk
As per the comments received in #2651, this patch moves the hardware
dependent code out of the tensor filter.
V2:
Also updated bugfix for linux (non android, non tizen) arm build
for proper header inclusion.
Resolves #2704 
> [hw/accl] move h/w dependent code out of filter + Bug Fix

- gst/nnstreamer/tensor_common.c
This patch fixes CWE-476 (NULL Pointer Dereference) in gst_tensors_info_parse_names_string () of tensor_common.c.
> [Coverity/Common] Fix CWE-476 in tensor_common

- gst/nnstreamer/tensor_repo/tensor_repo.c
This patch fixes CWE-366 (Race Condition within a Thread) in gst_tensor_repo_add_repodata () of tensor_repo.c.
> [Coverity/Repo] Fix CWE-366 in tensor_repo

- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
The conditions in `if` statements are guaranteed in the get_property function, so remove this part
> [Coverity] Fix CWE-466 (Lock) in tizensensor_get_property

- ext/nnstreamer/tensor_filter/tensor_filter_python.cc
- meson.build
**PR description**
This PR applies some changes in libpython v3.8 as follows:
- [Meson] Use python3-embed when the version of given python3 is 3.8 
- [Filter/Python] Apply the change sinve v3.8 in the PyCore library name
- FYI, files in libpython3.7 and in libpython3.8 could be checked here: [3.7](https://packages.ubuntu.com/bionic/amd64/libpython3.7/filelist) and [3.8](https://ubuntu.pkgs.org/20.04/ubuntu-updates-main-amd64/libpython3.8_3.8.2-1ubuntu1.2_amd64.deb.html)
Resolves: #2692 
2. Run test: [*]Passed [ ]Failed [ *]Skipped
> [Filter/Python] Apply changes in python v3.8

- tools/debugging/README.md
This patch adds a description on how to trace individual element using silent property.
I personally found it useful while working on PR #2714.
~The gst-launch example in the section will crash but it will quickly give the idea than showing an lengthy, fully working example.~ Now it won't crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nnstreamer/nnstreamer/2715)
> [tools/debugging] Add how to trace a specific NNStreamer element

- ext/nnstreamer/tensor_filter/meson.build
This patch adds the dependency check of flatbuffer when tf-lite filter
is enabled. It shows developers more detailed information instead of a
simple build break log.
If tf-lite filter is enabled, then `flatbuffers-dev` package also should be installed.
However, there is no dependency check for this so below error occurs.
```bash
$ meson build
..
$ ninja -C build
...
In file included from /usr/include/tensorflow/lite/core/api/op_resolver.h:20:0,
from /usr/include/tensorflow/lite/model.h:39,
from /home/again4you/nnstreamer_work/flatbuffer_dependency/nnstreamer/ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc:36:
/usr/include/tensorflow/lite/schema/schema_generated.h:21:10: fatal error: flatbuffers/flatbuffers.h: No such …
```
> [TF-lite] Check flatbuffer dependency when tf-lite is enabled.

- tests/meson.build
This PR fixes #2722 (#2723), which is meson failure in some test cases when there is no dependency on GTEST. 
**Note that although this PR fixes the configuration errors, https://github.com/nnstreamer/nnstreamer/issues/2704 is not resolved for the master branch. To build nnstreamer on aarch64, you need to check out the for-next branch with this PR**
> [Tests/Meson] bugfix: Fix meson failure because of no dependency on GTEST

- meson.build
This patch adds the missing dependency in the flatbuffer-support feature declaration.
> [Meson] bugfixes: Add missing dependency in flatbuffer-support declaration

- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
ONE supports API to set input info, remove unnecessary feature about changing input shape.
TODO:
1. We should wait next ONE release - maybe ONE 1.10 on next month.
2. After the next ONE release, consider to publish nnstreamer 1.6.x release.
> [Filter/NNFW] enable set-dim function

- ext/nnstreamer/tensor_filter/tensor_filter_python.cc
- ext/nnstreamer/tensor_filter/tensor_filter_python_api.c
- meson.build
- tests/nnstreamer_filter_extensions_common/meson.build
In order to nnstreamer-python3 work with python 3.8 on macOS, this PR revises the libpython name and the hard-coded file extensions of shared libraries to fit macOS. In addition, PyType_Ready is moved to the location before PyModule_Create as the official tutorial [1, 2] guided. This is because PyType_Ready after PyModule_Create fails with returning -1 in some cases.
[1] https://docs.python.org/3/extending/newtypes_tutorial.html
[2] https://docs.python.org/2/extending/newtypes.html
> [Filter/Python3] Make nnstreamer-python work with python 3.8 on macOS 

- ext/nnstreamer/meson.build
- meson.build
This patch revises meson.build to enable the flatbuf-support only if the versions of flatc and libflatbuffers are matched.
FYI, there is no way to get the version of the library found using cc.find_library() in Meson.
Therefore, ```flatbuffers.pc``` has been included in the dev-kit packages for Ubuntu and Tizen before submitting this PR.
(Wait for deployment of https://review.tizen.org/gerrit/gitweb?p=platform/upstream/flatbuffers.git;a=commit;h=1bfa4ddaa8e39fc6b50f8b8e359aa0c32ef8ced1)
Resolves: #2711 
> [Meson] Enable fbs-support only if versions of flatc and libs are matched @open sesame 09/22 11:55

- api/capi/meson.build
- packaging/nnstreamer.spec
This patch adds the verson number to libcapi-nnstreamer.so and fixes the
packaging issue as follows:
```bash
$ rpm -qlp capi-nnstreamer-1.5.3-0.x86_64.rpm
/usr/lib64/libcapi-nnstreamer.so.0
/usr/lib64/libcapi-nnstreamer.so.1
/usr/lib64/libcapi-nnstreamer.so.1.5.3
/usr/share/licenses/capi-nnstreamer
/usr/share/licenses/capi-nnstreamer/LICENSE
$ rpm -qlp capi-nnstreamer-devel-1.5.3-0.x86_64.rpm
/usr/include/nnstreamer/nnstreamer-single.h
/usr/include/nnstreamer/nnstreamer.h
/usr/lib64/libcapi-nnstreamer.so
/usr/lib64/pkgconfig/capi-nnstreamer.pc
```
* Add libcapi-nnstreamer.so.0 symlink to temporarily support the backward …
> [API/Tizen] Add verson number to libcapi-nnstreamer.so

- ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
- ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc
- ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
- ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
- ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
- ext/nnstreamer/tensor_filter/tensor_filter_python.cc
- ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- ext/nnstreamer/tensor_filter/vivante/tensor_filter_subplugin.c
- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
This patch focuses on moving subplugin initialization from dlopen constructers to static definitions.
This also includes a minor macro rename (s/__NO_ANONYMOUS_NESTED_STRUCT/NO_ANONYMOUS_NESTED_STRUCT/g).
Please see commit messages for detail.
1. Rebuilt library without error.
2. Run several examples and behaves the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nnstreamer/nnstreamer/2757)
> [tensor_filter] Improve subplugin initialization

- api/android/api/src/main/jni/nnstreamer-native-api.c
- api/android/api/src/main/jni/nnstreamer-native.h
Prepare next version to reduce latency while converting the tensors.
Add new native function to create data object.
After implementing new single-shot API (no data alloc in invoke API), I will update Java invoke method to remove memcpy.
> [Android] new function to create data object

- api/android/api/src/main/jni/nnstreamer-native-singleshot.c
- api/capi/include/nnstreamer-capi-private.h
- api/capi/include/tensor_filter_single.h
- api/capi/src/nnstreamer-capi-single.c
- api/capi/src/tensor_filter_single.c
Add new function to invoke the model with pre-allocated output data handle.
This may reduce single-shot invoke latency in Android Java API.
> [Single] invoke with pre-allocated output data

- Documentation/getting-started-meson-build.md
Update getting-started.md for ubuntu to include minimal requirement
required to build nnstreamer with default configuration
> [docs] Update getting-started with minimal requirement @open sesame 09/28 19:18

- debian/rules
- meson.build
- meson_options.txt
- nnstreamer_example/custom_example_LSTM/meson.build
- nnstreamer_example/custom_example_RNN/meson.build
- nnstreamer_example/custom_example_average/meson.build
- nnstreamer_example/custom_example_opencv/meson.build
- nnstreamer_example/custom_example_passthrough/meson.build
- nnstreamer_example/custom_example_scaler/meson.build
- packaging/nnstreamer.spec
Since there are test cases that require custom-filters, the install-example option should be set to true as well as the
install-test option to make the installed test cases fully work. To avoid such tangled dependencies between these meson options, this patch merges install-example into install-test.
Resolves: #2761
> [Meson] Merge install-example into install-test @open sesame 9/24 16:02

- ext/nnstreamer/tensor_filter/meson.build
This patch blocks the building of the TensorFlow-Lite subplugin without resolving the dependency on libflatbuffers-dev.
> [Ext/Filter/Meson] Do not build tflite-extension without flatbuffers-dev

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
This patch adds tf-lite version checking and makes it remove
'contrib' include path in tflite subplugin.
It resolves https://github.com/nnstreamer/nnstreamer/issues/2756.
> [Build/TF-Lite] Check tf-lite version and don't use contrib path @open sesame 9/24 16:03

- ext/nnstreamer/tensor_filter/tensor_filter_python.cc
- ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
This PR is about setting verify_model_path as TRUE to delegate the given model files' verification to the NNS common framework.
If such verification code is included in the tensor_filter sub-plugin, it is also removed from the sub-plugin.
> [Ext/Filter] Set verify_model_path as TRUE for TF, PyTorch, and Python sub-plugins

- tests/nnstreamer_repo_lstm/runTest.sh
- tests/transform_arithmetic/checkResult.py
- Add an escape character in runTest.sh
- Open binary file with 'rb' mode, not 'r'
> [test/SSAT] Fix minor SSAT test issues

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
This patch uses g_value_take_string, instead of g_value_set_string,
in get_property impl, to avoid redundant invoking g_free.
> [Fix/Filter] Use g_value_take_string in get_property

- debian/rules
- meson.build
- packaging/nnstreamer.spec
- packaging/run_unittests_binaries.sh
- tests/nnstreamer_filter_extensions_common/meson.build
- tests/tizen_capi/unittest_tizen_capi.cc
This patch eliminates hard-coded build root from source code. Instead of the hard-coded 'build', this patch introduces an environment variable, NNSTREAMER_BUILD_ROOT_PATH, which is provided by the meson build script. According to this change, packaging scripts are also updated.
> [Tests] Eliminate hard-coded build root from source code

- api/android/api/src/main/jni/Android-snap-prebuilt.mk
- api/android/api/src/main/jni/Android-snap.mk
- api/android/build-android-lib.sh
- ext/nnstreamer/tensor_filter/tensor_filter_snap.cc
- jni/nnstreamer.mk
Upload sub-plugin for SNAP.
To build Android library with SNAP, developer should download Samsung Neural SDK and set the path to SNAP SDK interface.
Tested on S20+ (QC)
> [Android/SNAP] subplugin for SNAP

- gst/nnstreamer/tensor_if/gsttensorif.c
- gst/nnstreamer/tensor_if/gsttensorif.h
Implemen basic operation of tensor_if element with uint8 type data.
Other PRs will be added soon to support generic type and remain actions.
- Supported operator: All
- Suppoted data type: uint8 (need to make it as generic type)
- Supported action: Not given. Just operate as passthrough(TRUE) and skip(FALSE)
How to test tensor_if element?
If the value of [0][0][0][0] of the first tensor is less than 60, the buffer is dropped.
```
gst-launch-1.0 v4l2src ! videoconvert ! videoscale ! video/x-raw, format=RGB, width=640, height=480, framerate=30/1 ! tensor_converter ! mux.sink_0 \
videotestsrc ! videoconvert ! videoscale ! video/x-raw, format=RGB, width=640, height=480, framerate=30/1 ! tensor_converter ! mux.sink_1 \
tensor_mux name=mux ! tensor_if name=tif \
compared_value=A_VALUE …
```
> [TensorIF] Implement basic operation with uint8 type data @open sesame 9/24 16:05

- gst/nnstreamer/tensor_if/gsttensorif.c
- gst/nnstreamer/tensor_if/gsttensorif.h
Support generic type for compared value and supplied value
float type is availabe for supplied value.
- e.g., supplied-value=2.23e+1,22.3
-  Supported operator: All
-  Supported data type: All
-  @todo: Supported action: Not given. Just operate as passthrough(TRUE) and skip(FALSE)
> [TensorIF] Support generic type for comapred and supplied value

- nnstreamer_example/meson.build
Because of the wrong file path in meson script, below error occurs when
running `meson build` command. This patch fixes that bug.
* Error message: nnstreamer_example/meson.build:98:2: ERROR: File
nnstreamer_customfilter_example_tensorrt_reshape.cc does not exist.
> [Meson] Fix the buildbreak of custom_example_tensorrt example

- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
add debug log in invoke function to print average time.
> [Log/TF-lite] print average invoke time

- gst/nnstreamer/meson.build
- gst/nnstreamer/registerer/nnstreamer.c
- gst/nnstreamer/tensor_rate/gsttensorrate.c
- gst/nnstreamer/tensor_rate/gsttensorrate.h
- gst/nnstreamer/tensor_rate/meson.build
- jni/nnstreamer.mk
This patch implements the prototype codes for `tensor_rate` element.
`tensor_rate` will include two methods to adjust a frame rate.
1) Either drop or duplicate frames similar to `videorate` plugin
2) Propagate a specified frame-rate to upstream elements.
As a prototype, most of codes are reused from `videorate` sources codes,
and still many things should be revised according to the tensor concept.
But, at least, its functionality was checked if we run this pipeline.
```                      
gst-launch-1.0 videotestsrc                                            
! video/x-raw,width=640,height=480,framerate=15/1                   
! tensor_converter                                                   
! tensor_rate framerate=10/1  
! tensor_decoder mode=direct_video …
```
> [TensorRate] Implement the prototype codes for tensor_rate element @open sesame 10/12 12:19

- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
When called set-info function, NNFW updates output shape after the invoke is done.
Add dummy invoke function and call it after input shape is changed.
> [Filter/NNFW] dummy invoke after set-info called

- tests/meson.build
- tests/nnstreamer_rate/runTest.sh
This patch adds simple testcases for tensor_rate element, just adjusting
downstream framerate without sending QoS events to upstream elements.
> [TensorRate/Test] Add simple testcases for tensor_rate (not QoS events)

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
- api/android/build-android-lib.sh
prepare next ONE release (ver 1.10.0)
- change pkg name (nnfw -> onert)
- add new testcase to check dynamic dimension
> [ONE/Android] prepare ONE-1.10.0 release

- gst/nnstreamer/tensor_transform/tensor_transform.c
An orc does not support a 64bit integer typecast.
A problem occurs when the pipeline is launched with the orc option,
and then the option is changed using set_property to convert type int64 or uint64.
So disables the orc if the int64 or uint64 typecast is required.
> [Tensor Transform] Fix unsupported orc type cast

- gst/nnstreamer/tensor_if/gsttensorif.c
- gst/nnstreamer/tensor_if/gsttensorif.h
Supports other/tensor(s) in output format.
- Supported operator: All
- Supported data type: All
- Supported action: passthrough, skip, tensorpick. (Others will be added)
- Output format: other/tensor or other/tensors
Test pipeline description
```
gst-launch-1.0 v4l2src ! videoconvert ! videoscale ! video/x-raw, format=RGB, width=640, height=480, framerate=30/1 ! tensor_converter ! mux.sink_0 \
videotestsrc ! videoconvert ! videoscale ! video/x-raw, format=RGB, width=640, height=480, framerate=30/1 ! tensor_converter ! mux.sink_1 \
tensor_mux name=mux ! tensor_if name=tif \
compared_value=A_VALUE compared-value-option=0:0:0:0,0 \
supplied-value=70,150 \
operator=RANGE_INCLUSIVE \
then = PASSTHROUGH\
else = TENSORPICK \
else-option= 1 \
tif.src_0 ! tensor_demux name=demux \
demux.src_0 ! …
```
> [TensorIF] Supports other/tensor(s) in output format

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
This patch initializes the omitted 'verify_model_path' value instead of
'allocate_in_invoke', which is set twice.
> [Filter] Fix the omitted initialization of GstTensorFilterFrameworkInfo

- debian/nnstreamer-dev.install
- debian/nnstreamer.install
- debian/rules
This patch adds missing installation files on Ubuntu packaging,
mostly related to capi and nnstreamer-check.
It resolves #2822
> [Fix/Debian] Add missing installation files (nnstreamer-check/capi)

- ext/nnstreamer/meson.build
- ext/nnstreamer/registerer/tizensensor.c
- ext/nnstreamer/tensor_source/meson.build
- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
- ext/nnstreamer/tensor_source/tensor_src_tizensensor.h
- meson.build
- packaging/nnstreamer.spec
- tests/tizen_capi/meson.build
This patch adds registerer for ext plugins to register multiple elements for ext plugins.
For example, 
- tizensensor plugin
--> tensor_src_tizensensor
- grpc plugin (TBA)
--> tensor_src_grpc
--> tensor_sink_grpc
@myungjoo Please take a look at this proposal.
> [Build/ExtPlugin] Add registerer for ext plugins (tizensensor, gRPC, ...)

- packaging/nnstreamer.spec
Flatbuf is required by tf-lite these days. Enable it.
Reported by Jongmin Lee.
> DIST/Tizen: enable flatbuf for VD

- debian/nnstreamer-dev.install
- debian/nnstreamer.install
This patch removes libcapi-nnstreamer.a from the main package and moves libcapi-nnstreamer.so to the development package.
Resolves: #2836 
> [Dist/Debian] Move libcapi-nnstreamer.a and .so to the development package

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
This patch fixes the wrong accelerator example in the prop spec.
This helps other developers to avoid confusions.
In actual tests, the true:(GPU,NPU,!CPU) format fails to be accepted so
that it switches to default mode. Also test cases do not cover such
format as well [1].
It also adds a note where to find available accelerator names.
[1]
https://github.com/nnstreamer/nnstreamer/blob/main/tests/nnstreamer_filter_tensorflow_lite/runTest.sh#L108
Signed-off-by: Bumsik Kim <k.bumsik@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nnstreamer/nnstreamer/2834)
> [tensor_filter_common] Fix a wrong example in accelerator prop spec

- ext/nnstreamer/tensor_filter/meson.build
TF2-Lite has all such data types enabled.
We do not need to check them.
> Filter/TF2-Lite: remove unnecessary if in meson @open sesame 10/28 15:05

- README.md
This patch adds hall-of-fame section to README.md
It looks like below
[![](https://sourcerer.io/fame/dongju-chae/nnstreamer/nnstreamer/images/0)](https://sourcerer.io/fame/dongju-chae/nnstreamer/nnstreamer/links/0)[![](https://sourcerer.io/fame/dongju-chae/nnstreamer/nnstreamer/images/1)](https://sourcerer.io/fame/dongju-chae/nnstreamer/nnstreamer/links/1)[![](https://sourcerer.io/fame/dongju-chae/nnstreamer/nnstreamer/images/2)](https://sourcerer.io/fame/dongju-chae/nnstreamer/nnstreamer/links/2)[![](https://sourcerer.io/fame/dongju-chae/nnstreamer/nnstreamer/images/3)](https://sourcerer.io/fame/dongju-chae/nnstreamer/nnstreamer/links/3)[![](https://sourcerer.io/fame/dongju-chae/nnstreamer/nnstreamer/images/4)](https://sourcerer.io/fame/dongju-chae/nnstreamer/nnstreamer/links/4)[![](https …
> [README.md] Add hall-of-fame section to README.md

- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- tests/nnstreamer_plugins/unittest_plugins.cc
This patch newly adds the rank count logic to GstTensorFilterProperties.
The rank count is automatically calculated based on the given dimension
string and NNStreamer rank count rule.
For example, given tensor filter parameters, input ranks are calculated as follows.
* `tensor_filter input=3:224:224`: input rank is 3.
* `tensor_filter input=3:224:224:1`: input rank is 4.
* `tensor_filter model=mobilenet_v1.tflite` : input rank is 3 since input dimension of given model is `3:224:224`.
* https://github.com/nnstreamer/nnstreamer/wiki/Rank-counting-with-other-tensor-types
* Set `outputranks` property as G_PARAM_READABLE.
* Rank …
> [Filter] Add rank count logic to GstTensorFilterProperties @open sesame 10/14 13:28

- gst/nnstreamer/tensor_repo/tensor_reposrc.c
When executing `gst-inspect-1.0 tensor_reposrc` command, below error
occurs.
```bash
$ gst-inspect-1.0 tensor_reposrc
...
** (gst-inspect-1.0:29483): CRITICAL **:
gst_tensor_repo_remove_repodata: assertion '_repo.initialized' failed
```
The main reason that the disposal callback always try to remove the repodata
even though it is not initialized and it causes the assertion error.
This patch fixes that bug.
> [Repo] Fix the assertion error when executing `gst-inspect-1.0 command

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
tensor_filter auto detection of framework takes in the extension
and for tflite extension tries to identify the framework using
a priority set with the configuration.
however, in case, the priority string is NULL, no tensor_filter
framework is set although multiple tensor_filters supporting
this extension can exist.
This patch sets a default framework for tflite extension which is
overwritten based on the priority if priority exists.
This bug shows when using ML_NNFW_TYPE_ANY with nnstreamer CAPI
for tflite extension files on TIZEN with gbs emulator where priority string
is read as NULL (happens in nntrainer).
> [tensorfilter] Set default framework when no priority

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
- api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java
Handle invalid param case -init nnstreamer with invalid context.
> [Android] handle invalid context

- gst/nnstreamer/include/nnstreamer_plugin_api.h
- gst/nnstreamer/tensor_common.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- tests/nnstreamer_plugins/unittest_plugins.cc
Even though the dimension string of the input tensor is given in the
pipeline, the `input` property is always fixed 4 dimensions (i.e.
d1:d2:d3:d4). This patch returns the dimension string considering tensor
dimension and rank count.
For example, given tensor filter parameters
'tensor_filter input=3:224:224', the returned dimension string is
`__3:224:224__` instead of `3:224:224:1`.
* Rebase previous patches
* According to Jaeyun's advice, make a simple logic
* first draft
> Update dimension string when it is explicitly given in Pipeline @open sesame 10/20 18:25

- tests/nnstreamer_if/unittest_if.cc
- Fix gtest's complaint about signed-unsinged comapre in unittest_if
The compile error log was:
```
Found ninja-1.8.2 at /usr/bin/ninja
[19/35] Compiling C++ object 'tests/59830eb@@unittest_if@exe/nnstreamer_if_unittest_if.cc.o'.
FAILED: tests/59830eb@@unittest_if@exe/nnstreamer_if_unittest_if.cc.o
c++ -Itests/59830eb@@unittest_if@exe -Itests -I../tests -Igst/nnstreamer -I../gst/nnstreamer -Igst/nnstreamer/./include/ -I../gst/nnstreamer/./include/ -Igst/nnstreamer/tensor_transform -I/usr/include/glib-2.0 -
I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/src/gtest -I/usr/src/gtest/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-p
ch -Wnon-virtual-dtor …
```
> [unittest] Fix signed-unsigned comapre

- README.md
LF-AI/Data recommends to maintain CII Best Practices checks.
This badge shows the status.
> Add CII Best Practices Badges

- README.md
- api/android/README.md
- api/android/api/build.gradle
- api/android/api/src/main/jni/Android-tensorflow-lite.mk
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- Tflite gpu delegate requires sdk version higher than 28. Bump up the minimum sdk version from 24 to 28
- Support gpu delegate for tflite-2.3.0
- Resolves #2852 
- REF: https://github.com/nnstreamer/nnstreamer-android-resource/pull/13
> [Android/tflite] Support gpu delegate @open sesame 11/06 10:52 

- packaging/nnstreamer.spec
This patch enables gRPC plugin in DA profile.
The below shows gRPC deployment status in each profile.
- DA: gRPC 1.20.1 (same with the upstream)
- VD: None
It resolves https://github.com/nnstreamer/nnstreamer/issues/2861
> [Tizen/gRPC] check gRPC capability in nnstreamer.spec

- ext/nnstreamer/meson.build
- ext/nnstreamer/registerer/grpc.c
- ext/nnstreamer/tensor_sink/meson.build
- ext/nnstreamer/tensor_sink/tensor_sink_grpc.c
- ext/nnstreamer/tensor_sink/tensor_sink_grpc.h
This patch implements gRPC tensor sink as a client.
Its gRPC server mode is WIP.
> [gRPC/Sink] Implement gRPC tensor sink @open sesame 11/10 12:12

- api/android/api/src/main/java/org/nnsuite/nnstreamer/Pipeline.java
- api/android/api/src/main/jni/nnstreamer-native-api.c
- api/android/api/src/main/jni/nnstreamer-native-pipeline.c
- api/android/api/src/main/jni/nnstreamer-native.h
Add new method to set a surface to video-sink element.
In Android application, developer can simply set SurfaceHolder object to glimagesink.
> [Android] method to set surface

- gst/nnstreamer/include/nnstreamer_plugin_api_converter.h
- gst/nnstreamer/include/nnstreamer_plugin_api_decoder.h
- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/nnstreamer_conf.c
- gst/nnstreamer/nnstreamer_conf.h
- gst/nnstreamer/nnstreamer_subplugin.c
- gst/nnstreamer/nnstreamer_subplugin.h
- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_decoder/tensordec.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- tools/development/confchk/confchk.c
This patch adds feature to show custom property description for
registered sub-plugins.
Related issue: #2782
Please share your opinions on better text formatting or recommended structure that contains related info.
For example, we can expect the following result
```
$ ./nnstreamer-check
...
NNStreamer registered sub-plugins:                                                           
============================================================                                 
[Filter]                                                                                     
cpp                                                                                        
- No custom property found                                                               
openvino …
```
> [Tools/Confchk] Show custom property description for sub-plugins @open sesame 10/15 19:48

- packaging/nnstreamer.spec
Since the rootstrap of Tizen v6.5 is not ready, some application built on v6.0 needs libcapi-nnstreamer.so file.
Because of this reason, this patch temporarily adds the capi-nnstreamer-devel Requires to capi-nnstreamer package.
It will be removed when the rootstrap of Tizen v6.5 is ready.
* https://github.com/nnstreamer/nnstreamer/issues/2874
* Add `capi-nnstreamer-devel` Requires to `capi-nnstreamer package` instead of making symlink.
* First draft
> [SPEC] Add capi-nnstreamer-devel Requires to capi-nnstreamer package

- gst/nnstreamer/tensor_filter/tensor_filter.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.h
- gst/nnstreamer/tensor_rate/gsttensorrate.c
- gst/nnstreamer/tensor_rate/gsttensorrate.h
This patch implements a simple QoS mechanism which skips
inference when QoS events arrive from tensor_rate.      
The below shows test results using tflite object detection example
- Without throttling (original pipeline, eventually saturated 10 FPS due to tensor filter's performance)
```
...
! queue leaky=2 max-size-buffers=2 ! videoscale ! video/x-raw,width=640,height=480 ! tensor_converter
! tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5
! tensor_filter framework=tensorflow-lite model=...
...
```
- With throttling (`tensor_rate` added, and no `max-size-buffer` setting, we want to limit framerate to 5 FPS)
```
...
! queue ! videoscale ! video/x-raw,width=640,height=480 ! tensor_converter
! tensor_transform mode=arithmetic …
```
> [TensorRate/Filter] Skip inference when QoS events arrive

- debian/control
This patch fixes some typos in debian/control
- MUlti-Arch --> Multi-Arch
> [Fix/Debian] Fix some typos in debian/control

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
In Android testcase, remove unnecessary format conversion to glimagesink.
> [Android/Test] remove unnecessary format conversion

- ext/nnstreamer/extra/nnstreamer_protobuf_grpc.cc
- ext/nnstreamer/extra/nnstreamer_protobuf_grpc.h
- ext/nnstreamer/tensor_sink/tensor_sink_grpc.c
- ext/nnstreamer/tensor_source/tensor_src_grpc.c
This patch implement a reverse pair of gRPC tensor_source/tensor_sink.
(i.e., tensor_source as client and tensor_sink as server)
> [gRPC] Implement tensor_source (client) and tensor_sink (server)      

- api/capi/include/nnstreamer-capi-private.h
- api/capi/include/nnstreamer.h
- api/capi/src/nnstreamer-capi-util.c
- tests/tizen_capi/unittest_tizen_capi.cc
Fix typo and add new function to get the nnfw type by subplugin name.
> [C-Api] define sub-plugin names

- api/android/build-android-lib.sh
- After Android API level 28, the introduced
`AMediaCodecOnAsyncNotifyCallback` make compile error.
- Make build script to patch this part after
https://android.googlesource.com/platform/frameworks/av/+/master/media/ndk/include/media/NdkMediaCodec.h#117
- This resolves #2899 
> [android/build] Patch NDK source to prevent build error @open sesame 12/01 15:52

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- meson_options.txt
- packaging/nnstreamer.spec
This patch supports the GPU Delegate functionality on Tizen platform.
NNStreamer filter for TFLite2 GPU delegate only supports OpenCL backend
since GLES v3.1 backend has a constraint that Invoke() must be called
from the same EGLContext.
If both tensorflow2_lite_support and tensorflow2_gpu_delegate_support
are set as 1 in nnstreamer.spec, GPU Delegate functionality is enabled.
If tensorflow2_gpu_delegate_support is set but tensorflow2_lite_support
is 0, then tensorflow2_gpu_delegate_support option is ignored.
~~Since Tensorflow2 GPU delegate is not ready,
tensorflow2_gpu_delegate_support is set as 0 in this patch.~~
* Enable …
> [Filter/tflite] Support GPU Delegate on Tizen

- packaging/nnstreamer.spec
This patch excludes auto-generated files from coverage analysis.
It's mostly related to protobuf/flatbuf build process.
> [Coverage/Fix] Exclude auto-generated files from coverage analysis

- ext/nnstreamer/tensor_filter/meson.build
- meson.build
- nnstreamer_example/meson.build
command: meson build -Dtensorrt-support=disabled
log: ERROR: Unknown variable "tensorrt_deps".
Without empty dependency declaration, features can not recognize
"tensorrt_deps"
Ditto grpc.
> [meson] Add deps declaration for tensorrt, grpc

- tests/tizen_capi/unittest_tizen_capi.cc
set build root (current dir) if env var is not set.
> [Test] path to build dir

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
- ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
- Add missing doxygen tags
- Existing snpe filter only use the final layer of the given model.
- This patch makes the filter support multiple output layers.
There are two ways of set output layer:
1.  Use custom property
```
"appsrc name=srcx ! " +
"other/tensor,dimension=(string)3:300:300:1,type=(string)float32,framerate=(fraction)0/1 ! " +
"tensor_filter framework=snpe " + "model=" + model.getAbsolutePath() +
" custom=OutputLayer:concat;concat_1 ! " +
"tensor_sink name=sinkx";
```
2. Use tensor info
```
"appsrc name=srcx ! " +
"other/tensor,dimension=(string)3:300:300:1,type=(string)float32,framerate=(fraction)0/1 ! " +
"tensor_filter framework=snpe " + "model=" + model.getAbsolutePath() +
" output=91:1917:1:1,4:1:1917:1 outputtype=float32,float32 outputname=concat,concat_1 ! " + …
```
> [filter/SNPE] Support multiple output layers

- tests/nnstreamer_grpc/unittest_grpc.cc
- tests/nnstreamer_sink/unittest_sink.cc
- Fix signed vs unsigned comapre in unittest_grpc
- Make unittest_sink properly get command line option like `--gst-plugin-path=`
> [unittest] Fix signed-unsigned compare and command line option

- tests/nnstreamer_grpc/get_available_port.py
- tests/nnstreamer_grpc/runTest.sh
This patch fixes gRPC unittests to use an unused port for each test.
Without this patch, it could make undesirable hangs on the CI server.
> [Fix/gRPC] Fix gRPC unittests to use an unused port for each test

- api/android/build-android-lib.sh
When building Android lib, remove unnecessary file (tf-lite lib) in ONE package.
> [Android/Build] remove unnecessary so

- debian/nnstreamer.links
- debian/rules
This patch fixes the broken symlink for DEB_HOST_MULTIARCH environment
variable. This patch solves the build break issue of `nntrainer`
```bash
$ dpkg-query -L nnstreamer:amd64
...
/usr/lib/$(DEB_HOST_MULTIARCH)
/usr/lib/$(DEB_HOST_MULTIARCH)/libnnstreamer.so
```
> [Debian] Fix the broken symlink

- tools/development/parser/types.h
We do not need to load up actual GObjects for this parser.
Thus, the data structures should be simplied.
Define substitute data types for GST Elements as well.
> [Tools/Parser] Update gstparser's types @open sesame 12/3 12:43

- gst/nnstreamer/include/nnstreamer_plugin_api.h
- gst/nnstreamer/tensor_common.c
- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_demux/gsttensordemux.c
- gst/nnstreamer/tensor_filter/tensor_filter.c
- gst/nnstreamer/tensor_if/gsttensorif.c
- tests/common/unittest_common.cc
- tests/meson.build
- tests/nnstreamer_sink/unittest_sink.cc
Add get tensors cap common function.
If the number of tensors is 1, it is to cover the case that only othenr/tensors is supported by peer pad.
> [TensorCommon] Add get tensors cap common function @open sesame 11/18 16:59 

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
- api/android/api/src/main/jni/nnstreamer-native-api.c
Fix test failure case, release thread specific key when closing native handle.
> [Android] fix resource leak

- tools/development/parser/grammar.y
- tools/development/parser/types.c
- tools/development/parser/types.h
We do not need to create GST objects with this parser.
Do not use GST object invoking macros.
> [Tools/Parser] Replace GST macros to dummy

- gst/nnstreamer/tensor_rate/gsttensorrate.c
- tests/meson.build
- tests/nnstreamer_rate/unittest_rate.cc
This patch adds some unittests for tensor_rate.
It increases the coverage of `gsttensorrate.c` from 67.7% to 78.3%.
> [TensorRate/Tests] Add some unittests for tensor_rate @open sesame 12/03 09:50

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
- api/android/api/src/main/AndroidManifest.xml
- Permission `WRITE_EXTERNAL_STORAGE` is not necessary for test
- Remove the permission
> [android/test] Remove unnecessary permission @open sesame 12/14 18:33

- api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
- api/android/api/src/main/AndroidManifest.xml
Merging for lts/1.6.y
- WRITE_EXTERNAL_STORAGE permission is not necessary for test
- Remove the permission
> [lts][android/test] Remove unnecessary permission @open sesame 12/14 18:33

- packaging/nnstreamer.spec
Since nnfw works on on x86 architecture for the Tizen emulator, This
patch enables the nnfw filter when building x86 architecture.
* https://dashboard.tizen.org/index.code?sr=submit/tizen/20201214.093059
> [Spec] Enable nnfw filter on x86 architecture

- packaging/nnstreamer.spec
- tests/nnstreamer_grpc/runTest.sh
This patch disables some components in tizen-6.0 profile.
The below does not work in tizen-6.0
- tensorflow-lite2
- grpc/flatbuffers
---> This needs some revision on grpc because grpc/protobuf works well. 
2. Run test: [*] Passed [ ]Failed []Skipped
> [Spec] Disable some components in tizen-6.0 profile @open sesame 12/15 17:00

- tools/development/parser/grammar.y
- tools/development/parser/types.h
Replacing GST methods with parser-only logic:
Rule 3 includes:
- chain
- openchain
- link
- pads
- morepads
> [Tools/Parser] Parser Rule #3: chain, openchain, link, pads, morepads

- api/android/build-android-lib.sh
This patch updates the build script to support an extra argument for the TensorFlow Lite version to use. The version can be given using the '--enable-tflite' option as follows: --enable-tflite=yes:1.13.1. Note that 1.13.1 can be replaced with other valid versions, 1.9.0, 1.15.2, and 2.3.0.
Resolves: #2904
See also: #2948
V2: To address https://github.com/nnstreamer/nnstreamer/pull/2950#pullrequestreview-552220892, the following commit is appended; 
- [Android/Build] Add an option to display help messages 
```bash
$ bash ./build-android-lib.sh --help
Build script for Android NNStreamer API Library
- Before running this script, below variables must be set.
- ANDROID_SDK_ROOT: …
```
> [Android/TFlite] Support an extra argument for the TFLite version to use

- api/capi/include/nnstreamer.h
Fix invalid parameter direction of the C-API.
> [C-API] fix invalid parameter direction

- api/android/api/src/main/jni/Android-tensorflow-lite.mk
Hide symbols in tensorflow-lite lib, to prevent conflict / exception case of tensorflow-lite and nnfw (ruy library).
> [Android/TF-lite] prevent conflict to nnfw @open sesame 12/16 17:53

- api/android/build-android-lib.sh
Fix invalid path to nnstreamer src directory.
> [Android/Build] fix invalid path

- api/capi/doc/nnstreamer_doc.h
This patch removes the unnecessary HTML link for feature/privilege.
* https://code.sec.samsung.net/confluence/pages/viewpage.action?pageId=197150692
> [Docs] Remove unnecessary HTML link for feature/privilege.

- api/android/build-android-lib.sh
NNFW internally uses nnapi library, this can break tf-lite nnapi option on android-11.
Remove this when building with NNFW.
> [Android/Build] remove unnecessary lib for nnapi

- debian/nnstreamer-grpc.install
- ext/nnstreamer/extra/meson.build
- ext/nnstreamer/extra/nnstreamer_grpc_common.cc
- ext/nnstreamer/extra/nnstreamer_grpc_common.h
- ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.cc
- ext/nnstreamer/extra/nnstreamer_grpc_protobuf.cc
- ext/nnstreamer/meson.build
- packaging/nnstreamer.spec
- tests/nnstreamer_grpc/runTest.sh
This patch seperates gRPC IDL dependencies (protobuf/flatbuf) using dlopen().
From now on, gRPC plugin does not have mandatory dependencies for its IDLs.
It resolves https://github.com/nnstreamer/nnstreamer/issues/2931
> [gRPC/Fix] Decoupling gRPC IDL dependencies @open sesame 12/17 10:05

- api/capi/doc/nnstreamer_doc.h
This patch removes the unnecessary HTML link for feature/privilege. It
is backporting work from the main branch.
> [Doc] Remove unnecessary HTML link for feature/privilege.

- api/capi/src/nnstreamer-capi-pipeline.c
- gst/nnstreamer/tensor_demux/gsttensordemux.c
This patch fixes a potential danger after `ml_pipeline_construct()` is called.
Currently, as `ml_pipeline_construct()` does not wait the pipeline state change,
the following APIs such as `set_property` may affect the initial pipeline processing
with dummy data (even if the pipe line is not started).
For example, the below sequence may incurs some problems because the property
is changed while processing the demux's `chain()`.
```
status = ml_pipeline_construct (pipeline, nullptr, nullptr, &handle);
EXPECT_EQ (status, ML_ERROR_NONE);
status = ml_pipeline_element_get_handle (handle, "demux", &demux_h);
EXPECT_EQ (status, ML_ERROR_NONE);
status = ml_pipeline_element_set_property_string (demux_h, "tensorpick", "1,2"); 
EXPECT_EQ (status, ML_ERROR_NONE);
```
It resolves …
> [CAPI] Wait until the pipeline state is changed

- tools/development/parser/grammar.y
- tools/development/parser/types.c
- tools/development/parser/types.h
Replacing GST methods with parser-only logic:
Rule 4 includes:
chain: openchain link PARSE_URL
openchain: PARSE_URL
With Rule 4, uri-element make is created.
> [Tools/Parser] Parser Rule #4: chain/openchain with URL

- debian/rules
- packaging/nnstreamer.spec
Because the SSAT result is printed after the tests are finished, the test results are not printed in deadlock status.
Change to print the test group name.
> [TEST/SSAT] Print progress log @open sesame 12/23 09:59

- debian/control
This patch revises the 'Build-Depends' field to use the protobuf v3.12.3, which is provided by nnstreamer/ppa. This also fixes build failure for Focal (and the laters) on the launchpad because of unmet dependencies related to protobuf-compiler17.
See also: #2881 
> [Dist/Debian] Revise 'Build-Depends' to support protobuf (>=3.12) @open sesame 12/30 11:49

- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_decoder/tensordec.c
add new property to get the sub-plugins list of tensor-converter.
> [Converter] property to print sub-plugin list

- ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
- ext/nnstreamer/tensor_converter/tensor_converter_protobuf.cc
- gst/nnstreamer/nnstreamer_conf.c
define name prefix of tensor-converter sub-plugins.
> [Converter/Sub] sub-plugin name prefix

- ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
- packaging/nnstreamer.spec
Even though `pytorch_support` is enabled, the pytorch filter is not
built since the necessary option is omitted. This patch newly adds the
pytorch filter package and the requires option.
2. Run test: [ ]Passed [X]Failed []Skipped
* Fix the loadModel bug in pytorch filter
* Add caffe2 filter package
* First draft
> [Pytorch] Add pytorch & caffe2 filter package and require options @open sesame 01/06 13:51

- tests/nnstreamer_rate/unittest_rate.cc
This is a trivial patch to fix the following -Werror=sign-compare errors in unittest_rate.
```bash
...omission...
[167/223] Compiling C++ object 'tests/59830eb@@unittest_rate@exe/nnstreamer_rate_unittest_rate.cc.o'.
FAILED: tests/59830eb@@unittest_rate@exe/nnstreamer_rate_unittest_rate.cc.o 
...omission...
../tests/nnstreamer_rate/unittest_rate.cc:377:3:   required from here
/usr/src/gtest/include/gtest/gtest.h:1392:11: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Werror=sign-compare]
if (lhs == rhs) {
[165/223] Compiling C++ object 'tests/59830eb@@unittest_rate@exe/nnstreamer_rate_unittest_rate.cc.o'.
FAILED: tests/59830eb@@unittest_rate@exe/nnstreamer_rate_unittest_rate.cc.o 
...omission... …
```
> [Tests/Rate] Fix -Werror=sign-compare errors @open sesame 01/08 11:45

- meson.build
The existing logic to resolve dependencies on nvinfer and nvparsers have bugs as follows:
1) Even though it is failed to find_library(), the declare_dependency()
creates a valid dependency object that returns True for .found(). For
this reason, the feature is enabled with some missing libraries.
2) Checking for required header files, NvUffParser.h and NvInfer.h, has
been omitted.
This patch fixes the above bugs.
FYI, I attached meson and ninja logs on my machine.
```bash
$ rm -rf build/ && meson build
The Meson build system
Version: 0.50.1
Source dir: /home/wook/Work/NNS/nnstreamer
Build dir: /home/wook/Work/NNS/nnstreamer/build
Build type: native build
Project name: nnstreamer
Project version: 1.7.1
Native C compiler: cc (gcc 8.4.0 "cc …
```
> [Meson/TensorRT] Fix bugs in resolving dependencies on nvlibs @open sesame 01/08 11:45

- api/capi/include/nnstreamer-single.h
- api/capi/include/nnstreamer.h
- tests/tizen_capi/unittest_tizen_capi.cc
When calling `ml_single_invoke()` after set the timeout option,
`ml_single_close()` should be called before destorying the inference
data. If not, the inference engine might try to access the data, which
is already freed by `ml_tensors_data_destroy()`.
This patch updates the related test cases.
* Resolves: #2959
> [C-API] Fix the occasional Segmentation fault in test case. @open sesame 01/13 20:20

- api/android/api/src/main/java/org/nnsuite/nnstreamer/Pipeline.java
- StateCallback occasionally fails to get initial state changes (null -> ready or ready -> pause)
- Assign `mStateCallback` before `ml_pipeline_construct`
- This resolves #2995 
> [Java-API] Fix `StateChangeCallback` @open sesame 01/14 12:19

- api/android/api/src/main/java/org/nnsuite/nnstreamer/Pipeline.java
- StateCallback occasionally fails to get initial state changes (null -> ready or ready -> pause)
- Assign `mStateCallback` before `ml_pipeline_construct`
> [lts][Java-API] Fix `StateChangeCallback` @open sesame 01/14 12:19

- tests/nnstreamer_filter_extensions_common/meson.build
This is a trivial patch to fix wrong option values following the '-i' option of 'sed' in the meson build script. Without this patch, some useless files such as "unittest_tizen_custom.cc'.cc'" are generated in the build directory.
```bash
build/tests/nnstreamer_filter_extensions_common  (main) $ ls -1
...omission...
unittest_tizen_custom
unittest_tizen_custom.cc
"unittest_tizen_custom.cc'.cc'"
unittest_tizen_custom-set
unittest_tizen_custom-set.cc
"unittest_tizen_custom-set.cc'.cc'"
unittest_tizen_python3-get
unittest_tizen_python3-get.cc
"unittest_tizen_python3-get.cc'.cc'"
unittest_tizen_python3-set
unittest_tizen_python3-set.cc
"unittest_tizen_python3-set.cc'.cc'"
unittest_tizen_tensorflow
unittest_tizen_tensorflow.cc …
```
> [Tests/Meson] Fix wrong option values for 'sed' in meson.build

- api/capi/include/nnstreamer-single.h
- api/capi/src/nnstreamer-capi-single.c
If filter sub-plugin allocates output tensor, single-shot notifies releasing output buffer when closing the single handle.
In this case, we dont need to free the output handle itself. Calling single-close and destroy-outdata functions will make an error.
> [C-API] fix double free case

- api/capi/capi-ml-common.pc.in
- api/capi/meson.build
- packaging/nnstreamer.spec
pc file was missing for capi-ml-common-devel package.
This patch adds pc file so that capi-ml-common can be included from
`pkg-config`
> Add pc file for capi-ml-common-devel

- tests/gen24bBMP.py
- tests/nnstreamer_merge/generateTest.py
- tests/transform_stand/generateTest.py
- tests/transform_transpose/generateTest.py
- Call python `pack` only once with list.
- This reduces test time on yocto qemu environment.
REF: https://stackoverflow.com/questions/9940859/fastest-way-to-pack-a-list-of-floats-into-bytes-in-python/9941455
On yocto qemux86-64,
`tests/nnstreamer_decoder/runTest.sh` takes about 33mins.
With this commit, it takes 2mins with this commit.
> [test/SSAT] Optimize python script with lazy `pack`

- debian/control
- debian/nnstreamer-api-common-dev.install
- debian/nnstreamer-dev.install
Currently, `capi-ml-common-devel` was added to rpm package but
corresponding package was not available in debian.
This patch adds `nnstreamer-api-common-dev` to the debian which
corresponds with `capi-ml-common-devel` in rpm.
> [debian] Add nnstreamer-api-common-dev package

- README.md
Change coverity link of the badge because coverity project has been
changed.
> [Badge] Change coverity link of the badge @open sesame 01/22 16:53

- api/capi/src/nnstreamer-capi-pipeline.c
- ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_if/gsttensorif.c
1. handle error case when failed to map the gst buffer.
2. init variable in cls constructor.
> [Coverity] fix coverity issues

- tests/nnstreamer_if/unittest_if.cc
- tests/unittest_util.c
Resolve the coverity issue
1. Unchecked return value
2. Logically dead code
> [Coverity] Resolve coverity issue

- api/capi/include/nnstreamer.h
If ml_custom_easy_invoke_cb() returns negative error values, the
constructed pipeline does not work properly anymore. This patch adds the
Note comments for this.
> [C-API] Add note comments for custom easy filter.

- api/capi/include/nnstreamer.h
This patch adds Add NNtrainer enum to singleshot api, `ml_nnfw_type_e`
> [ACR] Add NNTrainer enum to singleshot api

- ext/nnstreamer/tensor_filter/meson.build
- meson_options.txt
Some NPU vendors such as Verisilicon integrate their neural network
stack within TF-LITE through NNAPI for Linux OS.
https://github.com/VeriSilicon/tensorflow/commit/07a2d86919d2c27dc350a065ab01c815a3f4aa15
Thus, this option enables NNAPI support on tf-lite tensor filter plugin
for non android build such as NPU delegates could use NNAPI on non
Android OS.
Signed-off-by: Xavier Roumegue <xavier.roumegue@nxp.com>
---
```bash
characters or so. …
```
> [BUILD/TF-Lite] Add nnapi delegate option

- tools/development/parser/grammar.y
- tools/development/parser/types.c
- tools/development/parser/types.h
All remaining parsing rules for "gstreamer-string --> pbtxt" are written.
The next steps include aux parts of the parser (reference resolving) and integration with the pbtxt converter.
commit 4acbe348fe2bf8224990d1278bcb80b98965fbac
Date:   Fri Dec 11 15:36:14 2020 +0900
[Tools/Parser] Rule Implementation Done
Redefine "GstBin" and "GstElement" for nns-parser.
As we do not create actual pipelines from strings,
we only need symbolic data.
All the parsing rule implementations are fixed for nns-parser.
commit 14ef5e806db8b118ea1446863543db54f02a2f76
Date:   Mon Nov 30 16:04:04 2020 +0900
[Tools/Parser] Remove GSTPARSE functions
GSTPARSE has …
> [Tools/Parser] Other All Remaining Rules

- api/capi/capi-nnstreamer.pc.in
- ~**#3011** Add pc file for capi-ml-common-devel~
- ~**#3013** [debian] Add nnstreamer-api-common-dev package~
- ~**#3014** [Chores] Merge platform/tizen_error into ml_error~
- [pkg-config] Update require to capi-nnstreamer
```
As users of capi-nnstreamer.pc need `capi-ml-common.pc`, it should be
added to the require although currently, capi-ml-common.pc has the
exactly same include path so nothing really changes.
This is more of a future proof that one day capi-ml-common.pc might
point to a different include header.
```
> [pkg-config] Update require section of capi-nnstreamer @open sesame 01/25 22:25

- ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
Hello nnstreamer community,
Please find the few patches I had to develop to get [mobilenet_ssd_v2_coco](https://coral.googlesource.com/edgetpu/+/refs/heads/release-chef/test_data/mobilenet_ssd_v2_coco_quant_postprocess.tflite) neural network model imported from Google corail database running on iMX8MP NXP SoC.
The main enhancement is related to the default output tensor mapping within tensor decoder bounding boxes in TF-SSD mode, which is incompatible with [default object detection NN output tensors mapping delivered by tensor flow lite community](https://www.tensorflow.org/lite/models/object_detection/overview#output_signature) used nowadays.
Even though neural network output mapping could be reorganized offline to fit default tensor decoder bounding boxes mapping, this might be …
> [Decoder/BoundingBox/TF-SSD] Add output tensors mapping configuration option, plus minor fixes & enhancements

- api/capi/src/nnstreamer-capi-util.c
- debian/control
- debian/nnstreamer-dev-internal.install
- debian/nnstreamer-dev.install
- gst/nnstreamer/meson.build
- gst/nnstreamer/nnstreamer_conf.c
- gst/nnstreamer/nnstreamer_internal.h
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- packaging/nnstreamer.spec
Add internal header for sub-plugins and native APIs.
After separating API repo, native API build will include this header.
> [Build] internal header for APIs

- api/capi/src/nnstreamer-capi-pipeline.c
- api/capi/src/nnstreamer-capi-single.c
The additional log messages are required because returning the error code `ML_ERROR_STREAMS_PIPE` gives very little information for the abnormal situation.
> [ML-API] add log messages

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- tests/nnstreamer_plugins/unittest_plugins.cc
Modify the tensor filter to automatically detect the framework without specifying the framework option.
The default value of the framework is changed to "auto".
Related issue: #2702 
> [Filter] Framework auto detection without specifying the option  @open sesame 2/03 15:26 

- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
This patch adds mutex to count number of callbacks.
> [lts-1.6.y][Fix/UnitTest] Add mutex to count number of callbacks @open sesame 2/4 16:45

- .TAOS-CI/.gbs.conf
- Documentation/getting-started-tizen.md
- ext/nnstreamer/tensor_filter/vivante/README.md
- ext/nnstreamer/tensor_filter/vivante/tensor_filter_subplugin.c
- packaging/nnstreamer.spec
This commit is to use a (1) ./.TAOS-CI/.gbs.conf or (2) ./packaging/.gbs.conf file
by default to support customized GBS repositories for each GitHub repository
because the (3) ~/.gbs.conf file of user account (e.g., www-data) can be used among
lots of repositories.
**Changelog**
* Added ./.TAOS-CI/.gbs.conf
* Added ./packaging/.gbs.conf
* Replaced https with http to avoid ssl issue due to firewall
> TAOS-CI: Use .TAOS-CI/.gbs.conf by default @open sesame 02/05 11:07

- packaging/nnstreamer.spec
fix package name required for devel packages.
> [lts-1.6.y][Build] fix package name

- debian/rules
Remove unnecessary build option for sub-plugins, default val is auto.
> [Build] remove unnecessary option

- packaging/nnstreamer.spec
- tests/nnstreamer_grpc/runTest.sh
This patch makes gbs skip ssat tests on qemu/aarch64 env.
In gRPC 1.35.0, some behaviors are not supported on qemu/aarch64.
See the below error log
```
[  119s] qemu: Unsupported syscall: 168
[  119s] E0208 04:45:45.854670498   21089 cpu_linux.cc:41] Error determining current CPU: Function not implemented
[  119s]
[  119s] Unsupported setsockopt level=1 optname=15
[  119s] E0208 04:45:45.874942631   21089 socket_utils_common_posix.cc:222] check for SO_REUSEPORT: {"created":"@1612759545.874068306","description":"Protocol not available","errno":92,"file":"/home/abuild/rpmbuild/BUILD/grpc-1.35.0/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":198,"os_error":"Protocol not available","syscall":"setsockopt(SO_REUSEPORT)"}
[  119s] qemu: uncaught target signal 4 (Illegal …
```
> [gRPC/Test] Skip SSAT tests on qemu/aarch64

- api/capi/src/nnstreamer-capi-pipeline.c
Do not check restricted list when constructing a pipeline with internal API.
> [C-Api/Tizen] restricted elements for internal function

- tests/tizen_capi/unittest_tizen_capi.cc
After #3002, the user should destroy the output handle.
> [TEST/single] Destory output data handle

- gst/nnstreamer/hw_accel.c
OSX does not have sys/auxv.h
Add a macro assuming that SIMD is always available for
OSX-AARCH64 (e.g., M1) devices.
Tested at MacBook-Air M1
> [OSX] Build error fix

- tests/nnstreamer_sink/unittest_sink.cc
Some tests do not remove and free temporary files.
Change to remove and free temporary files from `_free_test_data`.
> [TEST] Remove and free temp file

- api/capi/include/nnstreamer.h
Change comment for nntrainer enum to comply convention.
> [CAPI] Change comment to comply convention @open sesame 02/15 15:32 

- tests/common/unittest_common.cc
Fix memory leak of the tensor common unit test.
> [TEST/common] Fix memory leak @open sesame 02/15 15:33

- gst/nnstreamer/nnstreamer_internal.h
add extern for cpp use in internal dev header.
> [Build/Dev] internal header in cpp

- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
1. During the `DBG` mode, the `g_critical` generates an error.
<details>
<summary>error log</summary>
```
$ gbs build -A armv7l --include-all
[  290s] /home/abuild/rpmbuild/BUILD/nnstreamer-1.7.1/ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc:278:15: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'int64_t' {aka 'long long int'} [-Werror=format=]
[  290s]   278 |   g_critical ("%ld invoke average %" G_GINT64_FORMAT ", total overhead %" G_GINT64_FORMAT,
[  290s]   279 |       tflite_internal_stats.total_invoke_num,
[  290s]       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  290s]       |                             |
[  290s]       |                             int64_t {aka long long int}
[  290s] …
```
> [TFLite] fix a minor bug

- tests/nnstreamer_plugins/unittest_plugins.cc
When testing auto option, *.tflite is used so nnstreamer tries to find
tflite in the framework. However when tflite is disabled, there is no
tflite support leading the test to segfault (tested in ubuntu 18.04)
This patch fixes the issue
> [Fix/test] fix unittest fail when no tflite given

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
- meson.build
Because of breaking changes of TF 2.4
https://github.com/tensorflow/tensorflow/blob/e43be76009614be88454d2fdf2fe702acc5bab77/RELEASE.md#breaking-changes-1
, we need to use different C-API usages for TensorFlow.
The corresponding change is
> C-API functions TF_StringDecode, TF_StringEncode, and TF_StringEncodedSize are no longer relevant and have been removed; see core/platform/ctstring.h for string access/modification in C.
Fixing #3081
CC: @ggardet
> [TF 2.4] TF C-API breaking changes at 2.4

- ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
The `DBG` flag and log messages are added to check the time of `invoke()` function
> [NNFW] add a timer and DBG flag

- tests/nnstreamer_grpc/runTest.sh
Reverts nnstreamer/nnstreamer#2978
gRPC 1.35.0 & async mode often makes deadlock in the pbuilder.
Before finding the reason, let's revert this.
> Revert "[gRPC/Async] Extend gRPC codes to support async/non-blocking APIs"

- meson.build
This patch supports alternative target name to find pkg dependency.
For example, in case of armnn, the dependency name should be
`Armnn` not `armnn` to find its cmake config files.
Related issue: https://github.com/nnstreamer/nnstreamer/issues/3079
> [meson] supports alternative target name to find pkg dependency @open sesame 02/22 15:50

- meson.build
This patch checks the dependency using alternative name even with 'enabled' option.
resolves #3079 
> [Fix/Meson] Find the dependency using alternative name

- packaging/nnstreamer.spec
With the side-effects of meon join_paths,
absolute paths of bindir/libdir is working,
this is not recommended.
Fix the path inputs; use relative paths along with
prefix.
Fixes #2642
> [Dist/RPM] Fix meson path options.

- meson.build
The existing build dependency checking mechanism for MvNCSDK2 is
unnecessarily complex. This patch revises it.
See also: https://review.tizen.org/gerrit/#/c/platform/adaptation/npu/intel-libmvnc/+/254171/
Reported-by: Jaeyun Jung <jy1210.jung@samsung.com> @jaeyun-jung 
> [Meson] Revise build dependency checking mechanism for MvNCSDK2 @open sesame 03/23 12:48

- tests/nnstreamer_rate/unittest_rate.cc
This patch fixes coverity issues (CID 314892, 314893)
- UNINTENDED_INTEGER_DIVISION
> [Coverity] Fix coverity issues (CID 314892, 314893)

- tests/common/unittest_common.cc
- tests/cpp_methods/unittest_cpp_methods.cc
- tests/gstreamer_join/unittest_join.cc
- tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc
- tests/nnstreamer_filter_edgetpu/unittest_edgetpu.cc
- tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
- tests/nnstreamer_filter_mvncsdk2/unittest_filter_mvncsdk2.cc
- tests/nnstreamer_filter_openvino/unittest_openvino.cc
- tests/nnstreamer_grpc/unittest_grpc.cc
- tests/nnstreamer_if/unittest_if.cc
- tests/nnstreamer_plugins/unittest_plugins.cc
- tests/nnstreamer_rate/unittest_rate.cc
- tests/nnstreamer_sink/unittest_sink.cc
- tests/nnstreamer_source/unittest_src_iio.cc
- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
- tests/tizen_sensor/unittest_tizen_sensor.cc
Resolves #2541
Update test suit names and test names not to contain underscore.
This follows gtest recommendations.
https://github.com/google/googletest/blob/master/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore
Signed-off-by: Juyeong Lee <2jy22@naver.com>
> Remove underscore in test names

- ext/nnstreamer/tensor_decoder/tensordec-pose.c
- ext/nnstreamer/tensor_decoder/tensordecutil.c
- tests/nnstreamer_decoder_pose/runTest.sh
Hi nnstreamer folks,
This PR adds support for using pose decoder with latest posenet neural network model which are using 17 different key points.
https://www.tensorflow.org/lite/examples/pose_estimation/overview#model_description
A sub plugin pose decoder option(3) has been added to specify the body joint labels.
If the option is not set or the specified file is not present, the default (14) pose labels are used as fallback.
Signed-off-by: Xavier Roumegue <xavier.roumegue@nxp.com>
Build test: [X]Passed [ ]Failed [ ]Skipped
Run test: [X]Passed [ ]Failed [ ]Skipped
> Decoder pose

- ext/nnstreamer/tensor_decoder/tensordecutil.c
When loading data from file, use param to get the contents size.
> [Decoder] file content size

- gst/nnstreamer/tensor_transform/tensor_transform.c
- gst/nnstreamer/tensor_transform/tensor_transform.h
Currently only float32 can use stand mode in tensor-transform.
Add option to set output type and calc stand mode.
> [Transform] tensor type in stand mode

- Documentation/writing-subplugin-tensor-filter.md
- debian/control
- debian/nnstreamer-configuration.install
- debian/nnstreamer-core.install
- debian/nnstreamer-test-dev.install
- debian/rules
- meson.build
- nnstreamer.pc.in
- packaging/nnstreamer.spec
- tests/nnstreamer_filter_extensions_common/meson.build
- [Packaging] Add test-devel to rpm/dpkg
```
Add test-devel to rpm/dpkg
This patch...
1. offers `nnstreamer-template.ini.in` from test-devel package
1. offers `subplugin_unittest_template.cc.in` from test-devel package
1. for rpm test-devel, it renames /etc/nnstreamer.ini until test-devel
is unintalled
1. add pkg-config variable to locate test related templates
Resolves #3124
Tested using gbs and pdebuild
```
- [Doc] Add documentation of using test-devel
```
Add documentation of how to utilize test-devel package in the
perspective of subplugin developer
2. Run …
```
> [Packaging] Add test-devel to rpm/dpkg

- gst/nnstreamer/tensor_transform/tensor_transform.c
If option string is empty, tensor-transform cannot parse the mode and will crash application.
Add error case for empty option string.
> [Transform] handle empty option string case

- packaging/nnstreamer.spec
As nnstreamer mata package was not containing `files` section, it led to
the recent SR fail, this patch resolves the issue.
Also add %config directive to the configuration file
related issue: https://dashboard.tizen.org/index.code?sr=submit/tizen/20210317.111732
> [Fix] Add missing file section in rpm build

- ext/nnstreamer/tensor_filter/tensor_filter_python3.cc
This fixes the following build issue:
error: 'runtime_error' is not a member of 'std'
|   192 |       throw std::runtime_error (dlerror ());
https://en.cppreference.com/w/cpp/error/runtime_error
Signed-off-by: Xavier Roumegue <xavier.roumegue@nxp.com>
3. Unit tests: [*]Passed [ ]Failed [ ]Skipped
> [Filter/Python3] Include <stdexcept> for std::runtime_error support

- debian/nnstreamer-flatbuf.install
- ext/nnstreamer/tensor_converter/meson.build
- ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
- ext/nnstreamer/tensor_decoder/meson.build
- ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc
- gst/nnstreamer/include/tensor_typedef.h
- packaging/nnstreamer.spec
- tests/nnstreamer_flexbuf/runTest.sh
Add tensor converter and decoder subplugin of flexbuffer.
Example launch line:
gst-launch-1.0 videotestsrc !  video/x-raw,format=RGB,width=320,height=240 ! tensor_converter ! tensor_decoder mode=flexbuf ! other/flexbuf ! tensor_converter ! tensor_decoder mode=direct_video ! videoconvert !  videoscale ! video/x-raw,width=320,height=240 ! xvimagesink
Note: Custom flexbuffer will be supported by callback function and python script.
> [Edge-AI] Add flexbuffer converter and decoder @open sesame 03/16 10:58

- debian/control
- debian/nnstreamer-grpc-flatbuf.install
- debian/nnstreamer-grpc-protobuf.install
- debian/rules
- tests/nnstreamer_grpc/runTest.sh
This PR includes old commits including
- disable gRPC in debian
- perform async tests in Tizen env.
Unfortunately, gRPC/Debian seems unstable, which often causes hanging or test failures.
I'm not sure why but it seems to be related gRPC debian packaging issue.
For now, gRPC is only supported in Tizen env.
See also: https://github.com/nnstreamer/nnstreamer/issues/3089
> [gRPC/debian] Disable gRPC in Debian and perform async tests in Tizen env.

- tests/nnstreamer_repo_dynamicity/runTest.sh
In case the unit tests are run from their installed directory,
unittest_repo binary can't be found in this case because install test
directory path and unittest_repo binary location are invalid.
This fixes regression introduced by bfb6630ff and 0c02456ba
Signed-off-by: Xavier Roumegue <xavier.roumegue@nxp.com>
> tests/nnstreamer_repo_dynamicity: Fix unittest_repo binary path handling

- ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
- ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
- gst/nnstreamer/tensor_converter/tensor_converter.c
Remove memory copy in converter.
Memory allocation occurs two times on g_memdup and gst_memory_new_wrapped.
Changed to use gst_memory_share.
No memory copy is performed and the memory region is simply shared.
> [Converter] Remove memcpy in converter @open sesame 03/30 11:19

- packaging/nnstreamer.spec
Add virtual conf package to resolve build dependency issue as suggested
in https://github.com/nnstreamer/api/pull/21#issuecomment-804599118
With this patch, it is now possible to install devel package with
`/etc/nntrainer.ini` or the packager choose to use `test-devel` when
building.
See also nnstreamer/nntrainer#1034
**Evaluation Method**
Cross building with nntrainer package
Cc: Myungjoo Ham <myungjoo.ham@samsung.com>
> [RPM] Add virtual conf package @open sesame 03/23 14:18

- ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
set init value of sensor type. 'all' means no specific sensor and if user does not set type in pipeline, it will be failed.
> [TizenSensor] init sensor type

- tests/tizen_sensor/unittest_tizen_sensor.cc
ret variable is used without initialization. This patch fixes the bug.
> [Test] Fix the Svace issue

- gst/nnstreamer/tensor_data.c
- gst/nnstreamer/tensor_data.h
- gst/nnstreamer/tensor_if/gsttensorif.c
- gst/nnstreamer/tensor_transform/tensor_transform.c
- gst/nnstreamer/tensor_transform/tensor_transform.h
- tests/transform_stand/checkResult.py
- tests/transform_stand/generateTest.py
- tests/transform_stand/runTest.sh
- "channel" is the first dimension.
- Support channel-wise default and dc-average transform
- Add SSAT testcases for stand
> [tensor_transform] Add "per-channel" option to stand mode

- ext/nnstreamer/tensor_filter/meson.build
When tensorflow2-lite is enabled, set dependency tf2-lite to build EdgeTPU sub-plugin.
> [Filter/EdgeTPU] tf-lite ver for EdgeTPU

- ext/nnstreamer/extra/nnstreamer_protobuf.cc
- ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
- ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
- ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
- gst/nnstreamer/tensor_converter/tensor_converter.c
A memory leak occurred because the name of the tensor was not released.
Free the name of the tensor and set the default name as "" instead of "Anonymous"
> [Converter] Fix mem leak of the converter

- debian/nnstreamer-python3.links
This patch fixes install link name of python3 module.
As python subplugin scripts import `nnstreamer_python`,
its name should be also matched.
> [Fix/Python3] Fix install link name of python3 module

- gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
- gst/nnstreamer/tensor_converter/tensor_converter.c
- Do not reset tensor config when flush event occurs, just clear the buffers
> [aggregator/converter] Fix when GST_EVENT_FLUSH_*

- ext/nnstreamer/extra/nnstreamer_protobuf.cc
- ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
- ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
- ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
- ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc
- gst/nnstreamer/include/nnstreamer_plugin_api_converter.h
- gst/nnstreamer/tensor_converter/tensor_converter.c
- tests/nnstreamer_plugins/unittest_plugins.cc
- Add error handling code for tensor converter and decoder subplugins.
- Add testcases for tensor converter and decoder subplugins.
> [Converter/Decoder] Add error handling code and testcases

- tests/common/unittest_common.cc
Add unittests for tensor common functions.
> [TEST] Add tensor common unittests

- gst/nnstreamer/tensor_converter/tensor_converter.c
- tests/nnstreamer_converter/unittest_converter.cc
- tests/nnstreamer_decoder/unittest_decoder.cc
Add tensor converter and decoder subplugin test
> [TEST] Add converter and decoder subplugins test

- Documentation/contributing.md
- Documentation/hotdoc/sitemap.txt
Change menu tree name of Documentation/contributing.md.
Related issue: #3100
Before:
After:
> [Doc] Change menu tree name of contributing doc.

- gst/nnstreamer/tensor_common.h
- gst/nnstreamer/tensor_common_pipeline.c
- gst/nnstreamer/tensor_merge/gsttensormerge.c
- gst/nnstreamer/tensor_mux/gsttensormux.c
Clear old buffer in collect pad data when received flush event.
> [Mux/Merge] clear collect pad data

- gst/nnstreamer/tensor_filter/tensor_filter_common.c
This patch maps *.ini as nntrainer to utilize auto detection for
nntrainer.
> Enable detection for nntrainer singleshot

- tools/development/parser/grammar.y
- tools/development/parser/types.c
- tools/development/parser/types.h
These aux routines emulate GST Objects so that
parsers wouldn't rely on actual GStreamer libraries
and pipeline instances.
This commit is WIP and will be continued by DJ.
> [Tools/Parser] GST Object Emulators

- tests/nnstreamer_decoder_boundingbox/runTest.sh
To guarantee backward compatibility with the deprecated modes(`tflite-ssd`, `tf-ssd`), some test cases are required.
see also: https://github.com/nnstreamer/nnstreamer/pull/3195#pullrequestreview-640919317
> [Decoder/BoundingBox] add a testcase for the deprecated modes

- debian/rules
- gst/meson.build
- gst/mqtt/meson.build
- gst/mqtt/mqttcommon.h
- gst/mqtt/mqttelements.c
- gst/mqtt/mqttsink.c
- gst/mqtt/mqttsink.h
- gst/mqtt/mqttsrc.c
- gst/mqtt/mqttsrc.h
- meson.build
- meson_options.txt
- packaging/nnstreamer.spec
This PR adds skeleton codes for GStreamer plugins that enable GStreamer/NNStreamer pipelines to publish and subscribe MQTT topics. By default, the build option for the MQTT plugins is disabled for the Ubuntu and Tizen platforms to avoid CI build break. 
> [Gst/MQTT] Add buildable skeleton codes for MQTT plugins 

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_tvm.cc
- meson.build
- meson_options.txt
- ~~User must specify tensors `shape` and `type` for both input and output~~
- `dlpack` and either `tvm` or `tvm_runtime` should be included
- Only supports tvm model compiled with relay (graph_executor)
See also: #3085
> [filter/TVM] Add tensor-filter subplugin for TVM

- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Initialize tensor-info struct before calling filter callback.
> [Test/NNFW] init info in testcase

- ext/nnstreamer/extra/nnstreamer_protobuf.cc
- ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
- ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
- ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
- ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc
- ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
- ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
- ext/nnstreamer/tensor_decoder/tensordec-pose.c
- tests/nnstreamer_decoder/unittest_decoder.cc
Since the ref count is raised when `gst_buffer_get_all_memory ()` is used,
`gst_memory_unref ()` has to be called after using the memory.
Furthermore, if the process is finished with an unexpected error,
the allocated memory has to be released.
> [Decoders] fix the mem leaks of the external decoders @open sesame 04/29 13:06 

- .clang-format
add space when using c-style typecast.
> [Format] clang format for typecast

- gst/mqtt/mqttcommon.h
- gst/mqtt/mqttsink.c
- gst/mqtt/mqttsink.h
- gst/mqtt/mqttsrc.c
- gst/mqtt/mqttsrc.h
This PR addresses #3196, which is timestamp synchronization between MQTT pipeline nodes. Other changes included in this PR as follows:
- Introduce a new property, max-buffer-size
- Using this property, mqttsink could exploit a static-sized buffer instead of dynamically allocating buffers according to the changes of incoming buffer' size.
- Support dynamic buffer re-allocation when the static-sized buffer mode is disabled
- To handle the case when the size of an incoming buffer is larger than the existing dynamically allocated one, mqttsink frees the existing buffer and re-allocates a new buffer.
> [Gst/MQTT] Support timestamp synchronization between nodes and dynamic buffer re-allocation

- gst/nnstreamer/nnstreamer_conf.c
- gst/nnstreamer/nnstreamer_subplugin.c
- gst/nnstreamer/nnstreamer_subplugin.h
- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_decoder/tensordec.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
Util function to get registrable subplugins list.
If conf file is not loaded (or does not exists), nnstreamer cannot get the subplugin list from configuration.
In this case (e.g., Android), conveter cannot set the pad template from subplugins, and will make negotiation failure.
To prevent this error, get subplugins from table and conf file.
> [Conf/Subplugin] get registered subplugins

- tests/nnstreamer_converter/unittest_converter.cc
This patch fixes a build error related to -Werror=sign-compare. Note that this error occurs while building the source code using gcc-7.5.
```bash
[233/241] Compiling C++ object 'tests/59830eb@@unittest_converter@exe/nnstreamer_converter_unittest_converter.cc.o'.
FAILED: tests/59830eb@@unittest_converter@exe/nnstreamer_converter_unittest_converter.cc.o 
ccache c++ -Itests/59830eb@@unittest_converter@exe -Itests -I../tests -Igst/nnstreamer -I../gst/nnstreamer -Igst/nnstreamer/./include/ -I../gst/nnstreamer/./include/ -Igst/nnstreamer/tensor_transform -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/src/gtest -I/usr/src/gtest/include -fdiagnostics-color=always …
```
> [Tests/Converter] Fix -Werror=sign-compare error

- gst/mqtt/mqttcommon.h
- gst/mqtt/mqttsink.c
- gst/mqtt/mqttsink.h
- gst/mqtt/mqttsrc.c
- gst/mqtt/mqttsrc.h
The purpose of this PR is to support just-in-time capability negotiation in the GStreamer pipeline using the capability information included in the message to which the other pipeline node sent.
In detail, this PR contains the following changes:
For the mqttsink, 
- The message header is modified to include a string representation of the fixated GstCaps.
For the mqttsrc,
- A procedure extracting the GstCaps information from the incoming header is added.
- According to the extracted GstCaps information, the pipeline tries to negotiation the capabilities just before processing the first buffer.
> [Gst/MQTT] Support dynamic Caps re-negotiation according to the Caps information sent from the other node @open sesame 05/19 13:00

- tools/development/parser/grammar.y
- tools/development/parser/meson.build
- tools/development/parser/parse.l
- tools/development/parser/toplevel.c
- tools/development/parser/types.c
- tools/development/parser/types.h
This patch updates meson script and resolve build errors.
Please note that delayed links are not considered here.  
It also provides the toplevel program using the parser (i.e., `nnstreamer-parser`)
The below shows its usage example.
```
$ echo "fakesrc name=src ! fakesink name=sink" | ./build/tools/development/parser/nnstreamer-parser
The given string: fakesrc name=src ! fakesink name=sink
got 2 elements and 1 links
linking some pad of fakesrc named src to some pad of fakesink named sink (0/0)
```
TODO LIST
- **gst --> pbtxt**
Supporting delayed links (e.g., queue)
Converting graph to pbtxt
- **pbtxt --> gst**
Implementing pbtxt parser
Converting graph to gst pipeline
- Porting to be available in the python script
> [Tools/Parser] Update meson script and resolve build errors @open sesame 05/10 19:06

- gst/mqtt/mqttsink.c
- gst/mqtt/mqttsink.h
- gst/mqtt/mqttsrc.c
- gst/mqtt/mqttsrc.h
In this PR, the following changes are included:
- Fixes memory leaks reported by Valgrind categorized as definitely lost
- Add a new property to enable debugging outputs
> [Gst/MQTT] Fix memory leaks and add a new property to enable debugging outputs 

- gst/nnstreamer/tensor_merge/gsttensormerge.c
- Set default string value as argument of `g_param_spec_string()`
> [fix/trivial] Fix compile warning of g_param_spec_string in gsttensormerge.c

- gst/mqtt/mqttsrc.c
- gst/mqtt/mqttsrc.h
In order to synchronize incoming streams which have different delays (e.g., two buffers with the same PTS but have arrived at different times), the source should answer the query about the latency from the downstream and be possible to disable the live source mode. This PR addresses this issue as well.
In detail, the following changes are submitted:
- [Gst/MQTT/Src] Handle the GST_QEURY_LATENCY query
- The latency is calculated by subtracting the current running time from the buffer's timestamp.
- To handle the query, the GstBaseSrc vmethod, query(), should be implemented to override GST_QUERY_LATENCY handling.
- [Gst/MQTT/Src] Add a new property to control the live source mode 
- When the live mode is set in the inherited class of the GstBaseSrcClass, the buffer's PTS is automatically …
> [Gst/MQTT/Src] Handle the messages with relatively long jitters or delays @open sesame 05/12 10:20

- gst/nnstreamer/meson.build
- gst/nnstreamer/registerer/nnstreamer.c
- gst/nnstreamer/tensor_crop/meson.build
- gst/nnstreamer/tensor_crop/tensor_crop.c
- gst/nnstreamer/tensor_crop/tensor_crop.h
- jni/nnstreamer.mk
Initial commit to add tensor-crop element.
tensor-crop will crop the incoming buffer with crop info.
TODO: define pads
- 2 sink pads: static tensor for raw data, flexible for crop info
- src pad: flexible with cropped tensor
> [Crop] add tensor-crop

- gst/mqtt/mqttsink.c
- gst/mqtt/mqttsink.h
To activate the delivery_complete callback, the `mqtt-qos` property is required.
> [MQTTsink] add mqtt QoS as a property

- ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
- ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
- ext/nnstreamer/tensor_filter/tensor_filter_tvm.cc
[Fix/Filter] Fix tensors info initialization
- Internal tensors-info is not correctly initialized for some sub filters, causing incompatible format error.
> [Fix/Filter] Fix tensors info initialization

- tools/development/parser/types.c
- tools/development/parser/types.h
This patch finds element name in the pipeline.
> [Tools/Parser] Find element name in the pipeline @open sesame 05/13 13:33

- gst/nnstreamer/tensor_converter/tensor_converter.c
- tests/nnstreamer_plugins/unittest_plugins.cc
- tests/nnstreamer_sink/unittest_sink.cc
Add pad template to handle flex tensors.
tensor-converter supports changing capability from flex to static, or static to flex if downstream element has flex-tensor caps.
> [Converter] support flex tensor

- gst/mqtt/mqttsink.c
The callback `on_message_arrived ()` is not required for MQTTsink because it publishes the messages
> [MQTTsink] remove message arrived cb

- gst/nnstreamer/tensor_crop/tensor_crop.c
- gst/nnstreamer/tensor_crop/tensor_crop.h
tensor-crop has 2 sink pads - raw and info.
- raw: receive raw tensor data to be cropped (other/tensor)
- info: receive crop info (other/tensors-flexible)
The output is cropped tensors (flex tensor format).
TODO
1. define GstTensorCropInfo (x,y,w,h) in tensor_typedef.h
2. add cropping in chain function
> [Crop] add two sink pads

- gst/nnstreamer/tensor_filter/tensor_filter.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- tests/nnstreamer_plugins/unittest_plugins.cc
Add pad template to support flex tensor in tensor-filter.
If incoming tensor is flexible, tensor-filter cannot get the meta from caps.
In this case, tensor-filter gets model info from subplugin and compares buffer size in transform().
That means, if the model handles non-static info (e.g., set-dimension with input info), it cannot support flex tensor.
> [Filter] support flex tensor

- gst/mqtt/mqttsink.c
according to the `paho-c-mqtt`, if the `message_arrived` callback is null, the others are not registered.
For this reason, the removed callback should be existed even they are not called.
https://github.com/eclipse/paho.mqtt.c/blob/64a5ff3c3b71fe019353aeacaebc66a3cf4f3461/src/MQTTAsync.c#L1496-L1504
```c
int MQTTAsync_setCallbacks(MQTTAsync handle, void* context,
MQTTAsync_connectionLost* cl,
MQTTAsync_messageArrived* ma,
MQTTAsync_deliveryComplete* dc)
{
int rc = MQTTASYNC_SUCCESS;
MQTTAsyncs* m = handle;
FUNC_ENTRY;
MQTTAsync_lock_mutex(mqttasync_mutex);
if (m == NULL || ma == NULL || m->c == NULL || m->c->connect_state != NOT_IN_PROGRESS)
rc = MQTTASYNC_FAILURE;
else
{
m->clContext = m->maContext = m->dcContext = context;
m->cl = cl;
m->ma = ma;
m->dc = dc;
} …
```
> [MQTTsink] revive the removed callbacks

- tools/development/parser/convert.c
- tools/development/parser/convert.h
- tools/development/parser/grammar.y
- tools/development/parser/meson.build
- tools/development/parser/toplevel.c
- tools/development/parser/types.c
- tools/development/parser/types.h
This patch converts gst pipeline to pbtxt. It also works on mediapipe demo site.
You can check the example pipeline in the https://viz.mediapipe.dev/
**Usage**
```
$ echo "fakesrc ! tensor_filter ! fakesink " |\
./build/tools/development/parser/nnstreamer-parser
input_stream: "fakesrc"
output_stream: "fakesink"
node: {
calculator: "tensor_filterCalculator"
input_stream: "fakesrc"
output_stream: "fakesink"
}
```
```
$ echo "fakesrc ! tensor_filter ! tee name=t ! queue ! fakesink t. ! queue ! fakesink" |\
./build/tools/development/parser/nnstreamer-parser 
input_stream: "fakesrc"
output_stream: "fakesink"
output_stream: "fakesink_2"
node: {
calculator: "tensor_filterCalculator"
input_stream: "fakesrc"
output_stream: "tensor_filter_0_0"
}
node: {
calculator: "teeCalculator"
input_stream: …
```
> [Tools/Parser] Convert gst pipeline to pbtxt (w/ mediapipe demo site)

- ext/nnstreamer/extra/nnstreamer_grpc.h
- ext/nnstreamer/extra/nnstreamer_grpc_common.cc
- ext/nnstreamer/tensor_sink/tensor_sink_grpc.c
- ext/nnstreamer/tensor_source/tensor_src_grpc.c
grpc-sink and grpc-src have duplicated codes. Remove them.
> Refactor/GRPC: remove duplicated codes

- ext/nnstreamer/tensor_decoder/tensordec-pose.c
- Free allocated string in tensordec-pose
> [Fix/Trivial] Fix mem leak in tensordec-pose @open sesame 05/24 16:00

- packaging/nnstreamer.spec
This patch makes the coverage analyzer ignore the reports of source
codes in tools. We don't need to add unittests for tools.
> [Coverage/Tools] Ignore coverage report of source codes in tools

- gst/mqtt/mqttsrc.c
- gst/mqtt/mqttsrc.h
MQTTsrc will return ack to the broker when it receives messages according to QoS level.
> [MQTTsrc] add mqtt QoS as a property

- ext/nnstreamer/tensor_filter/tensor_filter_tvm.cc
- gst/nnstreamer/include/nnstreamer_plugin_api.h
- gst/nnstreamer/meson.build
- gst/nnstreamer/tensor_allocator.c
- tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc
- Fix `set_input` to `set_input_zero_copy`
- Requires input data to be aligned by 128 (https://github.com/apache/tvm/pull/3416#discussion_r301917977)
> [Filter/tvm] set input without memory copy

- tests/gstreamer_mqtt/unittest_mqtt.cc
- tests/meson.build
Prior to enabling the dummy operation mode, this PR adds skeleton code for MQTT elements' unit test cases. The corresponding meson build script is also modified to generate and run the executable for the unit tests.
CC: @helloahn 
> [Tests/GstMQTT] Add skeleton code for MQTT elements' unit test cases

- debian/control
- debian/nnstreamer-tensorflow2-lite.install
- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
Per the request of #3282, add tf2-lite subpackage for Ubuntu releases.
Note that this requires merges of
https://review.tizen.org/gerrit/#/c/platform/upstream/tensorflow2/+/258437/
and then, refreshes of
https://code.launchpad.net/~nnstreamer/+recipe/tensorflow2-daily
After those, we can test build this commit.
> Dist/Deb: add tf2-lite for Ubuntu @open sesame 5/26 20:39

- ext/nnstreamer/extra/nnstreamer_protobuf.cc
- ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
- ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
The internal representation of temporary of type std::string is freed by its destructor.
Copy the std::string to avoid use after free.
> [Converter/subplugins] Fix use after free

- tests/gstreamer_mqtt/unittest_mqtt.cc
the basic test cases for get/set properties have been added.
> [MQTT/Test] add unittest for mqtt - @open sesame 05/25 14:40

- gst/nnstreamer/tensor_demux/gsttensordemux.c
- gst/nnstreamer/tensor_mux/gsttensormux.c
- tests/nnstreamer_sink/unittest_sink.cc
add pad template to accept flex tensor, and update source to configure tensor info for static/flex tensor stream.
> [Mux/Demux] accept flex tensor

- gst/nnstreamer/include/tensor_typedef.h
Define new struct for tensor meta.
The flex-tensor buffer will have a fixed-size header per mem block.
> [Meta] define tensor meta

- gst/mqtt/meson.build
- tests/gstreamer_mqtt/unittest_mqtt.cc
In this PR, 
- more MQTTSink test cases that can run without any MQTT broker are added
- the meson build script for GstMQTT is revised to install the GstMQTT plugins by default and not to build the static library
> [Tests/GstMQTT] Add more test cases for MQTTSink

- tests/nnstreamer_if/unittest_if.cc
Change timeout of the tensor_if test.
Timeout occurs somtimes because of slow speed of the armv7l to save files.
> [TEST] Change timeout of the tensor_if test

- ext/nnstreamer/extra/nnstreamer_grpc.h
- ext/nnstreamer/extra/nnstreamer_grpc_common.cc
- ext/nnstreamer/tensor_sink/tensor_sink_grpc.c
- ext/nnstreamer/tensor_source/tensor_src_grpc.c
grpc-sink and grpc-src have duplicated codes of get-property.
Remove them.
> Refactor/GRPC: remove duplicated get-property codes

- gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
To share the model representation(interpreter for TFLite), a new property is required.
Through this property, users can set the filters that share their model representation.
Additional logics(like checking duplication) will be added later.
The terms: `shared-tensor-filter-key`, `model representation`, are not well-known expressions.
I just named it with their purpose and I couldn't find better alternatives.
If you have any suggestions, please leave a comment.
related to #3114 
> [TensorFilter] add a property shared-tensor-filter-key

- debian/rules
- gst/nnstreamer/meson.build
- packaging/nnstreamer.spec
Instead of creating symlinks in packaging (RPM/DEB),
create symlinks at meson so that local-build & user-install
works appropriately.
Fixes #3316
CC: @smohantty
> Build: create libnnstreamer.so symlink in meson.

- debian/nnstreamer-core.links
Install nnstreamer shared object file in libdir.
This fixes build fail of the nnstreamer-api.
https://code.launchpad.net/~gichan-jang/+recipe/ml-api-daily
> [debian] Install nnstreamer shared object file in libdir

- gst/mqtt/mqttsink.c
- gst/mqtt/mqttsrc.c
This PR is related to bug fixes and further stabilization of the code. In detail,
- Reduced unnecessary mutex lock operations when changing MQTTSink's internal states. In addition, g_cond_wait is replaced with g_cond_wait_until to avoid possible deadlocks.
- Fixed bugs in the re-negotiation procedure in the MQTTSrc element
- Corrected the timeout in the MQTTSink element to wait for the disconnection to the broker using by MQTTSink
> [Gst/MQTT] Fix bugs and and further stabilize the Gst MQTT elements

- debian/nnstreamer-core.install
- debian/nnstreamer-core.links
Install symlink of nnstreamer shared object in libdir.
This fixes build fail of the nnstreamer-api.
https://code.launchpad.net/~gichan-jang/+recipe/ml-api-daily
> [FIX][debian] Install the link of nnstreamer lib

- tests/unittest_util.h
Change UNITTEST_STATECHANGE_TIMEOUT of the unit test util from 500 ms to 1,000 ms.
For cppFilterObj_base03 test, it takes an average of 700 ms to change the state in the armv7l arch.
> [TEST] Change state change timeout

- README.md
- Since JCenter service is stopped, replaced with daily build release temporarily.
- Change android official releases table
Dailybuild result of the android: http://nnstreamer.mooo.com/nnstreamer/ci/daily-build/build_result/latest/android/
> [README] Change android release link

- gst/nnstreamer/tensor_converter/README.md
- gst/nnstreamer/tensor_decoder/README.md
- packaging/nnstreamer.spec
flatbuffers python-support for tizen.
This will enable tensor converter and decoder unittest of the python.
> [tizen] flatbuffers python-support

- gst/nnstreamer/tensor_transform/tensor_transform.c
In transform() function, set write flag when mapping the output buffer.
> [Transform] set write flag

- gst/nnstreamer/include/nnstreamer_plugin_api.h
- gst/nnstreamer/tensor_common.c
- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_filter/tensor_filter.c
- gst/nnstreamer/tensor_mux/gsttensormux.c
- tests/common/unittest_common.cc
- tests/nnstreamer_plugins/unittest_plugins.cc
- tests/nnstreamer_sink/unittest_sink.cc
1. add util functions to handle tensor meta info.
2. parse and add header into each memory in buffer.
> [Meta] util functions to handle header in memory

- ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.cc
- ext/nnstreamer/extra/nnstreamer_grpc_protobuf.cc
- ext/nnstreamer/extra/nnstreamer_protobuf.cc
- ext/nnstreamer/tensor_converter/tensor_converter_python3.cc
- tests/nnstreamer_converter/unittest_converter.cc
- tests/nnstreamer_plugins/unittest_plugins.cc
remove unnecessary read-only flag when creating memory block with raw data.
> [Common/MemFlag] remove read-only flag

- ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
- meson.build
- packaging/nnstreamer.spec
- tests/nnstreamer_filter_lua/runTest.sh
- tests/test_models/models/passthrough.lua
- tests/test_models/models/scaler.lua
- Add Lua filter working with Lua5.1
- For now, it only supports num_tensors == 1 for input/output and only supports uint8 type
- Add SSAT testcases
- Enable Lua filter in Tizen
TODO (in upcoming PR) :
- scale for num_tensors > 1
- Support various tensor type
> [Filter/Lua] Add Lua tensor_filter subplugin

- tests/common/unittest_common.cc
- tests/nnstreamer_converter/unittest_converter.cc
- tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc
- tests/nnstreamer_plugins/unittest_plugins.cc
- tests/nnstreamer_sink/unittest_sink.cc
- Fix gtest signed-unsigned compare cases
- Change unittest_converter.cc CRLF -> LF
> [test/trivial] Fix signed-unsigned compare

- debian/control
- debian/nnstreamer-tvm.install
- meson.build
- tests/meson.build
This patch adds debian packaging for TVM filter
Fix meson.build corresponding to tvm-dev package
> [Debian] fix debian control for TVM @open sesame 06/10 10:17 

- gst/mqtt/mqttsink.c
- gst/mqtt/mqttsrc.c
Clear mutex when this is no longer used.
> [mqtt] Clear mutex of mqttsrc and mqttsink

- tests/nnstreamer_converter/unittest_converter.cc
- tests/test_models/models/custom_converter_test.py
- Fix python converter test fail on arm arch because of the slow speed of the
arm emulator.
- Fix the size of the input memory for the test.
> [TEST] Fix python converter test fail on arm arch

- gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
- gst/nnstreamer/tensor_common.c
- gst/nnstreamer/tensor_converter/tensor_converter.c
- gst/nnstreamer/tensor_demux/gsttensordemux.c
- gst/nnstreamer/tensor_filter/tensor_filter.c
- gst/nnstreamer/tensor_filter/tensor_filter_common.c
- gst/nnstreamer/tensor_source/tensor_src_iio.c
- gst/nnstreamer/tensor_split/gsttensorsplit.c
- tests/nnstreamer_plugins/unittest_plugins.cc
Code clean, use common util function to free tensor config struct.
> [CodeClean] use util function to free tensor config

- gst/nnstreamer/tensor_filter/tensor_filter.c
commit 0a03667f52b39d77c9df0e6cf1c487c2c4bebb62 (HEAD -> refactor/cc/0527_1)
Date:   Thu May 27 19:56:11 2021 +0900
Tensor-filter: elaborate error messages with invoke.
The runtime error messages of tensor-filter are not
meeting the standard. Elaborate the messages with
enough information for debugging.
commit 9d6534487e2c4ffe3f24202702e44fd14f0ecf0d
Date:   Thu May 27 19:41:54 2021 +0900
Tensor-filter: reduce CC by separating parameter checks.
Separate parameter check subrountine to reduce CC, which is
mentioned by "SAM".
> Refactoring tensor-filter (lower CC and elaborated error messages)

- gst/nnstreamer/tensor_crop/tensor_crop.c
- gst/nnstreamer/tensor_crop/tensor_crop.h
- tests/nnstreamer_plugins/unittest_plugins.cc
1. Default mode to crop region of raw data.
2. Add new property lateness.
If user sets lateness, then tensor-crop will compare the timestamp of incoming buffers and will drop buffer if time-diff is larger than lateness.
TODO later work
handle various crop-mode in tensor-crop.
> [Crop] crop region

- gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
- Catch other exceptions and print the error msg in invoke function.
- runtime_error or exception have wide coverage, Let those cpp exceptions return error code EINVAL.
- Developer should throw exceptions with detailed error message.
> [filter/cpp] Catch exceptions in invoke

- tests/gstreamer_join/runTest.sh
Add timeout option to fail test.
Pipeline does not end after test failure on arm arch.
Wait : https://github.com/myungjoo/SSAT/pull/21
> [test/join] Add timeout option

- ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
- tests/nnstreamer_filter_lua/unittest_filter_lua.cc
- Use `g_malloc` instead of `malloc` to abort program when malloc fails
- Give correct size to `lua_newuserdata`
> [fix/lua] Fix covertiy/svace issues issued in lua source code

- packaging/nnstreamer.spec
- tests/meson.build
- tests/nnstreamer_filter_tvm/meson.build
- tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc
TVM test model is compiled for x86_64, disable test on other architectures
TODO: prepare test models for more target devices
```
```
> [Test/TVM] Fix gbs test to run only on x86_64

- debian/nnstreamer-dev-internal.install
- meson.build
- nnstreamer-internal.pc.in
- packaging/nnstreamer.spec
API package requires to refer to additional headers that devel is not supposed to export.
Such files are exported with "internal-devel" package.
Add a new pkgconfig file for this additional devel package so that the build-dependency can be
resolved with pkgconfig as well.
commit 83967265053c6dc353813078b221cccb381e9d54 (HEAD -> fix/3230, github-fork/fix/3230)
Date:   Wed Jun 23 10:41:20 2021 +0900
pkgconfig: add nnstreamer-internal for API developers.
API developers require additional headers than subplugin writers,
which is packaged as "nnstreamer-internal".
With this additional pkgconfig file, such dependency can be met.
Fixes #3230
commit 3fb7f9e3285f32dc41d9f514199a0d41be7781de …
> pkgconfig: add nnstreamer-internal for API developers.

- meson.build
If sysconfdir option is not given or a relative path is given,
add prefix so that its actual install path (which uses prefix
if a relative path is given) matches NNSTREAMER_CONF_FILE
macro in nnstreamer_conf.h
Fixes #3161
> meson: configure inidir properly when a relative path is given.

- gst/mqtt/meson.build
- tests/gstreamer_mqtt/GstMqttTestHelper.hh
- tests/gstreamer_mqtt/unittest_mqtt.cc
- tests/gstreamer_mqtt/unittest_mqtt_w_helper.cc
- tests/meson.build
To improve line coverage of the GstMQTT plugins without the actual running broker, this PR implements mock functions for the methods related to publishing to a topic in the Paho Asynchronous MQTT C Client Library. Based on those mock functions, more test cases for MQTTSink are added.
> [Test/GstMQTT] Improve line coverage of MQTTSink using mock functions

- debian/nnstreamer-misc.install
- meson_options.txt
- packaging/nnstreamer.spec
- tests/meson.build
gstmqtt_dep is removed and newly gstmqtt_mocking_dep is declared.
This patch uses gstmqtt_mocking_dep to fix the buildbreak issue.
> [Test/GstMQTT] Use gstmqtt_mocking_dep instead of gstmqtt_dep

- gst/nnstreamer/tensor_filter/tensor_filter.c
- Log latency and throughput values when the mode is enabled
- This resloves issue #3186
> [filter/log] Log filter statistics when the mode is enabled

- Documentation/profiling-android-pipeline.md
Fix title to comply hotdoc rule.
Special characters are not allowed in the hotdoc title.
> [Doc] Fix title to comply hotdoc rule

- debian/nnstreamer-misc.install
- meson_options.txt
- packaging/nnstreamer.spec
- tests/gstreamer_mqtt/unittest_mqtt_w_helper.cc
To revert a78ad73ddc2d7068f8818f1c025a21e085e6b675, this PR fixes the test cases for GstMQTT mentioned in #3378.
In detail, it is confirmed that the following cases are fixed:
- Tizen GBS (i586)
- Stuck at ```testMqttSrc.srcNormalLaunch1```
- Ubuntu Pdebuild: 
```
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] testMqttSrc.srcNormalLaunch0
[  FAILED  ] testMqttSrc.srcNormalLaunch1
[  FAILED  ] testMqttSrc.srcNormalLaunch0_n
[  FAILED  ] testMqttSrc.srcNormalLaunch1_n
[  FAILED  ] testMqttSrc.srcNormalLaunch2
```
> [Tests/GstMQTT] Fix failure in GstMQTT test cases @open sesame 07/07 13:30

- tests/nnstreamer_converter_python3/runTest.sh
- tests/nnstreamer_decoder_python3/runTest.sh
- tests/nnstreamer_flatbuf/runTest.sh
- tests/nnstreamer_flexbuf/runTest.sh
- tests/nnstreamer_protobuf/runTest.sh
Test fails on arm arch(gbs build) because buffer conversion takes long time.
The order of buffers is important for this test because the frame rate of the filesource is different.
The purpose of the test is to convert other/tensors to stream buffers, so modifies the test.
*Consecutive use of the python decoder has some problem, I will fix it next PR.
> [TEST] Fix streambuffers test

- ext/nnstreamer/tensor_filter/meson.build
- ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
- packaging/nnstreamer.spec
- tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc
This commit series reenabled armnn subplugin builds for Tizen and Debian.
Commit 1: There is a Linux distro that has ARMNN parsers partially (Debian/Sid); thus, armnn subplugin should adapt to it at build-time.
Commit 2: Recent ARMNN has deprecated a few type enums that this subplugin uses. Update them.
Commit 3: Reenable Tizen ARMNN build.
This series has the following commits:
commit 6324473f31abbf081f8ee21996d39246ad1343ea (HEAD -> armnn-reenable, github-fork/armnn-reenable)
Date:   Tue Jul 6 11:46:49 2021 +0900
Tizen: re-enable armnn build.
Provide as many tensor-filter subplugins as possible!
commit …
> Revive ARMNN build
