ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
SAM report, remove global value in sub-plugins.
=> [SAM] remove global val

api/android/api/src/main/jni/nnstreamer-native-customfilter.c
After converting info object in registration, free tensors-info handles.
=> [Android/Custom] free tensors-info handle

api/android/api/src/main/jni/Android-nnfw-prebuilt.mk, api/android/build-android-lib.sh
Update build script
- Remove unnecessary so in nnfw prebuilt libs
- Add nnfw-ext option
=> [Android] build script for nnfw

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCustomFilter.java, api/android/api/src/main/java/org/nnsuite/nnstreamer/CustomFilter.java
Change method and interface name, with C# API implementation.
NOTE:
The example app should be updated also.
=> [Android/Custom] change method name

tools/profiling/README.md
This patch adds a section for NNShark to the README.md file.
=> [Tools/Profiling] Add a section for NNShark to README.md

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
This patch updates the tensor-decoder subplugin, "bounding-boxes", to support person detection models for OpenVino.
1. Build 
```console
$ pwd
./nnstreamer
$ sudo apt install openvino-dev
$ meson build -Denable-openvino=true
$ ninja -C build
```
2. Prepare the running environment
```console
$ export GST_PLUGIN_PATH=$(pwd)/build/gst/nnstreamer
$ export NNSTREAMER_CONF=$(pwd)/build/nnstreamer-test.ini
$ export NNSTREAMER_FILTERS=$(pwd)/build/ext/nnstreamer/tensor_filter
$ export NNSTREAMER_DECODERS=$(pwd)/build/ext/nnstreamer/tensor_decoder
```
3. Launch the pipeline
You can get the model files from …
=> [Ext/Decoder] Support person detection models for OpenVino @open sesame 8/18 13:26

api/android/build-android-lib.sh
update tf-lite version info in build script.
=> [Android] build script with tf-lite 2.3

packaging/nnstreamer.spec
Remove openvino for DA's own build configurations.
=> [Tizen/DA] DA wants to omit openvino

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java, api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
Add simple testcase of image classification result using NNFW.
=> [Android/Test] img classification using NNFW

api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
change log message when failed to create single-shot instance.
=> [Android] log message

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
fix function ptr when creating new tensor struct in tf sub-plugin.
=> [Filter/TF] fix deallocator ptr

api/android/build-android-lib.sh
=> [Android/NNFW] update version

gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
reset private data after deallocation.
=> [SVACE] fix svace issue

api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
add new constructor and parse option string in NNFW sub-plugin.
=> [Android/NNFW] parse option

api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsData.java, api/android/api/src/main/jni/nnstreamer-native-api.c, api/android/api/src/main/jni/nnstreamer-native.h
While converting tensor data, reduce method call to set each tensor.
=> [Android] reduce method call

api/capi/src/nnstreamer-capi-util.c, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
This patch fixes unreachable codes reported by coverity.
=> [Coverity] Fix unreachable codes

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
Update testcase about dynamic invoke, change dimension to 1 ~ 4.
=> [Android/Test] test for dynamic dim

meson.build, meson_options.txt
This patch adds the build dependency for TensorRT.
CC: @again4you 
=> [Build/TensorRT] Add TensorRT dependency

api/capi/src/nnstreamer-capi-single.c
Code clean, prepare new API to invoke the model with allocated output data handle.
=> [C-Api/Single] prepare no-alloc invoke

api/capi/meson.build, meson.build, tools/development/confchk/meson.build, tools/development/nnstreamerCodeGenCustomFilter.py
change license arg in meson script (LGPL > LGPL-2.1)
=> [Meson] change license arg

gst/nnstreamer/tensor_if/README.md
Describe for tensor_if definition, its properties and usage cases.
Related issue: #1703 
=> [TensorIF] Add README.md for tensor_if element @open sesame 9/24 15:25

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, tests/nnstreamer_filter_tensorflow2_lite/runTest.sh, tests/nnstreamer_filter_tensorflow_lite/runTest.sh
Add option structure to open tf-lite model, set NNAPI false as default value.
Using NNAPI in tf-lite may make lower performance and unexpected result for some model.
Let the developer select NNAPI option when constructing the pipeline.
=> [Filter/TF-lite] nnapi option @open sesame 10/06 20:45

gst/nnstreamer/include/nnstreamer_plugin_api.h
add function description about fetching version info in plugin-api header.
=> [Doc] update description

gst/nnstreamer/tensor_if/gsttensorif.c
Add basic action option: PASSTHROUGH, SKIP, TENSORPICK
- Supported operator: All
- Suppoted data type: All
- Supported action: passthrough, skip, tensorpick. (Others will be added)
@todo: Support  tensors on srcpad
@todo: Add callback function to support user defined condition.
Test pipeline description:
```
gst-launch-1.0 v4l2src ! videoconvert ! videoscale ! video/x-raw, format=RGB, width=640, height=480, framerate=30/1 ! tensor_converter ! mux.sink_0 \
videotestsrc ! videoconvert ! videoscale ! video/x-raw, format=RGB, width=640, height=480, framerate=30/1 ! tensor_converter ! mux.sink_1 \
tensor_mux name=mux ! tensor_if name=tif \
compared_value=A_VALUE compared-value-option=0:0:0:0,0 \
supplied-value=70,150 \
operator=RANGE_INCLUSIVE \
then = TENSORPICK \
then-option= 0 \
else = …
```
=> [TensorIF] Add basic action option

api/capi/include/nnstreamer-capi-private.h, tests/tizen_capi/unittest_tizen_capi.cc, tests/tizen_capi/unittest_tizen_capi_latency.cc
1. update testcase for benchmark (single-shot no output allocation)
2. mark todo for next APIs
=> [Test/Benchmark] benchmark with no output alloc

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
add option to set the number of threads to tf-lite interpreter.
=> [Filter/TFLite] option to set no of threads

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Cache nnfw tensors info and handle rank value when setting input info.
=> [NNFW] cache info from nnfw

gst/nnstreamer/tensor_if/gsttensorif.c
support tensor average option for compared value.
- Supported compared value: A_VALUE, TENSOR_AVERAGE_VALUE
Test pipeline:
```
gst-launch-1.0 v4l2src ! videoconvert ! videoscale ! video/x-raw, format=RGB, width=640, height=480, framerate=30/1 ! tensor_converter ! mux.sink_0 \
videotestsrc ! videoconvert ! videoscale ! video/x-raw, format=RGB, width=640, height=480, framerate=30/1 ! tensor_converter ! mux.sink_1 \
tensor_mux name=mux ! tensor_if name=tif \
compared_value=TENSOR_AVERAGE_VALUE \
compared-value-option=0 \
supplied-value=100 \
operator=GE \
then = TENSORPICK \
then-option= 0,1 \
else = TENSORPICK \
else-option= 0 \
tif.src_0 ! tensor_demux name=demux \
demux.src_0 ! queue ! tensor_decoder mode=direct_video ! videoconvert ! ximagesink async=false sync=false \
demux.src_1 ! …
```
=> [TensorIF] Supports tensor average option for compared value

gst/nnstreamer/tensor_if/gsttensorif.c, tests/meson.build, tests/nnstreamer_if/unittest_if.cc
Add testcases for tensor_if element.
Line coverage is 92.4%.
=> [TensorIF] Add testcases for tensor if

api/android/api/src/main/jni/nnstreamer-native-singleshot.c, api/capi/include/nnstreamer-capi-private.h, api/capi/include/nnstreamer-single.h, api/capi/src/nnstreamer-capi-single.c, tests/tizen_capi/unittest_tizen_capi.cc, tests/tizen_capi/unittest_tizen_capi_latency.cc
prepare next ACR
- function to invoke with preallocated output handle
- function to open nn model with custom options
Change function names and add description for each API.
=> [C-Api] prepare new APIs

jni/Android.mk, jni/nnstreamer.mk
remove unnecessary build flag - nnapi in jni is for nn-runtime.
=> [Android/Build] remove unnecessary build flag

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/include/nnstreamer_plugin_api_filter.h, nnstreamer.ini.in, tests/nnstreamer_filter_tensorflow2_lite/runTest.sh, tests/nnstreamer_filter_tensorflow_lite/runTest.sh
- Remove NNAPI custom prop instead,
- Enable NNAPI after the accelerator property
- TODO: Support appropriate delegates after the accelerator prop
=> [Filter/tflite] Remove NNAPI option

tests/nnstreamer_if/unittest_if.cc
The pipeline state changed to NULL before saving the result file due to slow speed of arm.
Give enough time or wait until the file is created.
=> [TensorIF] Fix unit test fail on arm arch @open sesame 10/29 08:30 

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java, api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java, api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
- Add Options to configure SingleShot instance preparing new features that might be added in future
- Add three negative test cases for newly added `Options`
=> [Android/SingleShot] Add `Options` class for configuring SingleShot

api/android/api/src/main/jni/nnstreamer-native-api.c, api/android/api/src/main/jni/nnstreamer-native-pipeline.c, api/android/api/src/main/jni/nnstreamer-native.h
Prevent invalid element handle case, compare element type when getting the element handle in hash table.
=> [Android] fix invalid handle case

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- Use NNAPI delegate directly instead of deprecated `UseNNAPI` method.
- This resolves #2755.
- Ref: https://github.com/tensorflow/tensorflow/commit/bf6f488c1102a88252960c4c8b90f6122e966b14
TODO: Handle #2820
=> [Android/tflite] Fix NNAPI inference bug

api/android/api/src/main/jni/nnstreamer-native-api.c, api/android/api/src/main/jni/nnstreamer-native-customfilter.c, api/android/api/src/main/jni/nnstreamer-native-pipeline.c, api/android/api/src/main/jni/nnstreamer-native-singleshot.c, api/android/api/src/main/jni/nnstreamer-native.h
1. move native methods registration to each file.
2. add new function to get data ptr in native.
=> [Android] codeclean

tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
nnfw-1.10 was released and now supports dynamic dimension.
Enable testcases and fix invalid test conditions.
=> [Test/NNFW] fix invalid tc

gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h, tests/nnstreamer_filter_pytorch/runTest.sh, tests/nnstreamer_filter_tensorflow/runTest.sh, tests/nnstreamer_filter_tensorflow_lite/runTest.sh
Add options for input and output combinations.
example pipeline
```
videotestsrc ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB,framerate=30/1 ! tensor_converter ! mux.sink_0 \
v4l2src ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB,framerate=30/1 ! tee name=t \
t. ! queue leaky=2 max-size-buffers=2 ! videoscale ! video/x-raw,width=300,height=300,format=RGB ! tensor_converter ! \
tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 ! mux.sink_1 \
tensor_mux name=mux ! tensor_filter framework=tensorflow-lite model=tflite_model/ssd_mobilenet_v2_coco.tflite inputCombination=1 outputCombination=i0,o0,o1 ! \
tensor_demux name=demux \
demux.src_0 ! queue leaky=2 max-size-buffers=10 ! tensor_decoder …
```
=> [TensorFilter] Combined Tensor Picking @open sesame 11/05 14:43 

debian/nnstreamer.install
Modify the install file list since grpc and join are newly added to the gst path.
=> [Debian] Modify nnstreamer install files @open sesame 11/13 15:08 

api/android/api/src/main/jni/nnstreamer-native-pipeline.c, api/capi/src/nnstreamer-capi-pipeline.c, api/capi/src/nnstreamer-capi-util.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c
Code clean, fix indent and common ptr to handle tensor info struct.
=> [CodeClean] indent and common function

api/capi/include/nnstreamer-capi-private.h, api/capi/include/nnstreamer.h, api/capi/src/nnstreamer-capi-util.c, tests/tizen_capi/unittest_tizen_capi.cc
Add new function to check the element availability (registered and not restricted)
=> [C-Api] element availability

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
For debug, add log retry count in set-dimension function.
=> [NNFW] print retry count log

tools/development/gstPrototxt.py
Skeleton code for GstPipe<-->Pbtxt Conversion.
Ultimately, we can use web-based WYSIWYG tools based on this!
=> [Tools] GstPipe<-->Pbtxt Conversion / Skeleton

api/android/api/src/main/jni/nnstreamer-native-pipeline.c
prevent invalid window handle case.
video-sink does not set new window handle directly. If video-sink accesses released window handle, this will crash an application.
=> [Android] fix invalid window error

gst/nnstreamer/nnstreamer_conf.c
fix warning in android native build (type conversion)
=> [Build] fix warning (type conversion)

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java, api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java, api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java, api/android/api/src/main/java/org/nnsuite/nnstreamer/Pipeline.java, api/android/api/src/main/jni/nnstreamer-native-api.c, api/android/api/src/main/jni/nnstreamer-native-pipeline.c
Add new method to check element available on the pipeline.
=> [Android/Api] method to check element availability

api/android/README.md
- Add guide for using TensorFlow Lite NNAPI delegate to README.md
This resolves #2820 
=> [Android/Doc] Add guide for using NNAPI delegate to README

packaging/nnstreamer.spec
1. .spec file code cleaned for readability
2. reflect recent changes in usage conditions of a few subplugins
3. allow to use CAPI in other Linux distros.
Addresses #2564
=> [DIST/RPM] Code Clean .spec for readability and non-Tizen users

gst/join/meson.build, tests/gstreamer_join/runTest.sh, tests/gstreamer_join/unittest_join.cc, tests/meson.build
Add testcases for join element.
Line coverage: 92.4%
=> [Join] Add testcases for join @open sesame 11/26 08:44

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
1. Fix invalid tensor info ptr when setting new tensor shape.
(Running dummy invoke tries to set old tensor info.)
2. Allocate dummy buffer and init to 0.
3. Handle insufficient output buffer case.
=> [Filter/NNFW] invalid tensor info

api/android/build-android-lib.sh
Prepare next release, update ONE version to 1.11.
=> [Android/ONE] update ONE version

debian/nnstreamer-util.install, debian/nnstreamer-util.links, debian/nnstreamer.links, debian/rules, meson.build, meson_options.txt, packaging/nnstreamer.spec, tools/development/confchk/meson.build, tools/development/meson.build
The main meson script will not handle utilities
under /tools/development
=> Build script clean: nnstreamer-check built by default

nnstreamer_example/custom_example_framecounter/nnscustom_framecounter.c, tests/nnstreamer_if/unittest_if.cc
Fix resource and mem leak of unit tests.
=> [Test] Fix resource and mem leak

api/android/api/src/main/jni/Android-tensorflow-lite.mk, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
define features in .mk file (GPU / NNAPI delegate and types for tf-lite version)
=> [Android/TF-lite] feature for tf-lite

tests/nnstreamer_plugins/unittest_plugins.cc, tests/nnstreamer_source/unittest_src_iio.cc, tests/transform_arithmetic/checkResult.py
- Set src_iio test with channels 3 -> 2
- Skip file permission test if the user is root
- Make division compatible with python3
=> [unittest] Fix some unittest for yocto

meson.build
- Currently `$ ninja test` failed for `join`
- Add gst_plugin_path and ext_plugin_path for env
=> [test] Fix ninja test for `join` @open sesame 12/03 12:35

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
parse custom option string to set tensorflow-lite delegate.
=> [Android/TF-lite] method to set tf-lite delegate

gst/nnstreamer/tensor_filter/README.md
Since new features of the filter are added, update the manual.
=> [Filter] Update filter manual @open sesame 12/04 09:33 

ext/nnstreamer/extra/nnstreamer_grpc_common.cc
This patch fixes some minor typos in gRPC common codes.
CC: @anyj0527 
=> [Fix/gRPC] Fix minor typos in gRPC common codes

gst/nnstreamer/tensor_filter/tensor_filter_common.c, meson.build, nnstreamer.ini.in
Set sub-plugin priority in ini.
(For tensorflow-lite, tf2-lite has high priority if tf2-lite is available.)
=> [Filter/Sub] sub-plugin priority

gst/nnstreamer/tensor_filter/tensor_filter_common.c
Code clean, add internal function for filter properties.
=> [Filter] reduce complexity

Documentation/getting-started-macos.md
Update meson build command options
Signed-off-by: Seonkyo Ok uyw4687@naver.com
=> [Doc] Update meson build command options

api/android/build-android-lib.sh
ONE v1.12.0 now released, update ONE version for next release.
=> [Android/NNFW] update ONE version

tools/development/parser/grammar.y, tools/development/parser/types.c
Replacing gst-factory method with simplified implementation.
Updated grammar and its static function for parsing rule
1. element
2. elementary
=> [Tools/Parser] Parser Rule #1 and #2 updated

tests/nnstreamer_decoder_image_labeling/runTest.sh, tests/nnstreamer_decoder_image_segment/runTest.sh, tests/nnstreamer_filter_reload/runTest.sh, tests/nnstreamer_filter_tensorflow_lite/runTest.sh
This patch changes tflite soname for grep in few unitests.
It resolves https://github.com/nnstreamer/nnstreamer/issues/2944
=> [Fix/TFlite] Change tflite soname for grep in few unittests

tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
This patch adds mutex to count number of callbacks.
It resolves https://github.com/nnstreamer/nnstreamer/issues/2941
=> [Fix/UnitTest] Add mutex to count number of callbacks @open sesame 12/14 18:32

api/android/api/src/main/jni/Android-dec-flatbuf.mk, api/android/api/src/main/jni/Android.mk, api/android/api/src/main/jni/nnstreamer-native-api.c, api/android/build-android-lib.sh, ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc, jni/nnstreamer.mk
Fixes https://github.com/nnstreamer/nnstreamer/issues/2928
This patch adds the decoder sub-plugin for FlatBuffers to the Android library (i.e., AAR).
=> [Android/Decoder] Add the decoder sub-plugin for FlatBuffers to AAR @open sesame 12/14 18:33

api/capi/include/nnstreamer.h
Define new API for tensor_if custom register/unregister
=> [C-API] Define new API for tensor_if

api/capi/include/nnstreamer-single.h, api/capi/include/nnstreamer.h
Fix API headers with the script in API design guide.
=> [C-API] fix C-API header

api/android/README.md
- Add guide for providing model file to NNS Java API with scoped storage
- Fix guide for tflite nnapi delegate
Please check: https://github.com/nnstreamer/nnstreamer/blob/a6e1f1e3c82e60065b4cfa0e81044b46dd759a67/api/android/README.md#using-model-file-with-scoped-storage
=> [Android/doc] Add guide for using model file in scoped storage

api/capi/include/nnstreamer-capi-private.h, api/capi/include/nnstreamer.h, api/capi/src/nnstreamer-capi-pipeline.c, tests/tizen_capi/unittest_tizen_capi.cc
Implement tensor_if custom register/unregister and add related test cases.
=> [C-API] Implement tensor_if custom condition and add test cases

gst/nnstreamer/tensor_filter/tensor_filter_common.c
add condition to check .dlc file for auto detection.
=> [Filter/SNPE] detect dlc file

gst/nnstreamer/tensor_if/gsttensorif.c, gst/nnstreamer/tensor_if/gsttensorif.h
remove unnecessary value and init null to avoid exception case using gst-inspect.
=> [If] init property values

ext/nnstreamer/android_source/gstamcsrc.c, ext/nnstreamer/tensor_source/tensor_src_tizensensor.c, gst/nnstreamer/tensor_aggregator/tensor_aggregator.c, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_if/gsttensorif.c, gst/nnstreamer/tensor_merge/gsttensormerge.c, gst/nnstreamer/tensor_rate/gsttensorrate.c, gst/nnstreamer/tensor_repo/tensor_reposink.c, gst/nnstreamer/tensor_repo/tensor_reposrc.c, gst/nnstreamer/tensor_source/tensor_src_iio.c, gst/nnstreamer/tensor_transform/tensor_transform.c
element name in nnstreamer and general classification of element.
=> [CodeClean] element type classification

gst/join/gstjoin.c
Remove unnecessary code and fix minor bugs. (pass NULL param).
=> [JOIN] Remove unnecessary code and fix minor bugs

debian/nnstreamer-dev.install, gst/nnstreamer/include/meson.build, packaging/nnstreamer.spec
add missed header for tensor-if custom callback.
=> [If] install header

api/capi/meson.build, packaging/nnstreamer.spec
set dependency to check privilege in tizen build.
=> [Build/Tizen] dependency to check privilege

gst/nnstreamer/tensor_filter/tensor_filter.c
Possible res leak in output combination case, release mem block if output tensor is not in the combination list.
=> [Filter] release mem block in combi case

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java, api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java, api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java, api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java, api/android/api/src/main/jni/Android-pytorch.mk, api/android/api/src/main/jni/Android.mk, api/android/api/src/main/jni/nnstreamer-native-api.c, api/capi/include/nnstreamer.h, api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c, ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc, jni/nnstreamer.mk
- Support pytorch subplugin on Android 
- Add image classification test for SingleShot and Pipeline API using PyTorch sub-plugin
=> [Android/PyTorch] Support pytorch subplugin on Android 

ext/nnstreamer/tensor_filter/tensor_filter_python3.cc, tests/nnstreamer_repo_lstm/generateTestCase.py, tests/nnstreamer_repo_rnn/generateTestCase.py
fix pycore lib name format (failure on v3.9)
=> [Filter/Python] pycore lib name

debian/control, debian/nnstreamer-grpc-flatbuf.install, debian/nnstreamer-grpc-protobuf.install, debian/nnstreamer-grpc.install, packaging/nnstreamer.spec
This patch creates per-IDL grpc packages to resolve dependency issues.
=> [Dist/gRPC] Create per-IDL grpc packages

api/android/build-android-lib.sh
- Add PyTorch to build script for android library
=> [build/Android] Update android lib build script for PyTorch

README.md
Change daily build directory path.
.... /nnstreamer/ci/taos/daily-build/ -> .... /nnstreamer/ci/daily-build/
=> [README] Change daily build path

ext/nnstreamer/extra/nnstreamer_grpc.h, ext/nnstreamer/extra/nnstreamer_grpc_common.cc, ext/nnstreamer/extra/nnstreamer_grpc_common.h, ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.cc, ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.h, ext/nnstreamer/extra/nnstreamer_grpc_protobuf.cc, ext/nnstreamer/extra/nnstreamer_grpc_protobuf.h, ext/nnstreamer/tensor_sink/tensor_sink_grpc.c, ext/nnstreamer/tensor_sink/tensor_sink_grpc.h, ext/nnstreamer/tensor_source/tensor_src_grpc.c, ext/nnstreamer/tensor_source/tensor_src_grpc.h
This patch revises gRPC common codes by adding grpc_config structure.
Also, gRPC non-blocking mode will be supported soon.
=> [gRPC] Add grpc_config struct and revise gRPC common codes

api/capi/include/tensor_filter_single.h, api/capi/src/tensor_filter_single.c
set private data for tensor-filter single properties.
TODO: move filter-single class to gst directory or declare extern for filter common function.
=> [Filter/Single] hide private properties

gst/join/gstjoin.c
remove unnecessary code (duplicated free line)
=> [Join] remove unnecessary code

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_demux/gsttensordemux.c, tests/common/unittest_common.cc
Update description to check peer pad caps, and fix invalid condition.
=> [Common] function to check peer caps @open sesame 01/21 14:13

api/capi/include/nnstreamer-capi-private.h, api/capi/meson.build, api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c, api/capi/src/tensor_filter_single.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h, jni/nnstreamer.mk, meson.build, tests/tizen_capi/unittest_tizen_capi.cc
fix typo and remove duplicated code to compare file extension.
=> [Common] code clean

packaging/nnstreamer.spec
add missed testcases - filter-cpp in tizen build.
=> [Test] add filter-cpp test

api/capi/include/nnstreamer.h, gst/nnstreamer/tensor_if/gsttensorif.c, tests/nnstreamer_if/unittest_if.cc
update description for tensor-if custom callback and set init value for condition.
=> [If/Api] api description for if callback

tests/gstreamer_join/unittest_join.cc
create buffer with pre-allocated mem.
=> [Test] fix coverity issue @open sesame 1/29 15:03

debian/control, debian/nnstreamer-api-dev.install, debian/nnstreamer-api.install, debian/nnstreamer-dev.install, debian/nnstreamer.install
add package for nnstreamer API (separate from nnstreamer pkg)
=> [Build] package for nnstreamer API

api/capi/include/nnstreamer-single.h, api/capi/include/nnstreamer.h
Clarify the description of nnstreamer C-API.
*I will update tensor_filter custom options of the sub-plugins after this PR.
(e.g., num-threads, delegate ...)
=> [C-API] Fix C-API header comments

tests/tizen_capi/unittest_tizen_capi.cc
Current setting and getting string property test try to select tensor(s) that does not exist.
Changed to set and get the framework of the tensor filter.
=> [TEST] Change string property test

Documentation/hotdoc/sitemap.txt, tools/README.md, tools/debugging/README.md, tools/development/README.md, tools/profiling/README.md, tools/tracing/README.md
Add nnstreamer tools doc to github.io
=> [Doc] Add nnstreamer tools to github.io

tests/nnstreamer_converter/runTest.sh, tests/nnstreamer_decoder/runTest.sh, tests/nnstreamer_filter_custom/runTest.sh, tests/nnstreamer_filter_python3/runTest.sh, tests/nnstreamer_rate/runTest.sh
- Remove some log files during SSAT test for humble yocto qemu environment
=> [SSAT] Remove some log files generated by SSAT tests

packaging/nnstreamer.spec
fix package name required for devel packages.
=> [Build] fix package name

tests/nnstreamer_decoder/runTest.sh
- Check existence of  flatbuf and protobuf decoder sub-plugins for some SSAT testcases.
=> [test/SSAT] Check flatbuf and protobuf decoder sub-plugins

api/capi/src/nnstreamer-capi-pipeline.c, api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c
=> [CodeClean] fix indent

api/capi/include/nnstreamer-single.h, api/capi/src/nnstreamer-capi-pipeline.c, api/capi/src/nnstreamer-capi-single.c
prepare next android build & release, push necessary commits to lts-1.6 branch.
=> [lts-1.6.y] prepare next release

gst/nnstreamer/include/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter_common.c
Fix mem leak of the tensor filter.
Related issue: #3055 
=> [Filter] Fix memory leak

gst/nnstreamer/tensor_demux/gsttensordemux.c, gst/nnstreamer/tensor_if/gsttensorif.c, gst/nnstreamer/tensor_rate/gsttensorrate.c, gst/nnstreamer/tensor_split/gsttensorsplit.c
Fix memory leak detected by valgrind.
=> [Bug] Fix memory leak

tests/tizen_capi/meson.build, tests/tizen_capi/unittest_tizen_sensor.cc
For tizen sensor element, remove dependency to ml api. Replace to gst functions.
=> [Test] remove dependency to ml api

ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_lua.cc, meson.build, meson_options.txt
This is skeleton code for LUA filter subplugin, which
shows the idea of implementation and usage patterns.
This starts addressing #3095 (backlog of #3087)
Anyone may jump in and start implementing the contents.
CC: @semun-lee
=> [Filter/Lua] Skeleton code for LUA filter subplugin

Documentation/features-per-distro.md, Documentation/hotdoc/sitemap.txt, README.md
For binary release list up supported features.
Fixes #1448
=> [Documentation] List up supported features for binary releases

Documentation/contributing.md
This patch updates broken links in contributing guide.
Signed-off-by: Juyeong Lee <2jy22@naver.com>
=> [Docs] Fix broken links in contributing guide

meson.build, packaging/nnstreamer.spec, tests/cpp_methods/meson.build, tests/meson.build, tests/nnstreamer_filter_mvncsdk2/meson.build, tests/tizen_nnfw_runtime/meson.build
change unittest install dir (libdir to bindir) and update related build script.
=> [Test] unittest install dir

packaging/nnstreamer.spec
fix build error, change unittest install path.
=> [Build] fix install path

gst/nnstreamer/tensor_if/gsttensorif.c, tests/gstreamer_join/runTest.sh
Fix typo, property name of tensor-if element.
=> [If] fix typo @open sesame 3/4 09:13

ext/nnstreamer/tensor_filter/tensor_filter_python3.cc
This patch changes the logic to find the python library name.
The library name depends on which options were used to build python.
For example, if python 3.7 was compiled with '--with-pymalloc',
the library name is 'libpython3.7m.so'
It resolves #3109 
=> [Python] Change the logic to find the python library name

gst/mqtt/README.md
This describes more specific for #3104.
The assignees of #3104 should refer to this document for implementation.
=> [Edge/MQTT] Manifest for MQTT implementation @open sesame 3/4 11:03

CODE_OF_CONDUCT.md, CONTRIBUTING.md, Documentation/component-description.md, Documentation/contributing.md, Documentation/data-type-and-flow-control.md, Documentation/doxygen-documentation.md, Documentation/edge-ai.md, Documentation/getting-started-tizen.md, Documentation/getting-started-ubuntu-ppa.md, Documentation/getting-started.md, Documentation/how-to-run-examples.md, Documentation/how-to-use-testcases.md, Documentation/writing-tizen-native-apps.md, README.md, tools/README.md
Fix all the md files in
$NNST_ROOT/*.md
$NNST_ROOT/Documentation/*.md
$NNST_ROOT/tools/*md
which has a link to other md files
Signed-off-by: hyeonseok lee <hs89.lee@samsung.com>
=> Fix md file link

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
Set tensor name in tensors info struct.
TODO: we should update testcases in api repo later.
=> [Filter/TF-lite] tensor name in meta

tests/cpp_methods/unittest_cpp_methods.cc
I found this typo after submitting PR #3130. I thought I've corrected this and pushed it, but actually it was not.
Sorry for the mistake.
=> [Test] Fix typo

tests/nnstreamer_flatbuf/runTest.sh, tests/nnstreamer_protobuf/runTest.sh
Test whether flatbuffer and protobuf support other/tensors.
Test: tensors -> protobuf or flatbuffer -> tensors
=> [TEST] Test whether protobuf and flatbuf support tensors

ext/nnstreamer/tensor_decoder/tensordec-pose.c
Hi nnstreamer folks,
As discussed in  https://github.com/nnstreamer/nnstreamer/pull/3126 context, this pull request adds support for :
- Get key point connections list from label file, such as the key body connections are model dependent.
- Add option4 to set decoding scheme mode, adding 'heatmap-offset' mode to support posenet model.
https://www.tensorflow.org/lite/examples/pose_estimation/overview
=> Add support for generic keypoint connections handling and heatmap with offset decoding scheme

packaging/nnstreamer.spec
* Disable OpenVino
* Omit the test case execution & testcase summary
=> [Spec] Fix the buildbreak issue for VD

ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
Provided comments on how to write nnstreamer filters with LUA.
Related with #3095
=> [Filter/Lua] Design of LUA script rules for nnstreamer.

gst/nnstreamer/meson.build, gst/nnstreamer/tensor_data.c, gst/nnstreamer/tensor_data.h, gst/nnstreamer/tensor_if/gsttensorif.c, gst/nnstreamer/tensor_if/gsttensorif.h, gst/nnstreamer/tensor_transform/tensor_transform.c, gst/nnstreamer/tensor_transform/tensor_transform.h, jni/nnstreamer.mk
Now tensor-transform and tensor-if use common data struct to handle data.
Add new struct and common functions to handle tensor type and value.
=> [Common] tensor data struct

gst/nnstreamer/tensor_transform/README.md, gst/nnstreamer/tensor_transform/tensor_transform.c, gst/nnstreamer/tensor_transform/tensor_transform.h
Add new option for DC removal (average value) in stand mode.
=> [Transform] option for DC removal

packaging/nnstreamer.spec
* Disable NNFW, ArmCL, Viviante, pytorch, caffe2 & tensorflow.
=> [Spec] Add configuration for VD build

ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc, jni/nnstreamer.mk
Prepare Android API build, add definition for flatbuf/flexbuf subplugins.
=> [Build/Android] prepare subplugins for flatbuf

gst/nnstreamer/tensor_transform/tensor_transform.c, gst/nnstreamer/tensor_transform/tensor_transform.h, tests/nnstreamer_sink/unittest_sink.cc, tests/transform_clamp/runTest.sh, tests/transform_dimchg/runTest.sh, tests/transform_transpose/runTest.sh, tests/transform_typecast/runTest.sh
Changd tensor transform to support tensors
=> [TRANSFORM] Changed to support tensors

.github/CODEOWNERS
We had been accepting new members.
=> CODEOWNERS: Add members

gst/nnstreamer/tensor_if/README.md
- Remove description of unsupported properties.
- Elaborate description.
=> [Doc] Modify tensor_if README.md

gst/nnstreamer/tensor_transform/tensor_transform.c, gst/nnstreamer/tensor_transform/tensor_transform.h
condition to support orc acceleration for each tensor.
=> [Transform/Orc] orc acceleration for tensors

ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc, gst/nnstreamer/include/tensor_converter_custom.h, gst/nnstreamer/tensor_converter/tensor_converter.c, gst/nnstreamer/tensor_converter/tensor_converter.h, tests/nnstreamer_converter/unittest_converter.cc
- Changed custom mode name to custom-code for callback type.
- Add user data to the custom callback.
=> [CONVERTER] Change custom mode name

CONTRIBUTING.md, Documentation/coding-convention.md, Documentation/component-description.md, Documentation/data-type-and-flow-control.md, Documentation/getting-started-android.md, Documentation/getting-started-ubuntu-ppa.md, Documentation/writing-subplugin-tensor-filter.md
=> [Doc] Fix typo in md files

ext/nnstreamer/tensor_converter/tensor_converter_protobuf.cc, ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc, ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc, ext/nnstreamer/tensor_decoder/tensordec-protobuf.cc, ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc, ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc, ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc, ext/nnstreamer/tensor_filter/tensor_filter_lua.cc, ext/nnstreamer/tensor_filter/tensor_filter_mediapipe.cc, ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc, ext/nnstreamer/tensor_filter/tensor_filter_python3.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorrt.cc
-  Change flatbuffers and flexbuffers function name
-  Add extern "C" in converter, decoder and filter subplugins.
- Add doxygen tag for tensorrt
=> [Subplugins] Change func name and add extern "C" @open sesame 03/30 14:03 

gst/nnstreamer/tensor_if/gsttensorif.c
To improve code quality, I want to suggest a null checker.
=> [TensorIf] add a NULL checker

ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c, ext/nnstreamer/tensor_decoder/tensordec-pose.c, ext/nnstreamer/tensor_source/tensor_src_tizensensor.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, tests/nnstreamer_plugins/unittest_plugins.cc, tests/nnstreamer_rate/unittest_rate.cc
There are a few code changes to improve the code quality.
- check the variables before using them.
- return error code.
- free the allocated memory when it finished with ASSERT.
=> [CodeQuality] fix some defects to improve code quality

gst/nnstreamer/tensor_transform/tensor_transform.c, gst/nnstreamer/tensor_transform/tensor_transform.h, tests/nnstreamer_sink/unittest_sink.cc, tests/transform_typecast/runTest.sh
User can select tensors to apply the transformation.
=> [Transform] Add apply option (select tensors)

gst/nnstreamer/tensor_transform/tensor_transform.c
add regex for stand mode, filter option string.
=> [Transform] add regex for stand mode

ext/nnstreamer/android_source/gstamcsrc.c, ext/nnstreamer/android_source/gstamcsrc_looper.cc, ext/nnstreamer/android_source/gstamcsrc_looper.h
Clear looper when media steam is finished.
=> [Android/AMC] clear looper

gst/nnstreamer/tensor_filter/tensor_filter_common.c
This patch adds auto detection for SRNPU subplugin.
=> [SRNPU/FILTER] Add auto detection for SRNPU subplugin

Documentation/synchronization-policies-at-mux-merge.md, gst/nnstreamer/tensor_common.h, gst/nnstreamer/tensor_common_pipeline.c, gst/nnstreamer/tensor_merge/gsttensormerge.c, gst/nnstreamer/tensor_mux/gsttensormux.c, tests/nnstreamer_flatbuf/runTest.sh, tests/nnstreamer_flexbuf/runTest.sh, tests/nnstreamer_merge/runTest.sh, tests/nnstreamer_mux/runTest.sh, tests/nnstreamer_protobuf/runTest.sh, tests/nnstreamer_repo_lstm/runTest.sh, tests/nnstreamer_repo_rnn/runTest.sh, tests/nnstreamer_sink/unittest_sink.cc
change property name (sync mode and option), remove underbar in property name.
=> [Mux/Merge] change property name

tests/nnstreamer_plugins/unittest_plugins.cc
Add tensor transform mode option test
=> [Test] Add tensor transform mode option test

ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
To handle various cases, add an available format for the direct video decoder and add an option to handle it.
The example of the new option
```bash
...
tensor_converter ! tensor_decoder mode=direct_video option1=RGBA ! \
...
```
=> [Decoder/DirectVideo] add the video format RGBA and so on @open sesame 04/06 16:36

gst/nnstreamer/tensor_converter/tensor_converter.c
Set source pad caps form caps filter for _NNS_MEDIA_ANY type.
Example launch-line:
```
...
tensor_filter silent=false framework=tensorflow-lite model=tflite_model/ssd_mobilenet_v2_coco.tflite ! \
tensor_decoder mode=flexbuf ! other/flexbuf ! tensor_converter silent=false ! \
other/tensors, num_tensors=2, framerate=30/1, dimensions=\"4:1:1917:1\,91:1917:1:1\", types=\"float32\,float32\" ! \
tensor_decoder mode=bounding_boxes option1=tflite-ssd option2=tflite_model/coco_labels_list.txt option3=tflite_model/box_priors.txt option4=640:480 option5=300:300 ! \
...
```
Related issue: #3191 
=> [Converter] Set caps from caps filter for _NNS_MEDIA_ANY type

Documentation/API-reference.md, Documentation/component-description.md, Documentation/writing-subplugin-tensor-filter.md, README.md, jni/README.md
Change nnstreamer CI server link
=> [Docs] Change nnstreamer CI server link

gst/nnstreamer/include/tensor_typedef.h
add definition to handle flexible tensors stream.
=> [FlexTensors] define mimetype for flexible tensors

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
- Add enum for delegates
- Refactor parsing custom props
=> [filter/tflite] Add enum for tflite delegates

gst/nnstreamer/tensor_aggregator/tensor_aggregator.c, gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_demux/gsttensordemux.c, gst/nnstreamer/tensor_split/gsttensorsplit.c, gst/nnstreamer/tensor_transform/tensor_transform.c
Code clean, compare predefined mime type - other/tensor(s).
=> [Common] predefined mime type

ext/nnstreamer/extra/nnstreamer_protobuf.cc, ext/nnstreamer/extra/nnstreamer_protobuf.h, ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_protobuf.cc, gst/nnstreamer/include/nnstreamer_plugin_api_converter.h, gst/nnstreamer/tensor_converter/tensor_converter.c, tests/nnstreamer_converter/unittest_converter.cc, tests/nnstreamer_plugins/unittest_plugins.cc
Change external converter param
- Remove unnecessary param (frames_in, frame_size)
=> [Converter] Change external converter param @open sesame 04/22 19:59

gst/nnstreamer/tensor_sink/tensor_sink.c
add pad template to handle flexible tensor stream.
=> [Sink] accept flex tensor

gst/nnstreamer/tensor_aggregator/tensor_aggregator.c, gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_merge/gsttensormerge.c, gst/nnstreamer/tensor_source/tensor_src_iio.c, tests/nnstreamer_plugins/unittest_plugins.cc, tests/nnstreamer_sink/unittest_sink.cc
Before updating tensor config, initialize config struct.
=> [Common] add init-config

gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h
Code clean, add common functions for combi option and set-info callback.
=> [Filter] reduce duplicated source

gst/mqtt/meson.build, gst/mqtt/mqttcommon.h, gst/mqtt/mqttsink.c, gst/mqtt/mqttsink.h, gst/mqtt/mqttsrc.c, gst/mqtt/mqttsrc.h
This PR mainly focuses on pushing code that implements the basic features for publishing and subscribing MQTT topics on mqttsink and mqttsrc, respectively.  
=> [Gst/MQTT] Implement basic pub/sub support via Paho MQTTAsync C client library

gst/nnstreamer/tensor_if/gsttensorif.c
memory map info is valid until gst_memory_unmap() is called.
=> [If] invalid map info

gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h
While getting tensor info in caps negotiation, check input combi option and compare info with combined.
=> [Filter] input combi option

tests/nnstreamer_converter/unittest_converter.cc, tests/unittest_util.h
In test-util function, set condition to check file size while running a pipeline.
=> [Test] condition to check file size

tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc
* Separate positive and negative tests of the unittest_armnn.
* Fix resource leak (model_file)
=> [TEST] Separate positive and negative tests @open sesame 05/04 13:25

packaging/nnstreamer.spec
The elements for audio & edgeAI have been added.
To make it clear, the additional macros have been added.
The generated meson build script
After
```
meson 
...
'-Drestricted-elements=capsfilter input-selector output-selector queue tee valve appsink appsrc audioconvert \
audiorate audioresample audiomixer videoconvert videocrop videorate videoscale videoflip videomixer \
compositor fakesrc fakesink filesrc filesink audiotestsrc videotestsrc jpegparse jpegenc jpegdec pngenc \
pngdec tcpclientsink tcpclientsrc tcpserversink tcpserversrc udpsink udpsrc xvimagesink ximagesink \
evasimagesink evaspixmapsink glimagesink theoraenc lame vorbisenc wavenc volume oggmux avimux \
matroskamux v4l2src avsysvideosrc camerasrc tvcamerasrc pulsesrc fimcconvert tizenwlsink gdppay \
gdpdepay join …
```
=> [Spec] add the restricted elements

tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc, tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc, tests/nnstreamer_sink/unittest_sink.cc, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Add set filter property function.
*The TCM parser stops analyzing when it encounters the constructor pattern.
=> [TEST] Add set property function

gst/nnstreamer/tensor_filter/tensor_filter.c
handle error case if incoming buffer has invalid size or the number of mem blocks is different.
=> [Filter] handle invalid buffer

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/include/tensor_typedef.h, gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_common_pipeline.c, gst/nnstreamer/tensor_converter/tensor_converter.c, tests/common/unittest_common.cc
add util functions to handle flexible tensor stream.
=> [Common] utils to handle flex tensor

gst/nnstreamer/tensor_transform/tensor_transform.c
Fix svace issue, change local param in macro.
=> [Transform] change val name in macro

debian/nnstreamer-python3.install, ext/nnstreamer/extra/nnstreamer_protobuf.cc, ext/nnstreamer/extra/nnstreamer_protobuf.h, ext/nnstreamer/extra/nnstreamer_python3_helper.c, ext/nnstreamer/tensor_converter/meson.build, ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_protobuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_python3.cc, gst/nnstreamer/include/nnstreamer_plugin_api_converter.h, gst/nnstreamer/tensor_converter/tensor_converter.c, gst/nnstreamer/tensor_converter/tensor_converter.h, packaging/nnstreamer.spec, tests/nnstreamer_converter/unittest_converter.cc, tests/nnstreamer_converter_python3/runTest.sh, tests/nnstreamer_plugins/unittest_plugins.cc, tests/test_models/models/custom_converter.py
Add subplugins for python custom converter
*Flexbuffer Python API is not officially released yet, disable the test if the version of flatbuffers is lower than 2.0.
(https://github.com/google/flatbuffers/issues/5306)
=> [Converter] Add subplugins for python custom converter

debian/nnstreamer-python3.install, ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_python3.cc, ext/nnstreamer/tensor_decoder/meson.build, ext/nnstreamer/tensor_decoder/tensordec-python3.cc, packaging/nnstreamer.spec, tests/nnstreamer_converter_python3/runTest.sh, tests/nnstreamer_decoder_python3/runTest.sh, tests/test_models/models/custom_decoder.py
Add tensor decoder python subplugins.
=> [Decoder] Add tensor decoder python subplugins @open sesame 05/06 19:32

gst/mqtt/mqttsrc.c
In the current implementation of GstBaseSrcClass's create vmethod, it is possible that deadlock occurs since some error cases during the initialization are not properly handled. This patch fixes this bug.
=> [Gst/MQTT/Src] Avoid deadlock cases in create() of GstBaseSrcClass

debian/control, debian/nnstreamer-util.install, debian/nnstreamer-util.links, meson_options.txt, packaging/nnstreamer.spec
This patch nnstreamer-parser to util package.
=> [Tools/Parser] Add nnstreamer-parser to util package @open sesame 05/13 17:13

gst/nnstreamer/tensor_crop/tensor_crop.c
While caps negotiation, set output framerate from input configuration.
=> [Crop] output framerate

Documentation/getting-started-ubuntu-ppa.md
I didn't find any documentation about the misc ppa on my first pass through the examples, so I added some.
=> Adding information about misc ppa

gst/mqtt/README.md
This patch slightly revises README.md.
=> [Gst/MQTT] Revise README.md

tools/development/parser/types.h
In tool/parser, check null ptr before comparing the id.
=> [Tool/Parser] check null ptr

gst/nnstreamer/tensor_if/gsttensorif.c, tests/common/unittest_common.cc, tests/unittest_util.h
- Fix possible double free case when `g_file_get_contents` is failed.
- Fix uninitialized supplied value 2.
- Initialize tensor(s) info and config.
=> [TEST] Fix svace issues

gst/mqtt/mqttsrc.c
This patch makes the subscription be removed when the state of the element is changed to PAUSED from PLAYING. In addition, to block the extra invocation of the receiving message handler running on the other thread, checking the subscription flag is added to this handler.
**Changelog**
- Handled the case when the state is changed to PLAYING again from PAUSED (https://github.com/nnstreamer/nnstreamer/pull/3279#pullrequestreview-661585524)
=> [Gst/MQTT/Src] Keep subscribing to the topic only in the PLAYING state

gst/nnstreamer/tensor_converter/tensor_converter.c
1. remove unnecessary memory map in chain function.
2. failure case when configuring multi tensors.
=> [Converter/CodeClean] unnecessary memory map

gst/nnstreamer/tensor_allocator.c
release object after finding allocator, fix possible leak.
=> [Alloc] ref count in allocator

tools/development/parser/convert.c
improve score, remove gv in sam report.
=> [CodeClean/Tool] remove gv in am report

ext/nnstreamer/tensor_converter/meson.build, ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_protobuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_util.c, ext/nnstreamer/tensor_converter/tensor_converter_util.h, jni/nnstreamer.mk
Remove the duplicated function definition.
Create tensor-converter extra subplugin's common util.
=> [Converter/Flatbuf,Flexbuf,Protobuf] Remove duplicated code

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/nnstreamer_internal.h, gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_common.h, gst/nnstreamer/tensor_converter/tensor_converter.c, gst/nnstreamer/tensor_demux/gsttensordemux.c, gst/nnstreamer/tensor_if/gsttensorif.c, gst/nnstreamer/tensor_mux/gsttensormux.c
add util fucntions to handle pad caps and move these to internal header.
=> [Flex/Common] util functions to handle pad caps

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
To make the interpreter shareable, need to change to a pointer first.
related to #3114
=> [Filter/TFLite] change interpreter to pointer

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
MM team request, before implementing fallback mode in ONE, set backend str w/cpu.
=> [Filter/ONE] change backend str

Documentation/getting-started-meson-build.md
Per the request of #3320, the document is updated.
CC: @shortcipher3
=> Documentation: meson build description updated.

ext/nnstreamer/tensor_converter/tensor_converter_python3.cc, gst/nnstreamer/tensor_converter/tensor_converter.c, packaging/run_unittests_binaries.sh, tests/meson.build, tests/nnstreamer_converter/unittest_converter.cc, tests/nnstreamer_plugins/unittest_plugins.cc, tests/test_models/data/example.json, tests/test_models/models/custom_converter_json.py, tests/test_models/models/custom_converter_test.py, tests/test_models/models/invalid_class_custom_converter.py
Add custom python converter testcases.
1. Test dynamic dimension
2. Test custom python conveter using json
=> [Converter] Add custom python converter testcases

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/tensor_common.c
Prepare later work, define util function to free config structure.
=> [Common/Util] util function to free config struct

Documentation/data-type-and-flow-control.md, gst/nnstreamer/tensor_converter/README.md
update docs - flex tensor and caps in tensor-converter.
=> [Doc] caps in tensor-converter

packaging/nnstreamer.spec
Unittest not built with DA profile
Resolves: #3348
=> [Spec] Fix DA build error

ext/nnstreamer/tensor_decoder/tensordec-pose.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, nnstreamer_example/custom_example_framecounter/nnscustom_framecounter.c
- Initialize the class member of the tensorflow-lite
- Replace atoi with g_ascii_strtoll
=> [Coverity] Initialize class member of the tflite filter

gst/nnstreamer/tensor_crop/tensor_crop.c, tests/nnstreamer_plugins/unittest_plugins.cc
support flex tensor on raw data pad.
=> [Crop] flex tensor on raw data pad

ext/nnstreamer/tensor_filter/tensor_filter_lua.cc, tests/meson.build, tests/nnstreamer_filter_lua/runTest.sh, tests/nnstreamer_filter_lua/unittest_filter_lua.cc, tests/test_models/models/passthrough.lua, tests/test_models/models/scaler.lua
- Support multiple input/output tensors
- Support all supported data types
- Elaborate error handling and index checking
- Describe simple example lua script in the source code
- Fix SSAT testcases and add negative cases
- Add gtest based unittests (including model reload)
=> [Lua] Support multi input/output tensors and tensor types

gst/nnstreamer/tensor_common.c
When getting config from caps, if caps is flexible, do not get the type and dimension from caps.
=> [Common] parse flex config from caps

gst/nnstreamer/tensor_transform/tensor_transform.c, tests/nnstreamer_plugins/unittest_plugins.cc
Add pad template and update chain function to support flexible tensor stream.
TODO: Now max rank supported in tensor-transform is 4.
=> [Transform] support flex tensor

packaging/nnstreamer.spec
Rewrite if-conditions for unit test executions.
Use direct conditions, not indirect conditions.
Add comments for conditions requiring further explanations.
=> Dist/spec: code clean w/ proper macro if/endif for unittest

debian/control, debian/nnstreamer-misc.install, debian/rules, gst/mqtt/mqttsink.c, packaging/nnstreamer.spec, tests/gstreamer_mqtt/unittest_mqtt.cc
This PR adds the GstMQTT element to the nnstreamer-misc package for Tizen and Ubunu/Debian.
=> [Dist] Add the GstMQTT element to nnstreamer-misc

packaging/nnstreamer.spec
- [pkg] Change group of nnstremaer package
```
This patch changes group of some packages to ML Framework
```
=> [pkg] Change group of nnstremaer package @open sesame 07/01 17:45

gst/nnstreamer/tensor_aggregator/tensor_aggregator.c, gst/nnstreamer/tensor_aggregator/tensor_aggregator.h, gst/nnstreamer/tensor_split/gsttensorsplit.c, gst/nnstreamer/tensor_split/gsttensorsplit.h, tests/nnstreamer_plugins/unittest_plugins.cc, tests/nnstreamer_sink/unittest_sink.cc
replace tensor-config to tensors-config
```bash
```
=> [Split] remove tensor-config @open sesame 07/02 09:11

ext/nnstreamer/extra/nnstreamer_protobuf.h, gst/nnstreamer/include/tensor_typedef.h, gst/nnstreamer/tensor_aggregator/tensor_aggregator.c, gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_converter/tensor_converter.c, nnstreamer_example/custom_example_framecounter/nnscustom_framecounter.c
Code clean, prepare caps string with tensor format.
- clean source code and update description
=> [CodeClean] prepare next caps nego

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/tensor_common.c
fix param annotation of common util functions.
=> [Doc] fix param annotation

gst/nnstreamer/tensor_merge/gsttensormerge.c, tests/nnstreamer_converter/unittest_converter.cc, tests/nnstreamer_plugins/unittest_plugins.cc, tests/nnstreamer_sink/unittest_sink.cc
- Fix unittest_sink & unittest_plugin
- fix merge & converter test
=> [test/sink] fix tensor-config in test 

gst/nnstreamer/include/tensor_typedef.h
Define caps template with tensor format.
After this PR, old caps (tensors/tensors-flexible) will be removed, and nnstreamer elements/testcases will be updated with new caps string.
=> [Caps/Tensor] caps string with format

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/include/tensor_typedef.h, gst/nnstreamer/tensor_common.c
Add util function to handle tensor format.
=> [Common] util function to handle tensor format

Documentation/getting-started-android.md
- fix docs more likely to work for beginners
---
=> [Doc] Fix android documentation

gst/nnstreamer/nnstreamer_internal.h, gst/nnstreamer/tensor_aggregator/tensor_aggregator.c, gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_common.h, gst/nnstreamer/tensor_filter/tensor_filter.c
Fix nego error case, add new function to get possible caps from config.
When receives caps event, element should return all possible caps.
=> [Common/Util] function to get possible caps @open sesame 07/06 09:50

gst/nnstreamer/registerer/nnstreamer.c, gst/nnstreamer/tensor_query/meson.build, gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_client.h, gst/nnstreamer/tensor_query/tensor_query_serversink.c, gst/nnstreamer/tensor_query/tensor_query_serversink.h, gst/nnstreamer/tensor_query/tensor_query_serversrc.c, gst/nnstreamer/tensor_query/tensor_query_serversrc.h, jni/nnstreamer.mk
=> [Query] add tensor query boilerplate

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
add custom option description in nnfw sub-plugin.
=> [Filter/NNFW] add custom description

ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc, ext/nnstreamer/tensor_filter/tensor_filter_python3.cc, ext/nnstreamer/tensor_filter/tensor_filter_snap.cc, ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, ext/nnstreamer/tensor_filter/vivante/tensor_filter_subplugin.c
This adds custom property descriptions for tensor-filter subplugins.
Fixes #3386
commit 73e46bd5fc89ef0ab1a5a02fb851a64b4a0183cc (github-fork/fix/3386, fix/3386)
Date:   Tue Jul 13 18:33:53 2021 +0900
Filter/Vivante: apply gst-indent
Vivante filter codes incur gst-indent complaints.
commit 28a383ce9b86793bd7cc80dd1da319c7ef875eda
Date:   Tue Jul 13 18:32:59 2021 +0900
Filters: add custom property descriptions
This adds custom property descriptions for
- edge-tpu
- python3
- snap
- snpe
- tf-lite
- vivante
=> Filters: add custom property descriptions @open sesame 7/14 09:00

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
Hi nnstreamer folks,
This pull request brings some enhancements to bounding boxes decoder element, while running in mobilenet ssd mode.
The first commit adds support for setting the post-processing parameters through option3. If not set, the default values are used, such as backwards compatibility is preserved.
The second commit brings an optimization while decoding, preventing to call costly expf mathematical function for each possible box while assessing a valid detected object. Instead, the comparison is done against values in the sigmoid domain.
This reduces the decoder element latency from ~20 ms to ~2ms on NXP iMX8MP platform.
Regards,
Xavier
=> Decoder: Bounding boxes: Mobilenet SSD mode enhancements

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_filter/tensor_filter.c
Add util function to copy tensor config struct.
=> [Common] util function to copy tensor config

gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h
Add init code - newly updated properties in filter.
=> [Filter] init properites

meson.build, meson_options.txt, nnstreamer.ini.in, packaging/nnstreamer.spec
Add meson-option to set fw priority for file extension (.nb, .bin)
=> [Build] framework priority option

tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc
=> [Test] fix res leak

gst/nnstreamer/tensor_converter/README.md, gst/nnstreamer/tensor_decoder/README.md
Add serialized buffer description.(flatbuf, protobuf, flexbuf)
=> [Doc] Add serialized buffer description

ext/nnstreamer/tensor_filter/tensor_filter_snap.cc
- SNAP v3.0 supports inference with TensorFlow Lite.
- Add the supported enum.
=> [filter/SNAP] Add TensorFlow Lite support

gst/mqtt/meson.build, gst/mqtt/mqttsink.c, gst/mqtt/mqttsink.h, gst/mqtt/mqttsrc.c
Resolve compiler warnings.
- Unused parameter
- Different type comparison
=> [Gst/Mqtt] Resolve compiler warnings

gst/nnstreamer/tensor_meta.c, gst/nnstreamer/tensor_meta.h, gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_common.c, gst/nnstreamer/tensor_query/tensor_query_serversink.c, gst/nnstreamer/tensor_query/tensor_query_serversrc.c
Code clean, fix possible res leak and invalid param.
=> [Query] res leak

ext/nnstreamer/tensor_filter/tensor_filter_tensorrt.cc, tests/nnstreamer_example/custom_example_tensorrt/nnstreamer_customfilter_example_tensorrt_reshape.cc
- Fix unused var build error in tensorrt related codes
=> [fix/build] Fix build error unused vars

gst/nnstreamer/tensor_query/tensor_query_common.c
Fix resource leaks reported by coverity.
2. Run test: [ ]Passed [ ]Failed [ *]Skipped
=> [Query] Fix resource leak

gst/nnstreamer/tensor_filter/tensor_filter_common.c
Remove unnecessary log while loading sub-plugins from conf file.
=> [Filter/Sub] unnecessary log to get subplugin from ini

tools/development/gstPrototxt.py
Fix warning - undefined variables.
=> [tools/pbtxt/py] fix warning

tests/meson.build, tests/nnstreamer_filter_caffe2/checkLabel.py, tests/nnstreamer_filter_custom/checkScaledTensor.py, tests/nnstreamer_filter_python3/checkScaledTensor.py, tests/nnstreamer_filter_pytorch/checkLabel.py, tests/nnstreamer_filter_tensorflow/checkLabel.py, tests/nnstreamer_filter_tensorflow2_lite/checkLabel.py, tests/nnstreamer_filter_tensorflow_lite/checkLabel.py, tests/test_utils.py, tests/transform_arithmetic/checkResult.py, tests/transform_clamp/generateTest.py, tests/transform_dimchg/checkResult.py, tests/transform_stand/checkResult.py, tests/transform_typecast/checkResult.py
Code clean, reduce duplicated source. Add util functions to run the unittest.
=> [Test/Py/CodeClean] util functions to run test

packaging/nnstreamer.spec, tests/meson.build, tests/nnstreamer_converter/runTest.sh, tests/nnstreamer_decoder/runTest.sh, tests/nnstreamer_decoder_image_labeling/runTest.sh, tests/nnstreamer_demux/runTest.sh, tests/nnstreamer_filter_caffe2/runTest.sh, tests/nnstreamer_filter_custom/runTest.sh, tests/nnstreamer_filter_pytorch/runTest.sh, tests/nnstreamer_filter_tensorflow2_lite/runTest.sh, tests/nnstreamer_filter_tensorflow_lite/runTest.sh, tests/nnstreamer_flatbuf/runTest.sh, tests/nnstreamer_flexbuf/runTest.sh, tests/nnstreamer_merge/runTest.sh, tests/nnstreamer_mux/runTest.sh, tests/nnstreamer_protobuf/runTest.sh, tests/nnstreamer_repo/runTest.sh, tests/nnstreamer_repo_dynamicity/runTest.sh, tests/nnstreamer_repo_lstm/runTest.sh, tests/nnstreamer_repo_rnn/runTest.sh, tests/nnstreamer_split/runTest.sh, tests/transform_arithmetic/runTest.sh, tests/transform_clamp/runTest.sh, tests/transform_dimchg/runTest.sh, tests/transform_stand/runTest.sh, tests/transform_transpose/runTest.sh, tests/transform_typecast/runTest.sh
Add test directory into unittest pkg and remove generated files.
=> [Test] unittest pkg

gst/mqtt/mqttcommon.h, gst/mqtt/mqttsink.c, gst/mqtt/mqttsrc.c, gst/mqtt/mqttsrc.h, tests/gstreamer_mqtt/unittest_mqtt_w_helper.cc
- Fix some minor typos in mqtt related codes
=> [mqtt/trivial] Fix typos in mqtt related codes

ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc, ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc, ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc, ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc, ext/nnstreamer/tensor_filter/tensor_filter_python3.cc, ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, ext/nnstreamer/tensor_filter/vivante/tensor_filter_subplugin.c, gst/nnstreamer/include/nnstreamer_plugin_api_filter.h, gst/nnstreamer/nnstreamer_internal.h, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h, gst/nnstreamer/tensor_filter/tensor_filter_custom.c
Add event handler for filter framework v0 and new event to check hw availability with custom option.
=> [Filter/Sub] add event handler for filter-fw v0

tests/gen24bBMP.py, tests/nnstreamer_converter/generateGoldenTestResult.py, tests/nnstreamer_filter_caffe2/checkLabel.py, tests/nnstreamer_filter_custom/checkScaledTensor.py, tests/nnstreamer_filter_python3/checkScaledTensor.py, tests/nnstreamer_filter_pytorch/checkLabel.py, tests/nnstreamer_filter_tensorflow/checkLabel.py, tests/nnstreamer_filter_tensorflow2_lite/checkLabel.py, tests/nnstreamer_filter_tensorflow_lite/checkLabel.py, tests/nnstreamer_filter_tensorrt/CheckMnist.py, tests/nnstreamer_repo_lstm/generateTestCase.py, tests/nnstreamer_repo_rnn/generateTestCase.py, tests/test_utils.py, tests/transform_arithmetic/checkResult.py, tests/transform_dimchg/checkResult.py, tests/transform_stand/generateTest.py, tests/transform_transpose/generateTest.py, tests/transform_typecast/checkResult.py
Code clean, reduce complexity.
- use itertool to remove multi loops
- separate code blocks
=> [Test/Py/CodeClean] reduce code complexity

tests/meson.build, tests/nnstreamer_query/runTest.sh, tests/nnstreamer_query/unittest_query.cc
Add tensor query tests.
Line coverage increased from 6.6% to 79.1%.
=> [TEST] Add tensor query tests @open sesame 08/27 19:27

gst/nnstreamer/tensor_query/tensor_query_common.c, gst/nnstreamer/tensor_sparse/tensor_sparse_util.c, gst/nnstreamer/tensor_sparse/tensor_sparse_util.h, tests/nnstreamer_filter_edgetpu/unittest_edgetpu.cc, tests/nnstreamer_plugins/unittest_plugins.cc, tests/nnstreamer_sink/unittest_sink.cc
Add new cases to improve test coverage and fix some minor comment.
=> [Test/CodeClean] new testcases for coverage

tests/nnstreamer_filter_lua/unittest_filter_lua.cc
- Add a testcase which covers all tensor types in tensor_filter::lua
=> [lua/test] Add tc for multiple tensor types in lua filter

Documentation/hotdoc/sitemap.txt, gst/nnstreamer/tensor_query/README.md
Add tensor query documentation.
- How to run examples.
- How to run test.
=> [Doc] Add tensor_quey README.md

tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc
- Add negative testcase for invalid custom props
- Add valid custom prop in the positive launch testcase.
=> [tvm/test] Add negative testcase for invalid custom prop

tests/gen24bBMP.py, tests/test_utils.py, tests/transform_arithmetic/checkResult.py, tests/transform_typecast/checkResult.py
- Refactor complex functions to increase FME score
This pr changes python SAM score:
SAM: 3.82 (CC:4.52, DC: 4.46, FME:3.82)
-> SAM: 4.66 (CC: 4.5, DC: 4.48, FME: 5.0)
=> [test/py] Fix test related python sources to increase SAM score

meson.build
Add feature for supported plugins in meson script.
=> [Meson] feature for supported plugins

gst/nnstreamer/tensor_sparse/tensor_sparse_dec.c, gst/nnstreamer/tensor_sparse/tensor_sparse_enc.c, gst/nnstreamer/tensor_sparse/tensor_sparse_util.c, gst/nnstreamer/tensor_sparse/tensor_sparse_util.h, tests/nnstreamer_plugins/unittest_plugins.cc
Change param - gst-memory to convert tensor data.
=> [Sparse] change util function param

gst/nnstreamer/nnstreamer_conf.c, gst/nnstreamer/nnstreamer_subplugin.h, gst/nnstreamer/tensor_common.c, tests/common/unittest_common.cc, tests/nnstreamer_decoder/unittest_decoder.cc, tests/nnstreamer_plugins/unittest_plugins.cc, tests/nnstreamer_repo_dynamicity/tensor_repo_dynamic_test.c, tests/nnstreamer_sink/unittest_sink.cc
Update testcase to improve test coverage.
=> [Test/CodeClean] improve coverage @open sesame 9/8 11:20

gst/nnstreamer/tensor_if/gsttensorif.c, gst/nnstreamer/tensor_query/tensor_query_common.c, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Fix svace issue,
- fix invalid condition to check the args.
- possible res leak in query close function.
- condition to free strings for test models.
=> [Svace] fix res leak case

gst/nnstreamer/include/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter_common.c
Fix svace issue,
- set next node when releasing the list item
- use macro to define local lock for shared table
=> [Filter/SharedModel] fix svace

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c, ext/nnstreamer/tensor_decoder/tensordec-directvideo.c, ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c, ext/nnstreamer/tensor_decoder/tensordec-pose.c, ext/nnstreamer/tensor_filter/tensor_filter_lua.cc, gst/nnstreamer/tensor_converter/tensor_converter.c, tools/development/nnstreamerCodeGenCustomFilter.py, tools/nnstreamer-toolkit.py
Previously, the nnstream project was analyzed by the LGTM system. [Alerts were discovered](https://lgtm.com/projects/g/nnstreamer/nnstreamer/), some of which are fixed in this PR. 
1. Build test: [x] Passed [ ]Failed []Skipped
2. Run test: [x] Passed [ ]Failed []Skipped
=> Fix some alerts that were detected by the LGTM system

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c, ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c, gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_converter/tensor_converter.c, tools/development/nnstreamerCodeGenCustomFilter.py, tools/nnstreamer-toolkit.py
Final correction of alerts found by the LGTM, one of which is marked as false-positive
I hope that after applying this PR, the LGTM`s check will be successful.
I think it would be nice to release v2.0.0 without LGTM alerts.
=> [Hotfix] Final fix LGTM alerts

README.md
* In accordance with the requirement of the CII Best Practices: all achievements must be specified.
* Display the LGTM current status of the project.
---
=> [Doc] Add LGTM badge

README.md
Changes are as follows:
1) Gitter - no change
2) DailyBuild - the project is successfully build
3) CII Best Practices - the project applies the best practices
4) LGTM Alerts - vulnerabilities found
5) Coverage - Test Coverage
6) Coverity - Defect Display
7) GitHub Repo Size - Repository Size
-) GitHub Issues - removed (indicated above on the page, has a negative shade)
-) GitHub Pull Requests - deleted (indicated above on the page, can be examined as not processed requests)
1. Build test: [  ]Passed [ ]Failed [x]Skipped
=> [Doc] Refactore badges in README.md @open sesame 9/24 11:22

.github/SECURITY.md
Benefits:
* Improve github profile
* One of the requirements of the CII Best Practices
=> [Doc] Add security policy

tests/nnstreamer_filter_tensorrt/runTest.sh
=> [trivial] Fix sub-plugin check in TensorRT test

gst/nnstreamer/tensor_converter/README.md
Update document to convert octet stream to static or flexible tensor.
=> [Converter/Doc] doc to convert octet stream

gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_common.c, gst/nnstreamer/tensor_query/tensor_query_serversink.c, gst/nnstreamer/tensor_query/tensor_query_serversrc.c
Clearly check the handles in finalize callback.
(e.g., gst-inspect shows gst-log if given handle is null.)
=> [Query] null ptr in finalize callback

ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc, ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc, tests/nnstreamer_decoder/unittest_decoder.cc, tests/nnstreamer_flexbuf/runTest.sh
Support flexible tensors for flexbuf. 
=> [Flexbuf] Support flexible tensors for flexbuf. 

gst/nnstreamer/tensor_query/tensor_query_common.c
Add attr to create message thread, to release thread resource.
=> [Query] detach option on msg thread

gst/nnstreamer/tensor_filter/tensor_filter_common.c, tests/common/unittest_common.cc
Add 2 commits to fix build issue from main branch.
This PR will resolve #3575 and #3579.
=> [lts/2.0] fix build issue

Documentation/hotdoc/gen-hotdoc.sh, Documentation/hotdoc/sitemap.txt, Documentation/profiling-android-pipeline.md, Documentation/tutorials/tutorial1_playing_video.md, Documentation/tutorials/tutorial2_object_detection.md, Documentation/tutorials/tutorial4_query.md, Documentation/tutorials/tutorial5_gstreamer_api.md
This patch fixes bad links in documentation.
Signed-off-by: yelini-jeong <yelini.jeong@samsung.com>
=> [Doc] Fix bad links @open sesame 12/01 19:10

gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_common.c, gst/nnstreamer/tensor_query/tensor_query_common.h, gst/nnstreamer/tensor_query/tensor_query_serversink.c
Code clean, add util function to send gst-buffer to destination.
=> [Query] util function to send gst-buffer

gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_common.c, gst/nnstreamer/tensor_query/tensor_query_common.h
Add util function to receive data and generate gst-buffer.
=> [Query] util function to receive data

gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_common.c, gst/nnstreamer/tensor_query/tensor_query_common.h, gst/nnstreamer/tensor_query/tensor_query_serversink.c, gst/nnstreamer/tensor_query/tensor_query_serversink.h
Code clean on tensor-query elements.
1. fix build issue on old machine (undefined ref).
2. remove unnecessary util functions.
=> [Query/CodeClean] remove unnecessary util functions

gst/nnstreamer/tensor_common.c
Change log level and add proper message to set default tensor format.
=> [Common] change log level to get tensor-config

Documentation/getting-started-meson-build.md
Add a simple example of the meson build for a beginner.
=> [Doc] Add meson build example.

gst/nnstreamer/tensor_query/tensor_query_serversrc.c
Set timestamp for each buffer.
=> [Query] Set timestamp for each buffer. @open sesame 12/10 14:15

gst/nnstreamer/tensor_query/tensor_query_serversink.c
This patch fixes some typos in query serversink.
=> [Typo] Fix some typos in query serversink @open sesame 12/14 16:02

tests/nnstreamer_query/unittest_query.cc
Fix invalid param - instance after launching test pipeline.
=> [Test/Query] fix invalid param

gst/nnstreamer/tensor_query/tensor_query_common.c
Fix possible resource leak - handle error case in query-server init.
=> [Query] error handing in query-server init

gst/nnstreamer/tensor_query/tensor_query_common.c
This patch fixes coverity issues (WGID 131439, CID 1243725)
Signed-off-by: yelini-jeong <yelini.jeong@samsung.com>
=> [Coverity] Fix use after free

gst/nnstreamer/tensor_common.c
Add error message for tensor common functions.
=> [Common] Add error message for tensor common functions

packaging/nnstreamer.spec
Remove invalid elements from restricted elements.
queryclient -> tensor_query_client
queryserversrc -> tensor_query_serversrc
queryserversink -> tensor_query_serversink
=> [Spec] Remove invalid elements from restricted elements. @open sesame 12/29 14:42

ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc, ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc, gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
- Fix pointer for subplugin in `cpp_close`
- Fix edgetpu and snpe filter's model path free function
=> [fix/bug] Fix destructor of cpp class subplugin

ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc, ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc, gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
- Fix pointer for subplugin in `cpp_close`
- Fix edgetpu and snpe filter's model path free function
1. Build test: [X]Passed [ ]Failed [*]Skipped
2. Run test: [X]Passed [ ]Failed [*]Skipped
=> [For LTS branch][fix/bug] Fix destructor of cpp class subplugin

tests/unittest_util.c
Fix implicit declaration on old machine.
=> [Test/Build] fix error on old machine

Documentation/getting-started-ubuntu-debuild.md
Add description for nnfw ppa.
Related issue: #3612
=> [Doc] Update debuild guide.

packaging/nnstreamer.spec
Update unnecessary dependency of filter sub-plugins.
=> [Build] unnecessary build dependency

gst/nnstreamer/tensor_query/README.md, gst/nnstreamer/tensor_query/tensor_query_client.c
- Fix invalid return value when caps is same.
- Update doc for capability of the query server and client.
- Add explanation about mqtt-hybrid
=> [Query] Update document and fix invalid return @open sesame 01/13 16:53

meson.build
Define target library to build filter-subplugin for trix-engine.
=> [Meson/TRIx] target dependency for trix engine

ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
This patch adds support for complex output types for pytorch, where the
complex output is serialized before being passed out to the gstreamer
based element - tensorfilter.
See also: #3620
=> [filter] Support complex output types for pytorch @open sesame 2/10 13:13

tests/nnstreamer_query/runTest.sh
1 second sleep time is not enough to operate query server.
see: https://github.com/nnstreamer/nnstreamer/issues/3657#issuecomment-1038708557
=> [TEST] Increase sleep time of the query test

ext/nnstreamer/tensor_filter/tensor_filter_trix_engine.cc
- Initialize class member.
- Fix bad copy and paste
=> [Filter/trix-engine] Fix svace issue

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c
remove gst-dependency to compare tensor config.
add return val of invalid condition.
=> [Util] util function to compare tensor-config

tests/cpp_methods/unittest_cpp_methods.cc
Wait until pipeline save the files.
Daily Test fail: http://nnstreamer.mooo.com/nnstreamer/ci/daily-build/build_result/latest/log/build_log_tizen_armv7l_output_2022-03-03.txt
Before this PR on armv7l: 57/100 passed
After this PR on armv7l: 100/100 passed
=> [TEST/cpp] Wait until pipeline save the files @open sesame 3/3 11:39

ext/nnstreamer/extra/meson.build
Add link to python util library in meson.
=> [Build/PyUtil] dependency to py-util

Documentation/products.md, README.md
- Update paper link
- Update support hardware
- Update product lists
=> doc: update README and products

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc, tests/nnstreamer_filter_snpe/unittest_filter_snpe.cc
- Support "userbuffer" for snpe filter
- With this mode, the memcpy from/into model's input/output does not occur
- Note that it only supports float type
- Add two simple cases to test user buffer execution
=> [filter/snpe] Support "user supplied buffer" for snpe

.github/CODEOWNERS
We have new members and members quiting.
=> CODEOWNERS: update reviewer list

Documentation/data-type-and-flow-control.md
NNStreamer 2.0 has updated data types significantly.
Update the documents accordingly.
Fixes #3661
=> Doc: data-types update with 2.0 @open sesame 3/14 15:40

.github/workflows/macos.yaml
Add macos build github action with brew
=> github-action: macos build

.github/workflows/ubuntu_clean_meson_build.yml
Test build & TC in a latest Ubuntu system with meson/ninja clean build.
=> github-action: Ubuntu clean meson build test

.github/workflows/ubuntu_clean_meson_build.yml
Fixed syntax error.
Run test action.
todo: register unit tests properly for meson test.
=> Fix ubuntu meson build github action

gst/nnstreamer/tensor_filter/tensor_filter_common.c
Fix svace issue - dereference after null check.
=> [Filter] svace issue

tests/cpp_methods/unittest_cpp_methods.cc, tests/unittest_util.h
Code clean, fix svace issue in testcase.
- count failure while loading data from file.
=> [CodeClean] fix svace issue

Documentation/API-reference.md, Documentation/component-description.md, Documentation/writing-subplugin-tensor-filter.md, README.md, gst/nnstreamer/tensor_query/README.md, jni/README.md
Change CI server domain name from nnstreamer.mooo.com to ci.nnstreamer.ai
=> [Doc] Change CI server domain name @open sesame 04/20 11:03

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
MP_PALM_DETECTION decoder for bounding box mode is presented. The model and
algorithm is based on mediapipe palm detection model and its
implementation.
Signed-off-by: Jiho Chu <jiho.chu@samsung.com>
2. Run test: []Passed [ ]Failed [ *]Skipped
v4l2src name=cam_src ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB,framerate=30/1 ! tee name=t \
t. ! queue leaky=2 max-size-buffers=2 ! videoscale ! video/x-raw,width=192,height=192,format=RGB ! tensor_converter ! \
tensor_transform mode=arithmetic option=typecast:float32,add:0.0,div:255.0 ! \
tensor_filter framework=tensorflow-lite model=tflite_model/palm_detection_lite.tflite ! \
tensor_decoder mode=bounding_boxes …
=> [decoder/bounding_box] Support decoder for mediapipe palm detection

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
Convert float value to get the object.
=> [Decoder] integ division

gst/mqtt/meson.build, gst/mqtt/ntputil.c, gst/mqtt/ntputil.h, tests/gstreamer_mqtt/unittest_ntp_util_mock.cc, tests/meson.build
Add ntp uniitest using GMock.
ntp unittest is enabled only on tizen.
=> [TEST/ntp] Add ntp unittest using GMock.

debian/nnstreamer-core.install, gst/nnstreamer/tensor_query/meson.build, gst/nnstreamer/tensor_query/nnstreamer_edge.h, gst/nnstreamer/tensor_query/nnstreamer_edge_aitt.c, gst/nnstreamer/tensor_query/nnstreamer_edge_common.c, gst/nnstreamer/tensor_query/nnstreamer_edge_common.h, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c, meson.build, meson_options.txt, packaging/nnstreamer.spec
initial commit to implement internal library for nnstreamer edge based on glib.
=> [Edge] header for nns-edge

gst/nnstreamer/nnstreamer_log.c, gst/nnstreamer/nnstreamer_log.h
Fix svace issue, check null ptr - allocation failure case in log util.
=> [Svace] check null ptr

gst/nnstreamer/meson.build
Remove unnecessary dependency from single-shot package.
=> [Package] Remove unnecessary dependency

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
- For multiple output models, let user set output tensors instead of
output layers
- And make the order of input / output tensors be consistent.
Updated:
- Some snpe models have "0" dim to represent resizable dim.
- Add a custom option "MaxResizableDim" to deal with this case.
=> [filter/snpe] Make the order of output tensors be consistent with the user given option @open sesame 4/28 09:30

gst/nnstreamer/nnstreamer_conf.c
Fix lgtm alert - name of global variable. Change param name.
=> [Conf] fix param name

ext/nnstreamer/tensor_filter/README.md
For #3713, add a usage manual because it may be not too trivial
for non-system-sw developers.
=> filter:tf-lite2-custom usage manual

gst/nnstreamer/tensor_query/nnstreamer_edge.h, gst/nnstreamer/tensor_query/nnstreamer_edge_common.c, gst/nnstreamer/tensor_query/nnstreamer_edge_common.h, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c
Update base code to handle edge event.
=> [Edge] base code for edge event

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/nnstreamer_subplugin.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_single.c, gst/nnstreamer/tensor_query/tensor_query_server.c
Replace logutil - glib funcs, use predefined log functions.
=> [Log] use internal log function

tests/nnstreamer_query/runTest.sh
Don't use & fork with bash function.
Add timeout for launching.
=> [CI TC Fail Fix] test/query: parallel client launching shouldn't use gstTest @open sesame 6/10 10:12

gst/nnstreamer/tensor_query/meson.build, gst/nnstreamer/tensor_query/nnstreamer_edge.h, gst/nnstreamer/tensor_query/nnstreamer_edge_common.c, gst/nnstreamer/tensor_query/nnstreamer_edge_common.h, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.h, gst/nnstreamer/tensor_query/nnstreamer_edge_mqtt.c
Add internal functions to handle mqtt message.
This is initial commit for mqtt-hybrid feature after separating the edge library.
=> [Edge] add mqtt functions

gst/nnstreamer/tensor_query/meson.build, gst/nnstreamer/tensor_query/nnstreamer_edge.h, gst/nnstreamer/tensor_query/nnstreamer_edge_common.h, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.h
- Add NNStreamer-edge TCP implementation.
=> [Edge] Add tcp implementation @open sesame 06/15 18:38

packaging/nnstreamer.spec
- Fix some typos in `nnstreamer.spec`.
=> [trivial] Fix typos in the spec file

gst/nnstreamer/tensor_query/nnstreamer_edge_common.h, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.h, gst/nnstreamer/tensor_query/nnstreamer_edge_mqtt.c
Update macros and mutex lock in edge handle.
=> [Edge] base code for mutex lock

gst/nnstreamer/tensor_query/nnstreamer_edge.h, gst/nnstreamer/tensor_query/nnstreamer_edge_common.c, gst/nnstreamer/tensor_query/nnstreamer_edge_common.h, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.h
Add new function to invoke event and export edge-event functions.
=> [Edge] new function to invoke event callback

gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.h
Remove global table for client IDs, and move it to edge handle.
=> [Edge] client IDs in handle

gst/nnstreamer/tensor_query/nnstreamer-edge.h, gst/nnstreamer/tensor_query/nnstreamer_edge_common.h, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.h
Refactoring to send/receive edge command and buffer.
- define command info struct to handle command, id, and memories.
- util functions to init, clear edge command.
=> [Edge] refactoring edge cmd @open sesame 07/01 10:33

ext/nnstreamer/extra/nnstreamer_grpc_common.cc
This patch modifies the hard-coded strings (e.g., libnnstreamer_grpc_*.so) which indicate the file name of the sub-plugins to use the pre-defined file extensions according to the platform.
=> [gRPC/Common] Modify hard-coded strings indicating sub-plugins' names @open sesame 07/01 20:05

debian/rules, ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc, ext/nnstreamer/tensor_filter/tensor_filter_deepview_rt.cc, ext/nnstreamer/tensor_filter/tensor_filter_lua.cc, ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, ext/nnstreamer/tensor_filter/vivante/tensor_filter_subplugin.c, gst/nnstreamer/include/tensor_typedef.h, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, gst/nnstreamer/tensor_converter/tensor_converter.c, gst/nnstreamer/tensor_data.c, gst/nnstreamer/tensor_transform/tensor_transform.c, meson.build, meson_options.txt, packaging/nnstreamer.spec, tests/nnstreamer_filter_lua/runTest.sh, tests/nnstreamer_filter_lua/unittest_filter_lua.cc, tests/transform_typecast/runTest.sh
=> Add Float16 Stream Data Type

tests/nnstreamer_query/runTest.sh, tests/nnstreamer_query/unittest_query.cc
Do not use fixed port number.
Let's get an available port number so that multiple tests do not use the same port number.
=> [TEST/query] Do not use fixed port number

Documentation/edge-ai.md
Add more explanation on edge-AI / among-device AI
=> doc/edge-ai: update documentation @open sesame 07/15 11:22

Documentation/features-per-distro.md
Update the list of features deployed via distro releases.
=> doc/distro-features: update features per distro @open sesame 7/18 16:57

tests/nnstreamer_grpc/runTest.sh
GBS does not support timeout. Remove it.
=> tests/grpc: remove timeout command @open sesame 7/20 14:29

Documentation/how-to-write-testcase.md
=> [Doc] Update how-to-write-testcase.md

gst/nnstreamer/elements/gsttensor_merge.c, gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_server.c, gst/nnstreamer/tensor_query/tensor_query_serversink.c, gst/nnstreamer/tensor_query/tensor_query_serversrc.c
Code clean, fix svace issues.
- check null string when getting caps from edge handle
- fix mem leak case
- fix invalid data comparison
=> [Svace] code clean and fix svace @Open sesame 07/22 15:50

tests/nnstreamer_grpc/runTest.sh
- Apply background test to grpc.
=> [TEST] Apply background test to grpc @open sesame 07/25 14:58

gst/join/gstjoin.c, gst/join/gstjoin.h
Don't wait all pad get eos event.
=> [Join] Don't wait all pads get eos event. @open sesame 07/27 20:28

ext/nnstreamer/extra/nnstreamer_grpc_common.cc, ext/nnstreamer/tensor_filter/tensor_filter_python3.cc, gst/nnstreamer/elements/gsttensor_srciio.c, gst/nnstreamer/include/nnstreamer_plugin_api_util.h, meson.build
Code clean, trivial, fix typo / indent and add feature for sub-plugin in meson.
=> [CodeClean] fix typo, indent

gst/nnstreamer/tensor_query/README.md, gst/nnstreamer/tensor_query/nnstreamer-edge-common.h, gst/nnstreamer/tensor_query/nnstreamer-edge-internal.h, gst/nnstreamer/tensor_query/nnstreamer-edge.h, gst/nnstreamer/tensor_query/nnstreamer_edge_aitt.c, gst/nnstreamer/tensor_query/nnstreamer_edge_common.c, gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c, gst/nnstreamer/tensor_query/nnstreamer_edge_mqtt.c, gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_client.h, gst/nnstreamer/tensor_query/tensor_query_common.c, gst/nnstreamer/tensor_query/tensor_query_common.h, gst/nnstreamer/tensor_query/tensor_query_server.c, gst/nnstreamer/tensor_query/tensor_query_server.h, gst/nnstreamer/tensor_query/tensor_query_serversink.c, gst/nnstreamer/tensor_query/tensor_query_serversink.h, gst/nnstreamer/tensor_query/tensor_query_serversrc.c, gst/nnstreamer/tensor_query/tensor_query_serversrc.h, tests/nnstreamer_query/runTest.sh, tests/nnstreamer_query/unittest_query.cc
- Update query for new edge interface.
- Separate ip and port for self and destination. 
=> [Query] Update query for new edge interface @open sesame 8/4 11:13

tests/meson.build, tests/nnstreamer_edge/generate_random_text.py, tests/nnstreamer_edge/runTest.sh, tests/nnstreamer_edge/unittest_edge.cc
This PR will be improved during the development of edgesrc and edgesink.
Changes:
- Init edgesrc and edgesink unit test.
- Add edgesrc and edgesink pipeline tests.
=> [Gst/Edge] Add pipeline tests @open sesame 8/8 17:23

tests/nnstreamer_query/runTest.sh
Disable query-hybrid test unitl the test is fixed.
Related issue: #3877
=> [TEST] Disable query-hybrid test

packaging/nnstreamer.spec
Add feature to support tensor_query using nnstreamer-edge library.
=> [Spec] feature to enable nns-edge

gst/nnstreamer/tensor_query/tensor_query_serversrc.c, tests/nnstreamer_edge/query/unittest_query.cc
Check more properties of query server.
=> [TEST] Check more properties of query server.

Documentation/component-description.md, ext/nnstreamer/tensor_filter/vivante/tensor_filter_subplugin.c, gst/nnstreamer/elements/gsttensor_converter.c
Fix wrong file path and names.
Related change: https://github.com/nnstreamer/nnstreamer/pull/3821
=> [Doc] Fix wrong file path and names.

ext/nnstreamer/extra/nnstreamer_python3_helper.cc, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
Handle error case if rank from python script is larger than max rank value.
Update log message in python helper.
=> [Py/Dims] error case to handle dimension @open sesame 09/01 11:29

tests/nnstreamer_edge/query/runTest.sh
- Add timeout option to prevent stuck during test.
- Set random available port for query client.
=> [TEST] Update query test @open sesame 09/07 16:32

.TAOS-CI/.gbs.conf
- Update repo urls to new ones.
=> [conf] Update gbs.conf to new repos

gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_serversink.c
Replace deprecated function of edge library.
=> [Query] replace deprecated function @open sesame 09/14 14:34

gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_server.c
Update changed flag and API of the nnstreamer-edge
Need Tizen group SR with https://github.com/nnstreamer/nnstreamer-edge/pull/60
=> [Edge] Update changed flag @open sesame 09/15 10:36

gst/edge/edge_common.c, gst/edge/edge_common.h, gst/edge/edge_elements.c, gst/edge/edge_sink.c, gst/edge/edge_sink.h, gst/edge/edge_src.c, gst/edge/edge_src.h, gst/edge/meson.build, gst/meson.build, gst/nnstreamer/meson.build, meson.build, packaging/nnstreamer.spec, tests/nnstreamer_edge/edge/runTest.sh
Init skelton of edgesrc and edgesink.
=> [Gst/Edge] Init edgesrc and edgesink @open sesame 09/21 13:42

packaging/nnstreamer.spec
Check dependency to nnstreamer-edge library.
=> [Spec] dependency to nns-edge

gst/edge/edge_common.c, gst/edge/edge_sink.c, gst/edge/edge_src.c, tests/nnstreamer_edge/edge/runTest.sh
- Support MQTT-hybrid connection for edgesrc and edgesink.
=> [Edge] Support MQTT-hybrid connection @open sesame 9/20 11:17

tests/meson.build, tests/nnstreamer_filter_shared_model/unittest_filter_shared_model.cc
This is a rebase of #3458 
---
Unittest to validate filter with shared key
=> [Test] Unittest for filter shared key (Rebased #3458)

tests/meson.build
Check dependency to tf-lite version to run unittest.
=> [Test] dependency to tf-lite ver

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
- Fix the outdated custom property description.
- Fix log messages.
=> [filter] Fix guide document of snpe subplugin

gst/edge/edge_sink.c, gst/mqtt/README.md, gst/mqtt/mqttsink.c, gst/mqtt/mqttsrc.c, gst/nnstreamer/tensor_query/README.md, gst/nnstreamer/tensor_query/tensor_query_serversrc.c, tests/nnstreamer_edge/query/runTest.sh
Change localhost address for mqtt from tcp://localhost to 127.0.0.1.
* mosquitto lib cannot parse the previous form.
=> [Edge] Change localhost address for mqtt @open sesame 10/25 14:47

Documentation/features-per-distro.md, Documentation/nnstreamer_capi.md, README.md
- Updated releases.
- Updated products and services.
=> Update documentations with recent data.

gst/edge/edge_src.c, gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_serversrc.c
Change input parameter type of the nns_edge_data_get. 
* Need to force merge and group SR with https://github.com/nnstreamer/nnstreamer-edge/pull/107.
=> [Edge] Change input parameter type of the nns_edge_data_get.

gst/join/gstjoin.c, gst/nnstreamer/tensor_filter/tensor_filter.c
- Remove unused code in gstjoin.c
- Fix mem leak in tensor_filter
=> [trivial] Fix svace issues

gst/nnstreamer/elements/gsttensor_if.c, tests/nnstreamer_if/unittest_if.cc
If  `NNS_TENSOR_RANK_LIMIT` is increased `~  ! tensor_if name=tif silent=false compared-value=A_VALUE compared-value-option=0:0:0:0,0 supplied-value=100 ! ~ `  can't be used.
This patch allows to declare compared-value-option in tensor_if without full dimension. 
Undeclared dimension will be filled with zero.
=> [TensorIf] Allow to declare option without full dimension @open sesame 11/17 18:07

.github/workflows/macos.yaml
Updating the given image incurs an error with sbt. Don't try to update it.
Fixes #3960
=> Workaround:CI/macos do not try to update brew images.

gst/nnstreamer/nnstreamer_plugin_api_impl.c
Code clean, remove unnecessary func call to get peer caps.
=> [Common] function to get peer caps

tests/common/unittest_common.cc, tests/cpp_methods/unittest_cpp_methods.cc, tests/nnstreamer_converter/unittest_converter.cc, tests/nnstreamer_decoder/unittest_decoder.cc, tests/nnstreamer_if/unittest_if.cc, tests/nnstreamer_sink/unittest_sink.cc, tests/unittest_util.c, tests/unittest_util.h
Fix coverity issue.
- Check return value of `g_remove`.
=> [TEST/coverity] Check return value

.TAOS-CI/.gbs.conf
- Change latest -> reference to fix CI build failure
=> [build] Fix gbs.conf for base repo @open sesame 2/21 18:01

gst/datarepo/datarepo_elements.c, gst/datarepo/gstdatareposrc.c, gst/datarepo/gstdatareposrc.h, gst/datarepo/meson.build, gst/meson.build, packaging/nnstreamer.spec
datareposrc initial version.
Element reads file data from directory and stores them to gstbuffer using datareposrc features.
datareposrc feature will be continuously updated.
=> [datareposrc] Create datareposrc initial element

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/nnstreamer_plugin_api_impl.c, tests/nnstreamer_sink/unittest_sink.cc
Code clean and fix svace issue,
1. update util function name and remove unnecessary function.
2. unmap gst-memory if failed to handle extra tensor.
=> [CodeClean] function to add extra tensor

gst/nnstreamer/include/tensor_typedef.h, gst/nnstreamer/nnstreamer_plugin_api_impl.c
Hide data structure (header in memory block) for extra tensor.
=> [Common] hide struct for extra tensor

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
This patch fixes the wrong start index in tflite filter. 
If rank starts from 0, some dimension info can be ignored.
See also: #3814 
=> [filter] Fix the wrong index in tflite filter @open sesame 03/27 17:33

gst/nnstreamer/elements/gsttensor_trainer.c
Determined g_cond_wait by train_complete when receive EOS
- To avoid dead lock, g_cond_wait is determined by train_complete value of GstTensorTrainerFrameworkInfo when receive EOS 
=> [tensor_trainer] Determined g_cond_wait by train_complete when receive EOS

ext/nnstreamer/tensor_filter/tensor_filter_trix_engine.cc
Check rank limit (max rank in trix-engine is 4 but nnstreamer is 8)
=> [Subplugin/TRIx] rank limit @open sesame 04/07 10:10

gst/datarepo/datarepo_elements.c, gst/datarepo/gstdatareposink.c, gst/datarepo/gstdatareposink.h, gst/datarepo/meson.build
- Create datareposink initial version
- Add location property to set the path for saving a file
- Add basic file writing functionality
=> [datareposink] Create datareposink initial element @open sesame 04/13 22:50

gst/nnstreamer/elements/gsttensor_trainer.c, gst/nnstreamer/elements/gsttensor_trainer.h
Modify query caps to support negotiation with fixed caps of peers  
- Support negotiation without tensor_converter
- Modify Example launch line
=> [tensor_trainer] Modify query caps to support negotiation with fixed caps of peers  

gst/edge/edge_common.c, tests/nnstreamer_edge/edge/runTest.sh
Add run test for MQTT data transmission of edgesrc/sink.
=> [EDGE] Add MQTT data transmission test @open sesame 04/20 12:55

.github/workflows/macos.yaml, .github/workflows/risc-v.yml, .github/workflows/ubuntu_clean_meson_build.yml, debian/control, gst/datarepo/gstdatareposrc.c, gst/datarepo/gstdatareposrc.h, gst/datarepo/meson.build, meson.build, packaging/nnstreamer.spec
- Add setting json file path to read meta information of the file specified as locaton
- Add function to read and validate JSON file for each types
- The sample size is calculated from reading JSON file
```
gst-inspect-1.0 datareposrc
[...]
json                : Json file path containing the meta information of the file specified as location
flags: readable, writable, changeable only in NULL or READY state
String. Default: null
```
=> [datareposrc] Add json property

.github/workflows/macos.yaml, .github/workflows/risc-v.yml, .github/workflows/ubuntu_clean_meson_build.yml, debian/control, gst/datarepo/gstdatareposink.c, gst/datarepo/gstdatareposink.h, gst/datarepo/meson.build, meson.build, packaging/nnstreamer.spec
- Add setting JSON file path to write the meta information of a sample data
- Write gstreamer caps, sample size, and number of total samples
- In the case of flexible tensors, write the offset of each sample except the sample size
=> [datareposink] Add json property

gst/datarepo/gstdatareposink.c, gst/datarepo/gstdatareposrc.c, tests/nnstreamer_datarepo/unittest_datareposink.cc, tests/nnstreamer_datarepo/unittest_datareposrc.cc
- Fix covertiy and SVACE issue
=> [SVACE] Fix SVACE and covertiy issue

Documentation/tutorials/tutorial2_object_detection.md
Add `nnstreamer-tensorflow2-lite` package to the install instruction in the tutorial
https://github.com/nnstreamer/nnstreamer/blob/main/.github/PULL_REQUEST_TEMPLATE.md which placed here has been removed by @wooksong
=> Update tutorial2_object_detection.md @open sesame 04/24 17:28

debian/control.ubuntu.ppa
- Add json-glib-dev dep
- Remove python2, tf, tf-lite
=> [Debian] Update ubuntu control file

tests/nnstreamer_sink/unittest_sink.cc
- remove meaningless test
- issue has been resolved
=> [TEST] remove meaningless test

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
Code clean, add brief tag of newly added functions.
=> [CodeClean] missed tags

tests/nnstreamer_filter_single/unittest_filter_single.cc, tests/nnstreamer_plugins/unittest_plugins.cc, tests/nnstreamer_sink/unittest_sink.cc
Run testcases when tf-lite ver 2.x is enabled.
=> [Test] enable testcases for tf-lite

ext/nnstreamer/tensor_filter/tensor_filter_mxnet.cc, ext/nnstreamer/tensor_source/tensor_src_tizensensor.c, gst/nnstreamer/elements/gsttensor_trainer.c, gst/nnstreamer/elements/gsttensor_transform.c, gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, gst/nnstreamer/tensor_filter/tensor_filter.c, tests/common/unittest_common.cc, tests/nnstreamer_datarepo/unittest_datareposrc.cc, tests/nnstreamer_filter_lua/unittest_filter_lua.cc, tests/nnstreamer_if/unittest_if.cc, tests/nnstreamer_sink/unittest_sink.cc, tests/nnstreamer_trainer/unittest_trainer.cc, tests/tizen_sensor/unittest_tizen_sensor.cc
Code clean, fix indent and remove unnecessary space.
=> [CodeClean] fix indent and unnecessary space

gst/nnstreamer/elements/gsttensor_trainer.c
Fix invalid tensor-config,
1. parse config when receiving caps event.
2. init/free config in start/finalize callback.
=> [Trainer] parse config in caps event

tests/nnstreamer_sink/unittest_sink.cc
For debug mode, parse error message received from pipeline.
=> [Test] parse error msg

tests/meson.build, tests/nnstreamer_datarepo/meson.build
Fix meson script, build testcases of datarepo when option is enabled.
=> [Meson/Test] testcases for datarepo

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c
Code clean, remove duplicated lines using util function.
=> [Common] duplicated lines

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
- If the property is given as  `... option6=1 ...`, result bounding boxes will be marked with unique IDs.
- Centroid based track algorithm is used. It calculate every euclidean centroid distance among previous boxes and incoming boxes. And match from the least distance pair.
NOTE that this is too naive and trivial to be applied to production level application. Use it for test purpose.
If you need more information about object tracking task, refer https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvtracker.html
DEMO: https://github.com/anyj0527/nnstreamer_pipeline_zoo/blob/main/person_detect_tracking/README.md
=> [decoder] Add "tracking" feature for bounding boxes

gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
Add util function to compare tensor dimensions.
=> [Common] util to compare dimensions

debian/control, debian/control.debian, debian/control.ubuntu.ppa, debian/nnstreamer-core.install, debian/nnstreamer-datarepo.install
Add missed libraries in debian package.
=> [Build] missed libs in debian package

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, tests/common/unittest_common.cc
Prepare increasing max rank and 0-init dimension case.
=> [Common] prepare 0-init dimension

gst/datarepo/gstdatareposink.c
Code clean, cleanup unnecessary lines.
- fix data type from gst-buffer
- handle error message
=> [CodeClean/RepoSink] unnecessary lines

gst/datarepo/gstdatareposrc.c, gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h
Code clean, fix indent and use util function for gst-caps.
=> [CodeClean] util function for caps

gst/nnstreamer/include/tensor_filter_custom_easy.h, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c, tests/nnstreamer_filter_custom/unittest_filter_custom.cc
- Support dynamic invoke
- The filter sub-plugin writer should update invoke function to support dynamic invoke.
- dynamic invoke function is added for custom-easy filter.
=> [Filter] Support dynamic invoke with custom-easy

gst/nnstreamer/nnstreamer_plugin_api_impl.c
Code clean, reduce duplicated mem-map calls for extra tensor memory.
=> [Common] unnecessary mem-map calls

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/nnstreamer_plugin_api_impl.c
Update doc, delete unnecessary param. (It was removed from prev PR.)
=> [Common/Doc] removed param

gst/nnstreamer/elements/gsttensor_crop.c
Push eos event to src pad when collect pad is set to EOS state.
=> [tensor_crop] Push EOS event

gst/nnstreamer/nnstreamer_plugin_api_impl.c
Code clean, remove unnecessary local val and use util function to handle extra tensors.
=> [CodeClean] use util func for extra tensors

gst/datarepo/gstdatarepo.c, gst/datarepo/gstdatarepo.h, gst/datarepo/gstdatareposink.c, gst/datarepo/gstdatareposink.h, gst/datarepo/gstdatareposrc.c, gst/datarepo/gstdatareposrc.h, gst/datarepo/meson.build
Define new enum of incoming data type for data-repo elements.
=> [DataRepo] enum of incoming data type

gst/datarepo/gstdatareposrc.c
Prepare extra tensors, use util function to get nth info.
=> [DataRepo] util to get nth info

gst/nnstreamer/nnstreamer_plugin_api_impl.c
- Decrease log level since the line is in proper scenario when the num_tensors is exactly 16.
=> [trivial] Fix log level warn -> info

gst/datarepo/gstdatarepo.c, gst/datarepo/gstdatarepo.h, gst/datarepo/gstdatareposink.c, gst/datarepo/gstdatareposrc.c
Add util function to get data type from caps.
=> [DataRepo] util to get data type

gst/nnstreamer/nnstreamer_plugin_api_impl.c
Handle extra tensors when reconfiguring the gst-buffer.
=> [Common] reconfigure gst-buffer with extra tensors

gst/datarepo/gstdatareposink.c, gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/tensor_filter/tensor_filter.c
Change the name of common util function.
=> [Common] change function name

gst/nnstreamer/nnstreamer_plugin_api_impl.c, tests/common/unittest_common.cc
Check memory size before parsing tensor-meta.
=> [Common] check mem size of flex tensor

gst/nnstreamer/nnstreamer_plugin_api_impl.c
Update util function to append flexible tensor into gst-buffer.
=> [Common] appending flexible tensor

gst/nnstreamer/elements/gsttensor_demux.c
Update util functions to handle memories in gst-buffer.
=> [Demux] util functions to handle memories

gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
Reduce unnecessary logs, add macro to check valid meta.
=> [Common] macro to check valid meta

gst/nnstreamer/elements/gsttensor_trainer.c
- Apply NNS_TENSOR_SIZE_EXTRA_LIMIT
- Bug fix: remove invalid flexible header pointer
remove buffer overflow related to the wrong tensor size
- Add check if tensor is flexible
=> [tensor_trainer]Apply NNS_TENSOR_SIZE_EXTRA_LIMIT and bug fix for flexible tensor operation

gst/nnstreamer/elements/gsttensor_trainer.c
A pushed gstbuffer by some src-element(not datareposrc) is prerolled if set sync=true.
so, it needs to create a framework in the chain function
- Add function to create a framework in the chain function
- Modify code related g_cond_wait
=> [tensor_trainer] Add function to create a framework in the chain function

packaging/nnstreamer.spec
Update allowed elements in tizen, clearly define the list of elements.
=> [Build/Tizen] allowed elements

tests/nnstreamer_datarepo/unittest_datareposrc.cc
Fix svace issue, set null to prevent duplicated free.
=> [Test/CodeClean] prevent duplicated free

.github/workflows/gbs_x64.yml
Add Github action for nntrainer integration build.
=> [Github Action] Add nntrainer integraion build @open sesame 08/23 13:12

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
- Add boundingbox decoder for yolov8 TODO: refactor yolov5 and yolov8 which are sharing many common parts
Tested simple pipeline:
```
v4l2src ! videoscale ! videoconvert ! video/x-raw,width=320,height=320,format=RGB,framerate=30/1,pixel-aspect-ratio=1/1 ! tee name=t \
t. ! queue ! tensor_converter ! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:320:320:1 ! \
tensor_transform mode=arithmetic option=typecast:float32,add:0.0,div:255.0 ! \
queue leaky=2 max-size-buffers=2 ! \
tensor_filter framework=tensorflow2-lite model=~/ultralytics/yolov8s_saved_model/yolov8s_float16.tflite custom=Delegate:XNNPACK,NumThreads:4 latency=1 ! \
other/tensors,num_tensors=1,types=float32,format=static,dimensions=2100:84:1 ! \
tensor_transform mode=transpose option=1:0:2:3 ! …
```
=> [decoder] Add boundingbox decoder for yolov8

tests/nnstreamer_filter_custom/unittest_filter_custom.cc
Someone has forgot to call free.
=> memleak fix: unittest/custom filter

gst/nnstreamer/elements/gsttensor_srciio.c
Bug fix, init gst-info in list inside of the loop.
=> [Src/IIO] init gst-info in list

ext/nnstreamer/tensor_decoder/tensordec-pose.c
Change condition to check tensor dimension - allows 0 dim.
=> [Decoder/Pose] condition to check tensor dims

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, ext/nnstreamer/tensor_filter/tensor_filter_trix_engine.cc, tests/nnstreamer_filter_openvino/unittest_openvino.cc, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Use util function to get nth info from tensors-info struct.
=> [Common] util to get nth gst-info

.TAOS-CI/.gbs.conf, .github/workflows/gbs_x64.yml, .github/workflows/tizen.gbs.conf
- Change url from Tizen to Tizen-7.0 in gbs.conf file
- To support further changes upon tizen-7.0
=> [lts][gbs] Fix gbs repo url to Tizen 7.0

gst/datarepo/gstdatareposink.c, tests/nnstreamer_datarepo/unittest_datareposink.cc, tests/nnstreamer_datarepo/unittest_datareposrc.cc
There are a few more leaks to be fixed.
=> DataRepo Memory Leak Fix @open sesame 8/30 16:24

tests/cpp_methods/cppfilter_test.cc, tests/nnstreamer_example/custom_example_LSTM/dummy_LSTM.c, tests/nnstreamer_example/custom_example_RNN/dummy_RNN.c, tests/nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c, tests/nnstreamer_example/meson.build, tests/nnstreamer_if/unittest_if.cc, tests/test_models/models/custom_converter.py, tests/test_models/models/custom_decoder.py, tools/development/nnstreamerCodeGenCustomFilter.py
1. Get the length of dimension, not constant.
2. Init dim as 0 in some testcase.
=> [Test] length of dims

ext/nnstreamer/extra/nnstreamer_python3_helper.cc, tests/test_models/models/scaler.py
This patch removes filling the dimension value with 1.
Tensor dimension initial value is 0.
=> [python] init dimension as 0  @open sesame 09/05 10:53

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c, ext/nnstreamer/tensor_decoder/tensordec-pose.c, ext/nnstreamer/tensor_filter/tensor_filter_mxnet.cc, gst/edge/edge_common.h, gst/edge/edge_src.c, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/tensor_common.h
Code clean, fix indent and code style.
=> [CodeClean] indent and code style

gst/nnstreamer/elements/gsttensor_converter.c, tests/nnstreamer_plugins/unittest_plugins.cc, tests/nnstreamer_sink/unittest_sink.cc
Update tensor dimension of incoming data, 0-init.
- video : [ch][w][h][frames]
- audio : [ch][samples]
- text : [size][samples]
- octet/tensor : [size]
=> [Converter] incoming data format

ext/nnstreamer/extra/nnstreamer_python3_helper.cc
This patch changes dims default value from 1 to 0 in python helper.
=> [python] change dims default value from 1 to 0

ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc, ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc, ext/nnstreamer/tensor_filter/tensor_filter_deepview_rt.cc, ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc, ext/nnstreamer/tensor_filter/tensor_filter_lua.cc, ext/nnstreamer/tensor_filter/tensor_filter_mediapipe.cc, ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c, ext/nnstreamer/tensor_filter/tensor_filter_mxnet.cc, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc, ext/nnstreamer/tensor_filter/tensor_filter_python3.cc, ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc, ext/nnstreamer/tensor_filter/tensor_filter_snap.cc, ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorrt.cc, ext/nnstreamer/tensor_filter/tensor_filter_trix_engine.cc, ext/nnstreamer/tensor_filter/tensor_filter_tvm.cc
Util function to get nth gst-info and fill remained dim as 0.
TODO:
I did not build and test all subplugins, need to check all subplugins later.
=> [Filter/Sub] fill 0 dim at nth info

packaging/nnstreamer.spec
Update the list of allowed elements - multifilesrc/sink.
=> [Tizen] allow multifilesrc/sink

ext/nnstreamer/tensor_filter/tensor_filter_snap.cc, gst/nnstreamer/elements/gsttensor_transform.md, gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, tests/test_models/models/passthrough.py
Fix test and comments.
- Remove useless initialization
- Change comment and docs
=> [CodeClean] test and comments

gst/nnstreamer/include/tensor_typedef.h, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, tests/common/unittest_common.cc
Set max length of tensor dimension in tensor-meta, same with tensor rank limit.
=> [Common] dimension in tensor-meta

ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc, ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc, ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc
Code clean, remove unnecessary copy of tensors-info and use util to get nth info.
=> [Subplugin/Flatbuf] util to get nth info

gst/nnstreamer/elements/gsttensor_crop.c, gst/nnstreamer/elements/gsttensor_merge.c, gst/nnstreamer/elements/gsttensor_mux.c
Remove random number, use util function to get new stream-id.
=> [CodeClean] util function to get stream-id

gst/datarepo/gstdatareposrc.c
This patch applies g_auto and g_autofree for local gchar * and gchar ** variables to improve readability.
=> DataRepo/Src: Apply g_autoptr for local variables

gst/nnstreamer/meson.build, gst/nnstreamer/ml_agent.c, gst/nnstreamer/ml_agent.h, gst/nnstreamer/tensor_filter/tensor_filter_common.c, meson.build, meson_options.txt, packaging/nnstreamer.spec
This patch is an initial draft to bring the ML Agent features into NNS.
=> Filter/MLAgent: Initial draft for ml-agent support in TensorFilter

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
- Add an option to decide whether to log (print) result boxes.
An example:
```sh
...
** INFO: 16:50:53.507: Detect 8 boxes in 320 x 320 input image
** INFO: 16:50:53.507: [person] x:66 y:76 w:237 h:171 prob:0.8498
** INFO: 16:50:53.507: [tv] x:0 y:70 w:40 h:82 prob:0.7554
** INFO: 16:50:53.507: [chair] x:132 y:71 w:51 h:75 prob:0.6667
** INFO: 16:50:53.507: [laptop] x:63 y:181 w:124 h:66 prob:0.4536
** INFO: 16:50:53.507: [keyboard] x:63 y:218 w:65 h:32 prob:0.4395
** INFO: 16:50:53.507: [mouse] x:62 y:199 w:23 h:19 prob:0.4324
** INFO: 16:50:53.507: [book] x:0 y:181 w:24 h:26 prob:0.2654
** INFO: 16:50:53.507: [mouse] x:174 y:228 w:14 h:18 prob:0.2560
...
```
=> [decoder] Add log option for bounding_box decoder @open sesame 10/10 17:02

gst/nnstreamer/elements/gsttensor_split.c
1. split->tensorseg is not freed when overwritten.
2. tensordim pointers are never freed but new-ed frequently.
=> memleak fix: tensor_split forgot to free things. @open sesame 8/31 09:05

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
- Let option3 of yolo decoders can handle user provided parameters.
For yolov5 and yolov8 mode: The option3 requires up to 3 numbers, which tell
- whether the output values are scaled or not 0: not scaled (default), 1: scaled (e.g., 0.0 ~ 1.0)
- the threshold of confidence (optional, default set to 0.25)
- the threshold of IOU (optional, default set to 0.45)
An example of option3 is "option3=0:0.65:0.6"
=> [decoder] Let user set yolo decoder parameters

gst/nnstreamer/nnstreamer_log.c
=> Delete unnecessary empty line

tests/nnstreamer_decoder_pose/runTest.sh
- Add a simple test for option3 and option4 (increasing line coverage)
=> [test] Add simple ssat testcase for pose decoder

gst/nnstreamer/elements/gsttensor_decoder.c, gst/nnstreamer/registerer/nnstreamer.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c
Show available frameworks / mode with gst-inspect. This is the first step to address #3903
@songgot : please add similar feature to tensor_trainer
=> decoder/filter: more info for gst-inspect.

gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
- Let the method returns string ended with "]" always.
- Let get_dimension_string returns NULL when given dim is filled with 0
=> [util] Fix gst_tensors_info_to_string

Documentation/gst-launch-script-example.md
- Add a simple audio classification gst-launch example.
- This resolves #3777
=> [doc] Add a gst-launch-script example for audio

.github/workflows/ubuntu_clean_llvm_build.yml, .github/workflows/ubuntu_clean_meson_build.yml
- Let ubuntu build install proper meson and python.
- And use meson commands explicilty rather than use outdated action from
github marketplace
=> [action] Fix meson install and usage

gst/nnstreamer/include/tensor_typedef.h, gst/nnstreamer/nnstreamer_plugin_api_impl.c
Hide old rank limit from header.
=> [Common] hide old rank limit

gst/nnstreamer/nnstreamer_plugin_api_impl.c
Code clean, use util function to handle nth tensor.
=> [Common] util to get nth info

ext/nnstreamer/tensor_converter/tensor_converter_python3.cc
Change util function to handle gst-buffer including tensors.
=> [Converter/Python] function to handle tensor buffer

gst/nnstreamer/nnstreamer_plugin_api_impl.c
Fix mem leak case if failed to append memory into gst-buffer.
=> [Common] fix mem leak case

ext/nnstreamer/extra/nnstreamer_python3_helper.cc, ext/nnstreamer/extra/nnstreamer_python3_helper.h
Validate output tensors info after parsing pyobject.
=> [Python] validate tensors info

gst/nnstreamer/nnstreamer_plugin_api_impl.c
Code clean, check index to get nth tensor from gst-buffer and remove unnecessary code.
=> [Common] check index to get nth tensor

ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
Code clean, fix mem leak case when failed to add new gst-buffer.
=> [Tizen/SensorSrc] fix mem leak case

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c, ext/nnstreamer/tensor_decoder/tensordec-directvideo.c, gst/nnstreamer/elements/gsttensor_trainer.c, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, jni/nnstreamer.mk, tests/nnstreamer_example/custom_example_LSTM/dummy_LSTM.c
Define macro to specify video formats supported in decoder direct-video.
=> [Decoder] macro for video formats

ext/nnstreamer/tensor_sink/tensor_sink_grpc.c, ext/nnstreamer/tensor_source/tensor_src_grpc.c
Release tensor-config struct when finalizing the element.
=> [Element/gprc] release tensor-config struct

tests/nnstreamer_example/custom_example_LSTM/dummy_LSTM.c, tests/nnstreamer_filter_openvino/unittest_openvino.cc
Code clean, use valid macro in test.
=> [Test/CodeClean] macro to handle tensor info

gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
Set default value after releasing tensor information struct.
=> [Common] init after free

gst/datarepo/gstdatareposrc.c
Code clean,
- reduce function call, parse caps and update stream type.
- update log message.
=> [DataRepo/CodeClean] parse gst-caps

gst/edge/edge_sink.c, gst/edge/edge_sink.h, gst/edge/edge_src.c, gst/edge/edge_src.h, gst/edge/meson.build, gst/meson.build
Use util function if current caps is tensor stream.
=> [Edge] util to handle tensor info

gst/nnstreamer/nnstreamer_plugin_api_impl.c
This patch introduces g_autofree and g_auto for automatic memory cleaning of "gchar *" and "gchar **", respectively. Note that "GStrv" is a typedef alias for "gchar **".
=> Common/API: Introduce g_auto for automatic memory cleaning of "gchar *" @open sesame 11/17 18:20

ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.cc, ext/nnstreamer/extra/nnstreamer_grpc_protobuf.cc, ext/nnstreamer/extra/nnstreamer_protobuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc, ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
Use common util function to handle tensor data.
=> [Subplugin/flatbuf/protobuf] util to handle tensor data

gst/datarepo/gstdatareposrc.c, gst/datarepo/gstdatareposrc.h, gst/nnstreamer/elements/gsttensor_converter.c, gst/nnstreamer/elements/gsttensor_crop.c, gst/nnstreamer/elements/gsttensor_decoder.c, gst/nnstreamer/elements/gsttensor_if.c, gst/nnstreamer/elements/gsttensor_merge.c, gst/nnstreamer/elements/gsttensor_mux.c, gst/nnstreamer/elements/gsttensor_reposrc.c, gst/nnstreamer/elements/gsttensor_sparsedec.c, gst/nnstreamer/elements/gsttensor_sparseenc.c, gst/nnstreamer/elements/gsttensor_srciio.c, gst/nnstreamer/elements/gsttensor_transform.c, gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, gst/nnstreamer/tensor_query/tensor_query_client.c, gst/nnstreamer/tensor_query/tensor_query_serversink.c
Code clean, use common util function to handle tensor information and memory.
=> [CodeClean/Element] util function to handle tensors

.github/CODEOWNERS
Update reviewers list in nnstreamer repo.
=> [Reviewers] update reviewers

Documentation/component-description.md, README.md
- Fix outdated urls for Tizen releases.
=> [doc] Fix outdated urls

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/datarepo/gstdatareposrc.h, gst/nnstreamer/elements/gsttensor_trainer.c, gst/nnstreamer/include/nnstreamer_plugin_api_filter.h, gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/include/tensor_typedef.h, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_single.c, tests/common/unittest_common.cc
Change definition for the max number of tensors (256), and update related code.
=> [Common] macro for max number of tensors

gst/nnstreamer/elements/gsttensor_demux.c, gst/nnstreamer/elements/gsttensor_if.c, gst/nnstreamer/ml_agent.c, tests/nnstreamer_filter_extensions_common/meson.build, tools/development/parser/meson.build
- Fix compile error with clang
- Fix some typos in some old source code.
=> [build] Enable clang with some deps @open sesame 11/23 21:55

gst/nnstreamer/elements/gsttensor_transform.c, tests/nnstreamer_plugins/unittest_plugins.cc
tensor-transform cannot determine the caps, this element can set out-caps by using incoming caps. 
Remove unnecessary query for peer caps and update types of out-caps if input has tensors.
=> [Transform] available caps without peer

.github/workflows/risc-v.yml, tests/nnstreamer_filter_lua/unittest_filter_lua.cc
=> github-action/riscv: enable gtest

gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/tensor_filter/tensor_filter.c, tests/nnstreamer_plugins/unittest_plugins.cc
For caps negotiation, compare tensor dimension if caps is tensor stream and already configured.
=> [Filter] condition to update dimension

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
After implementing 0-init dims, tf-lite subplugin fills zero when changing input dimension.
Fill 1 if given dimension is 0 dim value.
=> [Filter/TF-lite] fill 1 when changing input dimension

.github/workflows/get_ssat.sh, .github/workflows/risc-v.yml
Get SSAT and build SSAT for RISC-V
Then, Run!
@TODO: SSAT TC fails in RISC-V.
Either fix failed cases or let it ignore in RISC-V build.
=> Add SSAT to RISC-V github-action

ext/nnstreamer/tensor_filter/README.md, ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_ncnn.cc, meson.build, meson_options.txt, tests/meson.build, tests/nnstreamer_filter_ncnn/runTest.sh, tests/test_models/labels/squeezenet_labels.txt, tests/test_models/models/ncnn_models/squeezenet_v1.1.param
This PR is to newly add [ncnn 20230816](https://github.com/Tencent/ncnn/tree/20230816) subplugin support for tensor_filter.
**Building ncnn:**
Without Vulkan
```bash
sudo apt install build-essential git cmake libprotobuf-dev protobuf-compiler libomp-dev libopencv-dev
cmake -GNinja -Bbuild -S. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DNCNN_SHARED_LIB=ON
sudo ninja -Cbuild install
```
With Vulkan (recommended)
```bash
sudo apt install build-essential git cmake libprotobuf-dev protobuf-compiler libomp-dev libvulkan-dev vulkan-tools libopencv-dev
cmake -GNinja -Bbuild -S. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DNCNN_SHARED_LIB=ON -DNCNN_VULKAN=ON
sudo ninja -Cbuild install
``` …
=> [Filter/ncnn] Add a sub-plugin filter for ncnn

debian/control, debian/control.ubuntu.ppa
We have multiple control files for different distros. Clean up ubuntu-ppa control file.
Reported by Q2 of #4357
Fixes the first half of #4358
CC: @IvanFilipov
=> Ubuntu: clean up control file.

gst/edge/meson.build, meson.build
Code clean, use pkgconfig to check nnstreamer-edge dependency.
=> [Build/Edge] check nns-edge dependency

ext/nnstreamer/tensor_filter/meson.build
Code clean, generate tflite-custom library in build directory.
=> [Build/TF-lite-custom] gen shared lib in build dir

debian/nnstreamer-dev.install, debian/nnstreamer-single-dev.install, nnstreamer-internal.pc.in, packaging/nnstreamer.spec
1. move util for trainer (single-devel > devel)
2. update library (link to nns-single, internal devel package)
=> [Pkg] header file for devel package

ext/nnstreamer/tensor_decoder/tensordec-pose.c, ext/nnstreamer/tensor_decoder/tensordec-python3.cc, ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc, ext/nnstreamer/tensor_filter/tensor_filter_deepview_rt.cc, ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc, ext/nnstreamer/tensor_filter/tensor_filter_lua.cc, ext/nnstreamer/tensor_filter/tensor_filter_mediapipe.cc, ext/nnstreamer/tensor_filter/tensor_filter_ncnn.cc, ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorrt.cc, ext/nnstreamer/tensor_filter/tensor_filter_tvm.cc, gst/nnstreamer/include/nnstreamer_util.h, gst/nnstreamer/nnstreamer_log.c, meson.build, packaging/nnstreamer.spec, tests/gstreamer_mqtt/unittest_mqtt_w_helper.cc, tests/meson.build, tests/nnstreamer_filter_ncnn/runTest.sh, tests/nnstreamer_filter_onnxruntime/runTest.sh
Trivial, fix indent and codestyle for line comment.
=> [CodeClean] fix indent and codestyle

ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
Fix mem leak, free model path in destructor.
=> [Filter/ArmNN] fix mem leak

gst/nnstreamer/elements/gsttensor_transform.h, gst/nnstreamer/ml_agent.c
Code clean, fix indent and util function to get list size.
=> [CodeClean] util to get list size

packaging/nnstreamer.spec
add default onnxruntime true option for Tizen releases.
=> [add/onnxruntime] Update onnxruntime_support on

ext/nnstreamer/tensor_filter/tensor_filter_onnxruntime.cc
Fix covertiy and SVACE issue
- ```model_path``` isn't initialized. fixed it.
=> [fix/svace] fix svace issue

tests/nnstreamer_filter_custom/unittest_filter_custom.cc
Due to multithread nondeterminism, we get
occasional unit test error from the "new_data_cb"
callback.
Create a lock and make data local to the function.
=> test: nondeterministic unit test error.

.github/workflows/static.check.scripts/flawfinder.sh, .github/workflows/static.check.scripts/prohibited-words.sh, .github/workflows/static.check.scripts/prohibited-words.txt, .github/workflows/static.check.scripts/shellcheck.sh, .github/workflows/static.check.scripts/signed-off-by.sh, .github/workflows/static.check.scripts/sloccount.sh, .github/workflows/static.check.yml
The following TAOS-CI pr-prebuild checks are imported
- sloccount
- prohibited words
- signed off by
- shellcheck
- flawfinder
- coverity
=> actions: add sloccount, prohibited-words, signed-off-by, ... @open sesame 2/1 09:58

debian/control, debian/control.ubuntu.ppa, debian/nnstreamer-onnxruntime.install, debian/rules
- add new pkg for onnxruntime in debian build
=> [build/debian] add dependency to onnxruntime

gst/nnstreamer/elements/gsttensor_repo.c, gst/nnstreamer/nnstreamer_subplugin.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c
Fix svace issues, add missing lock.
=> [CodeClean] missing lock

tests/nnstreamer_edge/edge/runTest.sh, tests/nnstreamer_edge/edge/unittest_edge.cc
Skip AITT gtest and ssat until aitt-ses is available.
Signed-off-by: gichan2-jang <gichan2.jang@samsung.com>
=> [edge] Skip AITT test

ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
Return error with explicit error message (GST_ERROR) if
the element size mismatches.
For example, float32 tensor stream cannot be converted
to RGB video stream without tensor_transform.
=> decoder/direct_video: detect element size mismatch

gst/edge/edge_sink.c
Fix svace issue, remove unnecessary code to check connection timeout.
=> [Edge/CodeClean] remove unnecessary connection timeout

gst/nnstreamer/tensor_query/tensor_query_server.c
Code clean, remove unnecessary memory allocation while creating edge handle.
=> [CodeClean] unnecessary mem allocation

CODE_OF_CONDUCT.md, CONTRIBUTING.md, gst/nnstreamer/include/nnstreamer_cppplugin_api_filter.hh, gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/include/nnstreamer_plugin_api_converter.h, gst/nnstreamer/include/nnstreamer_plugin_api_decoder.h, gst/nnstreamer/include/nnstreamer_plugin_api_filter.h, gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h, gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/include/tensor_decoder_custom.h, gst/nnstreamer/include/tensor_filter_custom.h, gst/nnstreamer/include/tensor_typedef.h, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, jni/Android-app.mk, tests/unittest_mlagent/unittest_mlagent.cc
Code clean, fix indent and typo in source files.
=> [CodeClean] fix typo

gst/nnstreamer/tensor_query/tensor_query_server.c, tests/tizen_sensor/dummy_sensor.c
Code clean, check hash-table util function result.
=> [CodeClean] handle hashtable function

.github/workflows/gbs_build.yml, .github/workflows/update_gbs_cache.yml
- Let the daily job `update_gbs_cache.yml` save cache for every build arch.
- Let the PR job `gbs_build.yml` restore proper cache for each arch.
=> [action] Save gbs cache daily and restore gbs cache per PR

.github/workflows/pdebuild.yml, .github/workflows/update_pbuilder_cache.yml
- Let the daily job `update_pbuilder_cache.yml` save cache.
- Let the PR job `pdebuild.yml use proper cache for each arch.
=> [action] Save pbuilder cache daily and use it in each PR

gst/nnstreamer/hw_accel.c
Fix fatal error: asm-arm/hwcap.h: No such file or directory
---
```bash
- …
```
=> build: update header path

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
If input tensor dim/type is invalid, describe the given dim/type.
#4456 @ParimalMuley you may use this code if you are not familiar with GST_DEBUG.
=> decoder/bb/yolov8 Elaborate error message

jni/nnstreamer.mk
- This resolves recent android API build failures.
=> [android] Include recent modified source codes to build android API

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.cc, ext/nnstreamer/tensor_decoder/tensordec-font.c, ext/nnstreamer/tensor_filter/tensor_filter_ncnn.cc
- Trivial change to refer proper code.
=> [doc] Change occurrence of boundingbox.c to .cc

packaging/nnstreamer.spec
Disable features for mv project release.
=> [Spec] features for mv project

packaging/nnstreamer.spec
Update spec file to disable tensorflow-lite ver1.x.
=> [Spec] disable tensorflow-lite ver1.x

ext/nnstreamer/extra/nnstreamer_python3_helper.cc
Fix svace issue, use util function to get nth tensor info.
=> [CodeClean] util to get nth info

ext/nnstreamer/extra/nnstreamer_python3_helper.cc, ext/nnstreamer/tensor_converter/tensor_converter_python3.cc, gst/nnstreamer/tensor_query/tensor_query_client.c
cherry-pick commits from main branch to prevent svace issues.
=> [CodeClean] prevent svace issues

.github/workflows/docker.yml
Build and deploy docker image daily.
Test docker image creation and deploy to nnstreamer:nnstreamer.
https://hub.docker.com/r/nnstreamer/nnstreamer
=> github-action: build and deploy docker.

.github/workflows/android.yml, .github/workflows/cpp-linter.yml, .github/workflows/gbs_build.yml, .github/workflows/macos.yaml, .github/workflows/pdebuild.yml, .github/workflows/ubuntu_clean_llvm_build.yml, .github/workflows/ubuntu_clean_meson_build.yml, .github/workflows/yocto.yml
Github status checks are based on job names.
Add names to configure Github status checks.
=> Rename workflow jobs for github branch rules.

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.cc, ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
Code clean to fix svace issue, typecast of size and index value.
=> [CodeClean] typecast of size

ext/nnstreamer/tensor_decoder/tensordec-pose.c, ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c, gst/datarepo/gstdatareposrc.c, gst/nnstreamer/elements/gsttensor_srciio.c, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h
Fix svace issues,
1. check data type for typecast issue.
2. data type to get the latency in tensor-filter.
=> [CodeClean] typecast issue

ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
Code clean, check limit of max rank and dim value from script.
=> [Filter/Lua] check dimension len

ext/nnstreamer/tensor_decoder/box_properties/ovdetection.cc, gst/nnstreamer/tensor_filter/tensor_filter.c
Code clean, update condition to add detected object.
=> [Decoder] condition for deteted obj

gst/datarepo/gstdatareposrc.c
Code clean, handle invalid int value when reading integer from json.
=> [DataRepo] error case when reading int from json

Documentation/AI-integration-on-Tizen.md, Documentation/hotdoc/sitemap.txt
- This guide briefly described about how to use AI models on Tizen using conf based ML Service API
=> [doc] Add guide on "AI Integration on Tizen"

jni/README.md
This patch updates jni related README.
See also: #4495 
=> [Doc] Update jni README

.github/workflows/update_gbs_cache.yml
Release daily build result to S3.
Result : https://nnstreamer-release.s3.ap-northeast-2.amazonaws.com/index.html
@todo Release android and ubuntu result
=> [Action] Release daily build result

Documentation/AI-integration-on-Tizen.md
- Describe `ai_edge_torch`'s `to_channel_last_io` API.
=> [doc] Add `channel_last` convert in the Tizen AI guide doc

.github/workflows/publish_docs.yml, .github/workflows/update_pbuilder_cache.yml
- Release ubuntu daily build result
- Generate docs using hotdoc and publish result to nnstreamer.github.io
- Generate doxygen book and upload result to S3
=> [Action] Release deb packages and docs

gst/nnstreamer/elements/gsttensor_converter.c, gst/nnstreamer/elements/gsttensor_repo.c, tests/unittest_mlagent/mock_mlagent.cc, tests/unittest_mlagent/mock_mlagent.h, tests/unittest_mlagent/unittest_mlagent.cc
Code clean, fix indent and svace issues.
=> [CodeClean] fix svace issues

gst/nnstreamer/elements/gsttensor_crop.c, gst/nnstreamer/elements/gsttensor_demux.c, gst/nnstreamer/elements/gsttensor_merge.c, gst/nnstreamer/elements/gsttensor_mux.c, gst/nnstreamer/elements/gsttensor_split.c
Prevent invalid stream-id case if element has multiple sink pads.
=> [Element] invalid stream id

gst/nnstreamer/elements/gsttensor_merge.c, gst/nnstreamer/elements/gsttensor_mux.c, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/tensor_common.h
Code clean, remove unnecessary data in mux collect-pad data.
=> [Mux] remove unnecessary var

tools/cuda-version.sh, tools/tensorrt-version.sh
- Exit with proper value in tensorrt-version.sh and cuda-verison.h
=> [build] Fix tensorrt/cuda version check script

ext/nnstreamer/tensor_decoder/tensordec-tensor_region.c, gst/datarepo/gstdatareposrc.c, gst/nnstreamer/elements/gsttensor_merge.c, gst/nnstreamer/elements/gsttensor_reposrc.c, gst/nnstreamer/elements/gsttensor_split.c, gst/nnstreamer/elements/gsttensor_trainer.c, gst/nnstreamer/tensor_filter/tensor_filter.c, tests/gstreamer_mqtt/unittest_mqtt_w_helper.cc
Code clean, update util function to free allocated mem block and fix mem leak case.
=> [CodeClean] possible mem leak case

ext/nnstreamer/tensor_decoder/tensordec-pose.c, gst/nnstreamer/elements/gsttensor_merge.c, gst/nnstreamer/tensor_filter/tensor_filter.c
Code clean, use util function to get nth tensor-info ptr to prevent index error.
=> [Element] util to get nth info

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
Backporting #4536 for prod/tizen-7.0 branch
=> [prod/tizen-7.0] Backporting #4536

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
Remove unnecessary local val and use proper function to delete buffer handle.
=> [SNPE] function to delete instance

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc, ext/nnstreamer/tensor_filter/tensor_filter_snpe_v1.cc
Handle runtime error if snpe version is invalid, and update exception when failed to configure instance.
=> [Filter/SNPE] check snpe version

meson.build
Check snpe version by using snpe-util function.
Also, update build message.
=> [Meson] check snpe ver

tests/nnstreamer_edge/edge/unittest_edge.cc, tests/nnstreamer_edge/query/unittest_query.cc
Add edgesrc/sink and tensor_qeury custom connection tests. Enable the tests later.
=> [TDD] Add edgesrc/sink and query custom connection tests

Documentation/products.md
- MediaTek uses nnstreamer in their products to show some AI demo apps.
=> [doc] Add a new product using nnstreamer

meson.build, meson_options.txt, tests/nnstreamer_example/custom_example_llama2/nnstreamer_customfilter_llama2.c, tests/nnstreamer_example/meson.build
This PR adds custom filter to use llama2c.
https://github.com/karpathy/llama2.c/tree/master?tab=readme-ov-file#custom-tokenizers
I tested with vocab size 4096.
```
$ls
libnnstreamer_customfilter_llama2.so model.bin input.txt tokenizer.bin
$cat input.txt
There was a little
$ gst-launch-1.0 filesrc location=input.txt ! application/octet-stream ! tensor_converter ! other/tensors,format=flexible ! tensor_filter framework=custom model=libnnstreamer_customfilter_llama2.so ! filesink location=output.txt
$cat output.txt 
There was a little 3 year old girl named Lucy. She was very excited because today was her birthday. She was so happy and couldn't wait to open her presents.
Lucy's mom said, "Let's go to the store and get a present for you."
Lucy was so excited and quickly ran to the store. She …
```
=> [custom] Add custom filter to use llama2c

debian/rules, gst/edge/edge_common.c, gst/edge/edge_sink.c, gst/edge/edge_sink.h, gst/edge/edge_src.c, gst/edge/edge_src.h, packaging/nnstreamer.spec, tests/nnstreamer_edge/edge/unittest_edge.cc, tests/nnstreamer_edge/meson.build, tests/nnstreamer_edge/nnstreamer-edge-custom-test.c
- Implement custom connection for edgesrc and edgesink
- Enable the tests
=> [Edge] Implement custom connection for edgesrc and edgesink

gst/edge/edge_sink.c, gst/edge/edge_sink.h
Change the method of waiting for connection from polling to event.
Need group SR: https://github.com/nnstreamer/nnstreamer-edge/pull/225
=> [Edge] Wait connection from edgesrc

gst/edge/edge_sink.c
Code clean, fix svace issue - adding lock to check connection state.
=> [Edge] fix svace issue

gst/nnstreamer/elements/gsttensor_trainer.c
- Remove flexible CAPS from src pad because the output buffer is fixed to the values training_loss, training_accuracy, validation_loss and validation_accuracy
=> [tensor_trainer] Remove flexible CAPS from src pad

.github/workflows/codeql.yml
- Add a workflow to analyze github's CodeQL.
- Need to set a manual build process for C/C++ project.
=> [action] Add a workflow for github CodeQL

.github/workflows/yocto.yml
- Acquire enough disk space for yocto build cache.
=> [action] Acquire disk spaces for yocto workflow

.github/workflows/yocto.yml
- Add an option `nobranch=1` to prevent occasional fetch error.
- Remove unnecessary disk space acquisition step.
=> [action] Fix yocto build workflow

gst/nnstreamer/elements/gsttensor_trainer.c, gst/nnstreamer/elements/gsttensor_trainer.h
The following functionality has been separated into functions from the chain function.
- Check buffer drop conditions
- Check for run chain func
- Get header size
- Create input tensors
- Check input tensors size
- Destroy input tensors and output tensors
- Get model stats
- Create output tensors
=> [tensor_trainer] Refactoring the chain function

gst/nnstreamer/tensor_filter/tensor_filter.c
Extract functions to improve redability and matainability.
Signed-off-by: gichan2-jang <gichan2.jang@samsung.com>
=> [Refactor] Extract functions of tensor_filter transform. 

gst/nnstreamer/elements/gsttensor_crop.c, gst/nnstreamer/elements/gsttensor_merge.c, gst/nnstreamer/elements/gsttensor_mux.c
- Change sink_sid to sink_stream_id and sid to stream_id
=> Change variable names for readability

gst/nnstreamer/tensor_filter/tensor_filter.c
Code clean, use common util functions in filter implementation.
=> [Filter] use common util function

gst/nnstreamer/elements/gsttensor_trainer.c
Code clean, remove unnecessary code and use util function for tensor info.
=> [Trainer] delete unnecessary code

ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_executorch_llama.cc, meson.build, meson_options.txt
- Meta's executorch provides llama inference with simple APIs.
- As utilize it, add a simple filter name `exeuctorch-llama`.
REF: https://github.com/pytorch/executorch/blob/main/examples/models/llama
Tested with [this executorch commit](https://github.com/pytorch/executorch/commit/c242c4cec93320a017df8096bab84000d4072c1e).
pipeline usage:
```
echo "Hello who are you and what brings you here?" > input.txt && \
gst-launch-1.0  filesrc location=input.txt ! application/octet-stream ! \
tensor_converter ! other/tensors,format=flexible ! \
tensor_filter framework=executorch-llama model=llama3_2.pte,llama3.2-1b/tokenizer.model invoke-dynamic=true ! \
other/tensors,format=flexible ! tensor_decoder mode=octet_stream !
application/octet-stream ! filesink location=result.txt --no-position \
&& cat …
```
=> [filter] Add a new filter exeuctorch-llama

ext/nnstreamer/tensor_filter/tensor_filter_llama2.cc
This patch adds invoke_dynamic funciton to tensor filter llama2.
LLM model's output is flexible, so llama2 filter should use invoke_dynamic.
=> [llama2] Use invoke_dynamic in tensor filter llama2

gst/datarepo/gstdatareposink.c
- Added check for file write failure
- The log message outputs whether 64-bit is supported.
- Remove unnecessary event function
- Remove unnecessary comments
- Move repetitive static tensor checks in the rendering function to state changes after creating the function.
- create gst_data_repo_sink_set_is_static_tensors()
-  bug-fix: Memory leak occurs when set_caps is called multiple times
**Complete git Squash**
=> [datareposink] Code clean, refactoring and bug fix

tests/nnstreamer_datarepo/unittest_datareposink.cc, tests/nnstreamer_edge/edge/unittest_edge.cc, tests/nnstreamer_trainer/unittest_trainer.cc
- Remove erroneous "gst-launch-1.0" string in pipeline description.
=> [test] Fix pipeline for `gst_parse_lanch`

ext/nnstreamer/extra/meson.build, ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, meson.build, tests/meson.build, tests/nnstreamer_plugins/unittest_plugins.cc
Code clean, check supported args and set warning flags.
=> [Meson] warning flags

.github/workflows/gen_gbs_result_badge.py, .github/workflows/update_gbs_cache.yml, README.md
- Generate gbs build result badge for each arch.
=> [Action] Generate build result badge

.github/actions/gitpush/action.yml, .github/actions/s3_upload/action.yml, .github/workflows/publish_docs.yml, .github/workflows/update_gbs_cache.yml, .github/workflows/update_pbuilder_cache.yml
- use composite action for git push.
- use composite action for s3 upload.
=> [Action] Add composite action for duplicated works 

Documentation/getting-started-android.md, README.md, jni/Application.mk
This patch updates android API version in README.
ref : https://github.com/nnstreamer/api/blob/main/.github/actions/android-build/action.yml
=> [README] Update Android API version

Documentation/writing-subplugin-tensor-filter.md, ext/nnstreamer/tensor_filter/README.md
- Update the subplugin list.
- Update the "how to write tensor-filter subplugin" document.
=> doc: tensor-filter subplugin manual update

ext/nnstreamer/tensor_filter/meson.build, packaging/nnstreamer.spec
- Add building executorch filter subplugin package in spec file.
=> [Tizen] Prepare executorch build for Tizen

jni/nnstreamer.mk
- Let android api build orc code.
=> [build] Expose nnstreamer-orc.orc to android build

jni/nnstreamer.mk
This PR exposes the source code to build api/android.
Related with : https://github.com/nnstreamer/nnstreamer-android-resource/pull/45
=> [android] Build llama.cpp tensor_filter

ext/nnstreamer/tensor_decoder/box_properties/mobilenetssd.cc, ext/nnstreamer/tensor_decoder/box_properties/mppalmdetection.cc, ext/nnstreamer/tensor_decoder/box_properties/ovdetection.cc, ext/nnstreamer/tensor_decoder/box_properties/yolo.cc, ext/nnstreamer/tensor_decoder/tensordec-boundingbox.cc, ext/nnstreamer/tensor_decoder/tensordec-boundingbox.h
- yolov8-obb decoder for oriented object detection
- - support drawing oriented bounding boxes with angle
- add a mode option to nms() function
REF: https://docs.ultralytics.com/tasks/obb/
pipeline usage: 
```
filesrc location=boat.mp4 ! decodebin name=d \
d.video_0 ! queue ! videoconvert ! videoscale ! videorate \
video/x-raw,width=640,height=480,format=RGB,framerate=30/1 ! tee name=t \
t. ! queue leaky=2 max-size-buffers=2 ! videoscale ! videoconvert ! \
video/x-raw,width=512,height=512,format=RGB ! tensor_converter ! \
tensor_transform mode=arithmetic option=typecast:float32,div:255.0 ! \
queue ! tensor_filter framework=tensorflow-lite model=yolov8n-obb_float16.tflite custom=Delegate:XNNPACK,NumThreads:4 ! \
other/tensors,num_tensors=1,types=float32,format=static,dimens …
```
=> [decoder] Add a new decoder yolov8-obb

debian/nnstreamer-core.install, debian/nnstreamer-flatbuf.install, debian/nnstreamer-grpc.install, ext/nnstreamer/extra/meson.build, ext/nnstreamer/meson.build, ext/nnstreamer/registerer/grpc.c, ext/nnstreamer/registerer/tizensensor.c, ext/nnstreamer/tensor_converter/meson.build, ext/nnstreamer/tensor_decoder/meson.build, ext/nnstreamer/tensor_sink/meson.build, ext/nnstreamer/tensor_source/meson.build, packaging/nnstreamer.spec
Build and install common util library for sub-plugins.
=> [Subplugin] util lib for sub-plugins

jni/nnstreamer.mk
Add helper code to enable ml-agent on android build.
=> [Build/Android] code for agent

gst/edge/edge_common.h, jni/nnstreamer.mk
Add edge elements for android build and fix gst-plugin name.
=> [Build/Edge] define edge for android

ext/nnstreamer/tensor_decoder/tensordec-font.c, gst/nnstreamer/elements/gsttensor_decoder.c
- Fixing some typos found in the comments. I didn't submit an issue as I figured it to be quite trivial.
=> Fix typos in some comments

.github/workflows/yocto.yml
Run yocto daily build when there is a change in 24 hours.
=> [Action] Fix yocto daily build script.

.github/CODEOWNERS
Add `Geon Kim(g67.kim@samsung.com)` to codeowners.
- [*] Only Modify ".github/CODEOWNERS"
=> [doc] Add `Geon Kim(g67.kim@samsung.com)` to codeowners

ext/nnstreamer/tensor_decoder/tensordec-pose.c
Trivial, fix function name - destructor of decoder subplugin pose.
=> [Decoder] destructor of decode subplugin

gst/nnstreamer/nnstreamer_plugin_api_impl.c
Adding structure with mime-type tensor does not indicate framerate template.
Make caps with framerate feature for backward compatibility.
=> [Common] caps with framerate template

gst/nnstreamer/ml_agent.c, gst/nnstreamer/tensor_query/tensor_query_client.c, tests/nnstreamer_edge/nnstreamer-edge-custom-test.c
- Fix resource leak
- Fix dereferencing null pointer.
=> Resolve svace issue

ext/nnstreamer/tensor_sink/tensor_sink_grpc.c, ext/nnstreamer/tensor_source/tensor_src_grpc.c, gst/datarepo/gstdatareposink.c, gst/datarepo/gstdatareposrc.c, gst/edge/edge_src.c, gst/nnstreamer/elements/gsttensor_aggregator.c, gst/nnstreamer/elements/gsttensor_crop.c, gst/nnstreamer/elements/gsttensor_decoder.c, gst/nnstreamer/elements/gsttensor_demux.c, gst/nnstreamer/elements/gsttensor_if.c, gst/nnstreamer/elements/gsttensor_reposrc.c, gst/nnstreamer/elements/gsttensor_sparsedec.c, gst/nnstreamer/elements/gsttensor_sparseenc.c, gst/nnstreamer/elements/gsttensor_split.c, gst/nnstreamer/elements/gsttensor_split.h, gst/nnstreamer/elements/gsttensor_trainer.c, gst/nnstreamer/elements/gsttensor_transform.c, gst/nnstreamer/include/nnstreamer_plugin_api.h, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_query/tensor_query_client.c, tests/common/unittest_common.cc, tests/nnstreamer_sink/unittest_sink.cc
Code clean, use common util functions to handle tensor in nnstreamer elements.
=> [Common] util to handle tensor

ext/nnstreamer/tensor_filter/tensor_filter_llamacpp.cc
Update deprecated api of llama.cpp and cleanup source code.
=> [Filter/llama.cpp] deprecated api

gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, tests/common/unittest_common.cc
Code clean, update util functions and add more testcases.
=> [Common] test for common utils

gst/nnstreamer/include/nnstreamer_plugin_api_util.h, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h, tests/common/unittest_common.cc
Update util functions to check tensor info and caps config for debug.
=> [Common] util to print tensor info

ext/nnstreamer/tensor_filter/tensor_filter_qnn.cc
- Set proper `context_config` value for the QNN API
=> [filter] Fix qnn API calls

gst/edge/edge_sink.c, gst/edge/edge_src.c, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, tests/common/unittest_common.cc
Code clean, cleanup source code and fix mem leak case.
=> [CodeClean] cleanup source code

.github/workflows/nns_testhub.yml, .github/workflows/parse_ssat.py
- Upload coverage results to TestHub
- Runs an action on only for OASIS org.
=> [Action] Add nnstreamer testhub action.

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Code clean, remove deprecated api and cleanup source code.
=> [Filter/ONE] deprecated function

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Support new data types of ONE - int8/int16 and handle other uint8 type.
=> [Filter/ONE] support data types

jni/nnstreamer.mk
Generate header file of nnstreamer version info under the local path, to build android library on android-studio.
=> [Android] header for nns version

gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h, gst/nnstreamer/tensor_filter/tensor_filter_single.c
Code clean, update macro and functions to check filter-fw is opened.
=> [Filter] revise fw callback

Documentation/writing-subplugin-tensor-filter.md
Minor updates to the  `writing-subplugin-tensor-filter.md` 
- add links to the interface and reference files
- fix a note in the C subplugin section
=> [docs] update `writing-subplugin-tensor-filter.md`

gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
GstTensorFilterProperties is an important data structure.
Each property requires explanation for future developers.
=> [filter] update doxygen entry for async-invoke

ext/nnstreamer/tensor_filter/tensor_filter_llamacpp.cc
When generating each output token, create an output tensor and dispatch it to nnstreamer_filter.
See also : https://github.com/ggerganov/llama.cpp/blob/master/examples/simple/simple.cpp
Model from : https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF
```sh
echo "Hello my name is" > input.txt && \
gst-launch-1.0 filesrc location=input.txt ! application/octet-stream ! \
tensor_converter ! other/tensors,format=flexible ! \
tensor_filter framework=llamacpp model=llama-2-7b-chat.Q2_K.gguf invoke-dynamic=TRUE ! \
other/tensors,format=flexible ! tensor_decoder mode=octet_stream ! \
application/octet-stream ! filesink location=output.txt && \
cat output.txt
```
Result
```
<s> Hello my name is Jake and I am a 23 year old male from the United States. Unterscheidung between the two is important …
```
=> [llamacpp] Dispatch output tensor for each token generation

gst/nnstreamer/elements/gsttensor_transform.c, tests/transform_typecast/runTest.sh
gst-caps-transform callback is called with more abstract format in earlier stage of negotiation.
It should return all possible caps for such phase.
To complete the PR, test cases are added.
Addresses #4740
=> transform: flexible-to-flexible transform bugfix

gst/nnstreamer/elements/gsttensor_transform.c, gst/nnstreamer/nnstreamer_plugin_api_impl.c, gst/nnstreamer/nnstreamer_plugin_api_util_impl.c, tests/transform_transpose/runTest.sh, tests/transform_typecast/runTest.sh
Check empty info string when getting tensor caps and remove unnecessary code.
=> [Common] caps with empty tensor info

gst/nnstreamer/elements/gsttensor_transform.c, tests/nnstreamer_plugins/unittest_plugins.cc, tests/transform_typecast/runTest.sh
Support static to flexible tensor stream.
=> [Transform] static to flexible stream

tests/meson.build, tests/nnstreamer_filter_llamacpp/unittest_filter_llamacpp.cc
- Add a simple testcase for tensor_filter with llamacpp sub-plugin
=> [Test] Add test for llamacpp

gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
Update tensor info if its format is not static.
=> [Common] copy flexible tensor info

gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h, gst/nnstreamer/tensor_filter/tensor_filter_single.c
Add util function to validate filter properties before starting the pipeline.
=> [Filter] validate properties

.github/CODEOWNERS
- Add @hj210 (https://github.com/hj210)
=> Add Hyungjun Choi(@hj210) to codeowner

ext/nnstreamer/tensor_filter/tensor_filter_llamacpp.cc, tests/nnstreamer_filter_llamacpp/unittest_filter_llamacpp.cc
- Previously, only greedy samples were used
- Bug fix: Call llama_sampler_chain_init after calling llama_init_from_model
- Add TCs
**TC outputs**
```
[singleInputCombinedSampling_p]
num_predict:30,top_k:50,top_p:0.9,temperature:0.7
Hello my name is Jake and I'm a 25 year old from the United States. Unterscheidung zwischen “Your” und “You're” im Eng
[singleInputAllSamplingOptions_p]
num_predict:30,top_k:40,top_p:0.9,typical_p:0.9,temperature:0.7
Hello my name is Jake and I'm a 25 year old from the United States. Unterscheidung zwischen “Your” und “You're” im Eng
[singleInputTypicalPTempSampling_p]
num_predict:30,typical_p:0.9,temperature:0.7
Hello my name is Jake and I'm a 25 year …
```
=> [llama.cpp] Apply top_p, top_k, typical_p, and temperature samplers
