nnstreamer/nnstreamer

gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
gst/nnstreamer/tensor_merge/gsttensormerge.c
gst/nnstreamer/tensor_split/gsttensorsplit.c

Modify pad caps template - other/tensors with num 1.
Set src-pad caps using peer caps.

[Split/Merge/Aggregator] caps template for single tensor

---

gst/nnstreamer/meson.build
gst/nnstreamer/tensor_query/meson.build
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h
meson.build

This is the first step for the tensor query.
Add common socket functions for tensor-query.
Other common functions are added later.
tensor_query_src, tensor_query_sink and tensor_query_filter will use these functions.

[Query] Add common socket functions

---

packaging/nnstreamer.spec

Because of the security issue, VD does not use the script language.
Moreover, VD officially uses Python 3.5 for debugging purposes but the
latest Tizen 6.5 uses Python 3.9. Because of this reason, 'Recommends:
flatbuffers-python' section should be removed for VD build infra.
```bash
$ rpm -q --recommends nnstreamer-flatbuf-1.7.2-0.armv7l.rpm
flatbuffers-python
```
```
$ rpm -q --recommends nnstreamer-flatbuf-1.7.2-0.armv7l.rpm
```

[Spec] Remove flatbuffers-python recommends section

---

packaging/nnstreamer.spec
tests/nnstreamer_grpc/runTest.sh

This PR is related to #3391.
Since some system calls required by GRPC are not supported on qemu/arm as well, this patch blocks SSAT-based GRPC test cases' running on such environments.
See also: https://github.com/nnstreamer/nnstreamer/pull/3054
How to reproduce: Use ```gst-launch-1.0``` instead of ```gstTest```
For example, 
https://github.com/nnstreamer/nnstreamer/blob/f77cf18467e6e321bbe8776d2c8ebb4999771623/tests/nnstreamer_grpc/runTest.sh#L96-L98
to 
```bash
96  GST_PLUGIN_PATH=${PATH_TO_PLUGIN} gst-launch-1.0 tensor_src_grpc port=${PORT} num-buffers=${NUM_BUFFERS} idl=${IDL} blocking=${BLOCKING} ! 'other/tensor,dimension=(string)3:640:480,type=(string)uint8,framerate=(fraction)5/1' ! multifilesink location=result_%1d.log
97  sleep 1 
98  GST_PLUGIN_PATH=${PATH_TO_PLUGIN} …
```

[Tests/GRPC] Skip GRPC tests on the qemu/arm environment either  @open sesame 07/17 18:00

---

ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc

Fix converity issue
- Fix resource leak (delete core when init failed)
- Initialize networkid.
- Fix use after free (stop the test when there isn't test model)

[armnn] Fix coverity issue

---

ext/nnstreamer/tensor_filter/tensor_filter_tvm.cc
tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc

Uninitialized read on `PackedFunc` assignment
Fix dynamic overflow
---

[Coverity] Fix coverity issues (689481, 689480)

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

Mobilenet-ssd-postprocess has its own syntax for option3.
Describe it for users.
This should be merged AFTER #3408

Decoder: Bounding boxes: option3 comments update / After #3408

---

gst/mqtt/mqttsink.c
gst/mqtt/mqttsrc.c
tests/gstreamer_mqtt/GstMqttTestHelper.hh
tests/gstreamer_mqtt/unittest_mqtt_w_helper.cc

This PR fixes the following critical and major Coverity defects in GstMQTTSink, GstMQTTSrc, and the unit test cases.
- WGID 1238814, which is a critical defect, in mqttsink.c
- Three major defects (WGID 1238821, 1238825, and 1238826) in mqttsrc.c
- Five critical defects (WGID 1238819, 1238820, 1238824, 1238830, and 1238831) in unittest_mqtt_w_helper.cc
- WGID 1238828, which is a critical defect, in GstMqttTestHelper.hh

[Coverity] Fix critical and major defects in GstMQTT elements

---

debian/control
debian/control.ubuntu.ppa
debian/nnstreamer-nnfw.install

Add new pkg for NNFW (ONE) in debian build.
Related issue: https://github.com/Samsung/ONE/issues/7196

[Build/Deb] dependency to NNFW @open sesame 06/21 13:48

---

gst/nnstreamer/include/tensor_typedef.h
gst/nnstreamer/tensor_sparse/tensor_sparse_util.h

- Define a tensor_format for SparseTensor
- Define a info structure for SparseTensor which has "length" of non-zero elements
- Add a internal header `tensor_sparse_util.h` for util functions that will be used in related elements
- Add a union in GstTensorMetaInfo for SparseTensor
SparseTensor
SparseTensors could be more efficient on processing of tensors that contain a lot of zero values.
I'll adopt the coordinate list (COO) format for encoding it, same as other NN frameworks.
The COO encoding for sparse tensors is comprised of:  (REF: https://www.tensorflow.org/guide/sparse_tensor)
1. values: A 1D tensor with shape [N] …

[SparseTensor] Define SparseTensor and API @open sesame 07/06 09:45

---

gst/nnstreamer/include/tensor_typedef.h
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_converter/tensor_converter.c
gst/nnstreamer/tensor_crop/tensor_crop.c
gst/nnstreamer/tensor_demux/gsttensordemux.c
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_mux/gsttensormux.c
gst/nnstreamer/tensor_sink/tensor_sink.c
gst/nnstreamer/tensor_transform/tensor_transform.c
tests/nnstreamer_plugins/unittest_plugins.cc
tests/nnstreamer_sink/unittest_sink.cc

Add tensor format in caps.
Fix pad template with flex tensor and remove old mimetype.
Now caps string for flex-tensor has framerate field.

[Caps/Format] add tensor format in caps

---

gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h

Re-define tensor query common data structures.
- GSocket or MQTT_handled are managed from tensor_query_common.
- Each element manages a unique id which is generated using IP and port.

[Query] Define tensor query common data structures.

---

ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
gst/nnstreamer/include/nnstreamer_plugin_api.h
gst/nnstreamer/include/tensor_typedef.h
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_transform/tensor_transform.c
tests/common/unittest_common.cc
tests/nnstreamer_converter/unittest_converter.cc
tests/nnstreamer_plugins/unittest_plugins.cc
tests/nnstreamer_source/unittest_src_iio.cc

Remove tensor-config struct (for single tensor) and replace it to tensors-config.

[Common] remove tensor-config struct

---

gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
gst/nnstreamer/tensor_common.h
gst/nnstreamer/tensor_converter/tensor_converter.c
gst/nnstreamer/tensor_decoder/tensordec.c
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_if/gsttensorif.c
gst/nnstreamer/tensor_merge/gsttensormerge.c
gst/nnstreamer/tensor_mux/gsttensormux.c
gst/nnstreamer/tensor_rate/gsttensorrate.c
gst/nnstreamer/tensor_sink/tensor_sink.c
gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_transform/tensor_transform.c

1. Provide common macro of silent_debug and silent_debug_caps,
which had been repeatedly defined in each plugin.
2. Refactor the two macros to get "object" as an argument
so that it wouldn't use implicit argument exceot for "DBG".
The same macros are not touched in /ext directory
because they are not supposed to include "tensor_common.h",
which is an internal header.
@todo There are a few subplugins in /ext (not tensor-filter)
that uses "tensor_common.h". They should be refactored not to
use internal headers so that we can separate them to
independent repo anytime. Although we don't have such plans,
we need to keep them as appropriate examples for users.

Common: refactor silent_debug() and make it common

---

ext/nnstreamer/tensor_converter/tensor_converter_python3.cc

set memory size from mapped info, not buffer size.

[Converter/Py] mem size

---

debian/rules

enable nnfw subplugin test in ubuntu build.

[Test/Ubuntu] add nnfw test

---

ext/nnstreamer/extra/nnstreamer_python3_helper.cc
ext/nnstreamer/tensor_converter/tensor_converter_python3.cc
ext/nnstreamer/tensor_decoder/tensordec-python3.cc
ext/nnstreamer/tensor_filter/tensor_filter_python3.cc

In the sub-plugins for python, prevent resizing the array length when creating new array object.

[Subplugin/Py] prevent resizing the array length

---

ext/nnstreamer/tensor_filter/meson.build
meson_options.txt

In Yocto build, it appears that flatbuf dep check
is not available:
https://github.com/nnstreamer/meta-neural-network/blob/master/recipes-nnstreamer/nnstreamer/files/0001-Disable-flatbuf-check-for-tf-lite-for-yocto-build.patch
@anyj0527 : Let's remove all *.patch files from
meta-neural-network by updating related nnstreamer/*.git
*.patch files in meta-neural-network are obvious
hazards.

TFLite: Allow to skip flatbuf dep check

---

gst/nnstreamer/include/nnstreamer_plugin_api.h
gst/nnstreamer/include/tensor_typedef.h
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_common_pipeline.c
gst/nnstreamer/tensor_crop/tensor_crop.c
gst/nnstreamer/tensor_demux/gsttensordemux.c
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter_common.c
gst/nnstreamer/tensor_mux/gsttensormux.c
gst/nnstreamer/tensor_transform/tensor_transform.c
tests/common/unittest_common.cc
tests/nnstreamer_plugins/unittest_plugins.cc
tests/nnstreamer_sink/unittest_sink.cc

Set tensor format from caps struct.
tensor stream has single format, so format in tensor-info struct is unnecessary.

[Config/Format] tensor format in config

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c

The patch update the name 'srnpu' to 'trixengine'.

[Filter] Rename srnpu to trixengine

---

gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h

Common API functions used for both client and server elements
Currently based on TCP connections
TODO
- Enable timeout
---

[Query] Implement common utils for TCP

---

gst/nnstreamer/tensor_repo/tensor_repo.c
gst/nnstreamer/tensor_repo/tensor_repo.h
gst/nnstreamer/tensor_repo/tensor_reposrc.c

Gstreamer-meta in tensor repo only handles pad caps. Move caps into repo-data and remove repo-meta info.

[Repo] remove meta

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_client.h

Update tensor query client.
Example Buffer stream
- During negotiation: Send `_TENSOR_QUERY_CMD_REQUEST_INFO` cmd and receive `_TENSOR_QUERY_CMD_RESPOND_APPROVE` cmd
- During playing: Commands when sending one buffer | `START CMD` - `DATA CMD` - `END CMD` |
Todo
- Add unit test cases
- Get server port and IP from the category? not specify an option. (Mqtt-hybrid?)

[Query] Update tensor query client

---

gst/nnstreamer/meson.build
gst/nnstreamer/tensor_meta.c
gst/nnstreamer/tensor_meta.h
gst/nnstreamer/tensor_query/meson.build
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_server.c
gst/nnstreamer/tensor_query/tensor_query_server.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversink.h
gst/nnstreamer/tensor_query/tensor_query_serversrc.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.h
jni/nnstreamer.mk

Update query serversrc, serversink & meta-query
Src accepts connection from clients receiving messages such as
- Request Info : send back to client w/ src tensor config
- Start : indicates beginning of data transfer
- Data : contains tensor data
- End : ends transfer
Sink can identify client by meta-query, which contains host address
Sink sends transformed tensor by same policy
Example pipeline
```
gst-launch-1.0 tensor_query_serversrc host=127.0.0.1 ! other/tensors,num_tensors=1,dimensions=3:300:300:1,types=uint8,framerate=30/1 ! tensor_query_serversink host=127.0.0.1
gst-launch-1.0 v4l2src ! videoconvert ! videoscale !  video/x-raw,width=300,height=300,format=RGB,framerate=30/1 ! tensor_converter ! tensor_query_client src-host=127.0.0.1 sink-host=127.0.0.1 ! tensor_decoder …
```

[Query] Update server elements

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c
meson.build
meson_options.txt
nnstreamer.ini.in

This patch newly adds the `filter-aliases` section for searching the sub-plugin. If the alias name is provided from ini file, then it could be used as sub-plugin.
* Searching sequence: exact match -> priority option ->  `filter-aliases` section
* Add `filter-aliases` section in ini file
* Add default `trix-engine` value for backward compatibility of SRNPU.
```
[filter-aliases]
trix-engine = srnpu
```

[Filter/Sub] Add alias option for backward compatibility.

---

gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversink.h
gst/nnstreamer/tensor_query/tensor_query_serversrc.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.h

Add address resolver for server.
Todo:
common properties are adjusted by .ini and envvar.
Test pieline
Server:
```
gst-launch-1.0 tensor_query_serversrc ! other/tensors,num_tensors=1,dimensions=3:300:300:1,types=uint8,framerate=30/1 ! tensor_query_serversink
```
Client:
```
gst-launch-1.0 v4l2src ! videoconvert ! videoscale !  video/x-raw,width=300,height=300,format=RGB,framerate=30/1 ! tensor_converter ! tensor_query_client ! tensor_decoder mode=direct_video ! videoconvert ! ximagesink
```

[Query] Add address resolver for server

---

gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_server.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.c

- Assign NULL value after call `query_server_data_free` to  prevent double free
- Remove some trailing spaces

[tensor_query] Fix double free in tensor_query_server @open sesame 08/19 10:24

---

LICENSE

Add SPDX license identifier reference in LICENSE file.
See: https://github.com/nnstreamer/TAOS-CI/pull/733#discussion_r685098782

[LICENSE] Add SPDX reference in LICENSE file.

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.c

Support flexible tensors format for tensor query.
Test pipeline
server:
gst-launch-1.0 tensor_query_serversrc host=127.0.0.1 ! other/tensors,format=flexible ! tensor_query_serversink host=127.0.0.1
client:
gst-launch-1.0 v4l2src ! videoconvert ! videoscale !  video/x-raw,width=320,height=240,format=RGB,framerate=30/1 ! tensor_converter ! other/tensors,format=flexible ! tensor_query_client src-host=127.0.0.1 sink-host=127.0.0.1 ! tensor_converter input-dim=3:320:240 input-type=uint8 ! tensor_decoder mode=direct_video ! videoconvert ! ximagesink

[Query] Support flexible tensors format

---

ext/nnstreamer/tensor_filter/vivante/tensor_filter_subplugin.c
tests/bmp2png.c

This fixes some -Werrors after warning level of meson build was increased to 2 with gcc 10.2.0
Fixes: eb6f4e1c0b7b (Increase warning level and resolve compiler warnings)
1. Build test: [ *]Passed [ ]Failed []Skipped

Fix -Werror after warnings level increase

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
gst/nnstreamer/tensor_filter/tensor_filter_common.c
gst/nnstreamer/tensor_filter/tensor_filter_common.h

to manage the shared model representation, a new hash table is required.
TFLite shared model representation reduced memory as below.
```
[share]
MAX RSS: 212172
MAX PSS: 202508
[not share]
MAX RSS: 353576
MAX PSS: 278325
```
+ reload is not supported yet.

[Filter] add a hash table for shared key

---

gst/nnstreamer/include/nnstreamer_plugin_api.h
gst/nnstreamer/include/tensor_typedef.h
gst/nnstreamer/meson.build
gst/nnstreamer/registerer/nnstreamer.c
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_sink/tensor_sink.c
gst/nnstreamer/tensor_sparse/meson.build
gst/nnstreamer/tensor_sparse/tensor_sparse_dec.c
gst/nnstreamer/tensor_sparse/tensor_sparse_dec.h
gst/nnstreamer/tensor_sparse/tensor_sparse_enc.c
gst/nnstreamer/tensor_sparse/tensor_sparse_enc.h
gst/nnstreamer/tensor_sparse/tensor_sparse_util.c
gst/nnstreamer/tensor_sparse/tensor_sparse_util.h
jni/nnstreamer.mk
tests/nnstreamer_sparse/runTest.sh

- tensor_sparse_enc: encoding static tensors into sparse tensors
- tensor_sparse_dec: decoding sparse tensors into stsatic tensors
- Add SSAT test for sparse tensors

[tensor_sparse] Add elements tensor_sparse_enc and tensor_sparse_dec

---

tests/meson.build
tests/nnstreamer_filter_single/unittest_filter_single.cc

Add new testcases for tensor-filter single.
filter-single class is used only for ML single API. For coverage report, we need to run and test this class.

[Test/Filter] testcase for filter-single

---

gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
gst/nnstreamer/tensor_aggregator/tensor_aggregator.h
gst/nnstreamer/tensor_common.h
gst/nnstreamer/tensor_common_pipeline.c
gst/nnstreamer/tensor_converter/tensor_converter.c
gst/nnstreamer/tensor_converter/tensor_converter.h
tests/nnstreamer_plugins/unittest_plugins.cc

Use hashtable to aggregate buffers from multiple clients.
- create gst-adapter for each client id
- for normal case, set default adaptor (no meta in gst-buffer)

[Common/Adapter] aggregation from multi clients

---

gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
gst/nnstreamer/tensor_common.h
gst/nnstreamer/tensor_common_pipeline.c
gst/nnstreamer/tensor_converter/tensor_converter.c
gst/nnstreamer/tensor_meta.c
gst/nnstreamer/tensor_meta.h
gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_client.h
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversink.h
gst/nnstreamer/tensor_query/tensor_query_serversrc.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.h
tests/nnstreamer_plugins/unittest_plugins.cc
tests/nnstreamer_query/unittest_query.cc

currently, ip address of the client is only used to distinguish client which will receive buffers.
In this case, server cannot distinguish if more than one client with the samp ip is connected.
So instead of ip address, changed it to use the client's unique id.
Test pipeline
server:
```
gst-launch-1.0 tensor_query_serversrc ! other/tensors,num_tensors=1,dimensions=3:300:300:1,types=uint8,framerate=30/1 ! tensor_query_serversink
```
client 1:
```
gst-launch-1.0 v4l2src ! videoconvert ! videoscale !  video/x-raw,width=300,height=300,format=RGB,framerate=30/1 ! tensor_converter ! tensor_query_client ! tensor_decoder mode=direct_video ! videoconvert ! ximagesink
```
client2:
```
gst-launch-1.0 videotestsrc ! videoconvert ! videoscale ! …
```

[Query] Identify client using id @open sesame 9/2 14:47

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_serversrc.c

Problem:  Query server shouldn't follow framerates of clients.
Temporary solution: If data is not available in the socket, check the next socket.
Todo: Create threads for each client. (NNS 2.0 later)
Test pipeline:
server
```
gst-launch-1.0 tensor_query_serversrc  ! other/tensors,num_tensors=1,dimensions=3:320:240:1,types=uint8 ! tensor_query_serversink
```
client 1, framerate: 30/1
```
gst-launch-1.0 v4l2src ! videoconvert ! videoscale ! video/x-raw,width=320,height=240,format=RGB,framerate=30/1 ! tensor_converter !  tensor_query_client ! tensor_decoder mode=direct_video ! videoconvert ! ximagesink
```
client 2, framerate: 1/1
```
gst-launch-1.0 videotestsrc ! videoconvert ! videoscale ! video/x-raw,width=320,height=240,format=RGB,framerate=1/1 ! tensor_converter !  tensor_query_client ! …
```

[query] Handle different framerate of clients

---

ext/nnstreamer/tensor_filter/meson.build
meson.build
packaging/nnstreamer.spec

- If the build platform supports snpe lib, use it to build snpe subplugin
- Add snpe related packages in spec

[build/snpe] Build snpe subplugin when the platform supports the lib

---

tests/unittest_util.h

Releated issue: https://github.com/nnstreamer/nnstreamer/issues/3275
cppFilterObj.base03 test fail intermittenly on armv7l during state change to GST_STATE_PLAYING.
(http://nnstreamer.mooo.com/nnstreamer/ci/daily-build/build_result/latest/log/build_log_tizen_armv7l_output_2021-09-16.txt)
When measuring the state change time, it took around 600~800 ms on armv7l.
The current timeout is 1,000 ms, which is close to the boundary.
The test failure did not occur when repeated 1,000 times with 2,000 ms timeout.

[TEST] Adjust state change timeout.

---

gst/nnstreamer/tensor_common.c

Wrong format variable is used at L908.
If format is not given, gst_tensor_get_format (L898) returns `_NNS_TENSOR_FORMAT_END`
If tensors format is not given, default format (_NNS_TENSOR_FORMAT_STATIC) should be used.

[Common] Fix config from structure function @open sesame 9/16 9:13

---

ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc

warning correction -- breaks build with -Werror :
parse_accl_args struct has 4 members - some compilers and/or options require explicit definition of the 4 members.
Added explicit definition of NULL arguments for missing initalizers .
Same approach is used in existing code base for pytorch tensor filter.
Tests: 
ssat suite: passed
armnn GTest suite: passed
correction for compilation error:
tensor_filter_armnn.cc: In function 'int armnn_open(const GstTensorFilterProperties*, void**)':
nnstreamer_plugin_api_filter.h:568:76: error: missing initializer for member 'parse_accl_args::auto_accl' [-Werror=missing-field-initializers]
#define parse_accl_hw(...) parse_accl_hw_fill((parse_accl_args){__VA_ARGS__})
^
tensor_filter_armnn.cc:672:8: note: in expansion of macro 'parse_accl_hw'
hw = …

[armnn] compilation error - missing initializer

---

ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc

warning correction -- breaks build with -Werror :
Some function parameters are unused in body definition.  Those are explicitly marked with UNUSED() macro, same approach as in other elements.
Tests:
ssat suite: passed
armnn GTest suite: passed
correction for multiple occurences of compilation error:
error: unused parameter '[parameter name]' [-Werror=unused-parameter]
Signed-off-by: Julien Vuillaumier <julien.vuillaumier@nxp.com>

[armnn] compilation error - unused parameter

---

ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc

As mentioned in another PR, openvino subplugin calls accel function with invalid args.

[Filter/openvino] fix invalid args

---

meson.build

- Change `error` with `message` to skip snpe build when it's unavailable

[build/fix] Fix meson.build to skip snpe build when it's unavailable

---

gst/mqtt/meson.build
gst/mqtt/mqttcommon.h
gst/mqtt/mqttsink.c
gst/mqtt/mqttsink.h
gst/mqtt/ntputil.c
gst/mqtt/ntputil.h

This PR introduces utility functions to get timestamps from the given NTP server and the self-synchronization mechanism of the Unix epoch timestamps using them. 
To resolve the following issue, this PR also includes a patch to apply caching mechanism according to the polling interval given from the NTP server.
> Note that if the 'ntp-sync' property is set to true (which means that if this feature is enabled), the pipeline would be stuck after a while. This is because most of the public NTP servers restrict clients not to poll too frequently. To fix it, polling intervals and caching mechanisms should be applied to the NPT utility functions.
2. Run test: [*]Passed [ ]Failed …

[Gst/MQTT] Introduce the Unix epoch synchronization using NTP @open sesame 09/29 10:29

---

tests/gstreamer_mqtt/unittest_mqtt.cc

- Remove a testcase which assumes no broker.
- Fix and add negative testcases for mqttsink's invalid prop
- They passes both on w/ broker and w/o env.

[test/mqtt] Test mqtt w/ or w/o broker

---

packaging/run_unittests_binaries.sh

This patch adds an option to skip specific test cases to run_unittests_binaries.sh.
```bash
$ ./packaging/run_unittests_binaries.sh -h
run_unittests_binaries.sh: usage: run_unittests_binaries.sh [options] target
-k | --skip  BINARY_NAME[,*]
Skip the test cases whose names are...(valid only if target is a directory)
```

[UNITTEST] Add a skip option to the script running test cases

---

tests/common/unittest_common.cc

Correction for build issue showing up with GCC 11
unittest_common.cc:953:51:
error: 'structure' may be used uninitialized [-Werror=maybe-uninitialized]
Signed-off-by: Julien Vuillaumier <julien.vuillaumier@nxp.com>
SSAT unit tests: passed

[Test] Fix build issue with GCC 11 [-Werror=maybe-uninitialized]

---

tests/meson.build
tests/nnstreamer_filter_extensions_common/meson.build
tests/nnstreamer_filter_tensorflow2_lite/unittest_filter_tensorflow2_lite.cc

- Add gtest based unittests for tensorflow2-lite sub-plugin
They test the result of mobilenet models when the orange image is given
- Add a float type tflite model "mobilenet_v2_1.0_224.tflite"
- Add filter extension test for tf2lite sub-plugin 

[test/tf2lite] Add tests for tf2lite2 sub-plugin

---

ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.cc
ext/nnstreamer/extra/nnstreamer_grpc_protobuf.cc
ext/nnstreamer/extra/nnstreamer_protobuf.cc
ext/nnstreamer/tensor_converter/tensor_converter_python3.cc
gst/nnstreamer/include/nnstreamer_util.h
meson.build
tests/gstreamer_join/unittest_join.cc
tests/nnstreamer_converter/unittest_converter.cc

Function g_memdup() is deprecated starting from glib 2.68, replaced by g_memdup2() :
_" Use g_memdup2() instead, as it accepts a #gsize argument for byte_size, avoiding the possibility of overflow in a #gsize → #guint conversion."_
https://docs.gtk.org/glib/func.memdup.html
To keep compatibility with the 2 g_memdupX() variants,  option used is to detect glib version from meson script.
Alternative option may be to use in the source code construct like:
`
#ifdef GLIB_CHECK_VERSION(2, 68, 0)
data = g_memdup2(...);
#else
data = g_memdup(...);
#endif
`
Self Evaluation:
SSAT tests: passed
Update to fix build with glib version 2.68 and later
Legacy function:
gpointer g_memdup ( gconstpointer mem, guint byte_size )
is deprecated since version 2.68 and replaced by:
gpointer g_memdup2 ( …

[Build] Add g_memdup2() support for glib >= 2.68

---

meson.build
tests/check_broker.sh
tests/gstreamer_mqtt/unittest_mqtt.cc

If the broker is not available, the mqtt element cannot be changed to the playing state.
However, harnesses are used in the mqtt test, and errors occur if harnesses cannot be changed to the playing state.
So, if there's no broker on the test environment, the test fails.
For example, the build on the lunch pad failed.
https://launchpadlibrarian.net/566158157/buildlog_ubuntu-bionic-amd64.nnstreamer_2.1.0.0-0~202110290743~ubuntu18.04.1_BUILDING.txt.gz

[TEST] Disable MQTT Test when broker is not available.

---

gst/nnstreamer/tensor_common.h
gst/nnstreamer/tensor_common_pipeline.c
tests/common/unittest_common.cc

With gstreamer plugins, nnstreamer element may receive gst-buffer with invalid memory chunks.
nnstreamer internally checks the number of tensors using the mem blocks in gst-buffer.
To handle multi tensors, add util function to separate memories in gst-buffer.

[Common] util function to handle tensors

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
meson_options.txt

Changeset implements support for tensorflow lite filter external delegate:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/external
External delegate is defined via tensor filter custom properties by:
- 'ExtDelegateLib' : shared library name for targeted external delegate implementation
- 'ExtDelegateKeyVal': key-values pairs options passed to the external delegate for configuration purpose
Tested with:
- ARMNN Delegate
https://github.com/ARM-software/armnn/tree/branches/armnn_21_08/delegate/src
- VSI VX delegate
https://github.com/VeriSilicon/tflite-vx-delegate
Examples of gst-launch-1.0 tensor filter options for testing:
ARMNN:
`
tensor_filter framework=tensorflow-lite model=<file> custom=Delegate:External,ExtDelegateLib:libarmnnDelegate.so,ExtDelegateKeyVa …

Tflite external delegate

---

gst/nnstreamer/tensor_meta.h
gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.c
tests/nnstreamer_query/runTest.sh

The query server is changed to receive data by generating threads for each client.
TODO: Remove GStreamer dependency from tensor_query_common.

[Query] Add message handling thread for server.

---

gst/nnstreamer/tensor_converter/tensor_converter.c
tests/nnstreamer_plugins/unittest_plugins.cc
tests/nnstreamer_sink/unittest_sink.cc

1. convert bytes (octet stream) to flex-tensor when input info (type and dimension) is not denoted.
2. parse tensor-mata and convert to static when input is flexible tensor.

[Converter] convert bytes or flex-tensor without properties

---

ext/nnstreamer/tensor_filter/meson.build
packaging/nnstreamer.spec

To support NNStreamer filter for SNPE on both In-House build infra and
those of the public, this patch conditionally enables nnstreamer-snpe
rpm package when existing actual snpe library. (i.e. snpe.pc). In case
of the dummy SNPE package, nnstreamer-snpe rpm contains no files.
**Related Issue**
* https://github.com/nnstreamer/nnstreamer/issues/3442
* `snpe-devel.rpm` contains the `snpe-dummy.pc` so NNStreamer filter for SNPE is not built.
```bash
$ rpm -qlp snpe-devel-0.0.1-1.aarch64.rpm
/usr/lib64/pkgconfig/snpe-dummy.pc
$ rpm -qlp ./nnstreamer-snpe-2.1.0-0.aarch64.rpm
(contains no files)
```
* `snpe-devel.rpm` contains the …

[Spec] Enable SNPE filter on both In-House and public infra @open sesame 11/11 17:20

---

ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.cc
ext/nnstreamer/include/nnstreamer.fbs
ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
gst/nnstreamer/tensor_converter/tensor_converter.c
gst/nnstreamer/tensor_converter/tensor_converter.h
gst/nnstreamer/tensor_decoder/tensordec.c
tests/nnstreamer_flatbuf/runTest.sh

Support flexible tensors for flatbuffers.
Test pipeline
Server:
```
videotestsrc pattern=13 ! video/x-raw,format=RGB,width=640,height=480,framerate=5/1 ! tensor_converter ! mux.sink_0 \
videotestsrc pattern=18 ! video/x-raw,format=RGB,width=640,height=480,framerate=5/1 ! tensor_converter ! other/tensors,format=flexible ! mux.sink_1 \
tensor_mux name=mux ! tensor_decoder mode=flatbuf ! gdppay ! tcpserversink
```
Client
```
tcpclientsrc ! gdpdepay ! other/flatbuf-tensor ! tensor_converter ! other/tensors,format=flexible ! tensor_sink
```

[Flatbuf] support flexible tensors

---

gst/mqtt/mqttsrc.c

- Fix data type of GstQueryType 
- Default persistence mode have not been tested on various targets. Set it to None mode sync-ing with mqttsink.

[fix/mqttsrc] Set MQTT persistence mode of mqttsrc to None

---

jni/nnstreamer.mk

- Add mqtt sources to nnstreamer.mk
- Android api will build the gst element

[Android/mqtt] Add mqtt sources to nnstreamer.mk @open sesame 11/16 10:38

---

ext/nnstreamer/extra/nnstreamer_protobuf.cc
ext/nnstreamer/include/nnstreamer.proto
tests/nnstreamer_protobuf/runTest.sh

Support flexible tensors for protobuf.
Test pipeline.
Server:
```
videotestsrc pattern=13 ! video/x-raw,format=RGB,width=640,height=480,framerate=5/1 ! tensor_converter ! mux.sink_0 \
videotestsrc pattern=18 ! video/x-raw,format=RGB,width=640,height=480,framerate=5/1 ! tensor_converter ! other/tensors,format=flexible ! mux.sink_1 \
tensor_mux name=mux ! tensor_decoder mode=protobuf ! gdppay ! tcpserversink
```
Client
```
tcpclientsrc ! gdpdepay ! other/protobuf-tensor ! tensor_converter ! other/tensors,format=flexible ! tensor_sink
```

[Protobuf] Support flextensors for protobuf.

---

gst/mqtt/meson.build
gst/mqtt/mqttcommon.h
gst/mqtt/mqttsink.c
gst/mqtt/mqttsink.h
gst/mqtt/mqttsrc.c
gst/mqtt/ntputil.c
gst/mqtt/ntputil.h
meson.build
tests/check_broker.sh
tests/gstreamer_mqtt/unittest_mqtt.cc

Cherry-pick 6 commits from main branch to fix CI's mqtt test failure on lts/2.0,y branch

[lts/2.0.y][Hotfix] Fix mqtt related test failure on lts/2.0.y branch

---

ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.cc
ext/nnstreamer/extra/nnstreamer_grpc_protobuf.cc
ext/nnstreamer/extra/nnstreamer_protobuf.cc
ext/nnstreamer/tensor_converter/tensor_converter_python3.cc
gst/nnstreamer/include/nnstreamer_util.h
meson.build
tests/gstreamer_join/unittest_join.cc
tests/nnstreamer_converter/unittest_converter.cc

Update to fix build with glib version 2.68 and later
Legacy function:
gpointer g_memdup ( gconstpointer mem, guint byte_size )
is deprecated since version 2.68 and replaced by:
gpointer g_memdup2 ( gconstpointer mem, gsize byte_size )
Difference is byte_size argument type changed from guint to gsize.
Signed-off-by: Julien Vuillaumier <julien.vuillaumier@nxp.com>
This is a hotfix cherry-picking from main --> 2.0.y for https://github.com/nnstreamer/nnstreamer/issues/3218#issuecomment-977885118 (@ggardet )

[2.0.y][Build] Add g_memdup2() support for glib >= 2.68

---

gst/nnstreamer/tensor_common_pipeline.c
gst/nnstreamer/tensor_crop/tensor_crop.c
gst/nnstreamer/tensor_demux/gsttensordemux.c
gst/nnstreamer/tensor_sparse/tensor_sparse_dec.c
gst/nnstreamer/tensor_sparse/tensor_sparse_dec.h
gst/nnstreamer/tensor_sparse/tensor_sparse_enc.c
gst/nnstreamer/tensor_transform/tensor_transform.c
tests/nnstreamer_plugins/unittest_plugins.cc

If incoming buffer has single memory (case with gst-plugins), nnstreamer elements cannot generate output buffer (invalid memory chunks).

[Elements] handle single mem chunk

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
meson_options.txt

---
2 items related to XNNPACK delegate usage with TfLite framework (tested on TfLite 2.6):
1) Peculiarity of TfLite XNNPACK delegate usage in TfLite is that both input and output tensors buffer addresses are cached within XNNPACK runtime during first invoke(). NNStreamer tensor_filter input/output buffer memory addresses change from an inference to an other, therefore i/o buffer data has to be copied between Gst memory and TfLite allocated memory for tensors. Failure to do so typically leads to system crash as TfLite interpreter tries to access during subsequent invoke() to the GStreamer buffers populated during 1st invoke that have chances to have been deallocated and unmapped.
Currently only output tensors data copy is provisioned for XNNPACK case.
2) …

tensor_filter TFLite subplugin - XNNPACK delegate @open sesame 11/29 12:40

---

gst/nnstreamer/tensor_query/tensor_query_common.c

- backlog should be set before adding address or socket to listener.
REF:
https://people.gnome.org/~ebassi/docs/_build/Gio/method.SocketListener.set_backlog.html#description
- This commit should remove the following error logs:
```
...
GLib-GIO-CRITICAL **: 15:20:18.773: g_socket_set_listen_backlog: assertion '!socket->priv->listening' failed
...
```

[fix/query] Fix the order of calling `g_socket_listener_set_backlog`

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h

Fix socket op mode, blocking IO is unnecessary with multi-threaded server node.

[Query] fix invalid socket mode

---

packaging/nnstreamer.spec

This patch newly adds the restricted_element_vd for VD specialized
elements.

[Spec] Add restricted_element_vd for VD element @open sesame 11/02 06:05

---

packaging/nnstreamer.spec

This patch newly adds the restricted_element_vd for VD specialized
elements.
It is cherry-picking from main branch.

[Spec] Add restricted_element_vd for VD element

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_client.h
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_server.c
gst/nnstreamer/tensor_query/tensor_query_server.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversink.h
gst/nnstreamer/tensor_query/tensor_query_serversrc.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.h
tests/nnstreamer_query/runTest.sh

Change tensor query to accept ANY caps.
This change makes it possible to offload elements which require large amount of computation, such as tensor transforms, to the server.
Test pipeline.
SERVER
```
gst-launch-1.0 tensor_query_serversrc ! \
video/x-raw,width=300,height=300,format=RGB ! \
tensor_query_serversink
```
CLIENT
```
gst-launch-1.0 v4l2src ! videoconvert ! videoscale ! \
video/x-raw,width=300,height=300,format=RGB,framerate=30/1 ! \
tensor_query_client ! videoconvert !  ximagesink
```

[Query] Change tensor query to accpet ANY caps @open sesame 11/30 17:57

---

gst/nnstreamer/tensor_common.h
gst/nnstreamer/tensor_common_pipeline.c
gst/nnstreamer/tensor_merge/gsttensormerge.c
gst/nnstreamer/tensor_mux/gsttensormux.c

Currently, GstMeta of the buffer from first pad is used.
Change to copy GstMeta same with sync mode of the tnesor mux and merge.

[Mux/Merge] Change meta copy policy

---

debian/rules
meson.build
meson_options.txt
packaging/nnstreamer.spec

---
Tentative patchset for multilib fix, aggregating:
1) original change from @panfir submitted in https://github.com/nnstreamer/nnstreamer/pull/3554
2) complementary change from @myungjoo to fix Debian/Tizen packages, submitted in https://github.com/panfir/nnstreamer/pull/1
3) a couple of additional fixup that may help
See also: #3554
SSAT test suite passed

multilib correction - #3554 follow up

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.c

Define common timeout for tensor-query.
TODO: we should handle timeout in query-server elements.

[Query] set default timeout

---

gst/nnstreamer/nnstreamer_log.h
tests/meson.build
tests/nnstreamer_filter_edgetpu/meson.build
tests/nnstreamer_filter_edgetpu/unittest_edgetpu.cc
tests/nnstreamer_filter_extensions_common/meson.build
tests/nnstreamer_filter_mvncsdk2/meson.build
tests/nnstreamer_filter_openvino/meson.build
tests/nnstreamer_filter_tvm/meson.build
tests/nnstreamer_plugins/unittest_plugins.cc
tests/tizen_nnfw_runtime/meson.build
tests/tizen_sensor/meson.build
tests/unittest_util.c
tests/unittest_util.h

1. Add a dlog_print hijacker that makes dlog calls independent
from dlog daemon and drivers. As a result, developers can now
read the dlog log messages of unittests in gbs environment.
2. Clean up a bit of meson.build dependency declaration of
unit tests.
3. A unit test without direct dlog call is updated to call
it directly so that the hijacker is linked (edgetpu).

Test: enhancing log behaviors for unittest

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_common.c

1. Fix invalid data size - caps string length.
2. Clearly define client and server param and update log message.

[Query] fix invalid data size

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c

- Some filter using hardware accelerator consume quite time for loading model file.
- Add log for what time it takes.

[filter] Add a time duration log of filter open @open sesame 12/10 12:27

---

gst/nnstreamer/tensor_query/README.md
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversink.h

Some GStreamer element don't copy GstMeta. So tensor query cannot handle buffer.
Change error message when GstMeta is invalid and stop pipeline.
The available elements table is not completed yet and will change frequently, so I will write it on the wiki page first.
*note: query server src does not set format (GST_FORMAT_TIME) currently, compositor also is not availabe.  This will also be changed soon.

[Query] Change error message when GstMeta is invalid.

---

tests/cpp_methods/unittest_cpp_methods.cc

Change filesink buffer mode to ubnuffered.
Related issue: https://github.com/nnstreamer/nnstreamer/issues/3275

[TEST] Change filesink buffer mode.

---

debian/nnstreamer-core.install
ext/nnstreamer/tensor_decoder/meson.build
ext/nnstreamer/tensor_decoder/tensordec-octetstream.c
jni/Android.mk
jni/nnstreamer.mk
packaging/nnstreamer.spec
tests/nnstreamer_octet_stream/runTest.sh

Decode tensors to octet stream.
If tensor format is flexible, remove the header.

[Dec/Sub] Add octet-stream decoder subplugin. @open sesame 12/10 14:24

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h

1. Add new function to set client ID.
2. Remove unnecessary value - protocol in cmd data. The connection handle includes this value.

[Query] client id in connection handle

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc

For developers, we need to elaborate error messages.
The error messages should have enough information to
understand what's wrong and what to fix.
We will be updating all error messages of nnstreamer.
This helps #3603
This is part of #3475

filter/tensorflow-lite: loadModel error message

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_serversink.c

- Check whether the cap is fixed or not before setting the cap.
2. Run test: [*] Passed [ ]Failed [ ]Skipped

[Query] Check whether cap is fixed or not.

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc

Hello,
This change is a proposal to fix a crash visible on TFLite filter using external delegate - same issue is also present for other delegates except NNAPI that uses appropriate unique_ptr declaration.
XNNPACK, NNAPI and external delegate deletion has been verified. Could not verify GPU delegate as it is not available on my setup.
Thank you
On pipeline stop, crash in TFLite filter may be seen with some
delegates with log signature:
Setting pipeline to NULL ...
free(): invalid pointer
Pipeline termination procedure is then aborted.
TFlite delegates shall be released by specific deleter, provided
by their respective interface.
TFLite filter implementation manages delegates instance with
smart pointers for automatic disposal when interpreter goes out of
of scope.
Care should be taken to …

[Filter/TFLite] Fix delegates deleter usage @open sesame 12/17 16:37

---

tests/cpp_methods/unittest_cpp_methods.cc
tests/nnstreamer_converter/unittest_converter.cc
tests/nnstreamer_decoder/unittest_decoder.cc
tests/nnstreamer_if/unittest_if.cc
tests/unittest_util.c
tests/unittest_util.h

When creating a temp file name, it is intended to create a unique name, but duplicated temp names may occasionally generated because we remove generated file and get the temp name only.
So sometimes duplicated temp file names are generated when creating temp filenames multiple times.
Change the file to delete after it is used.
Previously, if 1,000 tests were performed, it failed about 15 times on my local PC.
There was no failure when I repeated 2,000 times with this change.
Related issue: #3275 
For example, generate tmp filename 5 times, tmp2 and tmp3 is duplicated.
[  200s] ** (unittest_cppfilter:132252): CRITICAL **: 05:07:52.416: tmp1: /tmp/nnstreamer_unittest_temp_UJOPE1
[  200s] ** (unittest_cppfilter:132252): CRITICAL **: 05:07:52.416: tmp2: …

[TEST/util] Change getTempFilename function

---

tests/nnstreamer_query/runTest.sh

- Wait for the server to start.
If client attempts to connect to the server when the server is not ready, it may  fails.
Previous PR, sleep time was omitted only in Test 7.
- Fix invalid comment.

[TEST] Wait for the server to start and fix comment.

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c

Fix mem leak, init default framework in filter-common function.

[Filter] set default fw in common

---

tests/nnstreamer_decoder/checkResult.py
tests/nnstreamer_decoder/runTest.sh
tests/test_utils.py

If the test runs with the valgrind, the comparison of the padded video fails.
(Related issue: https://github.com/nnstreamer/nnstreamer/issues/1367)
Zero was padded when running without the valgrind, but trash value was padded when running with the valgrind.
The comparison of the padded data is meaningless, it is modified to compare only the actual data.

[TEST] Changed the comparison method of the padded video.

---

meson.build
meson_options.txt
packaging/nnstreamer.spec

The name 'restricted-elements' of nnstreamer configuration is not
matched as its real operation. This patch renames it to
'allowed_elements'.
* https://github.com/nnstreamer/api/pull/128

[Conf] Update the name of 'restricted-elements'

---

tests/test_models/models/custom_converter_json.py

Getting result from python json parser, result string doesn't contain
null char, the test fails.
Add null char to the string from python json parser.
Daily build failure: http://nnstreamer.mooo.com/nnstreamer/ci/daily-build/build_result/latest/log/build_log_tizen_armv7l_output_2022-01-11.txt
```
...
[  357s] [ RUN      ] tensorConverterPython.jsonParser
[  357s] ../tests/nnstreamer_converter/unittest_converter.cc:490: Failure
[  357s] Expected equality of these values:
[  357s]   "string_example"
[  357s]   output
[  357s]     Which is: "string_exampleh\xE1\x18"
[  357s] [  FAILED  ] tensorConverterPython.jsonParser (282 ms)
...
```
2. Run test: [ *]Passed [ ]Failed [ …

[Test] Fix python custom converter test fail

---

packaging/nnstreamer.spec

Tizen Robot Vacuum cleaner needs the SNPE filter. This patch enables it
on the DA profile.

[Spec] Enable SNPE filter on DA profile

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

- Add a feature for decoding yolov5 model's output
- Tested with tflite models from https://github.com/ultralytics/yolov5/releases/tag/v6.0
issue #3623 
sample gst-launch pipelines:
- for 640x640 model
```bash
$ gst-launch-1.0 \
v4l2src ! videoscale ! videoconvert ! video/x-raw,width=640,height=640,format=RGB,framerate=30/1,pixel-aspect-ratio=1/1 ! tee name=t \
t. ! queue ! tensor_converter ! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:640:640:1 ! \
tensor_transform mode=arithmetic option=typecast:float32,add:0.0,div:255.0 ! queue leaky=2 max-size-buffers=2 ! \
tensor_filter framework=tensorflow2-lite model=./yolov5s-fp16.tflite ! \
other/tensors,num_tensors=1,types=float32,format=static,dimensions=85:25200:1:1 ! \
tensor_decoder mode=bounding_boxes option1=yolov5 …
```

[decoder/bounding_box] Add decoder for yolov5 @open sesame 01/03 18:03

---

ext/nnstreamer/tensor_filter/meson.build
packaging/nnstreamer.spec

To support the SNPE on DA Robot Vacuum cleaner, this patchset should be applied to Tizen 6.5 branch.
All of them are already merged to the main branch.
**Patch items**
* [Spec] Enable SNPE filter on both In-House and public infra
* [Spec] Enable SNPE filter on DA profile 

Support the SNPE on DA Robot Vacuum cleaner

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_trix_engine.cc
ext/nnstreamer/tensor_filter/tensor_filter_trix_engine.hh
meson.build
meson_options.txt
packaging/nnstreamer.spec

This patch adds TRIx-Engine tensor filter subplugin implementation.
It requires TRIV2 NPU HW and devel packages from the upstream tizen repo.

[TRIx-Engine] Add TRIx-Engine subplugin

---

gst/nnstreamer/nnstreamer_conf.c
meson.build
meson_options.txt
nnstreamer.ini.in
tests/common/unittest_common.cc

The product team wants to update the nnstreamer configuration (i.e.
/etc/nnstreamer.ini). However, the partition is Read-Only so it is not
updatable. Because of this reason, they want another nnstreamer
configuration file to meet their request such as product-specific
restricted elements. This patch newly adds the nnstreamer extension ini
file for product support.
```ini
[common]
extra_config_path=/tmp/nns-api-X6XDF1/nns-product.ini	 # Location of product-specific configuration file.
```
* https://github.com/nnstreamer/nnstreamer/issues/3629

[INI] Add extra configuration file for product support

---

ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc

ptyorch filter when working with gpu backend had bugs when converting
between the devices. The tensors returned by the conversion were not
captured. This patch provides the corresponding fix.
See also: #3620

[filter] Bug fix for pytorch filter with gpu

---

gst/mqtt/mqttsrc.c

Bug fix, set default value after initializing connection option.

[MQTTSrc] default options before initializaion

---

tests/nnstreamer_flatbuf/runTest.sh
tests/nnstreamer_flexbuf/runTest.sh
tests/nnstreamer_protobuf/runTest.sh

- Disable protobuf, flatbuf, flexbuf SSAT tests when related libs did not built
1. Build test: [✔]Passed [ ]Failed [ ]Skipped
2. Run test: [✔]Passed [ ]Failed [ ]Skipped

[test/ssat] Disable proto flat flex buf SSAT tests when there are no supports

---

Documentation/getting-started-android.md

- Update android guide document: gstreamer version v1.16.2 -> v1.20.0

[trivial/doc] Update android guide: gstreamer v1.16.2 -> v1.20.0

---

ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
tests/bmp2png.c

Fix svace issues
- init local variable
- check allocation failure case

[Svace] fix svace issues

---

gst/mqtt/mqttsink.c
gst/mqtt/mqttsrc.c

Destroy mqtt-async handle when the element instance is finalized.

[MqttSrc/Sink] release mqtt handle

---

ext/nnstreamer/extra/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
ext/nnstreamer/tensor_filter/tensor_filter_trix_engine.cc
ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
tests/bmp2png.c
tests/nnstreamer_filter_mvncsdk2/NCSDKTensorFilterTestHelper.cc
tests/nnstreamer_filter_mvncsdk2/NCSDKTensorFilterTestHelper.hh
tests/nnstreamer_filter_mvncsdk2/meson.build

Fix build error caused by unused param.
- Ignore auto generated files (flatbuf, protobuf)
Fix different sign compare

Fix build error - unused param, sign comapre

---

packaging/nnstreamer.spec

This patch disables trix_engine_support for TV releases.
Signed-off-by: yelini-jeong <yelini.jeong@samsung.com>

[Build] Disable trix engine support for TV releases

---

ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
ext/nnstreamer/tensor_filter/tensor_filter_tvm.cc
tests/nnstreamer_filter_lua/unittest_filter_lua.cc
tests/nnstreamer_filter_snpe/unittest_filter_snpe.cc
tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc

- Add check for `G_FILE_TEST_IS_REGULAR` in some cpp class based filters
- Free allocated string for lua script
- Fix minor mem-leak in lua, snpe, tvm unittests
Build test: [X]Passed [ ]Failed [ ]Skipped
Run test: [X]Passed [ ]Failed [ ]Skipped

[fix] Fix mem-leak issues in cpp class based filters

---

gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_transform/tensor_transform.c
tests/nnstreamer_filter_pytorch/runTest.sh

- Check null before call g_string_append to remove logs `g_string_insert_len: assertion 'len == 0 || val != NULL' failed`
- Since tensor_transform cannot specify the sinkpad's type caps in some modes, let the `transform_caps` remove the field in that case
- Add a test to check whether tensor_filter - tensor_transform pipeline can be negotiated with static format, not flexible format.
- Modify the order of `caps_intersect_full` in tensor_filter
This resolves #3636

[transform] Fix transform_caps in direction GST_PAD_SRC 

---

gst/nnstreamer/include/nnstreamer_plugin_api.h
gst/nnstreamer/include/nnstreamer_plugin_api_util.h
gst/nnstreamer/nnstreamer_plugin_api_impl.c
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
gst/nnstreamer/tensor_common.h

Fix typo and license in util functions and header.
Update internal function description and remove unnecessary param.

[Util] fix typo and license

---

tests/nnstreamer_converter/unittest_converter.cc
tests/nnstreamer_converter_python3/runTest.sh

TEMPORAL SOLUTIONS: PLEASE REVERT THIS COMMIT AFTER FIXING THE ISSUE.
When the Python tensor converter test is completed, a deadlock occurs.

[TEST] Disable python converter tests.

---

debian/nnstreamer-dev-internal.install

dev-internal pkg should include filter-single header for single-shot API.

[Pkg] add filter-single header

---

tests/nnstreamer_filter_python3/runTest.sh

- remove exit if build folder not exists
- bypass pushd failure if build folder not exists
Signed-off-by: Aymen Sghaier <aymen.sghaier@nxp.com>

[SSAT] Enable filter_python3 test to run on target @open sesame 3/7 18:10

---

gst/nnstreamer/meson.build
packaging/nnstreamer.spec
tests/unittest_util.c

Log util is available only in nnstreamer repo.
Remove exporting the header for logging.

[Log] exporting logger

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
meson_options.txt

- Check each tflite delegate symbol by linking with tflite dep in build time
This resolves #3674

[build/tflite] Check each delegate symbol in build time

---

ext/nnstreamer/extra/nnstreamer_python3_helper.cc
ext/nnstreamer/extra/nnstreamer_python3_helper.h
ext/nnstreamer/tensor_converter/tensor_converter_python3.cc
ext/nnstreamer/tensor_decoder/tensordec-python3.cc
ext/nnstreamer/tensor_filter/tensor_filter_python3.cc

Code clean,
1. possible leak and exception to load python module.
2. remove unnecessary macro.

[CodeClean/Python] possible leak in python subbplugin

---

meson.build

Add -Wredundant-decl only when !(pytorch or caffe2), not !(pytorch and caffe2).
Even when only one of the two are included, they have redundant decl warnings.
It appears that we haven't tested cases where only one of pytorch and caffe2 is
enabled.
Fixes #3693

filter/pytorch,caffe2: they have redundant decls. @open sesame 3/17 14:29

---

ext/nnstreamer/tensor_converter/tensor_converter_python3.cc
tests/nnstreamer_converter/unittest_converter.cc
tests/nnstreamer_converter_python3/runTest.sh

Tizen issues: After python version has been upgraded from 3.9.1 to 3.9.10, python converter is stopped at Py_Finalize.
Since Py_Initialize is not called twice from this object, Py_Finalize is temporarily removed.
Related issue: #3684 

[converter/python3] Temporarily remove Py_Finalize

---

ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc

Fix the print format string error:
```
In file included from /usr/include/glib-2.0/glib.h:62:0,
from ../gst/nnstreamer/nnstreamer_log.h:75,
from /<<PKGBUILDDIR>>/ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc:29:
/<<PKGBUILDDIR>>/ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc: In member function ‘int TorchCore::validateOutputTensor(at::Tensor, unsigned int)’:
/usr/include/glib-2.0/glib/gmessages.h:336:43: error: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘gsize {aka unsigned int}’ [-Werror=format=]
__VA_ARGS__)
^
../gst/nnstreamer/nnstreamer_log.h:79:17: note: in expansion of macro ‘g_critical’
#define ml_loge g_critical
^~~~~~~~~~
/<<PKGBUILDDIR>>/ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc:348:5: note: in expansion of macro …
```

filter:pytorch: armhf error in PPA (print format)

---

ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc

There are different definitions for gsize.
Use %G_GSIZE_FORMAT for the portability
Note that #3699 was not portable enough.

filter:pytorch: use %G_GSIZE_FORMAT for printing gsize

---

gst/nnstreamer/include/nnstreamer_plugin_api_util.h
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
gst/nnstreamer/tensor_converter/tensor_converter.c

When there is a pipeline error, especially at the construct phase,
users need elaborated error messages that provide useful infomation
to correct pipeline descriptions.

converter: elaborate error messages @open sesame 3/28 19:04

---

tests/nnstreamer_converter/unittest_converter.cc
tests/nnstreamer_decoder/unittest_decoder.cc
tests/nnstreamer_if/unittest_if.cc

We have the following error at PPA for armhf build:
```
../tests/nnstreamer_converter/unittest_converter.cc:409: Failure
Value of: wait_pipeline_process_buffers (data_received, 1, TEST_TIMEOUT_MS)
Actual: false
Expected: true
../tests/nnstreamer_converter/unittest_converter.cc:414: Failure
Expected: (caps) != (nullptr), actual: NULL vs 4-byte object <00-00 00-00>
(unittest_converter:16055): GStreamer-CRITICAL **: 06:06:01.349: gst_caps_get_structure: assertion 'GST_IS_CAPS (caps)' failed
../tests/nnstreamer_converter/unittest_converter.cc:416: Failure
Expected: (structure) != (nullptr), actual: NULL vs 4-byte object <00-00 00-00>
** (unittest_converter:16055): CRITICAL **: 06:06:01.351: gst_tensors_config_from_structure: assertion 'structure != NULL' failed …
```

test: ppa/armhf timeout

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
gst/nnstreamer/tensor_filter/tensor_filter_common.c

reload shared interpreter for filter objects sharing same key

[Filter] reload shared model @open sesame 2/28 00:30

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
gst/nnstreamer/tensor_converter/tensor_converter.c
tests/bmp2png.c

1. Set interpreter lock while replacing interpreter in tf-lite sub-plugin.
2. Remove unreached code in converter.
3. Clearly check file ext (bmp) in test util.

[CodeClean] fix svace issue

---

README.md

- Fix invalid log link of the ubuntu daily build.
- Change link of the badges to daily log path.

[README] Fix daily build log link

---

gst/nnstreamer/nnstreamer_subplugin.c

- When tf1-lite and tf2-lite both are present, the later called
subplugin is not initalized. It's because the constructor functions
are same as "init_filter_tflite".
e.g.) `g_module_open (...tf1lite.so, 0)` will call "init_filter_tflite" of
tf2lite.so.
- This resolves #3709

[subplugin] g_module_open with LOCAL flag (instead of GLOBAL)

---

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc

- Some snpe model has "0" for their output layer which is same as "1"
- Handle this corner case

[lts/6.5][fix/snpe] Handle zero dim models

---

gst/nnstreamer/tensor_transform/README.md
gst/nnstreamer/tensor_transform/tensor_transform.c
gst/nnstreamer/tensor_transform/tensor_transform.h
tests/nnstreamer_plugins/unittest_plugins.cc
tests/transform_arithmetic/runTest.sh

- Add "per-channel" arithmetic op (this resolves #3711)
- The syntax:
```
tensor_transform mode=arithmetic
option=typecast:float32,per-channel:true@DIM,add:A@CH_IDX,div:D@CH_IDX
```
- DIM means the dimension which is viewed as channel
ex) For 3:4:4:1 incoming tensor, per-channel:true@0 means 0-th DIM (value is 3) is the channel
- CH means the idx of channel that given operation is applied. If @CH_IDX is missing, the operation is applied to all channels.
ex) add:255@0 means add 255 to the 0-th channel (which is R among the RGB)
- Usage examples:
```
$ gst-launch-1.0 videotestsrc pattern=2 num-buffers=1 ! videoscale !
videoconvert ! video/x-raw,format=RGB,width=2,height=2 !
tensor_converter ! tensor_transform mode=arithmetic
option=typecast:float32,per-channel:true@0,add:1.5@0,add:2.5@1 ! …
```

[transform] Add per-channel feature for arithmetic op

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c

Remove unnecessary init while parsing accel string.
- fetch fw info to parse accel for the case if nn framework is not opened.
- check fw info if open() callback of nn framework is not written.

[Filter] unnecessary initialization

---

tests/nnstreamer_query/runTest.sh

This patch skips query test temporarily because of ppa build failure.
See also: #3657 
Signed-off-by: yelini-jeong <yelini.jeong@samsung.com>

[TEST] Skip query test temporarily @open sesame 04/26 13:29

---

gst/nnstreamer/meson.build
gst/nnstreamer/nnstreamer_log.c
gst/nnstreamer/nnstreamer_log.h
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter_common.c
gst/nnstreamer/tensor_filter/tensor_filter_common.h
jni/nnstreamer.mk

commit 6083f63be35bf6ee27a9276be2ee965800d3892e (HEAD -> err/filter/1, github-fork/err/filter/1)
Date:   Wed Mar 30 19:12:59 2022 +0900
[WIP] filter: elaborate error messages.
Elaborate error and warning messages so that users and developers
can easily point out and fix issues.
commit 14f3596df669383db0b8c6d24539e68bb6039d34
Date:   Wed Mar 30 19:12:08 2022 +0900
common/internal: backtrace function for debugging
For debugging messages, add a backtrace function.

Elaborate error messaegs for tensor-filter @open sesame 4/21 11:05

---

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc

This reverts commit https://github.com/nnstreamer/nnstreamer/commit/7826866a7524b6769b9d5476c6d9bf04f0105ea7.
- Still figuring out how to deal with this "zero dim".
Make the order of output tensors be consistent with the user given option
- For multiple output models, let user set output tensors instead of output layers
- And make the order of input / output tensors be consistent.
Updated:
Some snpe models have "0" dim to represent resizable dim.
Add a custom option "MaxResizableDim" to deal with this case.

[lts][filter/snpe] Revert "[fix/snpe] Handle zero dim models" and fix the order of output tensors

---

tests/meson.build

converter test uses python scripts.
disable converter test if python is not available.

test: disable converter test if python is not available.

---

tests/nnstreamer_plugins/unittest_plugins.cc

Some code quality analyzer checks no assertion test.
testTesnrSparse_utilConvert has assert test, but the analyzer cannnot check macro.
So, to avoid the false-positive case, unwinding macro.
```
Check result:
-Analysis Time: 05-13-2022 12:21
-Total TCs: 575
-Positive TCs: 276
-Negative TCs: 299
-Undefined TCs: 0
-Total Alarms: 0
```

[TEST] Unwinding macro to avoid no assertion test.

---

debian/nnstreamer-python3.install
debian/nnstreamer-python3.links
ext/nnstreamer/extra/meson.build
meson.build
packaging/nnstreamer.spec

Change install path for python-helper library.
This is to fix library link error.

[Python] path to python helper lib

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_mxnet.cc
jni/nnstreamer.mk
meson.build
meson_options.txt
tests/meson.build
tests/nnstreamer_filter_mxnet/Predictor.hh
tests/nnstreamer_filter_mxnet/download_and_run.sh
tests/nnstreamer_filter_mxnet/meson.build
tests/nnstreamer_filter_mxnet/simple_test_mxnet.cc

**Based on PR #2831 by @kbumsik**
This PR is to newly add MXNet subplugin support for tensor_filter.
We did these things:
- Rebased the commits of PR #2831 on current main branch
- Fixed some bugs on the test code
- Add/Modify some comments into doxygen style
- Reformatted the code to follow the coding convention in `.clang-format` of the root directory
We can follow instructions on original PR #2831, but we tested on the latest version of MXNet.
Warning: The following test example will download >1.5GB of data from MXNet for dataset
```
cd nnstreamer-git
ninja -C build install
cd build/tests/nnstreamer_filter_mxnet
./download_and_run.sh    # This will run simple_test_mxnet
```
Note: I am working on …

[Filter/MXNet] Add a sub-plugin filter for MXNet @open sesame 5/2 13:33

---

tests/nnstreamer_filter_extensions_common/meson.build

In macOS, the '-i' option of the sed command requires a parameter to
tell what extension to use for the backup file. To this end, this patch
appends '.bak' to the '-i' option to fix the build errors on macOS.

[macOS/meson] Add a missing parameter to the sed's in-place edit option

---

tests/nnstreamer_if/unittest_if.cc

This patch fixes the following build error while compiling with clang in macOS.
With clang in macOS:
../tests/nnstreamer_if/unittest_if.cc:65:8: error: 'TearDown' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
void TearDown ()
^
/opt/homebrew/Cellar/googletest/1.11.0/include/gtest/gtest.h:481:16: note: overridden virtual function is here
virtual void TearDown();
^
1 error generated.

[Tests/IF] Fix a build error related to -Winconsistent-missing-override

---

Documentation/getting-started-macos.md

This patch replaces the old organization name, nnsuite, remaining in the Getting Started document with the current one, nnstreamer.
See also: https://github.com/nnstreamer/homebrew-neural-network/issues/20
TODO: The Getting Started document for macOS looks out-of-date. It is required to be fully revised. 

[macOS/Doc] Replace 'nnsuite' with 'nnstreamer'

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

[decoder/bounding_box] Fix ssd box decoding without postprocessing
Boxes whose detection scores do not exceed the specified sigmoid
threshold shall never be reported as valid.
This changeset fixes current implementation whereby valid field
for a box is set only when its detection scores have passed the
threshold tests. Thus, if score test is not passed, valid field for
a box is inherited from the previous box score tests.
Therefore without this change, whenever one box passes the score
criteria, every subsequent boxes will be reported as valid, even though
their detection scores are low.
As a consequence, a very big number of boxes may be passed to the
next stage of NMS processing which causes processing overhead.
1. Build test: …

[decoder/bounding_box] Fix ssd box decoding without postprocessing

---

ext/nnstreamer/meson.build
ext/nnstreamer/tensor_filter/meson.build
meson.build
tools/development/parser/meson.build

This patch sets the keyword argument, 'check', of the run_command
function to true in order to fix the following warnings:
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in future releases of meson.
See also: https://github.com/mesonbuild/meson/issues/9300

[Meson] Fix warnings related to the run_command call

---

meson.build

Hello All,
We see a build issue with Yocto package on main branch during meson configuration.
This change fixes the problem for Yocto.
Thanks
A build configuration error is seen on Yocto Kirkstone (4.0)
coming from commit:
https://github.com/nnstreamer/nnstreamer/commit/0584ce06e30f1dbb188bce2b370df53d335046dd
Signature of error:
meson.build:505:4: ERROR: Command "//recipe-sysroot-native/usr/bin/python3-native/python3 -m site --user-site" failed with status 1
Building with Yocto, native tools are sandboxed in build workspace,
there is no python user site.
This change is to prevent meson configuration to break when no user
site package is present.
Signed-off-by: Julien Vuillaumier <julien.vuillaumier@nxp.com>
2. Run test: [ …

[meson] Fix Yocto Kirkstone build issue

---

debian/nnstreamer-tensorflow2-lite.install
debian/rules
ext/nnstreamer/tensor_filter/meson.build
meson_options.txt
packaging/nnstreamer.spec

This addresses plan B of #3713
$ ldd build/ext/nnstreamer/tensor_filter/libnnstreamer_filter_tensorflow2-lite-custom.so
linux-vdso.so.1 (0x00007fffe21f2000)
libnnstreamer-single.so => /source/AutoDrv/NNStreamer/build/ext/nnstreamer/tensor_filter/../../../gst/nnstreamer/libnnstreamer-single.so (0x00007f08b5bba000)
/source/AutoDrv/NNStreamer/ext/nnstreamer/tensor_filter/libtensorflow2-lite-custom.so (0x00007f08b50a5000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f08b4ea1000)
libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f08b4b8a000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f08b477d000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f08b4565000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f08b4174000) …

Tensorflow-lite custom bin support: Plan B @open sesame 6/10 08:01

---

ext/nnstreamer/tensor_filter/README.md

To clarify which mechanism to use for new tensor-filter subplugin,
added a short guide on how to write tensor-filter subplugin.

doc/filter subplugin: brief guide on how to write subplugin @open sesame 6/10 08:04

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.c
tests/nnstreamer_query/unittest_query.cc

Protocols are enum. Use enum-param, not int or string.
With this, users can use both numbers and enum-strings.
PTAL: @jaeyun-jung @gichan-jang

Query: fix protocol property handling

---

tests/cpp_methods/meson.build
tests/meson.build
tests/nnstreamer_filter_extensions_common/meson.build

If you have gcc >= 11 and gtest <= 1.8, you may have build errors:
/usr/src/gtest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
/usr/src/gtest/src/gtest-death-test.cc:1009:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
1009 |   StackLowerThanAddress(&dummy, &result);
|   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/src/gtest/src/gtest-death-test.cc:999:6: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here
999 | void StackLowerThanAddress(const void* ptr, bool* result) {
|      ^~~~~~~~~~~~~~~~~~~~~
/usr/src/gtest/src/gtest-death-test.cc:1007:7: note: ‘dummy’ declared here
1007 |   int dummy;
|       ^~~~~
As gtest's code is not our test target, let the …

tests: build error w/ higher gcc & lower gtest @open sesame 6/7 19:24

---

packaging/nnstreamer.spec

- In 64-bit the dep is like "libtensorflow2-lite-custom.so()(64bit)"
- To cut this properly, replace "so" with "*"

[spec] Fix spec to cut the depedency on custom tflite in 64-bit

---

gst/nnstreamer/tensor_query/nnstreamer_edge_common.h
gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c
gst/nnstreamer/tensor_query/nnstreamer_edge_mqtt.c

Code clean, remove unnecessary function and fix invalid return.
The edge-handle may have multiple connections, checking connection is unnecessary.
Instead, we will add internal function for each socket.

[Edge] remove unnecessary function

---

tests/nnstreamer_grpc/runTest.sh

1. Do not fork ssat-api functions
2. Do not sleep constant time. Check the launch process.

[CI TC Fail Fix] test/grpc: correct parallel unit test calls @open sesame 6/10 13:24

---

gst/nnstreamer/tensor_query/nnstreamer_edge_common.c

Fix mem leak and invalid data info when copying edge-data.

[Edge] invalid data info when copying edge data

---

gst/nnstreamer/tensor_query/tensor_query_common.c
tests/nnstreamer_filter_extensions_common/meson.build
tests/nnstreamer_if/unittest_if.cc

This PR fixes build breaks of lts/2.0.y for macOS. The cherry-picked patches from the upstream branch are as follows:
- tensor-query: cross-platform compatibility (non-Linux)
- [macOS/meson] Add a missing parameter to the sed's in-place edit option
- [Tests/IF] Fix a build error related to -Winconsistent-missing-override

Fixes build breaks of 2.0.y on macOS

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc

Hello all,
This is a bugfix for an issue detected with TFLite delegate supporting dynamic shape.
Tensors are not allocated and inference can not run.
AllocateTensors() has to be called consistently before Invoke() even in case of delegate usage.
That is the case in TFLite examples code.
Thanks
[Filter/TFLite] Fix model tensors allocation not working for some delegates
This change is correction for error below reported by the TFlite library
during Invoke():
"Invoke called on model that is not ready."
Tensors allocation may be done by TFLite framework during call to
ModifyGraphWithDelegate() but that is not guaranteed.
Therefore, even if delegates are used, tensors allocation must be done
explicitly with AllocateTensors(), prior to inferencing with Invoke().
Signed-off-by: Julien …

[Filter/TFLite] Fix model tensors allocation not working for some delegates

---

ext/nnstreamer/meson.build

This patch changes the way to find 'grpc_cpp_plugin' to use find_program(), the built-in function provided by Meson.

[Ext/Meson] Use find_program() instead of 'which'

---

tests/nnstreamer_grpc/runTest.sh

In case NNSTREAMER_BUILD_ROOT_PATH is not defined, the test cases for gRPC might run in an unintentional way. To this end, this patch adds a fallback value for PATH_TO_PLUGIN to runTest.sh.

[Tests/gRPC] Prepare a fallback value for PATH_TO_PLUGIN @open sesame 07/01 13:45

---

tests/nnstreamer_grpc/runTest.sh

By using ```SO_EXT``` and  ```StatCmd_GetSize``` provided by the SSAT API, this PR revise the script, runTest.sh, in a more portable way.
ref: #3820

[tests/gRPC] Revise runTest.sh in a more portable way by using the SSAT API

---

tests/nnstreamer_query/runTest.sh

grep in macOS does not have -P, --perl-regexp. In addition, the stat's option to specify a format also differs from that of Linux distros. This patch revises runTest.sh to support macOS by applying the above differences.

[Tests/Query] Revise runTest.sh to support macOS

---

.github/workflows/gbs_x64.yml
.github/workflows/tizen.gbs.conf

Run gbs in github-action for more Tizen testing.
Tested. Github-action took 13m 57s to complete the gbs test. (gbs build took 13m 18s, gbs-install took 33s)
This commit can be used by other github repos who want to test Tizen gbs build.
Note: TAOS-CI's gbs build is much faster!
TODO: write a single .yml file for github-action marketplace.

[github-action] Run GBS in github-action

---

ext/nnstreamer/extra/nnstreamer_python3_helper.h
ext/nnstreamer/tensor_filter/tensor_filter_python3.cc

Use Python GIL for multi-threaded python custom filters.
Don't use a local lock, use GIL.
The execution result of CV2 enabled python code of #3822:
```
$ gst-launch-1.0 videotestsrc num-buffers=10 ! video/x-raw,format=RGB,width=280,height=40 ! tensor_converter ! tensor_filter framework=python3 model=p2.py input=3:280:40:1 inputtype=uint8 output=3:280:40:1 outputtype=uint8  ! tensor_decoder mode=direct_video ! videoconvert ! ximagesink
init_filter_py:844
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
--- USE_CV2:True /source/AutoDrv/NNStreamer/tests/p2.py (33600,)
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
--- USE_CV2:True /source/AutoDrv/NNStreamer/tests/p2.py (33600,)
--- USE_CV2:True /source/AutoDrv/NNStreamer/tests/p2.py (33600,)
--- …
```

filter/python3: support multi-threaded python custon filters.

---

tests/meson.build

In order to enforce to keep ./tests/bmp2png the same as the one in the build directory, this patch modifies the meson build script to copy bmp2png to the tests directory from the build directory every build time.

[Tests/Meson] Copy bmp2png to the tests directory every build time @open sesame 07/05 10:15

---

ext/nnstreamer/extra/meson.build
ext/nnstreamer/extra/nnstreamer_grpc_common.cc
ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
tests/bmp2png.c
tests/nnstreamer_filter_mvncsdk2/NCSDKTensorFilterTestHelper.cc
tests/nnstreamer_filter_mvncsdk2/NCSDKTensorFilterTestHelper.hh
tests/nnstreamer_filter_mvncsdk2/meson.build
tests/nnstreamer_grpc/runTest.sh

In order to enable gRPC sub-plugins of 2.0.y LTS on macOS, this PR includes the following commits cherry-picked from the main branch.
- [[gRPC/Common] Modify hard-coded strings indicating sub-plugins' names](https://github.com/nnstreamer/nnstreamer/commit/9f3cfa20f4af04fd975e89147f94fec7d94b514c)
- [[Tests/gRPC] Prepare a fallback value for PATH_TO_PLUGIN](https://github.com/nnstreamer/nnstreamer/commit/7c1063d87e4746373ddbe0a10565fe2e5fa32ab5)
- [[tests/gRPC] Change the hard-coded shared object's extension](https://github.com/nnstreamer/nnstreamer/commit/0451effca767585fab2511caaea400c0a013b35a)
- [Fix build error - unused param, sign comapre](https://github.com/nnstreamer/nnstreamer/commit/a1924848100c42a91c6d0df8c88d23e1a64e0f60)
This might be the last PR for macOS support of 2.0.y …

[LTS/2.0.y] Push cherry-picked commits for enabling gRPC sub plugins of 2.0.y 

---

tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc

To remove duplicate code in each test case, this patch applies the test
fixture framework. Moreover, g_autofree macro is used for allocated
space to be freed automatically no matter test case is passed or not.
* Remove unnecessary white space
* Use `NNSTREAMER_SO_FILE_EXTENSION` instead of hard-coded extention (i.e. .so)
* Remove duplicate code in each test case
* Apply Test Fixture framework of Google Test
* `Setup()` method initializes required variables for each test and `Teardown()` releases allocated resources.

[Refactoring] Apply test fixture to TVM unit test @open sesame 07/14 09:25

---

tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc

Fix svace issue, initialize member variables in constructor.

[Svace] init member variables

---

gst/mqtt/mqttsink.c

This patch remove duplicated g_free for the message buffer(self->mqtt_msg_buf).

[Gst/MQTT/Sink] fix: Remove duplicated g_free for the message buffer

---

tests/nnstreamer_query/runTest.sh

Let's enable query test on ubuntu.
It seems that the problem that the test sometimes failed has now been solved.
* Passed test more than 10 times on CI server.

[TEST] Enable query test on ubuntu @open sesame 07/25 13:52

---

gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c

After the while loop, addrs may be a nullptr.
This causes a segmentation fault found with pdebuild/ubuntu 22.04.
CC: @gichan-jang @jaeyun-jung

query: fix null pointer access

---

ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
gst/nnstreamer/elements/gsttensor_if.c

This patch changes filter pytorch and tensorflow lites to support NNS_TENSOR_RANK_LIMIT 8
tensor_filter_pytorch's invoke does not have a problem when NNS_TENSOR_RANK_LIMIT is 4.
But when rank limit is 8, model->invoke has an exception while running the model.
Similarly, tensor_filter_tensorflow_lite's tflite_setInputDim has a problem.
TFLiteInterpreter::setInputTensorsInfo now iterates all possible ranks starting from MAX.
If NNS_TENSOR_RANK_LIMIT changed to 8, there is a case which ResizeInputTensor works while AllocateTensors does not work.
So I chagned to iterate from MIN, and Allocate Tensors inside for loop.
related: #3800 
ToDo
- Implement dimchg(tensor_transform) with NNS_TENSOR_RANK_LIMIT 8 and create test data
- Find reason why repo_* have errors when rank limit is 8
- Testcode …

[Filter] support NNS_TENSOR_RANK_LIMIT 8

---

debian/rules
ext/nnstreamer/extra/nnstreamer_python3_helper.cc

The following two commits are included:
commit 605ba3bdbee75528f917dc40267186ccbb5f89d8 (HEAD -> fix/python310)
Date:   Tue Aug 2 14:49:29 2022 +0900
join/test-case: remove undeterminism.
Because of the undeterministic nature of parallel streams,
the unittest case results sometime vary.
Specify the synchronization policy so that the results
become deterministic.
commit 7f952430cba64ca4ccbd5a82af11b85debccc31f
Date:   Tue Aug 2 13:49:23 2022 +0900
python: fix python 3.10 PyObject type errors.
From Python 3.10 python->C/C++ object transfer
has stricter type checks. Floats are no more
supported by PyLong.
Signed-off-by: MyungJoo Ham …

Fix last Ubuntu 22.04 test case issues @open sesame 8/3 08:53

---

tests/unittest_util.c
tests/unittest_util.h

- Change return errcode EPIPE to ESTRPIPE according to ml-api's ret value

[test][trivial] Fix return errcode EPIPE to ESTRPIPE

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

ssd_mobilenet v3 models handle 2034 anchor boxes 
while previous models v2 and v1 handles only 1917 boxes
thus updating the MAX value to 2034 adds support for v3 models
this update is needed for models without post-processing layer.
Signed-off-by: Aymen Sghaier <aymen.sghaier@nxp.com>

tensor-decoder: add ssd_mobilenet v3 support

---

gst/nnstreamer/tensor_query/tensor_query_serversink.c

This patch removes meaningless Caps releated actions from gst_tensor_query_serversink_start.

[Query] Remove unnecessary lines

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_common.c
gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_server.c
gst/nnstreamer/tensor_query/tensor_query_server.h
gst/nnstreamer/tensor_query/tensor_query_serversrc.c

Fix res leak in query elements.
Add destroy-cb function in query-server table to prevent mem leak.
Prevent duplicated creation of edge-handle in event callback.

[Query] fix res leak case @open sesame 08/11 21:26

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
jni/nnstreamer.mk

Do not allow to build with other compilers.
Refer to #3873 and https://lfscanning.org/reports/lfai/nnstreamer-2022-07-02-8eb54f0b-f36e-43ff-826f-80e9f251e17e.html
This is to comply with GPL-3.0 GCC Runtime Exception License of a few headers in PyTorch.

filter:pytorch allow gcc only.

---

ext/nnstreamer/extra/nnstreamer_flatbuf.h
ext/nnstreamer/extra/nnstreamer_protobuf.h
ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc
gst/nnstreamer/include/tensor_typedef.h

Do not have common data structures of ext modules in the
global-common directory. Put them in the ext modules
to avoid convoluted dependency.
Fixes #3837

proto/flat/flex buffers: reorganize common data structure. @open sesame 08/11 20:51

---

packaging/nnstreamer.spec

This patch disables the AI offloading feature on VD Cosmos infra.

[spec] Disable AI Offloading on VD Cosmos infra

---

tests/nnstreamer_grpc/runTest.sh
tests/nnstreamer_query/runTest.sh

In recent commits, pid assignment after invoking background processes
has disappeared. Revivde pid assignment so that we can kill unnecessary
processes and avoid indefinite waits.

test/query: revive pid retrieval

---

tests/nnstreamer_query/runTest.sh

tensor client of TEST 5-2 and 5-3 use same default port for listener.
Set random available port for query client.

[Query/Test] Set listener port for query client

---

tests/transform_typecast/runTest.sh

To fix xml parser error, change the test name.
Error message: Unescaped '<' not allowed in attributes values

[TEST] Change test name.

---

packaging/nnstreamer.spec
tests/nnstreamer_edge/query/runTest.sh

commit 775ba31a891f6e29bee735309f052ad795797d65 (github-fork/mosq_in_gbs)
Date:   Thu Aug 18 13:03:27 2022 +0900
test:query launch mosquitto for testing
Launch mosquitto with a random port for testing
and terminate it after testing.
commit d52222f138924cc28b30570f95411ca876699047
Date:   Thu Aug 18 11:15:42 2022 +0900
Tizen: add mosquitto at build-time for unit testing
Mosquitto is not used for building nnstreamer.
It is used for unit testing; thus, the built binaries
shouldn't have dependencies on Mosquitto.

test:query launch mosquitto for testing @open sesame @open sesame 8/31 14:32

---

tools/development/parser/grammar.y

This patch fixes the following warning about using a deprecated directive, '%pure-parser'. Note that '%pure-parser' is deprecated since Bison 2.3b (bison_min_version defined in meson.build is 2.4).
../tools/development/parser/grammar.y:372.1-12: warning: deprecated directive: ‘%pure-parser’, use ‘%define api.pure’ [-Wdeprecated]
372 | %pure-parser
| ^~~~~~~~~~~~
| %define api.pure
../tools/development/parser/grammar.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
See also:  https://fossies.org/linux/bison/NEWS

Tools/Parser: Silence a warning about using a deprecated directive @open sesame 9/1 16:25

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_client.h
tests/nnstreamer_edge/query/unittest_query.cc

- Add timeout prop to decide how much time to wait message from server.
- Default value is 0, no wait.
- Add simple unittest.

[query] Add timeout prop for tensor_query_client

---

tests/nnstreamer_filter_python3/cv2_availability.py
tests/nnstreamer_filter_python3/runTest.sh
tests/test_models/models/passThrough_CV.py

With the fear of regressions related with #3822 as
described in #3885, added a test case for multithreaded python
script of CV2.
TODO: add similar cases for converter and decoder
TODO: add negative cases
Fixes #3885

test:python3 multithreaded python script as a filter (CV2)

---

ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
ext/nnstreamer/tensor_sink/tensor_sink_grpc.c
ext/nnstreamer/tensor_source/tensor_src_grpc.c
gst/mqtt/ntputil.c
gst/nnstreamer/elements/gsttensor_repo.c
tests/nnstreamer_filter_reload/tensor_filter_reload_test.c

Fix coverity issues, remove unnecessary header includes and std-move to mem ptr.

[CodeClean] coverity issues

---

gst/nnstreamer/tensor_query/tensor_query_serversink.c

- Fix client_id type to `long long` in query_serversink.

[query] Fix client_id type to long long in query_serversink @open sesame 09/14 16:06

---

gst/nnstreamer/elements/gsttensor_transform.c

This patch fixes transform transpose rank to 3.
Increasing NNS_TENSOR_RANK_LIMIT will affect transform transpose.
It should be fixed to 3 until transform transpose supports rank N.

[transform] fix transform transpose rank to 4 @open sesame 09/08 15:56

---

packaging/nnstreamer.spec

With #3864, edgesrc/sink are added; however, in Tizen API, apps are restricted to use the allowed elements only. Add edgesrc/edgesink to that list.
ps. @gichan-jang @jaeyun-jung : please update and merge #3864 before Tizen 7 RC2. (RC1 if you can)

Edge: allow edgesrc/sink in Tizen @open sesame 9/22 20:08

---

gst/edge/edge_common.c
gst/edge/edge_sink.c
gst/edge/edge_sink.h
gst/edge/edge_src.c
gst/edge/edge_src.h
meson.build
meson_options.txt
packaging/nnstreamer.spec
tests/nnstreamer_edge/edge/runTest.sh
tests/nnstreamer_edge/edge/unittest_edge.cc
tests/nnstreamer_edge/query/unittest_query.cc
tests/unittest_util.c
tests/unittest_util.h

Edgesrc/sink support AITT as connection type.
Add unit test cases.

[EDGE] Support AITT as connection type. @open sesame 09/21 17:21

---

ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc

The preprocessor macro has a typo. Fix it.

filter/armnn: fp16 support macro fix

---

meson.build

- Fix meson config error when the 'disabled' options for mxnet is given explicitly

[trivial/build] Fix meson error when the disabled option is given

---

meson.build
meson_options.txt
packaging/nnstreamer.spec

Remove build dependency of AITT and check whether the AITT lib is installed or not at run-time for AITT test.
tests/nnstreamer_edge/edge/runTest.sh
```
...
/sbin/ldconfig -p | grep libaitt.so >/dev/null 2>&1
if [[ "$?" != 0 ]]; then
echo "AITT lib is not installed. Skip AITT test."
...
```
1. Build test: [* ]Passed [ ]Failed [*]Skipped
2. Run test: [* ]Passed [ ]Failed [*]Skipped

[AITT] Remove AITT build dependency

---

tests/nnstreamer_edge/edge/runTest.sh

This patch fixes nnstreamer_edge test code.

[edge] fix test code's multifilesink

---

ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.cc
ext/nnstreamer/extra/nnstreamer_protobuf.cc
ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc
gst/nnstreamer/elements/gsttensor_converter.c
gst/nnstreamer/elements/gsttensor_crop.c
gst/nnstreamer/elements/gsttensor_demux.c
gst/nnstreamer/elements/gsttensor_transform.c
gst/nnstreamer/include/nnstreamer_plugin_api_util.h
gst/nnstreamer/include/tensor_typedef.h
gst/nnstreamer/nnstreamer_plugin_api_impl.c
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
gst/nnstreamer/tensor_filter/tensor_filter_common.c
tests/common/unittest_common.cc
tests/nnstreamer_decoder/unittest_decoder.cc
tests/nnstreamer_plugins/unittest_plugins.cc

Move enum flag - tensor_format into tensors-info struct.
To pass flexible tensors to filter sub-plugins, we should indicate tensor format in tensors-info struct, not tensors-config. Internally tensors-config struct is used for caps negotiation.
TODO: need discussion, should we separate format in each tensor info, so that each mem chunk can express its format. (then, nnstreamer will combine memories: static+flexible in gst-buffer.)

[Common] tensor format in struct

---

gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter_common.c
gst/nnstreamer/tensor_filter/tensor_filter_common.h
tests/meson.build
tests/nnstreamer_latency/unittest_latency.cc

Hello all,
This is a proposal for implementation of filter latency estimate and reporting in the pipeline.
It should help with #1146 for tensor filter element that is the main contributor to the latency.
Tensor filter executes inferences that may take long time depending on the model complexity and the compute capabilities of the platform. When inference duration is long, it happens that some downstream buffers are dropped because associated timestamp is too far in the past.
It results in a shaky pipeline buffer rate and for instance occurences of error messages from the sink when operated in live mode (sync=TRUE): 'There may be a timestamping problem, or this computer is too slow.'
Tensor filter implementation already has the option to computes latency estimates when its element property …

[filter/core] Add tensor filter latency reporting to the pipeline @open sesame 10/27 23:11

---

ext/nnstreamer/tensor_decoder/tensordec-pose.c

Under some circumstances, setpixel() is called with y==data.height which causes a SEGV. While this might be a rounding error in the caller draw(), the added code gracefully ignores such out-of-bound pixels gracefully.
Steps to reproduce with modified nnstreamer example (different media):
```
souphttpsrc location=https://storage.googleapis.com/ts-video-test/test1_vlog.mp4 \
! qtdemux ! decodebin ! videoconvert \
! videoscale ! videorate ! video/x-raw,width=640,height=360,format=RGB \
! tee name=nnt \
nnt. \
! queue \
! videoscale ! videorate ! video/x-raw,width=257,height=257,format=RGB \
! tensor_converter \
! tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 \
! tensor_filter framework=tensorflow-lite \
accelerator=true:gpu,npu,cpu \ …
```

[decoder/pose] Fix SEGV, ignore pixel when coordinates are out of bounds. @open sesame 11/10 08:29

---

ext/nnstreamer/tensor_filter/meson.build

- Add `-Wno-unused-parameter` args because recent pytorch contains unused variables in its source.

[build] Add compile arg for pytorch subplugin

---

.gitignore
Documentation/getting-started-macos.md
meson.build

- Add alternative dependency to find libtorch through cmake during configuration
- Update the tutorial for building on macOS as tested on my ARM64 Monterey machine
I've made a fair amount of changes to the macOS tutorial to make it clearer and shorter, hopefully that'll be OK! 🙂
This follows our discussion on issue #3953 .

Fix PyTorch support for macOS @open sesame 11/17 17:21

---

ext/nnstreamer/tensor_filter/meson.build

- In cross build, found tflite lib could have different arch with target system. Disable this feature for cross build.
- This fixes #3964

[build] Disable tflite-custom in cross build

---

debian/control
debian/nnstreamer-tensorflow-lite.install
debian/nnstreamer-tensorflow.install
debian/rules

Let's not build obsolete tensorflow1.x subplugins
and remove them from official PPA build.
Fixes #3969

debian: remove tensorflow1 from PPA

---

gst/nnstreamer/elements/gsttensor_debug.c
gst/nnstreamer/elements/gsttensor_debug.h
gst/nnstreamer/elements/meson.build
gst/nnstreamer/registerer/nnstreamer.c
jni/nnstreamer.mk

We introduce the new element of nnstreamer, tensor_debug.
Tensor_debug allows pipeline writers and application writers to look at details of tensor stream properties and potentially the performance profiling information of tensor streams at a given point of a pipeline.
This addresses #3910

New Element: tensor_debug tensor stream debugger

---

.github/workflows/risc-v.yml
gst/nnstreamer/nnstreamer_log.c
meson.build
meson_options.txt
tools/development/parser/meson.build

This enables Github-Action for RISC-V build & unit tests.
commit 48973d86af8669d7bef2982a897a900cd8eb1714 (HEAD -> action/riscv, github-fork/action/riscv)
Date:   Thu Nov 24 16:47:52 2022 +0900
log: control dependency on execinfo with find_library
Like Android, Alpine linux does not ahve execinfo, too.
Determine whether to use execinfo or not based on
find_library results.
commit 1ed71a72e19849bd114872aa8c96f411f1b3fbaf
Date:   Thu Nov 24 13:46:19 2022 +0900
github-action: Add RISC-V build
This tries to enable RISC-V build in github-action
based on https://github.com/marketplace/actions/run-on-architecture-riscv64-alpine
In order to build …

Initial RISC-V Github-Action Infra

---

.github/workflows/ubuntu_clean_meson_build.yml

In the case of Ubuntu 22.04, the below error occurs since unmet dependencies. This patch fixes this bug.
- libunwind-14-dev : Breaks: libunwind-dev but 1.3.2-2build2 is to be installed

github-action: Add libunwind-dev for jammy (22.04)

---

README.md

This patch replaces the link for the SSDC 2019 page, which exists no more (404 Not Found), in README.md with the YouTube link.
Signed-off-by: Wook Song <wook16.song@samsung.co

README: Replace the broken link for the SSDC 2019 page @open sesame 12/3 19:11 

---

ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
tests/nnstreamer_filter_lua/runTest.sh

This patch allows to declare TensorInfo not using full dimension. 
It will be used for increasing NNS_TENSOR_RANK_LIMIT.
See also : #3987 

[Lua] Allow to declare TensorInfo not using full dimension

---

gst/nnstreamer/tensor_query/tensor_query_common.c

Since the tensor query does not send data through the mqtt, remove unnecessary enum.

[Query] remove mqtt connection type enum

---

gst/nnstreamer/include/nnstreamer_plugin_api_util.h
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
tests/common/unittest_common.cc
tests/nnstreamer_plugins/unittest_plugins.cc
tests/nnstreamer_sink/unittest_sink.cc

This patch adds common function for tensors dimension compare.
From https://github.com/nnstreamer/nnstreamer/pull/3987#pullrequestreview-1207979064

[Common] Add common utils for tensors dimension compare @open sesame 12/15 14:35

---

gst/nnstreamer/nnstreamer_conf.c

The result of 'sizeof (dump_list_type) / sizeof (nnsconf_type_path)' is 4 but dump_list_str array has only 3 items. Because of this reason, it can occur the array overflow issue. This patch fixes this issue.

[Svace] Fix the array overflow issue

---

.github/workflows/risc-v.yml

Try Ubuntu instead of alpine for riscv64 tests
Alpine linux provides a few developmental packages quite different from Ubuntu/Tizen, requiring too much exception handling in unit tests.

riscv64 alpine linux --> ubuntu

---

packaging/nnstreamer.spec

Since ARMNN is deprecated in Tizen, this patch disables the armnn_support option.

[spec] Disable armnn_support option as default

---

packaging/nnstreamer.spec

Because the file path for build has been changed to relative path, change base directory for lcov.
This patch fixes failure of coverage generation.

[lcov] Change base directory

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

- Set the conf and iou threshold values to follow the upstream https://github.com/ultralytics/yolov5.
- The yolov5 models released by github.com/ultralytics/yolov5 have different output semantics:
- the output of tflite and tf models should be scaled to input image size.
- torchscript and others return scaled output value.
- This patch support those two semantics by add option3:
- option1=yolov5 ...  option3=0 ... (default) for tflite models
- option1=yolov5 ...  option3=1 ... for other models
1. for tflite model
<pre>
gst-launch-1.0 filesrc location=bus.jpg ! jpegdec ! videoscale ! videoconvert ! \ …

[decoder/yolov5] Support scaled-output model for yolov5 bounding box decoder @open sesame 12/20 11:25

---

tests/cpp_methods/cppfilter_test.cc
tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc

This patch changes to use NNS_TENSOR_RANK_LIMIT instead of hardcoded dimension. 
It will be used for increasing NNS_TENSOR_RANK_LIMIT.

[tests] change hardcoded dimension compare to use NNS_TENSOR_RANK_LIMIT

---

.github/workflows/ubuntu_clean_meson_build.yml

Before resolving #3979, this PR applies a matrix strategy in our CI/CD workflow for Ubuntu as 'ubuntu-latest' is currently migrating from 20.04 to 22.04 [1].  You can see the result [here](https://github.com/wooksong/nnstreamer/pull/3).
[1] https://github.com/actions/runner-images#ongoing-migrations

GitHub/Actions: Use a matrix strategy in the workflow for Ubuntu

---

.github/workflows/ubuntu_clean_meson_build.yml

This patch makes the unit test cases defined in the meson build script run.
Signed-off-by: Wook Song wook16.song@samsung.com
1/12 unittest_common                         OK       0.47 s 
2/12 unittest_sink                           OK      25.91 s 
3/12 unittest_plugins                        OK      17.34 s 
4/12 unittest_if                             OK       5.24 s 
5/12 unittest_rate                           OK       0.37 s 
6/12 unittest_latency                        OK      13.07 s 
7/12 unittest_filter_single                  OK       0.01 s 
8/12 unittest_join                           OK       0.62 s 
9/12 unittest_src_iio                        OK      10.55 s 
10/12 unittest_tizen_custom                   OK       0.01 s 
11/12 unittest_tizen_custom-set               OK …

GitHub/Actions: Enable binary tests defined in the meson script

---

tests/gstreamer_join/runTest.sh

Fix join runTesh pipeline.
- Increase the number of buffers : Before the multifilesink saves four files, the pipeline receives the EOS and stops. This is prevented by increasing the number of buffers.
- Change tensor mux sync mode: Set the buffer used for comparison of tensor_if slowly enough and sync on this buffer.
- Enable timestamp.

[Join] Fix join run test pipeline.

---

gst/nnstreamer/include/nnstreamer_plugin_api_filter.h

This PR is about revising the comments in the ```nnstreamer_plugin_api_filter.h``` as follows:
- Correct a typo and weird indentations
- Update out-of-date comments ```s/tensor_filter.c/tensor_filter_common.c/g```

Filter/API: Update out-of-date comments

---

gst/nnstreamer/nnstreamer_plugin_api_impl.c
tests/nnstreamer_sink/unittest_sink.cc

- Fix assertion checking the NNS_TENSOR_SIZE_LIMIT
- Add simple testcases for tensor_mux and tensor_merge when the num_tensors equals 16
1. Build test: [X]Passed [ ]Failed [*]Skipped
2. Run test: [X]Passed [ ]Failed [*]Skipped

[fix] Fix NNS_TENSOR_SIZE_LIMIT check in collectpad

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc

- The output buffer address may change after the first invoke.
- To handle this case, Memcpy the output from tflite interpreter at the first invoke.

[fix][tensor_filter] Fix the first output with garbage value with tflite

---

gst/nnstreamer/include/meson.build
gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h
packaging/nnstreamer.spec

[API] Add structure for tensor_trainer's sub-plugin
- Create nnstreamer_plugin_api_trainer.h
- Add GstTensorTrainerFramework to define tensor_trainer sub-plugin
- Add GstTensorTrainerProperties to send tensor_trainer properties
Signed-off-by: hyunil park <hyunil46.park@samsung.com>
Related:
https://github.com/nnstreamer/nnstreamer/pull/3949
https://github.com/nnstreamer/nnstreamer/pull/3986
https://github.com/nnstreamer/nntrainer/pull/2059

[API] Add structure for tensor_trainer's sub-plugin @open sesame 12/27 11:50

---

gst/nnstreamer/tensor_query/tensor_query_server.c
gst/nnstreamer/tensor_query/tensor_query_server.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.c

Add new function to set query server caps.
This patch prevents the race condition of the query server caps.
*Need group SR with https://github.com/nnstreamer/nnstreamer-edge/pull/147 to fix armv7l test failure.

[Query] Prevent overwriting of the query server caps

---

gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h

Change callback parameter name of GstTensorTrainerFramework 
- Change 'train' and 'invoke' to 'start' and 'push_data' respectively

[API][trainer] Change callback parameter name of GstTensorTrainerFramework

---

gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h

[API][trainer] Change type of train_complete to int 
- Sub-plugin using c++ cannot access this type
<details><summary> error </summary>
<br/> 
tensor_trainer_nntrainer.cc:520:49: error: 'GstTensorTrainerFramework' {aka '_GstTensorTrainerFramework'} has no non-static data member named 'start'
[  539s]   520 |   .getFrameworkInfo = nntrainer_getFrameworkInfo};
</details>

[API][trainer] Change type of train_complete to int

---

debian/nnstreamer-single-dev.install

[API][trainer]  Packaging nnstreamer_plugin_api_trainer.h into debian
- Packaing header file to nnstreamer-single-dev.install

[API][trainer] Packaging nnstreamer_plugin_api_trainer.h into debian

---

gst/nnstreamer/elements/gsttensor_converter.c
gst/nnstreamer/elements/gsttensor_converter_media_info_video.h

This fix makes tensor_converter compatible with vaapih264dec and adds a WARNING if incoming video caps views>1.
The need for this workaround and warning has been surfaced because of a bug in vaapih264hdec https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1712 which provides `video/x-raw, ... multiview-mode=(string)mono, ... views=(int)2`. The caps restriction of `views=(int)1` prohibits the successful negotiation.
This has been tested with a mono video but not with a truly stereoscopic video which might need further handling in the buffer processing.

[tensor_converter] Remove a seemingly unnecessary caps attribute views=1

---

tests/tizen_sensor/unittest_tizen_sensor.cc

After upgrading the version of GStreamer to 1.22.0, the test case of the Tizen sensor filter failed. This is mainly because `gst_parse_launch()` can return a non-NULL value even though the error is set. So `error` should be checked first before using the return value of `gst_parse_launch()`. This code fixes this bug.
* Link: https://quickbuild.tizen.org/build/153434/gbs_reports/standard-armv7l
```bash
...
[  196s] [ RUN      ] tizensensorAsSource.virtualSensorCreate07_n
[  196s] 
[  196s] (unittest_tizen_sensor:272725): GStreamer-CRITICAL **: 01:09:02.734: 
[  196s] Trying to dispose element tensorsink1, but it is in READY …
```

[Test] Fix the test failure

---

gst/nnstreamer/include/nnstreamer_plugin_api.h
gst/nnstreamer/include/tensor_typedef.h
gst/nnstreamer/nnstreamer_plugin_api_impl.c
tests/nnstreamer_sink/unittest_sink.cc

- Add header structure for 16+th tensors
- Those tensors would be packed into 16th GstMemory in a GstBuffer.
- Define NNS_TENSOR_SIZE_EXTRA_LIMIT as 200
- Add an init API `gst_tensors_extra_init`
- Add an API `gst_tensors_get_nth_memory` which returns GstMemory from given GstBuffer with index larger than 16.
unittest:
- Add a simple TC which push and get 20 tensors.
- Note that the pipeline used in this TC does not care about the caps or negotiation.
TODO:
- Add APIs for `GstTensorInfo` of 16+th tensors. These will be used in each nnstreamer element for configuration and negotiation.
- Implement proper behavior of tensor_mux and tensor_merge.
Signed-off-by: Yongjoo Ahn …

[common] Add header structure for 16+th tensors and simple APIs

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_trainer.h

Change the condition for generating the output tensor   
- An output tensor is created when there is a epoch result
- Remove push_output property
- output type is changed to float64
- Add gst_buffer_unref() in chain function to unref input gstbuffer

[tensor_trainer] Change the condition for generating the output tensor

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_trainer.h
gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h

Rename some variable to use nouns instead of verbs
- Rename 'train' and 'valid' to 'training' and 'validation'

[API][trainer] Rename some variable to use nouns instead of verbs

---

gst/nnstreamer/tensor_query/tensor_query_common.c
tests/nnstreamer_edge/query/unittest_query.cc

Remove UDP connection type because we don't have plan to support it for tensor query.

[Query] Remove UDP connection type from tensor_query @open sesame 03/16 14:27

---

.github/workflows/risc-v.yml
.github/workflows/ubuntu_clean_meson_build.yml

Remove ubuntu 18.04 build since this distro has benn deprecated.
refer:
```
Annotations
2 errors and 5 warnings
build (ubuntu-18.04)
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04 or ubuntu-22.04 (ubuntu-latest). For more details, see https://github.com/actions/runner-images/issues/6002 build (ubuntu-18.04)
GitHub Actions has encountered an internal error when running your job.
```

[GithubAction] Remove ubuntu 18.04 build

---

gst/nnstreamer/elements/gsttensor_transform.c

---
Change gsttensor_transform.c to support per-channel arithmetic op w/ORC
Resolves: #123
See also: #456, #789
When I tested performance of arithmetic per-channel op w/ORC, results is 
3:256:256:1 -> 8ms
256:256:3:1 -> 51micro seconds
without ORC
3:256:256:1 -> 10ms

support tensor trasnform arithmetic mode per-channel op w/ORC

---

gst/nnstreamer/include/nnstreamer_plugin_api_util.h
gst/nnstreamer/include/tensor_typedef.h
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
tests/common/unittest_common.cc
tests/nnstreamer_sink/unittest_sink.cc

- Add a pointer of GstTensorInfo in GstTensorsInfo struct. And name it  as "extra"
- Add create and free APIs for extra info
- Fix get/parse utils for type, dim, name of tensor_info
- Fix tests that check NNS_TENSOR_SIZE_LIMIT in get/parse type/dim/name of tensor_info

[common] Add extra info for 16+th tensors 

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_trainer.h

Add epochs property   
- Add epochs property to inform the total amount of data subplugin can receive
- tensor_trainer should receive total number of samples (num-training-samples + num-validation-samples) * epochs
- Change data type of some properties from uint to int64
- Modify Example launch

[tensor_trainer] Add epochs property

---

gst/datarepo/gstdatareposrc.c
gst/datarepo/gstdatareposrc.h
gst/datarepo/meson.build

- Add supportable caps
other/tensors, video/x-raw, audio/x-raw, text/x-raw, application/octet-stream
image/png, image/jpeg, image/tiff, image/gif
- Add get_caps and set_caps function for caps negotiation
- Get media mimetype and media size after set_caps
a. get video size (Byte/frame)
b. get audio size (Bps)
c. get tensor type size
- Add function to read file from the MLOps Data repository
a. In case of tensors, tensors data are added to a single gstbuffer.
b. In case of image files, a image file is added to a single gstbuffer,
Images are numbered files
c. In other cases, data of size calculated in set_caps is added to a singgle gstbuffer

[datareposrc] Add supportable caps and function to read file

---

gst/datarepo/gstdatareposrc.c
gst/datarepo/gstdatareposrc.h

Add start/stop-sample-index and epochs property
- Add start-sample-index and stop-sample-index for setting range of files or samples to read (set none, set both, or set one)
- Add epochs property to set number of repetitions, datareposrc read range of files or samples for epochs
- Add gst_base_src_set_live and move start function to create function.
a. datareposrc can get media type and size after set_caps(), but set_caps is completed after PAUSED_TO_PLAYING.
b. filling the buffer should be pending until set_caps().
c. datareposrc is a live source.

[datareposrc] Add epochs and start/stop-sample-index property @open sesame 04/20 09:25

---

gst/nnstreamer/elements/gsttensor_mux.c
gst/nnstreamer/nnstreamer_plugin_api_impl.c
tests/nnstreamer_sink/unittest_sink.cc

- Update `gst_tensor_time_sync_buffer_from_collectpad` to support extra tensors
- Fix `gst_tensors_config_from_structure` to support extra tensors
- Add a testcase of tensor_mux with 20 sinkpads

[tensor_mux] Fix tensor_mux to support more than 16 sinkpads @open sesame 4/18 12:55

---

gst/datarepo/gstdatareposrc.c
gst/datarepo/gstdatareposrc.h

If the value is true, samples index are shuffled, default value is true.
The sample index is the order in which samples are stored in the file, starting from 0.

[datareposrc] Add is-shuffle property

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h

- Limit the number of samples to an int range
- bug-fix: When passing values to a sub-plugin in an arm 32bit environment, invalid values are passed.
- Add function to Check invalid param
- Remove default framework
- Change some default value

[API][tensor_trainer] Change type of structure member variable

---

gst/datarepo/gstdatareposrc.c
gst/datarepo/gstdatareposrc.h

- Tensors in a sample are read into gstBuffer according to input sequence.
- Only read the set tensors among all tensors in a sample.
- It is for other/tensors and default value is NULL.
```
e.g, if a sample has '1:1:1:1', '1:1:10:1', '1:1:784:1' and each index is '0,1,2' , 
"tensors-sequence=2,1" means that only '1:1:784:1' then '1:1:10:1' are read. 
```
further explanation
```
I modify MNIST dataset that have two features and labels in a sample.
so..
offset and sample_offset(byte size) are from 0.
if the size of one sample is 6352 and num_tensors is 4, dimensions are  '1:1:784:1' , '1:1:10:1',
'1:1:784:1' and '1:1:10:1' with float32.
the offset of the second sample is as follows.
-------------------------------------------------
sample_offset: 6352
tensors index: [ 0    | 1    | 2    | …
```

[datareposrc] Add tensor-sequence property @open sesame 4/21 16:51

---

gst/mqtt/mqttsink.c

Change string copy to avoid gcc-12 build error.

[MQTT] Change string copy @open sesame 04/28 16:12

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_trainer.h
tests/nnstreamer_trainer/unittest_trainer.cc

- Get TensorsInfo from negotiated caps
- Remove input-type and input-dim property
1. Build test: [*]Passed []Failed []Skipped
2. Run test: [*]Passed []Failed []Skipped

[tensor_trainer] Get TensorsInfo from negotiated caps instead of property

---

gst/nnstreamer/nnstreamer_plugin_api_util_impl.c

Clearly allocate extra info array in tensors-info struct, and remove unnecessary log line.

[Common] allocate extra info

---

gst/datarepo/meson.build
gst/meson.build
meson.build
meson_options.txt

Datarepo has its own unique dependency.
Thus, make datarepo optional at build so that
we can cut the dependency.
It's set "enabled by default" because most
releases will be using it anyway.

datarepo: dependency management.

---

gst/nnstreamer/nnstreamer_plugin_api_util_impl.c

Remove unnecessary log-print, most pipelines does not have extra info and dont need releasing extra info.

[Common] condition to release extra info

---

packaging/nnstreamer.spec

For test coverage, add missed testcases when running unittest in tizen build.

[Test] missed testcases in spec file

---

ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc

Allow tensor_filter to be configured with smaller number of output tensors than PyTorch returns native. This is useful e.g. when my Yolov7 converted model (TorchScript) has 4 output tensors, but I am really only interested in in the 1st. Without this fix, the code would crash with a memory overwrite in `TorchCore::serializeOutput` if the number of configured output tensors is smaller than the actual TorchScript model provides..

[Filter] PyTorch, ignore extra output tensors @open sesame 05/11 10:51

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_trainer.h
gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h

commit 1:
[API][tensor_trainer] Add event notifier and getStatus callback pointer
Add GstTensorTrainerEventNotifier to get event from subplugin
- subplugin must send event to tensor_trainer with this notifier by internal API
- Add GstTensorTrainerEventType
- Add new internal API: nnstreamer_trainer_notify_event(notifier, event_type, data)
Add getStatus callback pointer to GstTensorTrainerFramework.
- Call this to get status of subplugin
commit 2:
[tensor_trainer] Save the stats information of the model to output tensors
Whenever one of the epochs is completed, the stats information of the model being trained in subplugin is stored in the output tensor.
- Apply getModelRunStas to get stats from model being trained in subplugin
- Add new internal API(nnstreamer_trainer_notify_event()) to …

[tensor_trainer] Add event notifier, getStatus and new function to save the stats information of the model to output tensors

---

gst/datarepo/gstdatareposink.c
gst/datarepo/gstdatareposrc.c
gst/datarepo/gstdatareposrc.h
tests/nnstreamer_datarepo/unittest_datareposink.cc
tests/nnstreamer_datarepo/unittest_datareposrc.cc

- For caps negotiation, use the caps of the JSON file
- Remove supportable caps and add 'ANY'
- Add caps property for setting caps of unregistered file (have not JSON)
- Add unittest

[datareposrc] For caps negotiation, use the caps of the JSON file @open sesame 05/18 13:05

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

- Fix to calculate correct distance value between centroid and box
- Initialize tracking_id with 0 for yolov5 decode mode

[decoder] Fix logic error in box tracking

---

gst/nnstreamer/include/nnstreamer_cppplugin_api_filter.hh
gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c
gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
tests/meson.build
tests/nnstreamer_filter_custom/unittest_filter_custom.cc
tests/nnstreamer_sink/unittest_sink.cc

Change custom-easy filter version from v0 to v1
*todo: Support dynamic invoke of custom-easy filter

[Fillter] Change custom-easy filter version from v0 to v1 

---

gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
tests/common/unittest_common.cc

This patch fixes `gst_tensor_dimension_is_equal`
and adds unittests.

[Common] fix tensor dimension compare util

---

gst/nnstreamer/include/nnstreamer_plugin_api.h
gst/nnstreamer/nnstreamer_plugin_api_impl.c
gst/nnstreamer/tensor_filter/tensor_filter.c
tests/nnstreamer_filter_tensorflow2_lite/unittest_filter_tensorflow2_lite.cc
tests/nnstreamer_sink/unittest_sink.cc

- Remove unused argument of GstTensorsInfo.
- Fix used lines.
- Apply clang-format-15 to the file `unittest_sink.cc`

[util] Fix the signature of gst_tensor_buffer_get_nth_meory

---

gst/nnstreamer/include/tensor_typedef.h

- Making the total size limit to be 256 (16 + 240)
TODO: Set NNS_TENSOR_SIZE as 256 and update other source codes accordingly

[common] Increase tensor_size_extra_limit to 240

---

gst/nnstreamer/nnstreamer_plugin_api_util_impl.c

Fix util function, getting tensor size of extra tensor.

[Common] data size of extra tensor

---

debian/nnstreamer-core.install
ext/nnstreamer/tensor_decoder/meson.build
ext/nnstreamer/tensor_decoder/tensordec-tensor_region.c
jni/nnstreamer.mk
packaging/nnstreamer.spec

This is a tensor_decoder sub-plugin tensor_region. It takes input from tensor_filter's mobilenet_ssd model and generates cropping info (coordinates of upper left corner of crop_box, its width and height) for tensor_crop element.
It currently accepts 4 options:
option 1: number of cropped regions required (by default 1)
option 2: labels path
option 3: ( for mobilenet_ssd) box_priors.txt path
option 4: input video's width and height (by default, 300:300)

Tensor_decoder subplugin: tensor_region

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

Fix data type of distance value in 'g_array_set_size' (gint -> guint64)

[Fix] fix svace issue.

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

- Fix overflow before widen (distance value in 'g_array_set_size' func).

[Fix] fix svace issue. @open sesame 06/21 17:06

---

gst/nnstreamer/nnstreamer_plugin_api_impl.c

Param error case, validate tensor-info before appending new memory.

[Common] validate tensor-info

---

gst/nnstreamer/include/tensor_typedef.h
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
tests/common/unittest_common.cc

Add magic to tensor-meta, this indicates given memory block is flexible tensor.

[Common] magic number for flex-tensor

---

ext/nnstreamer/tensor_filter/meson.build
packaging/nnstreamer.spec

This patch fixes a GBS build error caused by https://github.com/nnstreamer/nnstreamer/pull/4007 on the SNPE
sub-plugin for Tizen.
See also: #4127

Dist/Tizen: Fix a GBS build error due to #4007

---

debian/rules

Modify to run nnstreamer_datarepo tests

[debian/rules] Add tests path of nnstreamer_datarepo to debian rules

---

gst/nnstreamer/elements/gsttensor_decoder.c
gst/nnstreamer/nnstreamer_plugin_api_impl.c
gst/nnstreamer/tensor_common.h
tests/nnstreamer_decoder_boundingbox/config_file.0
tests/nnstreamer_decoder_boundingbox/config_file.1
tests/nnstreamer_decoder_boundingbox/config_file.2
tests/nnstreamer_decoder_boundingbox/runTest.sh

This includes an API named gst_tensor_parse_config_file defined in nnstreamer_plugin_api_impl.c.
For any plugin, install a new property for defining the config file path and use the API as follows:
```
case PROP_CONFIG:
{
const gchar *config_path = g_value_get_string (value);
gst_tensor_parse_config_file (config_path, object);
break;
}
```
The config file is defined as:
```
mode=bounding_boxes
option1=mobilenet-ssd
option2=coco_labels_list.txt
option3=box_priors.txt
option4=640:480
option5=300:300
```
And the property can be used as:
`.. ! tensor_decoder config-file=configFile ! ..`

Config file for properties

---

gst/datarepo/gstdatareposink.c
gst/datarepo/gstdatareposink.h
tests/nnstreamer_datarepo/unittest_datareposink.cc

- To add memory to gstbuffer by number of flexible tensors when read sample in datareposrc,
sample_offset, tensor_size, and tensor_count field are added to the JSON file
- Add unit test
- Reference
* If caps of sink pad is flexible, the input gstBuffer is saved as a flexible tensor
* The size of the input gstBuffer is stored as sample_offset field in JSON file and
it will be used when shuffle operation in datareposrc
* Each flexible tensor size is stored as tensor_size field in JSON file and
it will be used with gst_buffer_append_memory() in datareposrc
**Reference**
Test with "other/tensors,format=flexible"
```
gst-launch-1.0 videotestsrc num-buffers=3 ! videoconvert ! videoscale …
```

[datareposink] Add function to write flexible tensors

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

- Skip nms when the size of given array is 0

[trivial] Fix nms in bounding_box decoder

---

gst/datarepo/gstdatareposink.c

Fix res leak case if gst-memory mapping is failed.

[DataRepo] handle error case

---

gst/nnstreamer/nnstreamer_plugin_api_impl.c
gst/nnstreamer/tensor_common.h

- Add gst_tensor_pad_get_format()
- Replace gst_tensor_pad_caps_is_flexible() function to macro.
- Add gst_tensor_pad_caps_is_static and gst_tensor_pad_caps_is_sparse macro
review history: #4141

[Common] Add new API to get tensor format of current pad caps

---

packaging/nnstreamer.spec

This patch removes the armcl dependency from the Tizen packaging.

[Spec] Remove armcl dependency

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
gst/nnstreamer/tensor_filter/tensor_filter_common.c
gst/nnstreamer/tensor_filter/tensor_filter_single.c
tests/nnstreamer_filter_single/unittest_filter_single.cc

Let tensor_filter_common handle extra tensors
- Extend array length for layout and ranks
- Replace accessing tensor_info with array index with util func `gst_tensors_info_get_nth_info`
- Extend the array length of out GstTensorMemory to support invoke of many in/out tensors model with filter_single
- Add testcases for filter_single with 32 in/out tensors model 
- Add calls for `gst_tensors_info_free` (fix mem leak)

[tensor_filter] Increase num tensors for tensor_filter_single

---

gst/nnstreamer/elements/gsttensor_demux.c
gst/nnstreamer/nnstreamer_plugin_api_impl.c
tests/nnstreamer_sink/unittest_sink.cc

- Let tensor_demux handle tensors # > 16
- Let `gst_tensor_time_sync_buffer_from_colletpad` support extra tensors as its input
- Add a TC to test MAX extra tensors with tensor_mux
- Add a TC to test tensor_demux handling extra tensors

[demux] Let tensor_demux handle tensors # > 16

---

gst/datarepo/gstdatareposrc.c
gst/datarepo/gstdatareposrc.h
tests/nnstreamer_datarepo/unittest_datareposrc.cc

- If the tensor format of the caps of the JSON file is flexible,
Reads a sample using the flexible meta information (sample_offset, tensor_size, tensor_count)
of the JSON file and appends memory to GstBuffer as many as the number of flexible tensors.
- Add unit test
- Add checking if it is a flexible tensor after writing data to GstMemory
- Reference
* The start offset for reading is sample_offset(sample size).
* Save each flexible tensor stored in a sample to a gstbuffer according to each
tensor_size, tensor_size can get tensor_size field in JSON file.
* A shuffled index is mapped to an index of sample_offset field in JSON file.
* A shuffled index is also mapped to an index of tensor_count field in JSON file
* The index value is a number of cumulative tensors, so it is mapped to an index …

[datareposrc] Add function to read flexible tensors

---

ext/nnstreamer/tensor_decoder/tensordec-tensor_region.c

Initially, the increment size of the output buffer pointer while storing the cropping info was 4 times the required value.

[tensor_region] fix memcpy to out buffer

---

gst/datarepo/gstdatareposink.c
gst/datarepo/gstdatareposink.h
gst/datarepo/gstdatareposrc.c
gst/datarepo/gstdatareposrc.h
tests/nnstreamer_datarepo/unittest_datareposink.cc
tests/nnstreamer_datarepo/unittest_datareposrc.cc

- Add writing sparse tensors to datareposink
To add memory to gstbuffer by the number of sparse tensors when reading a sample in datareposrc,
sample_offset, tensor_size, and tensor_count fields are added to the JSON file
- Add reading sparse tensors to datareposrc
If the tensor format of JSON file is sparse, read a sample using the JSON meta information
(sample_offset, tensor_size, tensor_count) and append memory to GstBuffer as many as the number
of sparse tensors.
- Add unit test
- bug fix about shuffle index

[datarepo] Add function to read and write sparse tensors @open sesame 07/24 16:00 

---

.github/workflows/macos.yaml

Don't install gstreamer-plugins.
Warning messages:
```
Warning: Formula gst-plugins-base was renamed to gstreamer.
Warning: Formula gst-plugins-good was renamed to gstreamer.
```
Related issue: https://github.com/Homebrew/brew/issues/15488
Bug report from the issue:  "There is technically a bug here in that the dependency collector doesn't recognise multiple renames into one formula as being a single formula, so it tries to install gstreamer multiple times."

[GitHub Action] Fix macOS build failure

---

Documentation/getting-started-meson-build.md
gst/datarepo/meson.build
gst/meson.build

If there is no libjson-glib-dev package, occur meson build error below:
```
$ meson build
...
Program sh found: YES (/usr/bin/sh)
Run-time dependency json-glib-1.0 found: NO (tried pkgconfig and cmake)
gst/datarepo/meson.build:7:0: ERROR: Dependency "json-glib-1.0" not found, tried pkgconfig and cmake
```

[Documentation] Add libjson-glib-dev package dependency

---

Documentation/getting-started-tizen.md

Tizen reference link has been changed and updated with the latest link.
- How to install GBS : https://docs.tizen.org/platform/developing/installing/
- How to build with GBS : https://docs.tizen.org/platform/developing/building/
```

[Documentation] Fix tizen reference link

---

gst/datarepo/gstdatareposrc.c
gst/datarepo/gstdatareposrc.h
tests/nnstreamer_datarepo/unittest_datareposrc.cc

datareposrc push GstBuffer according to framerate when sink element sets sync=true
- Set TIMESTAMP to GstBuffer
- Add function to calculate running_time for one frame

[datareposrc] Push GstBuffer according to framerate @open sesame 08/03 10:15

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_trainer.h
gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h
tests/nnstreamer_trainer/unittest_trainer.cc

- Add model_load_path to load an existing model to use for training a new model
- Add model_load_path property to tensor_trainer
Related PR : (No dependency) https://github.com/nnstreamer/nntrainer/pull/2258 (review please)

[tensor_trainer] Add load_model_path to GstTensorTrainerProperties

---

gst/datarepo/gstdatareposink.c
tests/nnstreamer_datarepo/unittest_datareposrc.cc

Code clean, fix svace issues.
1. prevent duplicated free case.
2. handle returned val when mapping incoming buffer.

[Svace] fix svace issue

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
ext/nnstreamer/tensor_decoder/tensordec-tensor_region.c
ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
gst/nnstreamer/elements/gsttensor_transform.c
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
tests/common/unittest_common.cc
tests/nnstreamer_plugins/unittest_plugins.cc
tests/nnstreamer_sink/unittest_sink.cc
tests/nnstreamer_sparse/runTest.sh
tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc

This PR removes padded value of dimensions.
Dimension in GstTensorInfo is 0 by default.
related to : https://github.com/nnstreamer/api/pull/338

[tensor] remove padded value of dimensions (0-init) @open sesame 08/03 15:25

---

gst/edge/edge_sink.c
gst/edge/edge_sink.h

If wait-connection prop is set true, wait until edgesrc is connected and don't drop the buffers.
Wait https://github.com/nnstreamer/nnstreamer-edge/pull/170

[Edge] Add wait connection prop @open sesame 08/09 18:27

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

Let's not ignore labels that may have larger score after the first label exceeding the threshold.
Fixes #4137

fix: decoder/bounding-box mobilenet threshold logic @open sesame 8/9 17:02

---

tests/nnstreamer_decoder_python3/runTest.sh
tests/nnstreamer_merge/runTest.sh
tests/nnstreamer_repo_lstm/runTest.sh
tests/transform_clamp/runTest.sh
tests/transform_stand/runTest.sh
tests/transform_transpose/runTest.sh

If the test is not available (e.g., numpy is not available or the tested feature is not built), don't test.

test: script updated for better fault handling.

---

gst/edge/edge_common.h
gst/edge/edge_sink.h
gst/edge/edge_src.h
gst/edge/meson.build
gst/nnstreamer/tensor_query/tensor_query_client.h
gst/nnstreamer/tensor_query/tensor_query_common.h
gst/nnstreamer/tensor_query/tensor_query_server.h
meson.build

1. nnstreamer-edge.h is from another package. Use #include appropriately.
2. dependency on nnstreamer-edge is not expressed proprely in meson.
Potential issue: Android build w/ nnstreamer-edge might need further care in /jni

tensor_query: nnstreamer-edge dependency fix

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_trainer.h
gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h

tensor_trainer calls this to stop model training being performed in a sub-plugin,
currently running epoch is finished to the end and sub-plugin saves the model
- Add function to stop model training
- Add ready-to-complete property to tensor_trainer
User should set when the training is ready to be completed and saved.
Ref: sub-plugin (https://github.com/nnstreamer/nntrainer/pull/2271/commits/6f5f4fcbc0698d140ed6af50ac8e0b6264c3518a)

[tensor_trainer] Add stop function to GstTensorTrainerFramework

---

debian/rules
gst/meson.build
meson.build
meson_options.txt
packaging/nnstreamer.spec
tests/meson.build

1. Make it 'feature' so that it can be resolved automatically.
2. Because it has an additional dependency, don't make it default true.
3. Force enable datarepo for Ubuntu/Tizen
CC: @songgot

Clean up build scripts for datarepo

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

"results" is allocated in ```_get_objects_mp_palm_detection_``` macro. Do not allocate it before calling it.
Fixes #4185

memleak fix: decoder/bounding-box

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

data->anchors is allocated at every init call without freeing.
Fixes #4187

memleak fix: decoder/bounding-box 2

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

- Let 0 dim value be acceptable for yolov5 decoder input's last values

[decoder] Fix yolov5 boundingbox dim check

---

ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
gst/nnstreamer/elements/gsttensor_converter.c
gst/nnstreamer/elements/gsttensor_converter_media_info_video.h
gst/nnstreamer/elements/gsttensor_converter_media_no_video.h
tests/nnstreamer_decoder/runTest.sh
tests/nnstreamer_sink/unittest_sink.cc

Support GRAY16 video format for tnesor_converter and tensor_decoder::direct_video.

[Converter/decoder] Support GRAY16 format

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

It has a few g_array that is not freed.
Fixes #4195

memleak fix: decoder/bounding-box mp_palm

---

tests/nnstreamer_sink/unittest_sink.cc

A few test cases did not call deallocation.

memleak fix: test/sink gtest

---

.github/workflows/macos.yaml

Fix the error:
```
==> Pouring python@3.11--3.11.5.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
rm '/usr/local/bin/2to3'
```
Reference: https://github.com/universal-ctags/ctags/pull/3759
This is a workaround. When homebrew resumes working in github-action,
we need to revert this.

workaround: brew error in github action.

---

ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
tests/nnstreamer_filter_lua/unittest_filter_lua.cc

It may access a struct of null pointer:
```
==32601== 1 errors in context 1 of 5:
==32601== Invalid read of size 8
==32601==    at 0x81659BA: nnstreamer::tensorfilter_lua::lua_subplugin::invoke(GstTensorMemory const*, GstTensorMemory*) (tensor_filter_lua.cc:498)
==32601==    by 0x8393D7B: nnstreamer::tensor_filter_subplugin::cpp_invoke(_GstTensorFilterFramework const*, _GstTensorFilterProperties*, void*, GstTensorMemory const*, GstTensorMemory*) (tensor_filter_support_cc.cc:168)
==32601==    by 0x16FCDC: nnstreamerFilterLua_invoke01_n_Test::TestBody() (unittest_filter_lua.cc:490)
==32601==    by 0x1A8F0B: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2402)
==32601==    by 0x1A274A: void …
```

memleak fix: filter/lua null check

---

gst/datarepo/gstdatareposrc.c

set-property may be called repeatedly.
Do not overwrite allocated pointers.
CC: @songgot : please take a look if there are similar errors (overwriting allocated pointers).

memleak fix: datareposrc json parse leaking.

---

tests/nnstreamer_trainer/unittest_trainer.cc

unref-ing GstElement from gst_bin_get_by_name is required with GST_OBJECT casting.

memleak fix: tests/trainer gtest @open sesame 8/29 12:16

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c

Fix wrong splling 'nueral' to 'neural' in tensor fliter property

[tensor_filter] Fix wrong spelling in spec string

---

gst/nnstreamer/elements/gsttensor_demux.c

g_strsplit_set()'s return should be freed by the caller.

memleak fix: tensor_demux forgot to free strv @open sesame 8/30 15:34

---

tests/common/unittest_common.cc

Unref gst-buffer that is allocated in the test case.

memleak fix: unittest-common forgot to unref

---

debian/rules

Since `enable-datarepo` is  removed, change to `datarepo-support`.

[Debian] Fix deprecated option

---

debian/control.ubuntu.ppa
debian/rules

Check pytorch version to fix ubuntu 18.04 build failure
- Fix incompatibility of protobuf and caffe2 of ubuntu 18.04.

[Ubuntu/1804] Check pytorch version @open sesame 08/31 14:16

---

tests/meson.build
tests/nnstreamer_filter_reload/meson.build
tests/nnstreamer_filter_reload/tensor_filter_reload_test.c
tests/unittest_util.c

- The mutex used in the filter is effected by invoke and reload both.
- Set GST_STATE_PAUSED before reloading models, to guarantee that mutex is unlocked.
- Use EPIPE instead of ESTRPIPE where it is not defined (macos).

[test] Fix filter_reload_test

---

gst/nnstreamer/elements/gsttensor_split.c

The initial value of tensor dimension is 0. Do not fill remained dims as 1.

[Split] init dim as 0

---

gst/nnstreamer/elements/gsttensor_srciio.c
tests/nnstreamer_source/unittest_src_iio.cc

0-init dims, data in src-iio has format of [ch-number][capacity].

[Src/IIO] dimension in tensorsrc-iio

---

tests/meson.build
tests/nnstreamer_decoder_image_labeling/runTest.sh
tests/nnstreamer_decoder_image_segment/runTest.sh
tests/nnstreamer_filter_reload/runTest.sh
tests/nnstreamer_filter_tensorflow_lite/runTest.sh

- Let's use tensorflow2-lite rather than deprecated tf1-lite.

[test] Replace tensorflow1-lite with tensorflow2-lite in SSAT tests

---

tests/nnstreamer_merge/runTest.sh
tests/nnstreamer_repo_lstm/runTest.sh
tests/transform_clamp/runTest.sh
tests/transform_stand/runTest.sh
tests/transform_transpose/runTest.sh

- Those runTest.sh are not executed regardless of the ret value of the python script. Fix It.

[ssat] Execute runTest.sh properly

---

ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
tests/nnstreamer_decoder/runTest.sh

Add test cases of all supported video format of the direct video decoder.

[Test/decoder] Add test cases for direct video decoer @open sesame 09/24 20:41

---

tests/nnstreamer_converter/unittest_converter.cc

converter gtest code mem leak.
converter element mem leak fix is coming with another PR that fixes multiple elements: #4238

memleak fix: converter test case fix

---

gst/nnstreamer/elements/gsttensor_if.c

- Wrong array index occur unwanted behavior and problem.

[TensorIF] Fix the wrong index in log format

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_transform.c
gst/nnstreamer/include/tensor_typedef.h
tests/common/unittest_common.cc
tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
tests/nnstreamer_plugins/unittest_plugins.cc

This patch Increase NNS_TENSOR_RANK_LIMIT
- Increase NNS_TENSOR_RANK_LIMIT to 16 from 8
- Delete convertMetaInvalidParam03_n, since NNS_TENSOR_RANK_LIMIT and NNS_TENSOR_META_RANK_LIMIT are now same.
- Fix some values in tests.

[tensor] Increase NNS_TENSOR_RANK_LIMIT to 16

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc

- Drop pytorch support for version less than 1.2.0 
- In the recent pytorch, `model->to (device)` does not work properly.
- Use `torch::jit::load (model, torch::Device)` instead.
Tested with yolov8 torchscript model with pytorch v2.0.1

[pytorch] Fix load model with use_gpu option with recent pytorch

---

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
tests/nnstreamer_filter_snpe/unittest_filter_snpe.cc

[filter]
- Remove excessive asserts. Throw exception when input or output buffer is NULL in invoke method instead.
[test]
- Sleep a while when the negative pipeline test exits.
- Deal with the recent rank update in nnstreamer.

[snpe] Remove excessive asserts and fix test

---

ext/nnstreamer/tensor_filter/meson.build
meson.build

- meson may change the default value of `run_command`'s `check` arg (false -> true). Set `check : false` in omitted lines.
- meson complains as `starting in "lib" only works by accident and is not portable`. Change `libSNPE` to `SNPE`.

[build] Fix recent meson usage

---

meson.build
tests/nnstreamer_filter_extensions_common/meson.build

- Set proper symbolic link and PYTHONPATH env variable to testenv to make `meson test` works with python module tests.

[build] Let meson test work with python3 support

---

packaging/nnstreamer.spec

For Tizen distro, do not let "auto" determine essential features. This will prevent regression that implicitly disabling nnstreamer-edge.

tizen: enable/disable nnstreamer-edge explicitly.

---

gst/edge/edge_src.c

Free host, topic variable memory in GstEdgeSrc when call finalize method to clear GstEdgeSrc memory

[Edge] Fix memory leak

---

packaging/nnstreamer.spec

The datarepo installed on the platform image can be used in the app, but if we reinstall the datarepo rpm after pushing by sdb, it cannot be used in the app.
-Add %license, %manifest, and %defattr(-,root,root,-) to spec

[datarepo] fix a bug that datarepo could not be used in Tizen App after reinstalling rpm @open sesame 09/19 17:05

---

meson.build

Since the ln command returns an error when the target already exists, 'meson build --reconfigure' fails as follows:
meson.build:746:4: ERROR: Command "/usr/bin/ln -s nnstreamer/build/ext/nnstreamer/extra/nnstreamer_python3.so
nnstreamer/build/ext/nnstreamer/extra/nnstreamer_python.so" failed with status 1.
To fix it, this patch appends the -f, (--force) option to the ln command that creates a soft link file for the python3 sub-plugin.

Meson: Append force option to 'ln' creating python sub-plugin @open sesame 9/20 17:15

---

tests/nnstreamer_filter_tensorflow2_lite/runTest.sh

Negative test cases require _n postfix for the test infrastucture to recognize them. The new test cases with property config forgot to add such postfix properly.
This fixes test case infra regression with #4262

test: tensor_filter/tflite2 correct postfix

---

Documentation/hotdoc/gen-hotdoc.sh
gst/nnstreamer/elements/README.md

This patch fixes broken link in github.io.
- Tensor * in https://nnstreamer.github.io/gst/nnstreamer/elements/README.html 
- Links in https://nnstreamer.github.io/gst/nnstreamer/tensor_query/README.html
github.com uses .md file and github.io uses .html file for link. 
So conversion is required.

[doc] fix broken link in github.io

---

gst/edge/edge_sink.c

- An explicit type casting technique is used to safely and clearly convert the type using a GST macro.
2. Run test: []Passed [ ]Failed [*]Skipped

[Edge] Change type casting to GST macro

---

gst/edge/edge_sink.c
gst/edge/edge_src.c

Free dest_host, topic variable memory in GstEdgeSink
when call finalize method to clear GstEdgeSink memory

[Edge] Fix memory leak when finalize sync

---

gst/datarepo/gstdatareposrc.c

This patch fixes the bug that tries to get the 'framerate' value from the caps of any data source. Note that there is no 'framerate' field in GstAudioInfo.
```bash
[ RUN      ] datareposrc.readAudioRaw
(unittest_datareposrc:334019): GStreamer-CRITICAL **: 16:19:54.338: gst_value_get_fraction_numerator: assertion 'GST_VALUE_HOLDS_FRACTION (value)' failed
(unittest_datareposrc:334019): GStreamer-CRITICAL **: 16:19:54.338: gst_value_get_fraction_denominator: assertion 'GST_VALUE_HOLDS_FRACTION (value)' failed
[       OK ] datareposrc.readAudioRaw (1002 ms)
```
```bash
[ RUN      ] datareposrc.readAudioRaw
[       OK ] …
```

DataRepo/Src: Get the framerate only if the data have it

---

gst/datarepo/gstdatareposrc.c

Since a null check is omitted in the finalize function, g_object_unref complains about it in some cases as follows:
(unittest_datareposrc:19927): GLib-GObject-CRITICAL **: 10:46:26.793: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
This patch fixes it.
```bash
26/27 unittest_datareposrc                        OK               7.91s
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:
[==========] Running 22 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 22 …
```

DataRepo/Src: Add missing null check to the finalize function

---

gst/nnstreamer/elements/gsttensor_decoder.c
gst/nnstreamer/elements/gsttensor_decoder.h
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter_common.c
gst/nnstreamer/tensor_filter/tensor_filter_common.h

Fix warning on gst-inspect cmd,
1. add config-path to read plugin properties.
2. update invalid description.

[Filter/Decoder] function to get property

---

tests/nnstreamer_filter_reload/tensor_filter_reload_test.c

The bus_callback was using a global variable, loop, while its registerers (e.g., TEST (datareposrc, fps30ReadFlexibleTensors) ) has loop local variable.
Therefore, the callback has been using uninitialied and unrelated global variable, loop, which often causes unit test errors:
```
[  316s] [ RUN      ] datareposrc.fps30ReadFlexibleTensors
[  317s] Elapsed time: 0.687305 second
[  317s] ../tests/nnstreamer_datarepo/unittest_datareposrc.cc:686: Failure
[  317s] Expected: (0.8) < (elapsed_time), actual: 0.8 vs 0.687305
[  317s] Elapsed time: 0.003219 second
[  318s] Elapsed time: 1.001501 second
[  318s] [  FAILED  ] datareposrc.fps30ReadFlexibleTensors (2045 ms)
```
by exiting from g_main_loop too early.

test/datarepo_src: scope error

---

meson.build

Flatbuf is not enabled if the version of flatc mismatches. Print a more friendly message for such version mismatch.
This helps #4226
CC: @Sourabh-ALTEN

build: better flatc-flatbuf version mismatch message

---

ext/nnstreamer/tensor_decoder/tensordec-tensor_region.c

commit e0fe59ef457740f32cf055a1fc95275be17413df (HEAD -> fix/tensor_region, origin/fix/tensor_region)
Date:   Wed Sep 6 17:30:40 2023 +0900
decoder:tensor_region: fix for future expansion.
- Fix a mem leak (tr_exit())
- For future expansion with different mode, prepare exiting previous modes.
commit 6d3446b851b7133c42c3381471ddb890f128c67f
Date:   Wed Sep 6 17:18:41 2023 +0900
style fix: decoder/tensor_region dos2unix & trailing whitespaces
It was formatted in "DOS" type. Apply dos2unix.
Then, remove trailing whitespaces.

decoder:tensor_region fixes

---

tests/nnstreamer_filter_custom/unittest_filter_custom.cc
tests/unittest_util.h

wait_pipeline_process_buffers accepts timeout in ms, not us.

test: don't wait for 10000sec. wait 10sec.

---

tests/nnstreamer_filter_single/unittest_filter_single.cc

- Those testcases requires recent tflite version (2.11.0), whose version is lower in tizen 7.0. skip it.

[lts][build] Disable some testcases in tizen-7.0

---

gst/nnstreamer/tensor_filter/tensor_filter.c

gst_tensor_info_convert_to_meta may return error
if the configured output tensor is invalid.
Handle the error before feeding it to another function, that may access uninitialized value.

filter: handle error of convert_to_meta

---

gst/nnstreamer/meson.build
gst/nnstreamer/ml_agent.c
gst/nnstreamer/ml_agent.h
meson.build

Since MLAgentd would no longer be used interchangeably with MLAgent, this patch applies those changes. 
See also: https://github.com/nnstreamer/api/pull/407

Filter/MLAgent: Replace MLAgentd with MLAgent @open saseme 10/13 16:30

---

.github/workflows/ubuntu_clean_llvm_build.yml
meson.build
tests/meson.build
tests/nnstreamer_filter_reload/tensor_filter_reload_test.c
tools/development/parser/toplevel.c

This fixes #3979 (CC @wooksong )
1st commit:
commit 3fe9ae56a19aff98a77d24862a2a3dbc756dfa7d
Date:   Fri Oct 13 18:16:58 2023 +0900
Support clang/clang++
Fix clang's complaints.
Addressing #3979
To build w/ LLVM, do
$ CC=clang CXX=clang++ meson ...
2nd commit:
commit 9d27be517d23d14ab097af0c954ac0d7f28ad024
Date:   Fri Oct 13 18:55:48 2023 +0900
github-action: ubuntu-llvm/clang build test
Add llvm/clang build test.
Fixes #3979

Test LLVM/Clang build in github-action

---

ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c

As #3903 requests, we need descriptions for subplugin users.
@wooksong, @yeonykim2, @niley7464 (or anyone who's capable), please populate such info for more decoder, converter, filter subplugins. (then, close #3903 )
@songgot : Please apply similar changes to tensor_trainer subplugins.

decoder: add detailed descriptions for a few subplugins.

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

In addition to https://github.com/nnstreamer/nnstreamer/pull/4284, this patch adds descriptions for the bounding box sub-plugin options.
See also: #3903 
```bash
$ ./nnstreamer-check
NNStreamer version: 2.4.1
loaded : TRUE
path   : /home/wook/Work/NNS/nnstreamer/build/gst/nnstreamer/libnnstreamer.so
NNStreamer configuration:
============================================================
Configuration Loaded: TRUE
Configuration file path: /home/wook/Work/NNS/nnstreamer/build/nnstreamer-test.ini
Candidates: envvar(NNSTREAMER_CONF): /home/wook/Work/NNS/nnstreamer/build/nnstreamer-test.ini
build-config: /usr/local/etc/nnstreamer.ini …
```

Decoder: Add detailed descriptions for the bounding box sub-plugin @open sesame 10/18 18:04 

---

gst/edge/edge_sink.c
gst/edge/edge_src.c
gst/edge/edge_src.h
tests/nnstreamer_edge/edge/unittest_edge.cc

- Add a description of deprecated for port and host property of edgesrc.
In the case of edgesrc, port and host settings are not required.
- Update description of port property of edgesink

[edge] Deprecate port and host property of edgesrc and update description for port property

---

.github/workflows/gbs_x64.yml

- Let github action cache the directory. Speed gbs build up by removing package downloads.
- The cache key is the date. The very first run each day will make new cache.
Gbs build with _skip_debug_rpm and --skip-srcrpm
- Let gbs build do not make debug rpms and skip srcrpm
- This will save extra seconds..

[action] Let gbs action cache 'GBS-ROOT/local/cache'

---

gst/nnstreamer/elements/gsttensor_demux.c
gst/nnstreamer/include/nnstreamer_plugin_api.h
gst/nnstreamer/nnstreamer_plugin_api_impl.c

Fix util function to take gst-memory if failed to append it.

[Common] unref memory when appending tensor buffer

---

.github/workflows/gbs_x64.yml
.github/workflows/macos.yaml
.github/workflows/risc-v.yml
.github/workflows/ubuntu_clean_llvm_build.yml
.github/workflows/ubuntu_clean_meson_build.yml
.github/workflows/update_gbs_cache.yml

- Doing every workflows on each push is not necessary as each
pull request already checks it.
- Do not run those to save the earth!
[action] Cache gbs once every weekday
- Let the new workflow cache gbs every weekday.

[action] Do not run github workflows on every push event

---

.github/workflows/update_gbs_cache.yml

- Let action cache gbs every morning weekday
to set cache key (date) properly.

[action] Change gbs cache timing

---

gst/nnstreamer/tensor_filter/tensor_filter_single.c

Changed to use a macro when converting a pointer to the GstTensorFilterSinglePrivate type. 
Through this, the type conversion method is unified in other functions to maintain consistency and ensure stability.

[Filter] Typecast using G_TENSOR_FILTER_SINGLE_PRIV macro

---

gst/edge/edge_src.c
gst/edge/edge_src.h
gst/nnstreamer/tensor_query/tensor_query_client.c

- Since the reconnection has been changed to be done inside the nns-edge, nns_edge_connect for reconnection is deleted from the nnstreamer element.
- Add state change function and set `playing` prop.
1. Build test: [O]Passed [ ]Failed [ ]Skipped
2. Run test: [O]Passed [ ]Failed [ ]Skipped

[Edge] Remove re-connect from nnstreamer element

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_client.h
tests/nnstreamer_edge/query/runTest.sh

Currently, the query client sends all input buffers to the query server.
If the processing speed of the server is slower than the client, the result time of the server is gradually different from the input time.
To prevent this, the server processes only limited number of buffers, and drop the remaining input buffers.
Signed-off-by: gichan2-jang <gichan2.jang@samsung.com>

[Query] Add max-request prop to query client @open sesame 11/22 10:40

---

ext/nnstreamer/tensor_filter/meson.build

- Remove those args thus it's not needed with recent snpe sdk.

[build] Remove unnecessary compile args for SNPE sub-plugin

---

tests/meson.build
tests/nnstreamer_filter_tensorflow2_lite/runTest.sh
tests/nnstreamer_filter_tensorflow_lite/runTest.sh

Fix version of tensorflow-lite.
Both version 2.x and 1.x can be used in testcase if tensor-filter property framework is tensorflow-lite. Default version is v2.x, and it has higher priority.
Also, added minor patch to fix indent.

[Test] tensorflow-lite version in testcase

---

gst/datarepo/gstdatareposrc.c
tests/nnstreamer_datarepo/unittest_datareposrc.cc

- The Filename is changed for each TC because sometimes the JSON file of unittest(fps30ReadFlexibleTensors) is deleted by g_remove() in the previous unittest

[datareposrc] Bugfix: Fixed removing JSON file before unittest @open sesame 11/24 12:50

---

gst/nnstreamer/include/tensor_typedef.h

Code clean, now we do not define data structure in ML API repo and use common functions of nnstreamer. 
Remove unnecessary lines defined in api repo.

[Doc] remove unnecessary lines from ml-api

---

ext/nnstreamer/tensor_filter/meson.build
meson.build

- Recent neural network frameworks needs c++17 standards to use its APIs
- Let nnstreamer be built with c++17.
- Add a Wno flag to snpe filter.

[build] Set cpp_std=c++17 (changed from c++14)

---

gst/nnstreamer/tensor_query/tensor_query_client.c
gst/nnstreamer/tensor_query/tensor_query_client.h

1. Decrease the ref count of incoming buffer if an error occurs.
2. Check the number of requested buffer before creating edge-data handle, and try to get the output from query-server.
3. Append gst-buffer using util function if current caps is tensor stream.

[QueryClient] handle tensor buffer

---

gst/nnstreamer/include/nnstreamer_plugin_api_util.h
gst/nnstreamer/nnstreamer_plugin_api_impl.c
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c

Prevent appending same caps if tensor dimension has min rank 4. 
(e.g., given dim is 1001:1, previous caps with rank 4 is unnecessary.)

[Common] check tensor dim to append previous caps

---

ext/nnstreamer/tensor_filter/meson.build
packaging/nnstreamer.spec

- TFLite API requires flatbuffers header. Let meson check required header
- Add `BuildRequires` flatbuffers-devel explicitly in spec

[build] Check flatbuffers header files before build tflite subplugin

---

tests/tizen_sensor/dummy_sensor.h

Since both mobile and wearable profiles in Tizen project are removed, related tags also should be removed. 
This patch removes them at Tizen PM's request.

[Test] Remove the MOBILE and WEARABLE tags in header file

---

ext/nnstreamer/tensor_filter/tensor_filter_python3.cc

A python-global reference counter is required for py-finalize.
This is workaround before applying such a global reference counter.
A real fix will be applied after #4348 and #4347

filter::python3: do not break converter/decoder

---

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c

This patch adds to check NNFW_MAX_RANK in nnfw filter. 
If tensor info's rank is larger than NNFW_MAX_RANK and min_rank is smaller, use min_rank instead.
https://github.com/nnstreamer/nnstreamer/pull/4352#discussion_r1429579168

[nnfw] Check NNFW_MAX_RANK in nnfw filter

---

debian/control
ext/nnstreamer/extra/meson.build
ext/nnstreamer/extra/nnstreamer_python3_helper.h
ext/nnstreamer/tensor_converter/meson.build
ext/nnstreamer/tensor_converter/tensor_converter_python3.cc
ext/nnstreamer/tensor_decoder/meson.build
ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
ext/nnstreamer/tensor_filter/tensor_filter_deepview_rt.cc
ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
ext/nnstreamer/tensor_filter/tensor_filter_mediapipe.cc
ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
ext/nnstreamer/tensor_filter/tensor_filter_mxnet.cc
ext/nnstreamer/tensor_filter/tensor_filter_ncnn.cc
ext/nnstreamer/tensor_filter/tensor_filter_onnxruntime.cc
ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
ext/nnstreamer/tensor_filter/tensor_filter_openvino.hh
ext/nnstreamer/tensor_filter/tensor_filter_snap.cc
ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorrt.cc
ext/nnstreamer/tensor_filter/tensor_filter_trix_engine.hh
ext/nnstreamer/tensor_filter/tensor_filter_tvm.cc
ext/nnstreamer/tensor_filter/vivante/meson.build
ext/nnstreamer/tensor_filter/vivante/tensor_filter_vivante.c
gst/nnstreamer/tensor_filter/meson.build
gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
packaging/nnstreamer.spec

Remove unnecessary dependency of gstreamer when building subplugins. 
(e.g., we should support filter-subplugin for single-shot, without gst.)

[Build] dependency to gstreamer

---

ext/nnstreamer/include/nnstreamer.fbs
ext/nnstreamer/include/nnstreamer.proto
gst/nnstreamer/include/tensor_typedef.h

Add missing tensor type 'float16' when generating protobuf and flatbuf code.

[Protobuf] missing tensor type

---

packaging/nnstreamer.spec

Remove flatbuf-python dependency from all Tizen profile.

Remove flatbuf-python dependency

---

packaging/nnstreamer.spec

Remove flatbuf-python dependency from all Tizen profile.
* This patch is backported from https://github.com/nnstreamer/nnstreamer/commit/28bb054acae2d29a902694b12f9684fcef203884

[Spec] Remove flatbuf-python dependency

---

meson.build

- Let meson check ncnn pc file first, and do fallback check then.

[build] Let meson check ncnn pkg-config

---

ext/nnstreamer/tensor_filter/meson.build
tests/nnstreamer_filter_extensions_common/meson.build

- Halt meson setup procedure when given compiler is not GCC and pytorch-support is enabled. Rather than warning and go.
1. Build test: [X]Passed [ ]Failed [*]Skipped
2. Run test: [X]Passed [ ]Failed [*]Skipped

[build] Halt meson setup when compiler is not GCC and pytorch is enabled

---

ext/nnstreamer/extra/nnstreamer_grpc_common.cc
ext/nnstreamer/tensor_source/tensor_src_grpc.c

The type of data pushed into queue is gst-buffer.
Clearly set the release function when calling free.

[CodeClean/grpc] clearly define release function

---

ext/nnstreamer/extra/nnstreamer_python3_helper.cc
ext/nnstreamer/extra/nnstreamer_python3_helper.h
ext/nnstreamer/tensor_converter/tensor_converter_python3.cc
ext/nnstreamer/tensor_decoder/tensordec-python3.cc
ext/nnstreamer/tensor_filter/tensor_filter_python3.cc
tests/test_models/models/scaler.py

filter/python3: revise GIL access.
Control GIL at C callbacks.
Control mutex at C++ class.
As in decoder/converter changes.
This is the last step before the final step for #3834

Revise GIL control for python3 subplugins. @open sesame 1/3 17:40

---

nnstreamer-internal.pc.in

nnstreamer-internal pkg requires nns-single library.

[Pkg] fix library name for nns internal

---

ext/nnstreamer/tensor_filter/meson.build
packaging/nnstreamer.spec

- The latest tflite2 tizen package has its own flatbuffers header internally. Let's remove the `BuildRequires: flatbuffers-debvel`
- Let meson check the header when build_platform is not tizen

[build] Remove unnecessary BuildRequires @open sesame 1/5 20:43

---

ext/nnstreamer/tensor_filter/tensor_filter_onnxruntime.cc

Some onnx models had free dimensions for batch. ex) [None:3:720:720]
\- It fixed that creating tensor with negative value in shape ```Ort::Value``` is treated  as 1.

[fix/onnxruntime-filter] fixed tensor with negative value in shape

---

gst/nnstreamer/ml_agent.c
tests/unittest_mlagent/mock_mlagent.h
tests/unittest_mlagent/unittest_mlagent.cc

- Let `mlagent_get_model_path_from` returns uri in fallback case
- Fix memleak (g_strfreev).
- Fix memleak in a testcase.
- Add a missing header <utility> in mock_mlagent.h
- It declares `std::exchange`
- Fix multiline comments in unittest_mlagent.cc to satisfy CI (doxygen)

[mlagent] Fix fallback case and unittest_mlagent @open sesame 1/9 16:24

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_snpe_v1.cc
meson.build

- Rename tensor_filter_snpe.cc to tensor_filter_snpe_v1.cc
- Current source code targets SNPE version 1.
- Let meson.build check SNPE API version.
- Added compile flag `SNPE_VERSION_MAJOR` would be used in future commits targeting SNPE v2.

[build] Rename ..._snpe.cc to ..._snpe_v1.cc and let meson check SNPE version

---

gst/nnstreamer/elements/gsttensor_trainer.c

- Move gst_tensor_trainer_check_invalid_param to enable setting properties in PAUSED states

[tensor_trainer] Move the function of checking invalid parameters

---

.github/workflows/risc-v.yml

Use dockerfile of nnstreamer's fork designed for nnstreamer packages.

github-action/risc-v test update

---

.github/workflows/static.check.scripts/doxygen-tag.sh
.github/workflows/static.check.yml

Add static checkers & verifiers to github-actions.
Initially, clang-format for C++ files and file size checker
are migrated from TAOS-CI.
We can add other pre-build TAOS-CI checks later in this workflow file.
To see how it works, please refer to https://github.com/nnstreamer/nnstreamer/actions/runs/7530746389/job/20497815796?pr=4381

actions: add static checks

---

.github/workflows/static.check.yml

The git-changed files may include deleted files.
Do not run static-cchecks on deletec files.

github-action: do not run static-checks on deleted files.

---

.github/workflows/cpp-linter.yml

This patch adds a GitHub Action workflow to check C++ source file format.
[Imported from deviceMLOps.MLAgent]

GitHub/Workflows: Add an action to check C++ source file format

---

gst/nnstreamer/nnstreamer_plugin_api_impl.c

- last_memory should be released before calling `gst_buffer_replace_memory`

[common] Fix mem leak in gst_tensor_buffer_append_memory @open sesame 2/6 13:59

---

gst/nnstreamer/ml_agent.c

- change misspelling 'stringied' to 'stringfied'

[mlagent] Fix misspelling variable naming and log

---

.github/workflows/static.check.scripts/indent.sh

Indent style error is set down to warning.
Until we have ZERO indent style error in overall,
let's keep them warning.

github-action: indent style error --> warning

---

ext/nnstreamer/tensor_decoder/tensordec-tensor_region.c
gst/nnstreamer/nnstreamer_plugin_api_impl.c
tests/nnstreamer_filter_tensorflow2_lite/unittest_filter_tensorflow2_lite.cc

- Extra tensor names stored in GstMemory leaks. Let the extra tensor do not store names.
- Fix mem leak in tflite unittest
- Fix memory leak in tensor_region
- mem argument of `gst_tensor_meta_info_append_header` should be freed.
- Properly free old memory after the call and replace the buffer with new memory

[Fix] Fix memory leaks found by CI valgrind check

---

tests/nnstreamer_datarepo/unittest_datareposink.cc

Occasionally, in github-action CI, datareposink.writeFlexibleTensors_n fails due to synchronization errors:
```
[ RUN      ] datareposink.writeFlexibleTensors_n
../tests/nnstreamer_datarepo/unittest_datareposink.cc:570: Failure
Expected: (file_info) != (nullptr), actual: NULL vs (nullptr)
[  FAILED  ] datareposink.writeFlexibleTensors_n (173 ms)
```
It happens when the pipeline is set NULL before the file 'flexible.data' is writtn within the pipeline.
Allow some time (0.1s) before setting it NULL.

test/datareposink: timing error in test case

---

packaging/nnstreamer.spec

- Suppress ORC logs as showing WARNING or higher logs to reduce too many them during gbs unittests.

[spec] Suppress ORC log level

---

ext/nnstreamer/extra/nnstreamer_protobuf.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
gst/nnstreamer/elements/gsttensor_if.c
tests/nnstreamer_filter_single/unittest_filter_single.cc
tests/nnstreamer_latency/unittest_latency.cc
tests/nnstreamer_plugins/unittest_plugins.cc

- Call `g_option_context_free` in unittest_latency
- Unref memory properly during unittests.
- Free g_list and GValue in tensor_if
- Fix memory leak when reload tflite model
- Fix memory leak in nnstreamer_protobuf

[Fix] Resolve memory leaks detected by valgrind

---

gst/nnstreamer/nnstreamer_plugin_api_impl.c

Clearly set null after releasing the name in tensor-info struct.

[CodeClean] set null after free

---

packaging/nnstreamer.spec

- Fix rpmbuild warning about wrong date
1. Build test: []Passed [ ]Failed [*]Skipped

[trivial] Fix bogus date in chagnelog

---

gst/nnstreamer/meson.build
gst/nnstreamer/ml_agent.c
meson.build
packaging/nnstreamer.spec

This patch updates build dependency on MLOps Agent. Note that MLAgent has been renamed to MLOps Agent and provided from a new repository separated from the API repository.
See also: https://github.com/nnstreamer/api/pull/455

Filter/MLAgent: Update build dependency on MLOps Agent

---

meson.build

If -Dsupport-ncnn=enabled is given and ncnn is not found, an error should be generated by meson.

meson: explicit 'enabled' should spit errors if not found

---

packaging/nnstreamer.spec

Due to the lcov 2.0 upgrade, the warning is changed to error so the gcov build fails. Ignore this case. (Tizen PM guide)

[Tizen] Fix gcov build error

---

gst/nnstreamer/elements/gsttensor_trainer.c

- When a request to stop model training is received, if it has already been completed, it is ignored

[tensor_trainer] Add condition to stop model training

---

gst/nnstreamer/tensor_query/tensor_query_server.c
gst/nnstreamer/tensor_query/tensor_query_server.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversink.h
gst/nnstreamer/tensor_query/tensor_query_serversrc.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.h
tests/nnstreamer_edge/query/unittest_query.cc

Problem: When state changes from PAUSED to NULL,the tensor_query_serversrc cannot switch to NULL state because it keeps waiting for data pop.
Solution: Change the creation and destruction of server data and edge handle to be managed according to the state.
READY->PAUSED: Create query server common data
PAUSED->PLAYING: Create nns-edge handle
PLAYING->PAUSED: Release nns-edge handle
PAUSED->READY: Destruct query server common data
Releated issue: https://github.com/nnstreamer/api/issues/487

[Query] Release edge handle when stoping the playing

---

gst/nnstreamer/tensor_query/tensor_query_server.c
gst/nnstreamer/tensor_query/tensor_query_server.h
gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversink.h
gst/nnstreamer/tensor_query/tensor_query_serversrc.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.h

To prevent double free case, remove query handle and use integer id.
Also, add util function to hide edge handle in query elements and fix null ptr case.

[Query] util function using integer id

---

.github/workflows/pdebuild.yml

- Currently pbuilder workflow does not use stored cache for permission error. This commit resolve the issue.
- Let it cache base.tgz and aptcache/ and do not make base.tgz everytime.

[workflow] Fix pbuilder caching

---

ext/nnstreamer/tensor_filter/tensor_filter_ncnn.cc

This patch makes ssat test (grep "accl = gpu" string) works.

[ncnn] Use g_message for accl log

---

tests/nnstreamer_edge/edge/runTest.sh
tests/nnstreamer_edge/query/runTest.sh
tests/nnstreamer_grpc/runTest.sh

Set the gstTestBackground TC as not critical:
The another background pipeline (videotestsrc ! ... ! filesink) from
`gstTestBackground` sometimes does not make test file properly.
If following compare tests succeed, It means queryserver pipeline
works well.

[test] Set a query-hybrid testcase as not critical

---

debian/control
debian/control.ubuntu.ppa

I decided to use pytorch being integrated by Ubuntu (debian/sid), and this package provides libtorch-dev for C++ binding.
Trying to address #4431

Ubuntu: mantic & noble support

---

.github/workflows/macos.yaml

Github-action macos build started spitting:
```
Run actions/setup-python@v1
with:
python-version: 3.x
architecture: x64
env:
changed_file_list: /var/folders/3m/p59k4qdj0f17st0gn2cmj3640000gn/T/tmp.b0uhtmFUzp
rebuild:        1
Error: Version 3.x with arch x64 not found
Available versions:
```
Similar with https://github.com/actions/setup-python/issues/162

github-action/macos build fix

---

.github/workflows/android.yml
.github/workflows/pdebuild.yml
.github/workflows/yocto.yml

- Currently `pdebuild --architecture arm64` is equivalent as `pdebuild --architecture amd64`. Drop arm64 build.
- Saving cache in each PR consumes too much space.
- To utilize the cache, we need to update each cache in main branch periodically.
Before introducing such action, disable cache for a while.

[action] Disable meaningless cache and action

---

packaging/nnstreamer.spec

- Set proper lcov options w.r.t. Tizen/lcov versions.

[spec] Fix lcov options for different Tizen/lcov versions

---

packaging/nnstreamer.spec

Update spec to enable ONNX runtime from Tizen 9.0.

[Build] onnx-runtime from tizen 9.0

---

.github/workflows/gbs_build.yml
.github/workflows/pdebuild.yml
.github/workflows/update_gbs_cache.yml
.github/workflows/update_pbuilder_cache.yml

- Since Ubuntu 22.04 supports gbs from this year, let's switch to it.
- This patch makes the daily pdebuild workflow save the cache key with date postfix and outdate previous cache. Then the pdebuild.yml workflow can use the fresh cache.

[actions] Fix gh actions

---

gst/nnstreamer/elements/gsttensor_trainer.c
tests/nnstreamer_trainer/unittest_trainer.cc

Added exception handling for a non-existent model config file

[tensor_trainer] bugfix: Add exception handling for a non-existent model config file

---

gst/edge/edge_src.c

- Prevent Gstreamer-CRITICAL message when caps is null

[edgesrc] Add checking caps before getting tensor size

---

ext/nnstreamer/tensor_filter/vivante/meson.build
packaging/nnstreamer.spec

- Build vivante subplugin for some targets.

[prod/tizen-7.0][spec] Enable vivante for specific profile

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_trainer.h

Change the variable name indicating the number of data pushed in the current epoch.

[tensor_trainer] Change variable name

---

packaging/nnstreamer.spec

- Disable snpe build. There is problem in platform's snpe package.
- This should be reverted when the snpe package is fixed.

[prod/tizen-8.0] Disable snpe subplugin build for mv_prj temporarily

---

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
jni/nnstreamer.mk

- Support snpe (SDK v2) in Android.
Some additional env variables are requires to be set.
REF: https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-2/dsp_runtime.html

[filter] Support snpe filter in android

---

ext/nnstreamer/tensor_filter/tensor_filter_deepview_rt.cc

Fix mem leak case when loading mapped model file, use member variable.

[Filter/DeepViewRT] mem leak case

---

gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.c

This patch makes to set tensor query caps, when state changes from PAUSED to PLAYING.
When the tensor_query_server is stopped, edge_handle is released.
So we need to set caps again when restarted.
If caps are not set, client connection is not possible after restart tensor_query_server.
This PR fixes https://github.com/nnstreamer/nnstreamer-android/pull/35#issuecomment-2164310115

[query] Set tensor query caps when state changes from PAUSED to PLAYING

---

gst/nnstreamer/tensor_query/tensor_query_serversink.c
gst/nnstreamer/tensor_query/tensor_query_serversrc.c

Set caps in edge handle before calling change-state callback.

[Query] case when change pipe state

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_trainer.h

When the pipeline stops and no data is input, the necessary data for the current epoch is generated for the normal termination of nntrainer. The data generation callback of nntrainer is no longer called until all the necessary data for the current epoch are received.

[tensor_trainer] Add a function that generates dummy data

---

meson.build

- If cuda deps are intalled but tensorrt is not, `tensorrt_version_str` equals '' and the meson script gives error. This patch fixes it.

[build] Fix meson logic checking tensorrt dep

---

ext/nnstreamer/tensor_filter/meson.build

- Check `delete` in meson.build. Recent versions of tflite need to check this.

[build] Fix tflite nnapi delegate check meson logic

---

gst/nnstreamer/elements/gsttensor_trainer.c
gst/nnstreamer/elements/gsttensor_trainer.h

- ready_to_complete property is removed
1. Build test:  [*] Passed [ ]Failed [ ]Skipped
2. Run test:  [*] Passed [ ]Failed [ ]Skipped

[tensor_trainer] remove ready_to_complete property

---

README.md

LGTM.com service is closed. They are acquired by github.com.

README: remove lgtm.com service

---

gst/nnstreamer/elements/gsttensor_split.h

spell checker error, fix subplugin name in brief tag.

[CodeClean] fix typo

---

ext/nnstreamer/tensor_filter/README.md
ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_executorch.cc
meson.build
meson_options.txt

This draft pull request lays the groundwork for integrating the executorch tensor filter into nnstreamer. Although the current implementation is not yet complete and might have some errors or inefficiencies, we believe it can serve as a valuable starting point and reference for future work on this feature.
During the development of this draft PR, we encountered significant performance issues with the current stable branch of executorch (v0.2.1). Despite our efforts to investigate and resolve these issues, we were unable to identify the root cause of the performance degradation.
As a result, we made the decision to build the executorch main branch instead of the stable v0.2.1 branch. While we acknowledge that using the main branch may introduce instability and potential compatibility …

[Draft] Initial implementation of executorch tensor filter

---

ext/nnstreamer/tensor_decoder/box_properties/mobilenetssd.cc
ext/nnstreamer/tensor_decoder/box_properties/mobilenetssdpp.cc
ext/nnstreamer/tensor_decoder/box_properties/mppalmdetection.cc
ext/nnstreamer/tensor_decoder/box_properties/ovdetection.cc
ext/nnstreamer/tensor_decoder/box_properties/yolo.cc
ext/nnstreamer/tensor_decoder/tensordec-boundingbox.cc
ext/nnstreamer/tensor_decoder/tensordec-boundingbox.h
tests/nnstreamer_decoder_boundingbox/runTest.sh

This patch use util to get nth info in tensor_decoder bounding box and add test case.
https://github.com/nnstreamer/nnstreamer/pull/4427#issuecomment-2114713513

[CodeClean] util to get nth info

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc

- Import QNN delegate header.
- For Android, set certain environment variables for DSP/HTP runtimes.
- Add custom option for QNN Delegate.
- Add custom option for QNN backend and performance mode.
- User can use this in pipeline:
`... custom=Delegate:QNN,QNNBackend:DSP,QNNPerformanceMode:highperformance ...`
Disclaimer: This only be tested in Android.

[filter] Support TFLite QNN Delegate

---

ext/nnstreamer/extra/nnstreamer_python3_helper.cc

It is possible that python-status-check is called
when PyIsInitialized is false (refer to #4523)
Trying to fix #4523
CC: @liuhao-97

don't assert on PyIsInitialized.

---

packaging/nnstreamer.spec

Tizen is going to accept TensorRT and NVidia GPUs in the build system. Let's allow to enable TensorRT.
However, meson is not configured to force tensorrt, yet, becuase we do not know whether Tizen is going to port TensorRT version >=10 or not.

tizen: allow tensorrt

---

tests/unittest_util.h

State change tests in the armv7l architecture is too long. Let's increase the timeout limit.
```
[  638s] [ RUN      ] nnstreamerFilterSharedModel.tfliteSharedReload
[  638s] ** Message: 09:59:55.720: accl = cpu
[  638s] ** Message: 09:59:55.725: accl = cpu
[  640s] ../tests/nnstreamer_filter_shared_model/unittest_filter_shared_model.cc:174: Failure
[  640s] Expected equality of these values:
[  640s]   setPipelineStateSync (pipeline, GST_STATE_PLAYING, (2000U))
[  640s]     Which is: -62
[  640s]   0
[  640s]
[  641s] ../tests/nnstreamer_filter_shared_model/unittest_filter_shared_model.cc:180: Failure
[  641s] Expected: (res[0]) != (0U), actual: 0 vs 0
[  641s]
[  643s] [  FAILED  ] nnstreamerFilterSharedModel.tfliteSharedReload (4570 ms)
```
1. Build test: [ ]Passed …

[TEST] increase timeout for state change

---

gst/nnstreamer/elements/gsttensor_converter.c
gst/nnstreamer/elements/gsttensor_converter_media_info_video.h
tests/nnstreamer_sink/unittest_sink.cc

- Channel First (NCHW) formats RGBP and BGRP are supported in gstreamer 1.20.0+
- Let tensor_converter handle this video_format.
Simple performance test in my machine shows
2500 FPS (videoconvert) v.s. 1300 FPS (tensor_transform transpose)
```bash
videotestsrc ! video/x-raw,width=640,height=480,format=RGB ! \
videoscale ! videoconvert !
video/x-raw,format=RGBP,width=320,height=320 ! \
tensor_converter ! tensor_sink
-> 2500 FPS
v.s.
videotestsrc ! video/x-raw,width=640,height=480,format=RGB ! \
videoscale ! videoconvert !
video/x-raw,format=RGB,width=224,height=224 ! \
tensor_converter ! \
tensor_transform mode=transpose option=1:2:0:3 ! tensor_sink
-> 1300 FPS
```
2. Run test: [X]Passed [ ]Failed [ …

[converter] Supports gstreamer video format RGBP, BGRP

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_dali.cc
meson.build
meson_options.txt
tests/meson.build
tests/nnstreamer_filter_dali/create_dali_pipeline.cc
tests/nnstreamer_filter_dali/runTest.sh
tools/cuda-version.sh
tools/dali-config.sh
tools/tensorrt-version.sh

This PR adds a tensor_filter for dali pipelines. See also https://github.com/NVIDIA/DALI. Only dali pipeline operators implemented in C++ are supported. The tensor_filter_dali uses the DALI c_api (which may be subject to change). By using the dali pipeline GPU operators, the preprocessing steps can be executed leveraging cuda acceleration.
The dali pipeline used for testing purposes is created using tests/nnstreamer_filter_dali/create_dali_pipeline.cpp. The created binary file (dali_pipeline_N_3_320_320.bin) contains the protobuf binary serialized representation of the dali pipeline.

[Filter] [Experimental] Add support for dali pipeline.

---

.github/workflows/publish_docs.yml

Fix invalid action job name
```
[Invalid workflow file: .github/workflows/publish_docs.yml#L11](https://github.com/nnstreamer/nnstreamer/actions/runs/10409426056/workflow)
The workflow is not valid. .github/workflows/publish_docs.yml (Line: 11, Col: 3): The identifier 'generate_github.io' is invalid. IDs may only contain alphanumeric characters, '_', and '-'. IDs must start with a letter or '_' and and must be less than 100 characters.
```
@todo: Remove gen doc from TAOS-CI

[Action] Fix action job name

---

ext/nnstreamer/tensor_decoder/box_properties/yolo.cc
ext/nnstreamer/tensor_decoder/tensordec-boundingbox.cc

- Free allocated memory in boundingbox
- Use `g_autofree gchar*` to clean code.

[CodeClean] Fix memleak and clean code in boundingbox

---

.github/workflows/publish_docs.yml
.github/workflows/update_gbs_cache.yml
.github/workflows/update_pbuilder_cache.yml

Change daily release path to apply lifecycle rule for each directory.
Release URL: release.nnstreamer.com
*S3 does not support symbolic link.

[Action] Change daily release path

---

ext/nnstreamer/extra/nnstreamer_protobuf.cc
ext/nnstreamer/tensor_decoder/tensordec-boundingbox.cc
ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc
ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
ext/nnstreamer/tensor_decoder/tensordec-pose.c
ext/nnstreamer/tensor_decoder/tensordec-python3.cc
tests/nnstreamer_decoder/unittest_decoder.cc

If gst-buffer has multiple mem blocks, memory from get-all-memory function does not update original data.
Update function - replace old memory.

[CodeClean] invalid function to handle mem block

---

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc

[prop `OutputTensor`]
- Let snpe subplugin set output tensor names provided by `OutputTensor`
custom property.
- Each name should be sepearted by `;` (if OutputTensor is plural)
- Example usage:
... model=model.dlc custom=OutputTensor:"output_0;output_1" ...
[prop `InputType` and `OutputType`]
- Let snpe subplugin set types for input/output tensors.
- The value should be one of {"FLOAT32", "TF8"}
- Each value should be seperated by `;` (if plural)
- The order should follow the order of input/output tensors in the model.
- Example usage:
... custom=InputType:TF8,OutputType:"FLOAT32,FLOAT32" ...
- If type is not specified, use default type of the given model.
- quanitzed model can use both float32 and tf8,
non-quantized model can only use float32.
1. Build test: …

[filter] Add custom prop `OutputTensor`, `OutputType`, and `InputType` for snpe 

---

ext/nnstreamer/tensor_filter/tensor_filter_qnn.cc
gst/nnstreamer/tensor_filter/tensor_filter.c

- Set proper option to context_config.
-  Fix log of filter subplugin's name 

[filter] Fix qnn context config

---

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
ext/nnstreamer/tensor_filter/tensor_filter_snpe_v1.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc

- QNN / SNPE filters on Qualcomm Android require additional job to use Qualcomm's DSP / NPU.
- Remove the redundant codes and let the job executed in MLAPI/Android.
This and https://github.com/nnstreamer/api/pull/556 should be merged together.

[filter] Remove initalizing for Qualcomm Android

---

ext/nnstreamer/tensor_filter/tensor_filter_qnn.cc

- Set `tensor.v1.memType` properly.
- Fix argument value to `compose_graphs`.
- Use nns_log instead of glib log.

[filter] Fix QNN API usages

---

jni/nnstreamer.mk

- Expose the source code in `jni/nnstreamer.mk` so that api/android build can use it.

[android] Let api-android build QNN tensor_filter

---

packaging/nnstreamer.spec

This patch disables the mlops-agent on VD Cosmos infra.

[spec] Disable mlops-agent on VD Cosmos infra

---

.github/workflows/ubuntu_clean_llvm_build.yml
.github/workflows/ubuntu_clean_meson_build.yml

upload-artifact v1 is obsolete and github-action rejects running it.

github-action: update upload-artifact

---

gst/datarepo/gstdatareposrc.c
gst/nnstreamer/elements/gsttensor_transform.c
tests/get_available_port.py

This resolves some CodeQL alerts
- Binding test socket to a address
- Converting to larger type

[fix] Resolve CodeQL alerts

---

.github/workflows/gbs_build.yml
.github/workflows/update_gbs_cache.yml

Let's gbs build and check nntrainer not per PR but daily.
- gbs build nntrainer for every PR is bothersome. It takes more than 20 minutes.
- nntrainer check its nnstreamer compatability in its CI

[action] gbs build nntrainer daily not per PR

---

tests/nnstreamer_edge/nnstreamer-edge-custom-test.c

Code clean, fix mem leak case when invoking event callback with data.

[Test/Edge] fix mem leak

---

jni/nnstreamer.mk

This patch modifies nnstreamer.mk to import TensorFilter sub-plugin for llama2.c into NNStreamer's Android NDK build chain.

JNI/NDK: Add llama2.c sources to nnstreamer.mk

---

ext/nnstreamer/tensor_filter/tensor_filter_llama2.cc

This patch fixes input memory buffer overflow.
Sometimes, there is another string right after input data.
llama2 api uses prompt string directly, so unintended prompt is added in that case.

[llama2] Copy input prompt to prevent buffer overflow

---

gst/nnstreamer/tensor_filter/tensor_filter.c

In case of output combination, in_mem is used after unref the memory.
@todo Refactor long method of tensor_filter.

[Filter] Fix use after free case

---

gst/nnstreamer/include/nnstreamer_cppplugin_api_filter.hh
gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc

- Let cpp-class based subplugins do `invoke_dynamic`.
- If subplugin overrides `invoke_dynamic` filter would call it, otherwise asserts.

[filter] Support invoke-dynamic for cpp subplugins

---

gst/nnstreamer/include/nnstreamer_cppplugin_api_filter.hh

The log util in nnstreamer is not exported, remove invalid header include.

[Filter/cpp] invalid header include

---

ext/nnstreamer/tensor_filter/tensor_filter_executorch.cc

- Fix the executorch `Module` API usage in the sub-plugin.

[filter] Update executorch API usage

---

packaging/nnstreamer.spec

This patch enables the protobuf filter for Movable project.

[Spec] Enable protobuf filter for Movable project

---

tools/development/parser/meson.build

version argument of find_program is avaiable since 0.52. Skip it if it's not 0.52 or higher.
Addresses the secondary point of #4553

meson: 0.50 doesn't support version with find_program

---

packaging/nnstreamer.spec

Test coverage generation has been failed due to gcc bug. Add comile option to fix it.
Refer: https://manpages.debian.org/unstable/lcov/geninfo.1.en.html#negative:

[gcov] Fix test coverage generation failure

---

gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
gst/nnstreamer/meson.build
gst/nnstreamer/nnstreamer_watchdog.c
gst/nnstreamer/nnstreamer_watchdog.h
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter_common.c
gst/nnstreamer/tensor_filter/tensor_filter_common.h
jni/nnstreamer.mk
tests/meson.build
tests/nnstreamer_filter_tensorflow2_lite/unittest_filter_tensorflow2_lite.cc
tests/nnstreamer_watchdog/unittest_watchdog.cc

- Add suspend mode for tensor_filter
- When there is no input within suspend timeout, unload NN framework. Reload the framework when the input comes again.
- Separate watchdog code
- Separate the watchdog because it can be used in other elements to manage time window.
Related issue: https://github.com/nnstreamer/nnstreamer/issues/4424

[Filter] Add suspend mode for tensor_filter

---

.github/workflows/gen_coverage_badge.py
.github/workflows/update_gbs_cache.yml
README.md

- Generate test coverage result and upload the result to github.io
- Generate coverage badge
- Use badge created by Github Action and change the action name for redability.
- Use S3  instead of EC2 for daily release.
test coverage result: https://nnstreamer.github.io/testresult/
test coverage badge: https://nnstreamer.github.io/testresult/coverage_badge.svg
daily release: https://release.nnstreamer.com/#nnstreamer/latest/

[Action] Generate test coverage from github action 

---

packaging/nnstreamer.spec

In case of GCC v14, the build process is stopped when ASAN option is enabled. Build engineer suggested to skip the test in such case to avoid the build failure.

[Spec] Skip test in case that ASAN is enabled

---

ext/nnstreamer/tensor_filter/tensor_filter_llama2.cc
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c

- Let the util function properly set format information.
- Skip copying n-th info if the format is not static.
- Add missing header `nnstreamer_log.h` in llama2 source.

[util] Let `gst_tensors_info_to_string` handle tensor_format

---

ext/nnstreamer/tensor_filter/meson.build

Let executorch filter static lib be installed in nnstreamer_libdir.

[build] Fix install dir of executorch filter

---

.github/workflows/yocto.yml

When there is no Yocto cache, unnecessary packages should be removed due to lack of space in the runner.
We don't need this option when we have the cache.
Activate again if there is no cache.

[Action] Disable making large image

---

debian/control
debian/control.ubuntu.ppa

Pytorch is still not supported with Ubuntu 24.04 PPA. Allow to build deb packages without pytorch.

dist:ubuntu 24.04 ppa support

---

debian/nnstreamer-tensorflow2-lite.install
meson_options.txt
packaging/nnstreamer.spec

tflite2-custom (using custom tflite2 binary per pipeline) is not stable and not maintained.
Disable it from the default builds until it gets stable.

dist: disable tflite2-custom

---

.github/workflows/update_gbs_cache.yml
.github/workflows/update_pbuilder_cache.yml
.github/workflows/yocto.yml

Even if the step failed, the `continue-on-error` was used to continue the next step. 
But `continue-on-error` marks success even if the step fails. 
So, let's use `always()` for subsequent steps.

[Action] Fix for failure case

---

ext/nnstreamer/tensor_filter/tensor_filter_executorch_llama.cc
ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
ext/nnstreamer/tensor_filter/tensor_filter_trix_engine.cc
tests/gstreamer_mqtt/unittest_ntp_util_mock.cc
tests/nnstreamer_example/meson.build

Recently Tizen upgrade its toolchains (gcc 14.1.0 / clang 18.1.6).
This fix complaints from the clang build.
- Remove an unused variable in openvino.cc
- Use `UNUSED` macro for an unused variable in trix_engine.cc
- Add override keyword for some overridden methods.
- Add proper Wno flag to fix compile opencv related sources.

[build] Fix GBS build error with clang

---

.github/actions/gitpush/action.yml

Get git diff size by cli tool.
*Fix daily build failure to publish docs to github.io

[Action] Get git diff size by cli tool

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_llamacpp.cc
meson.build
meson_options.txt

This PR adds llamacpp tensor_filter subplugin.
llama.cpp supports more options like kv cache and lora adapter than the existing llama2.c
See also : https://github.com/ggerganov/llama.cpp/blob/master/examples/simple/simple.cpp
Model from : https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF
```sh
echo "Hello my name is" > input.txt && \
gst-launch-1.0 filesrc location=input.txt ! application/octet-stream ! \
tensor_converter ! other/tensors,format=flexible ! \
tensor_filter framework=llamacpp model=llama-2-7b-chat.Q2_K.gguf invoke-dynamic=TRUE ! \
other/tensors,format=flexible ! tensor_decoder mode=octet_stream ! \
application/octet-stream ! filesink location=output.txt && \
cat output.txt
```
Result
```
llama_model_loader: loaded meta data with 19 key-value pairs and 291 tensors from …
```

[llamacpp] Add llamacpp tensor_filter subplugin 

---

gst/nnstreamer/elements/gsttensor_transform.c
gst/nnstreamer/elements/nnstreamer-orc.orc
tests/nnstreamer_plugins/unittest_plugins.cc

- Add orc functions for 64bit integers and let tensor_transform use 64bit orc funcs.
- Add TCs for {add/mul, typecast from/to} orc funcs which handle 64bit integers.

[orc/transform] Use 64bit int orc funcs in tensor_transform

---

packaging/nnstreamer.spec

Fix lib path when edge_test is enabled.
This will fix integration test failure on nnstreamer-edge repo.

[Test] lib path to run edge test

---

gst/nnstreamer/elements/gsttensor_aggregator.c
gst/nnstreamer/elements/gsttensor_crop.c
gst/nnstreamer/elements/gsttensor_demux.c
gst/nnstreamer/elements/gsttensor_if.c
gst/nnstreamer/elements/gsttensor_sparseenc.c
gst/nnstreamer/elements/gsttensor_split.c
gst/nnstreamer/include/nnstreamer_plugin_api.h
gst/nnstreamer/nnstreamer_plugin_api_impl.c
tests/common/unittest_common.cc

This PR adds common funciton gst_tensors_config_from_cap.
This function parses caps and set tensors config and replaces duplicated code.

[Common] Add function to parse caps and set config 

---

ext/nnstreamer/tensor_filter/tensor_filter_llamacpp.cc

This PR removes unused variables and enables llamacpp sublugin to use custom props.
The length of output could be controlled by num_predict.

[llamacpp] Use custom props in llamacpp subplugin

---

ext/nnstreamer/tensor_decoder/box_properties/yolo.cc
ext/nnstreamer/tensor_decoder/tensordec-boundingbox.cc

This patch fixes `NO_CAST.INTEGER_DIVISON`, `COMPARE_RESULT_OF_NEW`, `UNINIT.CTOR`.
WGID 113301~113303

[CodeClean] Fix coverity issues

---

gst/mqtt/ntputil.c

Fix build error on android, add missing header for socket.

[Element/MQTT] missing header in util

---

.github/workflows/ubuntu_clean_meson_build.yml

Building and running at aarch64 machines
is much faster than at x64 machines.
Note: actions/setup-python@v1 is not compatible with arm machines. Update it to the latest.

action: run ubuntu arm build/test in arm machines

---

.github/workflows/update_gbs_cache.yml

GitHub Action <NNStreamer + NNTrainer gbs build daily test> was failed with the following message.
```
Traceback (most recent call last):
File "/home/runner/work/***/***/.github/workflows/gen_coverage_badge.py", line 16, in <module>
from pybadges import badge
File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/pybadges/__init__.py", line 33, in <module>
import imghdr
ModuleNotFoundError: No module named 'imghdr'
```
https://github.com/nnstreamer/nnstreamer/blob/268d09a28e350b5a443fff3a1479ed931a755f2c/.github/workflows/update_gbs_cache.yml#L81-L90
The reason for this is that the module `imghdr` is no longer part of the Python standard library. It was removed in Python 3.13.
(https://docs.python.org/ko/3/library/imghdr.html)
So, install the module `imghdr` with pip, …

[Action] Fix `NNStreamer + NNTrainer gbs build daily test`

---

.github/workflows/ubuntu_clean_llvm_build.yml
.github/workflows/ubuntu_clean_meson_build.yml

GitHub Action \<Minimal meson build in Ubuntu with LLVM/clang> and \<Minimal meson build in Ubuntu with Valgrind> were failed with the following message.
```
Current runner version: '2.322.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: None
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. 
```
The reason for this is that `action/upload-artifact@v3` is no longer available, since January 30th, 2025.
(https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
So, update version of action/upload-artifact to v4.
1. Build test: [ ]Passed [ …

[Action] action/upload-artifact version update

---

.github/workflows/yocto.yml

Give input to enable acquring large space for yocto build.
Enable this option when there is no yocto cache.

[Action/Yocto] Give input for manual trigerring

---

tests/nnstreamer_grpc/runTest.sh

Fix invalid ini path.
This patch increases test coverage from 78.5% to 81.3%.

[Tests] Fix invalid ini path

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_tizen_hal_snpe.cc
ext/nnstreamer/tensor_filter/tensor_filter_tizen_hal_vivante.cc
meson.build
meson_options.txt
packaging/nnstreamer.spec

- Add snpe and vivante tensor_filter for Tizen HAL.
See also
https://github.com/nnstreamer/hal-api-ml
https://github.com/nnstreamer/hal-backend-ml-accelerator
Diagram
```mermaid
---
title: Tizen ML HAL Architecture
config:
class:
hideEmptyMembersBox: true
---
classDiagram
class hal-backend-ml.git {
hal-backend-ml-snpe
hal-backend-ml-vivante
..
tensor_typedef.h
nnstreamer_plugin_api_filter.h
}
hal-backend-ml.git -- libhal-backend-ml-snpe.so
snpe <|.. hal-backend-ml.git : BuildRequires/Requires
class snpe {
snpe
}
hal-backend-ml.git -- libhal-backend-ml-vivante.so
vivante <|.. hal-backend-ml.git : BuildRequires/Requires
class vivante {
ovxlib
amlogic-vsi-npu-sdk
} …
```

[Tizen HAL] Add tizen hal filters for snpe / vivante

---

packaging/nnstreamer.spec

- Disable hal filters in VD
- Disable building non-HAL filters when HAL is enabled

Fix spec hal

---

.github/workflows/yocto.yml

- Let those steps (generate and uploade badge and logs) note be executed when the yocto-build step is skipped.

[action] Fix yocto workflow to upload build result

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_tizen_hal.cc
packaging/nnstreamer.spec

- Add a new filter for tizen-hal.
- This filter get the user-given hal-backend name as custom prop.
Usage:
`... ! tensor_filter framework=tizen-hal custom=backend:snpe model=path.to.model ! ...`

[filter] Add a new filter for general tizen-hal

---

gst/nnstreamer/elements/gsttensor_crop.c
gst/nnstreamer/elements/gsttensor_demux.c
gst/nnstreamer/elements/gsttensor_if.c
gst/nnstreamer/elements/gsttensor_sparseenc.c
gst/nnstreamer/elements/gsttensor_split.c
gst/nnstreamer/include/nnstreamer_plugin_api.h
gst/nnstreamer/include/nnstreamer_plugin_api_util.h
gst/nnstreamer/nnstreamer_plugin_api_impl.c
gst/nnstreamer/nnstreamer_plugin_api_util_impl.c
gst/nnstreamer/tensor_filter/tensor_filter_common.c
tests/common/unittest_common.cc
tests/nnstreamer_sink/unittest_sink.cc

Update util functions to support old dimension format (padding with 1).
For example, if model has one tensor with shape '1', possible caps includes dimension '1' and '1:1:1:1'.
This PR fixes negotiation failure case using caps-filter.

[Common] caps for compatibility

---

gst/nnstreamer/elements/gsttensor_reposrc.c

When creating buffer, appending tensor may allocate new memory.
Append memory after updating its contents.

[RepoSrc] mem in out buffer

---

ext/nnstreamer/tensor_filter/meson.build

- Remove explicit ggml dep, which is included in llamacpp_support_deps.
2. Run test: [ ]Passed [ ]Failed [ ]Skipped

[build] Fix llamacpp deps in meson.build

---

.github/workflows/publish_docs.yml
.github/workflows/update_gbs_cache.yml
.github/workflows/update_pbuilder_cache.yml

Fix publishing docs 
- Add apt-get update command to prevent possible fetch error.
Fix pubuilder_cache workflow
- Fix python version to 3.11. Recent Python have dropped some packages.
Fix daily gbs cache workflow
- Check nntrainer with `--define 'unit_test 1'` for x86_64 only.
- Do not run testcoverage for nntrainer.

Fix workflows for daily github action

---

gst/nnstreamer/nnstreamer_plugin_api_util_impl.c

While appending memory into gst-buffer, nnstreamer internally checks header in the memory to check flexible tensor.
To remove unnecessary log print, fix condition to validate meta info.

[Common] unnecessary log

---

debian/control
debian/control.ubuntu.ppa
ext/nnstreamer/tensor_filter/meson.build
meson.build
tools/docker/Dockerfile

Update nnfw dep resolving in meson
- Use dep from `target: onert` and `target_alt: nnfw`
- Remove checking old symbol.
Fix dependency nnfw -> onert
- nnfw is deprecated package. Use onert.
Fix docker file to resolve ppa issue
- one-runtime/ppa do not have proper package, remove it.

[build] Fix nnfw build failure issue

---

.github/workflows/gbs_build.yml
.github/workflows/macos.yaml
.github/workflows/pdebuild.yml
.github/workflows/publish_docs.yml
.github/workflows/ubuntu_clean_llvm_build.yml
.github/workflows/ubuntu_clean_meson_build.yml
.github/workflows/update_gbs_cache.yml

- Fix python version to 3.11, which has `imghdr` module.
- Recent versions of cmake is not compatible with hotdoc.
Set certain version of cmake to be used.
- Let all workflows use same `setup-python` (3.11)

[workflow] Fix daily action failures

---

tests/nnstreamer_edge/meson.build

- Let the nnsedge custom lib be loaded during unittest_edge runtime.

[test] Set `LD_LIBRARY_PATH` for unittest_edge

---

.github/workflows/pdebuild.yml
.github/workflows/risc-v.yml
.github/workflows/ubuntu_clean_meson_build.yml

ubuntu-20.04 is deprecated in github actions.
- Remove 20.04 option in pdebuild.yml
- Change 20.04 -> 22.04 for the riscv64-ubuntu workflow.

[workflow] Remove deprecated ubuntu-20.04 workflows

---

gst/nnstreamer/elements/gsttensor_transform.md
tools/debugging/README.md

- Fixed a typo in the `tensor_transform` example usage.
- Updated the `gst-debugger` url: the [GitHub repo](https://github.com/GNOME/gst-debugger.git) is no longer accessible and has been archived on [GitLab](https://gitlab.gnome.org/Archive/gst-debugger.git).

[docs] fix tensor_transform example and gst-debugger url

---

ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc

Adding custom property description for the SNPE subplugin
- Property descriptions were referenced from `tensor_filter_snpe_v1.cc`
- A small implementation difference is the use of `SNPE_FRAMEWORK_NAME` instead of `snpe_subplugin::name`

[SNPE] add custom property description

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.cc

The properties_table contains the list of properties for loaded sub-modules. The properties are only added on initial module load which happens once, this is why the table is a static singleton not tied to the lifecycle of any one BoundingBox instance.
The issue is this table is cleared in the BoundingBox destructor, which means after any BoundingBox instance is removed, no new instances will be able to find any sub-module properties.
Fix this by not clearing the properties_table in the destructor.

[decoder] Do not clear properties_table in BoundingBox destructor

---

.github/workflows/_typos.toml
Documentation/component-description.md
README.md

This patch updates deprecated nxp examples webp url.

Update deprecated url

---

ext/nnstreamer/tensor_filter/tensor_filter_tizen_hal.cc

- custom prop other than "backend" could be used in the hal backend.
- Remove the confusing log.

[filter][tizen-hal] Remove confusing warning log

---

packaging/nnstreamer.spec

This patch enables the nnstreamer-test-devel package when building the robot profile.

[spec] Enable test-devel package for robot profile

---

ext/nnstreamer/tensor_filter/tensor_filter_tizen_hal_snpe.cc
ext/nnstreamer/tensor_filter/tensor_filter_tizen_hal_vivante.cc

- Vivante: copy-pasted name SNPE from snpe fixed.
- SNPE/Vivante: error code of "not supported".
- SNPE: remove unused macro.

filter/hal: snpe/vivante error fix

---

tests/nnstreamer_filter_llamacpp/unittest_filter_llamacpp.cc

Initialize all pointer members to nullptr in constructor to prevent SIGSEGV.
The TearDown() was trying to free uninitialized pointers when GTEST_SKIP() was called. It caused a segmentation fault.

[llama.cpp] Fix SIGSEGV in TearDown when model file is missing
