CMakeLists.txt, gst/tensor_aggregator/CMakeLists.txt, gst/tensor_aggregator/tensor_aggregator.c, gst/tensor_aggregator/tensor_aggregator.h
Plugin to aggregate tensor stream. (used gst-adapter)
1. add properties to set output frames
- frames-in : number of frames in input buffer
- frames-out : number of frames in output buffer
- frames-flush : number of frames to flush data
2. testcase (stream with aggregater) will be added soon.
related issue : #474 [Advanced Queueing] Support aggregation
=> [Aggregater] initial commit - @open sesame 09/04 15:05

gst/tensor_split/gsttensorsplit.c, gst/tensor_split/gsttensorsplit.h
In order to get/set tensor split size, TENSORSEG property is added. To
Manupilate set and get properties function is modified.
=> [TensorSplit] Add Set/Get Properties - @open sesame 08/31 22:14

gst/tensor_decoder/tensordec.c, gst/tensor_decoder/tensordec.h
Updates tensordec before removing media type and format in GstTensorConfig structure
1. add property to set output media type
2. add functions for media caps
- some functions in tensor_common will be removed
=> [Decode] remove dependency of media type in tensor config

common/tensor_common.c, include/tensor_common.h, tests/bmp2png.c, tests/gen24bBMP.py, tests/nnstreamer_converter/generateGoldenTestResult.py, tests/nnstreamer_converter/runTest.sh, tests/testAPI.sh
Relates: #74 
- Adding support for the 8-bit graycale video format, GRAY8
- Modifying tools (such as bmp2png, gen24bBMP.py, and testAPI.sh) in the test framework to support the newly added color format, GRAY8
- Adding test cases for the 8-bit graycale video format (i.e., video/x-raw,format=GRAY8)
=> [Common] Support GRAY8, the 8-bit grayscale video format - @open sesame 09/03 16:57

.github/CODEOWNERS
The usernames at github.com are different from our internal github repo.
Update CODEOWNERS accordingly.
Fixes #497
ps. This does not touch source code.
=> [CODEOWNERS] Update for github.com migration

CODE_OF_CONDUCT.md
This creates CODE OF CONDUCT for nnstreamer, targetting external contributors.
Based on the base CoC template of github.com, I've added "contributors' responsibilities".
Fixes #4
=> Update CODE_OF_CONDUCT.md - @open sesame 09/04 19:17

packaging/nnstreamer.spec, tests/unittestcoverage.py
To check unit test coverage, need 'taos-ci-unittest-coverage' package.
But this package is not provided 'download.tizen.org' so remove that package and add 'unittest.py' file, lcov package.
Related issue: nnsuite/TAOS-CI#126
=> [unittest] Remove dependency

gst/tensor_aggregator/tensor_aggregator.c, gst/tensor_aggregator/tensor_aggregator.h
1. add property to set the index of frames in tensor dimension.
2. add pad query function for caps negotiation.
3. set timestamp to push a buffer to src pad
=> [Aggregator] fix output tensor dimension - @open sesame 09/05 16:36

common/tensor_common.c, gst/tensor_converter/tensor_converter.c, gst/tensor_converter/tensor_converter.h, include/tensor_common.h, tests/nnstreamer_converter/runTest.sh, tests/nnstreamer_sink/unittest_sink.cpp
refactor tensor-converter with gst-adapter, so that this plugin can aggregate the frames.
1. change properties
- add frames-per-tensor to set the number of frames in output tensor
- remove force-memcpy, frames-per-buffer
2. fixed size of string type (GST_TENSOR_STRING_SIZE)
3. remove media format and type in GstTensorConfig
4. add simple testcases to test media stream and data aggregation using tensor-sink
=> [Convert] refactor tensor-converter

gst/tensor_decoder/README.md
This add the new README.md for tensor_decoder.
As partial solution of #490, this follows the format of other #490 related commits
ps. There is no code updates. No need for code tests.
ps2. @jinhyuck-park This commit requires more attention from you as you are working on decoder. I hope this document somewhat resolves your concern.
=> [Documentation] Add README.md entry for tensor_decoder - @open sesame 09/07 13:38

common/tensor_common.c, gst/tensor_demux/gsttensordemux.c, gst/tensor_filter/tensor_filter.c, gst/tensor_mux/gsttensormux.c, gst/tensor_transform/tensor_transform.c, include/tensor_common.h
- Remove rank from pad cap of other/tensor and other/tensors
- Remove dependencies on rank info from plugins
Fixes #515
CC: It appears that this PR requires attention from @helloahn @jaeyun-jung .
=> [Common/Refactor] Remove rank from pad cap

gst/tensor_transform/tensor_transform.c, gst/tensor_transform/tensor_transform.h, tests/transform_arithmetic/checkResult.py, tests/transform_arithmetic/runTest.sh
In addition to typecast and dimchg, we may need simple arithmetic for
element by element in tensor. For example, we need to add or
multiplicate a centain constant to element by element to scale. In
order to cover the requirement another mode called "arithmetic" is
added. The option for the this arithmetic mode is
"(operation):(constnat number)" such as "mul:2.0, add:-128".
"mode=arithmetic, option=add:-128"
One thing we should aware is that we do not gurantee the type of
tensor after the arithmetic operation. For the case of multiplication
with float type to the uint8_t type tensor, the output type should be
float. But in the mode, uint8_t is the type from this mode. That
means the type of output from this mode is always same with input type
of tensor. The user should aware of this and …
=> [Transform] Add Arithmetic Mode - @open sesame 09/07 15:07

gst/tensor_split/gsttensorsplit.c, tests/gen24bBMP.py, tests/nnstreamer_converter/generateGoldenTestResult.py, tests/nnstreamer_split/runTest.sh
In order to check the tensor_split plugin, testcases are added.
- Add 3 tensor split test cases from file source
- Add 3 tensor split test cases from multiplefile sources
=> [TensorSplit] Add testcases - @open sesame 09/05 16:28

gst/tensor_decoder/tensordec.c, gst/tensor_decoder/tensordec.h
Add initial data struct to process labels for tensor from tensor filter
1. Build test: [* ]Passed [ ]Failed [*]Skipped
=> [TensorDec] Add data struct for tensorflow lite labels - @open sesame 09/13 10:19

common/tensor_common.c, gst/tensor_aggregator/tensor_aggregator.c, gst/tensor_converter/tensor_converter.c, gst/tensor_decoder/tensordec.c, gst/tensor_filter/tensor_filter.c, gst/tensor_split/gsttensorsplit.c, include/tensor_common.h, include/tensor_typedef.h, tests/common/unittest_common.cpp, tests/nnstreamer_sink/unittest_sink.cpp
prepare multi-tensors (other/tensors)
1. add new structure and functions for tensor info
2. remove dependency of media info
3. remove the rank of tensor dimension
=> [Common] common functions to prepare multi-tensors

gst/tensor_transform/tensor_transform.c, gst/tensor_transform/tensor_transform.h
We may need transpose operation such as tensor_A[I][J][K][L] to
tensor_B[I][J][L][K].
In order to support this, transpose mode is added. It is working with
"mode=transpose, option=0:1:3:2" (Notice that the first dim is always
fixed).
=> [Transform] Add Transpose Mode

gst/tensor_decoder/tensordec.h
Let's constify mode names as they are not going to be edited in runtime, but switched between predefined strings only.
=> [Decoder] Minor style fix (variable types) - @open sesame 09/13 18:10

gst/tensor_filter/tensor_filter_custom.c
We check filter->privateData to see if the custom filter (.so) is already loaded or not.
Thus, in order to prevent duplicated filter loading, we need to ensure that
the created private data (*private_data) is stored at the desired location (filter->privateData).
=> [Filter/Custom] Ensure the loaded private data is stored at the desired position

common/tensor_common.c, gst/tensor_filter/tensor_filter.c, gst/tensor_filter/tensor_filter.h, gst/tensor_filter/tensor_filter_custom.c, gst/tensor_filter/tensor_filter_tensorflow.c, gst/tensor_filter/tensor_filter_tensorflow_core.cc, gst/tensor_filter/tensor_filter_tensorflow_lite.c, gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc, include/tensor_common.h, include/tensor_filter_custom.h, include/tensor_filter_tensorflow_core.h, include/tensor_filter_tensorflow_lite_core.h, include/tensor_typedef.h, nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c, nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c, nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough_variable.c, nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c, nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c, tests/common/unittest_common.cpp, tests/nnstreamer_sink/unittest_sink.cpp
refactor tensor-filter to support multi-tensors (other/tensors).
tf and tf-lte should be updated later for multi-tensors.
1. add common GstTensorsInfo in tensor-filter and parse from NN model
2. change NN framework properties
3. fix the bug in common functions for multi-tensors
4. remove space to get tensor dim and type in common function
=> [Filter/Common] prepare multi-tensors

gst/tensor_transform/tensor_transform.c
If it is < 0 or >= 4, it is not valid and breaks the buffer.
Supposed to Fix #552 (Didn't get through that static analysis tool. @leemgs please proceed with this.)
ps. @jijoongmoon : You do not have unit testcases for transpose!
CC: Jijoong Moon <jijoong.moon@samsung.com>
=> [Transform/Transpose] Check the validity of dimensions

gst/tensor_filter/tensor_filter.c, gst/tensor_filter/tensor_filter.h, gst/tensor_filter/tensor_filter_custom.c, gst/tensor_filter/tensor_filter_tensorflow.c, gst/tensor_filter/tensor_filter_tensorflow_core.cc, gst/tensor_filter/tensor_filter_tensorflow_lite.c, gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc, include/tensor_filter_custom.h, include/tensor_filter_tensorflow_core.h, include/tensor_filter_tensorflow_lite_core.h, include/tensor_typedef.h, nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c, nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c, nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough_variable.c, nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c, nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c
Change framework callbacks to support multi-tensors.
To support multi tensors,
1. GstTensorFilter allocates the memory block for each output tensor.
2. Fill input and output tensor info (GstTensorMemory)
3. GstTensorFilter calls 'invoke' with the structure GstTensorMemory.
=> [Filter] change filter-framework callbacks

nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c
Unsigned variables cannot be less than 0.
Do not check if they are less than 0.
Addresses one item of #558.
=> [Example/CustomFilterScaler] Fix coverity analysis error 1029511

gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc
1. variable initialization was cleared by #555 (they were removed). 
2. make a useless line as a comment for future.
It's about #558.
Signed-off-by: HyoungjooAhn <hello.ahn@samsung.com>
=> [Filter] Fix coverity analysis error - @open sesame 09/20 21:12 

gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc
Since tensor_transform will do typecast and data nomalization, temporal nomalization code is useless.
=> [Filter/TF-Lite] fix bug about nomalization

gst/tensor_transform/tensor_transform.c
Fixed issue https://github.com/nnsuite/nnstreamer/issues/552.
This commit is to fix a security issue that is reported by CPPCheck and SVACE tool.
1. Initialized in and out variable to avoid a buffer overflow issue.
* SVACE Checker:
```bash
BUFFER_OVERFLOW.PROC
Array 'in' of size 16 bytes passed to function 'gst_tensor_dimension_conversion' at tensor_transform.c:968
by passing as 5th parameter to function 'gst_tensor_dimension_conversion' at tensor_transform.c:1016,
where it is accessed by unacceptable index. This may lead to buffer overflow.
Trace Message
buffer overflow
┗ Shift at tensor_transform.c:968
┗ Variable '↦in[0]' is passed to function 'gst_tensor_dimension_conversion' as 5th parameter
at tensor_transform.c:1016 at …
```
=> Security: fix buffer overflow issue in gst_tensor_dimension_conversion

gst/tensor_mux/gsttensormux.c, gst/tensor_mux/gsttensormux.h
Parse incoming caps of single tensor and push it to tensors config.
After that, make caps for multi-tensors using tensors config.
=> [Mux] remove dependency of tensor-meta

nnstreamer_example/example_filter_performance_profile/nnstreamer_example_filter_performance_profile.c
This PR addresses #558.
In this PR, coverity analysis errors 1029505 and 1029509.
- Removing logically dead code, which is duplicated by mistake (1029505)
- Adding an initialization of a structure variable to fix the "Uninitialized scalar variable" issue (1029509)
In addition, the file header comment is slightly revised.
=> [Example/FilterPerformanceProfile] Fix coverity analysis errors 1029505 and 1029509

gst/tensor_split/gsttensorsplit.c, tests/nnstreamer_split/runTest.sh
When we write tensor dimension, it should be [C][W][H][B].
But before this PR, it considered C array type [B][H][W][C].
Resolves: #538
=> [TensorSplit] Fix Tensor dimension type assign

gst/tensor_saveload/tensor_load.c, tests/nnstreamer_tensors/tensors_test/gsttensorscheck.c, tests/nnstreamer_tensors/tensors_test/gsttensorscheck.h, tests/nnstreamer_tensors/tensors_test/gsttesttensors.c, tests/nnstreamer_tensors/tensors_test/gsttesttensors.h
1. Refactor test plugins to remove tensor-meta.
(these elements are for testing multi-tensors only)
2. Remove unnecessary header in saveload.
=> [Test/Meta] remove dependency of tensor-meta

gst/tensor_mux/gsttensormux.c
1. add timestamp (pts and dts) in output buffer
2. change default property value (silent true)
=> [Mux] set timestamp in output buffer

common/tensor_meta.c, gst/tensor_filter/tensor_filter.c, gst/tensor_filter/tensor_filter.h, gst/tensor_filter/tensor_filter_custom.c, gst/tensor_filter/tensor_filter_tensorflow.c, gst/tensor_filter/tensor_filter_tensorflow_lite.c, include/tensor_filter_custom.h, include/tensor_meta.h, include/tensor_typedef.h
This patch fixes the broken links instead of 'TO-BE-DETERMINED-SOON'
comment on boilerplate code.
Change-Id: I6776096752a5d52829043cd3ab9d9584154752d2
=> [boilerplate] fix broken links

gst/tensor_demux/gsttensordemux.c, gst/tensor_split/gsttensorsplit.c, gst/tensor_transform/tensor_transform.c
1. [split] remove rank in caps and use common structure to get tensor caps
2. add code to free the array of strings
=> [Split/Demux/Trandform] remove rank and fix mem leak @open sesame 10/02 15:27 

gst/tensor_decoder/tensordec.c, gst/tensor_mux/gsttensormux.c
fix coverity issue 1030251, 1030250 in tensor-decoder and tensor-mux
=> [Mux/Decoder] fix coverity issue

gst/tensor_decoder/tensordec.c
Fixed error: WID:57241610 Copying from string 'label' to 'out_info.data' without null termination at tensordec.c:743 by calling function 'strncpy'.
Reference: https://stackoverflow.com/questions/1453876/why-does-strncpy-not-null-terminate
=> [SVACE-Fix] Fix 376961 / str without termination

nnstreamer_example/example_cam/nnstreamer_example_cam.c, nnstreamer_example/example_filter/nnstreamer_example_filter.py
1. change to videoscale to set 640x480 frame
2. remove framerate in caps filter
=> [Example] change plugin to get scaled video frame from v4l2

gst/tensor_decoder/tensordec.c
Add install properties mode and mode-option-1 for tensor decoder
processing image labeling
=> [TensorDec] Add install properties in tensor decoder init

gst/tensor_converter/tensor_converter.c, gst/tensor_converter/tensor_converter.h, tests/nnstreamer_sink/unittest_sink.cpp
add new properties input-dim and input-type to get tensor info from byte-stream (application/octet-stream)
add testcase for byte-stream
=> [Converter] support byte-stream @open sesame 10/08 22:10

gst/tensor_transform/tensor_transform.c
Use NNS_TENSOR_RANK_LIMIT instead of 4 for transpose.
Resolves: #537
=> [Transform] Remove hard coded values in transform

gst/tensor_transform/tensor_transform.c, gst/tensor_transform/tensor_transform.h
Add Standardization Mode (mode=stand, option=default). Could be added
more methods.
for Tensor T,
: out[i] = fabs((T[i] - average(T)) / (stand(T) + 1e-10))
=> [Transform] Add Standardization Mode in Tranform Plugin @open sesame 10/10 10:41

packaging/nnstreamer.spec, tests/transform_stand/checkResult.py, tests/transform_stand/generateTest.py, tests/transform_stand/runTest.sh
Add Test Case for standardization mode.
Compare the result with python and approval diff is
-0.01 < diff < 0.01. (application/octet-stream mime is used.)
=> [Transform] Add Test Case for transform/standardization mode @open sesame 10/11 10:33

tests/transform_typecast/runTest.sh
This PR adds more test cases for testing the typecast operation between floating point types and integer types. 
=> [Test/Transform] Add test cases for typecast between float and integer - @open sesame 10/10 19:32

gst/tensor_transform/tensor_transform.c
There was wrong tensor and C array index in transpose mode.
Before this patch, the batch is the first index of C array or Tensor.
Batch should be last index.
=> [Transform] Fix transpose @open sesame 10/10 10:41

common/tensor_common.c
update code to check array size limit, tensors max is now 16.
Related issue : #635
=> [Common] check max tensor size limit

gst/tensor_transform/tensor_transform.c, gst/tensor_transform/tensor_transform.h, tests/transform_arithmetic/checkResult.py, tests/transform_arithmetic/runTest.sh
Resolves #523 
This PR includes
- supporting operand value of floating point type (the first sub-item of #523)
- supporting add-mul and mul-add  (the second sub-item of #523)
- adding several test cases in order to test both above cases
=> [Transform/Arithmetic] Support fused operators such as mul-add and add-mul

common/tensor_common.c, gst/tensor_transform/tensor_transform.c, gst/tensor_transform/tensor_transform.h, include/tensor_common.h, include/tensor_typedef.h
1. use common functions and structure in tensor-transform
2. add macros to print debug message
3. remove functions to parse caps (get_tensor_from_padcap, get_tensor_from_structure in common)
=> [Transform/Common] code clean

gst/tensor_merge/gsttensormerge.c
Fix the derefrencing bug before null check
=> [TensorMerge] fix Dereference before null check

gst/tensor_filter/tensor_filter_tensorflow_lite.c, gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc
`memcpy` was applied for each output tensors of tflite.
It should be a temporal solution and be updated in a better way.
=> [Filter/TF-Lite] apply memcpy for output tensors @open sesame 10/16 21:58

gst/tensor_merge/gsttensormerge.c, gst/tensor_merge/gsttensormerge.h, tests/nnstreamer_merge/generateTest.py, tests/nnstreamer_merge/runTest.sh
Add gst_tensor_merge_generate_mem function to generate output
GstMemory to push.
Now support linear mode and channel, width, height option.
Assume tensor a is aC:aW:aH:aB and b is bC:bW:bH:bB.
if the mode is linear and channel option,
the output tensor is generated by
aC+bC:aW:aH:aB ( should be aH==bH, aW==bW and a.type==b.type ).
That means,
[[aB][aH][aW][aC,bC]]
if linear and width option,
aC:aW+bW:aH,aB ( should be aC==bC, aH==bH and a.type==b.type ).
[[aB][aH][aW,bW][aC]]
if linear and height option
aC:aW:aH+bH,aB (should be aC==bC, aW==bW and a.type==b.type ).
[[aB][aH,bH][aW][aC]]
=> [TensorMerge] Add Proper GstMemory Generation according to direction

gst/tensor_transform/tensor_transform.c, tests/transform_typecast/runTest.sh
Fixes #618 
In order to provide same typecasting results for all architecture, this PR modifies the typecast policy to use signed integer as an intermediate type when casting from floating point types to unsigned integer types.
- [Transform/Typecast] Cast from float to unsigned int via signed int
- [Transform/Typecast/Test] Add test cases for casting from float to uint
=> [Transform/Typecast] Cast from float to unsigned int via signed int

include/tensor_filter_custom.h
Custom filter determines output-memory allocation using the function allocate_invoke.
(set true if allocate_invoke defined)
=> [Filter/Custom] remove unnecessary flag

gst/tensor_decoder/tensordec.c
Fixed issue #690.
This commit is to fix not null termination issue in strncpy library call
in the tensor decoder element.
strncpy() supposedly protects from buffer overflows. But if it prevents
an overflow without null terminating, in all likelyhood a subsequent
string operation is going to overflow.
**Change proposed in this PR:**
* Version 3:
1. Commented security issue and Gstreamer (gstbasetextoverlay.c) policy
* Version 2:
1. Replasced strncpy with memcpy.
2. Added annotation.
* Version 1:
1. Fixed not null termination issue of strncpy() by using memset().
=> [Tensor Decoder] Security: fixed not null termination of strncpy(3)

nnstreamer.pc.in
This PR is also related to #698.
The existing input file for pkg-config uses the hard-coded path, '/usr/include', to set the location to install the header files. In order to improve portability, this PR replaces '/usr/include' with @INCLUDE_INSTALL_DIR@ which is provided from the build script.
=> [PkgConfig] Use @INCLUDE_INSTALL_DIR@ instead of the hard-coded path

gst/tensor_aggregator/tensor_aggregator.c
unref old event and push the configured tensor caps to src pad
=> [Aggregator] fix new caps event in sink-pad

gst/tensor_merge/gsttensormerge.c, gst/tensor_merge/gsttensormerge.h
We need time synchronization based on PTS (GST_FORMAT_TIME).
if there is three src with 30/1, 20/1, 10/1 framerates, then it should
be synchronized as follow.
```
src_0              src_1                 src_2
(Synch) 000000000          000000000             000000000 : merged
(Drop)   33333333
(Drop)   66666666           50000000
(Synch)  99999999          100000000             100000000 : merged
(Drop)  133333333
(Drop)  166666666          150000000
(Synch) 199999999          200000000             200000000 : merged
(Drop)  233333333
(Drop)  266666666          250000000
(Synch) 299999999          300000000             300000000 : merged
....
```
In order to do this, gst_tensor_merge_collect_buffer() is modified.
2. Run …
=> [TensorMerge] Add Synchronization based on PTS Time

gst/tensor_converter/tensor_converter.c, gst/tensor_converter/tensor_converter.h, tests/nnstreamer_sink/unittest_sink.cpp
[Project NS] invalid timestamp in byte-stream
tensor-converter sets new timestamp if incoming buffer has invalid timestamp.
1. push time formatted segment event to down-stream.
2. add new property to set timestamp.
3. set timestamp using framerate.
=> [Converter] handle segment and timestamp

gst/tensor_merge/gsttensormerge.c
to fix coverity issue, use GST_CLOCK_DIFF to get time-diff of buffer pts time.
(pts is unsigned value, diff of two buffer timestamp always returns unsigned value)
=> [Merge] change code to compare timestamp @open sesame 10/30 19:50

gst/tensor_aggregator/tensor_aggregator.c, gst/tensor_converter/tensor_converter.c
for accept-caps query in sink pad, change condition to set the query result.
(true when caps is fixed)
=> [Converter/Aggregator] change condition for caps query

gst/tensor_merge/gsttensormerge.c
Fix wrong gst_buffer_unref call. 
If this call exist, pad->buffer will be invalid.
=> [TensorMerge] Fix gst_buffer_unref error

tests/nnstreamer_mux/runTest.sh
Add test cases to test time synchronization.
1. sink_0 (30FPS), sink_1 (10FPS)
2. sink_0 (30FPS), sink_1 (20FPS)
3. sink_0 (30FPS), sink_1 (20FPS), sink_1 (20FPS)
=> [TensorMux] Add time synchronization test case @open sesame 11/02 16:45

gst/tensor_decoder/tensordec.c, gst/tensor_decoder/tensordec.h
The decoder mode determins output type.
Thus, we do not need to supply output types as properties.
Fixes #667
=> [Decoder] We do not need to configure output types.

nnstreamer_example/custom_example_opencv/CMakeLists.txt, nnstreamer_example/custom_example_opencv/nnstreamer_customfilter_opencv_average.cc, tests/nnstreamer_filter_custom/runTest.sh
This patch newly adds an OpenCV custom filter example, which calculates
the average value of input tensor for each channel. The shape of the
input tensor is [N][y][x][M] and that of the output tensor is [N][1][1][M].
This example is developed based on `nnstreamer_customfilter_example_average.c` file.
* Resolves: #678 
=> [Example/OpenCV] Add OpenCV custom filter example: Average

gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_common.h, gst/tensor_merge/gsttensormerge.c, gst/tensor_merge/gsttensormerge.h, gst/tensor_mux/gsttensormux.c, gst/tensor_mux/gsttensormux.h
There are duplicated function call such as
gst_tensor_mux(merge)_collect_buffer(). It could be extracted and
rewrite as common function. Also there is duplicated structure
definition called GstTensorMux(Merge)PadData. It is placed in
tensor_common.h.
Considering Synchronization Options, It is more reasonable to set 
current_time value as GST_BUFFER_PTS(tensors). Therefore there is no need gst_tensor_merge_compare_pads() function.
=> [Merge/Mux] Extract Common Functions & Data Type @open sesame 11/02 18:04

nnstreamer_example/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c, nnstreamer_example/example_filter/nnstreamer_example_filter.c, nnstreamer_example/example_filter/nnstreamer_example_filter.py, nnstreamer_example/example_object_detection/nnstreamer_example_object_detection.cc
In the example using tf-lite model, add leaky property to drop old buffers (leaky on downstream).
=> [Example] add leaky to drop old buffers @open sesame 11/02 17:59

tools/README.md
This commit is to add a manual to use a GstShark tool to support
tracing and profiling method.
GstShark is an open-source project from Ridgerun that provides
benchmarks and profiling tools for GStreamer 1.7.1 (and above).
It includes tracers for generating debug information plus some tools
to analyze the debug information.
1. Added how to use GstShark
2. Updated GST_DEBUG_DUMP_DOT_DIR usage for debugging
---
=> Tools: Added manual to use GstShark for tracing & profiling @open sesame 11/02 16:31

gst/tensor_decoder/tensordec.h
We don't want future confusion or inconsistency between
enum values and string values
=> [Decoder] Refactor mode name array defs

packaging/nnstreamer.spec
Because of background running, unit test result doesn't reflected.
so fix it.
fix: #767 
---
```bash
Further …
```
=> [TEST] reflect unit test result while gbs build @open sesame 11/05 15:54

tests/recurrent_pipeline/generateTestCase.py, tests/recurrent_pipeline/runTest.sh
In order to test recurrent neural networks,
we need to implement #738 (we surely need new synchronization
policy from tensor_mux/merge)
As the first step of #738, I, hereby, provide
the 4x4 BGRx video/x-raw steam with frame-sequence
identification marks.
Verified with HEX viewer.
=> [Testcase] Recurrent Network, Input Stream @open sesame 11/02 17:47

gst/tensor_filter/tensor_filter_tensorflow_lite.c
the method 'setInputDimension()' is not used in tensorflow_lite.
=> [Filter/TFLite] remove the not used code @open sesame 11/06 18:00

tests/nnstreamer_decoder/runTest.sh
Golden case should be the first parameter for callCompareTest.
=> [Test/Decoder] Fix SSAT usage @open sesame 11/07 11:00

gst/tensor_filter/tensor_filter.c
Assume othercap is "ANY" if cap-size is ZERO.
Fixes #549
=> [Filter] Handle othercap only when it's valid. @open sesame 11/07 10:34

gst/tensor_filter/tensor_filter.c
To support pipeviz, the 4th subissue of #700 is resolved.
- Check if framework is configured (null check) at gst_tensor_filter_load_tensor_info()
- Don't die, get out gracefully if it is not configured and the pipeline wants to starts though.
=> [Filter] null check & die grarefully if not configured. 

gst/tensor_decoder/tensordec.c
If we are using GUI tools or dynamic pipelines,
the initial state may be unknown when a process
probes its mode or states.
Fixes the first subissue of #700
=> [Decoder] Mode may be unknown with get-property - @open sesame 11/08 08:20

gst/tensor_decoder/CMakeLists.txt, gst/tensor_decoder/tensordec-directvideo.c, gst/tensor_decoder/tensordec-plugins.c, gst/tensor_decoder/tensordec.c, gst/tensor_decoder/tensordec.h
**Finally this is ready for review & merge**
This PR allows you to create a decoder using the APIs described in
tensordec.h and tensordec-plugin.c
>  [Decoder] Enable decoder subplugins
Because there will be many decoding mechanisms,
we support subplugins for decoder.
In later commits, we will remove any decoding
mechanisms from the main decoder and the main
decoder (tensordec.c) will only be acting as
main loop for different decoders.
> [Decoder/Plugin] Direct-Video as Plugin
Remove direct-video routines from tensordec.c
Make it an example decoder plugin.
> [Decoder] Add comments on decoder plugin APIs
Fill in more doxygen entries and make the header more readable.
Fixes #760 #581
CC: @jinhyuck-park
1. Build …
=> [Decoder] Plugable Decoders along with an example, "direct video"  - @open sesame 11/08 17:32

gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_common.h, gst/tensor_merge/gsttensormerge.c, gst/tensor_merge/gsttensormerge.h, gst/tensor_mux/gsttensormux.c, gst/tensor_mux/gsttensormux.h, tests/nnstreamer_converter/generateGoldenTestResult.py, tests/nnstreamer_merge/runTest.sh, tests/nnstreamer_mux/runTest.sh
Implement BasePad Time Synchronization Policy. The sync_mode name is
"basepad" and it has sync_options which is base pad number and
duration. It is more like "sync_mode=basepad
sync_option=0:33333333". Duration is GstClockTime (unsigned int 64)
and pad number is unsigned int.
Once this sync_mode is enabled, then the merge time is decided based
on this "basepad". For example, if the framerate of basepad is 30/1,
then the time which is pushed by merge/mux is 33333333, 66666666,
99999999, 133333333, 166666666, etc. Some details are below. It
calculate difference between current time and pts time of updated buffer 
and if it is bigger than duration, it use previous pad buffer.
Test Case 1:
- srcpad0 ( framerate 30/1 ) : basepad with 33333333 duration.
- srcpad1 ( framerate 20/1 )
- srcpad2 ( …
=> [Merge/Mux] Implement BasePad Time Synchronization Policy  - @open sesame 11/08 17:21

gst/tensor_decoder/tensordec.c
This fixes 2nd subissue of #700.
- Do not die for incorrect mode name. Handle it gracefully.
- Enable get-property of plugins.
Note that this requires PR #762 and #796 merged prior.
=> [Decoder] Don't die for mode name & Get plugin name.

packaging/nnstreamer.spec, tests/CMakeLists.txt, tests/nnstreamer_plugins/unittest_plugins.cpp
Added new testcases using gst-harness.
If needs to test simple data conversion in nnstreamer plugins, add tc in unittest_plugins.
=> [Test] add testcase using gst-harness

gst/tensor_filter/tensor_filter.c
Handle incorrect model file path gracefully
because pipeviz users or dynamic-pipeline developers
can react to such cases accordingly.
Emit error, not die when model file is not found.
This is partially addressing #700
=> [Filter] Don't die for model file not found. @open sesame 11/10 20:41

packaging/nnstreamer.spec
For test or other reasons, add timeout flag to gbs build.
---
```bash
Further paragraphs come after blank …
```
=> [GBS] Add timeout flag

gst/tensor_decoder/tensordec-directvideo.c, gst/tensor_decoder/tensordec.c
Do not die when the pipeline has already allocated the exact
size of buffer for you. Just reuse what's already there.
This fixes the 3rd subissue of #700.
=> [Decoder/direct_video] Pipeline may allocate buffer for you already @open sesame 11/14 16:02

gst/tensor_converter/tensor_converter.c, gst/tensor_filter/tensor_filter.c, gst/tensor_filter/tensor_filter.h, gst/tensor_filter/tensor_filter_custom.c, gst/tensor_filter/tensor_filter_tensorflow.c, gst/tensor_filter/tensor_filter_tensorflow_lite.c
Set of workarounds to let tensor_filter work with pipeviz.
Mostly it is related with dynamic tensor_filter configurations
and grace error handling.
=> [Filter/Converter] Support pipeviz with tensor_filter @open sesame 11/14 16:02

tests/CMakeLists.txt, tests/nnstreamer_sink/nnscustom_framecounter.c
- For local internal testing, use custom option to make printouts
- For further synchronization testing, use custom option to add usleep()
The main purpose is to populate more sync-test cases with this custom filter. (resolving #739)
ps. This will further increase unit-test latencies. sorry..
=> [Tests] Upgrade framecounter custom filter

README.md
It is trivial. This commit is to fix incorrect link address
of TAOS-CI configruation folder.
---
=> doc: Fixed an incorrect link

gst/tensor_decoder/tensordec.c, gst/tensor_decoder/tensordec.h
Until we fix #837, I'll keep adding mode-options whenever needed.
Note that there is a bug for the previous option (Line 761 of tensordec.c in this PR)
However, this bug is fixed with #830 . so don't worry :)
=> [Decoder] Add one more option

nnstreamer_example/example_filter/nnstreamer_example_filter.c, nnstreamer_example/example_object_detection/nnstreamer_example_object_detection.cc
change function to free list (elements in the list contain the dynamic-allocated memory, we should free all these elements)
=> [Example] change free function

gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_typedef.h, gst/tensor_decoder/CMakeLists.txt, gst/tensor_decoder/tensordec-directvideo.c, gst/tensor_decoder/tensordec-imagelabel.c, gst/tensor_decoder/tensordec.c, gst/tensor_decoder/tensordec.h, tools/development/getTestModels.sh
Pluginize the image labeling mechanism.
1. [Common] Provide union of tensor elements.
- This makes C++ template-like usage of tensor elements EASIER.
2. [Tools] Update getTestModels after path migration
- Because getTestModels.sh has been moved, the path description in the script should be updated as well.
3. [Common] add todo item on comparing framerates.
- 1/2 == 2/4. Don't assert they are different.
4. [Decoder] Pluginize image labeling
- Pluginize the image labeling mechanism.
5. [Decoder] Fully pluginize decoders
- Remove all decoder implenmentations from decoder main.
=> [Decoder] Pluginize image labeling

nnstreamer_example/example_filter_performance_profile/nnstreamer_example_filter_performance_profile.c
This patch fixed a type found at capsfilter's "height" property.
Having it fixed, we were able to run the example successfully
along with our MIPI camera on ARTIK devkit.
Signed-off-by: Hwansoon Sung <hs2704.sung@samsung.com>
---
```bash
various tools …
```
=> [Example/FilterPerformanceProfile] Fix on capsfilter

debian/control
Since tensorflow-dev package is only built for amd64 and arm64 on launchpad.net, nnstreamer for armhf and i386 count not be built. In order to solve this issue, this patch only enables the tensorflow-dev Build-Depends when building amd64 and arm64 architecture.
* related issue: #850 
Change-Id: Ie69058450fc1f05424063536b2afd0ecb140757e
=> [Dist/Debian] Only enable tensorflow-dev Build-Depends when building amd64 and arm64

gst/tensor_decoder/tensordec.c, gst/tensor_decoder/tensordec.h, nnstreamer_example/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c, tests/nnstreamer_decoder_image_labeling/runTest.sh
- Refactor option handling codes to handle much more without
damaging code readability.
- Fix decoder parameters in test cases / examples.
For example, bounding box is going to be:
```
option1=ssd
option2=box_priors.txt
option3=labels.txt
option4=640:480
option5=300x300
```
=> [Decoder] option-3 is not enough. Increase to 9

gst/tensor_transform/tensor_transform.c, gst/tensor_transform/tensor_transform.h, nnstreamer_example/example_object_detection/nnstreamer_example_object_detection.cc, tests/nnstreamer_plugins/unittest_plugins.cpp, tests/transform_arithmetic/runTest.sh
refactor arith and typecast mode to handle arithmetic in sequence
1. define structure for tensor element value
2. add operators to handle tensor element with parsed option
3. remove multi-op (add-mul and mul-add)
4. change arith / typecast mode with added structure and functions
=> [Transform] refactor arith / typecast mode

gst/tensor_transform/tensor_transform.c
1. If there exists pre-configured list for arith operators, free it before parsing new option.
2. Remove duplicated code in the loop of arith mode.
=> [Transform] free operators list

packaging/nnstreamer.spec
SSAT writes colored text by default.
Apply -n (nocolor) in .spec so that SSAT writes non-colored results,
which will no more break OBS build logs.
=> DIST: Fix broken OBS build log of unit tests

gst/tensor_transform/tensor_transform.c
It is supposed to do float -> signed -> unsigned.
This is regression due to the omitted per-pr arm testing :(
Fixes #882
CC: @jaeyun-jung  (I guess this is regression after refactoring transform)
CC: @wooksong (I guess you once tackled the same issue before)
=> [Transform/Typecast] Fix float -> unsigned bug @open sesame 11/23 11:26

gst/tensor_decoder/tensordec-boundingbox.c
1. init struct detected-object
2. remove macro with no effect (unsigned compare)
=> [Decoder] fix coverity issue

gst/nnstreamer/tensor_typedef.h
There is a missing header in typedef header.
Without stdint.h, you won't be able to find "uint8_t".
=> [Common] build error fix for ubuntu/example.

gst/tensor_converter/tensor_converter.c, nnstreamer_example/example_filter/nnstreamer_example_filter.c, nnstreamer_example/example_filter/nnstreamer_example_filter.py
1. When received caps query, get the possible caps of peer pad and convert it to media caps.
Related issue #818
2. Remove caps-filter in example app
=> [Converter] get possible caps from downstream - @open sesame 11/26 18:44

gst/nnstreamer/meson.build, gst/tensor_repopush/meson.build, meson.build
Both Tizen and Ubuntu/Xenial does not support meson 0.47.
Lower down the Meson version requirement.
Fixes #897
=> [Meson] Support Ubuntu/Xenial and Tizen.

gst/tensor_filter/tensor_filter.c
This fixes the coverity issue, pointer out of scope.
=> [Filter] Fix coverity issue, pointer out of scope. @open sesame 11/26 16:54

CMakeLists.txt, debian/control, gst/nnstreamer/nnstreamer.c, gst/nnstreamer/tensor_common.h, gst/tensor_aggregator/tensor_aggregator.c, gst/tensor_transform/tensor_transform.c, packaging/nnstreamer.spec
1. define macro nns_memcpy/nns_memset
2. include liborc and use orc_memcpy instead in plugin tensor-transform and tensor-aggregator
3. add function orc_init to initialize orc library
TODO check cmake to use orc lib
=> [Transform/Orc] replace memcpy @open sesame 11/28 18:52

gst/nnstreamer/nnstreamer_conf.c
The returned object must be closed.
Reported-by: Wook Song <wook16.song@samsung.com>
CC: @wooksong
=> [Common/Conf] Close g_dir_open instance.

gst/nnstreamer/tensor_repo.c, gst/tensor_reposrc/tensor_reposrc.c
tensor_repo.c::gst_tensor_repo_add_repodata, unlock should be used
before return.
Resolves: #933
=> [Repo] Fix bug return without releasing lock

gst/nnstreamer/nnstreamer_conf.c
With auto-ptr, it tries to access read the pointer.
Thus, it should be initialized somehow.
Fixes Coverity Issue 1036166
=> [Common/Conf] Fix coverity issue, uninitialized pointer read

tests/nnstreamer_repo_lstm/generateTestCase.py, tests/nnstreamer_repo_lstm/runTest.sh
- Add python script to generate input stream & golden data.
- Add runTest.sh to run.
```
repository
+-----------+
+---------------------|  slot 1   |<-------------------- ---+
|                     +-----------+                         |
|  +------------------|  slot 0   |<----------------------+ |
|  |                  +-----------+                       | |
|  |                                                      | |
|  |                  +---+   +---+  +---+                | |
|  +-->repo_src:0 --->|   |-->|   |->|   |-->repo_sink:0 -+ |
+----->repo_src:1 --->| M |   | F |  | D |-->repo_sink:1 ---+
filesrc(new)-->|   |   |   |  |   |  |
+---+   +---+  +---+  -->out_%1d.log
```
2. Run test:	 [X]Passed [ ]Failed [ …
=> [Repo] Add runTest.sh for the dummy LSTM Test @open sesame 11/30 13:37

gst/tensor_decoder/tensordec-imagelabel.c, gst/tensor_decoder/tensordec.c
With dynamic pipeline configurations, the mode/option
properties may become incomplete. Do not die for such status
if the pipeline is not active.
This is critical for GUI toolkits.
Fixes a subitem of #827
=> [Decoder] Do not die for option errors. - @open sesame 11/30 15:09

gst/tensor_filter/tensor_filter.c, gst/tensor_filter/tensor_filter_tensorflow_lite.c
Pipeline Stop does not always mean pipeline close.
A pipeline may be paused and resumed (stop and start).
Thus, do not clean up internal data structure for stop.
Instead just notify the plugins of the events with
callbacks.
=> [Filter] Support pipeline stop and go.

gst/tensor_decoder/tensordec.c
Coverity wants to check the return value of
_tensordec_process_plugin_options.
Let't check and log if there is an unwanted return value.
=> [Decoder] Coverity issue 1036581 fix

CMakeLists.txt, gst/nnstreamer/nnstreamer_subplugin.c, gst/nnstreamer/nnstreamer_subplugin.h
Any subplugin-using elements may call get_subplugin () to
get internal data (set of callbacks) of the subplugin.
Next Step: modify tensor_decoder to use nnstreamer_subplugin.h
and test with it.
=> [Common/Subplugin] Internal API to handle subplugins  - @open sesame 12/01 12:42

tools/nnstreamer-toolkit.py
Fixed issue #878.
This commit is to provide a front-end GUI application to connect
tools such as tracing, debugging, profiling packages.
After doing a packaging work of back-end applications, the each menu
is going to be interconnected each other.
1. Added front-end GUI application
---
=> [Tool] Added a front-end GUI toolkit

gst/tensor_filter/CMakeLists.txt
fix typos at CMakeLists.txt of tensor_filter
=> [Bugfix] fix cmake typo for tensorflow

gst/nnstreamer/tensor_common.h, gst/tensor_transform/tensor_transform.c, gst/tensor_transform/tensor_transform.h
1. Orc feature is defined in config, include config header to prepare meson build.
2. Set default property value with orc feature.
3. Add log message to indicate orc acceleration.
=> [Transform/Orc] code clean to prepare meson

tests/nnstreamer_plugins/unittest_plugins.cpp
Using gst-harness, add testcases for the property acceleration in tensor-transform.
=> [Test] add more testcases

gst/tensor_filter/tensor_filter.c
Recent code commit has introduced the following errors in
modern gcc:
```
[ 20%] Building C object gst/tensor_filter/CMakeFiles/tensor_filterOBJ.dir/tensor_filter.c.o
cd /<<PKGBUILDDIR>>/build/gst/tensor_filter && /usr/bin/cc -DENABLE_TENSORFLOW_LITE -DHAVE_ORC=1 -DVERSION=\"0.1.0\" -I/<<PKGBUILDDIR>>/gst/nnstreamer -isystem /usr/include/gstreamer-1.0 -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/orc-0.4  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -Werror -fPIC -g -std=c89  -Wno-sign-compare   -o CMakeFiles/tensor_filterOBJ.dir/tensor_filter.c.o   -c /<<PKGBUILDDIR>>/gst/tensor_filter/tensor_filter.c
In file included from …
```
=> [Filter] Build Error Fix (gcc > 6)

gst/nnstreamer/tensor_common.c, gst/tensor_mux/gsttensormux.c, tests/nnstreamer_converter/generateGoldenTestResult.py, tests/nnstreamer_mux/runTest.sh
Resolves #982 
Related issues: https://github.com/nnsuite/nnstreamer/issues/858 https://github.com/nnsuite/nnstreamer/issues/902 
This PR makes the TensorMux element support multi-tenosrs for input stream. In addition, unit test cases for multiplexing of multi-tensors are added. 
**Changes in this PR**
- [V3] @jaeyun-jung tensor_common.c is revised according to https://github.com/nnsuite/nnstreamer/pull/991#pullrequestreview-185982273.
- [V2] @jaeyun-jung The code for checking that the number of tensors in the merged multi-tensors does not exceed NNS_TENSOR_SIZE_LIMIT is revised. 
- Unnecessary blank line is removed.
- g_assert is added in order to make sure that the number of memory in GstBuffer and the number of tensors that the GstBuffer represents are same. 
1. …
=> [TensorMux] Support multi-tensors for input

gst/tensor_filter/tensor_filter_tensorflow_core.cc, gst/tensor_filter/tensor_filter_tensorflow_core.h, gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc, gst/tensor_filter/tensor_filter_tensorflow_lite_core.h
remove dependency of tensor-common and unnecessary headers
=> [Filter/TF/TF-lite] remove link of tensor-common

gst/nnstreamer/tensor_converter/tensor_converter.c
Updating tensor info property may cause an error when doing caps negotiation.
related issue : #941
error case:
1. run pipeviz (e.g., videotestsrc - capsfilter - tensor_converter - tensor_sink)
2. set caps video/x-raw,format=RGB,width=640,height=480 in capsfilter and run pipeline
3. stop pipeline, and change caps (width=320,height=240)
4. run pipeline again, then it will make caps-negotiation failure.
If set tensor_info (line 1199), stop and run pipeline again,
- It resets the flag tensor_configured false. (in gst_tensor_converter_change_state())
- After running pipeline again, gst_tensor_info_validate (line 1189) returned true
and in-caps is different with saved tensor_info. This makes caps-negotiation failure.
=> [Converter] remove code to update property

gst/nnstreamer/tensor_decoder/tensordec-plugins.c, gst/nnstreamer/tensor_decoder/tensordec.c, gst/nnstreamer/tensor_decoder/tensordec.h, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter.h, gst/nnstreamer/tensor_filter/tensor_filter_custom.c, gst/nnstreamer/tensor_filter/tensor_filter_tensorflow.c, gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c, gst/nnstreamer/tensor_typedef.h
Allow tensor_filter sub-plugins to be independently built
and attached/detached in run-time with subplugin APIs.
This resolves one of "future work" in ATC 2019 submitted paper already :)
Objective:
#786 & #846 
- Allow independently developed and built subplugins for tensor_filter
- Search for sub-plugins in a pre-defined paths amd env-var
- Flexing muscles for coding after the long disappearance.
=> Plug-and-play sub-plugins for Tensor_Filter

packaging/nnstreamer.spec
installing libraries (.a) is unnecessary with meson.
=> [Build] remove unnecessary installation

gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_common.h, gst/nnstreamer/tensor_filter/tensor_filter.c, tests/common/unittest_common.cpp
Add common functions to handle the fomatted string of dimension, type, and name in tensors info.
=> [Filter/Common] common functions for tensor info - @open sesame 01/14 18:23

gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter.h, gst/nnstreamer/tensor_filter/tensor_filter_custom.c, gst/nnstreamer/tensor_filter_custom.h
It will handle the data pointer after GstMemory being destoryed.
If there is no specific method, it will be g_free() as a default.
This method will be useful to remove `memcpy` at tensorflow.
=> [Filter] add a method destoryNotify() to handle data pointer @open sesame 1/17 17:20 

nnstreamer_example/custom_example_opencv/nnstreamer_customfilter_opencv_scaler.cc
add destroy_notify callback at the example using allocate_invoke.
=> [Filter/Example] apply destroyNotify() callback at example

gst/nnstreamer/tensor_filter/tensor_filter_tensorflow.c, gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc, gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h
1. get the data pointer directly from tensor rather than copy each data.
2. to use data pointer properly, increase ref counter of Tensor by storing it in the map.
3. maintain the output tensors for a while and erase it from the map when `destroyNotify()` is called.
it closes #1016 and closes #973
=> [Filter/Tensorflow] remove memcpy of the output tensor - @open sesame 1/21 10:26

.TAOS-CI/taos/config/config-plugins-audit.sh
With recent updates on app test and build script,
we no longer have example applications in nnstreamer.git
It should be migrated to nnstreamer-example.git
We should build nnstreamer-example.git for app test, not
example directory in nnstreamer.git
This is an emergency fix for #1047
=> [CI Fix] Temporarily Disable App Test - @open sesame 1/21 16:44

debian/control, debian/nnstreamer.install, debian/rules
Before remocing CMAKE infrastructure,
migrate build system to meson/ninja for debian builds.
TODO
- Disable tensorflow for non-supporting arch in rules.
- Resolve #1024 for Ubuntu 16.04 pdebuild
2. Run test: [x]Passed [ ]Failed [  ]Skipped
1. Describe how to evaluate in order to be reproduced by reviewer(s).
Add signed-off message automatically by running **$git commit -s ...** command.
$ git push origin <your_branch_name>
```
=> DIST: apply meson/ninja to debian build

gst/nnstreamer/tensor_filter/tensor_filter.c
there are some typos about in/out at a comment & exception handling
=> [Filter] correct a misspell and an improper logic

Documentation/getting-started.md
The Debian/Ubuntu build instructions are incomplete, as tensorflow-dev, tensorflow-lite-dev and ssat packages are also needed for it to build.
Update the instructions.
While here, make the nnstreamer_example/example_cam to also work.
With that, it works fine with two cameras:
- HD Pro Webcam C920 (fourcc: YUYV, H264, MJPG);
- Sirius USB2.0 Camera (fourcc: YUYV);
I also tested with a sn9c20x SDK camera, with uses fourcc: GREY.
With this one, on my i7-5557U test machine, the pipeline works, but it gives:
"There may be a timestamping problem, or this computer is too slow."
=> Improve build instructions and make nnstreamer_example to work

gst/nnstreamer/tensor_filter/tensor_filter.c, nnstreamer_example/custom_example_LSTM/dummy_LSTM.c, nnstreamer_example/custom_example_RNN/dummy_RNN.c, nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c
this pr solves the memory leak problem about the `model_file` and the `name` of input/output tensor
* test command
```bash
./tests/nnstreamer_filter_tensorflow/
---------------------------------------------------------------------------------
$ valgrind \
--leak-check=full --log-file=out_valgrind2.log -v --error-limit=no \
gst-launch-1.0 filesrc location=data/9.raw ! application/octet-stream ! \
tensor_converter input-dim=784:1 input-type=uint8 ! tensor_transform mode=arithmetic \
option=typecast:float32,add:-127.5,div:127.5 ! tensor_filter framework=tensorflow \
model=../test_models/models/mnist.pb input=784:1:1:1 inputtype=float32 inputname=input \
output=10:1:1:1 outputtype=float32 outputname=softmax ! filesink location=tensorfilter.out.log
```
* previous state
```bash
...
==27680== …
```
=> [Filter] fix the memory leak at filter - @open sesame 1/23 17:50

gst/nnstreamer/tensor_repo.c, gst/nnstreamer/tensor_repo.h, gst/nnstreamer/tensor_reposink/tensor_reposink.c, gst/nnstreamer/tensor_reposink/tensor_reposink.h, gst/nnstreamer/tensor_reposrc/tensor_reposrc.c, gst/nnstreamer/tensor_reposrc/tensor_reposrc.h
Implement Dynamic slot_id property change of tensor_reposrc and
tensor_reposink. In order to check the status of current repo,
sink_changed(gboolean), sink_id(guint) and src_changed (gboolean),
src_id(guint) variables are added. While waiting buffer from
repo_sink, repo check if this variables are changed using
gst_tensor_repo_check_chagned call, and if it changed, it trys to get
buffer from new slot id. The changing status of repo is set when slot
id property changed using tensor_repo_set_changed.
- Added function calls to check and set the changing status of repo.
- Added variables to control flow in each repo.
Signed-off-by: jijoong.moon …
=>  [Repo] Implement Dynamic Property(slot_id) Change of Repo 

gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_common.h, nnstreamer_example/custom_example_LSTM/dummy_LSTM.c, nnstreamer_example/custom_example_RNN/dummy_RNN.c, nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c, tests/common/unittest_common.cpp
add common function to copy tensor info
TODO:
1. seperate util-functions for developer (custom filter and plugins)
2. update custom examples and nnstreamer plugins with these functions
=> [Common] common function to copy tensor info

debian/changelog, debian/control, packaging/nnstreamer.spec
- Build system migration cmake --> meson
- Support Tensorflow without input/output tensor memcpy
- other/tensor stream format updated
- From 0.1.0, a single property, "dimension", describes the whole dimension instead of "dim1", "dim2", ...
- Objective 1: in the future, we may support tensors with more than 4 dimensions without updating the protocol.
- Objective 2: it was just too ugly.
- Example applications migrated to other git repo to make this repo ready for upstreaming in the fugure and to ensure buildability for third party developers.
- Support run-time attaching subplugins (filter and decoder)
- Support "ini" and envvar configurations for subplugin locations
- Dynamic external recurrences
- Subplugin API sets (draft. do not expect backward compatibility)
- Bug fixes (memory …
=> Release NNStreamer 0.1.0

gst/nnstreamer/tensor_filter/meson.build, packaging/nnstreamer.spec
Subplugin name rule (described at gst/nnstreamer/nnstreamer_subplugin.h)
states:
The filename should be subplugin_prefixes[type]${name}.so
The subplugins should be follow the rule to be recognized by runtime
plug-and-play mechanism of nnstreamer_subplugin.h
This is passing the test only because libnnstreamer.so includes libtensor_filter_*.so in it.
In the later commits, I will remove such inclusion and make them independent plugins.
We will need to configure plugin-search paths appropriately for unit-testing as well as installed systems.
=> [Filter/subplugin] Follow the subplugin naming rule.

gst/nnstreamer/tensor_decoder/tensordec-boundingbox.c, gst/nnstreamer/tensor_filter/tensor_filter.c
make it available to process the output tensors of tensorflow ssd model.
the example script using `tensordec_boundingbox` is included at [this pr](https://github.com/nnsuite/nnstreamer-example/pull/8).
=> [Decoder/Boundingbox] make decoder possible to handle tensorflow ssd model

gst/nnstreamer/tensor_repo.c, gst/nnstreamer/tensor_repo.h, gst/nnstreamer/tensor_reposink/tensor_reposink.c, gst/nnstreamer/tensor_reposink/tensor_reposink.h, gst/nnstreamer/tensor_reposrc/tensor_reposrc.c, gst/nnstreamer/tensor_reposrc/tensor_reposrc.h, tests/meson.build, tests/nnstreamer_repo_dynamicity/runTest.sh, tests/nnstreamer_repo_dynamicity/tensor_repo_dynamic_test.c
In this PR, added repo test application. It constructs pipeline and
change slot id from 0 to 1 after spending time waiting for 200 micro
second.
```
repository
+------------+   +----------+        +-----------------+
| Multi-sink |<--| repo_src |<---+---|     slot 0      |<---+--+
+------------+   +----------+    |   +-----------------+    |  |
+---|     slot 1      |<---+  |
+-----------------+       |
|
+-----------+   +--------+   +-----------+   +-----------+     |
| Multi-src |-->| pngdec |-->| converter |-->| repo_sink |-----+
+-----------+   +--------+   +-----------+   +-----------+
```
=> [Repo] Add test case for repo dynamicity

gst/nnstreamer/nnstreamer_subplugin.c, gst/nnstreamer/nnstreamer_subplugin.h, gst/nnstreamer/tensor_decoder/tensordec-plugins.c, gst/nnstreamer/tensor_filter/tensor_filter.c
With dlopen, consturctor function is loaded, which
may call subplugin-probe.
If it has called subplugin-probe, registering the
subplugin to an element (filter/decoder) specific
internal list, we do not need to register it with
nnstreamer_subplugin structure.
- Add an internal API, "hold_register_subplugin", that
notified nnstremer_subplugin that it has probed already.
- Call "hold_register_subplugin" at probe function.
=> [Subplugin] Do not dlsym if it's already probed.

gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter.h, gst/nnstreamer/tensor_filter/tensor_filter_custom.c, gst/nnstreamer/tensor_filter/tensor_filter_tensorflow.c, gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h, gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c, gst/nnstreamer/tensor_typedef.h
Enable tensor-filter subplugins to be built without
dependencies on tensor_filter.
After this commit, we can build filter subplugins with
the exported "tensor_typedef.h".
This enables #786 and #761
=> [Filter:*] Cut build dependency of filter-subplugin to filter

gst/nnstreamer/nnstreamer_conf.c
If path is NULL, don't give it to glib path library.
Use "./" instead.
=> [Conf] Bugfix: if no path is given, use current dir.

gst/nnstreamer/nnstreamer_conf.c
The last element of vstr should be NULL.
Set NULL for such elements
=> [Conf] Bugfix of array out of bound

tests/nnstreamer_decoder_image_labeling/runTest.sh
If statements of bash uses ==, not =, for equal-comparison
=> [Test] runTest.sh typo

gst/nnstreamer/meson.build, gst/nnstreamer/tensor_transform/meson.build, tests/meson.build
Remove orc-generated files in nnstreamer plugin dep and clean up meson script.
If declares dependency with orc-gen files, it will compile generated file with this dep.
=> [Meson] dependency for generated files

debian/nnstreamer-dev.install, debian/nnstreamer.install, debian/rules, gst/nnstreamer/meson.build, nnstreamer.pc.in, packaging/nnstreamer.spec
1. Add symlink to libnnstreamer.so at _libdir
2. Install tensor-filter subplugins to the tensor-filter
configuration directory, not _libdir.
3. Do not generate api library. We can use libnnstreamer.
=> [DIST] Install path changes, add symlink

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c, gst/nnstreamer/meson.build, gst/nnstreamer/nnstreamer_plugin_api.h, gst/nnstreamer/nnstreamer_plugin_api_decoder.h, gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_decoder/tensordec.h, gst/nnstreamer/tensor_filter/tensor_filter_custom.c
Before:
- nnstreamer_plugin_api.h had mandatory filter APIs and optional APIs for filter/decoder, depend on glib, not supporting decoder mandatory APIs.
After:
- nnstreamer_plugin_api.h has optional APIs only / depend on glib
- nnstreamer_plugin_api_filter.h has mandatory Filter APIs / no dependencies
- nnstremaer_plugin_api_decoder.h has mandatory Decoder APIs / depend on gst
With this, we can completely cut the dependencies on glib for nnstreamer sub-plugin writers.
Besides, "ext-nizing" decoders requires this as well.
Wait for #1090 #1091 #1098 #1099
Fixes #761, #786
=> [API] Filter/Decoder subplugin API headers

gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_converter/tensor_converter.c, gst/nnstreamer/tensor_typedef.h, tests/nnstreamer_sink/unittest_sink.cpp
Remove definition for text size.
Instead, set dimension for text input with the property input-dim in tensor-converter.
=> [Converter] data size of text input

gst/nnstreamer/tensor_transform/tensor_transform.c, gst/nnstreamer/tensor_transform/tensor_transform.h, tests/nnstreamer_plugins/unittest_plugins.cpp
Resolves #946 
This PR mainly addresses the issue related with reaction for the invalid option string of each transform mode. 
- Using regex, each option string is verified before the pipeline starts. 
- When the option string is invalid, the plug-in explicitly displays error messages using g_critical,
- and then, the pipeline is terminated.
- For the arguments of the 'mode' property, the parameter spec is changed from string to enum so that  the gst-inspect-1.0 command can show the supported modes now.
- Format of the valid option strings for each mode is also added to the description of each mode property.
FYI, after this PR,
```bash
$ gst-inspect-1.0 tensor_transform
Factory Details:
Rank                     none (0)
Long-name                TensorTransform
Klass …
```
=> [Wait for other PR]  [Transform] Change reaction for the invalid option string @open sesame 2/15 13:45

debian/rules
See also: https://github.com/nnsuite/nnstreamer-ros/pull/7
This patch creates a symbolic link to libnnstreamer using dh_link.
Before this PR, 
```bash
$ dpkg-deb --contents /home/wook/Downloads/nnstreamer_0.1.1.0-0_201902150620_ubuntu16.04.1_amd64.deb 
drwxr-xr-x root/root         0 2019-02-15 18:32 ./
drwxr-xr-x root/root         0 2019-02-15 18:32 ./etc/
-rw-r--r-- root/root       145 2019-02-15 18:26 ./etc/nnstreamer.ini
drwxr-xr-x root/root         0 2019-02-15 18:32 ./usr/
drwxr-xr-x root/root         0 2019-02-15 18:32 ./usr/share/
drwxr-xr-x root/root         0 2019-02-15 18:32 ./usr/share/doc/
drwxr-xr-x root/root …
```
=> [DIST/Debian] Create a symbolic link to libnnstreamer

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter.h
use common functions to load tf/tf-lite model
1. remove unnecessary functions in sub-plugins (tf/tf-lite)
2. copy and free tensor info to load tf model during the caps negotiation
3. print additional logs when loading model info
=> [Filter] common functions in filter-subplugins

meson.build
This commit is to synchronize the version number of nnstreamer
among the Ubuntu, Gbs, and Meson. The standard number is located
in 'version' tag of ./packaging/nnstreamer.spec file.
* Tizen/gbs:  ./packaging/ (Standard)
* Ubuntu/pdebuild: ./debian/changelog
* meson/build-system: meson.build
---
```bash
subject of the …
```
=> meson: sync version number among ubuntu, gbs, and meson

gst/nnstreamer/tensor_repo.c
This patch is trivial. This commit is to fix a coding style
of header file consistently.
---
=> [tensor_repo] fixed coding style of header file

jni/Android.mk, jni/Application.mk
This commit is to support the ndk-build command that is included in Android
NDK toolkit. This commit is to be enabled in order to run nnstream-based
their applications on Android platform as well as Ubuntu and Tizen.
Signed-off-by: Jijoong Moon <Jijoong.moon@amsung.com>
=> [Android/ARM64, v5] Support ndk-build to run nnstreamer on Android

jni/Application.mk
This commit is to comment the limitation of NDK r12b when developers
try to run NNstreamer on their Android target device.
**Changes
1. Updated coding style of Application.mk
2. Added annotation on NDK r12b
---
=> [Android] ARM64: Added supported API level of NDK r12b

gst/nnstreamer/tensor_split/gsttensorsplit.c
It should be "verbose" if silent is false.
If it's "silent", it should not emit too many messages.
=> [Decoder] Bugfix: silent semantics reversed.

gst/nnstreamer/tensor_filter/tensor_filter.c
Check if open() is successful at the start().
Note that other usage of gst_tensor_filter_open_fw()
if called by gst_tensor_filter_call(), whose
success is checked by "ret" value if required; there
are cases where a "fail" is an option.
Note that by checking it at start callback,
we can ensure that it's successfully opened for
every pipeline start.
Fixes #1160
CC: @boxerab
=> [Filter] Check if open is successful.

jni/README.md
This commit is to append a document to describe how to compile
the nnstreamer repository with the ndk-build command to get the
libnnstreamer for Android software platform. The ndk-build
is provided by Android NDK toolkit.
=> doc: Add how to generate libnnstreamer.so with ndk-build

ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
Normal operation information log should not use "GST_ERROR".
=> [Decoder/DV] INFO, instead of ERR, for normal log

gst/nnstreamer/tensor_split/gsttensorsplit.c
1. Do not print "," as the first character: write "seg1,seg2,seg3" instead of ",seg1,seg2,seg3".
2. Free memory!
=> [Decoder] Bugfix: get_property/tensorseg format error

packaging/nnstreamer.spec
The files in /ext/* are officially released code.
Publish the lcov result.
This prepares #1153
=> [CI] Add /ext/* to unit-test-coverage scope

gst/nnstreamer/tensor_decoder/tensordec.c, gst/nnstreamer/tensor_filter/tensor_filter.c
If subplugin is not found or not configured,
do not proceed with GSTCAP negotiation or STREAM-START.
Fixes #1092
=> [Filter/Decoder] Exception handling of not found subplugin

CHANGES, debian/changelog, packaging/nnstreamer.spec
Along with Mini Summit #4, nnstreamer 0.1.1 is released.
=> Release of 0.1.1 / Start of 0.1.2-RC

jni/Android-app.mk, jni/Android-nnstreamer.mk, jni/Application.mk
This commit is to improve the writing style of the existing ABI
(CPU architecture) with a method that is described at the documentation
website of the Android NDK toolkit.
* https://developer.android.com/ndk/guides
---
=> Android/ARM64: Improve how to specify CPU architecture(ABI)

jni/README.md
This commit is to update the existing building manual to generate
NNstreamer library (e.g., libnnstreamer.so) and a test application.
**Changelog**
1. Updated the existing ndk-build manual
2. doc: replaced ndk-r16b with ndk-r12b
---
=> [Android/ARM64] doc: updated how to build nnstreamer and test app

gst/nnstreamer/tensor_demux/gsttensordemux.c, gst/nnstreamer/tensor_split/gsttensorsplit.c
remove memory corresponding to get_property
replacing g_value_set_string() with g_value_take_string() to release ownership of strings.
=> [demux/split] memory leak

ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
Allow 0/1 framerate in decoder-direct video mode
=> [Decoder/DirectVideo] 0/1 framerate

jni/Android-app.mk
This commit is to specify a variable to maintain the custom linker64.
This build script handles how to run the NNstreamer-based 64bit application
on Android 32bit platform. If the tart device is based on Android 64bit platform,
We do not need to use the custom linker64 repeatedly on the device.
---
=> [Android/ARM64] linker64: added a variable to maintain custom linker64

jni/Android-app.mk, jni/Android-nnstreamer.mk
This commit is to update correctly the existing path of libs and obj folder
after improving the configuration file to generate a C/C++ library.
**Changelog**
1. Fixed indentation
2. Replaced ../{libs,obj} with ./{libs,obj}
---
=> Android/ARM64: fixed incorrect path of libs/obj

packaging/nnstreamer.spec
-orc file generated while building nnstreamer.
Exclude this in unittest coverage report.
=> [Test] exclude orc file in coverage

debian/control
In Ubuntu PPA, there is tensorflow-dev, not tensorflow, which
includes both devel and libraries.
As a workaround, make it depends on either of the two.
Fixes #1204
Addresses https://github.com/nnsuite/nnstreamer-example/issues/21
=> [Workaround] There is no tensorflow deb in the PPA

gst/nnstreamer/tensor_filter/tensor_filter.c
If an extension (e.g., nnstreamer-tensorflow) is missing,
the error message must be explicit and visible even without
GST_DEBUG envvars; most applications developers won't know it.
However, we cannot alarm them at the stage of set-properties.
Thus, delay alarming until it becomes "fatal".
Fixes #1206
Helps https://github.com/nnsuite/nnstreamer-example/issues/21
=> [Filter] Clear & explicit error for missing extensions.

jni/Android-nnstreamer.mk, meson.build, packaging/nnstreamer.spec
This commit is to synchronize the version information among Ubuntu,
Tizen, Android, and Meson.
---
=> Build: synchronize vesion info among platforms

gst/nnstreamer/tensor_converter/tensor_converter.c, tests/nnstreamer_sink/unittest_sink.cpp
1. when called get_property, return empty string if converter has invalid tensor info.
2. check each properties iin stream test.
=> [Converter] test for converter properties

gst/nnstreamer/tensor_common.c
This patch removes the unnecessary gst_tensor_config_init() function call
since init function of each type (i.g. gst_tensor_config_from_[TYPE]_info())
calls gst_tensor_config_init() internally.
=> [Common] Remove unnecessary init function call

gst/nnstreamer/tensor_common.c
Use return values from function calls while setting up config
=> [Common] Updated return value

jni/README.md
This commit is to depict how to run nnstreamer-based test application
with linker64 (the ELF interpreter) on the Android 64bit devices.
We assume that you run your test applications in the `/data/nnstreamer/`
folder on the Android devices based on ARM64 CPU. Note that the 'linker64'
file to interpret ELF files is located in the `/data/nnstreamer/libandroid/`
folder.
---
=> [URGENT] Android/ARM64: Added how to run CLI app with linker64

.gitignore
This patch updates .gitignore to exclude files generated by the test script of codegen.
=> [Git] Update .gitignore to ignore files generated by codegen tests

gst/nnstreamer/nnstreamer_plugin_api.h, gst/nnstreamer/tensor_common.c
Added function to copy tensor info with variable length
This PR is needed as a functionality for the PR #1228.
=> [Common] Updated copy tensor info

gst/nnstreamer/tensor_transform/tensor_transform.c, tests/nnstreamer_plugins/unittest_plugins.cpp, tests/transform_arithmetic/checkResult.py, tests/transform_arithmetic/runTest.sh
Related issue: #1153
In order to cover mode code by various unit test cases, this patch adds more test cases for the 'arithmetic' mode of the 'tensor_transform' element.
- Update checkResult.py to support test results of integer number type
- Add test cases that increase code coverage
- Replaces assertion code for handling wrong option string in tensor_transform with the code returning error code in order to gracefully terminate the pipeline with proper error messages
- [v2] checkResult.py: Add missing doxygen tag
- [v2] checkResult.py: Eliminate the duplicate statement
- [v2] add test for dynamically changing option string
- [v3] Set the default value for 'acceleration' to FALSE when HAVE_ORC is not set
- Before this PR: 
| Filename  | Line Coverage  | Functions |
| ------------- …
=> [Test/Transform/Arithmetic] Add more test cases @open sesame 3/14 20:36

gst/nnstreamer/tensor_decoder/tensordec.c
In order to clean up private data of each decoder sub plug-in, corresponding TensorDecDef.exit() should be invoked by the decoder. To this end, this patch adds GObject 'finalize' vmethod implementation to the tensor decoder element.
=> [Decoder] Add GObject vmethod implementation for finalize

meson_options.txt, nnstreamer_example/meson.build
The only place which has opencv dependency is
custom_example_opencv. In order to manage more efficient,
enable-opencv-test meson option is added. If it is true, opencv
example is enabled or disabled, if not.
=> [YOCTO] Add enable-opencv-test meson option to remove opencv dep

CHANGES, debian/changelog, jni/Android-app.mk, jni/Android-nnstreamer.mk, meson.build, packaging/nnstreamer.spec
This is a release of nnstreamer 0.1.2 per NNStreamer Summit 5, https://github.com/nnsuite/nnstreamer/wiki/NNStreamer-Mini-Summit-%235
After this, nnstreamer 0.1.3 RC development starts.
=> Release of 0.1.2 & Start of 0.1.3 RC.

nnstreamer_example/custom_example_RNN/dummy_RNN.c
In Tizen, this uninitialized output buffer sometimes causes a wrong result
It fixes #1247 
=> [Test/RepoRnn] handle the uninitialized output buffer

packaging/nnstreamer.spec
ssat is required only when unit_test is enabled.
We are not going to enable auto-unit-test in Tizen:Unified.
We will execute auto-unit-test only in Github-CI and
personal gbs for now.
We will enable auto-unit-test in Tizen:Unified after
we submit ssat to tizen.org
=> [Dist] Do not depend on ssat if it's not needed.

packaging/nnstreamer.spec, tests/meson.build, tests/tizen_capi/meson.build, tests/tizen_capi/unittest_tizen_capi.cpp, tizen-api/meson.build
This is to be the basis of TCT (Tizen Compliance Test) in the future.
=> [Tizen/API] Add unittest skeleton for Tizen-CAPI (TCT candidate) 

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h, packaging/nnstreamer.spec
Through conf, we can avoid unexpected errors in the specific environment by turning on/off the option(memory optimization).
=> [Filter/Tensorflow] remove memcpy by getting conf

gst/nnstreamer/tensor_source/tensor_src_iio.c, gst/nnstreamer/tensor_source/tensor_src_iio.h
Added scale and offset to process raw data.
First get channel specific scale/offset, if available. Secondly, try
generic scale/offset, else use default values.
=> [IIO] added scale and offset

gst/nnstreamer/nnstreamer_subplugin.c, gst/nnstreamer/nnstreamer_subplugin.h
We no longer need dlsym subplugin loader, which make it
incompatible with statically built subplugins.
Subplugins have been calling register_subplugin in its
init functions; thus removing dlsym routines is ok.
Fixes #1130
=> [Subplugin] Remove dlsym subplugin loader

tests/tizen_capi/meson.build, tests/tizen_capi/unittest_tizen_capi.cpp, tizen-api/include/tizen-api-private.h, tizen-api/include/tizen-api.h, tizen-api/src/tizen-api-pipeline.c
Implement Tizen-CAPI, "start/stop/getstate/destroy" for a nnstreamer pipeline.
Add testcases for them.
=> [Tizen/API] Implement start/stop/getstate/destroy with testcases

gst/nnstreamer/tensor_source/tensor_src_iio.c, gst/nnstreamer/tensor_source/tensor_src_iio.h
1. using scale and offset
2. removed unused mutex
3. using GST_ERROR_OBJECT() instead of GST_ERROR()
4. using silent debug properly
5. bug fix for setting generic_name in channel properties
6. using G_UNLIKELY with updated cppcheck
=> [IIO] minor bug fixes and changes @open sesame 03/22 16:17

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h
Since the `STRING` input tensors should be processed differently(cannot be done with `C_API`),
the logic was fixed.
it resolves #1269 
=>  [Filter/Tensorflow] fix bug of testcase

gst/nnstreamer/nnstreamer_conf.c, gst/nnstreamer/nnstreamer_conf.h
Any subplugins (/ext/) may use this to make custom
configuration keys.
To support custom filters, the header should be exported.
However, for now, let's forget about the need from
custom filters.
=> [Conf] Custom conf keys  @open sesame 3/26 18:40

packaging/nnstreamer.spec, tests/tizen_capi/unittest_tizen_capi.cpp, tizen-api/src/tizen-api-pipeline.c
>   [Test/Unit-test-coverage] Add Tizen/API into unittest coverage
Count test-coverage of Tizen/API.
>   [Test:Tizen/API] Test "valve" control Tizen APIs
Test if frames flow only when valve is opened.
>   [Tizen/API] Bugfix on object unref, get_state
1. Unref'ing caps should use gst_caps_unref, not gst_object_unref/g_object_unref.
2. gst_state should not wait indefinitely. Let's give 100us as the "deadline".
=> [Tizen/API] Add testcases for "valve", fix newly-found bugs from the new testcases.

tizen-api/doc/nnstreamer_doc.h
This patch fixes the minor typos in doc header file.
=> [Tizen] fix the typos in doc header @open sesame 03/27 18:26

packaging/nnstreamer.spec
Fixed the issue #1193 and #1275 finally.
https://github.com/nnsuite/nnstreamer/issues/1193#issuecomment-469635177
https://github.com/nnsuite/nnstreamer/issues/1275
This commit is to replace UTC with KST by default in order to display the date format
with Seoul time.  The 'lcov' generates the date format with UTC time zone by default.
So, let's replace UTC with KST.
---
=> lcov: Changed the default time zone from UTC to KST

gst/nnstreamer/tensor_repo.c
There is hanging error when it is waiting pulled signal. In the case
of EOS(End of Stream), there is no pulling procedure but it is
required to get signal to get out the while loop.
1. Build test:   [X]Passed [ ]Failed [ ]Skipped
2. Run test:     [X]Passed [ ]Failed [ ]Skipped
=> [TENSORREPO] Fix hanging while waiting pulled signal when eos.

README.md
This patch adds a badge that displays code coverage status to the main page of github, i.e., README.md.
=> [README] Add a badge for displaying status of code coverage @open sesame 3/29 08:30 

gst/nnstreamer/tensor_source/tensor_src_iio.c
This PR partially resolves #1293 (the issue related to the byte order conversion functions only)
Without defining _BSD_SOURCE and __USE_BSD macros, the functions such as be16toh, le16toh, be32toh, le32toh, be64toh and le64toh are not compatible with c89. In order to fix this issue, this patch replaces such functions with byte order macros from glib-2.0.
=> [IIO] Change functions used for byte order conversion

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h, nnstreamer.ini.in
This rephrases #1013 with nnstreamer configuration support.
Add TRUE or 1 or ON of "enable_nnapi" in .ini file or
Use NNSTREAMER_tensorflowlite_enable_nnapi=1 as an environmental
variable to enable NNAPI for tensorflow-lite.
CC: @daeinki
=> [Filter/TF-Lite] Enable NNAPI with configurations

tests/nnstreamer_sink/unittest_sink.cpp
Line 343 of unittest_sink.cpp has svace warning:
WID:65505049 Use of vulnerable function 'sprintf' at
unittest_sink.cpp:343. For better security, VD recommends NOT to use
sprintf. Use snprintf instead.
=> [SVACE/414655] Fix 65505049 Warning

tests/bmp2png.c
Fix: WID:65505007 Integer value 'width * height' obtained from untrusted source at bmp2png.c:239 by passing as 1st parameter to function 'fread' at bmp2png.c:232 without checking its lower bound is used in a trusted operation at bmp2png.c:254 by calling function 'calloc'.
Add lower limits for height/width.
=> [SVACE/414602] Fix 65505007 Warning

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
Line 249 of tensordec-boundingbox.c has the following SVACE warning:
Possible integer underflow: left operand is tainted. An integer underflow may occur due to arithmetic operation (unsigned subtraction) between values { [0, 1073741823] } and '1', where the first value comes from the expression 'strlen(line)'
=> [SVACE/414609] Fix 65505016 Warning

nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c
If it's NULL, don't proceed:
Pointer 'data' returned from function 'malloc' at nnstreamer_customfilter_example_average.c:36 may be null, and it is dereferenced at nnstreamer_customfilter_example_average.c:38.
=> [SVACE/414629] Check malloc return value.

nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c
Do not proceed if malloc returns null:
Pointer 'data' returned from function 'malloc' at nnstreamer_customfilter_example_scaler.c:45 may be null, and it is dereferenced at nnstreamer_customfilter_example_scaler.c:48.
=> [SVACE/414630] Check malloc return value

nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c
Do not proceed if malloc returns null:
Pointer 'data' returned from function 'malloc' at nnstreamer_customfilter_example_scaler_allocator.c:65 may be null, and it is dereferenced at nnstreamer_customfilter_example_scaler_allocator.c:68.
=> [SVACE/414631] Check malloc return value

tests/nnstreamer_sink/nnscustom_framecounter.c
Do not proceed if malloc returns null:
Pointer 'data' returned from function 'malloc' at nnscustom_framecounter.c:96 may be null, and it is dereferenced at nnscustom_framecounter.c:98.
=> [SVACE/414632] Check malloc return value

nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c
Do not proceed if malloc returns null:
Pointer 'output[0].data' returned from function 'malloc' at nnstreamer_customfilter_example_scaler_allocator.c:159 may be null, and it is dereferenced at nnstreamer_customfilter_example_scaler_allocator.c:202.
=> [SVACE/414633] Check malloc return value

gst/nnstreamer/tensor_filter/tensor_filter.c
DEREF_OF_NULL.RET.ALLOC
Pointer '↦left[0]' returned from function 'g_strdup_printf' at tensor_filter.c:965 may be null, and it is dereferenced at tensor_filter.c:984.
Pointer '↦right[0]' returned from function 'g_strdup_printf' at tensor_filter.c:974 may be null, and it is dereferenced at tensor_filter.c:986.
=> [SVACE/414634-5] Fix 65505041/2 Warning

meson.build, meson_options.txt, nnstreamer_example/meson.build, tests/meson.build, tests/nnstreamer_filter_custom/runTest.sh, tests/nnstreamer_plugins/unittest_plugins.cpp, tests/nnstreamer_repo_dynamicity/runTest.sh, tests/nnstreamer_repo_dynamicity/tensor_repo_dynamic_test.c, tests/nnstreamer_repo_lstm/runTest.sh, tests/nnstreamer_repo_rnn/runTest.sh, tests/nnstreamer_sink/unittest_sink.cpp
Because there are test cases incluiding absolute path for library, it
is hard to run unit testcases after installation. In this PR, these
testcases and nnstreamer_example libraries are installed
/usr/lib/nnstreamer/unittest. For the nnstreamer_example, libraries
are in /usr/lib/nnstreamer/unittest/nnstreamer_exampls, and For the
tests, they are installed in /usr/lib/nnstreamer/unittest/tests.
Some unittest executions (unittest_repo, unittest_sink,
unittest_common, unittest_plugins) are installed in
/usr/lib/nnstreamer/unittest.
=> [YOCTO] Modified unittest directory for installation & runn @open sesame 04/01 10:54

gst/nnstreamer/tensor_source/tensor_src_iio.c, gst/nnstreamer/tensor_source/tensor_src_iio.h, tests/nnstreamer_source/unittest_src_iio.cpp
1. Created virtual iio device to test against
2. Added test case to test state change from NULL to PLAYING and backwards
3. Bug fixes-
3.1 setting of fixated caps moved to _fixating() from _start()
3.2 channel property list memory issue resolved
3.3 missing sampling frequency file while setting it is now a warning
skip to default frequency if file is not present
3.4 More minor bug fixes
4. IIO base directories moved to header file
These directories are modified to temporary location when testing with simulated device
=> [IIO] test cases for state change and corresponding bug fixes @open sesame 03/27 18:44

tests/common/unittest_common.cpp
Line 448 of unittest_common.cpp has svace warning:
WID:65505047 Return value of a function 'fopen64' is dereferenced at
unittest_common.cpp:448 without checking, but it is usually checked
for this function (8/9).
=> [SVACE/414949] Fix 65505047 Warning - @open sesame 04/02 15:23

gst/nnstreamer/tensor_source/tensor_src_iio.c, gst/nnstreamer/tensor_source/tensor_src_iio.h
restore the existing values of scan_channels_en, sampling_frequency,
buffer/length and current trigger (if exist) when stopping the element
**Related Issue**
#1199 
=> [IIO] restore iio device on _stop() @open sesame 4/2 15:17

gst/nnstreamer/tensor_filter/tensor_filter.c
In tensor-filter, ip-mode vmethod is unnecessary.
=> [Filter] remove ip mode vmethod 

tests/nnstreamer_source/unittest_src_iio.cpp
This fixes the error of unchecked return value upon deletion of directory structure.
=> [Coverity 1050275] Unchecked return value

gst/nnstreamer/nnstreamer_conf.c, gst/nnstreamer/nnstreamer_conf.h
const of const gboolean func() is useless.
=> [Coverity 1049998/1050018] Fix useless keyword

gst/nnstreamer/tensor_common.c
dimensions and types are now deliminated by both '.' and ','.
It is to support GstCap (CapsFilter) with other/tensors string
expressions.
Note that ... ! other/tensors,types=float32,int32 !...
is not supported. We need to use . instead in such cases.
2. Run test: [x]Passed [ ]Failed [  ]Skipped
=> [Common] Add other/tensors parsing rule.

gst/nnstreamer/tensor_source/tensor_src_iio.c
[Coverity 1049985,1049986,1049990,1049991,1050015,1050016,1050030,1050272]
This fixes branch past initialization (transfer of control bypasses initialization) at many incidents
=> [Coverity] Branch Past Initialization in _start()

gst/nnstreamer/tensor_source/tensor_src_iio.c, gst/nnstreamer/tensor_source/tensor_src_iio.h
Removed usage of fileno to file descriptor to compile without error with C89
as fileno() requires _POSIX_C_SOURCE >= 1 || _XOPEN_SOURCE || _POSIX_SOURCE
Using open() from fcntl directly instead of fopen() and fileno() combined
Resolves issue #1293
=> [IIO] Removing fileno()

packaging/nnstreamer.spec
Fixed issue #1314.
This commit is to support optional flag to skip the generation of debug packages
to speed up a build time and to save a storage cost. In case that developers
have to do a debugging the source code with gdb, they may change the value of
the 'nodebug' from 1 to 0.
---
=> BUILD: Support nodebug option for gbs build

tests/tizen_capi/unittest_tizen_capi.cpp, tizen-api/src/tizen-api-pipeline.c
This PR fix the #1340 issue by checking both the return value and GError value in `nns_pipeline_construct()` because gst_parse_launch() could return non-NULL even though the error is set. Detailed patches are as below.
* Add pipeline failure test cases
* Bugfix when passing a wrong pipeline command
* https://github.com/nnsuite/nnstreamer/issues/1340
=> [Tizen/API] bugfix when passing a wrong pipeline command

gst/nnstreamer/tensor_demux/gsttensordemux.c, tests/nnstreamer_sink/unittest_sink.cpp
1. fix invalid src pad index in tensor-demux
2. add simple testcase for the properties and tensorpick option
=> [Demux] fix invalid pad index

gst/nnstreamer/tensor_source/tensor_src_iio.c, gst/nnstreamer/tensor_source/tensor_src_iio.h, tests/nnstreamer_source/unittest_src_iio.cpp
Commit 1:
1. Added test case to check data validity for the element for various data bytes sizes
2. Added a property of timeout while reading file in non-blocking mode.
This allows looping while reading the file along with EAGAIN error.
3. Corrected mask generation
4. IIO dev file is replaced with fifo. Using threads to make these fifo as
opening it blocks unless both read and write mode are opened together.
5. Added test case to validate data with and without trigger.
Commit 2:
1. Added test cases when only some of the channels are enabled
2. Bug fix in test case for indexing when filling in data
3. Added test case for using device number and testing name-by-id
Completed 12 …
=> [IIO] Added data validity testcases - @open sesame 04/05 12:58

ext/nnstreamer/tensor_filter/tensor_filter_python_api.c
It's a python module which a user will import in a python script.
Currently, only 'TensorShape' type object is supported.
I'm considering other useful APIs.
=> [PythonFilter/API] Add a python module to provide NNS-related APIs

gst/nnstreamer/tensor_source/tensor_src_iio.c, tests/nnstreamer_source/unittest_src_iio.cpp
1. set base src as async, resolves the error of hanging
without setting base_src as async, _start_complete gets called twice
2. initializing log_file to NULL
3. NULL check for variable before using it for remove/rmdir
4. remove _query function, was incomplete, and complete function
was same as parent class function
resolve #1353, nnsuite/TAOS-CI#489
=> [IIO] bugfixes related to errors from yocto run

gst/nnstreamer/tensor_source/tensor_src_iio.c
Using case insensitive string comparison for property decision
=> [IIO] Using case insensitive string comparison

gst/nnstreamer/nnstreamer_conf.c
Remove unnecessary free that caused error with valgrind
resolves nnsuite/TAOS-CI#489
=> [CONF] remove unnecessary free

tests/tizen_capi/unittest_tizen_capi.cpp, tizen-api/include/tizen-api.h, tizen-api/src/tizen-api-pipeline.c
In order to pass the ACR process, 'tensor_typedef.h' in tizen-api.h
should be removed and its related thing also be updated. This patch
handles that issues. Detailed modification are as below.
* Remove dependency for 'nnstreamer/tensor_typedef.h' header
* Add necessary constant and enum variables such as
NNS_TENSOR_RANK_LIMIT and nns_tensors_info.
* Use nns_tensors_info structure instead of GstTensorsInfo
* http://suprem.sec.samsung.net/jira/browse/ACR-1382
=> [Tizen/API] Remove dependency 'tensor_typedef.h'

gst/nnstreamer/tensor_transform/tensor_transform.c, gst/nnstreamer/tensor_transform/transform-orc.orc, tests/nnstreamer_plugins/unittest_plugins.cpp
For add,mul,div op in orc functions, use single array ptr to handle operator.
Orc generated functions have __restrict__ ptr, the pointers overlapping memory regions may cause an error.
To avoid this, pass single array ptr to handle each operator.
=> [Transform/Orc] data ptr in orc function

tests/tizen_capi/unittest_tizen_capi.cpp, tizen-api/include/tizen-api.h
In order to increase test coverage, this PR adds some test case about `SRC` node. Moreover, it updates 
the comment about nns_pipeline_src_puthandle() such as parameter type and return values. Detailed items are as below.
* Update the comment about nns_pipeline_src_puthandle()
* Add testcase about src node
=> [Tizen/API] Add testcase about src node and update its comment - @open sesame 04/17 15:14

tests/nnstreamer_source/unittest_src_iio.cpp
TOCTOU issue : A check occurs on a file's attributes before the file
is used in a priveleged operation, but things may have changed.
Removed file test operation and using stat as a single check operation
as well as file size reading operation.
=> [Coverity] Resolved TOCTOU issuse from coverity @open sesame 4/18 17:28

tests/nnstreamer_source/unittest_src_iio.cpp
Negative returns: negative value used as argument to a function
expecting a positive value
Resolved with an assert
=> [Coverity] Resolved negative returns issue @open sesame 4/18 17:28

gst/nnstreamer/tensor_source/tensor_src_iio.c, tests/nnstreamer_source/unittest_src_iio.cpp
MEMORY_LEAK_EX : Dynamic memory reference was allocated and lost.
Resolved memory leaks given by svace for src_iio code as well as tests
=> [SVACE] Addressess memory leaks @open sesame 4/18 17:28

gst/nnstreamer/nnstreamer.c, gst/nnstreamer/tensor_common.h
We don't need to init orc functions.
It will be called when creating new orc program.
=> [Orc] remove unnecessary code

tests/meson.build
set unittest timeout to 2 minutes for sink and src_iio stream test.
default 30 seconds may make a timeout error when running unittests in local.
=> [Meson/Test] increase test-timeout - @open sesame 04/23 17:48

tests/meson.build
add
. nnstreamer_filter_tensorflow-lite
. nnstreamer_filter_tensorflow
. nnstreamer_decoder_image_labeling
according to enable-tensorflow and enable-tensorflow-lite option.
=> [UNITTEST] add tensorflow-lite test cases accorting to option - @open sesame 04/19 15:01

gst/nnstreamer/tensor_common.c
There is svace issuse said:
WID:66310552 Return value of a function 'g_slist_nth' is dereferenced
at tensor_common.c:1096 without checking, but it is usually checked
for this function (195/205).
Add Null check.
=> [SVACE] Fix Issue #414638

gst/nnstreamer/tensor_source/tensor_src_iio.c
MEMORY_LEAK.EX Dynamic memory referenced by raw_data_base was allocated
by calling function g_malloc and lost
Fixed with updated memory free
=> [SVACE/IIO] Bugfix of memory leak for iio svace

gst/nnstreamer/tensor_reposrc/tensor_reposrc.c
Threre is svace issue said:
WID:66310927 Return value of a function 'gst_buffer_get_meta' is
dereferenced at tensor_reposrc.c:338 without checking, but it is
usually checked for this function (20/21).
Add check if the meta is null and arise the error.
=> [SVACE] Fix Issue WGID 414639

gst/nnstreamer/tensor_common.h, gst/nnstreamer/tensor_demux/gsttensordemux.h, gst/nnstreamer/tensor_split/gsttensorsplit.h
define common tensor-pad struct used in split/demux
=> [Common] pad info struct - @open sesame 04/24 15:54

tests/meson.build
gen24bBMP.py is requried from some of tests
=> [Unittest] add install gen24bBMP.py - @open sesame 04/29 12:56

tests/meson.build
Add tensorflow-lite model data when test unittest is installed.
=> [Unittest] Added tensorflow-lite model data @open sesame 04/30 15:10

gst/nnstreamer/tensor_source/tensor_src_iio.c
Initialize variable to handle memory blocks (fix coverity issue)
=> [IIO] init local variable

gst/nnstreamer/tensor_repo.c, gst/nnstreamer/tensor_repo.h
If repo has no data or hashtable returns null, this makes exception to set lock or signal.
To prevent this exception, check returned data and handle error case.
Exception case when checking 'gst-inspect-1.0 -a'
tensor-repo made an exception.
TODO: Consider to move repo/reposrc/reposink sources into one directory.
Now tensor-repo is not a common source.
=> [Repo] handle empty repo data

ext/nnstreamer/tensor_decoder/meson.build, ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c, ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
1. use glib function to load and initialize labels (fix one of security issues)
2. fix exception case when total label is larger then ssd model output
=> [Security] [Decoder/Sub-plugins] use glib to load labels

tests/nnstreamer_decoder_image_labeling/runTest.sh, tests/nnstreamer_filter_tensorflow/runTest.sh, tests/nnstreamer_filter_tensorflow_lite/runTest.sh
We need to skip tests using tensorflow and lite if they are not
installed. So pkg-config is used to identify their installation.
related issue : #1370 
=> [UNITTEST] Skip the test when there is not tensorflow and lite  - @open sesame 04/17 13:43 

packaging/nnstreamer.spec, tests/tizen_capi/unittest_tizen_capi.cpp, tizen-api/capi-nnstreamer.pc.in, tizen-api/doc/nnstreamer_doc.h, tizen-api/include/nnstreamer.h, tizen-api/include/tizen-api-private.h, tizen-api/meson.build, tizen-api/src/tizen-api-pipeline.c
The file name "tizen-api.h" is ubsurd for Tizen application writers.
CC: @again4you 
=> [Tizen/API] Rename tizen-api.h to nnstreamer.h

meson.build, packaging/nnstreamer.spec, tizen-api/meson.build
Meson v0.50 supports the install arg in configure_file().
If install_dir is set, configured file will be installed.
Also, TEST_TENSORFLOW in rpm spec is unnecessary.
=> [Build/Meson] remove unnecessary flag

tizen-api/doc/nnstreamer_doc.h, tizen-api/include/nnstreamer.h, tizen-api/src/tizen-api-pipeline.c
This PR modifies the API and its related thing to comply with Tizen ACR process.
Detailed items are as below.
* Make a consistency in naming of GStreamer
* Make a verb for the third person singular
* Add 'remarks' information for specific functions
* https://github.com/nnsuite/nnstreamer/issues/1435
=> [Tizen/API] Update Tizen API to comply with ACR process

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c, gst/nnstreamer/nnstreamer_conf.c, gst/nnstreamer/nnstreamer_conf.h, nnstreamer.ini.in, packaging/nnstreamer.spec, tests/common/unittest_common.cpp
Remove default flag about tensorflow memory optimization.
In tensorflow sub-plugin, read this option using custom-bool function.
=> [Conf/Tensorflow] remove default flag in conf setting

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c, ext/nnstreamer/tensor_decoder/tensordec-directvideo.c, ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c, gst/nnstreamer/nnstreamer_plugin_api_decoder.h, gst/nnstreamer/tensor_decoder/tensordec.c, gst/nnstreamer/tensor_decoder/tensordec.h
1. change decoder register function / struct name
2. remove unnecessary private properties and code clean (sub-plugin mode only)
=> [Decoder/Api] change function name / sub-plugin mode

tests/common/unittest_common.cpp, tests/nnstreamer_plugins/unittest_plugins.cpp, tests/nnstreamer_sink/unittest_sink.cpp, tests/nnstreamer_source/unittest_src_iio.cpp
GCC7 has stricter rules on signed-unsigned comparison.
Update unit-test cases to avoid gtest errors with gcc7.
=> [Unittest] GCC7-GTEST compatibility

ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
This patch implements callback functions for opening and closing GstTensorFilterFramework for the Intel Movidius Neural Compute Stick sub-plugin of tensor_filter.
Relates to #1437
See also: https://github.com/nnsuite/nnstreamer/pull/1441 #1138
**Changes**
- V5: Invalidate *private_data at close
- V4: Add missing free for private data
- V3: Correct typos
- V2: Remove GMappedFile-typed variable in the private data structure 
- V2: Unref GMappedFile-typed variable, file_model, right after using it
- V2: Assign input and output tensor desc to the corresponding variables in the private data structure
=> [Filter/MvNCSDK] Implement callbacks for open/close of filter framework

ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
This patch fills the bodies of callback functions, getInputDimension and
getOutputDimensions, which return the dimension information of input and
output tensor of this filter.
Relates to #1437
See also: https://github.com/nnsuite/nnstreamer/pull/1441 #1138
=> [Filter/MvNCSDK] Write callbacks for getting dimensions of in/out tensor

tests/tizen_capi/unittest_tizen_capi.cpp, tizen-api/include/nnstreamer.h, tizen-api/src/tizen-api-pipeline.c
1. change function name and indent rule in tizen-capi.
2. unref object after usage (caps and pad data).
3. add macros for log message.
=> [Api/Tizen] change function name and refactor code

CHANGES, debian/changelog, jni/nnstreamer.mk, packaging/nnstreamer.spec
0.1.3 RC has become 0.2.0 as this version is accepted by Tizen 5.5 M1.
- A lot of security issues and bugs fixed (for Tizen 5.5 M1 release)
- Tizen Public C-API Pipeline for 5.5 M1
- Tizen Public C-API SingleShot Prototype
- Yocto/Openembedded layer released
- ROS sink/src
- IIO support
- Android source draft
- Python custom filter
- Android sample application released
- Tensorflow-lite / NNAPI support
=> Release of NNStreamer 0.2.0

tizen-api/doc/nnstreamer_doc.h, tizen-api/include/nnstreamer.h
In order to pass the ACR process, unnecessary information such as `TBD`
or `todo` should be removed in Public header. This patch removes those
things.
* https://github.com/nnsuite/nnstreamer/issues/1435
=> [Tizen/API] Remove unnecessary todo and TBD items

ext/nnstreamer/tensor_filter/tensor_filter_python_core.cc
This PR updates missing initializations of class member variables.
It's reported from SVACE.
=> [Filter/Python] Fix missing initialization of class members @open sesame 5/31 14:27

gst/nnstreamer/tensor_typedef.h, tizen-api/doc/nnstreamer_doc.h, tizen-api/include/nnstreamer-single.h, tizen-api/src/nnstreamer-single.c
This is quite similar with CoreML/MLModel API, which is the
low-level API for iOS CoreML.
With this, application developers may invoke "inferences"
of a given model with a single data frame without
any pre/post-processings.
The corresponding pipeline will be:
app_src --> tensor_filter --> tensor_sink
with 0/1 framerate.
=> [Tizen/API] CoreML-like API - @open sesame 04/05 14:36

tests/tizen_capi/unittest_tizen_capi.cpp, tizen-api/include/nnstreamer.h, tizen-api/include/tizen-api-private.h, tizen-api/src/tizen-api-pipeline.c
1. Register the appsink as a sink element. User can register appsink and tensor-sink as a sink element.
2. Move logging macro to private header.
3. Add testcases to test appsink element.
=> [Tizen/Api] add appsink to handle sink event

tizen-api/doc/nnstreamer_doc.h, tizen-api/include/nnstreamer.h
This PR modifies the API and its related thing to comply with Tizen ACR process.
Detailed items are as below.
* Use the word `function` instead of `API` in documentation 
* Fix the broken link
=> [Tizen/API] Update Tizen API to comply with ACR process @open sesame 6/03 17:40

.gitignore
This patch updates .gitignore to exclude files generated by Visual
Studio for C# APIs.
=> Update .gitignore to ignore files generated by Visual Studio

gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter.c
Since caffe2 require 2 model files(init, prediction), the filter option should handle the complicated input string
=> [Filter] add the model path parser - @open sesame 5/31 11:19 

packaging/nnstreamer.spec
% is the macro character in RPM/spec. $ is a typo.
---
=> [Dist] typo fix $ --> % @open sesame 6/6 22:00

ext/nnstreamer/android_source/README.md, ext/nnstreamer/android_source/gstamcsrc.c, ext/nnstreamer/android_source/gstamcsrc.h, ext/nnstreamer/android_source/gstamcsrc_looper.cc, ext/nnstreamer/android_source/gstamcsrc_looper.h
This PR includes codes of a source element for Android MediaCodec (AMC).
It's related to issue https://github.com/nnsuite/nnstreamer/issues/1281.
Also, I made another PR for example app (https://github.com/nnsuite/nnstreamer-example/pull/33).
**Changelog:**
1. Fix doxygen errors
2. Add README.md
3. Fix minor bugs
4. Change the termination logic
=> [Source/AMC] Source element for Android MediaCodec (AMC) @open sesame 6/3 11:23 

gst/nnstreamer/nnstreamer_plugin_api_decoder.h, gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/nnstreamer_subplugin.c, gst/nnstreamer/tensor_decoder/tensordec.c, gst/nnstreamer/tensor_filter/tensor_filter.c
1. add definition to find filter/decoder sub-plugins instance.
2. check duplicated name when registering sub-plugin.
=> [Subplugin] define function to find subplugin

gst/nnstreamer/tensor_common.c, tests/common/unittest_common.cpp, tests/nnstreamer_sink/unittest_sink.cpp
1. check string len while checking data type.
2. unref pad instance in testcases.
=> [Common/Test] minor update

ext/nnstreamer/tensor_filter/tensor_filter_pytorch_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
When they cannot load a model file due to file types,
don't just tell you cannot load it.
Tell more about it along with the file path.
=> [Filters] Emit more friendly error messages.

packaging/nnstreamer.spec
CAPI files have been moved from tizen-capi to api/capi.
Note that C-API will support all other general Linux distros
and we will support C# and Java APIs as well.
=> Unittest-coverage: apply the changed paths of CAPI files

gst/nnstreamer/tensor_common.c, tests/common/unittest_common.cpp
if name string is empty, set null str.
=> [Common] parse empty name string

gst/nnstreamer/nnstreamer_conf.c
If conffile path is not available in envvar, use the default.
We had this feature before and... somehow, this feature
has been removed at some point.
I'm reviving this feature as this makes errors in some systems.
I've added g_assert to avoid similar errors without
detected at the point of failure.
=> [Conf] If CONFFILE path is not available, use the default @open sesame 6/25 17:25

api/capi/src/nnstreamer-capi-single.c
gst_app_sink_try_pull_sample is available at ver 1.10.
check minor version and get buffer from appsink with gst_app_sink_pull_sample.
=> [C-API] appsink function in old version @open sesame 6/19 13:33

debian/nnstreamer-dev.install, debian/nnstreamer.install, debian/rules, tests/tizen_capi/unittest_tizen_capi.cpp
1. Add capi in nnstreamer debpkg
2. Fix test fail cases in local.
- caps string to appsrc (sets invalid caps)
- set default root dir in c-api testcases
=> [Build/Test/C-Api] add capi in nnstreamer deb and fix test failure case

api/capi/src/nnstreamer-capi-single.c, tests/tizen_capi/unittest_tizen_capi.cpp
Check given model file has valid file extension.
If the param nnfw is unknown and file ext is valid, determine fw with the ext.
=> [C-Api] check nnfw with file extension

api/capi/doc/nnstreamer_doc.h, api/capi/include/nnstreamer-capi-private.h, api/capi/include/nnstreamer-single.h, api/capi/include/nnstreamer.h, api/capi/src/nnstreamer-capi-pipeline.c, api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c, tests/tizen_capi/unittest_tizen_capi.cpp
As we discussed, tensors metadata in c-api changed to the handles for meta/data.
1. alloc and destory functions are added for tensors meta/data handle.
2. refactors all functions and testcases with meta/data handle.
3. update api description.
=> [C-Api] tensor data handle and API defines @open sesame 7/5 17:55

api/capi/doc/nnstreamer_doc.h, api/capi/include/nnstreamer.h
This PR updates the feature name of Tizen API and its related
documentation. Detailed information is as below.
* NNStreamer -> Single / Pipeline without NNStreamer
* Newly add the 2 feature keys (machine_learning & machine_learning.inference)
=> [C-API] Update doxygen for Tizen API - @open sesame 7/11 15:23

api/capi/include/nnstreamer.h, api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c, tests/tizen_capi/unittest_tizen_capi.cpp
This patch newly adds the ML_NNFW_TYPE_NNFW enumeration for future use
of NNFW.
* https://github.com/nnsuite/nnstreamer/issues/1519
=> [C-Api] Add NNFW enum for future use - @open sesame 7/12 14:04

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h
override a specific method `data()` at the specific version of TF, `1.9.0` (before `1.13`)
it resolves #1518
=> [Filter/TF] fix build conflict with TF version 1.13.1

api/capi/include/nnstreamer-single.h, api/capi/src/nnstreamer-capi-pipeline.c, api/capi/src/nnstreamer-capi-single.c
1. return valid error code when opening single-shot model.
2. When called destroy() in pipeline, remove all callbacks before changing pipeline state.
=> [C-Api] fix error to run pipeline - @open sesame 7/12 19:55

api/capi/src/nnstreamer-capi-util.c
Since developers can reduce the number of Tensors by calling
ml_tensors_info_set_count(), it causes the memory leak when invoking
ml_tensors_info_free() and ml_tensors_data_destroy(). This patch fixes
that bug by checking all possible elements (i.e. ML_TENSOR_SIZE_LIMIT).
=> [C-Api] fix memory leak bug

packaging/nnstreamer.spec
With the Tensorflow update from 1.09 to 1.13 @ Tizen,
we have decided to drop tensorflow (non-lite).
ps. This is required for Submit-Request in Tizen Dashboard.
=> [Dist/Tizen] Disable tensorflow (non-lite) for Tizen

packaging/nnstreamer.spec
Tensor filters such as libnnstreamer_filter_tensorflow-lite.so does not
have a smack label, smack deny occurs when accessing it . This patch fixes
that bug.
```bash
[  127.077180] audit: type=1400 audit(1563522638.030:103): lsm=SMACK fn=smack_inode_getattr action=denied subject="User::Pkg::org.tizen.machine.nnstreamer.Test" object="User::Shell" requested=r pid=3541 comm="dotnet-launcher" path="/usr/lib/nnstreamer/filters/libnnstreamer_filter_tensorflow-lite.so" dev="vda" ino=2207
```
=> [Tizen/Api] add smack label for tensor filter

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc
The different constructor is applied according to the version of TF
With this pr, GBS build works well without errors related to tensorflow 1.13.1
=> [Filter/TF] apply a new constructor for TFBuffer - @open sesame 7/22 15:49

tests/nnstreamer_decoder_image_labeling/runTest.sh
Related to https://github.com/nnsuite/nnstreamer/pull/1456.
There are several bugs in the runTest.sh script. 
- The name of the 'ini_path' variable should be replaced with 'ini_file'. In the scope of the code handling /etc/nnstreamer.ini, there is no ini_path.
- The if-logic for handling /etc/nnstreamer.ini is wrong. It is always returned at the end of that if-logic without reaching the actual test code (i.e., gstTest).
In addition, we have same issues in runTests.sh scripts for the other test cases. I will fix them.
=> [Tests/Decoder/ImageLabeling] Bugfixes in the runTest script

tests/nnstreamer_filter_tensorflow_lite/runTest.sh
Related to #1456.
This PR also fixes same bugs mentioned in #1543. The only difference is that this fixes the bugs in the test script for the tensorflow-lite tensor filter.
=> [Tests/Filter/TFLite] Bugfixes in the runTest script

api/capi/src/nnstreamer-capi-single.c
Before calling gstreamer function, this patch checks its initialization
status by calling gst_init_check() in ml_single_open().
=> [C-API] check gstreamer initialization status in ml_single_open()

gst/nnstreamer/tensor_sink/tensor_sink.c, gst/nnstreamer/tensor_sink/tensor_sink.h
use basesink default and remove unnecessary functions.
=> [Sink] remove unnecessary functions

jni/Android.mk, jni/nnstreamer.mk, jni/prepare_tflite.sh
In order to build nnstreamer shared libraries including
sub-plugins (decoder, filters), the android.mk file is
restructured. Becuse gstreamer building block list for nnstreamer might be
required for static build and android application build, it is moved
to nnstreamer.mk.
If you bulid libnnstreamer.so using this android.mk, gstreamer shared
libries should be prepared. Please refere "Build Gstreamer full source
based Android rootFS with Cerbero" in
https://github.com/nnsuite/nnstreamer-example/tree/master/android.
Once the build is finished successfully, you can find libnnstreamer.so
and gstreamer shared libraries in libs/$TARGET_ARCH/ which is listed
in nnstreamer.mk under the name of "NNSTREAMER_BUILDING_BLOCK_LIST".
you can use these to build your own android application.
New script for …
=> [ANDROID] Built as Shared Library with tensorflow-lite @open sesame 7/15 09:35

tests/nnstreamer_filter_custom/runTest.sh
This patch fixes a minor bug in the code for checking existence of OpenCV libraries.
Resolves: #1548 
=> [Tests/CustomFilter] Fix a bug in code for checking existence of OpenCV

gst/nnstreamer/nnstreamer_conf.c, gst/nnstreamer/nnstreamer_conf.h
Since the default value of 'sysconfdir' in the Meson build system is just 'etc' instead of '/etc', NNSTREAMER_CONF_FILE could be set to wrong path when the default value is used. This patch fixes this issue.
CC: @jaeyun-jung 
See also: https://github.com/nnsuite/nnstreamer/pull/1424
**Changes**
- V4: Add #define to the header file and remove 'const static' in the c file
- V3: Regard the path of root directory for "windows" and "others" as "c:\" and "/" n, respectively
- V2: Use g_path_is_absolute() instead of NNSTREAMER_CONF_FILE[0] == ' /'
=> [Conf] Handle the case of using the default 'sysconfdir' value of meson @open sesame 7/25 19:20

tests/tizen_capi/unittest_tizen_capi.cpp
free strings after getting the pad list in testcase.
=> [Test] free string -  @open sesame 7/25 17:46

gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_custom.c
Prevent error case if filter framework does not need a model file.
Add a flag in nnfw struct and change condition to check model in transform callback.
=> [Filter] condition to check model

tests/nnstreamer_filter_caffe2/runTest.sh, tests/nnstreamer_filter_pytorch/runTest.sh, tests/nnstreamer_filter_tensorflow/runTest.sh
Related to #1456.
This PR also fixes same bugs mentioned in #1524 for the tensor filters, caffe2, tensorflow, and pytorch.
=> [Tests/Filters] Bugfixes in the runTest script

api/capi/doc/nnstreamer_doc.h, api/capi/include/nnstreamer-capi-private.h, api/capi/include/nnstreamer-single.h, api/capi/include/nnstreamer.h, api/capi/meson.build, api/capi/src/nnstreamer-capi-pipeline.c, api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c, debian/rules, packaging/nnstreamer.spec, tests/tizen_capi/unittest_tizen_capi.cpp
This patch checks the machine_learning.inference feature before
processing API by calling ml_get_feature_enabled() function.
=> [C-Api] Check feature before processing API

api/capi/include/nnstreamer-single.h, api/capi/src/nnstreamer-capi-single.c, tests/tizen_capi/unittest_tizen_capi.cpp
In QEMU, things are not that fast. Slow it down!
Commit 1: update unit test cases of API to support QEMU-ARM unit test
Commit 2: update Single-Invoke to have an increased timeout (1 --> 3 sec)
This fixes
1. unit-test in ARM/ARM64 with GBS.
2. launchpad build for armhl/aarch64 in 18.04
=> [UnitTest/TizenCAPI] Support in-emulator unit test

tools/README.md
fix a typo of README file: technolog -> technology
=> [Typo] fix typo at README.md

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h, meson.build, meson_options.txt, nnstreamer.ini.in
after changing filter_TensorFlow using `c-api`, the option `mem_optmz` is not used anymore.
=> [Filter/Tensorflow] remove the unused option for memory optimization

tests/codegen/runTest.sh, tests/nnstreamer_converter/runTest.sh, tests/nnstreamer_decoder/runTest.sh, tests/nnstreamer_decoder_boundingbox/runTest.sh, tests/nnstreamer_decoder_image_labeling/runTest.sh, tests/nnstreamer_demux/runTest.sh, tests/nnstreamer_filter_caffe2/runTest.sh, tests/nnstreamer_filter_custom/runTest.sh, tests/nnstreamer_filter_python/runTest.sh, tests/nnstreamer_filter_pytorch/runTest.sh, tests/nnstreamer_filter_tensorflow/runTest.sh, tests/nnstreamer_filter_tensorflow_lite/runTest.sh, tests/nnstreamer_merge/runTest.sh, tests/nnstreamer_mux/runTest.sh, tests/nnstreamer_repo/runTest.sh, tests/nnstreamer_repo_dynamicity/runTest.sh, tests/nnstreamer_repo_lstm/runTest.sh, tests/nnstreamer_repo_rnn/runTest.sh, tests/nnstreamer_split/runTest.sh, tests/transform_arithmetic/runTest.sh, tests/transform_dimchg/runTest.sh, tests/transform_stand/runTest.sh, tests/transform_transpose/runTest.sh, tests/transform_typecast/runTest.sh
In order to improve readability, this patch applies a bash shell script formatter named 'shfmt' [1] to all runTest.sh files in the ./tests directory. Note that 4 spaces are used for indentation instead of using
'tab'.
[1] https://github.com/mvdan/sh
=> [Tests] Apply bash script formatter to all runTest.sh files

meson.build
remove missed option about tensorflow mem-optimize in meson.
=> [Meson] remove missed option

meson.build, meson_options.txt
Add meson-option to disable orc library (default true).
Set -Denable-orc=false if you need to block the orc library.
=> [Meson] option to disable orc - @open sesame 8/9 13:35

debian/control, meson.build
Fixes https://github.com/nnsuite/nnstreamer/issues/1581
Related to #1380, #1440, #1461 
In the case that gtest has been installed via apt (i.e., apt install libgtest-dev), meson provides the -I options indicating the directory that does not exist. Therefore, it is failed to build when '-Wmissing-include-dirs' is set. This patch works around this issue.
https://launchpad.net/~wooksong/+archive/ubuntu/build-test/+sourcepub/10398603/+listing-archive-extra
amd64: fully built
arm64: fully built
armhf: **FAILED**
```bash
The Meson build system
Version: 0.50.1
...omission...
Did not find CMake 'cmake'
Found CMake: NO
Dependency protobuf found: NO (tried pkgconfig and cmake)
Dependency orc-0.4 found: YES 0.4.25
Program orcc found: YES (/usr/bin/orcc)
Dependency tensorflow-lite found: YES 0.1 …
```
=> [Meson] Apply work-around for gtest-related failure on meson 0.50.1 @open sesame 8/9 14:30

ext/nnstreamer/tensor_filter/tensor_filter_python.c
SAM result, remove global val about filter-framework.
=> [Filter/Py] remove global val to register subplugin

debian/rules
set python-encode utf-8 for meson build.
=> [Build] set python encode for meson

debian/rules
If it's ARM, don't use tensorflow.
#1590 needs this as well.
=> [Debian] Use Tensorflow only if it's amd64

debian/control
We are removing tensorflow-arm64 from our PPA.
=> [Debian] Remove tensorflow-dev build-dep for arm64

debian/rules
It takes too much time in the launchpad arm emulator.
Disable it to pass unittest-capi.
This resolves another case of #1598
CC: @helloahn @again4you @jaeyun-jung
=> [Debian/Unittest] Disable capi-unittest in arm/launchpad. [NEED APT UPDATE in CI-SERVER]

tests/bmp2png.c
This fixes:
FAILED: tests/59830eb@@bmp2png@exe/bmp2png.c.o
cc -Itests/59830eb@@bmp2png@exe -Itests -I../tests -I/usr/include/libpng16 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Werror -std=gnu89 '-DVERSION="0.2.1"' -Wredundant-decls -Wwrite-strings -Wformat -Wformat-nonliteral -Wformat-security -Winit-self -Waddress -Wno-multichar -Wvla -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Waggregate-return -Wold-style-definition -Wdeclaration-after-statement '-DNNSTREAMER_CONF_FILE="/etc/nnstreamer.ini"' -DHAVE_ORC=1 -DENABLE_TENSORFLOW_LITE=1 -DENABLE_PYTORCH=1 -DENABLE_CAFFE2=1 -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -MD -MQ …
=> [gcc9-fix] fix strncpy '__builtin_strncpy' issue @open sesame 8/14 22:00

packaging/nnstreamer.spec
Post uninstall script with `-p` option invokes a single program directly
instead of spawning shell script. Because of this reason, below error
occurs when uninstalling package. This patch fixes that bug.
----------------------------------------------
/sbin/ldconfig: relative path `1' used to build cache
warning: %postun(nnstreamer-0.2.1-6.4.i686) scriptlet failed, exit
status 1
=> [Spec] Fix the bug of post uninstall script. @open sesame 8/6 16:08

tests/bmp2png.c, tests/meson.build
strncpy is required not to use strlen for the length.
Use g_strdup and let glib handle it.
Fixes #1598 
(EOAN fix)
=> [Test/bmp2png] Use g_strdup to avoid gcc9 strict checks [Need CI-Server apt update]

api/capi/src/nnstreamer-capi-util.c, meson.build, meson_options.txt, nnstreamer.ini.in
Handles element restriction (whitelist for API release)
If needs restriction in pipeline elements, simply set the list in meson option.
e.g. meson -Denable-capi=true -Denable-element-restriction=true -Drestricted-elements='videotestsrc videoconvert' build
this allows videotestsrc and videoconvert with nnstreamer elements.
=> [Api/Pipeline] element restriction

api/android/api/build.gradle, api/android/api/jni/Android.mk, api/android/build-android-lib.sh
Add script to build android-api library.
If runs this script, ext-files are downloaded and run gradle build.
TODO add repo for ext-files (or another way to get ext-files)
=> [Android/Api] add script to build api library - @open sesame 8/19 16:47

gst/nnstreamer/nnstreamer.c, gst/nnstreamer/nnstreamer_conf.c, gst/nnstreamer/nnstreamer_conf.h, gst/nnstreamer/tensor_source/meson.build, meson.build, tests/common/unittest_common.cpp, tests/meson.build, tests/nnstreamer_sink/unittest_sink.cpp
https://github.com/myungjoo/SSAT/pull/12 is required.
This PR concerns macOS (High Sierra) support.
- Update the meson build script to make NNStreamer be built on macOS
- Support .dylib as a file extension of shared object in the macOS envirionment
- Let unit test cases for common and tensor_sink work on macOS 
1. Development environment
```bash
$ uname -a
Darwin MacbookAirAtHome 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
2. How to build
- [brew](https://brew.sh) is required. 
```bash
$ /usr/bin/ruby -e "$(curl -fsSL …
```
=> Support macOS (High Sierra)

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h, gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter.c, meson.build
Add nnapi property in the tensor_filter element.
Use nnapi=(true|false)(:(cpu|gpu|npu)) option for tensor_filter
element. For example,
gst-launch-1.0 --gst-plugin-path=${PATH_TO_PLUGIN} filesrc
location=${PATH_TO_IMAGE} ! pngdec ! videoscale ! imagefreeze !
videoconvert ! video/x-raw,format=RGB,framerate=0/1 ! tensor_converter
! tensor_filter framework=tensorflow-lite model=${PATH_TO_MODEL} nnapi=true:gpu ! filesink location=tensorfilter.out.log
=> [FILTER] add nnapi property @open sesame 8/18 21:21

gst/nnstreamer/tensor_decoder/tensordec.c, gst/nnstreamer/tensor_filter/tensor_filter.c
Check sub-plugins file extension after supporting mac.
Wook defined the file extension for build target. With this, set sub-plugins name in filter/decoder.
=> [Filter/Decoder] sub-plugins extension

api/capi/include/nnstreamer-single.h, api/capi/src/nnstreamer-capi-single.c
This patch fixes the wrong boilerplate text. (Apache -> LGPL-2.1)
=> [Tizen/API] Fix the wrong boilerplate text

jni/nnstreamer.mk, meson.build, packaging/nnstreamer.spec
Fix duplicated and unnecessary code with the updation of nnstreamer features.
1. remove src-iio in android-jni (currently excluded to register the element, so unnecessary.)
2. remove option enable-nnfw in .spec (default false)
3. duplicated feature definition for tizen
=> [Build] update build script

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
If the parameter hw of constructor is NNAPI_UNKNOWN, the member variable
accel is not initialized. This patch fixes that bug.
=> [Filter] Fix svace issue

packaging/nnstreamer.spec
This PR appends 'gtest_output' into .spec file to generate .xml gtest output files.
These XML files are reported to TESTHUB (for daily x86_64 build).
=> [TESTHUB] Append 'gtest_output' to report unittest output results

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
The string list requires a terminating null.
=> [EMERGENCY FIX] [TF-Lite] Add terminating null

api/capi/src/nnstreamer-capi-single.c
1. validate model path before checking the file extension.
2. set pre-defined so extension for custom-filter.
=> [Api/Single] invalid condition to check model

gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_transform/tensor_transform.c
1. remove unnecessary code to get output size in tensor-filter.
2. set null to find operator in tensor-transform.
=> [Filter/Transform] code clean

api/capi/include/tensor_filter_single.h, api/capi/meson.build, api/capi/src/tensor_filter_single.c, meson.build
Added prototype for tensor_filter_single
tensor_filter_single is going to form the backend for singleshot api
to minimize the latency. This is made to be independent of GStreamer,
supporting all the existing tensor_filter plugins
Working on #1547 
=> [filter_single] Added tensor_filter_single prototype

api/capi/meson.build, api/capi/src/tensor_filter_single.c, gst/nnstreamer/tensor_filter/meson.build, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h, jni/nnstreamer.mk
Simplified common functions between tensor_filter and tensor_filter_single
Added more implementations in tensor_filter_single
Common Functions between `tensor_filter.c` and `tensor_filter_single.c` have been moved to `tensor_filter_common.c`. These functions do not depend on GStreamer. 
Working on #1547 
=> [filter_single] Common functions between tensor_filter and tensor_filter_single

api/capi/capi-nnstreamer.pc.in
There are wrong include path, link option and omitted requires in CAPI
PC file. This patch fixes that bug.
* Contained files of capi-nnstreamer-devel package
```bash
$ rpm -qlp capi-nnstreamer-devel-0.2.1-0.x86_64.rpm
/usr/include/nnstreamer/nnstreamer-single.h
/usr/include/nnstreamer/nnstreamer.h
/usr/lib64/libcapi-nnstreamer.a
/usr/lib64/libcapi-nnstreamer.so
/usr/lib64/pkgconfig/capi-nnstreamer.pc
```
@kparichay and @jaeyun-jung 
Please go over this PR. Thanks in advance.
=> [API] Fix the errors in package config file @open sesame 09/03 17:30

packaging/nnstreamer.spec
In order to use capi-devel, you need capi.
CC: @again4you
=> [Dist/RPM] devel required library.

api/capi/capi-nnstreamer-single-new.pc.in, api/capi/meson.build, api/capi/src/nnstreamer-capi-single-new.c, packaging/nnstreamer.spec
Added open/close for the new single-shot implementation
New single-shot directly uses tensor-filter subplugin to avoid gstreamer overhead
Get input/output info is also added
The API for the new implementation is not changed.
Working on #1547
=> [single-shot] Added open/close for the new single-shot implementation

tests/codegen/runTest.sh, tests/nnstreamer_filter_custom/runTest.sh, tests/nnstreamer_repo_lstm/runTest.sh, tests/nnstreamer_repo_rnn/runTest.sh
This patch replaces the hard-coded filename extension, 'so', in the custom filter, repo_lstm, and repo_rnn test scripts with SO_EXT defined at ssat-api.
Partially resolves a sub-item of #1608 
=> [Tests] Use SO_EXT instead of hard-coded 'so'

api/android/api/res/values/strings.xml, gst/nnstreamer/nnstreamer_conf.c, gst/nnstreamer/tensor_common.c
1. add condition to check file path or tensor name
2. remove unnecessary res file in android
This will remove unnecessary log-print while running java custom-filter and tf-lite model.
=> [Android] unnecessary log while running android-lib

tests/nnstreamer_filter_tensorflow_lite/runTest.sh
With SSAT updates, this bug has been exposed:
- New test cases of nnapi-tensorflow-lite require nnapi. However,
there are systems that do not support nnapi.
ps. @jijoongmoon Please update nnapi test cases so that it is applied to Tizen-ARM/ARM64 systems only (then, update the 4th argument of ```testResult``` call from 1 to 0)
=> [HOTFIX] [Fix/Test] nnapi test cases breaks non-Tizen-arm builds

Documentation/getting-started-macos.md, README.md
In this PR, a 'getting-started' manual for macOS is newly added and README is also updated to have a link to this manual.
Resolves a sub-item of #1608 
See also: https://github.com/nnsuite/homebrew-neural-network
=> [Documentation] Add 'getting-started' for macOS @open sesame 09/09 10:03

tests/nnstreamer_decoder_pose/runTest.sh
Add a fail case and a simple-run case of decoder-pose.
This is to mitigate under-80% unit test coverage.
=> [Test] Add decoder-pose unit test

api/capi/include/nnstreamer-capi-private.h, api/capi/meson.build, api/capi/src/nnstreamer-capi-single-new.c, api/capi/src/nnstreamer-capi-util.c, api/capi/src/tensor_filter_single.c, packaging/nnstreamer.spec, tests/tizen_capi/meson.build
Completed the implementation for single-shot API without GStreamer
Added a separate binary for this API
Added remaining functions in `tensor_filter_single.c`
Added another test run in meson and `nnstreamer.spec` for testing of this new implementation
Note: single-shot new API is not part of the original `capi-nnstreamer-0.2.1-0.*.rpm` package
It is contained in `capi-nnstreamer-single-new-0.2.1-0.*.rpm` along with its devel version
Working on #1547
Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com
=> [single-shot] Completion for new single-shot API

api/capi/src/README.md, tests/tizen_capi/unittest_tizen_capi.cpp
Added benchmarking the latency and running times in the test code
This compares old vs new singleshot api - showing reduction in latency and running-time
These values averaged over 10 continuous runs
|  | Open (us)      | Invoke (ms)           | Close (us)  |
| --- |:-------------:|:-------------:|:-----:|
| New (cache warmup) |  658   | 5195 | 206 |
| Old (cache warmup) |  1228 | 5199   | 5245 |
| New (no warmup) | 1653 | 5205  | 201 |
| Old (no warmup) | 7201 | 5225  | 5299  |
These values are just for the first run
| | Open (us)      | Invoke (ms)           | Close (us)  |
| --- |:-------------:|:-------------:|:-----:|
| New  |  12326   | 5231 | 2347 |
| Old |  58772 | 5250   | 52611 |
Working on #1547
Run test: [x]Passed [ …
=> [single-shot] benchmarking the latency @open sesame 09/09 17:11

api/capi/src/nnstreamer-capi-single.c, tests/tizen_capi/unittest_tizen_capi.cpp
1. Add mutex-lock for internal process.
2. Clear old buffer of appsink before pushing new buffer to appsrc.
When old buffer received in appsink after timeout, next output of invoke() may be the previous result.
To prevent this, clear old sample in appsink.
=> [Api/Single] clear old buffer

api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java, api/android/api/src/main/jni/nnstreamer-native-singleshot.c, api/android/sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
Add method to set the timeout in single-shot API.
=> [Android/Api] add timeout in single-shot

api/capi/meson.build
Updated meson to do static linking with unit-test executable
This resolves #1653
=> [single] Static linking with unit-test @open sesame 09/16 12:24

packaging/nnstreamer.spec
Update the restricted elements in Tizen.
Restricted elements
- capsfilter input-selector output-selector queue tee valve
- appsink appsrc
- audioconvert audiorate audioresample audiomixer
- videoconvert videocrop videorate videoscale videoflip videomixer compositor
- fakesrc fakesink filesrc filesink
- audiotestsrc videotestsrc
- jpegparse jpegenc jpegdec pngenc pngdec
- tcpclientsink tcpclientsrc tcpserversink tcpserversrc udpsink udpsrc
- xvimagesink ximagesink evasimagesink evaspixmapsink glimagesink (mmfw ini)
- theoraenc lame vorbisenc wavenc volume oggmux avimux matroskamux (mmfw ini)
- v4l2src avsysvideosrc camerasrc fimcconvert (mmfw ini)
=> [Api/Tizen] restricted elements in Tizen

nnstreamer.ini.in
Remove unnecessary lines about tensorflow optimization.
The key of mem-optimize was removed and these lines are now unnecessary.
=> [Config] remove unnecessary lines

api/android/build-android-lib.sh, api/capi/meson.build, meson.build, packaging/non_tizen_build.patch
When enable-capi is set and enable-tizen is not set,
meson modifies nnstreamer.h to build capi without tizen
However, that modification is not reverted
This PR reverts the modification at the end of install
=> [build] Cleanup after build - @open sesame 09/18 16:38

api/capi/src/nnstreamer-capi-single-new.c, api/capi/src/nnstreamer-capi-single.c
Added bug fix for thread safe usage
Single shot API use single handle lock for making all its API call thread safe
However, the call to close the API destroys the handle itself making the
call to close not thread safe
Added a global lock to make closing of handles thread safe
=> [single] Thread safety bug fix - @open sesame 09/19 18:24

tests/nnstreamer_plugins/unittest_plugins.cpp
This PR is related to a sub-item of https://github.com/nnsuite/nnstreamer/issues/1608.
A GCC bug [1] might cause warnings related to 'conversion-null' when using googletest macros with !FALSE as arguments. Therefore, in the case that Werror is true, the build would be broken by this bug. To avoid such situation, this patch replaces EXPECT_EQs in the plugin unit tests with EXPECT_TRUE or EXPECT_FALSE.
[1] https://github.com/google/googletest/issues/322
Detail build logs are as follows:
```bash
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: …
```
=> [Tests/Plugins] Avoid warnings caused by a GCC bug related to gtest - @open sesame 09/19 18:24

tests/tizen_capi/unittest_tizen_capi.cpp
function declaration to avoid build warning (missing-declaration)
=> [Build] remove warning message

README.md
This patch corrects typo in bullet items under the Getting Started section.
=> [ReadMe] Correct typo in bullet items under Getting Started

tests/nnstreamer_filter_custom/runTest.sh, tests/nnstreamer_repo_lstm/runTest.sh, tests/nnstreamer_repo_rnn/runTest.sh
Tests which require custom shared library does not consider the tests using the unittest package (which means not the build time test). They uses hardcoded path to indicate the location of the shared library. In order to fix this problem, this patch makes the test use the default installation directory when the test is running using the unittest package.
=> [Tests/CustomFilters] Use default installation direcotory

tests/nnstreamer_repo_dynamicity/runTest.sh
As a workaround for running tests on Yocto, this patch uses the default installation directory excepting that the tests are running at the build time or the directory where the test binary is located is provided.
=> [Tests/RepoDynamicity] Support running tests on Yocto @open sesame 09/25 19:05

tests/nnstreamer_filter_tensorflow_lite/runTest.sh
NNAPI tests are only needded in the case of Tizen. Although these tests are not harmful on the other platform, this patch makes those NNAPI tests run only on Tizen.
=> [Tests/TFLite] Run NNAPI tests only on Tizen

tests/gen24bBMP.py, tests/nnstreamer_converter/generateGoldenTestResult.py, tests/nnstreamer_filter_caffe2/checkLabel.py, tests/nnstreamer_filter_custom/checkScaledTensor.py, tests/nnstreamer_filter_python/checkScaledTensor.py, tests/nnstreamer_filter_pytorch/checkLabel.py, tests/nnstreamer_filter_tensorflow/checkLabel.py, tests/nnstreamer_filter_tensorflow_lite/checkLabel.py, tests/nnstreamer_repo_rnn/generateTestCase.py, tests/transform_dimchg/checkResult.py, tests/transform_stand/checkResult.py, tests/transform_typecast/checkResult.py
There are several platforms which do not support python2.7 by default anymore. To prepare this issue, this patch revises all python scripts in tests to be also compatible with python3.
=> [Tests] Make tool scripts written in python be compatible with python3 @open sesame 9/27 15:09

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
Sometimes testcase failed with pipeline state NULL when stopping the pipeline.
Add sleep time before closing the pipeline.
=> [Android/Test] tc fail case

packaging/nnstreamer.spec
remove meson-related directory in coverage report.
=> [Coverage] remove meson private folder

CHANGES, debian/changelog, jni/nnstreamer.mk, meson.build, packaging/nnstreamer.spec
This is 1.0 RC2.
With Tizen Official Release, 1.0 stable will be released.
I'll merge this commit with next SR in Tizen.org. Don't merge it before that.
=> Release of nnstreamer 1.0.0 (1.0 RC2) @open sesame 9/30 13:28

ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, meson.build, meson_options.txt, packaging/nnstreamer.spec
Skeleton code for Tizen-nnfw is added.
New nnfw of Tizen has its own interface; thus, we can no longer
rely on tensorflow-lite/nnapi for this.
This uses https://review.tizen.org/gerrit/gitweb?p=platform/core/ml/nnfw.git;a=summary as the backend.
=> [Filter/nnfw] Tizen-nnfw skeleton @open sesame 9/27 13:16

gst/nnstreamer/tensor_mux/gsttensormux.c
For the readability and to follow how mux element is used in gstreamer,
1. Move 'tensor_mux name=mux ! fakesink' from front to back.
2. Add \ for readability
3. Add missing regular expression ']|'
Signed-off-by: niklasjang <niklasajang@gmail.com>
=> [Code Clean] Make example launch line in remark follow convention.

ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, packaging/nnstreamer.spec, tests/meson.build, tests/tizen_nnfw_runtime/meson.build, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cpp
This validates integration mechanisms for nnfw-runtime of Tizen.
=> [Tizen/nnfw] Add open/close callbacks for tensor_filter

api/capi/src/nnstreamer-capi-tizen.c
remove code which occurs error.
Since the previous code lock the resource internally,
when another pipeline want to contact to the resource, an error is generated.
=> [Api/Tizen] remove code which occurs error

packaging/nnstreamer.spec
This patch fixes the rootstrap buildbreak issue by using relative path
instead of absolute one.
=> [API/Tizen] Fix the rootstrap buildbreak issue

api/capi/meson.build, api/capi/src/nnstreamer-capi-pipeline.c, api/capi/src/nnstreamer-capi-tizen.c, packaging/nnstreamer.spec
Check the pipeline with device policy restricted case.
Create dpm handle and when trying to start the pipeline, check device policy and handle error case.
=> [Api/Tizen] handle dpm restriction case

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c, tests/nnstreamer_sink/unittest_sink.cpp
It is dangerous to cast from gint to guint and vice versa.
According to Gstreamer GstBaseSrc menual, num-buffer's type is  'gint' not 'guint'.
num-buffers means 'Number of buffers to output before sending EOS (-1 = unlimited).
And because of comparison with buffer_index, buffer_index also must be also gint type.
<https://gstreamer.freedesktop.org/documentation/base/gstbasesrc.html?gi-language=c#GstBaseSrc:num-buffers>
Signed-off-by: Niklas Jang <niklasjang@gmail.com>
=> [test]Change num_buffers type from guint to gint @open sesame 10/14 18:52

gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_source/tensor_src_iio.c, gst/nnstreamer/tensor_transform/tensor_transform.c, tests/nnstreamer_source/unittest_src_iio.cpp
This patch use explicit type casting between variables and return values of
`g_ascii_strtoll()` or `g_ascii_strtoull()` functions.
This resolves issue #1762, which is about potential warnings
from compilers with strict option.
Original codes invoke warnings from gcc with `-Wconversion` option.
Signed-off-by: Injae Kang <abcinje@gmail.com>
=> [Typecast] Use explicit type casting with g_ascii_strto(u)ll function

api/android/api/src/main/jni/nnstreamer-native-api.c
add log to print nnstreamer, gstreamer and glib version info.
=> [Android] add log to print version string

api/capi/src/nnstreamer-capi-util.c
This intends to fix:
```
There may be a null pointer dereference, or else the comparison against null is unnecessary.
In ml_tensors_data_create: All paths that lead to this null pointer comparison already dereference the pointer earlier (CWE-476)
```
It appears that Coverity hates defensive coding.
ps. Please Review. But Do not Merge until we test this with Coverity/SVACE
=> [Coverity/1087163] Fix dereference before null check

ext/nnstreamer/tensor_filter/tensor_filter_python_core.cc
Define macro for file format and remove macro(preprocess defines) in the function call.
This PR is related with ssms-1016-0007.
=> [Security] python lib name format @open sesame 10/17 15:00

gst/nnstreamer/tensor_converter/tensor_converter.c
get min block size and use memcpy when input mime-type is text.
This PR is related with ssms-1016-0005.
=> [Security] [Converter] handle text format in chain function @open sesame 10/17 15:17

README.md
This commit is to append the badge of the Coverity (static analysis tool).
TODO: the Coverity module of TAOS-CI will be soon enabled in the nnstreamer GitHub repository.
---
=> Added the coverity badge

tests/meson.build, tests/tizen_capi/meson.build
Install models/data with tests correctly when needed
Install tizen-capi-unittest with install-test option
Install python and caffe2 unittests
=> [tests] Install models/data with tests @open sesame 10/16 19:28

api/android/build-android-lib.sh
Added excution bit of gradlew to prevent permission denied error.
The "api/android/build-android-lib.sh" file has changed
related issue: #1793 
Signed-off-by: 이원준 <dldnjs1013@nate.com>
=> [Android/Api] Add execution bit of gradlew

packaging/nnstreamer.spec
This patch fixes typo in `packaging/nnstreamer.spec`
Signed-off-by: Injae Kang <abcinje@gmail.com>
=> [Typo] Fix typo

ext/nnstreamer/tensor_decoder/meson.build, ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
It is a implementation of #69 [WIP][bashscript/android] Support tflite segmentation model.
This PR contains two commits.
1. Tensor decoder for image segmentation
- skeleton code of tensor decoder for image segmentation
2. Meson build for image segmentation decoder
- Changed `meson build` for image segmentation
[ex]
We will continue to improve this decoder :)
Signed-off-by: niklasjang <niklasjang@gmail.com>
Signed-off-by: Jihoon Lee <ulla4571@gmail.com>
=> [Decoder] Tensor decoder for image segmentation

api/capi/include/nnstreamer-single.h, api/capi/src/nnstreamer-capi-single-new.c, api/capi/src/nnstreamer-capi-single.c
Adding support for flexible input dimension
Added API and skeleton for setting input dimension via single API
Check #1651 for more information
=> [single] Added API and skeleton for flexible input dimension

api/android/api/src/main/jni/Android-gst-plugins.mk, api/android/api/src/main/jni/Android.mk, api/android/build-android-lib.sh
Add build option to set target abi and core gstreamer plugins.
For example, to build library with core plugins for arm64
./build-android-lib.sh --api_option=core --target_abi=arm64
This only includes gstreamer core plugins, so library size is under 15MB.
=> [Android] add option to build with min plugins

ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c, jni/nnstreamer.mk
1. handle allocation failure case
2. fix possible mem leak to get the out caps
3. add definition to include img segment in android-libray
=> [Decoder/Sub] mem error case in img segment

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h, gst/nnstreamer/nnstreamer_plugin_api.h, gst/nnstreamer/tensor_common.c
Added implementation for setInputDimension
This can allow support for flexible input dimensions
The support is limited to only changing dimensions
Data type for the input or the number of inputs cannot be changed with current TF-Lite API
The rank for the input is allowed to be changed if the model allows
The input dimension can return error if the model does not allow dimension to be changed
Check #1651 for more information
=> [TF-Lite] Added setInputDimension

ext/nnstreamer/tensor_filter/tensor_filter_pytorch_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_pytorch_core.h
First run after configuring the tensor filter with pytorch framework
is now run with a try/catch.
Check #1809 for more details.
=> [pytorch] Do first run with try/catch @open sesame 10/22 15:50

debian/control, debian/nnstreamer-cpp-dev.install, debian/nnstreamer-cpp.install, debian/nnstreamer-dev.install, ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc, ext/nnstreamer/tensor_filter/tensor_filter_cpp.h, meson_options.txt, packaging/nnstreamer.spec
Before adding test cases for C++ filter subplugins,
enable build for Tizen/Ubuntu.
Add enable-cppfilter=true for meson build if you
want to use this feature.
Fixes #1692 
=> [Filter] Enable C++ subplugin build @open sesame 10/18 16:07

api/capi/src/nnstreamer-capi-single-new.c, api/capi/src/nnstreamer-capi-single.c
Added simplification for get_tensors_info in single API implementation
input and output tensors info is stored in single API
This patch updates to use that information than extracting the info again from element
=> [single] simplify get_tensors_info in single API @open sesame 10/22 11:55

api/capi/include/platform/tizen_error.h, api/capi/meson.build, debian/rules, meson.build, packaging/generate-tarball.sh, packaging/nnstreamer.spec
In order to build C-API for Non-Tizen platforms, nnstreamer.h should be modified or patched at build time to emulate some Tizen-dependent symbols.  Instead, this PR adds a mock header, tizen_error.h, which emulates symbols required to build C-API and includes system header. In addition, the rpm spec file is also modified to filter out the mock header so that any Tizne packages do not contain that header.
Fixes: #1796 
Overrides: #1800 
See also: #1795
Note that the build script for Android API will be addresses in anther PR.
=> [C-API] Use mock tizen_error.h when building C-API for Non-Tizen platform

tests/meson.build, tests/nnstreamer_sink/unittest_sink.cpp
This PR is required to enable build-time tests NNStreamer on macOS deployed with Travis CI and mainly focuses on fixing that unittest_sink is failed.
In low performance machines such as VMs in the cloud,  there are several cases that the pipelines cannot finish their job until the pipeline is stopped.  Moreover, sometimes they even cannot keeo the given framerate so that few buffers are lost while testing. To work around this issue, this PR adds command-line options for adding jitter between start and stop pipe qnd controlling the speed of tests made of videotestsrc-based single pipeline.
Resolves a sub-item of #1608
See also: https://github.com/nnsuite/homebrew-neural-network
*Self evaluation:**
1. Build test: [*] Passed [ ]Failed [ ]Skipped
2. Run test: [*] Passed [ ]Failed [ ]Skipped …
=> [Tests/Sink] Fix test failure on macOS/Travis CI @open sesame 10/22 20:30

meson.build
When numpy is installed using pip, meson couldn't find
numpy/arrayobject.h.
I included pip include path to find numpy.
This patch resolves #1805.
Signed-off-by: Injae Kang <abcinje@gmail.com>
=> [Build] Include pip include path to find numpy

gst/nnstreamer/tensor_filter/tensor_filter_custom.c
Recent TAOS-CI/Android complains:
.../tensor_filter_custom.c: In function 'custom_loadlib':
.../tensor_filter_custom.c:95:15: warning: assignment discards 'const' qualifier from pointer target type
dlsym_error = dlerror ();
^
ps. need #1828
=> [Filter/Custom] Fix compiler complaints @open sesame 10/25 20:38

ext/nnstreamer/tensor_filter/meson.build
fix the cpp filter-subplugin path for test coverage report.
=> [Coverage] source path for coverage report @open sesame 10/25 11:38

api/android/api/src/main/jni/Android-gst-plugins.mk, api/android/build-android-lib.sh
change the build option 'lite' and add library name with given options.
=> [Android] set library name in build script

gst/nnstreamer/tensor_filter_custom_easy.h
This allows to define a custom-filter (C) easily.
This will be especially helpful for C/C++ application writers.
The same approach may be implemented for C#/Java for Tizen.NET and Android app writers.
This commit is to make a suggestion.
Implementation can wait until we conclude with the prototype.
Rationale:
- In most cases, the custom-filter struct is an overkill. Thus, this might be useful. 
- In other words, "what if an app writer simply wants to insert a simple C-function in a pipeline?"
Change-Id: Id1ff43424283c217c0688e91b919ade99e3cc134
=> [Filter/Custom-Easy-C] Prototype of Custom-Easy Tensor Function

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, tests/meson.build, tests/test_models/models/metadata/MANIFEST, tests/tizen_nnfw_runtime/meson.build, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cpp
Added nnfw base testing scenario for verification along with a few bug fixes                                                             
NNFW repo has been updated to test with cpu backend                                                                                      
However, that patch has not been uploaded to main tizen repo                                                                             
So, in order to test this patch, clone nnfw repo and build locally                                                                       
Also, building nnfw repo installs libbackend_acl_cl.so in /usr/lib in emulator                                                           
Delete this file to test nnstreamer with cpu backend with nnfw successfully
This is because …
=> [nnfw] Adding nnfw base test for verification @open sesame 11/4 14:51

tests/tizen_capi/unittest_tizen_capi.cpp
Add testcase.
If tensorflow is not supported, opening tf model (single api) returns not-supported.
=> [Test/Api] tc with unavailable nnfw

ext/nnstreamer/tensor_filter/tensor_filter_caffe2_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_caffe2_core.h
First run after configuring the tensor filter with caffe2 framework is now run with a try/catch
Check #1809  for more details
cc. @helloahn
=> [caffe2] Do first run with try/catch 

README.md
This commit is to append a badge to display current defects of Coverity Scan.
---
=> Added a badge to display current coverity defects

gst/nnstreamer/tensor_converter/tensor_converter.c
fix typos of the `tensor_converter.c` file
=> [Typo] fix typos of tensor_converter.c

api/capi/doc/nnstreamer_doc.h, api/capi/include/nnstreamer-single.h, api/capi/include/nnstreamer.h
This patch removes an unnecessary asterisk on header file for doxygen.
After running Tizen Native API Check script tool, this issue is reported by Sunggyu Choi.
=> [C-API] Remove unnecessary asterisk on header file - @open sesame 11/11 17:31

tests/nnstreamer_source/unittest_src_iio.cpp
This PR addresses the Coverity defects in GENERATE_TESTS_TO_VERIFY_DATA_WO_TRIGGER, which is a macro for test generation. 
- Fix defects about resource leak found from Coverity
- These defects are caused by the previous PR #1859 
- Fix TOCTOU and NEGATIVE_RETURNS defects as well
CC: @kparichay
=> [Tests/Src/IIO] Fix Coverity defects in a macro that generates tests 

api/capi/include/nnstreamer-capi-private.h, api/capi/include/nnstreamer.h, api/capi/src/nnstreamer-capi-pipeline.c
Currently only 'other/tensor' and 'other/tensors' are available for `appsrc` with C-API.
Since there are many `media types`(video, audio, text, octet) that should be used as a `src` data, and they cannot be used currently, this commit makes them available with a partial restriction.
With this commit, I checked the `video/x-raw` works properly, and others will be tested with other sample apps.
Since there will be restriction, however, we need to discuss this method is desirable.
=> [C-API] make other mediatypes available with appsrc

api/android/api/src/main/jni/nnstreamer-native-api.c, api/android/api/src/main/jni/nnstreamer-native-customfilter.c, api/android/api/src/main/jni/nnstreamer-native-pipeline.c, api/android/api/src/main/jni/nnstreamer-native-singleshot.c, api/android/api/src/main/jni/nnstreamer-native.h, api/capi/include/nnstreamer-single.h, api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c, tests/nnstreamer_sink/unittest_sink.cpp
1. remove static inline function in header for sam score
2. release handle when called invoke-dynamic
3. return type to validate tensors info
4. add condition to check ncsdk2
5. clean unnecessary code in android native
=> [CodeClean] cleanup sources and fix mem leak in api  @open sesame 11/14 12:50

api/capi/src/nnstreamer-capi-pipeline.c, tests/tizen_capi/unittest_tizen_capi.cpp
When trying to register sink callbacks to same sink element, it returns null handler.
To fix this, allocate new handle and add it  into the handle list.
=> [C-Api] fix invalid sink handle @open sesame 11/15 15:55

api/capi/src/nnstreamer-capi-single.c, api/capi/src/tensor_filter_single.c, tests/tizen_capi/unittest_tizen_capi.cpp
Enable flexible input dimension for custom filters
Add corresponding unittest
Refer #1651 
=> [single] Enable flexible input dimension for custom filters @open sesame 11/15 15:45

.github/PULL_REQUEST_TEMPLATE.md
This patch removes an unintended blank in the self-evaluation section of the template file for PR.
=> [Github] Remove an unintended blank in the template file for PR

api/capi/src/nnstreamer-capi-util.c
Until we implement its supporting code, assume a new
nnfw is NOT SUPPORTED.
This makes sure that it does not reply "supported" for
arbitrary new NNFWs.
=> [CAPI] By default a new nnfw is "not available" @open sesame 11/20 16:34

packaging/nnstreamer.spec
When .so files are added or removed,
ldconfig should be called.
=> [Dist/Tizen] Execute ldconfig after touching .so files @open sesame 11/18 19:50

ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c, gst/nnstreamer/nnstreamer_plugin_api.h, gst/nnstreamer/tensor_common.c, gst/nnstreamer/tensor_converter/tensor_converter.c, gst/nnstreamer/tensor_merge/gsttensormerge.c, gst/nnstreamer/tensor_split/gsttensorsplit.c, gst/nnstreamer/tensor_transform/tensor_transform.c, nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c, nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c, tests/nnstreamer_sink/unittest_sink.cpp
change improper return type to get tensor element size/count.
=> [Common] change return type

tests/bmp2png.c
This patch fixes unintended-sign-extension defects reported by Coverity in the bmp-to-png tool.
=> [Tests] Fix Coverity defects in the bmp-to-png tool

Documentation/getting-started.md
Updated the mirrors for debian build in the getting-started docs
This now complies with the list of mirrors used by launchpad of nnstreamer
=> [Docs] Updated the mirrors for debian build @open sesame 11/21 13:42

debian/control, meson.build, packaging/nnstreamer.spec
Update nnstreamer package to support c++14 language standard
This is primarily needed to support armnn tensor filter subplugin
armnn headers use c++14 compliant code
More info in #1817
=> [spec/meson] Update nnstreamer package to support c++14 language standard @open sesame 11/21 14:11

api/capi/include/nnstreamer.h
We will be supporting new NPU hardware along with
its userspace libraries.
Prepare enum spaces for them for future development.
=> [CAPI] Add enum for incoming NPU hardware @open sesame 11/21 14:12

ext/nnstreamer/tensor_source/tensor_src_tizensensor.c, ext/nnstreamer/tensor_source/tensor_src_tizensensor.h
This adds get/set property methods for tizen sensor extension plugin.
This should follow #1857 and addresses #1143
=> Tensor-src-tizensensor: add get/set properties @open sesame 11/20 16:29

ext/nnstreamer/tensor_filter/meson.build, packaging/nnstreamer.spec
Resolves #1845 
See also #1709
This PR addresses #1845, which is about enabling the tensor filter extension for Intel Movidius Neural Compute stick SDK2 (NCSDK2) in Tizen.
=> [Dist/Tizen] Enable nnstreamer-ncsdk2

tests/common/unittest_common.cpp, tests/nnstreamer_plugins/unittest_plugins.cpp, tests/nnstreamer_sink/unittest_sink.cpp, tests/nnstreamer_source/unittest_src_iio.cpp
Add try/catch for exceptions thrown by function calls in main bosy when using gtest
=> [tests/coverity] Fix coverity issues related to gtest main

Documentation/component-description.md, gst/nnstreamer/tensor_converter/README.md
update docs about the dimension of each media stream.
=> [Doc] dimension in converter @open sesame 11/28 15:24

gst/nnstreamer/nnstreamer_plugin_api.h, gst/nnstreamer/tensor_common.c
1. validate tensor info when comparing the structure.
2. fix invalid doxygen tag.
=> [Common] condition to compare tensor info

gst/nnstreamer/tensor_transform/tensor_transform.c
init 0 to register the enum-value for transform mode option.
=> [Transform] init 0 for mode enum-value

gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h
This PR adds new tensor filter property to indicate a given model
to a tensor filter is updatable or not. The default value is False.
Related issue: https://github.com/nnsuite/nnstreamer/issues/1900
=> [PROP] Add new tensor filter prop to indicate a model is updatable - @open sesame 12/03 19:23

packaging/nnstreamer.spec
With recent changes in the dependencies between
libarmcl and nnfw, nnfw incurs have-choice-for
errors for its users.
Fixing this requires some overlap periods for the
integration system; thus, we need this workaround for a while
until the OBS eliminates obsolete packages (libarmcl-release)
This is to be group-SR'ed with armcl.git in Tizen;
thus, this won't be able to pass CI-Tizen build until
everything gets fixed up.
=> [Dist/Tizen] Fix integration error with libarmcl

debian/control
This PR fixes a typo of nnstreamer-cpp package in debian/control.
=> [TYPO] Fix a typo of nnstreamer-cpp package in debian/control

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Now, nnfw will use available backend. Thus, no need to configure default backend manually.
Test on gbs build:
Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>
=> Remove nnfw default backend configuration - @open sesame 12/09 17:36

debian/control
This PR adds a missing debian package for nnstreamer-caffe2.
Note that it has a dependency on PyTorch.
CC: @helloahn 
=> [DIST/DEBIAN] Add a missing debian package for nnstreamer-caffe2

api/capi/src/tensor_filter_single.c, ext/nnstreamer/tensor_filter/tensor_filter_caffe2.c, ext/nnstreamer/tensor_filter/tensor_filter_caffe2_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, ext/nnstreamer/tensor_filter/tensor_filter_python.c, ext/nnstreamer/tensor_filter/tensor_filter_pytorch.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c, gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_custom.c, gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c, tests/nnstreamer_plugins/unittest_plugins.cpp, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cpp
This PR revises the model property to support multiple model files.
Also,` tensor_filter_common.c` now does not handle FW-specific model file
semantic info (e.g., pred/init files).
CC: @jaeyun-jung
=> [PROP/MODEL] Revise the model property to support multiple model files

gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h
This PR adds a callback, `reloadModel()`, of tensor filter for model
update in runtime. When the model property is updated, this callback
will be called if `is-updatable` is TRUE.
Also, it adds an event handler to update a model in the same pipeline.
On receiving a model update event, it calls `set_property()` of `PROP_MODEL`.
Related issue: #1900
=> [TensorFilter] Add a callback of tensor filter for model update in runtime

tests/nnstreamer_sink/unittest_sink.cpp
This PR adds a missing g_clear_error() in unittest_sink.cpp.
=> [FIX] Add a missing g_clear_error() in unittest_sink.cpp

api/capi/include/nnstreamer-capi-private.h, api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c, tests/tizen_capi/unittest_tizen_capi.cpp
Check input/output tensor info when opening the nn model.
If given info is not matched with model, try to change input info for dynamic mode.
=> [C-Api/Single] check invalid tensor info @open sesame 12/05 15:11

api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c, ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, meson.build, meson_options.txt, nnstreamer.ini.in, tests/tizen_capi/unittest_tizen_capi.cpp, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cpp
- Update the nnfw framework input model format to work with file path
- Enable nnfw for single API
- nnfw and tensorflow-lite both support tflite extensions. Added meson option to set default behavior which prioritizes tensorflow-lite
- Add invoke test for nnfw with single API
=> [nnfw/single] enable nnfw for single API

gst/nnstreamer/nnstreamer_conf.c
This PR removes unnecessary `g_key_file_free()` because `g_autoptr`
already provides a cleanup process. This bug was detected by Valgrind.
=> [FIX/CONF] Remove unnecessary g_key_file_free()

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
This PR adds temporary fix for aarch64 enabling successful build and
testing of nnfw plugin for nnstreamer
This PR will be reverted once the nnfw package fixes are applied.
After this PR and #1856, #1912 can go ahead.
=> [nnfw] nnfw fix for aarch64 @open sesame 12/12 15:44

gst/nnstreamer/tensor_filter/tensor_filter_common.c
Remove unnecessary space in the description.
(Using gst-inspect, the property model shows unnecessary space)
=> [Filter] property description

api/capi/src/nnstreamer-capi-pipeline.c, ext/nnstreamer/tensor_source/tensor_src_tizensensor.c, packaging/nnstreamer.spec, tests/tizen_capi/dummy_sensor.c, tests/tizen_capi/dummy_sensor.h, tests/tizen_capi/meson.build, tests/tizen_capi/sensor.h, tests/tizen_capi/unittest_tizen_sensor.cpp
1. Unit tests are added.
2. dummy_sensor.c/h offers dummy Tizen sensor framework for unit tests,
where we cannot activate Tizen sensor framework daemon.
3. Bugs were found with the unit tests and they are fixed.
- g_hash_table misuses
- property configuration errors
- frequency (framerate) handling
- Clean up and configured-status handling
- Mutex deadlock
- Timestamp handling
=> UnitTest: Tensor-src-tizensensor / Initial test cases & fixes

tests/nnstreamer_sink/unittest_sink.cpp
This PR adds a test option, `need_sync`, for sync property in `TensorSink`.
Basically, GstBaseSink has a `sync` property enabled by default, and
`TensorSink` also does. In this case, if the frame is later than max-lateness,
the sink will drop the buffer without calling the render method.
It can be a problem if some unittests (e.g., `signals`) expects the exact
number of received data. In slow system, if a signal callback is too slow,
some buffer can be dropped.
To fix this problem, this patch adds a test option for sync property and
sets `sync` property as `FALSE` by default to disable the buffer dropping
feature for `signals` unittest.
2. Run test: [*]Passed [ ]Failed …
=> [TensorSink/UnitTest] Add a test option for sync property in TensorSink

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h, gst/nnstreamer/nnstreamer_plugin_api_filter.h
This PR revises tflite sub-plugin to support model reloading.
It implements an interpreter class with its own mutex, which wraps
existing codes. Also, it's designed to support interpreter switching
to hide the overhead of model reloading.
Related issue: #1900
**changelog**
V4: Add extra notes for a `reloadModel` callback.
V3: Add error handling for model mismatch
V2: Remove operator overloading
=> [TFLITE/RELOAD] Revise tflite sub-plugin to support model reloading

packaging/nnstreamer.spec
Because TAOS-CI skips unittests for ARM/ARM64 because of the latency,
we need to enable unittests for ARM-only tests unconditionally
if the test-target features are ARM-only.
Especially, this will help preventing regressions from other packages
in Tizen by enabling unit-tests in Tizen build (build.tizen.org) for
those selected features.
ps. We will enable the full unit tests in all arch for Tizen build soon, in order to prevent regressions from other packages.
ps2. This will enforce testing nnfw and sensor-fr in Tizen for every SR.
=> Policy Update: Test Tizen Features in ARM, always.

CHANGES, debian/changelog, jni/nnstreamer.mk, meson.build, packaging/nnstreamer.spec
Versioning Rule Proposal:
- 1.even.0 is the minor release.
- 1.even.1+ is a stability update for the minor release
- 1.odd.x is a developmental version.
- When 1.odd.x is completed, it will release 1.odd+1.0 and move on to 1.odd+2.0.
> Release of nnstreamer 1.2.0
>
> New features are coming with 1.2.0
> Release of 1.3.0, the development version
>
> When 1.3.x is completed, it will be released as 1.4.0 and
> 1.5.x development will be started
=> Release of 1.2.0 & Start of 1.3.0 development

tests/tizen_capi/unittest_tizen_capi.cpp
Probably because of GTest macros, having if statement around
EXPECT_* appears to be not a good approach if it is not bracketed.
Fix compiler warnings from such.
=> Test/Fix Compiler Warning (else ambiguity)

gst/nnstreamer/nnstreamer_conf.c, gst/nnstreamer/nnstreamer_conf.h
To handle paths/files of each subplugin category,
use loops and enums instead of hardcoded variables.
=> Refactor/Conf: avoid using hardcoded categories

packaging/nnstreamer.spec
nnfw package is now created and corresponding tests performed
only for tizen in the spec file.
=> [spec] nnfw now packaged only for tizen

ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc, meson_options.txt
Support EdgeTPU with non-NNAPI tensorflow-lite interface (delegation).
Tested with Ubuntu 18.04 + Coral Edge-TPU + Mobile-SSD TF Lite model.
TODO (later PRs): How to test with w/ GTest in CI?
Fixes #1661
=> Filter: support EdgeTPU with tensorflow-lite interface

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter_common.c
Allow setting of accelerator for nnfw
Parsing accelerator moved to tensor_filter_common. Currently, used in
tflite and nnfw, and use directly for other filters like this.
Related Issue: #1849 
=> [nnfw] Set accelerator for nnfw

packaging/nnstreamer.spec
Because it has an executable (shared library), we need
SMACK manifest information.
=> Dist/Tizen: add missing manifest for source-tizen-sensor

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Reverse the order of dimensions with nnstreamer as
nnfw stores dimension in accordance with tflite
=> [nnfw] Reverse the order of dimension

api/android/README.md, api/android/api/src/main/jni/Android.mk, api/android/api/src/main/jni/nnstreamer-native-api.c, api/android/build-android-lib.sh
Update script to build Android library including SNAP.
Before running with option --enable_snap=yes, developer should define SNAP_DIRECTORY (dir path to SNAP sub-plugin and prebuilt library)
=> [Android/SNAP] build script for SNAP @open sesame 12/23 20:04

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/tensor_filter/tensor_filter_common.c, tests/nnstreamer_filter_tensorflow_lite/runTest.sh
Tensorflow-lite unittest which tests for appropriate hardware accelerator backend parsing and testing
should always pass.
=> [tflite] Acceleratator HW unittest should always pass

tests/meson.build, tests/nnstreamer_filter_reload/runTest.sh, tests/nnstreamer_filter_reload/tensor_filter_reload_test.c
This PR adds a testcase to test asynchronous model updates during
tflite inferences. It repeatedly switches tflite models between
mobilenet_v1 and mobilenet_v2. It expects the same index for input img.
=> [TEST/RELOAD] Test runtime model reloads during tflite inferences

gst/nnstreamer/tensor_filter/tensor_filter_common.c
This PR fixes the wrong log message for custom-easy tensor filter sub-plugin.
For this sub-plugin, we don't need to check whether the model path exists.
The below describes the original problem.
```
[----------] 1 test from tensor_filter_custom_easy
[ RUN      ] tensor_filter_custom_easy.in_code_func_01
** (unittest_sink:25055): CRITICAL **: Cannot find the model file [0]: safe_memcpy_10x10
[       OK ] tensor_filter_custom_easy.in_code_func_01 (1003 ms)
[----------] 1 test from tensor_filter_custom_easy (1003 ms total)
```
1. Build test: [*]Passed [ ]Failed [*]Skipped
2. Run test: [*]Passed [ ]Failed [*]Skipped
=> [FIX/LOG] Fix a wrong error message for custom-easy tensor filter @open sesame 12/23 21:25

api/capi/include/nnstreamer.h, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter_common.c, tests/nnstreamer_filter_tensorflow_lite/runTest.sh
Add TPU as a backend accelerator property option in list of hardware
accelerators
Move default accelerator to avoid changing default accelerator enum value
everytime a new backend device is added
Refer #1849 
=> [plugin/hw] Add more HW accelerator and update implementation

ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/tensor_filter/tensor_filter_custom.c
Replace asserts with appropriate error handling in tensor filter extensions
This will allows test cases for failure scenarios and handle erronous inputs
via single-shot API gracefully with error return than shutting down with assert failure
Issue : #1959 
=> [filter/ext] Replace asserts with error handling @open sesame 12/23 19:36

gst/nnstreamer/tensor_filter/tensor_filter_custom.c
prevent unnecessary logs if custom-filter does not define set/get dim callbacks.
=> [Filter/Custom] unnecessary log

Documentation/getting-started.md
This patch modifies the meson version required to build up-to-date, 0.50.
=> [Documentation] Modify the meson version required to build up-to-date

api/capi/include/nnstreamer.h
This patch explicitly set the enum value in pipeline buffer policy as
below.
* ML_PIPELINE_BUF_POLICY_AUTO_FREE: 0
* ML_PIPELINE_BUF_POLICY_DO_NOT_FREE: 1
=> [C-API] Set omitted enum value in pipeline buffer policy @open sesame 01/06 16:45

ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc, ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc, tests/common/unittest_common.cc, tests/meson.build, tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc, tests/nnstreamer_plugins/unittest_plugins.cc, tests/nnstreamer_sink/unittest_sink.cc, tests/nnstreamer_source/unittest_src_iio.cc, tests/tizen_capi/meson.build, tests/tizen_capi/unittest_tizen_capi.cc, tests/tizen_capi/unittest_tizen_sensor.cc, tests/tizen_nnfw_runtime/meson.build, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc, tests/unittestcoverage.py
This PR renames file extensions of test source codes written in C++
(i.e, *.cpp -> *.cc), which hurt the consistency.
Resolves #2003.
=> [Cpp/Ext] Renames file extensions of test source codes written in C++

ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
Related to https://github.com/nnsuite/nnstreamer/issues/1708.
After negotiated, the given neural network should be loaded into the acceleration device (note that, currently, CPU is the only supported one). This PR is a draft of the implementation of that mechanism.
=> [Filter/OpenVino] Load a given network into the acceleration device 

api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter_common.c, tests/tizen_capi/unittest_tizen_capi.cc
Add implementation to check hw support for framework while checking for its availability.
Added unittests for this functionality with tensorflow-lite
Run test: [x]Passed [ ]Failed [ ]Skipped    
=> [single/hw] Check hw support for framework @open sesame 1/716:07

debian/rules, packaging/nnstreamer.spec, packaging/run_unittests_binaries.sh, tests/meson.build, tests/nnstreamer_filter_extensions_common/deploy.sh, tests/nnstreamer_filter_extensions_common/meson.build, tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cpp, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Added basic unittests for all the the filter extensions
This creates failure cases of unittests for the interface defined with GstTensorFilterFramework
for most of the extensions, and performs basic unittests
Updated the unittest list in packaging files as well
Also added a script file to run all the test cases inside a folder
TODO:  python extensions in this as well
Issue: #1959
=> [filter/ext] Added basic unittests for all filter extensions

packaging/nnstreamer.spec, tools/development/count_test_cases.py
Aggregate all gtest and SSAT results at the end of testing.
After this, unittest-enabled gbs will show results like:
```
[  117s] GTest (total 232 cases)
[  117s]   Passed: 232 / Failed: 0 / Ignored: 0
[  117s] SSAT (total 513 cases)
[  117s]   Passed: 497 / Failed: 0 / Ignored: 16
[  117s] Grand Total: 745 cases
[  117s]   Passed: 729 / Failed: 0 / Ignored: 16
```
Suggested TODO in later PRs:
- Count negative test cases.
ps. We need to wait for https://dashboard.tizen.org/index.code?sr=submit/tizen/20191218.033148 accepted (need an update of SSAT)
=> Dist/Tizen: show unit test result summary @open sesame 1/7 17:07

tests/tizen_nnfw_runtime/meson.build, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Unit tests are added to verify NNFW with ML-API.
Detail of the added test case is :
- Single API, Invoke a sample model via Single API
- Invoke a sample model via Pipeline API, with a stream input
- Invoke a sample model via Pipeline API, with two input streams into a single tensor
- Invoke two-sample model via Pipeline API, sharing a single input stream
=>  [TEST] Unit test case for NNFW ML-API

ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc, ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc, ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc, ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc, ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc, ext/nnstreamer/tensor_filter/tensor_filter_python.cc, ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter_common.c
Currently, each sub-plugin of the tensor filter should check the validity of the path of the model files. In general, it leads to unnecessary code duplication.  Moreover, sometimes those are not checked
at all. This patch adds an option to centralize checking the path of model files so that each sub-plugin is in charge of the validity of model files only when this option is set to TRUE.
=> [Filter] Add an option to centralize checking the path of model files

ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_python.cc, packaging/run_unittests_binaries.sh, tests/nnstreamer_filter_extensions_common/meson.build
- Python initialize and finalize is done once for the module rather than doing it per object 
Doing initialization per object causes errors when importing modules
- Replaced Assert with appropriate error handing for python extension of tensor filter
- Added basic unittests for python which covers the failure cases
Issue: #1959
=> [python/ext] Added basic unittests for python @open sesame 12/24 15:38

gst/nnstreamer/nnstreamer_conf.c
Now Android functions do not use the conf file, remove assertion to run Android library.
=> [Android] assertion to load conf file

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, tests/nnstreamer_filter_tensorflow_lite/runTest.sh
Bug: Not setting accelerator ignored the use_nnapi configuration - this is resolved
Enable setting accelerator unittest non-tizen platforms as well
See also #1849 
=> [tflite/bug] Set accelerator bug solve

tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc
This PR fixes build errors in the source code generated from unittest_tizen_template.c.
```bash
error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
```
Even if #2014 also fixes those build errors, I think that it is better to merge this simple hotfix than to wait for merging #2014.
See also: #2014
1. Build test: [*]Passed [ ]Failed [*]Skipped
2. Run test: [*]Passed [ ]Failed [*]Skipped
=> [Tests/FilterExtCommon] hotfix: Fix build errors, dangling-else

packaging/run_unittests_binaries.sh
This patch makes the run_unittests_binaries script in ./packaging find only executable files.
=> [Tests/Script] Make the run_unittests_binaries script find executables

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/tensor_filter/tensor_filter_common.c
This PR defines the behaviour of reloading model files when the GstTensorFilter's property, verify_model_path, is set to TRUE and enables it on the tensor filter for TensorFlow Lite.
See also: https://github.com/nnsuite/nnstreamer/pull/1999
CC: @dongju-chae 
=> [Ext/Filter/TFLite] Enable a TensorFilter's property, verify_model_path 

gst/nnstreamer/tensor_common.c, tests/common/unittest_common.cc
Added proper comparison of GstCaps framerate (1/2 == 2/4)
Added corresponding unittest cases
=> [common] Added proper GstCaps framerate comparison

tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
This patch fixes failure in the test cases generated from unittest_tizen_template.cc.in. This is a bug of [1]
[1] cbb65b01278b39789e69c6de888b3e0e78b3e5db
=> [Tests/FilterExtCommon] Fix test case failure @open sesame 1/16 15:47

ext/nnstreamer/tensor_filter/meson.build, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, packaging/nnstreamer.spec, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Added verification of input model filename
This is performed by parsing the metadata/MANIFEST file to be provided with the model
The first model in the list of models should be the model to be run by nnfw
json-glib is added as dependency to allow json parsing
Corresponding unittest is also added
Resolve: #1981
=> [nnfw] Verify input model filename @open sesame 1/16 16:12

tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
Verify that the function is available before running tests for that function
Added the above verification for getInputDimension and getOutputDimension
Further enhanced invoke test to run successfully if the getDimension exists
=> [test/ext] Add condition for function to exist

debian/rules, meson_options.txt, packaging/nnstreamer.spec
This PR disables by default the tensor filters to support external neural network frameworks such as pytorch, caffe2, and tensorflow-lite in the meson_options.txt file. According to this change, the .spec and rules files are also modified as well.
=> [Meson] Disable external filters for pytorch, caffe2, tf-lite by default 

ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
Resolves https://github.com/nnsuite/nnstreamer/issues/1996
This PR mainly addresses Movidious Neural Compute Stick 1 and 2 support via the MYRIAD plugin of the OpenVino toolkit. In addition to this main change, 
- A trivial typo and bug are fixed.
- The mechanism for setting up 'accelerator' has bee revised.
See also: #1708
=> [Filter/OpenVino] Support the MYRIAD plugin @open sesame 1/16 15:46

ext/nnstreamer/tensor_filter/meson.build, tests/meson.build
In order to handle the case that 'enable-edgetpu' is set to 'true', meson requires a variable, 'tflite dep', which is a declaration of a dependency on TensorFlow-Lite. Therefore, the 'enable-edgetpu' option
alone cannot properly set the feature. This patch fixes this issue.
=> [Meson] Make 'enable-edgetpu' depend on 'enable-tensorflow-lite'

tests/nnstreamer_filter_edgetpu/unittest_edgetpu.cc
'videoformat' in the pipeline strings seems to be an invalid or illegal GST element so that it is replaced with 'videoscale'.
=> [Tests/Filter/EdgeTPU] Revise pipeline strings

gst/nnstreamer/nnstreamer_conf.c
Even if there is no .ini file, we need to load up the
subplugins from the default hardcoded paths or
the paths given with envvars.
ps. A few other PRs of mine needs this to pass the CI.
=> Fix: load the configuration even if there is no .ini file

gst/nnstreamer/tensor_split/gsttensorsplit.c
While build with GBS using the latest base and unified repository, the compiler complains about a variable that is used without initialization. Even though it looks a false-positive, this PR eliminates this build warning.
```bash
[   63s] FAILED: gst/nnstreamer/73d9e45@@nnstreamer@sha/gsttensorsplit.c.o 
[   63s] cc -Igst/nnstreamer/73d9e45@@nnstreamer@sha -Igst/nnstreamer -I../gst/nnstreamer -Igst/nnstreamer/tensor_transform -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Werror -std=gnu89 '-DVERSION="1.3.0"' -D__TIZEN__=1 -Wredundant-decls -Wwrite-strings -Wformat -Wformat-nonliteral -Wformat-security -Winit-self -Waddress -Wno-multichar -Wvla -Wpointer-arith …
```
=> [Split] Fix a build warning incurred by a may-be-uninitialized variable

debian/rules, gst/nnstreamer/nnstreamer_conf.c, meson_options.txt
1. Check null string before validating the conf file.
2. Disable default build option of python.
=> [CodeClean] build option for python and conf file in android

tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
Set max array for input and output tensor-memory to prevent out-of-index exception.
Invoke-callback requires the array of tensor memories.
Now this does not make an error, but later if we try to generate another testcase with multi-tensors, it needs to set the array of tensor data.
=> [Test] input memory to invoke filter-plugins

gst/nnstreamer/tensor_converter/tensor_converter.c
This PR adds type checking for the gst value, `supported_formats`.
When an unsupported colorspace is used, `gst_value_list_get_size()` has
generated unnecessary warnings.
Refer to the below for the original problem.
```
make[1]: Entering directory '/home/dchae/PR/nnstreamer-private-plugins'
cd tests && ssat -n && cd ..
(gst-launch-1.0:4388): GStreamer-CRITICAL **: gst_value_list_get_size: assertion 'GST_VALUE_HOLDS_LIST (value)' failed
(gst-launch-1.0:4402): GStreamer-CRITICAL **: gst_value_list_get_size: assertion 'GST_VALUE_HOLDS_LIST (value)' failed
(gst-launch-1.0:4418): GStreamer-CRITICAL **: gst_value_list_get_size: assertion 'GST_VALUE_HOLDS_LIST (value)' failed
```
=> [Fix] add type checking for gst value in tensor_converter.c

gst/nnstreamer/nnstreamer_conf.c
This PR skips duplicated paths from multiple conf sources.
It resolves #2057 
=> [Fix] Skip duplicated paths from multiple conf sources

ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
This patch revises the error handling mechanism for the API version of MvNCSDK not supported by NNStreamer.
=> [Filter/MvNCSDK] Revise error handling for unsupported API version

gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter_common.c, tests/nnstreamer_sink/unittest_sink.cc
Data layout added for tensor_filter in GstTensorFilterProperties 
Four data layouts are supported
- ANY - unknown does not matter
- NHWC - referred as channels last
- NCHW - referred as channels first
- none - doesnt fit with above options 
These data layouts can be different for each other/tensor in other/tensors 
Layout is taken input as a string, and then parsed for each tensor 
This layout is stored in tensor_filter element itself to be used by its subplugins, and not passed to other elements in the pipeline
Added corresponding unittests as well
This is not the final solution but a temporary solution to provide data layouts to tensor filters. Better solution is being tracked at #2051.
Related Issue: #1986 
2. Run test: …
=> [tensor_filter] Support data layout for tensor @open sesame 02/04 16:27

api/capi/include/nnstreamer.h, api/capi/src/nnstreamer-capi-single.c, api/capi/src/nnstreamer-capi-util.c, ext/nnstreamer/tensor_filter/meson.build, meson.build, tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc, tests/tizen_capi/unittest_tizen_capi.cc
Enable support for caffe in single-shot API with armnn as backend framework
Added test cases with caffe and tflite models
Verified by testing on tizen device.
Related issue : #1817 
=> [single/caffe] Enable caffe in single-shot API

packaging/nnstreamer.spec, tests/meson.build, tests/nnstreamer_filter_mvncsdk2/NCSDKTensorFilterTestHelper.cc, tests/nnstreamer_filter_mvncsdk2/NCSDKTensorFilterTestHelper.hh, tests/nnstreamer_filter_mvncsdk2/meson.build, tests/nnstreamer_filter_mvncsdk2/unittest_filter_mvncsdk2.cc, tests/test_models/labels/google_lenet_ncsdk_caffe_1.labels
This PR addresses unit testing of the mvncsdk2 tensor filter.
- A helper class for unit testing of the mvncsdk2 tensor filter is added.
- A basic test case for the most basic execution flow testing is added.
- The meson build scripts and the rpm spec files are updated.
See also: https://github.com/nnsuite/nnstreamer/issues/1709, https://github.com/nnsuite/nnstreamer/issues/1696
@TODO: Add failure test cases
=> [Tests/Filter/MvNCSDK2] Add a basic test case @open sesame 1/28 10:20

gst/nnstreamer/tensor_filter/tensor_filter.c
Resolve bug related to unused variable
If DBG is defined, this error is raised as the variable is only used
for check silent property when DBG is not defined
=> [tensor_filter] Unused variable bug resolve

packaging/nnstreamer.spec, tests/unittestcoverage.py
This PR generates test coverage results in `gcc-9` env.
But, it requires the latest version of lcov, and some perl modules.
So, enabling `testcoverage` should be done only in CI servers that can hold
cached RPM files (i.e., `lcov`, `perl-PerlIO-gzip`, `perl-JSON`).
=> [TestCoverage/Fix] Generate test coverage results in gcc-9 env.

tests/cpp_methods/unittest_cpp_methods.cc
GTest APIs may throw exceptions. Handle them.
Coverity CID 265573: Error handling Issues (UNCAUGHT_EXCEPT)
/tests/cpp_methods/unittest_cpp_methods.cc: 292 in main()
=> Fix/Coverity/265573: Handle thrown exceptions

tests/nnstreamer_filter_openvino/meson.build, tests/nnstreamer_filter_openvino/unittest_openvino.cc
In this PR, more test cases, which are not handled in #2071, are added.
- Test cases for getInput/OutputDimension () are added.
- Negative test cases for getIn/OutputDimension ()  are also added.
- Both positive and negative test cases for utility methods of the OpenVino Tensor Filter class are added.
Note that current line coverage is 85.2 %.
Resolves:  #1708 #2005
=> [Tests/Filter/OpenVino] Add more test cases for getInput/OutputDimension callbacks and other utility methods

packaging/nnstreamer.spec, tests/nnstreamer_filter_mvncsdk2/NCSDKTensorFilterTestHelper.cc, tests/nnstreamer_filter_mvncsdk2/NCSDKTensorFilterTestHelper.hh, tests/nnstreamer_filter_mvncsdk2/unittest_filter_mvncsdk2.cc
This patch adds failure test cases, which are based on the normal pipeline launch test case. Note that the current line coverage of tensor_filter_movidius_ncsdk2.c is 87.2%.
=> [Tests/Filter/MvNCSDK2] Add failure test cases 

tests/tizen_capi/unittest_tizen_sensor.cc
Coverity says not to use stack variable larger than 10kB.
Move verify_data data to global so that it does not
consume the stack.
=> Coverity/1123747/1123767/1123869: Stack Size Limit

api/capi/src/nnstreamer-capi-single.c
Added coverity fix of checking return value
In ml_single_set_info_in_handle: Value returned from a function is not checked for errors before being used (CWE-252)
Fix coverity issue CWE-416
Issue: In ml_single_set_info_in_handle: A pointer to freed memory is dereferenced, used as a function argument, or otherwise used
=> [coverity] single-shot API coverity fix

tests/tizen_capi/unittest_tizen_capi.cc
Fix to catch exception from GTest
Coverity CID  1123652, 1123668 : Error handling Issues (UNCAUGHT_EXCEPT)
tests/tizen_capi/unittest_tizen_capi.cc
=> [Coverity] 1123652/1123668 : Handle thrown exception

tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc, tests/nnstreamer_filter_edgetpu/unittest_edgetpu.cc, tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Fix to catch exception from GTest
Coverity CID : 1123913, 1123863 and potential error code
- tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc (coverity issue)
- tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc (potential error code)
- tests/nnstreamer_filter_edgetpu/unittest_edgetpu.cc (potential error code)
=> [Coverity] 1123913, 1123863 and potential error : Handle thrown exception

Documentation/component-description.md, Documentation/how-to-use-testcases.md
This PR fixes broken links for `SSAT` in documentation.
`nnsuite/SSAT` is no longer available.
It resolves #2094 
=> [Doc] Fix broken links for SSAT in documentation.

ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc, ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc, ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc, ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc, ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c, ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c, ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc, ext/nnstreamer/tensor_filter/tensor_filter_python.cc, ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc, gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_custom.c, gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c
Refactor subplugin interface
Add new interface for the subplugins along with the old interface
Added version number to check if old subplugin interface is used or the new one
Both the interfaces are added as a union,
This will allow for staggered changes rather a big change to be made at once
Related Issue: #2045 
=> [subplugins] Refactor subplugin interface

MAINTAINERS.md, RELEASES.md
LF/AI requires to add MAINTAINERS.md and RELESES.md
This is to comply with the propsal of
https://github.com/lfai/proposing-projects/pull/9
=> LF/AI: Add required documents

api/capi/src/tensor_filter_single.c, ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc, ext/nnstreamer/tensor_filter/tensor_filter_python.cc, ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc, gst/nnstreamer/nnstreamer_plugin_api_filter.h, gst/nnstreamer/tensor_filter/tensor_filter.c, gst/nnstreamer/tensor_filter/tensor_filter_common.c, gst/nnstreamer/tensor_filter/tensor_filter_common.h, gst/nnstreamer/tensor_filter/tensor_filter_custom.c
NNStreamer extensions for tensor filter update their functions based on the model file
However, this behavior is not thread-safe.
Updated for extensions to not update their functions (for destroyNotify and allocate_in_invoke)
For allocate_in_invoke, tensor_filter needs to know based on the model if the allocate_in_invoke is supported or not
So added another interface in GstTensorFilterFramework - allocateInInvoke
~destroyNotify interface is also updated. private_data for the subplugin is passed embedded in the data field so that
based on the private data, appropriate model specific destroy function for custom filter can be called~
V2:
Added allocate_in_invoke to be set properly in single API implementation of tensor_filter
Also added some minor updates in comment
Added minor bugfix in …
=> [subplugin/ext] Extensions not update their functions

tests/nnstreamer_filter_openvino/unittest_openvino.cc, tests/nnstreamer_plugins/unittest_plugins.cc
Fix coverity issues and potential error caused by resource leak.
Error occurred when assert test  was used after other memories were allocated.
The assert test performs immediately after the frame work was obtained.
- CID: 1123780, 1123859, 113952, 1123963
- tests/nnstreamer_filter_openvino/unittest_openvino.cc
=> [Coverity] Fix resource leak
