gst/tensor_filter/tensor_filter.c
gst/tensor_filter/tensor_filter.h
gst/tensor_filter/tensor_filter_custom.c
gst/tensor_filter/tensor_filter_tensorflow.c
gst/tensor_filter/tensor_filter_tensorflow_core.cc
gst/tensor_filter/tensor_filter_tensorflow_lite.c
gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc
include/tensor_filter_custom.h
include/tensor_filter_tensorflow_core.h
include/tensor_filter_tensorflow_lite_core.h
include/tensor_typedef.h
nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c
nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c
nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough_variable.c
nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c
nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c

get rid of set the index 0 and make it iteration
Signed-off-by: HyoungjooAhn <hello.ahn@samsung.com>

[Filter] make filter available handling multi tensor - @open sesame 09/04 15:40

---

gst/tensor_filter/tensor_filter.c

As the CI system returns, we got unchecked style error.
Fixes CI style error found with PR #487

[Style Fix] Indentation Error Fix.

---

Documentation/ci-config/config-environment.sh
Documentation/ci-config/config-plugins-audit.sh
Documentation/ci-config/config-plugins-format.sh
Documentation/ci-config/config-webhook.json

This commit is to update the existing configuration files for TAOS-CI because
the files are out-of-date.
1. Added webhook configuration file
2. Updated out-of-date configuration files
3. Updated default variables in the configuration files
---
```bash
subject of the commit and the rest of …
```

[config] Updated the existing configuration files for TAOS-CI

---

gst/tensor_converter/README.md

- Updated the status of converter.
- Added more information for converter.
- Removed unrelated part.
Addressing #490
ps. This does not touch any code. No need for testing the behavior.
ps2. @jaeyun-jung Please review the first part (audio and text) carefully.

[Documentation] Update README.md of converter

---

gst/tensor_split/gsttensorsplit.c
gst/tensor_split/gsttensorsplit.h

Complete TensorSplit Implementation.
- Adding chain function
. Create pad to push downstream
. Create GstMemory and insert into GstBuffer
: Test cases will be added soon.

[TensorSplit] Complete TensorSplit Implementation

---

Documentation/component-description.md
README.md

- Updated the developmental status of each element.
- Updated URLs
- The whole document is revised.
Partially addressing #490.
ps. This is document update. No code test was required.

[Documentation] Update the root README.md - @open sesame 09/06 20:27

---

gst/tensor_filter/README.md

Addressing #490, this adds more information about tensor_filter.
ps. This does not touch the code. No need for testing.

[Documentation] Update README.md entry for tensor_filter

---

gst/tensor_aggregator/README.md
gst/tensor_converter/README.md

1. add readme.md file for tensor-aggregator
2. fix typo in tensor-converter

[Document] update readme.md

---

Documentation/ci-config/config-environment.sh
Documentation/ci-config/config-plugins-audit.sh
Documentation/ci-config/config-plugins-format.sh
Documentation/ci-config/config-server-administrator.sh
Documentation/ci-config/config-webhook.json

This commit is to update the existing configuration files
based on the latest version of TAOS-CI.
1. Added config file for server administrator
2. Updated the existing config files TAOS-CI version 1.0.20180913.

CI: Updated config files based on latest TAOS-CI version - @open sesame 09/13 19:23

---

gst/tensor_decoder/tensordec.c
gst/tensor_decoder/tensordec.h

…decoder
Add function for image labeling data when initialize tensor decoder

[TensorDec] Add initalize function for image labeling data of tensor

---

gst/tensor_filter/tensor_filter.c

The copy-pasted description from converter is incorrect.
Fixes #539
There is no effective code changes.

[Filter/Main] Correct plugin description

---

gst/tensor_decoder/tensordec.c
gst/tensor_decoder/tensordec.h

add set label path property and set label infos in tensor decoder
and with #542

[TensorDec]Add set label path property

---

include/tensor_typedef.h

Define the new structure as a standard unit of data tensor. 
It will be allocated and used to store the tensor data.
Signed-off-by: HyoungjooAhn <hello.ahn@samsung.com>

[Filter] create new structure for multi tensors

---

gst/tensor_filter/tensor_filter.c

Tensor-filter gets fixed tensor info, it does not need intersection in fixate_caps.
1. remove intersect in fixate_caps()
2. use tensor meta in fw-property during caps negotiation
3. add macro to print tensor info

[Filter] fix caps nego failure case

---

nnstreamer_example/example_filter/nnstreamer_example_filter.c

1. add videoscale to set 640x480 video frame
2. use the framerate of webcam

[Example] fix nego failure case - @open sesame 09/19 17:12

---

gst/tensor_transform/tensor_transform.c

unsigned values cannot be <0 checking it whether it's >=0 or not is meaningless
addressing one more item of #558

[Tranform] Fix coverity issue 1029522

---

nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough_variable.c
tests/nnstreamer_filter_custom/runTest.sh
tests/nnstreamer_sink/unittest_sink.cpp

1. change custom passthrough example to support multi tensors
2. add simple stream testcases for multi tensors

[Example/CustomFilter/Test] change custom passthrough filter

---

nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c
nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c

fix unsigned compare issue in custom scaler filter

[Example/CustomFilter] fix coverity issue (1029512, 1029504)

---

gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc

copy data pointer directly rather than the `memcpy` logic at the input tensor
Resolves #572

[Filter/TF-Lite] remove memcpy for input tensor

---

gst/tensor_demux/gsttensordemux.c
gst/tensor_demux/gsttensordemux.h
gst/tensor_split/gsttensorsplit.c
gst/tensor_split/gsttensorsplit.h

1. change the element classification string
2. remove unnecessary header
3. fix typo and duplicated tag

[Demux/Split] update description

---

tests/nnstreamer_decoder/runTest.sh

remove the property silent in tensor decoder testcase.

[Test/Decode] remove debug message

---

gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc

Let's not repeat the same code for switch cases.

[Wait for #577] [Filter/TF-Lite] refactor to reduce repeated code

---

gst/tensor_decoder/tensordec.c
gst/tensor_decoder/tensordec.h

Add functions regarding image labeling
in tensor decoder

[TensorDec] Add functions regarding image labeling in tensor decoder

---

gst/tensor_sink/README.md

Update README.md file for the element tensor-sink.
Related issue: #490

[Document/Sink] update README.md about tensor-sink

---

gst/tensor_mux/gsttensormux.c

Add log message and remove unnecessary state.

[Mux] fix coverity issue (1029508)

---

gst/tensor_demux/gsttensordemux.c

change default property value (set default value true)

[Demux] change default property value

---

common/tensor_common.c
gst/tensor_filter/tensor_filter.c
include/tensor_common.h
nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c
nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough_variable.c
nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c
tests/nnstreamer_tensors/tensors_test/gsttensorscheck.c

add function to get date size with GstTensorInfo
and refactor elements and examples

[Common] add function to get tensor size

---

gst/tensor_decoder/tensordec.c

Implement set out buffer with updated image label text

[tensorDec] Implement copy label string to out buffer

---

gst/tensor_converter/README.md
gst/tensor_sink/tensor_sink.c

change log messages in tensor-sink
add description for properties and signals in tensor-sink
fix property name in tensor-converter doc

[Document/CodeClean] update description and debug messages

---

common/tensor_common.c
include/tensor_common.h
tests/nnstreamer_converter/runTest.sh
tests/nnstreamer_sink/unittest_sink.cpp

includes two commits,
1. add audio format (signed/unsigned 32bit, floating point 32/64bit)
2. update stream testcases

[Common/Test] expand audio format

---

nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c

Do not check if it's < 0 if it's unsigned.

[example/custom] Fix coverity issue.

---

tests/nnstreamer_sink/unittest_sink.cpp

add stream testcase with tensor-split to check out buffers

[Test] add stream tc with tensor-split

---

gst/tensor_decoder/tensordec.c

Coverity issues fix for tensor decoder

[Coverity] fix CID 1030252, CID 1030251 issues

---

common/tensor_common.c

update condition about framerate, denominator should be larger than 0.

[Common] update condition to validate tensor config

---

gst/tensor_aggregator/tensor_aggregator.c
gst/tensor_converter/tensor_converter.c

set timestamp with distance (bytes from pts)
if frames-in is larger than frames-out, it will set same timestamp.
in this case, elements update timestamp with distance.

[Converter/Aggregator] update timestamp

---

common/tensor_common.c
include/tensor_common.h

1. define new type for byte-stream (application/octet-stream)
2. refactor functions to get tensor config
TODO: need to update tensor-converter later

[Common] initial commit to add a type of byte-stream

---

gst/tensor_aggregator/README.md
gst/tensor_aggregator/tensor_aggregator.c
gst/tensor_aggregator/tensor_aggregator.h

update output dimension with the properties frames-dim, frames-out.

[Aggregator] fix out-tensor dimension @open sesame 10/08 22:19

---

gst/tensor_converter/tensor_converter.c

add condition to check frame size (divide by zero)

[Converter] fix coverity issue 1034478

---

tests/nnstreamer_sink/unittest_sink.cpp

1. add tc to change dimension in output tensor (tensor-aggregator)
2. change output dimension for octet-stream (tensor-converter)

[Test] update stream testcase

---

CODE_OF_CONDUCT.md

The COC we are based on appears to be based on postmeritocracy with political intentions.
Before moving on the the official nnsuite CoC, I suggest to use this temporarily updated one.

[CoC Update] Update due to recent turmoil at LKML

---

gst/tensor_aggregator/README.md
gst/tensor_aggregator/tensor_aggregator.c
gst/tensor_aggregator/tensor_aggregator.h

1. add property concat (default true, to do the concatenation)
2. add functions to check dimension before pushing the buffer into source pad
TODO : update concat code with the axis

[Aggregator] update code to concatenate output

---

gst/tensor_aggregator/tensor_aggregator.c

update data concatenation for the axis (frames-dim)

[Aggregator] update code to concatenate data with axis

---

gst/tensor_decoder/tensordec.c

Update tensor decoder for proper working
set caps and some minor updates

[TensorDec] update tensor decoder for proper working

---

gst/tensor_sink/tensor_sink.c

add function prefix to prepare single bin

[Sink] code clean

---

common/getTestModels.sh

For the demonstration, provide a shell script that gets
the standard example tflite model and its labeling file

[Utility] For demo, create a shell script loading model/label

---

gst/tensor_merge/gsttensormerge.c
gst/tensor_merge/gsttensormerge.h
gst/tensor_mux/gsttensormux.c
gst/tensor_mux/gsttensormux.h

1. remove unnecessary value in pad-data structure
2. add cond to check valid buffer

[Mux/Merge] remove unnecessary value

---

gst/tensor_aggregator/tensor_aggregator.c

add condition to check flush-size (when sets large value to flush the data)

[Aggregator] add condition to flush the bytes

---

.TAOS-CI/taos/auto-unittest.sh
.TAOS-CI/taos/menu.html

archive unit test result using crontab, you can see it on'nnsuite.mooo.com'

[unittest] Archive unit test result

---

gst/tensor_decoder/tensordec.c
gst/tensor_decoder/tensordec.h

change mode type from const char to uint
and add bounding boxes mode
push origin <your_branch_name>
```

[TensorDec] update mode with bounding boxes

---

gst/tensor_filter/tensor_filter.c

when called transform-caps, try to get tensor info from NN model.
if tensor-filter cannot parse the tensor info from in-caps, it will return pad template caps.

[Filter] get out-caps info from NN model

---

gst/nnstreamer/tensor_common.c

To fix coverity issue, block some lines (logical dead code now)

[Common] fix coverity issue 1035367

---

nnstreamer_example/example_cam/nnstreamer_example_cam.c
nnstreamer_example/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c
nnstreamer_example/example_filter/nnstreamer_example_filter.c
nnstreamer_example/example_filter/nnstreamer_example_filter.py
nnstreamer_example/example_object_detection/nnstreamer_example_object_detection.cc
nnstreamer_example/example_sink/nnstreamer_sink_example.c
nnstreamer_example/example_sink/nnstreamer_sink_example_play.c

Set default debug flag to false. The examples will not print messages.

[Test] change the flag to print logs

---

nnstreamer_example/tizen_app_build_example/CMakeLists.txt
packaging/nnstreamer_testapp.spec

add requirement gst-audio to build test apps

[Test] update pkg requirement

---

gst/tensor_decoder/tensordec.c

refactory transform function
from property out-type to property mode
1. Build test: [*]Passed [ ]Failed [*]Skipped
2. Run test: [*]Passed [ ]Failed [* ]Skipped

[TensorDec] refactoring transform function with property

---

gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc

remove `memcpy` by changing tflite input/output property dynamic.
it resolves #536 

[Filter/TFLite] remove memcpy after invoke

---

gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc

get the length of a vector before the iteration.

[Filter/TFLite] make better the inefficient code

---

gst/tensor_filter/tensor_filter.c
gst/tensor_filter/tensor_filter.h
include/tensor_typedef.h

refactor code to remove dependancy of nnfw callbacks

[Filter] remove nnfw callbacks from nnfw property structure

---

gst/tensor_merge/gsttensormerge.c
gst/tensor_merge/gsttensormerge.h

Add synch option to synchronize input tensors;
Default synch option is true. If it is false, it does not care about
time synchronization and merge without time synchronization.

[TensorMerge] Add Time Synchronization Option  

---

tests/nnstreamer_converter/generateGoldenTestResult.py
tests/nnstreamer_merge/runTest.sh

Add test case for time synchronization
1. test case 0 : sink_0 (30FPS), sink_1 (10FPS)
2. test case 1 : sink_0 (30FPS), sink_1 (20FPS)
3. test case 2 : sink_0 (30FPS), sink_1 (20FPS), sink_2 (10FPS)

[TensorMerge] Add Test case for time synchronization 

---

packaging/nnstreamer.spec

Set a time limit(10min) to prevent './testAll' from getting longer while gbs build.
---
```bash
Further …
```

[TEST] To manage gbs build time, add time limit to './testAll' @open sesame 11/02 14:59

---

packaging/nnstreamer.spec

Now, sleep 1 and minus value is 60. so timeout was 10 seconds.
fix that using interval value.
---
```bash …
```

[TEST] fix timeout error

---

gst/tensor_decoder/tensordec.c
gst/tensor_decoder/tensordec.h

add initial functions of tensor decoder bounding boxes

[TensorDec] add init functions of bounding boxes mode @open sesame 11/02 17:59

---

gst/tensor_decoder/tensordec.h

Somehow recent fix got away from CI. Strange.

[Emergency Fix] Build Error Fix / tensor-dec @open sesame 11/05 11:14

---

tests/nnstreamer_decoder/runTest.sh
tests/nnstreamer_decoder_image_labeling/runTest.sh
tests/nnstreamer_filter_custom/runTest.sh
tests/nnstreamer_merge/runTest.sh
tests/nnstreamer_mux/runTest.sh

During the recent CI failure, broken testcases (obsolete cases)
were mixed up.

[Emergency Fix] Build Error Fix / Testcases Broken (old commit mixed)

---

tests/transform_transpose/generateTest.py
tests/transform_transpose/runTest.sh

Add three transpose test cases
1. Tensor 100:50:3:1  --> Tensor 3:100:50:1
2. Tensor 200:100:3:1  --> Tensor 3:200:100:1
3. Tensor 200:100:3:1  --> Tensor 100:200:3:1

[Transform] Add testcases for transpose

---

gst/tensor_filter/tensor_filter.c

add code to free memory if allocate-invoke is true.
Related issue : #757

[Filter] free memory when allocate-invoke is true

---

tools/README.md

This commit is to append case study of GstShark tool.
1. Fixed incorrect autogen.sh statement to generate Makefile
2. Added Case study (processing time)
---

[Tools] Added case study of GstShark

---

debian/control
tests/CMakeLists.txt

use ssat instead of testAll.sh
---
```bash
**Changes proposed in …
```

[TEST] change unit test logic in pdebuild @open sesame 11/06 17:24

---

packaging/nnstreamer.spec

To remove overhead, change the logic
resolves: #776 
---
```bash …
```

[TEST] Change time out logic @open sesame 11/07 15:36

---

gst/tensor_transform/tensor_transform.c
gst/tensor_transform/tensor_transform.h

change code to use common structure for in/out tensor info

[Transform] refactor with common tensor info 

---

CMakeLists.txt
gst/nnstreamer/tensor_common.h
gst/tensor_mux/gsttensormux.c
nnstreamer_example/CMakeLists.txt
packaging/nnstreamer.spec
tests/CMakeLists.txt

delete dlog and tizen definition.
related issue : #807
TODO : determine log level defined in common header

[Cmake] delete dlog

---

tests/nnstreamer_sink/unittest_sink.cpp

Adding more cases for mux/merge sync policy testing of #739
ps. Testcases are growing too fast with redundant code. We might want to refactor them pretty soon (1812 or 1901?)

[Test] Add mux/merge sync unit tc for #739

---

gst/nnstreamer/tensor_common.c

For the basepad mode with options with 0 or maximum duration, current
implementation is not working properly. In order to support this
situation, base time is decided min(duration, pts(nth)-pts(n-1 th)-1).

[Mux/Merge] Fix time synchronization bug for cornner cases

---

gst/tensor_decoder/tensordec.c

Critical typo fixed. Option2 --> Option1

[Decoder] trivial fix on option property init.

---

Documentation/getting-started.md

write how to install and build with meson.
---
```bash
**Changes …
```

[DOC] write how to build with meson

---

tests/nnstreamer_converter/generateGoldenTestResult.py
tests/nnstreamer_merge/runTest.sh
tests/nnstreamer_mux/runTest.sh

Added test cases for basepad mode with "option=0" and "option=0:0"

[Merge/Mux] Add test cases for conner cases @open sesame 11/14 15:58

---

tests/nnstreamer_sink/unittest_sink.cpp

Add logs if failed to remove temp file for unit-test.
(These changes are to resolve coverity issues)

[Test] print log if failed to remove temp file

---

gst/tensor_filter/tensor_filter_tensorflow_lite.c
gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc
gst/tensor_filter/tensor_filter_tensorflow_lite_core.h

fix NULL ptr error by adding initialize function
it resolves #826 

[Filter/TFLite] fix bug

---

gst/tensor_filter/tensor_filter_tensorflow_lite.c
gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc
gst/tensor_filter/tensor_filter_tensorflow_lite_core.h

User open `tflite` model when a model is already loaded, compare it with the previous one and if it is different, make the object the new one with a new model.

[Filter/TFLite] support dynamic model

---

gst/nnstreamer/meson.build
gst/tensor_aggregator/meson.build
gst/tensor_converter/meson.build
gst/tensor_decoder/meson.build
gst/tensor_demux/meson.build
gst/tensor_filter/meson.build
gst/tensor_merge/meson.build
gst/tensor_mux/meson.build
gst/tensor_saveload/meson.build
gst/tensor_sink/meson.build
gst/tensor_split/meson.build
gst/tensor_transform/meson.build
meson.build

Initial commit of meson. This commit's goal is to make single binary.
---
```bash
Further paragraphs come …
```

[Meson] Initial commit of meson build

---

gst/tensor_aggregator/tensor_aggregator.c
gst/tensor_sink/tensor_sink.c

Use gst macros to print debug logs

[Sink] update log format

---

nnstreamer_example/example_object_detection/gst-launch-object-detection.sh
nnstreamer_example/example_object_detection/nnstreamer_example_object_detection.cc

update arith mode in tensor-transform to normalize

[Example] update arithmetic for normalization

---

gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_common.h
gst/tensor_converter/tensor_converter.c
gst/tensor_decoder/tensordec.c
gst/tensor_filter/tensor_filter.c
gst/tensor_filter/tensor_filter_custom.c
gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc
gst/tensor_merge/gsttensormerge.c
gst/tensor_mux/gsttensormux.c
gst/tensor_transform/tensor_transform.c
tests/nnstreamer_tensors/tensors_test/gsttensorscheck.c

1. Use common gst macros to print debug logs.
2. Remove debug macros in common header. (debug_print and err_print)

Change log format @open sesame 11/23 11:55 

---

gst/nnstreamer/tensor_common.h

We will be using typefind soon along with tensor_save/load.

Trivial Typo Fix

---

.TAOS-CI/taos/config/config-environment.sh
.TAOS-CI/taos/config/config-plugins-audit.sh
.TAOS-CI/taos/config/config-plugins-format.sh
.TAOS-CI/taos/config/config-server-administrator.sh
.TAOS-CI/taos/config/config-webhook.json
.TAOS-CI/taos/menu.html

For ci server, update config files.
---
```bash
**Changes …
```

[CI] update config files.

---

gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc
gst/tensor_filter/tensor_filter_tensorflow_lite_core.h

move unused method to private and remove extern methods
Signed-off-by: HyoungjooAhn <hello.ahn@samsung.com>

[Filter/TFLite] code clean

---

CMakeLists.txt
nnstreamer_example/example_object_detection/CMakeLists.txt
packaging/nnstreamer.spec

Let the user download the model at run-time with the given scripts.
They will be able to do so after #909
With #909, this concludes #866

[CMake] Do not download anything during build.

---

CMakeLists.txt
gst/nnstreamer/nnstreamer_conf.c
gst/nnstreamer/nnstreamer_conf.h

We are going to allow users to configure paths of
filters, decoders, and custom filters.
This is the API skeletons for the first step of #804

[Common/Conf] API to get conf values.

---

tests/nnstreamer_converter/generateGoldenTestResult.py
tests/nnstreamer_repo/runTest.sh

3 test cases are added.
- ID 0 : 10 stream --> tensor_reposink --> (Repo) --> tensor_reposrc
- ID 0 : 10 stream --> tensor_reposink --> (Repo) --> tensor_reposrc
ID 1 : 10 stream --> tensor_reposink --> (Repo) --> tensor_reposrc
- ID 0 : 10 stream --> tensor_reposink --> (Repo) --> tensor_reposrc
ID 1 : 10 stream --> tensor_reposink --> (Repo) --> tensor_reposrc
ID 2 : 10 stream --> tensor_reposink --> (Repo) --> tensor_reposrc

[Repo] Add testcases for tensor_reposink/tesnor_reposrc @open sesame 11/28 13:28

---

gst/nnstreamer/tensor_repo.c
gst/nnstreamer/tensor_repo.h

In order to keep the synchronization better, two cond variable is
used.

[Repo] Split Cond variable to use push and pull the data @open sesame 11/30 13:37

---

gst/tensor_decoder/meson.build
gst/tensor_filter/meson.build
meson.build
meson_options.txt
nnstreamer_example/custom_example_LSTM/meson.build
nnstreamer_example/custom_example_RNN/meson.build
nnstreamer_example/custom_example_average/meson.build
nnstreamer_example/custom_example_opencv/meson.build
nnstreamer_example/custom_example_passthrough/meson.build
nnstreamer_example/custom_example_scaler/meson.build
nnstreamer_example/example_cam/meson.build
nnstreamer_example/example_decoder_image_labelling/meson.build
nnstreamer_example/example_filter/meson.build
nnstreamer_example/example_filter_performance_profile/meson.build
nnstreamer_example/example_object_detection/meson.build
nnstreamer_example/example_sink/meson.build
nnstreamer_example/meson.build
tests/meson.build
tests/nnstreamer_tensors/tensors_test/meson.build

For ssat and example, add meson.build

[meson] add meson.build for example apps and custom filter - @open sesame 11/30 13:07

---

gst/tensor_transform/tensor_transform.c
tests/nnstreamer_plugins/unittest_plugins.cpp

set typecast option only in the first

[Transform] limit typecast in arith mode

---

gst/tensor_transform/transform-orc.orc
tests/nnstreamer_plugins/unittest_plugins.cpp

1. add functions for operator add/mul
2. add functional testcases for orc
TODO :
1. support int64
2. add typecast functions

[Orc] update function for operator add/mul

---

nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c

[Bug Fix] fix unused variables bug - @open sesame 12/04 20:34

---

gst/tensor_transform/transform-orc.orc
tests/nnstreamer_plugins/unittest_plugins.cpp

1. add typecast functions
2. add testcases for typecast

[Orc] add functions for typecast

---

gst/nnstreamer/meson.build
gst/tensor_aggregator/meson.build
gst/tensor_converter/meson.build
gst/tensor_decoder/meson.build
gst/tensor_demux/meson.build
gst/tensor_filter/meson.build
gst/tensor_merge/meson.build
gst/tensor_mux/meson.build
gst/tensor_reposink/meson.build
gst/tensor_reposrc/meson.build
gst/tensor_saveload/meson.build
gst/tensor_sink/meson.build
gst/tensor_split/meson.build
gst/tensor_transform/meson.build
meson.build

1. set base-args and include orc features
2. check orc lib and orcc, and generate orc files in tensor-transform

[Meson] include orc

---

debian/control
debian/nnstreamer.install
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_typedef.h
gst/tensor_filter/CMakeLists.txt
gst/tensor_filter/meson.build
gst/tensor_filter/tensor_filter.c
gst/tensor_filter/tensor_filter_tensorflow.c
gst/tensor_filter/tensor_filter_tensorflow_core.cc
gst/tensor_filter/tensor_filter_tensorflow_core.h
meson_options.txt
packaging/nnstreamer.spec
packaging/nnstreamer_testapp.spec

this is a draft of tensorflow filter
it resolves #121 

[Filter/Tensorflow] upload tensorflow draft

---

gst/nnstreamer/nnstreamer.c
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_common.h
gst/tensor_converter/tensor_converter.c

1. move function video-stride to converter.
2. move mainpage tag to nnstreamer.c.
3. in nnstreamer.c, include config header for orc feature.

[Converter] code clean

---

gst/nnstreamer/meson.build
gst/tensor_aggregator/meson.build
gst/tensor_converter/meson.build
gst/tensor_decoder/meson.build
gst/tensor_demux/meson.build
gst/tensor_filter/meson.build
gst/tensor_merge/meson.build
gst/tensor_mux/meson.build
gst/tensor_reposink/meson.build
gst/tensor_reposrc/meson.build
gst/tensor_saveload/meson.build
gst/tensor_sink/meson.build
gst/tensor_split/meson.build
gst/tensor_transform/meson.build
meson.build
nnstreamer_example/custom_example_LSTM/meson.build
nnstreamer_example/custom_example_RNN/meson.build
nnstreamer_example/custom_example_average/meson.build
nnstreamer_example/custom_example_opencv/meson.build
nnstreamer_example/custom_example_passthrough/meson.build
nnstreamer_example/custom_example_scaler/meson.build
nnstreamer_example/example_cam/meson.build
nnstreamer_example/example_decoder_image_labelling/meson.build
nnstreamer_example/example_filter/meson.build
nnstreamer_example/example_filter_performance_profile/meson.build
nnstreamer_example/example_object_detection/meson.build
nnstreamer_example/example_sink/meson.build
nnstreamer_example/meson.build
tests/meson.build
tests/nnstreamer_tensors/tensors_test/meson.build

1. rename dependencies of gstreamer, glib (follows gst-base)
2. rename nnstreamer include path and dependencies
3. add unittest (command '$ ninja test' will build and start gtest)

[Meson] add unittest and code clean

---

gst/tensor_filter/meson.build
gst/tensor_filter/tensor_filter_tensorflow_core.cc
nnstreamer_example/custom_example_LSTM/meson.build
nnstreamer_example/custom_example_RNN/meson.build
nnstreamer_example/custom_example_average/meson.build
nnstreamer_example/custom_example_opencv/meson.build
nnstreamer_example/custom_example_passthrough/meson.build
nnstreamer_example/custom_example_scaler/meson.build

1. check dependency of protobuf, tensorflow
2. fix indentation and build warning

[Filter/TF] fix warning and check dependency @open sesame 12/10 15:00

---

gst/tensor_filter/tensor_filter.c

check the existence of the value before free for input/output name properties

[Filter] add a condition to check properties: input/output name - @open sesame 12/11 13:54

---

tests/nnstreamer_converter/runTest.sh
tests/nnstreamer_decoder/runTest.sh
tests/nnstreamer_decoder_image_labeling/runTest.sh
tests/nnstreamer_demux/runTest.sh
tests/nnstreamer_filter_custom/runTest.sh
tests/nnstreamer_filter_tensorflow_lite/runTest.sh
tests/nnstreamer_merge/runTest.sh
tests/nnstreamer_mux/runTest.sh
tests/nnstreamer_repo/runTest.sh
tests/nnstreamer_split/runTest.sh
tests/nnstreamer_tensors/runTest.sh
tests/transform_arithmetic/runTest.sh
tests/transform_dimchg/runTest.sh
tests/transform_stand/runTest.sh
tests/transform_transpose/runTest.sh
tests/transform_typecast/runTest.sh

set plugin path for the unittest using nnstreamer elements.

[Test] add plugin path - @open sesame 12/12 17:12

---

gst/tensor_filter/tensor_filter_tensorflow_core.cc

logic is fixed to make it work properly for any type of input dimension

[bugfix] fix checking the dimension of input tensor

---

gst/nnstreamer/meson.build
gst/tensor_aggregator/meson.build
gst/tensor_converter/meson.build
gst/tensor_decoder/meson.build
gst/tensor_demux/meson.build
gst/tensor_filter/meson.build
gst/tensor_merge/meson.build
gst/tensor_mux/meson.build
gst/tensor_reposink/meson.build
gst/tensor_reposrc/meson.build
gst/tensor_saveload/meson.build
gst/tensor_sink/meson.build
gst/tensor_split/meson.build
gst/tensor_transform/meson.build
meson.build
meson_options.txt
nnstreamer_example/custom_example_LSTM/meson.build
nnstreamer_example/custom_example_RNN/meson.build
nnstreamer_example/custom_example_average/meson.build
nnstreamer_example/custom_example_opencv/meson.build
nnstreamer_example/custom_example_passthrough/meson.build
nnstreamer_example/custom_example_scaler/meson.build
nnstreamer_example/example_cam/meson.build
nnstreamer_example/example_decoder_image_labelling/meson.build
nnstreamer_example/example_filter/meson.build
nnstreamer_example/example_filter_performance_profile/meson.build
nnstreamer_example/example_object_detection/meson.build
nnstreamer_example/example_sink/meson.build
tests/meson.build
tests/nnstreamer_tensors/tensors_test/meson.build

1. add flags for tensorflow and tensorflow-lite
2. set objs with the flags and dependency of libraries
3. set proper dependencies for each examples
4. make bmp2png for the unittest
5. add installation

[Meson] update script

---

gst/tensor_filter/tensor_filter_tensorflow_core.cc
gst/tensor_filter/tensor_filter_tensorflow_core.h

to run model, hold the original rank internally

[Filter/Tensorflow] take the original rank of model internally

---

gst/tensor_filter/tensor_filter_tensorflow_core.cc
gst/tensor_filter/tensor_filter_tensorflow_core.h
gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc

To fix coverity issue, init variables and code clean.

[Filter/TF] fix warning

---

gst/tensor_filter/tensor_filter_tensorflow_core.cc

checking the status of tensorflow after running model

[Filter/Tensorflow] add an exception case for tensorflow

---

gst/tensor_filter/CMakeLists.txt

set pkgs for tensorflow and link with necessary modules

[Filter/Cmake] link proper modules

---

meson.build
tests/meson.build
tests/nnstreamer_tensors/tensors_test/meson.build

declare nnstreamer-lib dependency with include directory

[Meson] set dependency with include dir

---

meson.build
packaging/nnstreamer.spec

update .spec to build using meson

[Meson] gbs build using meson - @open sesame 12/19 21:38

---

.github/CODEOWNERS
README.md

The two reviewers have left the team.

Reviewer List Updated @open sesame 1/14 11:16

---

gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc

fix broken logic at input tensor.

[Filter/Tensorflow] fix bug at input tensor

---

gst/nnstreamer/meson.build
gst/nnstreamer/tensor_transform/meson.build

Add dependency for generated files.

[Meson] add dependency for generated files @open sesame 1/16 14:53

---

Documentation/getting-started.md
README.md

modify the guide about meson and ppa address

[Documentation] update the getting-started document

---

gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter.h
gst/nnstreamer/tensor_filter/tensor_filter_custom.c
gst/nnstreamer/tensor_filter_custom.h
gst/nnstreamer/tensor_typedef.h

FW definition is now unnecessary.
1. remove fw defines
2. update custom filter description

[Filter] remove definition of supported framework

---

gst/nnstreamer/meson.build
gst/nnstreamer/tensor_filter/meson.build
meson.build

change dependency for thread (guide in meson-build https://mesonbuild.com/howtox.html)

[Meson] change dependency for thread @open sesame 1/21 10:08

---

tests/nnstreamer_repo/runTest.sh

In order to check negotiation error, added test cases for repo.
- Added Test cases for repo
Resolves: #1026

[Repo] Add test cases for negotiation check

---

Documentation/coding-convention.md
Documentation/component-description.md
Documentation/how-to-use-testcases.md

update broken links and nnstreamer changes

[Document] update documents

---

gst/nnstreamer/tensor_decoder/tensordec-boundingbox.c

some parameters subordinated to the ssd model of TFLite should have their own name.
the main reason is the duplication of some parameters' name with the tensorflow ssd model.

[Decoder/BoundingBox] rename parameters just for tf-lite

---

Documentation/getting-started.md

Cleaning up the documentation, following up 3065d38fb8c56064ab695a8d46b2f9dbd3e1aad7

[Doc] Update getting started.

---

README.md

Build/Text status and Test code coverage will be
available after https://github.com/nnsuite/TAOS-CI/issues/452
is resolved.

[Doc] Add regular release status

---

gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc
gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h
gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h

adjust the style and remove useless keywords.

[Filter/NNFW] clean code of tensorflow & tf-lite

---

CHANGES
debian/changelog
packaging/nnstreamer.spec

This is the start of 0.1.1 development.

Start of 0.1.1 Release Candidate Development

---

gst/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc

add the error messages when errors have occurred

[Filter/NNFW] add error message for user&debugging

---

debian/control
debian/rules

protobuf packaging done, enable tensorflow option.

[Build/Deb] enable tensorflow

---

.github/CODEOWNERS

And, we do not need special reviewers for packaging any more.

[Codeowner] Add kparichay to default reviewers

---

debian/nnstreamer.install
debian/rules
meson.build
nnstreamer.ini
packaging/nnstreamer.spec

Users can configure the locations of decoder/filter subplugins.

[DIST] Install /etc/nnstreamer.ini

---

meson.build
nnstreamer.ini
nnstreamer.ini.in
nnstreamer_example/custom_example_LSTM/meson.build
nnstreamer_example/custom_example_RNN/meson.build
nnstreamer_example/custom_example_average/meson.build
nnstreamer_example/custom_example_opencv/meson.build
nnstreamer_example/custom_example_passthrough/meson.build
nnstreamer_example/custom_example_scaler/meson.build
packaging/nnstreamer.spec

1. add config to set sub-plugins install prefix
2. change  custom-filter examples install path

[Meson] configuration to install ini

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h
gst/nnstreamer/meson.build
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter_custom.c
gst/nnstreamer/tensor_typedef.h
meson.build
packaging/nnstreamer.spec

fix typo and clean up build script,
1. remove unnecessary variable and dependency.
2. set common path and dependencies, clean up meson script.

[Build/Filter] code clean

---

gst/nnstreamer/tensor_decoder/tensordec-boundingbox.c
gst/nnstreamer/tensor_decoder/tensordec-directvideo.c
gst/nnstreamer/tensor_decoder/tensordec-imagelabel.c
gst/nnstreamer/tensor_decoder/tensordec.c
gst/nnstreamer/tensor_decoder/tensordec.h

The interface between tensor-decoder::main and tensor-decoder::*
should not include internal tensor-decoder data structure.
Communicate with Gstreamer native or exported data structure only.
For third-party / user-contents developers, detach
glib dependencies as well.
Wait for  #1090 #1091 #1098

[Decoder] refactor subplugin structure for /ext preparation

---

gst/nnstreamer/tensor_filter/tensor_filter.c

add warning message if properties and model info are different

[Filter] print message when caps-nego failed

---

gst/nnstreamer/nnstreamer_plugin_api.c
gst/nnstreamer/nnstreamer_plugin_api.h
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_common.h
tests/common/unittest_common.cpp

1. add new function _info_free() to free allocated data in tensor-info structure
2. move functions to plugin api header
3. fix return type in common functions and code clean
TODO:
I will add new PR to use common functions to set/get tensor info in tensor_filter tf sub-plugins.

[Common] add new function and code clean

---

gst/nnstreamer/tensor_decoder/tensordec.c
gst/nnstreamer/tensor_decoder/tensordec.h

remove unused code and fix log type

[Decoder] remove unused

---

gst/nnstreamer/tensor_converter/tensor_converter.c

ci report - indent error in tensor-converter

[Build] fix indent error @open sesame 2/15 13:48

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h

1. set in/out tensor info while loading and verifying tf model
2. copy raw data into tensor instead loop and remove macros to set tensor data

[Filter/TF] refactor to init tf model

---

gst/nnstreamer/tensor_repo.c

This commit is to update the existing annotation on EOS in order to
generate understanding statements with Doxygen.
---

[tensor_repo] Doxygen: Updated annotation on EOS

---

tests/nnstreamer_split/runTest.sh

Tensorpick feature is not tested in unittest.
Add a corresponding test case.

[Unittest/Split] Test tensorpick property

---

tests/nnstreamer_decoder/runTest.sh

To cover more code measured by lcov, add test cases for exceptions

[Test/Decoder] Add unit test cases of errors

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c

Signed-off-by: Aaron Boxer <aaron.boxer@collabora.com>

[Filter] handle TF framework open return value

---

debian/control
debian/nnstreamer-tensorflow-lite.install
debian/nnstreamer-tensorflow.install
debian/nnstreamer.install
packaging/nnstreamer.spec

This concludes the EPIC item of #786.

[Dist] Separate filter subplugin subpackages

---

README.md

- Update reviewer list
- Add more external materials of nnstreamer
- Updated introduction

[README] update README

---

tests/nnstreamer_sink/unittest_sink.cpp

Add more unit test cases to boost the lcov coverage data of decoder and split.
This requires #1168 merged to pass all the test cases.
(Bug of #1168 is found by this unit test cases)

[Unittest] GetProperty of decoder/split

---

gst/nnstreamer/meson.build
gst/nnstreamer/tensor_source/meson.build
gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h

Added empty template for tensor source plugin for linux IIO
Properties for IIO devices have been added, but not yet finalized

[Src] Template for tensor source

---

tests/unittestcoverage.py

fix index error in ut-coverage

[Test] fix index error

---

debian/rules
meson.build
packaging/nnstreamer.spec

add werror in project default options

[Meson] add default werror option

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc

when the model file is not valid or not existed,
system generates the proper error messages without any options.

[Filter] add proper error messages

---

ext/meson.build
ext/nnstreamer/meson.build
ext/nnstreamer/tensor_decoder/meson.build
ext/nnstreamer/tensor_filter/meson.build
gst/nnstreamer/tensor_decoder/meson.build
meson.build

add current dir path and clean up meson script.
This will make to get the unittest coverage for ext sub-plugins.

[Meson] fix file paths

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h

1. Updated properties for IIO src plugin
2. Added get and set property functions
implementing for #1199

[IIO] Add properties for IIO

---

tests/nnstreamer_plugins/unittest_plugins.cpp

add new testcases for aggregator properties and same in/out frames

[Test/Aggregator] testcase for same in/out frames

---

tizen-api/LICENSE.Apache-2.0
tizen-api/capi-nnstreamer.pc.in
tizen-api/doc/nnstreamer_doc.h

This is a draft for Tizen 5.5 NNStreamer Public API.

[Tizen] Native API Draft: Documentation

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h

clear unused tensorflow header files

[Filter/Tensorflow] remove unused header files

---

README.md

We now have Android-NDK build support. Apply the change along with a typofix.

Update README: release status & typo correction

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h

1. Add reading device and its properties
2. Get device ready to data capture, start function (null->ready state)
Helper functions to read files and directories, parse strings are also added
implementing for #1199 

[IIO]Tensor src iio start stop functions

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h

Handling scheduling query and remaining queries handled with basesrc class
All events are handled by basesrc class

[IIO] Handling queries for tensor src IIO

---

tools/development/nnstreamerCodeGenCustomFilter.py

add lines to set name in tensot-info structure

[CodeGen] add tensor name @open sesame 03/12 11:12

---

gst/nnstreamer/tensor_source/tensor_src_iio.c

Added _get_times() to support syncing of buffer for the live source
_get_times() purpose: Given a buffer, return the start and stop time when it should be pushed out. The base class will sync on the clock using these times.

[IIO] added _get_times

---

jni/README.md

This commit is trivial. However, the existing statements have to be updated
to give developers a correct instruction. After updating *.mk file, The binary
path is also changed from ../ to ./ folder.
---

Android/ARM64: Updated binary path

---

tizen-api/include/tizen-api-private.h
tizen-api/include/tizen-api.h

The prototypes of TIZEN-ML-NNSTREAMER-PIPELINE (Main API set of NNStremaer-Tizen) are defined.

[Tizen] Native API Draft: Main API Prototype

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h

1. Enabling buffers in _start
2. Setting channels data location in buffers
3. Storing only filtered channels
Added some bugfixes and fixes to comments

[IIO] enable buffers

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h

1. Finding caps from data configs based on the device channels
2. Fixating the caps for the pad
3. Filling _set and _get for caps
4. Added feature to merge channels data into 1 tensor

[IIO] setting caps and data configs

---

tests/nnstreamer_decoder_image_labeling/runTest.sh

Related issue: #1153
This patch adds more test cases for checking that the 'image labeling' sub plug-in of tensor_decoder properly works with various data types.
- Before this PR: 
| Filename  | Line Coverage  | Functions |
| ------------- |:--------------------:| --------------:|
| tensordec-imagelabel.c | 69.1% (76/110)  | 77.8% (7/9) |
- After this PR: 
| Filename  | Line Coverage  | Functions |
| ------------- |:--------------------:| --------------:|
| tensordec-imagelabel.c | 87.3% (96/110)  | 88.9% (8/9) |

[Test/Decoder/ImageLabeling] Add test cases for various data types

---

.github/CODEOWNERS
README.md

https://github.com/dongju-chae has just joined the group.

Welcome new member: Dongju Chae

---

gst/nnstreamer/nnstreamer_conf.c

- nnsconf_load(FALSE) do not process if it's loaded. We do not need to check it before calling it.
- Do not repeat parsing the configuration string (Raw values). Cache it and read the cached values.
- Processing raw values should be completed in nnsconf_load() for caching.

[Conf] Code Clean

---

.TAOS-CI/taos/config/config-plugins-format.sh
Documentation/contributing.md
gst/nnstreamer/nnstreamer_plugin_api.h
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_converter/README.md
gst/nnstreamer/tensor_filter/tensor_filter.c
tizen-api/include/tizen-api.h

- 'upto' --> 'up to'
- 'there is' --> 'there are'
This commit is for testing my submission environment.

[Typo] Updated the misspelt words @open sesame 3/19 16:55

---

packaging/nnstreamer.spec

[Build] requirement for orc lib

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h

1. Read the data from IIO device
2. Process the raw data
3. Fill the buffer with processed data

[IIO] scan data and fill buffer

---

gst/nnstreamer/tensor_source/tensor_src_iio.c

Create the buffer, allocate memory for the buffer
Enable setting the timestamp for the buffer by base src
Ignore timestamp channel for now - added in todo

[IIO] _create() creates the buffer

---

gst/nnstreamer/tensor_reposink/tensor_reposink.h
gst/nnstreamer/tensor_reposrc/tensor_reposrc.h

change incorrect header definition

[Build] build warning

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h

relocate headers at proper position and remove useless headers

[Filter/TFLite] refine the headers

---

tizen-api/include/tizen-api-private.h
tizen-api/include/tizen-api.h
tizen-api/src/tizen-api-pipeline.c

Tizen-API implementation to handle
- tensor_sink
- app_src
- input_selector
- output_selector
- valve
Unit test cases and code clean/compaction commit will follow soon.
ps. API prototype has been updated due to findings from implementations.

[Tizen/API] Implement src/sink/switch/valve handlers

---

tizen-api/src/tizen-api-pipeline.c

> [Tizen/API] Use macro to shorten common codes.
Use macro for init/exit routines that are same in many functions.
> [Tizen/API] Code clean: use macro for dlog tag name
Use DLOG_TAG instead of "nnstreamer-capi-pipeline".

[Tizen/API] Code Clean

---

debian/rules
gst/nnstreamer/nnstreamer.c
gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h
jni/Android-nnstreamer.mk
packaging/nnstreamer.spec
tests/meson.build
tests/nnstreamer_source/unittest_src_iio.cpp

1. Register plugin as a nnstreamer plugin and initialize it
2. Add test case for setting/getting properties of tensor src iio
3. Bug fixes for the bugs found with the tests
1. Build test: [X ]Passed [ ]Failed [*]Skipped
2. Run test: [ X]Passed [ ]Failed [* ]Skipped

[IIO] register iio source and add test cases

---

tests/nnstreamer_merge/generateTest.py
tests/nnstreamer_repo_lstm/generateTestCase.py
tests/transform_stand/generateTest.py

Some of test cases is not appropriate for python3. In this PR, these
are fixed. (wirte binary data in to string file write option)

[UNITTESTS] Fix binary write

---

gst/nnstreamer/nnstreamer_conf.c
gst/nnstreamer/nnstreamer_conf.h
tests/common/unittest_common.cpp

Added a few test cases for custom conf.

[Wait #1273] Test Cases for Custom Conf. 

---

gst/nnstreamer/tensor_source/tensor_src_iio.c

1. Removed blocksize (merging multiple buffers of data together). Use tensor_aggregator for this functionality
2. Merging of tensors is done with innermost dimension (merging on outermost dimension introduced reduntant dimensions)
3. Bugfix:
- buffer size scaled by buffer_capacity
- data rate_d set to buffer_capacity
4. Moved one-shot mode todo - no support for one-shot mode now
**Related Issue**
#1199 

[IIO] removed blocksize, merging with inner dimension @open sesame 2/4 11:17

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
tests/nnstreamer_source/unittest_src_iio.cpp

1. Support device/trigger number as input, added corresponding test case as well
2. Set proper max limit on buffer capacity and frequency
3. Filled _finalize()

[IIO] Support device number, filled _finalize() @open sesame 4/2 15:17

---

gst/nnstreamer/tensor_source/tensor_src_iio.c

This fixes array out of bound access found by the three incidents.

[Coverity 1050274,1050277][SVACE/414964] Array out of bound

---

tests/meson.build

Add installation of ssat unittest cases according to install-test
option.

[Unittest] add install unittest

---

gst/nnstreamer/tensor_source/tensor_src_iio.c

This fixes branch past initialization (transfer of control bypasses initialization) at two incidents

[Coverity 1050026,1049988] Branch Past Initialization

---

gst/nnstreamer/tensor_filter/tensor_filter.c
tests/nnstreamer_filter_tensorflow_lite/runTest.sh

1. remove assertion while loading model info and doing caps negotiation
2. add testcases for invalid tensor properties

[Filter] remove assertion and add fail testcases

---

tests/common/unittest_common.cpp
tests/nnstreamer_sink/unittest_sink.cpp

add testcase to get tensor-filter properties

[Test] add testcase for filter-properties

---

gst/nnstreamer/tensor_split/gsttensorsplit.c
tests/nnstreamer_sink/unittest_sink.cpp

check return result of mem map

[Test] fix coverity 1050278, 1035696 - @open sesame 04/04 12:58

---

tests/nnstreamer_source/unittest_src_iio.cpp

This solves the unchecked return value issue in destory_dev_dir():
Value returned from a library is not checked for error before being used.
remove/rmdir will return with failure if the file/dir does not exist.
added safe_remove/rmdir to delete a file without checking for validity.

[Coverity 1050275] Unchecked return value

---

meson.build
packaging/nnstreamer.spec
tests/meson.build
tests/unittestcoverage.py
tizen-api/meson.build

1. exclude tests directory in test coverage
2. set full path to get coverage report
3. print valid path while processing coverage report
4. remove unnecessary flag and clean meson script

[Test/Coverage] update source path - @open sesame 04/08 10:00

---

gst/nnstreamer/tensor_source/tensor_src_iio.c

This is a trivial PR of refactoring.
Refactored _start for code maintainability and understanding.
Resolves #1300

[IIO] refactor _start()

---

nnstreamer_example/meson.build
tests/nnstreamer_filter_custom/runTest.sh

Added option to check opencv availability at runtime.
This simplify meson.build in nnstreamer_example.
Also added verification of the model before running the test.
Resolves #1332

[Test] checking opencv availability at runtime

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc

With mem-optimized flag, always unref tf-buffer after making tensor with passed input data.

[Filter/TF] refcount of tf-buffer

---

jni/Android-app.mk
jni/Android-nnstreamer.mk
jni/nnstreamer.mk
packaging/nnstreamer.spec

define common features to build nnstreamer library for android
TODO: update mk files in nnstreamer-example later

[Build/Android] add common definition

---

tests/tizen_capi/unittest_tizen_capi.cpp
tizen-api/src/tizen-api-pipeline.c

- Return TensorsInfo with get-src-handle
- Fix src-inputdata with TensorsInfo caching mechanism
The second commit in this PR is to add a unit-test-case to prevent regression.

[Tizen/API] Fix pipeline-src implementation @open sesame 4/10 10:22

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
tests/nnstreamer_source/unittest_src_iio.cpp

1. Added test cases for
- caps verification
- default restoration
- setting trigger with number
- using generic scan element type
- auto enable channels
2. Corresponding bug fixes

[IIO] Added more test cases with corresponding bug fixes

---

gst/nnstreamer/tensor_source/tensor_src_iio.c

Enabling/Disabling buffer when going from PAUSED to PLAYING state.
This might lead to higher latency but provides latest and correct data.
Enabling in READY to PAUSED can lead to accumulation of frames before playing
and result in unreal latency as well as old data.
This commit will also sync gst timing with iio device time.

[IIO] Enable/Disable buffer at correct state

---

ext/nnstreamer/tensor_filter/tensor_filter_python.c
ext/nnstreamer/tensor_filter/tensor_filter_python_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_python_core.h

It's a nnstreamer subplugin for custom filters written in Python.
It supports both Python 2 and 3.

[PythonFilter/Subplugin] Add a subplugin for Python custom filters

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h
tests/nnstreamer_source/unittest_src_iio.cpp

Added the option for user to specify custom channel number as input
to enable specific channels.
Added test case for custom channel index as well.
1. Build test: [ ]Passed [ ]Failed [ ]Skipped
2. Run test: [ ]Passed [ ]Failed [ ]Skipped

[IIO] Custom channel index number as input

---

tizen-api/capi-nnstreamer.pc.in
tizen-api/include/tizen-api-private.h
tizen-api/meson.build

remove unnecessary dep declare and fix typo

[Build/C-Api] clean build script

---

gst/nnstreamer/tensor_source/README.md
gst/nnstreamer/tensor_source/tensor_src_iio.c

- Updated README.md
- Added section description for the element

[IIO] added more documentation @open sesame 04/15 15:17

---

gst/nnstreamer/tensor_source/tensor_src_iio.c

1. Refactored handling sampling frequency
2. Added more cases for sampling frequency when files dont exist
3. Renamed functions for better understanding

[IIO] Refactor sampling frequency handling

---

tests/nnstreamer_source/unittest_src_iio.cpp

Resource Leak : Leak of memory or pointers to system resources
Resolved with free data pointers

[Coverity] Resolved memory leaks @open sesame 4/18 17:28

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
gst/nnstreamer/nnstreamer_conf.c
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_demux/gsttensordemux.c
gst/nnstreamer/tensor_merge/gsttensormerge.c
gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_transform/tensor_transform.c

update changes to remove warning message

[Build] remove warning

---

gst/nnstreamer/tensor_reposink/tensor_reposink.c
gst/nnstreamer/tensor_reposink/tensor_reposink.h
gst/nnstreamer/tensor_reposrc/tensor_reposrc.c
gst/nnstreamer/tensor_reposrc/tensor_reposrc.h
tests/nnstreamer_repo_dynamicity/tensor_repo_dynamic_test.c

1. In testcase of tensor-repo test, it does not need to include repo header.
2. Code clean tensor-repo src/sink

[Test/Repo] remove unnecessary header

---

gst/nnstreamer/tensor_split/gsttensorsplit.c
gst/nnstreamer/tensor_split/gsttensorsplit.h

1. check null ptr to get the property tensorseg
2. tensor-split code clean

[Split] exception to get property @open sesame 4/18 17:26

---

tests/nnstreamer_sink/unittest_sink.cpp

1. add timer to push test buffers into appsrc.
2. prevent unittest locked when appsrc cannot send eos event.

[Test/Valgrind] timer to push buffer @open sesame 4/19 12:22

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
ext/nnstreamer/tensor_filter/tensor_filter_python.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
gst/nnstreamer/tensor_filter/tensor_filter_custom.c
gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h

remove build warning (-Wdiscarded-qualifiers)

[Build] remove warning - @open sesame 04/22 19:00

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
tests/nnstreamer_source/unittest_src_iio.cpp

Added support for other/tensors when merging of channels
with corresponding test cases

[IIO] Added support for other/tensors @open sesame 4/18 17:26

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
gst/nnstreamer/tensor_decoder/tensordec.c
gst/nnstreamer/tensor_decoder/tensordec.h
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter_custom.c
gst/nnstreamer/tensor_merge/gsttensormerge.c

update sources to fix warning (missing-prototypes)
TODO : add function prototype to register tensor_* plugins

[Build] fix build warning

---

gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_transform/tensor_transform.c

Some Coverity Issues such as `Resource leak` or `Dereference before null check` are reported by Tizen PM. This PR fixes that issues.
* https://github.com/nnsuite/nnstreamer/issues/1408

[Coverity] Fix the Coverity Issue.

---

ext/nnstreamer/tensor_filter/tensor_filter_python.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h
gst/nnstreamer/nnstreamer_plugin_api_filter.h
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter.h
gst/nnstreamer/tensor_filter/tensor_filter_custom.c
gst/nnstreamer/tensor_filter_custom.h
gst/nnstreamer/tensor_typedef.h

Mode the struct NNFW definition and properties into filter-api header.
Change function name and code clean.
TODO : update decoder struct and api also.

[Filter/Api] move NNFW struct

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h

use glib to compare and parse strings (fix one of security issues)

[Security] [Filter/TF] use glib to parse and compare string

---

gst/nnstreamer/nnstreamer_conf.c
gst/nnstreamer/nnstreamer_conf.h
gst/nnstreamer/tensor_decoder/tensordec.c
gst/nnstreamer/tensor_filter/tensor_filter.c

1. Scan sub-plugins directory and update only so files.
2. Print the list of sub-plugins using gst-inspect in filter/decoder.

[Conf/Subplugins] scan subplugins

---

gst/nnstreamer/tensor_source/tensor_src_iio.c

Use glib function to open file (fix one of security issues)

[Security] [IIO] open file with with glib function

---

gst/nnstreamer/tensor_filter/tensor_filter.c

1. Add code to validate nn-framework data before registration.
2. Code clean to set filter properties.

[Security] [Filter] validate sub-plugin data

---

gst/nnstreamer/nnstreamer_subplugin.c
gst/nnstreamer/tensor_filter/tensor_filter_custom.c

1. Add code to check symlink before open file handle. 
2. Update code to handle error case of invalid params.
(fix one of security issues)

[Security] [Subplugin] check symlink before getting handle - @open sesame 05/08 15:22

---

gst/nnstreamer/nnstreamer.c
gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
gst/nnstreamer/tensor_common.h
gst/nnstreamer/tensor_converter/tensor_converter.c
gst/nnstreamer/tensor_decoder/tensordec.c
gst/nnstreamer/tensor_demux/gsttensordemux.c
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_merge/gsttensormerge.c
gst/nnstreamer/tensor_mux/gsttensormux.c
gst/nnstreamer/tensor_reposink/tensor_reposink.c
gst/nnstreamer/tensor_reposrc/tensor_reposrc.c
gst/nnstreamer/tensor_sink/tensor_sink.c
gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_split/gsttensorsplit.c
gst/nnstreamer/tensor_transform/tensor_transform.c

Move all element registration to common file. (warning about function prototype)

[Build/Plugin] common plugin registration

---

tizen-api/doc/nnstreamer_doc.h

NNStreamer Pipeline is in NNStreamer group.
CC: @again4you 

[Tizen/API] Module group hierarchy fix

---

tizen-api/include/nnstreamer.h

This PR modifies the API and its related thing to comply with Tizen ACR process.
Detailed items are as below.
* Fix the typos in doc header
* Update omitted return codes
* Make API signature as single line

[Tizen/API] Update Tizen API to comply with ACR process @open sesame 05/09 11:25

---

gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_common.h

Remove typefind function.
TODO
Consider to add typefind later in tensor-save/load plugins.

[Common] remove typefind function

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h
meson.build

add minimal flags to prevent build warning

[Meson] add minimal warning flag

---

ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
gst/nnstreamer/nnstreamer_plugin_api.h
gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_common.h
gst/nnstreamer/tensor_converter/tensor_converter.c
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_merge/gsttensormerge.c
gst/nnstreamer/tensor_mux/gsttensormux.c
gst/nnstreamer/tensor_split/gsttensorsplit.c
gst/nnstreamer/tensor_transform/tensor_transform.c
gst/nnstreamer/tensor_typedef.h
nnstreamer_example/custom_example_opencv/meson.build
nnstreamer_example/custom_example_opencv/nnstreamer_customfilter_opencv_average.cc
nnstreamer_example/custom_example_opencv/nnstreamer_customfilter_opencv_scaler.cc
nnstreamer_example/custom_example_passthrough/meson.build
nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c
nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough_variable.c
nnstreamer_example/custom_example_scaler/meson.build
nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c
nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c
tests/meson.build
tests/nnstreamer_sink/unittest_sink.cpp
tools/development/nnstreamerCodeGenCustomFilter.py

1. add common functions about time-sync option (mux/merge)
2. refactor function name and param to handle sync option
3. add functions to get tensor type string and element size

[Common] common functions about time-sync and element type

---

ext/nnstreamer/tensor_filter/tensor_filter_python_core.cc
meson.build
tests/nnstreamer_filter_python/checkScaledTensor.py
tests/nnstreamer_filter_python/python/passthrough.py
tests/nnstreamer_filter_python/python/scaler.py
tests/nnstreamer_filter_python/runTest.sh

I've added some existing testcases
- passthrough.py
- scaler.py
Changelog
V2: update codes to check the python version
V1: add two testcases

[PythonFilter/Testcases] V2: Add some testcases for Python filter

---

gst/nnstreamer/tensor_decoder/tensordec.c

Check decoder sub-plugins data before registration.

[Decoder] validate sub-plugin data

---

debian/changelog
jni/nnstreamer.mk
packaging/nnstreamer.spec

After the release of 0.2.0, 0.2.1-rc1 is started.

Development of 0.2.1 RC1 started

---

tests/tizen_capi/unittest_tizen_capi.cpp
tizen-api/include/nnstreamer.h
tizen-api/src/tizen-api-pipeline.c

1. change function param names and enums for acr process
2. check the error case of invalid param

[Api/Tizen] change param and enum

---

tests/tizen_capi/unittest_tizen_capi.cpp

Add testcases for function params and element switch

[Test/Api/Tizen] add testcases for params and element

---

Documentation/getting-started.md
debian/control
ext/nnstreamer/tensor_filter/meson.build
meson.build

update required meson version to 0.42

[Meson] update version info

---

ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c

This patch fills the body of the callback function for invoke_NN, which
invokes the framework with the given network model.
Relates to #1437
See also: #1441 #1138
**Change logs**
- V3: Fix bug related to g_return_val_if_fail
- V2: Check the number of input tensor in NN_invoke callback
1. Build test: [X]Passed [ ]Failed [*]Skipped
2. Run test: [X]Passed [ ]Failed [* ]Skipped
Signed-off-by: Wook Song wook16.song@samsung.com

[Filter/MvNCSDK] Write callbacks for framework invocation

---

packaging/nnstreamer.spec
tests/tizen_capi/unittest_tizen_capi.cpp
tizen-api/include/nnstreamer-single.h
tizen-api/include/nnstreamer.h
tizen-api/meson.build
tizen-api/src/nnstreamer-single.c
tizen-api/src/tizen-api-pipeline.c

Add base code for single shot model.
Update .spec and add simple testcases.

[Tizen/Api] basic implementation for single shot

---

tests/tizen_capi/unittest_tizen_capi.cpp
tizen-api/include/nnstreamer-single.h
tizen-api/include/nnstreamer.h
tizen-api/include/tizen-api-private.h
tizen-api/src/nnstreamer-single.c
tizen-api/src/tizen-api-pipeline.c

change function name and param prefix to ml

[Tizen/Api] change name prefix

---

gst/nnstreamer/tensor_filter_custom.h

[Typo] fix a minor typo of comment

---

tests/tizen_capi/unittest_tizen_capi.cpp
tizen-api/include/nnstreamer-single.h
tizen-api/include/nnstreamer.h
tizen-api/include/tizen-api-private.h
tizen-api/src/nnstreamer-single.c
tizen-api/src/tizen-api-pipeline.c

Change tensors data struct and set callback with tensors data (sink and appsrc)

[Tizen/Api] change callback param for tensors @open sesame 06/10 13:15

---

tests/tizen_capi/unittest_tizen_capi.cpp
tizen-api/include/nnstreamer-single.h
tizen-api/include/nnstreamer.h
tizen-api/include/tizen-api-private.h
tizen-api/meson.build
tizen-api/src/nnstreamer-single.c
tizen-api/src/tizen-api-pipeline.c
tizen-api/src/tizen-api-util.c

1. Define new functions to handle tensor data and refactor api functions.
2. Update api description.
3. Add testcases using custom filter.

[Tizen/Api] add common utilities @open sesame 06/12 19:35

---

ext/nnstreamer/tensor_filter/tensor_filter_caffe2.c
ext/nnstreamer/tensor_filter/tensor_filter_caffe2_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_caffe2_core.h

it will be updated after packaging pytorch properly and example & test also

[Filter/Caffe2] initial commit for caffe2

---

ext/nnstreamer/tensor_filter/tensor_filter_python_core.cc

Update files to fix svace issue

[Svace] fix save issues for python filter

---

api/capi/src/nnstreamer-capi-pipeline.c
gst/nnstreamer/tensor_filter/tensor_filter.c
tests/common/unittest_common.cpp

update files to fix svace issues

[Svace] fix svace issues

---

api/capi/doc/nnstreamer_doc.h
api/capi/include/nnstreamer-single.h
api/capi/include/nnstreamer.h

This patch fixes the error list of ACR check script.
* https://github.com/nnsuite/nnstreamer/issues/1487

[Tizen/API] Fix the error list of ACR check script. @open sesame 6/18 11:27

---

debian/nnstreamer-caffe2.install
ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_caffe2.c
ext/nnstreamer/tensor_filter/tensor_filter_caffe2_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_caffe2_core.h
jni/nnstreamer.mk
meson.build
meson_options.txt
packaging/nnstreamer.spec

make nnstreamer build process including the caffe2.

[Filter/Caffe2] add caffe2 at the nnstreamer build process- @open sesame 6/18 15:55

---

meson.build

define protobuf dependency and check this dep with tf and caffe2 option.

[Meson] protobuf dependency

---

api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-util.c
tests/tizen_capi/unittest_tizen_capi.cpp

1. add tensorflow pipeline in singleshot
2. testcase with tensorflow speech cmd model

[Tizen/Api] support tensorflow model in singleshot

---

ext/nnstreamer/tensor_decoder/meson.build
ext/nnstreamer/tensor_decoder/tensordec-pose.c
jni/nnstreamer.mk

In order to display the result from pose estimaition, we may need
decoder. The output format of pose estimation is [14, o_Width,
o_Height, 1]. 14 means number of joint of human bone structure, top,
neck, r_shoulder, r_elbow, r_wrist, l_shoulder, l_elbow, l_wrist,
r_hip, r_knee, r_ankle, l_hip, l_knee, l_ankle.

[DECODER] Add Pose Estimation Decoder - @open sesame 6/28 13:29

---

debian/control
gst/nnstreamer/tensor_source/README.md

Add PR to fix typo (nerual > neural)

[Doc] fix typo

---

api/capi/doc/nnstreamer_doc.h

update doc-header file (fix typo and minor changes)

[API] fix typo in doc header

---

jni/nnstreamer.mk

define path of c-api for android build

[C-Api/Android] add build path for c-api

---

api/capi/src/nnstreamer-capi-single.c

Add code to validate input data in single-invoke function.

[C-Api/Single] validate input data @open sesame 7/11 15:23

---

api/capi/src/nnstreamer-capi-pipeline.c
tests/tizen_capi/unittest_tizen_capi.cpp

Add code to free pipeline element and hash-table.

[C-Api] free element handle - @open sesame 7/15 14:42

---

ext/nnstreamer/tensor_decoder/meson.build
ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
ext/nnstreamer/tensor_decoder/tensordec-font.c
ext/nnstreamer/tensor_decoder/tensordec-pose.c
jni/nnstreamer.mk

change font file in decoder-subplugins to build static library.

[Decoder/Sub] build static lib

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h

change the codes of tensorflow filter to use c_api only
it resolves #1556 

[Filter/TF] apply c_api at tensor_filter_tensorflow

---

api/android/api/jni/Android.mk
api/android/api/jni/nnstreamer-native-api.c
api/android/api/jni/nnstreamer-native-customfilter.c
api/android/api/jni/nnstreamer-native-pipeline.c
api/android/api/jni/nnstreamer-native-singleshot.c
api/android/api/jni/nnstreamer-native.h
api/android/api/src/com/samsung/android/nnstreamer/CustomFilter.java
api/android/api/src/com/samsung/android/nnstreamer/NNStreamer.java
api/android/api/src/com/samsung/android/nnstreamer/Pipeline.java
api/android/api/src/com/samsung/android/nnstreamer/SingleShot.java
api/android/api/src/com/samsung/android/nnstreamer/TensorsData.java
api/android/api/src/com/samsung/android/nnstreamer/TensorsInfo.java
api/android/sample/src/main/java/com/samsung/android/nnstreamer/sample/MainActivity.java

1. Fix wrong conversion of byte buffer in native.
2. Add methods to allocate buffer with native byte order.
3. Fix invalid condition to close handle.
4. Add custom-filter in java to execute tensors data in the application.

[Android/Api] fix invalid data and add custom-filter

---

api/capi/src/nnstreamer-capi-pipeline.c
api/capi/src/nnstreamer-capi-util.c

1. Fix invalid condition when mutex-lock of element handle locked.
2. Add new struct to set mutex locked.

[Tizen/Feature] invalid condition to check feature status

---

api/capi/src/nnstreamer-capi-util.c

In the functions for tensor data, add code to check null param.

[Api] check null param

---

api/capi/include/nnstreamer-single.h
api/capi/include/nnstreamer.h

Fix typo and update details about the APIs.

[Api] update api description

---

api/capi/include/nnstreamer-capi-private.h
api/capi/src/nnstreamer-capi-pipeline.c
api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-util.c

change nnstreamer headers include to prepare gradle build.

[Api] common headers in nnstreamer

---

gst/nnstreamer/nnstreamer_plugin_api_decoder.h
gst/nnstreamer/nnstreamer_plugin_api_filter.h
tests/nnstreamer_sink/unittest_sink.cpp

1. link error about plugin api in cpp file.
2. Add simple stream testcase for custom-filter without model file.

[Common/Test] function declaration and testcase for custom

---

README.md

We now fully ready for Android & Yocto.
Update the release status

[Readme] Update release status

---

ext/nnstreamer/tensor_filter/tensor_filter_python_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_python_core.h

This commit fixes svace errors.

[PythonFilter] Fix svace errors in python filter

---

tests/common/unittest_common.cpp
tests/nnstreamer_converter/runTest.sh
tests/nnstreamer_decoder/runTest.sh
tests/nnstreamer_filter_custom/runTest.sh
tests/nnstreamer_filter_pytorch/runTest.sh
tests/nnstreamer_filter_tensorflow_lite/runTest.sh
tests/nnstreamer_repo/runTest.sh
tests/nnstreamer_sink/unittest_sink.cpp
tests/tizen_capi/unittest_tizen_capi.cpp
tests/transform_arithmetic/runTest.sh
tests/transform_typecast/runTest.sh

1. Add postfix in tc name for the negative testcases.
2. Update comment for future work.

[Test] mark negative testcase - @open sesame 8/6 15:25

---

api/capi/src/nnstreamer-capi-single.c

1. allocate output buffer after invoke is done.
2. allow one buffer in appsink and drop old buffer.

[Api/Single] invalid output if error occurs

---

api/android/api/src/com/samsung/android/nnstreamer/TensorsData.java
api/android/api/src/com/samsung/android/nnstreamer/TensorsInfo.java

add method to calculate byte size of tensor data.

[Android/Api] method to get data size

---

api/capi/include/nnstreamer-capi-private.h
api/capi/src/nnstreamer-capi-pipeline.c
api/capi/src/nnstreamer-capi-util.c
tests/tizen_capi/unittest_tizen_capi.cpp

prepare code to validate the plugins in pipeline.
TODO: update code to initialize white-list for tizen

[Api/Tizen] base code to check plugin name - @open sesame 8/8 16:09

---

api/capi/include/nnstreamer-capi-private.h
api/capi/src/nnstreamer-capi-pipeline.c
api/capi/src/nnstreamer-capi-single.c

1. add struct for state change callback
2. check element pointer before free the resources
3. remove unnecessary code to free buffer mem block

[Api] code clean

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h
meson.build
meson_options.txt
packaging/nnstreamer.spec

Support nnfw. If enable-nnfw is on, it will use nnfw.

[nnfw] Adding nnfw support with nnapi

---

ext/nnstreamer/tensor_filter/tensor_filter_python_core.h
ext/nnstreamer/tensor_filter/tensor_filter_pytorch_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_pytorch_core.h
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h
gst/nnstreamer/nnstreamer_subplugin.c
gst/nnstreamer/tensor_filter/tensor_filter_custom.c

Remove dependency of tensor_filter plugins on gst headers
Working on #1547 

[Filter/Plugins] Remove dependency on gst headers

---

api/capi/include/nnstreamer-single.h
api/capi/include/nnstreamer.h
api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-util.c
tests/tizen_capi/unittest_tizen_capi.cpp

PR for next ACR
1. get the byte size with data index.
2. add new function to set the timeout to wait for the output.

[Api/Tizen] update APIs for next process

---

gst/nnstreamer/tensor_transform/tensor_transform.h

fix invalid file extension in transform header

[Doc] fix invalid extension

---

tests/tizen_capi/unittest_tizen_capi.cpp

In slow systems such as QEMU-ARM, a few test cases fail often.
- Add dynamic timeout for pipeline start
- Add mutex for sink callbacks
@leemgs We can now enable unit-test for ARM in CI server.

[Test] Prevent unit-test errors in slow systems

---

CHANGES
debian/changelog
jni/nnstreamer.mk
meson.build
packaging/nnstreamer.spec

Please do SR with this.
If you have PRs to be merged before 0.3.0, please hurry up! :)

Release of 0.3.0

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h
tests/nnstreamer_filter_tensorflow_lite/runTest.sh

Add test cases for reading nnapi property in tensorflow lite example.

[TESTS] add test cases for nnapi property @open sesame 9/3 07:51

---

api/capi/include/nnstreamer-capi-private.h
api/capi/include/nnstreamer.h
api/capi/meson.build
api/capi/src/nnstreamer-capi-pipeline.c
api/capi/src/nnstreamer-capi-tizen.c
api/capi/src/nnstreamer-capi-util.c
gst/nnstreamer/nnstreamer_plugin_api.h
gst/nnstreamer/tensor_common.c
packaging/nnstreamer.spec
tests/common/unittest_common.cpp
tests/tizen_capi/unittest_tizen_capi.cpp

1. Add new file for Tizen dependent code.
2. Add base code to check predefined element name in pipeline description.

[Api/Tizen] base code to convert element in pipeline

---

tests/nnstreamer_filter_tensorflow_lite/runTest.sh

[TEST] Fix nnapi test

---

Documentation/component-description.md

This document was way too obsolete. Update it with recent info.

[Doc] Update the component-description

---

packaging/nnstreamer.spec

Added dependency of devel-capi on capi

[Dist/RPM] Added library required by devel package

---

api/android/api/build.gradle
api/android/build-android-lib.sh
api/android/build.gradle
api/android/sample/build.gradle

Add dependency and args for jcenter release.
To upload NNStreamer library, run the script with bintray user name.
./api/android/build-android-lib.sh --release=yes --release_version=$release_ver --bintray_user_name=$user_name --bintray_user_key=$user_key

[Android] update script to release - @open sesame 09/10 15:53

---

api/capi/src/nnstreamer-capi-single-new.c

Added support for timeout in new single-shot API implementation to
comply with the existing single-shot API
Working on #1547

[single-shot] Added support for timeout in single-shot

---

api/capi/src/nnstreamer-capi-single-new.c

1. Fix invalid cond to check file extension.
2. Add proper log message and error code to set tensors info.

[Api/Single] invalid condition to check file extension

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
ext/nnstreamer/tensor_filter/tensor_filter_python_core.cc
gst/nnstreamer/nnstreamer_conf.c
gst/nnstreamer/tensor_demux/gsttensordemux.c
gst/nnstreamer/tensor_merge/gsttensormerge.c
gst/nnstreamer/tensor_mux/gsttensormux.c

remove duplicates and unnecessary code.

[CodeClean] remove duplicates

---

ext/nnstreamer/tensor_filter/tensor_filter_python_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_python_core.h

remove pthread header and use g_mutex instead.

[Filter/Sub] use glib-mutex

---

api/capi/include/tensor_filter_single.h
api/capi/src/tensor_filter_single.c
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter.h
gst/nnstreamer/tensor_filter/tensor_filter_common.c
gst/nnstreamer/tensor_filter/tensor_filter_common.h

Add common functions for tensor-filter and filter-single.
1. add struct for common property
2. reduce duplicated code of tensor-filter

[Filter] add common functions

---

api/capi/src/nnstreamer-capi-single-new.c
api/capi/src/nnstreamer-capi-single.c
tests/tizen_capi/unittest_tizen_capi.cpp

Added more unittests for single-shot API testing
1. Multiple runs in parallel with varying timeouts
2. Changing timeout/closing the handle while calling the API in a different thread
3. Closing the handle multiple times
4. Check valid result after increasing the timeout, when earlier it was timing out

[Single] Added unittests

---

packaging/nnstreamer.spec

Fix typo and cleanup build options.

[Build] cleanup script @open sesame 09/18 19:11

---

README.md

We now release macoS and JCenter binaries.

[Readme] Update deployment status @open sesame 09/18 19:46

---

api/android/build-android-lib.sh
api/capi/meson.build
debian/rules
meson.build
packaging/non_tizen_build.patch

Added cleanup of patches after android/ubuntu build
Changed relative path of files to patches in patch file

[build] Added cleanup after android/ubuntu build @open sesame 09/19 12:31

---

api/capi/include/nnstreamer-capi-private.h
api/capi/src/nnstreamer-capi-pipeline.c
api/capi/src/nnstreamer-capi-single-new.c
api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-util.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc

1. define common functions to reduce complexity
2. condition to print log message about nnapi

[Clean/SAM] add common functions - @open sesame 09/18 15:27

---

api/capi/src/nnstreamer-capi-single-new.c
api/capi/src/nnstreamer-capi-single.c

For the readability and to prevent mistakes in the future,
- Apply symmetricity to lock/unlock, hide magic lock from programmers
- Apply common ops into macro
CC: @kparichay

[CAPI/New-Single] Code Clean

---

api/android/api/build.gradle
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java

Add base code to run Android instrumented test on the target devices.
TODO add testcases for each java class

[Android/Test] base code to run instrumented test @open sesame 09/20 16:26

---

api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsInfo.java
api/android/sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java

Fix typo in tensor-info class and update related sample code.

[Android/Api] fix typo

---

api/capi/src/nnstreamer-capi-single-new.c

Remove the dependency over pthread
Use glib functionalities instead

[single-new] Remove dependency over pthread

---

api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsData.java

1. update condition to check the given params.
2. update api description about ml model.

[Android/Api] update condition

---

api/capi/src/nnstreamer-capi-single-new.c
tests/tizen_capi/unittest_tizen_capi.cpp

Added memory leak bug fix in error cases running

[single-new] Memory leak bug fix in error cases

---

README.md
api/android/README.md

add readme to build android library using the script.

[Android/Api] add readme to build api

---

api/android/build-android-lib.sh

Update script to run the unittest on target device.
Note that, the testcases are android instrumented test which requires the target device.
Cmd to build and run test: ./build-android-lib.sh --run_unittest=yes

[Android/Test] script to run unittest

---

api/capi/src/nnstreamer-capi-single-new.c
tests/nnstreamer_source/unittest_src_iio.cpp

Fix svace issues, check returned value and file descriptor.

[Security] handle return value

---

api/capi/src/nnstreamer-capi-tizen.c

Check camera and recoder privilege for each src element.

[Api/Tizen] check cam privilege

---

api/android/api/build.gradle
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCustomFilter.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestTensorsData.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestTensorsInfo.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/CustomFilter.java

1. update testcases for each java class
2. add flag to generate coverage report

[Android/Test] update testcases @open sesame 9/27 15:35

---

api/capi/src/nnstreamer-capi-single-new.c

missed typecast in single-shot, fix build error.

[URGENT] [Build] build fail in 18.04

---

tests/tizen_capi/unittest_tizen_capi.cpp

Increase the default timeout to pass the test case on a slow machine/not fully
optimized tensorflow-lite. Also, as the running time for tf-lite test case in
aarch64 is over 10x compared to armv7l, higher defailt timeout is better.
In unit-test, increased the corresponding default timeout as well.
Further, when running many test cases in parallel, default timeout is scaled
with number of parallel runs.
Solves #1717

[URGENT] [single] Increase default timeout

---

api/capi/include/nnstreamer-capi-private.h
api/capi/src/nnstreamer-capi-pipeline.c
api/capi/src/nnstreamer-capi-tizen.c

add flag to ignore the permission (supposed tizen internal)
TODO
add new pkg in tizen with this PR

[Api/Tizen] internal function to ignore permission

---

ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
ext/nnstreamer/tensor_filter/tensor_filter_cpp.h

A few users have requested the ability to write C++ custom filters
especially for OpenCV usage.

[Filter/C++] Skeleton header @open sesame 9/28 11:51

---

api/android/build-android-lib.sh

Update build script to be directly used by CI for building

[android/build] Update build script

---

api/capi/src/nnstreamer-capi-tizen.c

Add missed param mm-handle to get video cam src element in Tizen.

[Tizen/Api] fix invalid params to parse mm info

---

ext/nnstreamer/tensor_filter/tensor_filter_caffe2.c
ext/nnstreamer/tensor_filter/tensor_filter_pytorch.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
gst/nnstreamer/nnstreamer_plugin_api_filter.h
gst/nnstreamer/tensor_filter/tensor_filter_common.c

Check returned value when the nn model file is already loaded.

[Filter/Sub] already loaded case

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCustomFilter.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java

Add aging test to check local ref table overflow.

[Android/Test] add tc to check max local ref

---

api/capi/src/nnstreamer-capi-single-new.c

Added minor updates in C-API single shot implementation for improved modularity
This makes the code skeleton at par with existing single-shot implementation

[single] Minor updates for modularity

---

api/capi/include/nnstreamer-capi-private.h
api/capi/include/nnstreamer-tizen-internal.h
api/capi/meson.build
api/capi/src/nnstreamer-capi-pipeline.c
packaging/nnstreamer.spec
tests/tizen_capi/unittest_tizen_capi.cpp

Add Tizen internal API without checking the permission.

[Api/Tizen] Tizen internal API to construct pipeline

---

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
ext/nnstreamer/tensor_filter/tensor_filter_python.c
ext/nnstreamer/tensor_filter/tensor_filter_pytorch.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c

change string util functions to parse and compare strings.

[Filter/Sub] use glib to compare strings

---

packaging/nnstreamer.spec

Add tv-camsrc and pulsesrc as cam input src element.

[Api/Tizen] update restricted elements

---

api/capi/src/nnstreamer-capi-pipeline.c
api/capi/src/nnstreamer-capi-tizen.c

bug-fix to replace element string in pipeline description.

[Api/Tizen] bug-fix to replace str

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h

1. remove duplicated src and fix indent
2. move hw-type string definition

[Filter/TF-lite] cleanup hw-type string

---

gst/nnstreamer/tensor_common.c

Use regular expressions instead of combined if-statements.
related issue: nnsuite#1745
Signed-off-by: Injae Kang <abcinje@gmail.com>

[CodeClean] Apply regular expressions

---

Documentation/component-description.md
Documentation/writing-subplugin-tensor-filter.md

With https://github.com/nnsuite/nnstreamer-example/pull/68
this guide helps developer write a new filter subplugin easily.
With that PR in nnstreamer-example, this resovles #1746

[Doc] Guide: writing a new tensor-filter subplugin

---

api/capi/src/nnstreamer-capi-single.c

check the output buffer size before copying the mem block.
This will fix SSMS-0002.

[Security] check buffer size

---

api/capi/src/nnstreamer-capi-pipeline.c
ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
ext/nnstreamer/tensor_filter/tensor_filter_python.c
ext/nnstreamer/tensor_filter/tensor_filter_pytorch.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
gst/nnstreamer/nnstreamer_conf.c
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_merge/gsttensormerge.c
gst/nnstreamer/tensor_source/tensor_src_iio.c

EXP20-C. Perform explicit tests to determine success, true and false, and equality
This will fix SSMS-0003.

[Security] cond to compare strings

---

Documentation/getting-started.md
Documentation/writing-tizen-native-apps.md

This guide allows developers to start writing Tizen native apps more easily.
This partially resovles #1751.

[Doc] Tizen Native App Guide

---

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c

Added implementation for get_input/output_dimensions functions
Refer #1677

[tizen/nnfw] Add get_input/output_dimensions

---

Documentation/component-description.md
Documentation/gen-md-toc.sh
Documentation/getting-started.md
Documentation/how-to-write-testcase.md
Documentation/writing-subplugin-tensor-filter.md
Documentation/writing-tizen-native-apps.md

Update docs (fix links and typo in document)

[Doc] fix typo and link

---

ext/nnstreamer/android_source/gstamcsrc.c
gst/nnstreamer/nnstreamer_conf.c
gst/nnstreamer/tensor_source/tensor_src_iio.c

Add one more commit for string compare, check returned value.
EXP20-C. Perform explicit tests to determine success, true and false, and equality

[Security] returned value to compare str

---

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c

Added invoke implementation for nnfw along with some bug fixes
Refer #1677

[tizen/nnfw] Add invoke for nnfw

---

Documentation/doxygen-documentation.md

update doc-doxygen, fix the linked url.

[Doc] fix doxygen link

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc

make a variable for "interpreter->tensor (tensor_idx)->dims".
replace "interpreter->tensor (tensor_idx)->dims" with the variable.
related issue: #1773 
Signed-off-by: Junsang Mo <junsang.mo@samsung.com>

[CodeClean]remove duplicates in TFLiteCore::getTensorDim

---

tests/nnstreamer_plugins/unittest_plugins.cpp

Add testcase to re-open nn model in tensor-filter using gst-harness.

[Test] update model in tensor-filter

---

gst/nnstreamer/tensor_transform/tensor_transform.c

combine if statements in tensor_transform.c.
I confirmed it worked well in example_image_classification_tflite.
related isuue: #1786 
Signed-off-by: Junsang Mo <junsang.mo@samsung.com>

[CodeClean] combine if statements.

---

gst/nnstreamer/tensor_transform/tensor_transform.c

replace (a, b) with (from, to).
Signed-off-by: Dongwon Lee <dongwon1103@naver.com>

[CodeClean] replace meaningless variables @open sesame 10/20 17:03

---

ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c

Added implementation of two functions.
1.  `set_label_index()` : Set a index with the highest probability of 21 labels for each pixel. 
2.  `set_color_according_to_label()` : Paint the appropriate color according to the label_idx for each pixel.
Signed-off-by: niklasjang <niklasjang@gmail.com>
Signed-off-by: Jihoon Lee <ulla4571@gmail.com>

[Decoder] Implementation of image segmentation

---

gst/nnstreamer/nnstreamer_plugin_api_decoder.h

Update callback description for decoder sub-plugin.

[Decoder] update callback description

---

api/capi/include/tensor_filter_single.h
api/capi/src/nnstreamer-capi-single-new.c
api/capi/src/tensor_filter_single.c
tests/tizen_capi/unittest_tizen_capi.cpp

Added implementation of flexible input dimension at the API level
Handling flexible input dimension at the tensor filter extension
scope to be done.
Check #1651 for more information

[single] Implementation of flexible input dimension

---

api/capi/src/nnstreamer-capi-single-new.c

Added fix for flexible dimension unittest fail fix for master branch

[URGENT] [single] flexible dimension unittest fail fix

---

ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
ext/nnstreamer/tensor_filter/tensor_filter_caffe2_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_caffe2_core.h
ext/nnstreamer/tensor_filter/tensor_filter_pytorch_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_pytorch_core.h
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h
gst/nnstreamer/tensor_repo/tensor_reposrc.c

Update code to fix invalid condition and free functions in nnstreamer plugins.

[Coverity] fix coverity issues

---

api/capi/meson.build
debian/control
meson.build
packaging/nnstreamer.spec
tools/development/nnstreamerCodeGenCustomFilter.py

Set min meson version 0.50 and cleanup the script.

[Meson] update required meson version

---

api/capi/src/nnstreamer-capi-single-new.c

Fix possible svace issue
https://github.com/nnsuite/nnstreamer/pull/1787#discussion_r337823705
CC. @jaeyun-jung

[single] Fix possible svace issue later

---

api/capi/include/nnstreamer-single.h

Added extra inline funcitons to provide easier API for dyanmic input dimensions
Check #1651 for more information

[single] More inline functions for flexible dimensions

---

meson.build

Resolves #1805 
This PR improves #1815 by refactoring the logic that checks dependencies on numpy.

[Meson] Refactor the logic that checks dependencies on numpy

---

api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/api/src/main/jni/nnstreamer-native-pipeline.c
api/android/api/src/main/jni/nnstreamer-native.h

define enum for pipeline and element type, remove string compare.

[Android/Api] enum for pipeline type

---

Documentation/component-description.md

I added feature 'Planned' for better understanding.

[Doc] Update document

---

Documentation/writing-tizen-csharp-apps.md

This patch newly adds the guide for writing .NET Application with
Machine Learning APIs.
* Apply all comments from reviews
* Sync from Tizen official documentation

[Doc] Guide: how to write .NET Application

---

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cpp

Added unittest for invoke for nnfw tensor filter extension
Added unittest for get input/output dimensions
Corresponding bug fixes are also added
Resolves #1677 

[filter/nnfw] Unittest for invoke

---

api/android/README.md

Added updates to README.md for setting up and building nnstreamer API for android

[android/doc] Update README.md

---

api/capi/include/nnstreamer-single.h
api/capi/src/nnstreamer-capi-pipeline.c

1. declare function to iterate the elements in pipeline description
2. fix api declaration (params in same line)

[CodeClean] reduce complexity @open sesame 11/08 07:03

---

api/android/README.md
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/build-android-lib.sh

update build script to provide native libraries using nnstreamer c-api.

[Android] prepare native libs for c-api @open sesame 11/10 13:27

---

api/android/README.md
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
api/android/api/src/main/jni/nnstreamer-native-singleshot.c

Added flexible dimensions support for Android API
Added unittests for flexible API as well for Android

[android] Add flexible dimensions support for Android API

---

tests/nnstreamer_source/unittest_src_iio.cpp

This patch fixes defects related to CWE-637 found from Coverity.
See also: https://github.com/nnsuite/nnstreamer/issues/1682
Coverity-scan: CID-263387, CID-263398, CID-263366, CID-263406,
CID-263410, CID-263372, CID-263390, CID-263361,
CID-263414

[Tests/Source/IIO] Fix defects (CWE-637) found from Coverity @open sesame 11/11 16:00

---

api/capi/include/nnstreamer.h
api/capi/src/nnstreamer-capi-single.c

Let C-API users use Intel NCS.
CC: Wook Song <wook16.song@samsung.com>

[C-API] Support MVNC with Single API

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h
meson.build
meson_options.txt

Fix variables in meson.build for nnfw and nnfw-runtime

[nnfw] Fix meson @open sesame 11/15 15:56

---

ext/nnstreamer/tensor_source/README.md
ext/nnstreamer/tensor_source/meson.build
ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
ext/nnstreamer/tensor_source/tensor_src_tizensensor.h
packaging/nnstreamer.spec

This element fetches data from Tizen Sensor Framework for NNStreamer.
This commit includes the init parts and shows how it will be built and deployed.
Other function bodies will follow in other commits/PRs.
This addresses #1143

New Element: Tensor_SRC_TizenSensor, Init

---

tests/nnstreamer_source/unittest_src_iio.cpp

Fix coverity defects
1. Related to fd resource leak in a macro with assert failure
2. Add more defect fixes already provided in #1859 and #1863 to another location
cc. @wooksong

[Test/Src/IIO] Fix coverity defects

---

ext/nnstreamer/tensor_filter/tensor_filter_caffe2_core.cc

1. fix invalid tensor meta while running invoke callback
2. add debug messages for tensor meta info

[Filter/Caffe2] fix invalid data type

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h
gst/nnstreamer/nnstreamer_plugin_api_filter.h
gst/nnstreamer/tensor_filter/tensor_filter_common.c
tests/nnstreamer_filter_tensorflow_lite/runTest.sh

Added update to support various accelerators for tensor filters
~This is an initial design
Please provide your comments.
Note: this only provides the design, and implementation and support for all the sub-plugins will be 
added after initial review.~
Updated tensorflow-lite nnapi setting based on these accelerators
Added testcases for tensorflow-lite
Refer #1849 

[tensor_filter/tflite] Update for supporting various accelerators @open sesame 11/15 15:35

---

tests/nnstreamer_source/unittest_src_iio.cpp

Added more checks coherent with in #1859 and #1863 to another location

[IIO/test/coverity] Resolve coverity issues

---

tests/nnstreamer_source/unittest_src_iio.cpp

free log-file name str in clean-dev function.

[CodeClean/Test] free log-file str

---

ext/nnstreamer/tensor_source/tensor_src_tizensensor.c

- finalize, start, stop, is_seekable filled.
- Internal static functions are partially filled for future direction.
This should follow #1864 and addresses #1143
ps. I'm separating into smaller commits for better reviewability.

Tensor-src-tizensensor: fill minor gst callbacks

---

Documentation/writing-tizen-csharp-apps.md
api/capi/doc/nnstreamer_doc.h
ext/nnstreamer/tensor_source/tensor_src_tizensensor.c

This patch updates the URL for Tizen API and its related link.

[Docs] Update the link for Tizen

---

ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
ext/nnstreamer/tensor_source/tensor_src_tizensensor.h

- Added Tizen sensor-framework mechanisms (sensor-listeners)
- Added get/set caps callbacks of Gst.
- Revised a few data structures.
This addresses #1143

Tensor-src-tizensensor: fill gst callbacks, Tizen sensor-fw APIs @open sesame 12/03 21:53

---

ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
ext/nnstreamer/tensor_filter/tensor_filter_python_api.c
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.cc
gst/nnstreamer/nnstreamer_plugin_api.h
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_converter/tensor_converter.c
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_transform/tensor_transform.c
gst/nnstreamer/tensor_transform/tensor_transform.h
tests/common/unittest_common.cpp
tests/nnstreamer_plugins/unittest_plugins.cpp
tests/tizen_capi/unittest_tizen_capi.cpp
tools/development/nnstreamerCodeGenCustomFilter.py

1. remove duplicated condition and fix invalid comment
2. add tc to check tensor info

[CodeClean] cleanup duplicated and update testcases

---

ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
ext/nnstreamer/tensor_source/tensor_src_tizensensor.h

All the required callbacks are implemented.
Next step: write test cases.
This addresses #1143

Tensor-src-tizensensor: complete initial implementation. @open sesame 12/05 13:32

---

Documentation/component-description.md

The component descriptions were obsolete. Update them.

Doc: update component implementation status

---

ext/nnstreamer/tensor_source/meson.build
ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
ext/nnstreamer/tensor_source/tensor_src_tizensensor.h

Apply gst-indent to the new element, "tensor_src_tizensensor".
Changed in v2:
- Fixed meson.build
- Fixed all the build erros and warnings of tizensensor

Tensor-src-tizensensor: fixes (style & build)

---

api/android/build-android-lib.sh

Add asset dir for native library.

[Android] add asset dir for native library

---

Documentation/contributing.md

Let's describe the standards we are already enforcing.

Doc/Contributing: update code quality standards

---

api/android/api/src/main/jni/Android-nnstreamer.mk
jni/Android-app.mk
jni/Android-nnstreamer.mk
jni/Android.mk
jni/nnstreamer.mk

define common header path for gstreamer.

[Android] common headers for gstreamer

---

api/android/build-android-lib.sh

provide headers for plugin writer in android native build.

[Android] header files for sub-plugin

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc

remove unnecessary code (duplicated with tf_destroyNotify())

[Filter/TF] remove unnecessary code

---

gst/nnstreamer/tensor_converter/tensor_converter.c

define function to get possible media caps from downstream element.

[Converter] reduce complexity

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc
ext/nnstreamer/tensor_filter/tensor_filter_python.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc

Remove -Wno-sign-compare and corresponding fixes

[build] Remove -wno-sign-compare

---

ext/nnstreamer/tensor_filter/meson.build

remove remained flag 'no-sign-compare'

[Build] remove unnecessary flag

---

packaging/nnstreamer.spec

Added minor fixes:
- nnstreamer-capi.manifest to be not used non-tizen packages
- remove nnfw enable variable as nnfw is always enabled
Cleanup
- remove extra tizen conditions
- Move similar blocks together for better understanding

[spec] Minor fixes and cleanup

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
meson_options.txt
packaging/nnstreamer.spec

Added tensor filter extension of armnn
Related Issue: #1817 

[armnn] Added tensor filter extension of armnn @open sesame 12/23 18:49

---

packaging/nnstreamer.spec
tests/meson.build
tests/nnstreamer_filter_armnn/unittest_filter_armnn.cpp

Added unittests for armnn tensor filter extension
Related Issue: #1817

[armnn] Added unittests for armnn

---

ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc

Related to https://github.com/nnsuite/nnstreamer/issues/1708.
This patch adds skeleton code of a tensor filter sub-plugin for OpenVino Toolkit (dldt) support.

[Filter/OpenVino] Add skeleton code of a sub-plugin for OpenVino support

---

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
ext/nnstreamer/tensor_filter/tensor_filter_python.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
gst/nnstreamer/nnstreamer_subplugin.c
gst/nnstreamer/tensor_filter/tensor_filter_common.c

fix some coverity issues and sam score

[CodeClean] fix coverity

---

api/capi/include/nnstreamer.h
api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-util.c

Define SNAP in nnfw type, only for Android.

[Api] add SNAP in nnfw enum type

---

ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc

This PR requires #1983 and applies the comments https://github.com/nnsuite/nnstreamer/pull/1983#discussion_r361885418 from @dongju-chae and https://github.com/nnsuite/nnstreamer/pull/1983#discussion_r361888911 from @jaeyun-jung.
This PR improves the mechanism to parse the provided model(s). The model could be given in the following forms:
- a path of the .bin or .xml file
- a path of the prefix of the .bin and .xml file
- a set of paths of the both .bin and .xml files.
In addition to the above, this PR adds a mechanism to handle the case when this sub-plugin is
re-opened.

[Filter/OpenVino] Improve provided model(s) parsing and Handle the case when the sub-plugin is re-opened 

---

ext/nnstreamer/tensor_filter/tensor_filter_python.cc
ext/nnstreamer/tensor_filter/tensor_filter_python_api.c
packaging/nnstreamer.spec

This patch newly adds the python-filter option, which could support to be
disabled if developers want. 

[Spec] Add python-filter option

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCustomFilter.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestTensorsData.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestTensorsInfo.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/CustomFilter.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/Pipeline.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsData.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsInfo.java
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/api/src/main/jni/nnstreamer-native-customfilter.c
api/android/api/src/main/jni/nnstreamer-native-pipeline.c
api/android/api/src/main/jni/nnstreamer-native-singleshot.c
api/android/api/src/main/jni/nnstreamer-native.h

1. Add tensors info in TensorsData class.
2. Handle error case when failed to create pipe info in native functions.
3. Define enumeration for tensor data type and pipeline state.

[Android] tensors-data class with metadata @open sesame 01/06 17:15

---

ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc

Related to #1708.
This PR adds a method to run inference for given input tensors using InferenceEngine on the acceleration device. It also implements the mandatory callback of GstTensorFilterFramework, invoke, with such method.
Running tests are done with inception v3.

[Filter/OpenVino] Fill the mandatory callback, invoke

---

gst/nnstreamer/nnstreamer_conf.c

This PR overrides `NNSTREAMER_CONF_FILE` with env-var conf in
non-Tizen system. So, env-var conf has a higher priority than others.
With this feature, some unittests using a conf file from env-var has
passed even if the default conf file (`/etc/nnstremer.ini`) exists.
Note that Tizen does not allow to set configurations from env-var.
**Problem**
`unittest_common` has failed when `/etc/nnstreamer.ini` exists because it always has a higher priority than others. 
```
[----------] 1 test from conf_custom
[ RUN      ] conf_custom.env_str_01
../tests/common/unittest_common.cpp:786: Failure                                
Expected equality of these values:                                              
fn                                                                            
Which is: NULL …
```

[CONF] override NNSTREAMER_CONF_FILE with env-var conf in non-Tizen

---

.github/CODEOWNERS

Notify Gichan and Yongjoo for any changes in the repo.

CODEOWNERS: add new members

---

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc

With updated nnfw API, support setInputDimension with nnfw
Although the API is defined, its not yet implemeted interally
So, the unittest is added, but disabled

[nnfw] Support setInputDimension with nnfw

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCustomFilter.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSNAP.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestTensorsData.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestTensorsInfo.java
api/android/api/src/main/AndroidManifest.xml
api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/api/src/main/jni/nnstreamer-native-singleshot.c
api/android/api/src/main/jni/nnstreamer-native.h
api/capi/include/nnstreamer-capi-private.h
api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-util.c

In Java APIs, handle multiple model files and custom option to support SNAP.
Define enum for supported NNFW and implement native functions.

[Android] support SNAP in Android

---

tests/nnstreamer_filter_extensions_common/deploy.sh
tests/nnstreamer_filter_extensions_common/meson.build
tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc
tests/nnstreamer_source/unittest_src_iio.cc

1. change file extension to .cc in testcases
2. change path to generate ext-test files

[CodeClean] change file extension

---

README.md

- Added the two new reviewers
- Added more info on the project status

README: update reviewers and project status

---

Documentation/coding-convention.md
Documentation/component-description.md
Documentation/contributing.md

We have been progressed a lot. Update the documentation accordingly.

Documentation Update of 2020.01

---

ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc

The headers are not in this project. Though it does not occur errors, to prevent misunderstanding, it needs to be fixed.

[Caffe2] Change how headers are included

---

tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc

check exception case in testcases.

[CodeClean] fix coverity issue

---

api/capi/include/nnstreamer-capi-private.h
api/capi/src/nnstreamer-capi-util.c
packaging/nnstreamer.spec

1. remove unnecessary function to get caps from tensor-info.
2. move to proper build option and cleanup unnecessary option.

[CodeClean] remove unnecessary code

---

packaging/nnstreamer.spec

Resolve version mismatch of .spec with current dev version 1.3.0
Resolves: #2036

[Spec] Update version 1.2.0 to 1.3.0 of rpm spec

---

tests/nnstreamer_sink/unittest_sink.cc

add testcase with multiple custom filters.

[Test] stream testcase with multiple custom-filters @open sesame 1/16 16:10

---

Documentation/nnstreamer_capi.md
api/capi/doc/nnstreamer_doc.h
api/capi/include/nnstreamer-capi-private.h
api/capi/include/nnstreamer-single.h
api/capi/include/nnstreamer-tizen-internal.h
api/capi/include/nnstreamer.h
api/capi/include/platform/tizen_error.h
api/capi/src/README.md
api/capi/src/nnstreamer-capi-pipeline.c
api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-tizen.c
api/capi/src/nnstreamer-capi-util.c

typo correction in C-Api headers.

[Api] typo correction

---

ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/nnstreamer-cpp.pc.in
ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
ext/nnstreamer/tensor_filter/tensor_filter_cpp.h
meson.build
packaging/nnstreamer.spec
tests/cpp_methods/meson.build
tests/cpp_methods/unittest_cpp_methods.cc
tests/meson.build

With C++ filter, application authors may supply C++ classes as tensor-filters.
They may provide C++ classes as an independent .so files for other application
authors as well.
@TODO: more tests.
@TODO: usage manual

[Filter/C++] Complete implementation of C++ filter.

---

ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
tests/nnstreamer_filter_pytorch/runTest.sh

Enabled setting of accelerators
Enabled getting supported accelerators
See also #1849 

[pytorch] Enable setting accelerators @open sesame 1/15 16:20

---

tests/cpp_methods/meson.build
tests/cpp_methods/unittest_cpp_methods.cc
tests/meson.build
tests/nnstreamer_sink/unittest_sink.cc
tests/unittest_util.c
tests/unittest_util.h

Unit test cases of C++ custom filters
Positive cases: 3
Negative cases: 6

Test/C++-custom-filter: Add unit test cases.

---

gst/nnstreamer/tensor_transform/tensor_transform.c

For caps negotiation, copy tensor info first and update necessary meta.

[Transform] copy tensor-info for negotiation

---

tests/cpp_methods/cppfilter_test.cc
tests/cpp_methods/cppfilter_test.hh
tests/cpp_methods/meson.build
tests/cpp_methods/unittest_cpp_methods.cc

prevent build warning with googletest static library.
1. separate cpp sub-plugin and gtest
2. remove unnecessary dependency in meson

[Test/Cpp] cleanup build script

---

packaging/nnstreamer.spec

[Spec] Minor bug fix in spec

---

api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/api/src/main/jni/nnstreamer-native.h
gst/nnstreamer/nnstreamer_plugin_api.h
gst/nnstreamer/tensor_common.c

1. add new function to get the NNStreamer version string.
2. get nnstreamer version string in Android method.
3. print log about version info when initializing the nnstreamer.

[Common/Android] add version info

---

api/capi/include/nnstreamer-single.h
api/capi/src/nnstreamer-capi-single.c

Codeclean to prepare next ACR, remove unnecessary function definition.

[Api/CodeClean] prepare next acr

---

tests/nnstreamer_decoder_boundingbox/runTest.sh
tests/nnstreamer_filter_pytorch/runTest.sh
tests/nnstreamer_filter_tensorflow_lite/runTest.sh

Naive PR about clean up.
Clean up files created during tests with ssat.

[tests] Clean up files after tests

---

packaging/nnstreamer.spec

Avoid running tests multiple times
More cleanup also added

[spec] spec file cleanup

---

packaging/run_unittests_binaries.sh
tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc

Identify the build failures correctly
This resolves #2081

[build/tizen] Identify build failure correctly

---

gst/nnstreamer/nnstreamer_subplugin.c

We need to hold ALL handles if the pipeline is not closed.
However, after the pipeline is closed, all the handles must be
dlclosed; otherwise, the application may hold unnecessary
resources during the execution.
ps. This is supposed to clean up a Coverity issue as well.
Changes in v2:
Use g_ptr_array instead of garray.
Changes in v3:
Added workaround for dlclose-racing bug of GLIBC 2.23 (Ubuntu 16.04)

Fix: subplugin infra: dlclose & free handles at exit

---

api/capi/include/nnstreamer-capi-private.h
api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-util.c

Add new function to get sub-plugin name and conditions to validate the nnfw is available.
TODO : add condition to check the nnfw availability.

[C-Api] add function to get subplugin name

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSNAP.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
api/android/api/src/main/jni/nnstreamer-native-singleshot.c
api/capi/include/nnstreamer-capi-private.h
api/capi/include/nnstreamer-single.h
api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-util.c
gst/nnstreamer/tensor_filter/tensor_filter_common.c
tests/tizen_capi/unittest_tizen_capi.cc

ACR required.
Add new function to set/get the property of tensor-filter in single-shot.
With this function, we can support the tensor layout in single-shot instance.

[Api/Single] add new function about property

---

ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
ext/nnstreamer/tensor_filter/tensor_filter_cpp.hh

dlclose() should not be called if the target-library's contents may
be refered later.
dlclose() should be called at the exit of a pipeline to avoid
memory leaks of user applications.
Thus, we need to call dlclose for all handles at the ensured exit
point.
ps. I'm going to apply similar fixes for subplugin library as well.

Filter/C++: Fix potential memory leak.

---

ext/nnstreamer/tensor_source/tensor_src_tizensensor.c

Fix info:
CID 1123841 - check the return value of sensor_listener_start
CID 1123966 - g_free the newly allocated memory

[Coverity] fix coverity CID 1123841, 1123966

---

tests/tizen_capi/unittest_tizen_capi.cc

Fix coverity issues caused by resource leak.
CID: 1123663, 1123830, 1123853, 1123860
tests/tizen_capi/unittest_tizen_capi.cc

[Coverity] Fix resource leak

---

gst/nnstreamer/nnstreamer_subplugin.c

add internal function for sub-plugin scan.

[Conf/CodeClean] remove duplicated code

---

api/capi/include/nnstreamer-single.h
api/capi/include/nnstreamer.h

Update API description and prepare release process.

[Api] prepare release process

---

gst/nnstreamer/tensor_aggregator/README.md

Per the request on the usage of "dis-aggregator",
leave a note that it is already supported by aggregator.
Fixes #2101

Aggregator/Doc: add dis-aggregator notes. @open sesame 02/14 15:10

---

gst/nnstreamer/tensor_transform/README.md
gst/nnstreamer/tensor_transform/tensor_transform.c

This PR fills the README.md file for tensor_transform.

[Transform] Submit initial draft of README 

---

tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc
tests/nnstreamer_sink/unittest_sink.cc
tests/tizen_capi/unittest_tizen_capi.cc
tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc

1. init null before getting the file contents.
2. fix mem leak

[Coverity] fix coverity issue

---

tests/tizen_capi/unittest_tizen_capi.cc

change buffer mode in filesink when writing a buffer with small size.

[Test] filesink buffer mode

---

api/android/api/src/main/jni/nnstreamer-native-customfilter.c

add version info to construct custom-filter in android.

[Android] add filter-subplugin version

---

api/capi/include/nnstreamer.h
api/capi/src/nnstreamer-capi-util.c
tests/tizen_capi/unittest_tizen_capi.cc

change enum val for npu-sr, and remove enum npu-srcn.

[Api] hw enum for sr-npu

---

api/android/api/src/main/jni/nnstreamer-native.h
api/capi/include/nnstreamer-capi-private.h
gst/nnstreamer/meson.build
gst/nnstreamer/nnstreamer_log.h
gst/nnstreamer/tensor_common.h
gst/nnstreamer/tensor_filter/tensor_filter_common.c
jni/Android-app.mk
jni/Android-nnstreamer.mk
tests/nnstreamer_filter_reload/tensor_filter_reload_test.c

Add internal header to define common log formats.

[Common] define macro to print logs

---

debian/nnstreamer-dev.install
gst/nnstreamer/meson.build
packaging/nnstreamer.spec

add missed headers to be installed in dev package.

[Build] install headers in dev pkg

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/Pipeline.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/api/src/main/jni/nnstreamer-native-singleshot.c

1. change method name to set/get the property
2. handle empty node name
3. define method to get model file in testcase

[Android] sync to cs-api update

---

tools/development/count_test_cases.py

Count negative test cases of gtest results.
SSAT negative test cases will be counted after SSAT updates.
Addresses #2150
Updates for SSAT will follow soon.

[TestCase] Count negative cases of gtest results

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCustomFilter.java
gst/nnstreamer/nnstreamer_subplugin.c
tests/nnstreamer_sink/unittest_sink.cc

do not allow 'auto' as subplugin name.

[Filter/Sub] preserved name

---

gst/nnstreamer/tensor_source/tensor_src_iio.c
gst/nnstreamer/tensor_source/tensor_src_iio.h
tests/nnstreamer_source/unittest_src_iio.cc

Add properties to set base dir for IIO devices, and update testcases.

[Src/IIO] property to set base dir

---

api/capi/src/nnstreamer-capi-single.c

Add error logs for input tensor size mismatching cases.
Please give me some feedback!
Resolves (partially) : #2127 

[API/Single] Elaborate error logs of ml_single_invoke

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c

Fix the AHUB issue:
WID:16576318 This statement in the source code might be unreachable during program execution.

[AHUB/430155] Remove unreachable code

---

tests/nnstreamer_filter_reload/runTest.sh

The test cases for reload models require the tensor filter extension for Tensorflow Lite. As other test cases do, this patch adds a procedure that checks existence of the tensorflow-lite filters before starting the test.
See also: #2164 

[Tests/Filter/Reload] Check existence of TFLite filters before start

---

api/capi/src/nnstreamer-capi-single.c
tests/tizen_capi/unittest_tizen_capi.cc

update function to set/get the custom property from filter.

[Api/Single] add property key custom

---

api/android/README.md
api/android/api/src/main/jni/Android-nnstreamer.mk
api/android/api/src/main/jni/Android-tensorflow-lite.mk
api/android/api/src/main/jni/Android.mk
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/build-android-lib.sh

1. add flag to disable tf-lite.
2. update build script for each build option.

[Android/Build] clean build script

---

api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/api/src/main/jni/nnstreamer-native-customfilter.c
api/android/api/src/main/jni/nnstreamer-native-pipeline.c
api/android/api/src/main/jni/nnstreamer-native-singleshot.c
api/capi/src/nnstreamer-capi-pipeline.c
api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-tizen.c
api/capi/src/nnstreamer-capi-util.c
api/capi/src/tensor_filter_single.c
ext/nnstreamer/android_source/gstamcsrc.c
ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
ext/nnstreamer/tensor_filter/tensor_filter_python_api.c

Fix coding style

---

Documentation/doxygen-documentation.md

Remove Samsung Proprietary / Confidentail Notice in Document MD.
---
```bash
various …
```

[LF/AI] Remove Samsung Proprietary/Confidential notice

---

Documentation/contributing.md

Update Signed-off-by Section in contributing.md

[LFAI-3] Fix Signed-off-by Section in contributing.md

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c
gst/nnstreamer/tensor_filter/tensor_filter_common.h

Related issue : #2128
Related PR : #2148
When a user sets the framework option to auto, it automatically finds the framework using the file extension.
todo : unittest case will be added.

[Filter] Framework auto detection

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java

Before running the test, check nnfw (tf-lite or snap) is available and test can be run.

[Android/Test] check nnfw availability

---

api/android/build-android-lib.sh
jni/nnstreamer.mk

add filter subplugin-cpp base class in android build.

[Android/Build] add filter cpp suport in android build @open sesame 03/26 16:40

---

gst/nnstreamer/tensor_repo/tensor_reposink.c

Although this PR eliminates the main problem of #2181, it prevents the pipeline from being stuck.
A failure case of the function, gst_tensor_reposink_render_buffer, was not carefully considered. Therefore, the pipeline becomes stuck when gst_tensor_reposink_render_buffer fails. In order to avoid such situation, this patch modifies the function to explicitly return GST_FLOW_ERROR when
a buffer could not be rendered.

[Repo/Sink] Consider a failure case of the render-buffer-function

---

CHANGES

Fix typos and clarify some sentences

[Doc] Fix typo in CHANGES

---

tools/development/README.md

Updates README.md in tools/development to demonstrate newly added tools.
2. Run test: [*]Passed [ ]Failed [  ]Skipped

[Doc] Update tools/development

---

gst/nnstreamer/tensor_filter/tensor_filter.c

Support tensor filter framework v1 callbacks for the pipeline
See also: #2116

[tensor_filter] Support tensor filter framework v1 callbacks for the pipeline @open sesame 3/27 17:13

---

tools/development/count_test_cases.py
tools/development/nnstreamerCodeGenCustomFilter.py

Add `if __name__ == '__main__'` to check if *.py is running on shell to prevent unwanted crash if users happen to import those files to customize tools.

[Tools/dev] Check if *.py is running on shell

---

api/capi/src/nnstreamer-capi-util.c
meson.build
meson_options.txt
nnstreamer.ini.in

Integrate duplicated code for framework auto detection.
1. Build test: [ *]Passed [ ]Failed []Skipped
2. Run test: [ *]Passed [ ]Failed []Skipped

[capi/util] Change framework auto-detection

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestTensorsData.java

Using image classification model (tf-lite), check label with max score.

[Android/Test] add tc to check classification result

---

tests/nnstreamer_filter_mvncsdk2/unittest_filter_mvncsdk2.cc
tests/nnstreamer_plugins/unittest_plugins.cc

Add unittest for tensor-filter framework auto detection.

[Filter] Unit test for tensor filter auto option @open sesame 04/07 13:22

---

api/android/build-android-lib.sh

1. add option to get gst/nns root dir and android sdk path.
2. check instrument test result if test is enabled.
3. prepare ci build.

[Android/Build] option to get sdk path @open sesame 03/27 16:25

---

ext/nnstreamer/tensor_filter/meson.build
meson_options.txt
tools/development/gen_mediapipe_libs.sh

This is a initial version of meson script about mediapipe. It will be used to development mediapipe as an external filter like other filters.

[Mediapipe] add meson option & build script for mediapipe

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
api/android/api/src/main/jni/Android.mk
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/build-android-lib.sh
jni/nnstreamer.mk

Update build script and API to support NNFW.
TODO : fix/update prebuilt libs of NNFW later (now CPU only)

[Android/NNFW] add NNFW

---

api/capi/src/nnstreamer-capi-single.c
api/capi/src/nnstreamer-capi-util.c

The CC value of open-custom function was 21.
Lower it down!
ps. What is cyclomatic complexity: https://en.wikipedia.org/wiki/Cyclomatic_complexity

[CAPI/Single] Lower cyclomatic-complexity

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c

The CC value of the set-property function was 57.
Lower it down!
ps. What is cyclomatic complexity: https://en.wikipedia.org/wiki/Cyclomatic_complexity

[Filter/Common] Lower cyclomatic-complexity

---

gst/nnstreamer/tensor_common.c

The CC value of buffer-sync-collectpad was 23.
Lower it down!
ps. What is cyclomatic complexity: https://en.wikipedia.org/wiki/Cyclomatic_complexity

[Common] Lower cyclomatic-complexity

---

gst/nnstreamer/tensor_converter/tensor_converter.c

The CC value of chain function was 24.
Lower it down!
ps. What is cyclomatic complexity: https://en.wikipedia.org/wiki/Cyclomatic_complexity

[Converter] Lower cyclomatic-complexity

---

tests/tizen_capi/unittest_tizen_capi.cc

Modified to check the state change of each state.
Considering low speed of the arm, I gave more time than it needed.
*This should have been included in the previous PR, but it was not reflected because the modification was late.
1. Build test: [ *]Passed [ ]Failed []Skipped
2. Run test: [ *]Passed [ ]Failed []Skipped

[Tests/CAPI] Add state change check methods

---

gst/nnstreamer/tensor_if/gsttensorif.c
gst/nnstreamer/tensor_if/gsttensorif.h

Anyone can jump in and start the development!
This is for #1703 
ps. I'm going to add test cases before the feature implementation for TDD.

[Tensor-IF] An anchor for further development.

---

api/capi/src/tensor_filter_single.c
gst/nnstreamer/tensor_filter/tensor_filter.c
gst/nnstreamer/tensor_filter/tensor_filter_common.c
gst/nnstreamer/tensor_filter/tensor_filter_common.h

Support tensor filter framework v1 callbacks for the single-shot API
See also: #2116

[tensor_filter] Support tensor filter framework v1 callbacks for single API

---

tests/tizen_capi/unittest_tizen_capi.cc

Test fails occasionally due to slow speed of arm.
The test was modified to only check if the switch is working.

[Tests] Fix tizen capi unit test

---

api/android/build-android-lib.sh

change tf-lite version to 1.13 in android api build.

[Android] tf-lite version

---

api/capi/src/tensor_filter_single.c
gst/nnstreamer/registerer/nnstreamer.c
tests/tizen_capi/unittest_tizen_capi.cc

1. fix ret type of filter callback.
2. minor update (warning w/Wmissing-declarations)

[CodeClean] return type

---

README.md

Add daily build result of each architecture in ofiicial release table

[README] Add daily build result badge in table

---

ext/nnstreamer/tensor_decoder/meson.build
ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
ext/nnstreamer/tensor_decoder/tensordec-pose.c
ext/nnstreamer/tensor_decoder/tensordecutil.c
ext/nnstreamer/tensor_decoder/tensordecutil.h
jni/nnstreamer.mk

Add "utility" internal API to remove
duplicated code.

[Dec/Subplugins] Remove duplicated code

---

tests/nnstreamer_sink/unittest_sink.cc

Don't export internal variables.

[Tests] Add static to internal-global vairables.

---

tests/nnstreamer_repo/runTest.sh

Fix tese case name of nnstreamer repo unit test.
*This PR does not fix test fail.

[TEST] Fix test case name

---

api/capi/src/nnstreamer-capi-pipeline.c

do not call free() when destroying gst-buffer.
TODO : prevent memcpy() when pushing input data into src element.

[C-Api] fix duplicated free

---

gst/nnstreamer/tensor_source/tensor_src_iio.c

1. If g_hash_table_insert returns FALSE,
it simply means that the entry is duplicated.
Just skip it, then.
2. If we cannot parse it, don't change status, but
ignore the whole property values.

[Src-IIO] CHANNEL property handling fix

---

tests/unittest_util.c
tests/unittest_util.h

Add unit test util function that waits for the desired number of buffers to be processed.

[TEST/util] Add unit test util function

---

ext/nnstreamer/tensor_filter/meson.build

set `opencv_path` when system architecture is detected.

[Mediapipe] fix meson script

---

ext/nnstreamer/tensor_filter/tensor_filter_python.cc

A subplugin shouldn't be arrogant enough to assert.
Return errors or throw exceptions instead.

[Filter/Python] Don't assert. Provide exceptions.

---

tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc

1. separate testcase - invalid model and invalid data.
2. fix mem leak, destroy handle before creating new data.

[Test/NNFW] separate testcase

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java

- For both single-shot and pipeline, add simple tests to validate SNAP with tensorflow model
- Test with CPU, DSP, NPU runtime on recent Snapdragon (S20) and preloaded model files

[Android/Test] add SNAP tests using tensorflow model

---

gst/nnstreamer/tensor_merge/gsttensormerge.c

1. fix invalid return value
2. mem-unmap when failed to get mem ptr in input buffer.

[Merge] fix return type

---

debian/nnstreamer-cpp-dev.install
debian/nnstreamer-cpp.install
debian/nnstreamer-dev.install
debian/nnstreamer.install
ext/nnstreamer/tensor_filter/meson.build
ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
gst/nnstreamer/include/meson.build
gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
meson_options.txt
packaging/nnstreamer.spec

This updates edgetpu subplugin as a C++ class to test V1 subplugin API and C++ class as T-F subplugin features.
In the course there are
- (patch0001) The EDGE-TPU C++ (derived) Class
- (patch0002) Enable C++ base class by default
- (patch0003) Spec/Debian update (DIST/packaging)
- (patch0004) C++ base class bugfix.
- (patch0005] Workaround for #2320
Tested with edgetpu, C++ tensor-filter class is ready to be deployed.
Included commits:
commit c4d30225d75fe50d31de0fc703fe81d28e58bc44 (HEAD -> cpp/filter/edgetpu)
Date:   Mon Apr 27 18:29:02 2020 +0900
[Filter/EdgeTPU] Workaround for #2320
Until #2320 is resolved, adding AUTO/DEFAULT to "supported hw"
list makes it easier to use.
commit …

C++ Tensor-Filter Class / EdgeTPU C++ class / Enable C++ TF class by default

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
api/android/api/src/main/jni/Android.mk
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/build-android-lib.sh

Prepare sub-plugin SNPE in android.
- add enum (nnfw type) and build option
- update document for the changes

[Android] prepare SNPE

---

Documentation/nnstreamer_capi.md
api/capi/src/nnstreamer-capi-single.c
tests/nnstreamer_filter_reload/tensor_filter_reload_test.c

1. add sync=false option in model reload test.
2. update pipeline description in docs.

[Test] add sync option in appsink

---

tests/tizen_capi/unittest_tizen_sensor.cc

Add test case for tizen sensor

[TEST] Add test case for tizen sensor

---

ext/nnstreamer/android_source/gstamcsrc.c
ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
ext/nnstreamer/tensor_filter/tensor_filter_openvino.hh
gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
tests/nnstreamer_filter_mvncsdk2/NCSDKTensorFilterTestHelper.cc
tests/nnstreamer_filter_mvncsdk2/NCSDKTensorFilterTestHelper.hh
tests/nnstreamer_filter_openvino/unittest_openvino.cc

[CodeClean] line comment

---

tests/tizen_capi/unittest_tizen_capi.cc

Add more negative test cases to increate test coverage rate.

[Test/CAPI-Util] Add negative cases.

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c
tests/nnstreamer_sink/unittest_sink.cc

update simple testcases for the element properties.

[Test] add tc for element properties

---

tests/nnstreamer_sink/unittest_sink.cc

add test for filter-fw v1 registration without model file.

[Filter/Test] test for filter-fw registration

---

tests/nnstreamer_source/unittest_src_iio.cc

the added testcase covers various cases not covered the previous set.

[Unittest/IIO] add a testcase for unusual cases

---

gst/nnstreamer/tensor_transform/tensor_transform.c
tests/nnstreamer_plugins/unittest_plugins.cc

1. return false if failed to set option.
2. add simple testcases for the option string.

[Transform] return value when failed to set option @open sesame 05/06 15:26

---

packaging/run_unittests_binaries.sh
tests/nnstreamer_filter_python/runTest.sh

This patch modifies the scripts running the test cases for python filters to use proper PYTHONPATH.

[Tests/Python] Update test scripts for python extensions

---

README.md

Add daily build and test badge (Tizen x64, Tizen X86, Ubuntu x64)

[README] Add daily build and test badge @open sesame 05/06 14:54

---

tests/nnstreamer_source/unittest_src_iio.cc

testcase for the logic with:
1. invalid frequency
2. invalid base dir path

[Unittest/IIO] add negative cases - @open sesame 05/06 15:26

---

tests/tizen_capi/unittest_tizen_capi.cc

add testcases for internal function (validate model files)

[Test] add testcases for internal function

---

api/capi/src/nnstreamer-capi-util.c

do not allow setting unknown tensor type.

[C-Api] unknown tensor type

---

ext/nnstreamer/tensor_filter/tensor_filter_mediapipe.cc
tools/development/gen_mediapipe_libs.sh

this subplugin helps running mediapipe graph through nnstreamer

[Mediapipe] upload the new subplugin

---

debian/rules
ext/nnstreamer/tensor_filter/meson.build
gst/nnstreamer/meson.build
gst/nnstreamer/tensor_transform/meson.build
meson.build
meson_options.txt
packaging/nnstreamer.spec
tests/meson.build
tests/nnstreamer_filter_edgetpu/meson.build
tests/nnstreamer_filter_extensions_common/meson.build

This PR is going to resolve #2281 with following implementation plan.
1. Feature / feature handler added
2. Add video support as feature (and wipe out disable-video-support)
3. Implement enable-tesnorflow, enable-tensorflow-lite ... as feature
4. Add extra args support
5. Implement enable-orc, ... as feature (current)
6. Change docs (Left for later PR)
**This PR has an issue:** 
~`-Denable-*` build flags are going to be deprecated. If there is a script using `-Denable-*` flags, those need to be updated. Alternatively, this PR can add backward compatibility but code will be a lot dirtier.~
1. Build test: [ * ]Passed [ ]Failed [ ]Skipped
2. Run test: [ * ]Passed [ ]Failed [ ]Skipped

Meson: Change -Denable-options to features object handler @open sesame 05/06 17:31

---

gst/nnstreamer/nnstreamer_subplugin.h

This patch fixes the typo in header file.

[Subplugin] Fix the typo

---

api/capi/src/nnstreamer-capi-single.c

Existing implementation seeks the tensor filter class based on its type everytime a class to class is needed.
Rather, cache the tensor filter class increasing its ref, and at unref at single api close.

[single] cache tensor filter class once at open @open sesame 5/9 16:48

---

tests/tizen_capi/unittest_tizen_capi.cc

add simple testcases for native c-api and internal functions.

[Test] add simple testcases

---

api/capi/src/nnstreamer-capi-util.c

add function for nnfw auto detection and clean up functions to validate model file.

[C-Api/CodeClean] validate model file

---

meson_options.txt

remove unnecessary option for disabling audio elements.

[Meson/Option] remove unnecessary option

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/main/jni/Android-snpe.mk
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/build-android-lib.sh
api/capi/include/nnstreamer.h
api/capi/src/nnstreamer-capi-util.c
jni/nnstreamer.mk

- Support SNPE for Android api
- Add simple tests (singleshot, pipeline) using pre-loaded SNPE model

[After #2328][Android/snpe] Support SNPE for Android

---

tools/development/gst-indent

This commit is to update the below contents in the 'gst-indent' file.
**Changelog**
* Fixed typo
* Declared a default shell script (e.g., bash) with Linux shebang line
---

indent: Update the gst-indent file

---

api/android/api/src/main/jni/Android-nnstreamer.mk
api/android/api/src/main/jni/Android-snpe-prebuilt.mk
api/android/api/src/main/jni/Android-snpe.mk
api/android/api/src/main/jni/Android-tensorflow-lite.mk
api/android/api/src/main/jni/Android.mk
api/android/build-android-lib.sh
jni/nnstreamer.mk

1. build shared libs (nnstreamer and subplugins)
2. clean up build script
TODO : we need to update mk files in android-res repo and sub-plugins

[Android] build shared libs

---

packaging/nnstreamer.spec

[SPEC] Fix typo in the spec file @open sesame 5/18 18:20

---

api/android/README.md

This PR is a succeeding PR of #2359. 
* Apply original patch of @leemgs
* Update some guides and fix the typoes
* Apply all comments of reviewers

[Android] Updated document for nnstreamer multi-model app v2

---

api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java

fix lint report : set default locale

[Android] fix lint warning

---

api/android/api/src/main/java/org/nnsuite/nnstreamer/CustomFilter.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/Pipeline.java

link proper method, for the interfaces defined in Pipeline/CustomFilter.

[Android/Doc] link proper method

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java

test/sample to input media data format into appsrc.

[Android/Test] sample for media format

---

gst/nnstreamer/tensor_merge/gsttensormerge.c

code clean in tensor-merge element, reduce code complexity.

[Merge] reduce complexity @open sesame 5/28 19:14

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsInfo.java

fix build warning, remove unnecessary code.

[Android] fix warning @open sesame 5/28 18:04

---

ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc
ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
ext/nnstreamer/tensor_filter/tensor_filter_mediapipe.cc
ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
ext/nnstreamer/tensor_filter/tensor_filter_openvino.hh
ext/nnstreamer/tensor_filter/tensor_filter_python.cc
ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
gst/nnstreamer/tensor_filter/tensor_filter_common.c

Update subplugin's accelerators support as per updated rules for auto/default

[subplugins] Update subplugins accl support @open sesame 5/28 20:02

---

gst/nnstreamer/tensor_filter/tensor_filter.c

release in/out mem blocks when failed to invoke nn framework.

[Filter] release mem block when execution failed @open sesame 5/29 14:35

---

api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsData.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsInfo.java
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/api/src/main/jni/nnstreamer-native-customfilter.c
api/android/api/src/main/jni/nnstreamer-native-pipeline.c
api/android/api/src/main/jni/nnstreamer-native-singleshot.c
api/android/api/src/main/jni/nnstreamer-native.h

1. get required method ids to improve performance when initializing the pipe info.
2. add internal method to handle arraylist.

[Android] cache method id @open sesame 5/28 20:00

---

gst/nnstreamer/tensor_filter/tensor_filter_common.c

move a few `g_free()` to fix mem leak

[Filter] fix a tiny mem leak

---

Documentation/component-description.md
README.md

There are a few components completed. Update component list
- Add the new committer
- Add the list of hardware accelerators
- Add daily-release status

Documentation Updates (README, Component List)

---

packaging/nnstreamer.spec

This commit is trivial. It is to keep an indentation consistently.
---

SPEC: fixed indentation

---

ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c

This patch extends tensordec-imagesegment to support snpe-deeplab/depth.
Also, it include minor code refactoring.
CC: @anyj0527 

[Decoder] Extend tensordec-imagesegment to support snpe-deeplab/depth

---

ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c

This commit is trivial. Let's fix typos in the Movidius filter file.
---

Movidius Filter: Fixed typos

---

gst/nnstreamer/tensor_filter/tensor_filter.c

[Fix][Filter/Prop] Fix performance property (latency) for tensor_filter @open sesame 6/8 17:19

---

gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc

This patch adds more catch blocks that return negative error code in cpp_open so that the execution does not go further when it failed to open NN framework.
See also: https://github.com/nnstreamer/nnstreamer/issues/1966#issuecomment-641708718

[Filter/C++] Do not go further when failed to open NN framework

---

gst/nnstreamer/include/nnstreamer_plugin_api_converter.h
gst/nnstreamer/include/tensor_typedef.h

typo correction and fix document for converter sub-plugin api.

[Doc] fix invalid document

---

gst/nnstreamer/tensor_converter/converter-media-info-no-video.h

fix wrong file name in converter header file.

[Doc] fix wrong file name

---

meson.build
tests/meson.build

Resolves #2464
This patch fixes the unknown variable error related to the filter sub-plugins for python 2 and 3.

[Tests/Meson] Fix the unknown variable error related to python filters

---

api/android/README.md

Update document, build options for android library.

[Android/Doc] build options

---

gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c

In the filter custom-easy, prevent error case when developer tries to register custom-filter with local variables.

[Filter/Custom] copy metadata in registration

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc

Replace , with ;
Signed-off-by: junmin-kim <junmindd.kim@samsung.com>

[Filter/tflite] Fix typo

---

ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc

This patch adds a 'dummy' device mode for the test purpose instead of using the dummy shared library that pretends to be libedgetpu.so.

[Filter/EdgeTPU] Add a 'dummy' device mode for the test purpose @open sesame 6/15 11:46

---

tests/nnstreamer_repo_lstm/runTest.sh

applying line change at the complicated pipeline to understand easier.

[Repo/Test] make it easier to understand

---

gst/nnstreamer/tensor_common.h
gst/nnstreamer/tensor_common_pipeline.c
gst/nnstreamer/tensor_merge/gsttensormerge.c
gst/nnstreamer/tensor_merge/gsttensormerge.h
gst/nnstreamer/tensor_mux/gsttensormux.c
gst/nnstreamer/tensor_mux/gsttensormux.h

code clean, prepare new sync-mode.
- remove unnecessary param
- reduce code complexity
- change return val (true to push buffer to src pad)

[Mux/Merge] code clean

---

tests/tizen_capi/unittest_tizen_capi.cc

fix possible mem leak in c-api testcases.

[Test] fix mem leak

---

gst/nnstreamer/tensor_repo/tensor_reposrc.c

[Repo] fix a mem leak

---

tests/nnstreamer_converter/runTest.sh

fix tensor converter unit test

[TEST] Fix Tensor converter test

---

tests/nnstreamer_flatbuf/runTest.sh

Add flatbuffer converter and decoder run test

[Test] Add flatbuffer converter and decoder test

---

api/capi/include/nnstreamer-capi-private.h
api/capi/include/nnstreamer.h
api/capi/src/nnstreamer-capi-pipeline.c
tests/tizen_capi/unittest_tizen_capi.cc

This PR defines new APIs and callbacks for custom filter.

[C-Api] define new API for custom filter @open sesame 7/3 10:41

---

ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc

change to static function to release buffer.

[Filter/TF] code clean  @open sesame 7/3 11:17

---

gst/nnstreamer/tensor_decoder/tensordec.c
tests/nnstreamer_decoder/runTest.sh

Changed to update tensor config dynamically.
Clear private data of subplugin, and init the subplugin.
Related issue : #2492 

[Decoder] Dynamic update of tensor config @open sesame 7/7 16:42

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCustomFilter.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/CustomFilter.java
api/android/api/src/main/jni/nnstreamer-native-api.c
api/android/api/src/main/jni/nnstreamer-native-customfilter.c
api/android/api/src/main/jni/nnstreamer-native.h

Update custom-filter API using custom-easy.
- register custom-filter with in/out info and implement invoke interface only.

[Android] custom-easy filter @open sesame 7/7 15:16

---

packaging/nnstreamer.spec

Fix the install files list.
Separate flatbuf as independent package.

[SPEC] Fix install files list

---

tests/meson.build
tests/nnstreamer_source/unittest_src_iio.cc

Add sleep time unitl state changed within the timeout
Related issue : #2434 

[TEST] Fix iio unit test that fails occasionally

---

api/android/api/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java

Update javadoc
- link to ONE and NNStreamer repo
- add add options for SNPE

[Android/Doc] update doc about nn framework

---

api/capi/src/nnstreamer-capi-util.c

change condition to check restricted element.
tizen sensor-src will be included in restrict list.

[Tizen/Restriction] add sensor-src in restriction

---

gst/nnstreamer/tensor_converter/tensor_converter.c

code clean, function to set/parse media info for each mime type.

[Converter] code clean (parse media info)

---

ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
ext/nnstreamer/tensor_filter/tensor_filter_openvino.hh
gst/nnstreamer/include/meson.build

sam report, remove global val in openvino plugin.
update script to install common header file.

[SAM/CodeClean] remove global val

---

api/capi/src/nnstreamer-capi-single.c

In invoke thread, init status (error-none) before calling the invoke callback.

[Api/Single] init status code before invoking

---

packaging/nnstreamer.spec

* Fix the wrong definition of flat buffer
* Add `nnfw_support` flag to control NNFW even though ARM architecture

[SPEC] Cleanup spec file

---

api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java

edit comment in SingleShot.java
Signed-off-by: Park Hyeoung-Min <phm0127@gmail.com>

edit comment in SingleShot.java

---

Documentation/edge-ai.md
Documentation/products.md
README.md

- Restyle example lists of README.md
- Add "edge-ai" and "products" category

README: update example style and add more examples

---

debian/nnstreamer-flatbuf.install
debian/nnstreamer-protobuf.install

Fix protobuf util lib install path
2. Run test: [ ]Passed [ ]Failed [ *]Skipped

[Debian] Fix protobuf lib install path @open sesame 7/24 10:11 

---

ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
gst/nnstreamer/tensor_sink/tensor_sink.c
tests/tizen_capi/dummy_sensor.c
tests/tizen_capi/dummy_sensor.h

- Remove timestamp in `_create()` and `_fill()` and let BaseSrc do timestamp
- Remove `_get_times()`
- Init debug category
- Add query for latency
- set_interval for tizen sensor_listener
- Add debug log for buffer timestamp in `tensor_sink_render_buffer`

[tizensensor] Fix tensor_src_tizensensor to work properly

---

tests/tizen_capi/unittest_tizen_sensor.cc

Removed some trailing whitespace
Signed-off-by: Tony Jinwoo Ahn <tony.jinwoo.ahn@gmail.com>

[Test] Remove trailing whitespace

---

api/capi/src/nnstreamer-capi-single.c

Do not invoke in a secondary thread, but ivoke in
the primary thread directly without CV so that
there is minimized latencies for single-invoke calls.
This has refactored the invoke-output-process routine.
This follows-up #2551 / CC: @jaeyun-jung 

CAPI/Single: Optimize no-timeout mode run-time performance @open sesame 7/28 13:33

---

api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java

Now C-API allows setting 0 timeout val, change condition to set timeout value.

[Android/Single] allow 0 timeout @open sesame 7/28 13:39

---

.ahub/tcchecker-tca/config.yaml

TCM(Test Case Manager) requires config.yaml file.
The config file is written for android API test.
1. Build test: [ ]Passed [ ]Failed [ *]Skipped
2. Run test: [ ]Passed [ ]Failed [ *]Skipped

[TCM] Add yaml config file for android @open sesame 07/28 15:51

---

api/capi/include/nnstreamer-capi-private.h
ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc

Remove redundant space in source file.

[CodeClean] remove redundant space

---

gst/nnstreamer/include/nnstreamer_plugin_api.h
gst/nnstreamer/tensor_common.c
gst/nnstreamer/tensor_converter/tensor_converter.c
gst/nnstreamer/tensor_converter/tensor_converter.h
tests/common/unittest_common.cc
tests/nnstreamer_plugins/unittest_plugins.cc
tests/nnstreamer_sink/unittest_sink.cc

parse the list of input info (dimension and type), and convert byte-stream to multi tensors.

[Converter] bytes to multi tensors @open sesame 7/15 15:00

---

api/capi/src/nnstreamer-capi-single.c

Add memory leak bug fix
When output ml_tensors_data_h fails to allocate, the already computed output must be freed before return

[single] Memory leak bug fix

---

api/capi/src/nnstreamer-capi-single.c

Remove setup gstTensorMemory in each invoke call
rather, pre-set the tensor memory when input dimensions are set
and re-use that setup tensor memory wrapper each time

[single] Optimize invoke critical path

---

api/capi/include/nnstreamer.h

This patch fixes the public header issue for doxygen, which is requested
by Sunggyu Choi.

[CAPI] Fix the public header issue for doxygen

---

nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c

[example] Fix typo

---

api/capi/include/nnstreamer-single.h
api/capi/include/nnstreamer.h
api/capi/src/nnstreamer-capi-util.c

add line comment and missing dot in api description.

[C-Api] fix typo

---

tests/tizen_capi/unittest_tizen_sensor.cc

- Add negative TCs with invalid sensor, unsupported sensor

[Test/tizensensor] Add unittest for tensor_src_tizensensor

---

packaging/nnstreamer.spec
tests/meson.build

Add packaging of unittests for Tizen distribution

[Dist/Tizen] Package unittests

---

tests/tizen_capi/unittest_tizen_capi.cc
tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc

mark negative cases and add new testcases for single-shot invoke function.

[Test] add test for single-invoke

---

api/capi/src/nnstreamer-capi-pipeline.c

Remove memcopy in input-data API.
If buffer policy is do-not-free, we dont need to set free function when wrapping the memory block.

[C-Api/Src] free function in input data

---

ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c

This patch caches the type for the input and output data tensor
rather than calculating it at every invoke call.

[nnfw] Optimize nnfw invoke

---

nnstreamer_example/custom_example_LSTM/dummy_LSTM.c
nnstreamer_example/custom_example_LSTM/meson.build

Add a macro to copy tensor info

[example] Use macro to copy tensor info
